refined-github/refined-github

.gitattributes
There are two lists-like sections in the readme:
- Highlights
- Related
When there are multiple pull requests adding to the lists whichever is merged first would cause conflicts in the rest.
The union merge cause Git to try to resolve the conflicts automatically by keeping both additions.
Read more here: https://about.gitlab.com/2015/02/10/gitlab-reduced-merge-conflicts-by-90-percent-with-changelog-placeholders/
I think this is also useful for the CSS file where it would be common separate rules to be added to the bottom in different pull requests.
=> Use union merge for readme and CSS

extension/content.css
The uploading of files directly is nice, but the drag-n-drop ability is enough.
This of course could be merged a bit later once it has rolled out and people are familiar the upload feature is available. One could of course say users of this extension would not care about that feature.
=> Hide Upload files button from file navigation in the repo

extension/content.css
This is more specific so it doesn't hide the count of lines added/deleted in the diff on a PR.
=> fix #30 - make hiding markdown helpers more specific

extension/content.css
The last "fix" for the comment boxes was over-specific and missed inline comment boxes.
=> Remove the markdown helper text from inline comment boxes

extension/custom.css
- Hides Clone in Desktop links for both the repo and the wiki.
- Hides Open in Desktop link for files
This is an alternative, more generic version of #37. Closes #37.
=> Hide every github-mac:// link

extension/content.js
Not sure if this was intentionally left like that, just checking.
=> Close bracket of a[href^=/username] selector

extension/content.js
I noticed this when looking at the last PR. (Test with `master` here: https://github.com/sindresorhus/refined-github/pull/41)
There's an error in the console because the test is if there's a container not an author, but we really need to be sure there's an author.
Error:
```
Uncaught TypeError: Cannot read property 'innerHTML' of undefined
```
=> fix error on voting count when there are inline comments

extension/content.css
This is fixes #44 with CSS and no additions to the UI.
The update does the following:
* Hides news feed items for pushing to a branch, deleting a branch, creating a branch. These seem like pretty pointless updates to me, and while they're using the `.simple` class and very small, I never read them.
* Increase the visibility of items relating to a user starring a repo. This is a good discovery tool for me, and it's the main reason I follow another GH user. It should be easier to see.
Here is a screenshot that has a PR, starred repo, and comment in order:
Here is the same section of my feed without the plugin (you can see a pushed commit that was hidden by the extension):
=> Hide some news feed items, increase visibility of starred repos

extension/content.css
This fixes #64 with CSS. The edit README link should not be visible on blobs for MD files, and the links that were visible were bad links anyway. This hides links in those scenarios.
=> Hide edit README links floating over the delete button on blobs

extension/content.js
- GitHub changed some DOM in https://github.com/blog/2123-more-code-review-tools The `.commit-id` is still matching elements on the page, but they are not anchors.
- I have tried changing the selector and making it future proof by checking the href attribute, but actually they have changed links to the commits in a PR as well. They now use `/<source owner>/<source repo>/pull/<PR id>/commits/<commit sha>`.
That said I think we should remove the correct branch links across forks as it produces JS error.
We can restore it if we find another solution.
On top of that the links to a renamed fork are redirect unless there is another repo with the same name so the branch links would work in most cases even without handling the renamed forks case.
=> Remove renamed fork support from branch name links

extension/content.js
This closes #70.
As discussed, this just puts the avatars of the voters in each group underneath the count of votes in either direction. It looks like the avatars under the participants area, and each avatar is wrapped in an link to the user that voted.
=> Add avatars for voters to sidebar

extension/content.css, extension/content.js
Keep the collapse behaviour when clicking file headers using a click handler.
No need for `isCompare()` check anymore.
Simplify other click delegate event a bit using Sprint and keep code-style consistent.
Closes #85
=> Remove minimise/maximise all buttons

extension/content.js
This is a follow-up after #86 to catch cases such as https://github.com/sindresorhus/refined-github/pull/86/files to be a commit view as GitHub now shows just the single commit info there.
=> Consider PR files listing with 1 commit to be a commit view

extension/content.css, extension/content.js, extension/diffheader.js, extension/manifest.json
=> Show current filename in sticky pull request header

extension/content.css
This fixes #113 by hiding the notification when someone forks another repo. :v:
=> Hide notification when a user forks a repo

extension/content.css
- Make input and textarea when writing a commit message monospaced
- Limit input to about 50 chars so you see when you are close to the warning
- Limit textarea to about 80 chars ~~and turn off wrapping~~.
This simulates the behaviour of Vim when writing a Git commit message.
Unfortunately implementing autowrapping like Vim is harder and quite more opinionated.
Before:
After:
=> Make commit message inputs monospaced

extension/content.js
Note: Once #99 goes in, it would make sense to switch out the `prCommit` regex local to this function with the `isPRCommit` regex (the one that will be moving to the URL utils file shortly).
=> Fix broken patch/diff links on commit PRs. Fixes #104

extension/content.css
This fixes #115. Only the Saved Replies button is shown in the comment toolbar now.
=> Show Saved Replies in Comment Toolbar

extension/content.js
This is a fix to close #135.
Checks if there are links and doesn't add them if there are.
=> Fix repeated appending of patch/diff links to commits

extension/content.js, extension/manifest.json, extension/page-detect.js
Closes #120.
In this change I've tried to improve readability and consistency and not focus so much on performance as microoptimisations in these checks are not worth it.
Except for moving the checks to a separate file I've unified them a bit and made some fixes:
- simplified and unified dashboard regular expressions
- made all regex checks nested under a repo consistent
- re-used as much as possible especially for commit checks
- simplified repo root check
- fixed repo root check with `tree` in the regex for repositories like https://github.com/react-component/tree
- tried to use consistent naming and order of the methods
- fixed a few regular expressions not taking trailing slash in the URL into account
=> Move page detection checks to a separate file

extension/content.css
=> Disable zoom cursor for expand/collapse on inline diff comments in PRs (#127)

extension/content.css, extension/diffheader.js
Still needs more discussion based on the conversation in #122, but I wanted to kickstart the work on this.
=> Shrink filename in sticky diff header when its too long. Fixes #122

extension/content.css
This commit pushes the comment options on the right. Refined Github
makes the gitHub interface better by removing useless features and by
organizing in an smarter way the other ones. Before this commit, if you
used an extension on the comment menu it was could be not properly
aligned. By removing the "margin-left" all options are pushed on the
right.
resolves #133
=> Push comment options on the right

extension/content.js, readme.md
I often use the <kbd>tab</kbd> key to move on in github forms. I understand the desire to have it indent text, but I'd really like a workaround. I think allowing the user to enter <kbd>alt</kbd> + <kbd>tab</kbd> to get default behavior is reasonable as long as this doesn't interfere with some other common key binding I'm unfamiliar with. (Totally just tripped up again trying to submit this pull request by hitting <kbd>tab</kbd>...)
Definitely open to other ways to enable this...
=> allow default behavior in textareas

extension/content.js, readme.md
Closes #74.
Closes #161.
Removes the work done in: #17, #39 and #73.
Please discuss whether to do this in #74 where the original discussion is.
I would love @paulmolluzzo and @SpaceK33z to chime in as they implemented this initially.
This of course could wait for #145 and could be followed-up by a comment-combining feature (see https://github.com/sindresorhus/refined-github/issues/74#issuecomment-204128892).
=> Remove thumbs up/down from sidebar

extension/content.css
Fixes #139 
My design skills are *weak*, so let me know if you can think of a better alternative.
=> Fix display of "out of date" and "stale" warnings in sticky header

.travis.yml, Gruntfile.js, deploy.sh, package.json
@sindresorhus This will not work without some steps from you, and as of right not we can't test until it's merged into `master`. I hope you don't mind helping with this PR.
To get this working we need to set some environment variables for Travis CI. You can do this by adding encrypted credentials to the .travis.yml file, or through the Travis CI website. I documented it a bit here https://github.com/paulmolluzzo/test-deploy-chrome
Once that is done, we actually need to have this in `master` because the bash script is going to check that we're on that branch when it runs the script. You can test this outside of `master` by removing the checks in `./deploy.sh`, but you'll want to put them back in so we aren't deploying non-master branches or PRs, which are likely WIP or something.
=> Auto deploy to Chrome Webstore on new git tags

extension/content.js, extension/copy-file.js, extension/manifest.json, extension/page-detect.js, readme.md
Closes #62. There was a caveat to this implementation, however.
The `copy` command with `execCommand` in Chrome will only be set to `enabled` for a *very* brief period of time after a user-triggered event (in this case, a button click). I believe it's 1 second, but didn't end up spending too much more time digging into it. Because of this, I'm fetching the contents of the file prior to click, which means it happens on every page load for single-file pages.
I *think* we may be able to bypass that restriction if we do the `Copy` from a background page and request clipboard permission(s), but I'm not sure that's worth the extra complexity of adding a background page + setting up messaging between background <> content script.
Open to feedback :smile:
=> Add "Copy" button for raw file contents in single file view

extension/content.js
Resolves #140 
I have a sneaking suspicion that, for super active users, showing this on *every* page of the repo may become a bit of a pain. Maybe we limit it to just "List" pages, like the PR list or the issues list, rather than individual issue/PR pages. Would love feedback/input.
=> Show "Recently pushed branches" in more places than just the repo root

extension/reactions-avatars.js
Fixes #178
GitHub added "reacted with ... emoji" which we add to the last username and add an invalid avatar.
/cc @DrewML
=> Fix reaction avatars with changed GitHub copy

extension/content.css
This fixes #176.
The only "bad" thing about this solution is that it doesn't preserver the collapsed state on navigating. I don't think there's a way around it though. I tried switching the class to an `attr` and the issue persisted, so it's something about the DOM being different than expected.
=> Fix narrow diff view on navigation

extension/content.css
This is an alternative to #188 using only CSS and also fixes #184.
One small note about this is that you now see `${user} created ${tag-number} at ${repo}`. I'm not sure how everyone feels about hiding/displaying that. It's possible to hide that too if we want.
=> Show created repository/tag notifications in Dashboard, keep new branch hidden

extension/content.css
Fixes #199. Not sure why this wasn't an issue before tbh.
=> Fix reactions popup below comment content covering button

extension/content.css
The resize handler in the right-bottom didn't work because we force the textarea to be bigger by default.
Fixes #203
=> Fix textarea resizing not working

extension/reactions-avatars.js
I've found myself trying to right click >> "open in new tab" a few times on the avatars that we list in reactions. This PR just wraps the avatar in an `a` tag to enable that.
Note that clicking on the avatar itself still triggers a reaction.
Also removed a few unnecessary calls to `$`.
=> Wrap reaction users avatar with a tag pointing to users profile

extension/content.js
The current behavior conflicts with `OctoEdit`, and it's a bit of a pain.
There is still discussion in #195 about whether we should have this feature in the extension at all. Since that discussion may take a bit, would be nice to get this in for now.
=> Limit indenting of textarea contents to the comment field only

test/page-detect.js
This is currently failing `xo` linting right now, due to this usage of macros + the `ava/test-title` ESLint rule.
[I know that I can assign a function to `urlMatcherMacro.title` and the lint rule won't nag](https://github.com/avajs/eslint-plugin-ava/commit/c2e158c3c351ee81a32b57fd5eccda7b105b67d1), but, for this scenario, that's not really needed.
@sindresorhus @jamestalmage Any suggestions? One thing I considered doing was removing the need to pass in the `detectFn`. Instead, we would use the first string passed in for the dynamic test title + as a key for looking up the `detectFn` on the `pageDetect` object. The snag there was that the first string arg passed to a `test` call gets passed to the `title` fn, but not to the macro itself. I could make the title/method name the _last_ arg to …
=> Re-write test helper as an AVA macro

extension/content.js
linkfied branch refs should be url encoded when having branch names like ``#123-refactor-foo``.
Fixes #246.
=> urlencode linkfied branch refs in PR section

extension/content.css, extension/content.js, extension/manifest.json, extension/show-names.js, readme.md
I made the decision to cache all users real names in `chrome.storage.local`, since I don't think it's super common for people to change their name. Let me know if anyone has any strong opinions here.
So far, I've verified this works in the following places/scenarios:
1. Comments on issues
2. Comments on PRs
3. "Outdated" comments in PRs (after clicking to expand)
4. On partial page nav back/forward
[Here is a good issue to use as a test case](https://github.com/isaacs/github/issues/9). Note the second refresh (after all names load) is much faster. Pretty happy that `chrome.storage` is async, or we'd be having a baddd time.
Note: I did this directly with native DOM APIs, but happy to switch the implementation over to Sprint if desired.
=> Show real names next to usernames in comments. Closes #250

extension/add-blame-parent-links.js, extension/content.js, extension/manifest.json
Fixes #208 
This PR traverses over the DOM in the ``git blame`` table in the UI in order to find all lines affected by a change and adds them as hash URLs. Old ``#L123`` will be removed
=> blame parent links should link to specific line

extension/content.css
Allow other types of file diffs to be hidden, not just ones with tables.
Note: This will set the entire div to `display: none`
Example of a diff that can't be collapsed:
=> Allow collapse of all file diffs

extension/content.js
Fixed #216 
Working on public, non-empty repo:
No home page showing on empty repo:
The only reliable way I could find to do this was to do an HTTP Request. If someone knows a better way, happy to change it.
=> Do not show new PR button on issues/pulls when repo is empty

extension/content.css, extension/content.js
Minor bug I've observed with the branch ref linkifications if the repository has been removed.
This change avoids linkifying a branch if the repository is unknown as this would result in broken links.
=> skip linkifyBranchRefs() if fork has been removed

extension/content.css
This PR fixes the toolbar's top margin.
=> Fix the toolbar top margin

extension/content.css
To ensure the newsfeed is shown even when it’s empty. This keeps the
repository column in place and avoids the following problem for those of us where there's not a lot going on...
=> Add min-height to newsfeed

extension/show-names.js
This is a fix for #268. Thanks to @LoicMahieu for pointing out this bug!
This strips opening/closing `script` tags from usernames. There might be better solution that actually _preserves_ the `script` tag and doesn't let it execute, but I don't know that we care.
Really any time we shove some unknown string into the DOM it should be cleaned in some way, so if we want to do a comprehensive review let's do that.
// @DrewML
=> Fix #268 - safely insert usernames into DOM in showRealNames()

extension/content.css
GitHub is a great free service, I feel bad to hide the only unobtrusive and relevant ad they have. It's there only when you [mark yourself](https://github.com/settings/profile#user_profile_hireable) as "Available for hire"
=> Avoid hiding the jobs ad

extension/content.js, readme.md
This adds an option to the view options for diff pages.
It works with commit pages and pull request diff pages,
and works by modifying the URL (adding `w=1` parameter
to suppress whitespace diff, remove it for resetting).
This targets #191.
Please let me know if you have anything to change / do differently and I’ll try my best to adapt this pull request. Tested it with both, commit and PR pages here with a local extension build.
=> Add option to disable whitespace diff via URL parameter.

extension/content.css
GitHub must've updated the CSS class on the nav.
=> Fix organisation dashboard pagehead nav

extension/content.css
Images are rendered in a `.render-wrapper` instead of a `.data` element
=> Fix minimizing images in pull request diffs

extension/content.css, extension/content.js, extension/manifest.json, extension/mark-unread.js, extension/page-detect.js
This PR fixes #273, but with another approach.
Now there's a "Mark as unread" button in "Notifications" area on pull request and issue pages.
When you mark that issue/PR as unread, extension remembers it and keeps it in storage until that same page is visited again. On notifications page, notifications remembered by the extension look and function exactly the same as "native" ones (first two notifications are created by the extension):
Notifications are stored in `localStorage` under `unreadNotifications` key. Minimum enough info is stored to render a notification in `/notifications` page. When the unread page is visited again, entry with the same URL (`notification.url === location.href`) is removed from the storage, marking that page as "read".
When `/notifications` page is visited, …
=> Add "mark as unread" feature

extension/custom.css
This PR adds [Fira Code](https://github.com/tonsky/FiraCode) to the list of mono-space fonts to enable the use of code ligatures.
Before:
After:
=> custom.css: Add "Fira Code" monospace font-family for code ligatures

extension/copy-file.js
Adds an extra class (`BtnGroup-item`) to the copy button to fix the look.
=> Add missing BtnGroup-item class to copy button

extension/content.css, extension/content.js, readme.md
So, I had deleted my fork when cleaning up some extraneous repositories I had, so this is all of the changes from, and requested in #254.
This will close #280 if/when it is merged.
=> Easier copy-pasting from diffs by making +/- signs unselectable

extension/content.css
Hides the annoying 'Pro Tip! Updating your profile...' box on the personal profile page (appears whenever your name isn't set)
=> [CSS] Hide `new-user-avatar-cta` protip box

extension/content.js
This fixes #298.
I changed the method of making the fork path to use an `attr` found in the DOM that has the fork's user and repo name. It seems like this is appropriate for creating the path to the settings for the fork, and the existing tests (not the original repo, is merged, etc.) remained intact.
=> Fix delete fork button for merged PRs

extension/custom.css
Since Operator Mono is a $200 font, I think it being installed is much more likely to indicate that it's preferred by the user. Thoughts?
=> Move Operator Mono to top of font stack

extension/custom.css
The button was moved inside a combined download/clone popup. Hiding it in there now just leaves empty space inside a button that says "**Clone** or download"
Current:
After this PR:
=> Restore Open in Desktop button

extension/content.js
The dropdown/button has a fixed width, so the branch title/slug is sometimes shortened to fit, and an ellipsis is added at the end. This change reads the current branch name from the button’s `title` attribute instead, where it’s not affected by the visual space limitations.
=> Current branch = [shortened] inner text -> button title

extension/content.css
Fixes #362 
The solution differs from what I suggested initially because that didn't take into consideration this little guy  <img width="30" alt="add reaction button" src="https://cloud.githubusercontent.com/assets/1402241/23577773/f47cbeb0-007c-11e7-9a35-ab9d33e617a3.png">
The long selector is a [Quantity Query](https://alistapart.com/article/quantity-queries-for-css). It can be done via JS but I promised it would be CSS-only
=> Limit reaction avatars when there are too many

extension/content.js, extension/reactions-avatars.js
Today I noticed the release counter looks weird. It turns out that GitHub has for some reason capitalized the class name responsible for applying proper styling for this element.
**Before changes:**
**After changes:**
=> Fix releases counter class name

extension/custom.css
Some Operator Mono users install the ScreenSmart variant, sometimes exclusively (due to what license they bought), so it would be nice to have the relevant font name in the overridden code font family.
Here goes.
=> Leverage Operator Mono ScreenSmart variant

extension/content.js, extension/linkify-urls-in-code.js, extension/manifest.json, extension/page-detect.js, readme.md, test/linkify-urls-in-code.js
Closes #380 
This linkifies numbered issues (i.e. `#123`) and URLs found in code comments. You can take a look at this page to see it in action: https://github.com/contao/core/blob/549738f9a41974d963bd09a3a83ae0f46f887f01/system/modules/core/pages/PageForward.php#L51
In that page there is a URL and there are a few issues linked.
Should work on any page with code, so a PR with inline comments works: https://github.com/sindresorhus/refined-github/pull/346
The files on a PR: https://github.com/sindresorhus/refined-github/pull/346/files
And the code for individual files/commits: https://github.com/sindresorhus/refined-github/commit/2d0c354b66556cd15ac9f1fc5f775a313f026f96#diff-0730bb7c2e8f9ea2438b52e419dd86c9
// @Loilo
=> Linkify URLs and issues in code comments

extension/content.js
Fixes #387 and changes the label tooltip if it is the logged in user to match GitHub's own tooltip messages.
=> Improve OP labels

.gitattributes
Currently if you checkout the code on Windows the JS files will have CRLF and will automatically fail in ESLint when running 'npm test'
=> Force JS files to checkout as LF

extension/content.js
I have some Gist's with many files and I get lost quite often.
=> Add support for gist.github.com in the diff file collapse feature

extension/linkify-urls-in-code.js
Fix #390.
The issue was we weren't adding the right `class` to the linkified URLs. This issue would have presented itself anywhere we linkify a URL and navigate via a `pjax` route.
I fixed the issue and pulled the common class and `attr`s out since it's repeated in a bunch of places.
=> Fix issue where linkified URLs were re-added

extension/content.js
Fixes #377. ~Definitely not the nicest solution to re-run the function on scroll, but I can't think of any other solution.~ ~Also not sure how to handle https://github.com/sindresorhus/refined-github/issues/377#issuecomment-296781677~
=> Make "diff copy" feature work with lazy-loaded diffs

extension/content.js, readme.md
Fixes #389
This adds a new search filter on issues/PR pages with the text of
'Everything commented by you' with the filter of 'is:open
commenter:<username>'
=> Add search filter for "Everything commented by you"

extension/content.js
This fixes issue #400. Currently if you visit the compare page,
https://github.com/sindresorhus/refined-github/compare/ you'll get a JS
error because the element list has no items.
=> Create observer only if we have elements to observe

extension/content.js
GHE uses a class of 'counter' instead of 'Counter'
Fixes #418
=> Fix Project tab displaying on GHE with 0 Projects

extension/mark-unread.js
Seems like GitHub changed some class names 😜
As a result of this **state** field ended up undefined.
Have updated those class names.
Here's screenshot of the fixed issue
Fixes #424
=> Fix unread "undefined" icon

extension/content.css, extension/content.js
This would prevent linking to deleted branches when wrapping head and base branches on pull request pages with links.
- Fixes #105
- Fixes #349 by using the canonical name from the title in the DOM with owner, repo name and branch
Things which this would not do or take into account, because it's not worth it:
- If a branch is deleted and subsequently restorted, it would not link to it
- If the base branch of a PR is deleted or renamed, it would still link to it
=> Do not link to deleted branches

extension/mark-unread.js
Unread notification count doesn't include local notifications
Add both the count and display it in the unread notification count.
Right now I don't have any unread github notification. So not able to test it. 
Please check that too :)
Fixes #427
=> Fix "Unread" count on notification page

extension/content.js, readme.md
=> Use pull request title for squash and merge commit message

extension/mark-unread.js
"Mark all as read" button does not clear notifications that were added using extention
Clear localStorage.unreadNotifications when button is clicked.
Fixes #291
=> Fix "Mark all as read" button for local notifications

extension/content.css, extension/content.js, extension/mark-unread.js
Unread indicator on the bell icon is displayed only for github notification. Not the local notifications that we have bookmarked.
Include local notifications too
Not sure I've covered all the use cases. If I've missed something, please let me know 😄 
Fixes #292
=> Show "Unread" indicator for local notifications

extension/custom.css
Fixes https://github.com/sindresorhus/refined-github/issues/433
Now when the Insights tab drop down holds Graphs and Pulse we can stop hiding Pulse.
=> Bring back Pulse tab

extension/content.css
Styling for created repos in dashboard. (Make it look like stared repos)
I tried to avoid overriding other styles (#215)
Not sure if it still has any side effects / covers all use cases.
Please let me know if I've missed anything :)
Fixes (#213)
=> Fix created repo style

extension/manifest.json
Those domains are implied since they appear in `content_scripts.matches`
=> Remove duplicate permissions

extension/show-names.js
`console.error` is bound in the latest versions of Chrome and Firefox, no need to wrap it or bind it.
=> Skip wrapper for console.error()

extension/content.js, extension/manifest.json, extension/vendor/element-ready.js
Issue before this PR: the Trending link is added on domready, which happens after the first paint.
This change can probably be applied to more jumpy parts at some point, but this is the most visible on every page.
=> Avoid jump when adding Trending link

extension/content.css, extension/content.js, extension/page-detect.js, readme.md, test/page-detect.js
Add a 'Yours' menu tab to the top navigation. This does a Github search
for all open items created by yourself, which includes PRs and Issues.
Fixes #183 
Shortcut is 'g y' and appears after Issues in the menu.
=> Add `Yours` issue/PR search tab

extension/content.js
Creating the `div` beforehand doesn't seem to be necessary. jQuery handles the `include-fragment` fine.
=> Let jQuery do innerHTML once

extension/content.js, extension/copy-file-path.js, extension/copy-file.js, extension/copy-gist.js, extension/copy-on-y.js, extension/diffheader.js, extension/linkify-urls-in-code.js, extension/mark-unread.js, extension/page-detect.js, extension/reactions-avatars.js, extension/util.js
The easiest part was merging sequential selections like `$('a').find('span')` that most of the time were better written as `$('a span')`.
`$()` selects multiple elements but RG often only needs one element. Sometimes we forget that vanilla DOM methods are less awkward than `$('a')[0]` or even `$('a').toArray()[1]`
Since `document.querySelector` is a mouthful I was going to use a local `select()` function, but then I ended up saving it as `utils.el`.
Also often `$(selector).length > 0` was used to detect the existence of an element. I initially replaced it with `utils.el(selector)` but thought it'd be more explicit as `utils.exists(selector)`
Wherever `$()` was dropped in these places, I also switched to plain DOM APIs; e.g. `.textContent` instead of `.text()`
---
I avoided these changes …
=> Faster selections (big PR)

extension/background.js, extension/content.js, extension/manifest.json, extension/options/index.css, extension/options/index.html, extension/options/index.js, extension/vendor/webext-dynamic-content-scripts.js
Fixes #315 
New domains can be specified in GH's options view, which can also help #193, should that ever materialize.
To test this without access to GHE:
1. remove all the permissions to `github.com` in `manifest.json`
42. disable and re-enable the extension (don't just reload it)
369. Verify the permissions, `github.com` should not be there
9001. Add `https://github.com` via the form
=> Add support for GitHub Enterprise

extension/content.js
This fixes #322.
TL;DR: Github changed the markup from a select optionbox
to a tablist. This change re-implements the whitespace
diff toggle option as third tab-item on diff view pages.
=> Fix whitespace diff option button

package.json, src/content.js, src/libs/copy-file-path.js, src/libs/copy-file.js, src/libs/copy-gist.js, src/libs/copy-on-y.js, src/libs/diffheader.js, src/libs/linkify-urls-in-code.js, src/libs/mark-unread.js, src/libs/page-detect.js, src/libs/util.js
As requested in https://github.com/sindresorhus/refined-github/commit/c5103b6df8b786335d42997cee7844192e535050#commitcomment-22414772
Do you like `select.exists()` or do you prefer keeping it as `exists()` with the following?
```js
import select, {exists} from 'select-dom';
```
=> Use bfred-it/select-dom@4.1's .exist() method

src/libs/show-names.js
Closes #489 
Since Firefox doesn't seem to allow `fetch`ing relative URLs (even though it's in their own [docs](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch)), we now use an absolute URL.
=> Fix real names not being fetched in Firefox

src/libs/show-names.js
This fixes a small bug where showing the full name of an edited issue/PR post would show a stray dash at the end like:
> WanderMax commented 5 hours ago • edited by arkon Eugene Cheung -
See https://github.com/kabouzeid/Phonograph/issues/195 for an example.
=> Fix text formatting for name of post editor

extension/content.css, src/content.js
The space mentioned by #317 is:
Replaces #453
=> Simplify removeDiffSigns

extension/manifest.json, src/content.js, src/libs/auto-load-more-news.js, src/libs/on-feed-update.js
- Automatically start loading new content if the button is visible, without scrolling
- Keep loading new content until the button is no longer visible
- If GH's JS was slow to load, clicking the button would trigger a full-page reload because of the non-ajax form submission. _No more!_
Fixes #256
~~Firefox 55+ because of IntersectionObserver. It'll land in September, IIRC.~~ Edit: semi-ponyfill added.
Demo (using [GitHub Clean Feed](https://github.com/bfred-it/github-clean-feed) to hide most content)
=> Load more news until the screen is full

src/content.js, src/libs/domify.js
* shorten selectors
* avoid unnecessary operations
* skip jQuery
* get user content out of innerHTML (XSS)
* various code shortcuts
Tested on the pages:
* base branch: https://github.com/sindresorhus/refined-github
* custom branch: https://github.com/sindresorhus/refined-github/tree/badges
* long branch name: https://github.com/bfred-it/sandbox/tree/what-do-you-think-the-maximum-branch-name-length-is-question-mark-i-think-there's-no-limit-so-i'm-just-gonna-keep-going-until-github-throws-up-or-i-get-tired-of-typing-nonsense-omg-why-are-you-still-reading
* 1-level deep readme: https://github.com/GhostText/GhostText/tree/master/browser
* multi-level deep readme: https://github.com/babel/babel/tree/7.0/packages/babel-cli
* commit view (no edits allowed): …
=> Optimize addReadmeButtons

src/content.js
Related to #423
The previous selector matched both the button that shows the rebase form and the confirming rebase button. Try on this PR:
```js
document.querySelectorAll('.btn-group-squash button[type=submit]')
```
This means that the title was being reset ALSO after pressing the confirm button. This discarded any changes to the title in the form... right **after** I confirmed them. Oops.
I saw that @sindresorhus changes the title and then merges the PR. That shouldn't be the only (roundabout) way to name merge commits.
---
I replaced jQuery with select to ensure that only one element will ever be selected.
=> Allow customization of the rebase title

readme.md
In https://github.com/sindresorhus/refined-github/pull/465, the link to `content.js` broke as it moved. This commit changes the path to point to its new location under `/src/`.
=> Update readme.md link to content.js

src/content.js
The build wraps jQuery and `select` into an IIFE, hiding it from the console. This makes it harder to debug some code by copying and pasting it in the console.
=> Add window.$ and window.select to simplify debugging

extension/content.css, src/content.js
This is an attempt to solve https://github.com/sindresorhus/refined-github/issues/549
I tried doing it with jQuery but [you do notice the jump](https://github.com/sindresorhus/refined-github/issues/549#issuecomment-311532819) from visible to hidden.
The only thing I could come up with in css is a rule to hide the empty message.
The problem here is that it hides the message even for admins, so it's a little weird after the change:
Here we can see that the UI is much cleaner after the change:
=> Hide repo description when it's empty

src/libs/show-names.js
Per #493 update Real Name styling to have the name wrapped in ()
This adds (Real Name) behind all author links. Including:
- edited by: user (Real Name)
- user (Real Name) added <Label>
- user (Real Name) referenced this <item>
This does cause wrapping of the header sometimes, examples can be
seen here: #461 and #546. Not sure how we can avoid that though, open to suggestions.
Comment edited by @bfred-it to test the *edited by* part.
---
Fixes #493
=> Update real name styling

src/content.js
=> Ensure single initialization

extension/content.css, src/content.js
Fixes #557
I made sure that the position of the +/- stayed the same (Chrome, OSX, retina), try it on your computer.
=> Fix expanded diffs alignment

package.json, src/libs/copy-markdown.js, test/copy-markdown.js
Mostly fixes #522. There's only [one left](https://github.com/sindresorhus/refined-github/issues/522#issuecomment-310547556) and that's hard to fix.
Edit: **Automated tests have been [added](https://github.com/sindresorhus/refined-github/pull/546/commits/75ad7c36a28fdc7827ee67e32c95a923f227e168) ⚡️**
✅ Drop `g-emoji` elements: 🔥🔥🔥
✅ Drop tasks from lists
✅ Drop autolinks around images: ![](https://camo.githubusercontent.com/7a0ef30dc39981585543e0bbd816392a52dddd8a/687474703a2f2f692e696d6775722e636f6d2f4b6361644c36472e706e67)
✅ Keep `<img>` if it has width, height or align: <img align="center" width="32" alt="copy" src="https://camo.githubusercontent.com/7a0ef30dc39981585543e0bbd816392a52dddd8a/687474703a2f2f692e696d6775722e636f6d2f4b6361644c36472e706e67">
✅ Unwrap commit/issue autolinks: …
=> Markdown copy improvements

readme.md
Fixes #518
Suggestions welcome for ordering and section naming. The idea was to make a screenshot gallery instead of having a list, like often seen for apps:
But some items are not easily capturable and many are very small changes.
---
<details><summary>screenshot holder, ignore</summary>I told you to ignore me. Why don't you listen? 😠😁
=> Group features by type in readme

src/libs/linkify-urls-in-code.js
Bug example: https://github.com/treycordova/nativejsx/issues/26
Notice the w3.org URLs: the first one is linkified, the second one isn't, because TreeWalker completely drops out when the first element is replaced. Not sure why it worked elsewhere but not here.
=> Fix linkifyURLs bug in some code

src/libs/show-names.js
Fix issue where initial retrieval of `cachedNames` returns an empty object which is considered to have a property with the same name
=> Fix problem with initial retrieval of `cachedNames`

src/libs/domify.js, src/libs/show-names.js
`document.createRange().createContextualFragment` helps in creating a document fragment by parsing HTML but additionally loads resources linked from the HTML.
This is solved by using the HTML `template` tag.
=> Prevent domify from making unnecessary network requests

readme.md, src/content.js, src/libs/page-detect.js
The default sorting of milestones in github is pretty frustrating. Milestones are used to manage releases; where as the closest one is often more important than the last updated one.
This PR fixes the default sorting, so they are sorted by closest due date, instead of recently updated.
=> Sort milestones by closest due date

extension/content.css, src/content.js, src/libs/op-labels.js
Ok. This is ready and tested.
Test it here:
- Emoji titler: 👍 should have a `title`
- `addDiffViewWithoutWhitespaceOption`: visit https://github.com/sindresorhus/refined-github/pull/586/files?w=1, notice the working **No Whitespace** button (which, btw, is broken on master since the JSX switch)
- `addFilterCommentsByYou`: go to https://github.com/vadimdemedes/dom-chef/issues and click Filters
- Cancel comment prompt: leave a review on this PR, but change your mind
- `cacheReleasesCount`: visit an [obscure repo's Releases page](https://github.com/bfred-it/supports-webp/releases), then visit the Code tab, then notice the number in the Releases tab
- `addOPLabels`: see my next comment
=> Spring cleaning

src/content.js
1. I think GitHub recently stopped using the `recently-touched-branches-wrapper` class we were testing for.
2. I think we can avoid parsing the DOM for unrelated elements and just look for the specific element in the string.
Extracted from #586
=> Fix recently pushed branches duplication

extension/content.css
tab-size only ever applies to `pre`-like areas, so this uniformly applies it on every code area.
=> Apply tab-size to everything

extension/content.css, src/content.js, src/libs/copy-file-path.js, src/libs/utils.js
- The copy path button doesn't appear in small PRs like https://github.com/sindresorhus/refined-github/pull/571/files
- The button's style is unusual and misaligned: 
* The button appears in small PRs like that one
* The style and position now matches now matches GitHub's own Copy path button in [file view](https://github.com/sindresorhus/refined-github/blob/master/.npmrc)
* The button uses GitHub's own copy path code
* The function is much lighter (204 loops vs 740 on  [this 204-files PR](https://github.com/bfred-it/sandbox/pull/13/files) for example)
=> Change copy-path style and show on small PRs

.travis.yml
Related to #595 
I'm not 100% sure that this condition works (although it seems to work locally) but it should:
* Only deploy on cronjobs
* Only deploy if there was a commit in the last 26 hours
**26 hours** should help with Travis' cronjob irregularities. It might occasionally let some commits be deployed again, but at least it shouldn't *miss* any commits.
Next steps:
1. [add daily cronjob](https://travis-ci.org/sindresorhus/refined-github/settings) + 24 hour option.
2. Perhaps change the version from `y.m.d.hmm` to `y.m.dhh` since we don't expect this to be deployed more than once per hour, even if an urgent version should be let in.
=> Only deploy on cron

extension/content.css, src/content.js, src/libs/utils.js
Fixes #612 
Manual tests:
- #601 alignment on Windows/Linux:
https://github.com/dunst-project/dunst/commit/717c747a8caf0f823da0e4e45bbb632ef46c68ee
- #590 indentation of ajax-loaded diffs:
https://github.com/rob3n/yard-frontend/pull/4/files (scroll all the way down)
- #557 indentation of expanded code:
https://github.com/npmhub/npmhub/pull/63/files?diff=unified (click to expand collapsed code)
- https://github.com/sindresorhus/refined-github/pull/607#issuecomment-314142245 indentation of whatever regression
[sindresorhus/eslint-plugin-unicorn/pull/99/files#diff](https://github.com/sindresorhus/eslint-plugin-unicorn/pull/99/files#diff-2d660eee44e5e1d2a779ac70f6ad47a6R22)
- https://github.com/sindresorhus/refined-github/pull/607#issuecomment-314150451 no spaces added *inside* the line: …
=> Fix diff indentation

package.json, webpack.config.js
* Drop process shim: 6KB (4%)
* Optimize code via babili: 18KB (12%)
This is almost minimization but the code remains readable because mangling and  `simplify` are disabled.
You can see the diff of the resulting `content.js` by checking out:
```
https://gist.github.com/afa017a7c81dd5f5eeefc963593088b4.git
```
=> Lighter bundle

package.json
Uses cross-env like it was used before by Windows user @jgierer12 in https://github.com/sindresorhus/refined-github/commit/ffe599b8ba16a7276e51e941a17d0d10cbfafda2
Drops an unnecessary ENV since it does not change the output size.
=> Restore cross-OS build compatibility

src/content.js
This page was also matched (and it failed): https://github.com/sindresorhus/refined-github/blob/master/readme.md
=> Only add the Edit/Tag buttons on repo pages

extension/content.css, package.json, src/content.js
Last piece to be JSX-ified. Was blocked by https://github.com/vadimdemedes/dom-chef/pull/8 which caused the `viewBox` to be ignored, which caused the icons to stay at their original 16px size.
Testable on: https://github.com/babel/babel/commits/7.0
=> JSX+clean: markMergeCommitsInList

src/content.js
Fixes #245 
The only inconvenience with `Tab multiple lines at a time` is that the you'll have to press cmd+z as many times as the lines that have been indented. I can't find a way to make it atomic.
=> Comment field tabbing improvements

extension/content.css, src/content.js
> If a branch is deleted and subsequently restored, it would not link to it
> @hkdobrev in #422 
* Fixes the above
* Cleans up the function
* Fixes the below (title not showing on `user deleted the xxx branch` event)
=> Link to restored branches

src/libs/copy-markdown.js
Fixes #635 
Untested. Will be running this for a while but I think we can merge it preventively if it doesn't break anything itself.
=> Don't break 'copy' if copy-markdown fails

package.json, src/libs/mark-unread.js, src/libs/synchronous-storage.js
`mark-unread` is the only piece that uses localStorage, which I just realized it's shared across all extensions enabled on github.com and can end up being fuller than we expect.
This PR moves `mark-unread` to `chrome.storage.local` and, while at it, it tries the promised `browser.*` polyfill by Mozilla as mentioned in #495
There's one minor issue though: `chrome.storage.local` is async and `mark-unread` makes a lot of synchronous queries to the storage. I thought of just using `async`/`await` but that meant that literally almost every function would have to be `async` and therefore `await`ed. It got messy quickly.
An _ok_ alternative solution was to provide a local asynchronous cache that responded synchronously: `SynchronousStorage`. I tried to keep it as small as possible. API …
=> Move mark-unread to browser.storage.local

extension/content.css, src/content.js
And tested locally on Chrome.
Restoring the following features :
- A menu item "Trending now appears after "Marketplace" and before "Gist".
- Pressing g and t will now make the browser navigate to the trending page
Fix bug #638 for feature #153 .
=> Fix Trending menu item and "g + t" shortcut disappearance and hide Marketplace menu item

extension/content.css
Transparent avatars:
> <img width="127" alt="hole-y avatars" src="https://user-images.githubusercontent.com/1402241/28609344-e3a0aae6-7216-11e7-8ee4-39eff44d3b43.png" valign=middle>  <-- before this PR
As seen on this comment: https://github.com/sindresorhus/refined-github/pull/571#issuecomment-313707428
Avatars' gray placeholders appear before they load:
> ![](https://user-images.githubusercontent.com/1402241/28609365-f6643698-7216-11e7-88bc-bee2e2e69672.gif)
Testable on https://github.com/babel/babel/pull/3646
=> Improve avatar style during loading and for transparent avatars

extension/content.css, src/libs/reactions-avatars.js, src/libs/utils.js
Fixes #240
Testable on https://github.com/babel/babel/pull/3646
> <img width="708" alt="more than 3 avatars" src="https://user-images.githubusercontent.com/1402241/28608582-667e7726-7213-11e7-9729-e0b33779ff0b.png">
Still limited and compressed when they don't fit:
> <img width="715" alt="lots of avatars" src="https://user-images.githubusercontent.com/1402241/28608590-75819c30-7213-11e7-9af9-f9b00a91d2ee.png">
Since this is now in JS, _limited_ avatars won't be loaded at all (contrary to what happened before)
=> Show more than three Avatars for Reactions

src/libs/domify.js
This behavior is unused and undesired.
What does ` <i>a</i>` return?
1 el
What does ` <i>a</i><i>a</i>` return?
frag with 3 nodes
Now it always returns a frag.
=> Cleanup: Remove unused domify uncertainty

package.json, webpack.config.js
Source maps increase the first build time by 300ms, but a rebuild only takes 300ms in `watch` mode (which I hope you're using when checking out PRs and working on the extension)
Seeing the real source code makes sense when debugging stuff. No one wants to read webpack's output.
The only issue is that it doubles the extension's zip since currently the `.js.map` files are included — but perhaps seeing the source _in production_ is good and it doesn't affect the JS files' loading time.
=> Always use source maps

package.json, webpack.config.js
- Lets us skip the extra babel-cli step.
- Enables **full** source map output (otherwise not available because of
babel/babel#3940)
- Which means we can have full source maps after the minification.
- Which means that we get the real code even when debugging a published
version.
- Which means that we can minify the JS fully and just submit the source
maps to Mozilla Addons (if they accept them, let's try with a beautified version first)
[In a few weeks](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/pull/63#issuecomment-313283672), when they have tested out uglify-es, this will become part of webpack core and we can drop the dependency.
=> Uglify all the things

src/content.js
During a pull-request review, when going through individual commits, maintain the whitespace option when using the "Previous" and "Next" buttons ("p" and "n" shortcuts, respectively) to navigate between commits.
Closes #660.
=> Maintain whitespace option on previous/next navigation.

extension/manifest.json, readme.md, src/libs/auto-load-more-news.js
- [Firefox 55 was released on Aug 8](https://www.mozilla.org/en-US/firefox/55.0/releasenotes/)
- Min version is specified, so old 54 users will just not get the new version until they upgrade
- We've been stuck in mozilla queue for 2 weeks anyway, we'll probably have to wait longer.
=> Drop Firefox 54 support

extension/content.css
Isn't this cute?
We can distinguish between new notifications and threads marked as unread. 
- Green: only threads marked as unread
- Blue: real notifications (and maybe the above)
The gradient comes straight from GH's buttons.
=> Change "Mark as unread" indicator to green

extension/content.css
The bug was here: https://github.com/pulls
=> Fix /pulls view after label reordering

src/content.js
When a user clicks on the "details" link to view a CI build instead of taking you away from GitHub, it just opens the CI build information in a new browser tab.
=> Make CI links in a pull request open in a new tab

src/content.js, src/libs/preview-issues.js
**Feature Request**
I often find myself hovering on the issues number for so long just to preview the title of the issues. I think it will be nice if the titles are going to be shown on tooltips as soon as I hover on them. Like demonstrated below.
It uses the default style of the tooltip of Github. I also remove the `title` attribute as soon as the tooltip is loaded to avoid duplicated informations, not sure whether it is a good idea though.
Hope this could be landed, Many thanks 😉 .
=> Add preview issue/PR title tooltip in comment

src/content.js
Currently the promise is getting cancelled as we never find a match for the selector, resulting in most of the extension being broken. This adds some duplicate classes, but they have no impact on github.com from what I see in the DOM.
=> Fix Trending menu item on GHE

src/libs/page-detect.js, test/page-detect.js
Currently we're trying to add releases on the trending page, update the `isRepo` check to account for
the `/trending/X` URLs.
This error is from https://github.com/trending/developers
```js
add-releases-tab.js:42 Uncaught (in promise) TypeError: Cannot read property 'insertAdjacentElement' of null
at add_releases_tab (add-releases-tab.js:42)
at github_injection_default (content.js:594)
at gitHubInjection (index.js:23)
at onDomReady (content.js:591)
at <anonymous>
```
=> Fix JS error on Trending sub pages

extension/content.css
Fix #713
This PR will
* fix account-switcher margin-bottom on dashboard discover repository.
* compatibility with dashboard, since you can't find class `.page-dashboard` on Github dashboard discover repository page.
=> Remove .page-dashboard as parent class css

extension/content.css
The low z-index made some text appear on top of the header bar...
Before:
After:
=> Bump z-index of sticky file headers

src/content.js
Highlight Trending link when on the Trending page and subpages and
remove highlighting from Explore when on Trending pages.
Fixes issue #705
=> Highlight Trending link correctly

src/content.js
Fixes #723 .
Remove the selector for `.title` in descendants of `.watch_starred` or `.fork`. We can assume the presence of `a[href^="/${username}"]` anywhere in the descendants is enough to assume it is a star/fork of the user's repo.
=> Fix selector for hiding other users starring/forking your repos

extension/content.css
I don't know what the selectors for deleting branches and adding someone as a collab is though since I couldn't find any in my news feed.
=> Fix selector for hiding pushes and forks

src/libs/icons.js
The compare icon only has a width of 13 in the dropdown, where as the other icons have 16. This makes it 16 to align with the others.
Found here: https://github.com/sindresorhus/refined-github/pull/739#issuecomment-337668957
=> Resize Compare icon to be consistent

readme.md, src/content.js
Closes #312.
Use `ctrl/cmd-shift-enter` as a shortcut to enter a single comment instead of starting a review.
Also close a comment when `esc` is pressed in a non-empty comment since the extension shows a confirmation dialog in that case.
Questions:
* Would the `if/else` be better as a `switch`?
* Does it matter that `ctrl or cmd-shift-enter` triggers this on Mac, and `ctrl or Windows-shift-enter` works on Windows?  I could look at `navigator.platform` to limit it to `ctrl` on Windows and `cmd` on Mac.
=> Add keyboard shortcut for adding a single comment

src/content.js, src/libs/copy-file.js, src/libs/op-labels.js
Just replacing the wordy API with shorter equivalent ones that have been available for about 6 browser releases.
=> .insertAdjacentElement -> .after/.before

src/libs/page-detect.js, test/page-detect.js
Currently only `/notifications*` is treated as a notifications page, but we also want the same "Mark all as read" and "Open all in tabs" options for other notifications pages, for example `/sindresorhus/refined-github/notifications*`. So we need to match `*/notifications*`.
Continuation of https://github.com/sindresorhus/refined-github/issues/701
See https://github.com/sindresorhus/refined-github/issues/701#issuecomment-331732397
>If you only want to open notifications from a specific repo, you can just select it from the list on the left and then click `Open all in tabs` there:
>
><img width="1010" alt="image" src="https://user-images.githubusercontent.com/15943089/30785822-bf33e34e-a164-11e7-8496-9a1e0e7fe65e.png">
=> Treat all notifications pages as notifications

extension/content.css
This hides the upload bar only when it's in its default state and shows it during the upload and on various errors.
=> Show upload messages

src/content.js
Fixes #774
Auto merging this after Travis because it was a previously unnecessary change.
=> Move onDomReady after duplicate load check

src/content.js, src/libs/page-detect.js, src/libs/remove-diff-signs.js
Fixes #765 
I manually ran the tests described in https://github.com/sindresorhus/refined-github/pull/613
Bug example:
https://github.com/sindresorhus/refined-github/blob/bacb4bcc7aaa7a0052b0b623d1b2fa794b03e339/.gitignore#L1
> Screenshot
> <img width="205" alt="bug" src="https://user-images.githubusercontent.com/1402241/32050771-a5c5ebca-ba17-11e7-9ca2-495ae334ff3c.png">
Edit: life would be easier if we had [`ode_modules`](https://www.vocabulary.com/dictionary/ode) instead of `node_modules`
=> Avoid running removeDiffSigns on every table

extension/content.css
GitHub's modals have an invisible layer which lets you _click anywhere to close._ This is invisible, which means that if you open a dropdown and then scroll it out of the view you will lose your first click and won't even know why.
- Global: Top right, **profile** dropdown
- Repo: **Watch/Unwatch** dropdown
- Repo: **More** dropdown
- PRs: Files changed: **Review** button dropdown
- PRs: **change PR base** dropdown
- Issues: sidebar **reviewers/labels** dropdowns
- Issues: new comment: **Insert a reply** dropdown
- Issues list: **author/labels/milestones** filters
- Issues list: **filter** button near search box
- Homepage: **organization** dropdown
- Own profile: **contribution settings** + **jump to** dropdown
- Commits list: **verified** commits dropdown
=> Make modal backdrop visible

extension/content.css, src/content.js, src/libs/add-releases-tab.js, src/libs/icons.js, src/libs/more-dropdown.js
After https://github.com/sindresorhus/refined-github/pull/739 the dropdown creation was getting lengthy. It made sense to merge all the related code.
Current output unchanged:
=> Unify reponav-dropdown creation

src/content.js
This PR **completely disables** RG when the user is not logged into their GitHub account.
Discussed in [#756 (comment)](https://github.com/sindresorhus/refined-github/issues/756#issuecomment-340210256).
* Fixes #756 
* Fixes regression left out by #592 ([comment](https://github.com/sindresorhus/refined-github/pull/592/#issuecomment-314098650))
/cc @bfred-it @sindresorhus
=> [rev] Don't do anything when not logged into GitHub

src/libs/mark-unread.js
This code was supposed to only be temporary to allow migration of old data. But now it's been a few months already, it's safe to remove it.
=> Remove storage migration from mark-unread

src/content.js, src/features/add-confirmation-to-comment-cancellation.js, src/features/add-delete-fork-link.js, src/features/add-diff-view-without-whitespace-option.js, src/features/add-filter-comments-by-you.js, src/features/add-keyboard-shortcuts-to-comment-fields.js, src/features/add-milestone-navigation.js, src/features/add-patch-diff-links.js, src/features/add-profile-hotkey.js, src/features/add-project-new-link.js, src/features/add-readme-buttons.js, src/features/add-title-to-emojis.js, src/features/add-trending-menu-item.js, src/features/add-yours-menu-item.js, src/features/fix-squash-and-merge-title.js, src/features/focus-confirmation-buttons.js, src/features/hide-empty-meta.js, src/features/hide-own-stars.js, src/features/linkify-branch-refs.js, src/features/linkify-issues-in-titles.js, src/features/mark-merge-commits-in-list.js, src/features/move-account-switcher-to-sidebar.js, src/features/move-marketplace-link-to-profile-dropdown.js, src/features/open-ci-details-in-new-tab.js, src/features/preserve-whitespace-option-in-nav.js, src/features/remove-projects-tab.js, src/features/show-recently-pushed-branches.js, src/features/sort-milestones-by-closest-due-date.js
As discussed in: https://github.com/sindresorhus/refined-github/pull/784#discussion_r147628508
> Move it to its own file? Would be nice to eventually reduce content.js to just be a router/delegator.
> I also think we should create a separate directory for the features. Now they're mixed with utils, icons, domify, etc.
This first PR only extracts `content.js` functions. Another PR will move whatever doesn't belong to `libs` out of there as well (because there are conflicting open PRs)
=> Extract all features from content.js

webpack.config.js
Tabs are changed to 4 spaces by UglifyJS. This brings it back to 1 space
164KB -> 119KB
=> Reduce the bundles by 28% with one weird trick

extension/content.css
Visible on retina displays. I hoped GH would fix it, but here we are. Before and after:
=> Fix subpixel rendering Chrome bug in tooltips' triangles

package.json, src/content.js
Most new logging appears in the background page. Here's the logging added to the deps:
https://github.com/bfred-it/webext-content-script-ping/commit/4b8ac2c050dcc7e1e1f0d133b079d246410a5c5b
https://github.com/bfred-it/webext-dynamic-content-scripts/commit/1c0473220ad0179c5ab4f6125b73f8b7785cb63e
The sooner this appears in the store, the quicker we can solve that long-standing issue.
=> Added temporary logging and instructions to fix #565

src/features/add-trending-menu-item.js, src/features/linkify-branch-refs.js, src/features/move-account-switcher-to-sidebar.js, src/libs/page-detect.js, src/libs/utils.js, test/page-detect.js
Fixes #783 again
I decided to put the check in `getRepoPath` because this function kinda implies that it only gets a repo's path, not blindly get whatever happens to be 2 dirs deep.
=> Improve repo page detection across the board

extension/content.css, readme.md, src/content.js, src/features/add-ci-link.js
Notes:
* disregard tooltip position, it'll be removed by #799 
* needs mention in the readme once accepted
Testable pages:
* https://github.com/sindresorhus/refined-github (Travis only)
* https://github.com/Microsoft/vscode (multiple)
* https://github.com/bfred-it-obsolete/empty (no ci)
Fixes #726
=> Add build status and link to CI next to the repo's title

extension/content.css
GitHub apparantly has changed the dashboard switcher `button` element to a `summary` element.
**Before:**
**After:**
This is just a quick PR as this a change from the GitHub's side, it is still unknown that may also have broken RG somewhere else.
=> Fix account-switcher broken by GitHub

package.json, src/content.js
Fixes #565
* RGH already includes the latest prerelease of the dependency.
* This PR merely points to the next major version of the dependency
* RGH v17.11.9.1725 was published as a last verification that this works
Next steps for me:
1. Wait for possible bug reports in #565 for the next few days
2. Publish `webext-dynamic-content-scripts@3.0.0`
3. Merge this PR
=> Fix duplicate content script injection

src/content.js, src/features/add-ci-link.js, src/features/linkify-branch-refs.js, src/features/mark-unread.js, src/features/move-account-switcher-to-sidebar.js, src/features/show-names.js, src/features/show-recently-pushed-branches.js, src/libs/api.js
As requested in https://github.com/sindresorhus/refined-github/pull/800#discussion_r149753499
All were changed except:
```js
src/libs/synchronous-storage.js:
28  		this._get = get;
29  		this._set = set;
30: 		return get().then(value => {
31  			this._cache = value;
32  			return this;
```
-> because It's inside a constructor.
```js
src/libs/utils.js:
30  
31  	// Don't check ad-infinitum
32: 	domLoaded.then(() => requestAnimationFrame(() => waiting.cancel()));
33  
34  	// If cancelled, return null like a regular select() would
```
-> because it's not meant to be awaited.
=> Change all .then to await

src/content.css
GitHub recently pushed changes that altered the previous layout. This PR fixes the issue.
Before:
After:
=> Match context switcher's width to the width of the containers below it

src/content.css
The actual centering of the ▲ (relative to the button) varies in GitHub's own interface, so I avoided manually fixing each instance of the popup.
=> Fix reactions popups position issues

package.json, src/background.js, src/libs/utils.js, src/manifest.json, src/options.html, src/options.js
This lets the user enable Enterprise support in 2/3 clicks, without having to copy paste URLs. The _After_ screenshot could be used in the readme as instructions.
I plan to extract this feature into its own npm module so it can be easily shared across extensions that require the same functionality (i.e. enable content scripts on multiple hosts) so they have a common interface.
=> Move GHE domain dialog to Browser Action

src/content.css
GitHub replaced their old JS-based dropdown with `summary+details`. So here are some necessary changes.
I wasn't able to restore the show-popup-on-hover for whatever reason. `opacity !important` is ignored and it stays 0.
It might need to be implemented via JS (`mouseenter -> trigger click`). Let's merge these visual fixes for now and then open an issue to restore the feature.
=> Fix Reactions issues

source/features/add-diff-view-without-whitespace-option.js
https://github.com/sindresorhus/refined-github/commit/d10510f660d4e1393ad01af097f97de36ced680c
This feature is meant to remove `Changes from` from PR files view, but it doesn't exist in regular commit diffs.
=> Whitespace toggle: Only remove extra copy if it exists

source/features/add-keyboard-shortcuts-to-comment-fields.js
`return false` in jQuery event handlers means `preventDefault` + `stopImmediatePropagation`
In this case, only `preventDefault` or nothing at all was needed.
<kbd>tab</kbd> bug example:
Bug caused by #832
=> Restore tab behavior in comment areas

source/libs/page-detect.js
The switcher will now render correctly on the [Discover repositories](https://github.com/dashboard/discover) page.
=> Fix account switcher on Discover page - fixes #857

source/content.css
Closes #779
@bfred-it Like this?
=> Remove Specific Toolbar items

source/content.css, source/content.js, source/features/reactions-avatars.js, source/libs/page-detect.js, test/page-detect.js
I found out today the reaction avatars were not working for the recently launched ”Discussions” feature on GitHub. Unfortunately I do not have a live public example to link directly to test it, however I attach some screenshots before and after the change.
**Before:**
**After:**
=> Enable reaction avatars for teams' discussions

source/features/embed-gist-inline.js
Partial solution to #870 
Limit is **11.5** lines to avoid giving the impression that it's _only_ 12 lines.
Example from https://github.com/WhisperSystems/Signal-Desktop/issues/1884
=> Limit gists embeds to 11.5 lines

source/features/embed-gist-inline.js
Related to #870 
The stylesheet for the embed loads after the first content paint, so the Flash Of Unstyled Content overflows and overlaps until that completes. This PR avoid the overflow and makes it look decent during the FUOC.
=> Improve gist embed FOUC style while loading

source/features/add-keyboard-shortcuts-to-comment-fields.js
**Affected feature:** <kbd>tab</kbd> to indent
**Problem:** when indenting multiple lines, it needed just as many <kbd>cmd</kbd>+<kbd>u</kbd> to undo them.
**Solution:** use `insertText` once
**Why:** less wear of <kbd>cmd</kbd> and <kbd>u</kbd> keys and left-hand ligaments.
=> Keep comment tab undoes to 1 keypress

source/features/reactions-avatars.js
Currently in order to see who has reacted on GitHub, you have to either know which avatar belongs to who, or check the link’s preview in Chrome in the bottom left corner. Why not exposing it as the link’s title, so it would be visible when hovering over the avatar? ;)
=> Add participant username as title to reactions avatars

webpack.config.js
Some npm package we depend on can at any time start expecting a property on `process` to exists and then break. The `process` polyfill is pretty small anyway.
=> Don't exclude the `process` object

readme.md, source/content.css, source/content.js, source/features/add-quick-review-buttons.js
Related to #883 
Test it on #886 
**One issue:** <kbd>cmd</kbd>+<kbd>enter</kbd> will submit the form correctly when there's only one button (**Comment**), but currently fails when there is more than one button. What should we do in that case? 
- 👉 Default to **Comment** (if a different action was meant, just submit a new comment-less review)
_**Edit:** I picked this one because GitHub also defaults to "comment", as you can see in the first screenshot_
- ~~Disable <kbd>cmd</kbd>+<kbd>enter</kbd>~~
=> Add quick review buttons

source/content.js
The extra `''` is to interrupt the bold style on the second `%c`
=> Add logged out notice

source/content.js, source/features/add-jump-to-bottom-link.js, source/libs/page-detect.js, test/page-detect.js
Today I stumbled upon a bug related to the ”Jump to bottom” feature introduced in #904. Whenever a user keep changing between tabs in the PR view, the link had been added multiple times even if it had already existed in the DOM.
Preview of the behaviour: [a GIF file](https://user-images.githubusercontent.com/11782/34378469-3de83d9a-eaf6-11e7-8417-5ecf486f04d9.gif)
=> Only show 'Jump to bottom' link on PR Conversation tab

source/options.html
=> Show Firefox mis-support only in Firefox' options

source/options.html
Context: https://github.com/sindresorhus/refined-github/pull/546#issuecomment-313748489
At the bottom:
It looks long but #924 helps shorten the page also
=> Add related extensions to options

source/options.css, source/options.html
Firefox styles are now only applied there. Chrome has a better style without them.
A minor annoyance is the two extra `<link>`s and their loading errors in Chrome. But I prefer that to having/updating an extensive Firefox style _in-house_
=> Meta: Improve Options style in Firefox (and Chrome)

source/content.css
Demo gifs containing before and after
We could arguably also hide "build finished/failed" messages, but perhaps [some bots include good info.](https://github.com/siddharthkp/bundlesize)
=> Hide PR summary duplicate info

source/content.css
Fixes #936, removes old selectors and adds comments to existing ones
=> Restore tooltips for reaction avatars

source/features/auto-load-more-news.js
=> Check if `newsfeedObserver` is set before referencing it

source/content.js, source/features/linkify-urls-in-code.js, source/features/shorten-links.js
Fixes #938 
Reproduce:
1. Visit https://github.com/drlogout/caddy-proxy
2. Click the "Issues" tab
3. Press the browser's back button
=> Don't shorten URLs in markdown code blocks

source/features/show-names.js
Currently, Refined GitHub fetches the name of the user with the same username when it encounters a feed entry by a GitHub app bot.
*Refined GitHub displays the name of [the user `stale`](https://github.com/stale) although [`stale` is a GitHub app](https://github.com/apps/stale).*
*Refined GitHub no longer displays the name.*
=> Don't show names for GitHub apps

source/content.css
I've had this in my Stylus stylesheet for a while now and think that it greatly improves readability of comments with deletions. Color is the same as quotes. Feel free to close if you don't like it.
Before | After
--- | ---
=> Lighten deletions in markdown

source/features/add-keyboard-shortcuts-to-comment-fields.js
This pull request addresses two issues by adding new shortcuts to comment fields.
When the user is inside an **empty** comment field and presses <kbd>Esc</kbd> the comment field will be unfocussed/"blurred".
*Closes #848*
When the user is inside the "Leave a comment" field at the bottom of issues and presses <kbd>Up</kbd> while the field is **empty**, Refined GitHub will `.click()` the edit button of the last comment by the user and put the caret at the end of the input field.
*Closes #858*
=> Add more comment field shortcuts

readme.md, source/content.css, source/content.js, source/features/diff-expand.js, source/features/extend-diff-expander.js
Allow the entire expandable line to be clicked to see more lines, rather than just the expander button in the left margin. Includes hover style to match the button.
Closes #547
=> Extend diff expander (see more lines) button

source/content.js, source/features/make-discussion-sidebar-sticky.js
Implements the functionality suggested by @bfred-it in #842.
> Perhaps it can just be done the old way: `if it fits, make it sticky` (repeat on resize)
*Closes #842*
=> Make discussion sidebar sticky

source/content.css
Fixes #967.
I’m not sure whether there is a nicer way, however it seems to do the job.
=> Strengthen selector to target the common footer

source/features/linkify-branch-refs.js
=> Escape branch name in linkify-branch-refs

source/content.css, source/features/mark-unread.js
In PRs and Issues,  the button was placed in a ajaxed area, meaning that it would get removed by GitHub when new comments were loaded via ajax.
This moves it out but it doesn't change its visual position.
=> Preserve Mark Unread button on ajax updates

source/content.css
=> Recently-pushed branches: Don't cover repo tabs

source/content.css
I always ping team members for a certain project, but sometimes I don't know what members are in a specific team (and if I have/want to ping other persons too), so I'd like to activate tooltips for team mentions.
=> Allow tooltips for team mentions

source/features/add-delete-fork-link.js
Undo #805 
> The link only appears if you can edit the **current** repo, which doesn't make much sense
> https://github.com/sindresorhus/refined-github/issues/1001#issuecomment-358294572
=> Remove incorrect Delete Fork condition

source/features/add-your-repositories-link-to-profile-dropdown.js
Currently GHE does not have the wrapping `<li>` on the `<a>` resulting in a null returned from the current selector.
This solution is not super elegant, but will allow GHE to just work once it's updated to the same markup as GH is using.
=> Fix 'Your Repository' link on GHE

source/libs/utils.js
Quick fix for #1010 using default values while destructuring.
Can someone think of a better way of retreving options from browser storage `¯\_(ツ)_/¯`?
/cc @sindresorhus @bfred-it @hkdobrev @busches
=> Fix empty options while destructuring

source/content.css
It's a no-brainer. Browsers decided that `<details>` don't trigger `cursor: pointer` for whatever reason.
=> Change cursor to pointer when hovering <details>

source/content.css
Magic fixes #919 
This has a couple side effects:
- code: occasionally causing a flicker when clicking the line numbers
- md: causing the "link" icon to be invisibly 45px taller (i.e. 45px above it are invisibly clickable)
=> Avoid file header overlap when loading linked lines

source/features/linkify-urls-in-code.js
Fixes #999.
Just updated a CSS selector to match diff tables inside discussions.
Test on [saglacio/saglac.io#143 (commit-diff)](https://github.com/saglacio/saglac.io/pull/143/files/e92bf806d0a0757da2b16623172fa3041e65db36#diff-aeb42283af8ef8e9da40ededd3ae2ab2), and https://github.com/saglacio/saglac.io/pull/143#pullrequestreview-76120305
=> Fix issue where URLs in commented diffs aren't linkified

package.json
Not sure if this is wanted, but I made a package to generate the versions using the same scheme that you are using and I'd thought I'd share.
There is a subtle difference which I _think_ is a bug/unintended in the current approach. The `date` command will generate versions were the last part will have leading zeros between 00.00 and 00.59, my package will not.
e.g.
```sh
$ date -u +%y.%-m.%-d.%-H%M
18.1.22.001
$ utc-version
18.1.22.1
```
This will also work on Windows, I'm not sure that `date` does...
Cheers 👋
=> Use utc-version to generate manifest version

source/content.css
=> Avoid file header overlap when loading linked *multiple* lines

source/features/mark-unread.js
=> Correctly group buttons in Mark as Unread feature

source/content.css
Set the header z-index above the main body content so that the drop-down backdrop on the header will be displayed above the body content.
fixes #994
fixes #1038
=> Fix dropdowns backdrop z-index issues

source/features/add-download-folder-button.js, source/features/remove-upload-files-button.js, source/libs/page-detect.js, test/page-detect.js
The repo root already has an official Download ZIP button.
`isRepoTree` initially excluded the main repo page, but still included the root non-default branches, like: https://github.com/webpack/webpack/tree/TheLarkInn-patch-1
Also it changes the `isRepoTree` test.
=> Hide download folder button on repo root

source/content.css
Something like #922, but without deduplication (that'd require JS)
I personally found the hover card to be more annoying than useful so this might be a compromise between showing large cards for all and showing some info unobtrusively.
=> Show more info on dashboard without hover

source/features/add-jump-to-bottom-link.js, source/features/mark-unread.js
Fixes #987
Fixes https://github.com/sindresorhus/refined-github/issues/987#issuecomment-359037251
Test:
1. Visit an issue or PR
2. Leave a comment, close the issue/PR, or wait for others' comments to flow in
3. "Jump to bottom" link and "mark as unread" button disappear from header and sidebar
=> Re-add missing RGH buttons when issue page updates

readme.md
\+ drop deployment badge
Now that we have <img width="42" alt="" src="https://user-images.githubusercontent.com/1402241/36077002-1e334e16-0f97-11e8-97a2-b43d63c99604.png"> I don't see the need for badges anymore
One-click demo: https://github.com/sindresorhus/refined-github/tree/readme-badges#-refined-github
=> Meta: move badges away from title

readme.md, source/content.css, source/content.js, source/features/extend-issue-status-label.js
- adds reference to PR/commit that closed the current issue/PR
- clicking the label will scroll to the event
- clicking the reference will visit it
- I ended up leaving it red (@hkdobrev will love this) because this can also appear on RED PRs that are closed by _other_ merged PRs
- Sadly this has to wait for the whole discussion to load, which might be a few seconds later on long discussions.
https://github.com/bfred-it/github-issue-link-status/issues/2 (closed by commit)
https://github.com/sindresorhus/refined-github/issues/479 (closed by pr, then closed manually)
https://github.com/sindresorhus/refined-github/issues/565 (closed by a commit, then by a pr)
https://github.com/sindresorhus/refined-github/issues/233 (closed by pr, reopened)
Example PR: …
=> Show issue resolution in header

source/content.css
Also, a cool trick:
```js
document.body.insertAdjacentHTML('beforeend', `
<style>
.tooltipped::before,
.tooltipped::after {
opacity: 1;
display: inline-block;
text-decoration: none;
}
</style>
`);
```
=> Hide some file-related tooltips

source/content.css
I saw today the diff signs were a little off in the PR files view. This PR fixes this behaviour (see the attached screenshot).
Live example: https://github.com/sindresorhus/refined-github/pull/1108/files
=> Fix diff signs' positioning

readme.md, source/content.css, source/content.js, source/features/add-diff-view-without-whitespace-option.js, source/features/add-keyboard-shortcuts-to-comment-fields.js, source/features/add-profile-hotkey.js, source/features/add-releases-tab.js, source/features/add-shortcut-help.js, source/features/add-trending-menu-item.js, source/features/improve-shortcut-help.js, source/libs/page-detect.js, test/page-detect.js
An attempt to improve the shortcut help that can be opened by pressing <kbd>?</kbd>.
* All shortcut groups are now shown.
* Relevant shortcut groups have a higher opacity.
* "Projects"-related groups are removed entirely unless the user is on a projects page.
* Refined GitHub shortcuts are included (which closes #579) and marked with a small purple circle.
* `<kbd>` tags containing multiple keys are split up for consistency.
---
There's a little API for other features to register their shortcuts:
```js
import {registerShortcut} from './improve-shortcut-help';
const group = 'site';
const hotkey = 'g t';
const description = 'Go to Trending';
registerShortcut(group, hotkey, description);
```
* `group`: the [ID of the group](https://github.com/shroudedcode/refined-github/blob/ee2cc184a59548a63 …
=> Improve shortcut help

source/features/add-branch-buttons.js
Too much noise?
<a href="https://github.com/babel/babel/"><img width="368" alt="always visible tag" src="https://user-images.githubusercontent.com/1402241/36968396-f9115420-2094-11e8-8bd6-ddc1748a891d.png"></a>
Test on: https://github.com/babel/babel/
=> Show latest tag in `latest release button`

readme.md, source/content.js, source/features/toggle-all-things-with-alt.js
This feature was only working on PR pages (files changed tab or pr commit), but not when opening a specific commit outside a PR.
=> Enable toggleAllThingsWithAlt on all commits

source/content.css
Setting `opacity` on `table-list-cell` for merge commits had a negative effect on the build statuses overlay (see the attached screens).
**Before:**
**After:**
In addition I fixed some tiny issues in the CSS file which I spotted when running `npm test` locally.
Live test case: https://github.com/Microsoft/TypeScript/commits/master
=> Fix opacity for merge commits

source/content.js, source/features/linkify-branch-refs.js, source/libs/utils.js
- The `name` parameter was only used in one case. I'm dropping it
- Dropped a couple of unnecessary comments
- Show feature name when outputting errors (whether logging is enabled or not)
=> Meta: enableFeature improvements

source/content.css
Seems like this is needed only for Chrome and [Firefox works without this change](https://user-images.githubusercontent.com/10276208/37541612-370acbae-2981-11e8-83e7-92eacfeca392.png)
Fixes #1176
=> Fix user full names with accents

source/content.js
```
> xo && stylelint source/*.css
source/content.js
...
⚠  162:1  Function ajaxedPagesHandler has a complexity of 30.  complexity
...
3 warnings
43 passed
```
This does nothing and nothing can be done about it except moving the filters inside each feature, which is something I've been doing [in some features.](https://github.com/sindresorhus/refined-github/blob/master/source/content.js#L162-L168) Being just a bunch of function calls and `if`s it's not really complex.
=> Meta: stop marking ajaxedPagesHandler as complex

source/content.css
=> Fix z-index for showing "open pull request" shortcut

source/features/add-branch-buttons.js
Changes:
- The caching of the default branch was site-wide instead of repo-wide. Oops.
- We can't know the default branch on forks, so the button won't appear there anymore. https://github.com/sindresorhus/refined-github/pull/1115#issuecomment-371908428 https://github.com/sindresorhus/refined-github/pull/1132#issuecomment-372924429
- Sometimes we know the branch, but we don't have a link to it. https://github.com/sindresorhus/refined-github/issues/1160
Follows #1115 
Replaces #1132 (more context there)
=> Fix default branch buttons in some cases

source/features/add-patch-diff-links.js
Fixes and closes #1080 (again!).
Test links:
* https://github.com/sindresorhus/refined-github/commit/09041df0cba07b115bd0de437540bda271e6efb7
* https://github.com/sindresorhus/refined-github/pull/1119/commits/0f51dfe30eb36e60369a188786d88b6e421f1543
=> Fix adding patch and diff links to commit pages

package.json, source/content.css, source/content.js, source/features/display-issue-suggestions.js, source/libs/api.js, test/searchable-words.js
*A basic implementation of the feature suggested by @fenollp in #1138.*
When the title input field on the `New Issue` page is blurred, an API request is made to fetch issues on the repository with the title as the query. The first five issues are then displayed in the sidebar.
If there are more than five, an *X more results* link that links to the regular issue search is added below.
Currently, the search is really basic. While StackOverflow's suggestions get more accurate as you enter more text, this search only looks for issues that contain the text in the title which is not the best way to determine whether an issue is relevant. Please let me know if you have any ideas on how the search could be improved.
=> Display possibly related issues on the 'New Issue' page

source/content.css
Resets `top-margin` to `0px` for the CI icon.
Before:
After:
---
Closes #1221
=> Fix alignment of ci icon

source/content.css
Hides the tooltip on the following buttons:
Keeps the tooltip on the expand / collapse glyph since it contains a helpful tip:
---
Closes #1212
=> Hide overlapping tooltips

package.json, source/content.css
Less of a feature, more of a community service. This only appears to who left the comment.
Feature annoyance rating: 🔥🔥🔥💦💦
=> Privately remind users not to leave :+1: and :-1: as comments

source/content.css, source/features/more-dropdown.js, source/libs/icons.js
Fixes #1269 
Not tested on GHE. @Naramsim can you try this branch?
Style matches the native one as well:
And it should look like this on GHE (mockup):
=> Use native reponav dropdown if available

source/features/display-issue-suggestions.js
This pull request fixes the issue where suggestions would be displayed with an empty title.
Now, the user must enter a **minimum of 3 characters** in order to generate suggestions. Also if the user **clears** the title field leaves **less than 3 characters**, the suggestion box is removed.
=> Avoid showing related issues when the issue title is empty

source/features/close-out-of-view-modals.js
Added an if check to avoid calling `.click()` with a `null` value.
=> Prevent console error in `close-out-of-view-modals`

source/content.css
I noticed that the issue labels were quite big. After looking into the code, I discovered that the current CSS selector doesn't seem to be valid any longer. GitHub has renamed the `label` class to `IssueLabel` both on pull requests and issues.
I could also change it to `.js-issue-row .label, .js-issue-row .IssueLabel {` to be backwards-compatible (think maybe older GitHub enterprise versions?).
=> Correct issue label CSS class

source/features/add-keyboard-shortcuts-to-comment-fields.js
Fixes #1252.
* Don't do **anything** if the selector box is open (separated this so that it may possibly useful for #1003)
* Add support for hiding "edit comment" box
* On 'Escape', if there is a cancel button then close the view, else blur the field
=> Fix keyboard shortcuts on comment fields

readme.md, source/content.css
This PR makes the bar the contains `labels / milestones / assign` at the top of the issues listing sticky on scroll.
This is super useful when you want to manipulate multiple issues at once, you can check issues and scroll down the list with available options and total selected remaining in view.
One selected issue is off screen, but sticky bar makes it clear that this is the case.
=> 📌Sticky Issues Header

source/content.css
Apologies, missed this when testing the feature as my repository did not have a scrollable list of labels.
closes https://github.com/sindresorhus/refined-github/issues/1317
=> Addresses unable to scroll label list

source/content.css
The sticky table-header-bar is obscuring the PR filter list:
=> Fixed PR filters popup being obscured

package.json, source/features/add-branch-buttons.js, source/libs/compare-versions.js, test/compare-versions.js
Fixes #1291
Tested on problematic repos:
- https://github.com/trello/navi (version has only 2 parts)
- https://github.com/live-clones/recalbox (a part has a leading zero)
- https://github.com/fsprojects/FSharp.Interop.Dynamic (version has 4 parts)
- https://github.com/mrdoob/three.js (version has one part and starts with `r`)
- https://github.com/sindresorhus/refined-github (not a real version, just the latest tag)
Possible trouble: betas might not be detected/sorted properly
Bonus: RGH loses 40KB 🙂 (`semver` package was heavy)
=> Support non-semver versions

source/features/open-all-notifications.js
Addresses https://github.com/sindresorhus/refined-github/pull/1306#issuecomment-389518788
And avoids the ajax calls caused by clicking the "Mark all as read" buttons instead of just replacing the class.
=> Hide "used" buttons in notifications

readme.md, source/content.js, source/features/add-create-release-shortcut.js, source/features/add-releases-tab.js, source/libs/page-detect.js, test/page-detect.js
Closes #1254.
Registering the shortcut in a non-existent section didn't work though. Perhaps we could separately think how to handle that in the `registerShortcut` function.
=> Create a release shortcut

source/content.js, source/features/fix-squash-and-merge-message.js
It's related to #423 , which uses the PR title as the squash commit title.
This PR introduces a new feature, which uses the PR description as the squash commit body message.
The change is in contrast to the default github behavior, that is, compiling a list of individual commit messages before the squash.
Fixes #1322
=> Use the pull request message as the commit message when merging with `Squash and merge`

source/features/add-quick-review-buttons.js
I've been using refined-github for some time and I'm loving it so far!
I found an issue with review buttons. Due to how it currently works, it's possible to accidentally double click a button which will lead to double submission (or however many times you manage to click it until the page reloads):
This PR adds locking to the review buttons after one of them was clicked:
=> Lock review buttons after clicking

source/content.css, source/content.js, source/features/hide-navigation-hover-highlight.js
This highlight is actually an accessibility/keyboard feature (`j`/`k`) and it's present in other parts of the site (notifications, issues, PRs) so either it's disabled everywhere on hover or left alone
=> Restore file-list highlight when using keyboard navigation

readme.md
For issue #1336 :
- Added a note that any hidden events in dashboard by default is intended and configurable.
- Corrected a few typos.
=> Mention hide-useless-newsfeed-events in the readme

source/features/mark-unread.js
This blue line appears next to a discussion if you have notifications regarding that:
Fixes https://github.com/sindresorhus/refined-github/issues/1032#issuecomment-362380041
=> Add unread indicator next to discussion in lists

package.json
This removes the following warnings when installing:
```
warning webpack-cli > jscodeshift > babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
warning webpack-cli > webpack-addons > jscodeshift > babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
warning webpack-cli > jscodeshift > nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
warning webpack-cli > webpack-addons > jscodeshift > nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
```
=> Upgrade webpack-cli

source/content.js
I thought someone had an opened an issue for this, but I can no longer find it, but I run into this almost daily when pushes a new commit to fix feedback and the one click option doesn't exist.
=> Enable PR Quick Review buttons on PR commit pages as well

source/features/linkify-urls-in-code.js
Fixes #1376 
Tested in Firefox 60, 62, Chromium 66
=> Disable referrer for linkified URLs

readme.md, source/content.js, source/features/add-delete-to-pr-files.js, source/libs/icons.js
This PR fixes #1127. The issue was to add a delete button for individual files in a PR. We implemented this functionality by adding `add-delete-to-pr-files.js` to the features directory, importing that file into `content.js` and added line 287 to `content.js` to add the delete button functionality to the extension. The delete button appears to the left of the "Copy path" button on the toolbar of each file. When clicked, the button takes you to the correct page to delete that specific file from the PR. No tests were affected and we removed all linter errors.
Contributors: @jacklaird0, @ericmellow, @meloncatty
=> Add delete button to files in a PR 

readme.md, source/content.js, source/features/prev-next-commit-buttons.js
When reviewing a long commit in a PR, it's annoying to have to scroll
back to the top of the page to hit the "Next" button to go to the next
commit. Here we duplicate the Prev/Next buttons and insert them at the
bottom of the page too.
Fixes #1387
=> Copy Prev/Next buttons to bottom of commit page

source/content.css
Fixes #1404.
The fix uses a sloppy `[id^="issuecomment"]` selector, there is also another option to use `.js-minimizable-comment-group` but that makes highlighting on inline commit comments look bad.
[example](https://github.com/sindresorhus/refined-github/pull/1393#commitcomment-29673209)
--------------------------
Let me know if I should use the attribute selector or class selector (I prefer the latter one as its still something than nothing)!
=> Fix targeted comment highlight

readme.md, source/content.js, source/features/show-followers-you-know.js
What inspired me to make this, is the twitter's profile page:
The reason I think this is important is same as #1392. Social proof is useful for discovering people. This updated profile page can show how you are connected to a particular person. If you have friends in common, then that friend might be able to introduce you.
Or, if you don't know why this profile is worth following, the person in common can explain.
"Who to follow" is another feature I like on twitter. I was thinking how I could make it work for github, but I have not found a way just yet. Maybe it's the people, who the person you just followed, follows. It's very useful for people discovery 👍
=> Show followers you know

source/features/add-releases-tab.js
Following up this issue: https://github.com/isaacs/github/issues/1301
Remove the coma from releases numbe as it blocks reading of the release number by 'Number' class and results in showing 'NaN'.
=> Remove coma from release number

readme.md, source/content.js, source/features/linkify-commit-sha.js
Resolves #1053 
For example, [this PR commit page](https://github.com/sindresorhus/refined-github/pull/1045/commits/b7137144f3df9a77f80c78ca63bf43322b2cf621) now links to the ["raw" commit page](https://github.com/sindresorhus/refined-github/commit/b7137144f3df9a77f80c78ca63bf43322b2cf621).
---
=> Linkify commit SHA on PR commit page

readme.md, source/content.js, source/features/hide-comments-faster.js, source/libs/events.js, source/libs/icons.js
From **5 clicks + 700px mouse movement** to **3 clicks + 100px movement.**
Fixes #1268
Replaces and closes #1410
=> Hide comments in fewer clicks

source/features/remove-diff-signs.js
This resolves https://github.com/sindresorhus/refined-github/issues/1444 so that diffs on GitHub.com are only modified if the new GitHub diff sign selection feature is not supported. This means legacy versions of GitHub will continue to support the feature via Refined GitHub and newer GitHub DOMs will use the built in support provided by GitHub.com.
This ensures that users of both GitHub.com and GitHub Enterprise (older versions) can use Refined GitHub without disabling the remove-diff-sign feature.
Also this will ensure that if GitHub reverted the change Refined GitHub will continue to work as expected.
=> Do not remove diff signs from DOM unless GitHub feature is not supported

source/features/add-filter-comments-by-you.js
the selector works again and I slightly updated the added HTML to match what's being used on the page.
resolves #1466
=> Fix selector for add-filter-comments-by-you

source/content.css
GitHub recently started using an alpha color on the border shadow on the sticky pr toolbar. This causes an ugly gap as you scroll over diffs:
This fixes it:
=> Fix 1px space between file headers & diff toolbar

source/features/reactions-avatars.js
Because when a bot reacts to a message, the avatar's url is not valid.
**Before:**
Invalid url `https://github.com/dependabot[bot].png?size=22.000000476837158` is called:
**After:**
Valid url `https://github.com/dependabot.png?size=22.000000476837158` is called:
You can see a live example [here](https://github.com/Kocal/jsdoc-vuejs/pull/108).
=> Fix reactions avatars for bots

source/features/wait-for-build.js
=> Open new tab when clicking the wait-for-build info link

source/content.css, source/features/add-jump-to-bottom-link.js
=> Avoid breaking "Jump to bottom" link in two lines

readme.md
This doesn't appear anywhere anymore
=> Drop unused travis link from readme's markdown

source/features/linkify-branch-refs.js
Closes #1487.
The link is still crossed out and "Deleted" is still displayed, but it's clickable and you will be redirected to the repository.
=> Display link to repository after branch deletion

source/features/show-names.js
This fixes #1549. This feature was initially added in #959, but was [broken by GitHub](https://github.com/sindresorhus/refined-github/issues/1549#issuecomment-426314655).
=> Don't show names for GitHub apps (again)

source/options.html
When clicking the 'Personal Token' link found in the options menu, the
repo options are now preselected to avoid the confusion of what
permissions are required.
This closes #1425
=> Default repo scope for personal token link

source/features/add-branch-buttons.js, source/libs/cache.js, source/libs/get-default-branch.js
Fixes #1173 #1132
This enables the ["see on the default branch" button](https://github.com/sindresorhus/refined-github/pull/1115) in a couple of situations:
- forks
- tags (without visiting a branch first)
- commits (without visiting a branch first)
- files (without visiting a branch+folder first)
https://github.com/sindresorhus/refined-github/tree/visited (branch root)
https://github.com/sindresorhus/refined-github/tree/visited/media (branch folder)
https://github.com/bfred-it/refined-github/blob/visited/.gitattributes (fork, pre-existing branch)
https://github.com/bfred-it/refined-github/blob/default-branch-api/.gitattributes (fork, new branch)
https://github.com/Microsoft/ChakraCore/tree/v1.11.1 (tag)
https://github.com/Microsoft/vsts-tasks/tree/5ca661d47b0ebc6352d4c7697293f23f4f254971 …
=> Use the API to get the default branch

source/features/copy-file.js
Fixes #1500. https://github.com/denkristoffer/refined-github-reproduction/blob/master/file.js can be used to test the fix.
=> Include all linebreaks when copying file

source/features/hide-comments-faster.js
Closes #1561.
- GH changed the `aria-label` attribute of the `summary` tag.
- Now we have to close the parent dropdown manually (don't know how that was closed automatically before, or if it even used to close before).
- I know that I changed the comments and variable names a little bit, will be waiting for @bfred-it to suggest changes.
=> Fix hiding comments

source/features/add-branch-buttons.js
Hi! 👋 
Thanks for the AWESOME extension! 🙌 
I noticed a very minor issue:
When I open the default branch of _**a private repo for the first time***_, Refined GitHub shows the default branch button as "undefined".
\* _this happens right after installing the extension for the first time, AND before switching to a branch other than the default branch. After switching to another branch, Refined Github detects the default branch successfully and caches it, which resolves the issue._
If I'm on the default branch already, I don't expect this button to show up.
The get default branch script attempts to extract the default branch from the DOM. When it fails to find it, it uses the GitHub API as a backup. 
The API fallback ~only work for public repos, not private ones~ requires an access token for …
=> Fix default branch displaying as undefined on private repos

readme.md
Thanks for making GitHub better! Was wondering if you would be willing to add Sourcegraph to your list of related extensions that also make GitHub better?
=> Add Sourcegraph to related extensions in the readme

source/options.html
As reported in https://github.com/sindresorhus/refined-github/issues/840#issuecomment-431700557
@bfred-it should we also add a notice saying that it works on FF now?
=> Remove GitHub Enterprise support notice on Firefox

source/features/hide-useless-comments.js, source/features/linkify-branch-refs.js
Closes #1536.
The fix is surprisingly simple.
The textContent of the comment is empty (under Linux) if only one or more g-emojis were used. So we can simply check for an empty string.
=> Fix hiding of useless comments under Linux

source/content.css
fixes #1570 
CSS caped from a previous fix. (#974)
=> Prevent file header from covering review comment on deeplink

source/features/copy-file.js
GitHub changed some things about the DOM structure of their code highlighter which broke the selector I added in #1559. I changed the selector which hopefully fixes #1603. Please test this extensively, I want this to be my last PR fixing problems with this feature. :smile:
=> Make "Copy file" feature work again

source/content.css, source/features/mark-private-orgs.js, source/libs/icons.js
GH may have changed the markup for organization avatars, which made the absolutely positioned lock icon relative to body.
This PR positions it absolutely, adding relative to the parent avatar.
I also simplified the filled icon a little bit to make it consistent with the other icons.
=> Fix positioning of lock icon on private organization avatar

source/content.css
=> do not cover up fork/star/other extension buttons behind the "recently pushed branches" indicator

source/content.css, source/features/add-toggle-files-button.js
Collapse button is shown again with this fix. Because append is used it will be added to the end of the container.
Remarks
* I noticed it only works on `isRepoRoot()`, is this still the wanted behaviour?
* When going back to repo root (history back) the button doesn't work (page reload needed), not sure if this has always been the case or a new bug.
Closes #1608
=> Fixed bug `No collapse button on repository's browser file list`

source/content.js, source/libs/page-detect.js, test/page-detect.js
Exclude addMoreDropdown & addReleasesTab & removeProjectsTab from loading on the repo search page.
Fixes #1637.
=> Fix errors on repo search pages 

source/features/open-all-notifications.js
The "open all unread notifications in tabs" feature is very convenient, as it requires a single click to be triggered.
When there's only one notification for a given repository, the icon is not shown, which is understandable, but that forces the same action to be done via a Ctrl+click, or a right click to show the context menu and then "Open in a new tab".
Both options are less convenient than the button provided by this feature, so this change simply removes the minimum of two notifications to show the "open in new tabs" icon. As a side effect, it also makes the notifications page more consistent, since all notification blocks now have the same set of icons. Contrast with the current behavior where some blocks have two icons at the top right, and others have only one:
=> Remove minimum count in open-all-notifications.js

source/content.css, source/features/make-discussion-sidebar-sticky.js
Fixes #1647
Before:
After:
`z-index` set to 26, since the comment titles have 25
=> Update discussion-sidebar z-index

readme.md, source/background.js, source/content.js, source/features/hide-issue-list-autocomplete.js
Reverts sindresorhus/refined-github#1657
🤷‍♂️
I'm actually not seeing `autocomplete=off` in the repo issue search anymore.
=> Revert "Drop `hide-issue-list-autocomplete`"

readme.md, source/content.js, source/features/bypass-checks-travis.js
Will close #1620.
It was too hard to use API v3/v4 to get last checks from a pull request, so I used the easy solution:
- find Travis branch/PR checks
- extract `Details` link
- Make an XHR request
- Find `View more ...` link
And this is working very well:
=> Bypass the "Checks" page and go directly to the Travis build when clicking the "Details" links on a PR

source/features/add-branch-buttons.js, source/libs/utils.js
Fixes #1654 
Repo with non-standard tags: https://github.com/PointCloudLibrary/pcl
Repo with standard tags: https://github.com/sindresorhus/negative-zero (shouldn't trigger an API call)
Repo without tags: https://github.com/sindresorhus/refined-github (shouldn't trigger an API call)
=> Fix latest tag link

source/features/mark-unread.js
Fixes #1673 
This adds a check before adding a “Mark as unread” button before attempting to add another one which stops situations like this
=> check for the existance of a “Mark as unread” button

source/features/add-branch-buttons.js, source/features/show-names.js, source/features/user-profile-follower-badge.js, source/libs/api.js
- Throw real errors to the console
- Detect errors sent by the GraphQL endpoint
- Consistently return an `object`, instead of `object`|`boolean`
- Add minimal documentation
- Accept any status via option; code is actually shorter: `if (options['accept' + response.status])`
- Improve readability of existing error messages
- Actually catch 404 errors; it defaulted to `accept404:true`
- "Follows you" feature: visit the profile of someone who follows you (find them in your [followers tab](https://github.com/bfred-it?tab=followers))
- "Default branch": visit a branch of [a project you've never seen before](https://github.com/GhostText/GhostText/tree/phoenix-text)
- "Full names": can you read my full name next to my username?
- https://github.com/sindresorhus/refined-github/pull/1677
- …
=> Improve API error handling

source/libs/utils.js
Before/after screenshot follow
Firefox does not display extension errors, so messages related to the tokens are lost
`Uncaught error (in promise)` text is dropped in Chrome
=> Improve error logging

source/content.css
Fixes #1672 
We can either expand the search field to the left, or don't expand it at all.
This PR add extending it to the left, which does kinda feel a little weird because it has a search filtering dropdown.
=> Expand search field on project page to the left

source/content.css
Details matter.
The selector is pretty generic but it serves as a default and it will be overridden by anything GitHub possibly applies via any `.class` selector.
=> Improve dropdown expansion animation

source/content.css, source/features/make-discussion-sidebar-sticky.js
The `60px` comes from the `gh-header-sticky` height introduced [here](https://blog.github.com/changelog/2019-01-04-sticky-coversation-headers/).
---
Before:
---
After:
=> Fix top position for sticky discussion-sidebar

source/content.css, source/features/make-headers-sticky.tsx
Fixes #1727 
The includes option was set to an empty array, causing it to be excluded from all pages. This changes it so that it's included when `isPRFiles` or `isSingleFile` are true.
=> Fix the `make-headers-sticky` feature

source/features/pr-branches.tsx
=> Fix empty API query error in `pr-branches`

source/features/quick-review-buttons.tsx
Enables the display of the disabled review buttons and takes the
aria-label of the label and turns it into a tooltip. Had to make the
tooltip go to the 'nw' to have it not cut off the screen.
dom-chef doesn't seem to support `disabled={radio.disabled}` as it was
including it even when false, unlike React which ignores false
properties, hence the extra lines for making them disabled still.
Closes #1646.
=> Display disabled review buttons

source/features/diff-view-without-whitespace-option.tsx, source/features/preserve-whitespace-option-in-nav.tsx, source/features/sort-issues-by-update-time.tsx, source/features/sort-milestones-by-closest-due-date.tsx
`preserve-whitespace-option-in-nav` was broken because of `new URLSearchParams(location.href)` (it should be `location.search`)
=> Fix `preserve-whitespace-option-in-nav` and refactor with URLSearchParams

source/content.css
=> Shrink tab padding when 7+ tabs exist on Profile

readme.md, source/features/remove-projects-tab.tsx, source/libs/page-detect.ts, test/page-detect.ts
Fixes https://github.com/sindresorhus/refined-github/issues/984
Fixes #1757 
The tab is hidden if:
- it's 0, and
- you’re not on a Project page, and
- you can't disable projects (i.e. you’re not the owner)
The "New project" is added if:
- the project tab normally appears, and:
- repos: all
- orgs: only if you belong to the organization and thus can create projects
- Repo with 0 Projects tab: https://github.com/bfred-it-obsolete/test
- Repo with projects: https://github.com/babel/babel
- Organization: https://github.com/bfred-it-obsolete
- Organization with projects: https://github.com/rust-lang
- Organization you belong to ("New project" will appear)
- Organization you own (the tab will not be hidden)
- Profile: https://github.com/bfred-it
- Your own profile ~~(the tab will not be …
=> Hide the project tab in profiles and orgs

source/libs/api.ts
Closes #1703
`api/graphql/` to `api/graphql`
ref: https://developer.github.com/enterprise/2.15/v4/guides/forming-calls/#the-graphql-endpoint
receive error message
{
"message": "Not Found",
"documentation_url": "https://developer.github.com/enterprise/2.15/v4"
}
=> Edit GHE GraphQL endpoint

package.json, readme.md, source/content.css
It was halved by https://github.com/sindresorhus/refined-github/pull/1587 and later broken by their custom-element-based buttons.
=> Restore toolbar button-hiding feature

source/manifest.json
It was added in https://github.com/sindresorhus/refined-github/commit/d17ad257b70a665f8bfe47fd14ba04509b20abb9
> Indicates the extension or app uses document.execCommand('copy') or document.execCommand('cut'). This permission is required for hosted apps; it's recommended for extensions and packaged apps.
> \- https://developer.chrome.com/apps/declare_permissions
It's not required and it seems to work fine without it.
More here: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard
=> Remove unused permission

package-lock.json, package.json, source/features/add-co-authored-by.tsx, source/features/close-out-of-view-modals.tsx, source/features/collapsible-content-button.tsx, source/features/comment-fields-keyboard-shortcuts.tsx, source/features/extend-diff-expander.tsx, source/features/hide-comments-faster.tsx, source/features/mark-unread.tsx, source/features/scroll-to-top-on-collapse.tsx, source/features/toggle-files-button.tsx, source/features/upload-button.tsx, source/features/wait-for-build.tsx
Events are now attached only once without needing `onetime`. 
Will auto-merge tomorrow.
Fixes https://github.com/sindresorhus/refined-github/pull/1804#discussion_r259465822
=> Replace `delegate` with `delegate-it`

source/content.css
So that everything fits in one line. Closes #1830.
Before:
After:
This can be tested in any repo, but as mentioned in #1830, it will only make a difference (prevent overflow) in repos with many PRs that you have push access to.
=> Reduce issue/PR filter button padding when batch-open-issues is active

package.json, source/content.css
- Dropped some outdated styles
- Added some `feature-names`
- Applied commit title style/sizing to PR merge form as well
- Included commit title style/sizing in `monospace-textareas` feature
=> Cleanup CSS (first 200 lines)

source/features/comments-time-machine-links.tsx, source/features/warning-for-disallow-edits.tsx, source/libs/page-detect.ts
Fixes #1811 
One of them was because on review comments the time appears elsewhere:
I think it's ok for now. I think eventually we'll have to move that icon into the dropdown menu for each comment. GitHub didn't have that before.
=> Fix console errors for a few features

source/features/highlight-closing-prs-in-open-issues.tsx, source/libs/icons.tsx
You can close issues by just referencing them in commits. Live demo: https://github.com/sindresorhus/refined-github/issues/1827
Closing commits are already supported by [`extend-status-labels`](https://github.com/sindresorhus/refined-github/pull/1078)
=> Also show closing commit in issue header

readme.md, source/content.css
Fixes #1859 and follows #1824.
I think I got to a good point. This matches the "Recent activity" box style at the top of the page.
And it also works decently for organization events:
Comment events still show a lot of duplicate info, but I don't look at them enough (or at all) to care to improve it (and maintain it)
=> Change dashboard style again

source/content.css, source/content.ts, source/features/hide-watch-and-fork-count.tsx
I add a new class `hide-watch-and-fork-count`.
Or maybe should I just use `btn.style.display = 'none'`?
Closes #1843
=> Let users disable `hide-watch-and-fork-count`

source/content.css, source/features/hide-useless-newsfeed-events.tsx
`.news` might not be available on domReady in the new dashboard
=> Make `hide-useless-newsfeed-events` more reliable

source/content.css, source/features/branch-buttons.tsx
These buttons have been missing:
https://github.com/babel/babel/tree/v7.4.2
https://github.com/sindresorhus/refined-github/blob/a759d4346e5ac4a98c9fdb2734cdae625de0f309/source/content.css
https://github.com/babel/babel/blob/master/.editorconfig
=> Restore `branch-buttons` feature

package.json
`real` time almost halved:
```diff
❯ time npm run test
...
-        11.83 real        19.58 user         1.91 sys
+         6.42 real        24.42 user         2.35 sys
```
=> Meta: Run tests in parallel

readme.md, source/content.css
Before/after. Negligible change in the global list page, but those filters on `/pulls` are starting to feel too many, maybe they should be turned into a dropdown.
Global: https://github.com/pulls
Repo: https://github.com/sindresorhus/refined-github/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc
=> Wider search field

readme.md, source/content.ts, source/features/parse-backticks.tsx
This feature will convert \`code\` into `code` where applicable. **Currently it only looks for it in issue titles,** but it can be expanded (hence the very generic name)
The style is TBD. 
- Should the backticks stay?
- Should the text size be increased? 
- Should the background be turned gray?
**Edit: no, yes, yes; see next comment**
https://github.com/sindresorhus/np/issues
<details><summary>Edit: discarded, see next comment</summary>
=> Add `parse-backticks` feature

source/features/useful-not-found-page.tsx
GHE still has super old 404 page markup and `main` does not exist. Updating the selector allows both GH and GHE to utilize this feature. Tested on GHE 2.16.4.
=> [bug] Fix useful-not-found-page on GHE

source/features/mark-unread.tsx
For some reason a few pages in GHE, mainly projects, has different markup for the notification icon which doesn't have the `mail-class` list resulting in an error when we try to reference this `statusMark.classList.toggle('unread', hasUnread);` later.
Sample wrong markup:
```html
<a href="X" class="notification-indicator d-md-none mr-3" aria-label="Create new project">
<svg height="22" class="octicon octicon-plus" viewBox="0 0 12 16" version="1.1" width="16" aria-hidden="true"><path fill-rule="evenodd" d="M12 9H7v5H5V9H0V7h5V2h2v5h5v2z"></path></svg>
</a>
```
GHE hasn't had notifications until a recent release, so likely a miss on their end.
=> [bug] Fix null pointer error on GHE Projects page

source/features/follow-file-renames.tsx
On GHE (v2.16.4) the disabled pagination "buttons" are not buttons, rather span elements
GHE (v2.16.4):
```
<span class="disabled">Newer</span>
```
Github:
```
<button class="btn btn-outline BtnGroup-item" disabled="disabled">Newer</button>
```
=> Support `follow-file-renames` on GHE (v2.16.4)

source/features/reactions-avatars.tsx
This PR fixes #1888 by changing the `load` definition of the `reactions-avatars` feature from `onAjaxedPages` to `onNewComments`.
As mentioned in the issue, a page to test this would be [sindresorhus/eslint-plugin-unicorn#169](https://github.com/sindresorhus/eslint-plugin-unicorn/issues/169), search for "hidden items" and click the according element to reveal new comments and have their reaction avatars attached.
=> Fix `reactions-avatars` for new elements

source/features/global-discussion-list-filters.tsx
Fixes https://github.com/sindresorhus/refined-github/issues/1919
Links to reproduce: global [Pull Requests](https://github.com/pulls) or [Issues](https://github.com/issues), then click either the `Commented` or `Yours` button.
Things this PR fixes:
1. In the global Issues page, the proper parameter is put in the URL so the filter is correct (i.e. pull requests don't appear as well).
2. When in a `Commented` or `Yours` query, the added query parameter is removed correctly from the rest of the buttons URLs (`Created`, `Assigned`, `Mentioned` and `Review requests`). The previous behaviors removed one space too many leading to parameters joined together. Fixes #1919.
3. When the query parameters contained a malformed query, the `Commented` or `Yours` buttons don't light up. For example, if …
=> Various fixes for `global-discussion-list-filters` feature

source/features/show-names.tsx
Replaced (maybe a typo) `name` with the actual user name `{names[userKey].name}` and added a guard condition to avoid breaking.
Fixes #1940
Closes #1940
=> Fix `show-names`

source/features/branch-buttons.tsx, source/features/pr-branches.tsx, source/features/releases-tab.tsx, source/features/remove-projects-tab.tsx
1. `pr-branches`: 
- An alphanumeric string was being passed to `Number()` causing it to return `NaN` and eventually lead to failure of GraphQL query.
- https://github.com/sindresorhus/refined-github/issues/1935#issuecomment-484849946
2. `remove-projects-tab`: Selector was renamed from `HeaderMenu` to `Header`.
3. `branch-buttons`: Feature scope was set to `isRepo` so it was breaking on some due to lack of the expected selector. Enabled the features on `isRepoRoot` and `isSingleFile`.
4. `releases-tab`
- https://github.com/sindresorhus/refined-github/issues/1935#issuecomment-484849946
Fixes #1935
Closes #1935
=> Fix `pr-branches` and `remove-projects-tab` features

source/features/copy-file.tsx, source/features/esc-to-deselect-line.tsx, source/features/hide-own-stars.tsx, source/features/hide-useless-comments.tsx, source/features/highlight-closing-prs-in-open-issues.tsx, source/features/mark-unread.tsx, source/features/open-all-notifications.tsx, source/features/scroll-to-top-on-collapse.tsx, source/features/upload-button.tsx, source/features/wait-for-build.tsx, source/libs/utils.ts
In most cases, `target` could be replaced for `currentTarget`, which is correctly typed. Even `currentTarget` is typed by `React.Event` as `EventTarget & TElement`
Currently untested
_Related open TypeScript PRs:_ https://github.com/sindresorhus/refined-github/pull/1947 https://github.com/sindresorhus/refined-github/pull/1943 https://github.com/sindresorhus/refined-github/pull/1936
=> Drop some TypeScript type assertions

source/globals.d.ts
Relates to #1735. Just added a note to remove some types we merge on once TypeScript ships with a fix for https://github.com/Microsoft/TypeScript/issues/30928.
=> Add TODO comment about TS bug in NamedNodeMap

source/features/edit-files-faster.tsx
I had an issue with this [extension](https://chrome.google.com/webstore/detail/github-vscode-icons/hoccpcefjcgnabbmojbfoflggkecmpgd) and tried to disable the edit-files-faster feature but it did not work.
So i tried to disable every feature on by on and it work when I disabled edit-comments-faster.
And then I notices that the extension logged twice that this feature was disabled, so I took a look in edit-files-faster.tsx. There I saw that the id was wrong, so this PR fixes this issue.
=> Fix wrong id in edit-files-faster

source/features/filter-pr-by-build-status.tsx
This addresses the issue called out here: https://github.com/sindresorhus/refined-github/pull/1904#issuecomment-485615635
I didn't want to return on the first selector, as if GH changes the DOM, then we won't realize the feature broke as easily.
=> Fix filter-by-pr-status when no Pull Requests exist

source/content.css, source/features/mark-unread.tsx
Closes #1954
Using the `title` attribute of status label to detect draft PRs, because status label for draft PRs don't have any additional CSS classes added to them.
-----------------------
Also sneaked some code in to align reaction avatars and last updated labels with GitHub's native notifications, this is because GH notifications have additional "Save for later" button, which we don't add.
<details>
<summary>Misaligned avatars</summary>
</details>
-----------------------
Another minor change is to add hover-card support to notifications marked as unread.
=> Allow marking draft PRs as unread

source/features/upload-button.css
Closes #1992 
@bfred-it mentioned [here](https://github.com/sindresorhus/refined-github/issues/1992#issuecomment-487345168) that
> the **!important** is required now because they have a utility class on it
=> Hide comment box upload message

source/features/show-names.tsx
show-names fails when the link is to the marketplace.
~~fixes []() #1978~~
=> Fix `show-names` features when bots are on the page

.travis.yml, package.json
Thanks to Google everyone can be a git/shell wizard 🧙‍♂️
Fixes #1995 
Documentation: 
- https://docs.travis-ci.com/user/deployment/#conditional-releases-with-on
- https://stackoverflow.com/a/33733020/288906
- https://stackoverflow.com/a/3826705/288906
Tested with:
```sh
TRAVIS_EVENT_TYPE=cron
if [[ ($TRAVIS_EVENT_TYPE = cron) && ($(git tag -l --points-at HEAD) = "") ]]
then 
echo :ship-it:
fi
```
Further simplifications welcome
=> Avoid duplicate releases

readme.md, source/content.ts, source/features/clean-sidebar.css, source/features/clean-sidebar.tsx, source/features/hide-tips.css
Closes https://github.com/sindresorhus/refined-github/issues/421 (hide milestones)
Closes https://github.com/sindresorhus/refined-github/issues/977 (hide projects)
Replaces and closes https://github.com/sindresorhus/refined-github/pull/1945
Replaces and closes https://github.com/sindresorhus/refined-github/pull/1965
~~The code is ugly but sadly each section is at least slightly different :(~~ → ceeca8d 🌈
Depends on many variables:
- issues/PRs
- empty/full sections
- can/cannot edit sections
These have a good variety of _PR + cannot edit_ sections: https://github.com/parcel-bundler/parcel/pulls
=> Add `clean-sidebar` feature

source/features/extend-status-labels.tsx
Recap: Besides linking to a concrete PR/commit, the `extend-status-labels` feature also puts an anchor to the closing note on the status label (which I find really handy since the most valuable/helpful comments are often right before the closing note).
However, those anchors are currently not set when an issue was *not* closed by a PR/commit (e.g. #2005).
This PR changes that behavior by not bailing out prematurely when no commit/PR was found. Instead it always puts the anchor to the closing note and adds the `in #xxxx` label + link if needed.
=> In discussions, always link the "Closed" label to the closing event

source/features/batch-open-issues.tsx
GitHub has removed the `.table-list-header` class. Fixes #2004
This should be easily testable by opening any list of issues with more than one issue :smile:
=> Restore "Open All" on issues/PRs list (`batch-open-issues`)

package-lock.json, package.json, source/features/tag-changelog-link.tsx
Fixes https://github.com/sindresorhus/refined-github/pull/1998#issuecomment-492285094
Tested it on 
1. https://github.com/parcel-bundler/parcel/releases (Namespaced tags)
2. https://github.com/facebook/react/releases (Tags with the beta, alpha versions)
=> Decode tag before extracting version and namespace

source/libs/fetch-dom.ts, source/libs/page-detect.ts, test/page-detect.ts
Fixes #2056
<details>
<summary>Edit: type issues solved</summary>
There's a type issue with `p-memoize` though: https://github.com/sindresorhus/p-memoize/issues/9
```ts
source/features/ci-link.tsx:10:30 - error TS2558: Expected 0 type arguments, but got 1.
10  const icon = await fetchDom<HTMLElement>(url, '.commit-build-statuses');
~~~~~~~~~~~
source/features/show-followers-you-know.tsx:9:20 - error TS2554: Expected 2 arguments, but got 1.
9  const dom = await fetchDom(url);
~~~~~~~~~~~~~
source/features/tag-changelog-link.tsx:21:10 - error TS2554: Expected 2 arguments, but got 1.
21      return fetchDom(nextPageLink.href);
~~~~~~~~~~~~~~~~~~~~~~~~~~~
source/features/tag-changelog-link.tsx:26:10 - error TS2554: Expected 2 arguments, but got 1.
26      return …
```
=> Fix console errors

source/features/reactions-avatars.tsx
Clicking on the avatars in Firefox brings you to their profile. So I dropped the link on those avatars. Also the `a` is used in the styles so I just left it there to avoid having to change the styles as well.
=> Improve clickability of reaction buttons in Firefox

.github/pull_request_template.md
There was an unclosed comment in the pull request template under the 'closed' text. This unclosed comment ended up commenting out everything underneath it.
=> Fix formatting in `pull_request_template.md`

source/features/bypass-checks.tsx
#1636 and #1693 were created to bypass the annoying _new page_ Checks and it's working properly.
However, for GitHub Actions, we actually don't want to bypass the Checks page.
Below, every `Details` link are redirecting to https://developer.github.com/actions/ and it's pretty useless:
We want `Details` links to be untouched, so they are still redirecting to the good Check page:
See the checks at the bottom of https://github.com/actions/zeit-now/pull/4.
=> Don't bypass GitHub Actions checks

source/features/clean-rich-text-editor.css
The visible drag and drop area is the only method of attaching files to a release. It looks like the selector meant to hide the message on discussions accidentally applies to also releases.
The drag and drop area for releases was hidden in #2068.
As an admin of refined-github, you can check the behaviour on https://github.com/sindresorhus/refined-github/releases/new?tag=19.5.26.1924
=> Show drag and drop area on release page

source/background.ts, source/libs/cache.ts
Closes #2077 
The cache lib was defining its own `browser.runtime.onMessage.addListener` and there can only be one of these. The solution to this was to make the background script delegate the message to the cache lib function if necessary.
You can view this fix in action at https://github.com/mulberrysymbols/mulberry-symbols
=> Make sure release count is always shown

source/features/preview-hidden-comments.tsx
Fixes an issue where clicking the source link in Features list (in about:addons) would result in a 404 due to id being different to the actual source file.
When I loaded my dev copy as a temporary extension in Firefox, changing the ID seemed to result in the feature being disabled. Not sure if there's some way to fix that?
=> Fix typo in `fix-hidden-comments` feature's ID

source/features/more-dropdown.tsx, source/libs/utils.ts, test/utils.ts
Include current ref (branch or tag) in compare & commit repo links added in [`more-dropdown`](https://github.com/sindresorhus/refined-github/blob/master/source/features/more-dropdown.tsx#L37-L48). Different pages required different detection to get the current ref (branch or tag).
Optionally I can include [the default branch](https://github.com/sindresorhus/refined-github/blob/master/source/libs/get-default-branch.ts), but that requires an extra API call and is not necessary.
Closes #1197.
1. Visit any of the below urls.
2. Open repo tab "More" -> "Compare" or "Commits".
3. See it link to the correct tree (branch or tag).
* https://github.com/BrowserSync/browser-sync ➡ no ref
* https://github.com/BrowserSync/browser-sync/tree/client-ts ➡ compare & commits should link to ref
* …
=> Link to current branch in More's Compare and Commits links

source/features/tags-dropdown.css, source/features/tags-dropdown.tsx, source/features/widen-search-field.css
Closes #2013.
- Aligned subnav items based on their classes.
- Removed margin on tags selector.
- https://github.com/sindresorhus/refined-github/labels
- https://github.com/sindresorhus/refined-github/releases
=> Fix alignment of subnav items

.github/CODEOWNERS, readme.md, source/content.ts, source/features/highest-rated-comment.css, source/features/highest-rated-comment.tsx, source/libs/icons.tsx
Closes #1898
https://github.com/leafo/sticky-kit/issues/201
https://github.com/facebook/react/issues/13991
https://github.com/flutter/flutter/issues/11609 has controversial comments
https://github.com/MrMEEE/bumblebee-Old-and-abbandoned/issues/123
=> Add `highest-rated-comment` feature

source/features/raw-file-link.tsx
Closes #2006  
https://github.com/sindresorhus/refined-github/pull/1783/files
=> Restore `raw-file-link` feature

readme.md, source/content.ts, source/features/format-discussion-titles.tsx, source/features/linkify-issues-in-titles.tsx
Closes #1984
1. For issues: All issues present on https://github.com/HardikModha/github-playground/issues
2. For PR pages: All PRs present on https://github.com/HardikModha/github-playground/pulls
3. Also tested the feature by updating the issue / PR title. (https://github.com/HardikModha/github-playground/issues/9)
=> Format titles on single issue / PR pages

source/features/recently-pushed-branches-enhancements.css
Fixes https://github.com/sindresorhus/refined-github/pull/2110#issuecomment-498922194.
Issues:
- It looked misaligned.
- The branch icon was not in alignment with the text.
Before:
After:
=> Fix branch name alignment in recently-pushed-branches

package-lock.json, package.json, source/features/releases-tab.tsx, source/globals.d.ts, source/libs/cache.ts, source/libs/get-default-branch.ts
What methods should I implement besides get/set?
Closes #2100
https://github.com/sindresorhus/refined-github (Open devtools on the background page to see the console, repo pages use `release-count` and `default-branch` caches)
=> New cache implementation

source/features/global-discussion-list-filters.tsx, source/libs/page-detect.ts, test/page-detect.ts
GitHub included some new urls at the global discussion list for PR and issues:
* https://github.com/issues
* https://github.com/issues/assigned
* https://github.com/issues/mentioned
* https://github.com/pulls
* https://github.com/pulls/assigned
* https://github.com/pulls/mentioned
* https://github.com/pulls/review-requested
Those are not matched by the `isGlobalDiscussionList` page-detect. And therefor breaking `global-discussion-list-filters` feature (and probably also `sort-issues-by-update-time`).
#2134
1. Disable feature `sort-issues-by-update-time`
2. Go to https://github.com/pulls
3. See "Commented" and "Yours" buttons
4. Select "Assigned"
5. You will be redirect to https://github.com/pulls/assigned
6. See "Commented" and "Yours" buttons **appear again**
=> Enable discussion list features on new URLs

source/features/ci-link.tsx, source/features/filter-pr-by-build-status.tsx
Closes #2127
1. https://github.com/sindresorhus/refined-github/pulls (Filter should be present)
2. https://github.com/HardikModha/github-playground/pulls (Filters should not be present)
=> Only show `filter-pr-by-build-status` if the repo has CI

source/features/show-names.tsx
Currently, when an organization creates an event in a discussion, it will be picked up by `show-names`, but organizations aren't users, so the current implementation can't get its real name, and fails from the graphql error.
This just ignores organizations, you should know the organization from its name.
Test: https://github.com/rust-lang/rfcs/pull/2544
=> Ignore organizations from `show-names`

source/features/indented-code-wrapping.css, source/features/indented-code-wrapping.tsx
Closes #2085.
Fixes #2089.
- Assumes that spaces always come after tabs, but other way around too.
- Works for dynamic `tab-size` values too, like when using "GitHub Custom Tab Size".
- But as mentioned in https://github.com/sindresorhus/refined-github/issues/2085#issuecomment-498032629, wrapped text would not be at the same level of the actual line, it would be where the last tab character ended.
- https://github.com/eclipse/omr/commit/75c09985f5d5dd6cfd7c9d1e4f4d56e9406a45c4#diff-3990e65f3237ed46d278a1a8aefbaeeaR389 from https://github.com/sindresorhus/refined-github/issues/2085#issue-448919803.
- https://github.com/sindresorhus/electron-context-menu/pull/76#discussion_r289699052 from https://github.com/sindresorhus/refined-github/issues/2085#issuecomment-500191824.
- …
=> Fix `indented-code-wrapping`

.github/CODEOWNERS, readme.md, source/content.ts, source/features/cycle-lists-with-keyboard-shortcuts.tsx, source/globals.d.ts
Closes #1450.
- Makes use of custom events emitted by GitHub to detect and add events to input elements.
- As opposed to #2008, this PR adds `keydown` event listeners to only search fields, which is also what GitHub uses (you cannot use up and down arrow keys to navigate when the search field is not focused).
- Supports cycling through labels, projects, milestones and all other sidebar elements, even when a search filter is applied.
Can be tested on any issue or PR that you have permissions to edit.
=> Add `cycle-lists-with-keyboard-shortcuts` feature

source/features/highest-rated-comment.tsx
See https://github.com/sindresorhus/refined-github/pull/2108#issuecomment-505378681
leafo/sticky-kit#201
facebook/react#13991
flutter/flutter#11609 has controversial comments
MrMEEE/bumblebee-Old-and-abbandoned#123
microsoft/vscode#71827
=> Add label to highest-rated comment

readme.md
Add images to `indented-code-wrapping` and `limit-title-commit-length` features, mentioning them in the readme.
From https://github.com/sindresorhus/refined-github/pull/2115#issuecomment-506672071 and https://github.com/sindresorhus/refined-github/pull/1989#issuecomment-506671210.
=> Mention recently added features in readme

source/features/forked-to.tsx
Make cache key unique per username. 
This will fetch all forks again.
Already cached forks will invalidate after 10 days anyways.
Closes https://github.com/sindresorhus/refined-github/pull/2153#issuecomment-509045202
/cc @1138-4EB & @bfred-it
=> Make cache key unique per username

source/features/mark-private-orgs.tsx, source/libs/api.ts
Fixes #2210 
After some digging, it seems as though the response from GitHub's API changed a bit(?), and some of the keys in the response aren't iterable. 🤔 
This just uses an explicit `Object.values` around the `publicOrgs` response object. 😄
=> Restore lock icons on private orgs

source/options.tsx, webpack.config.ts
Options page was missing its `.css` file.
Open extension options.
=> Fix missing `options.css`

package-lock.json, package.json, source/features/forked-to.tsx
Follows #2153 
Changes:
- Actually validate fork via HTTP request
- Don't validate current page
- Delete cache entry completely when fork is gone
- Avoid merging with existing cache when unnecessary (i.e. when opening the fork dialog)
- Get/validate/update cache in one step before showing the links
- Reduce number of functions
Currently untested
cc @jerone
=> Various fixes to `forked-to`

readme.md, source/content.ts, source/features/mark-files-as-viewed.tsx
Whenever I approve a PR I’d love to have all of the changed files marked as viewed.
https://github.com/lukaszklis/refined-github-mark-files-as-viewed/pull/1/files (can grant collaborators privileges upon request)
=> Add mark files as viewed feature

source/features/mark-files-as-viewed.tsx
This morning when approving a PR I spotted a problem with the ”mark all files as viewed” feature I added in #2218. The selector I used to find ”Viewed” checkboxes did not take into the account that some of them might have already been checked.
=> Fix checkbox selector for mark files as viewed

source/features/minimize-upload-bar.tsx
Can't use `:last-child` selector, because the last child inside the markdown-toolbar on the new issue page is an hidden element.
Fixes #2234.
1. https://github.com/sindresorhus/refined-github/issues/new?labels=bug&template=bug_report.md
=> Fix `minimize-upload-bar` on new issue

source/features/branch-buttons.tsx, source/libs/utils.ts
Closes #2049 
I took the closet approach I can think of via a `<link>` tag in head which looks like follow.
```html
<link href="https://github.com/sindresorhus/refined-github/commits/master.atom" rel="alternate" title="Recent Commits to refined-github:master" type="application/atom+xml">
```
Looks like every pages have it, and we can get the current branch from it stably. Please let me know if there is any concern.
I tried getting the current branch from the dropdown menu, but they are lazily loaded. Then I tried to get it from the `title` attribute of the dropdown button, it works for branch, but not for tag. I want to have a more general solution so I took this approach.
https://github.com/kevin940726/refined-github/blob/fix/branch-buttons/.travis.yml
=> Fix branch link broken with `/` in the branch name

source/content.ts, source/features/edit-readme.tsx
Quickly edit a repository's README from the repository root.
Closes https://github.com/sindresorhus/refined-github/issues/2225
1. Open any repo with a readme where you don't have admin rights to.
2. Scroll to the readme.
3. Click the edit button.
_Test with readme in subfolder:_
1. Go to https://github.com/davidbailey/tum/tree/master/handbook#readme.
2. Click edit button.
---
<details>
<summary>
<b>IssueHunt Summary</b>
</summary>
This pull request has been submitted to:
- [#2225: Restore `edit-readme-button` on all repos](https://issuehunt.io/repos/51769689/issues/2225)
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>
=> Add `edit-readme` feature

source/features/scrollable-code-and-blockquote.css
Might be a little hard to tell, but the Emoji is clipped on the bottom.
[Comparison with a slider](https://cdn.knightlab.com/libs/juxtapose/latest/embed/index.html?uid=6d42935a-a612-11e9-b9b8-0edaf8f81e27)
https://github.com/sindresorhus/refined-github/issues/1900#issuecomment-511180163
=> Fix: Unwanted scroll bar in quotes with an Emoji

source/features/recently-pushed-branches-enhancements.css
Closes #2227 
Before:
After:
This is the same as it was earlier
=> make sure `recently-pushed-branches` is applied to Header only

source/features/faster-pr-diff-options.tsx
Trim the PR title on the PR files tab.
Fixes #2202.
* Fixed on: https://github.com/sindresorhus/refined-github/pull/2229/files
* N/A on: https://github.com/sindresorhus/refined-github/pull/2229/commits/b8b9a3394d9aa667ad9c2576ff5fd381147c4960
=> Fix wrapping too long PR title on PR files tab

source/features/open-issue-to-latest-comment.tsx
Adds jumping to the latest comment on pinned issues
=> Extend `open-issue-to-latest-comment` to pinned issues

source/features/warning-for-disallow-edits.tsx
Closes #2244
Still works on the new pull request page.
Snapshot of the current HTML:
Go to a PR of yours, uncheck "Allow edits from maintainers" on the side bar.
=> Fix `warning-for-disallow-edits` on PR page

source/options.html
Firefox move the options to its own Tab so the header is no longer needed
=> Improve Options page

source/libs/get-default-branch.ts
(master **is** the default branch)
```js
branchInfoRegex = /([^ ]+)\.$/;
branchInfoRegex.exec($('.branch-infobar').textContent.trim());
(2) ["master.", "master", index: 108, input: "Pull request↵        ↵      ↵        ↵        Comp…↵      This branch is 64 commits ahead of master.", groups: undefined]
```
I think you need to have a clean cache for this repo, and go to https://github.com/pymedusa/Medusa/tree/develop,
then you can visit the default branch https://github.com/pymedusa/Medusa
=> Fix period on default branch

source/features/view-markdown-source.tsx
It seems like f7e0d05b0f09c46833c2411ab12997c73963958d from https://github.com/sindresorhus/refined-github/pull/1873 does not highlight the selected lines currently:
Switching out the hash once to an empty string and back to the original value causes the highlight to be applied.
cc @bfred-it
=> Highlight permalinked line in `view-markdown-source`

source/options.css, source/options.html
Do to layout changes the box was made wider so 50% is still too big
Closes #2257
=> Shorten personal token field in options for privacy

source/features/edit-readme.tsx
Note: This feature is a bit trippy because GitHub already has it, but **not in repos you you can't push.**
Partial fix to #2261
- The feature was broken everywhere
- The feature was trying to "edit" files on commits and tags: GitHub doesn't allow that.
Since this feature is kind of a "polyfill", we need to match GitHub's behavior: those "Edit readme" links on commits and tags now point to the default branch
All links should point to `master` except the `release` branch link, that's a valid one.
- https://github.com/chartjs/Chart.js
- https://github.com/chartjs/Chart.js/tree/release
- https://github.com/chartjs/Chart.js/tree/v2.8.0
- https://github.com/chartjs/Chart.js/tree/6632b8ba8475e020fd0533e2630117376a9cbc73
- https://github.com/chartjs/Chart.js/tree/master/docs
- …
=> Fix `edit-readme` feature

source/features/edit-files-faster.tsx
Partially fixes #2261 the same way as #2278 does
All links should point to `master` except the `release` branch link, that's a valid one.
- https://github.com/chartjs/Chart.js/tree/master/docs
- https://github.com/chartjs/Chart.js/tree/release/docs
- https://github.com/chartjs/Chart.js/tree/v2.8.0/docs
- https://github.com/chartjs/Chart.js/tree/6632b8ba8475e020fd0533e2630117376a9cbc73/docs
=> Fix `edit-files-faster` feature

contributing.md, readme.md
Fixes https://github.com/sindresorhus/refined-github/pull/2283#issuecomment-516127150
- I tried moving the comment above each line but it also caused the rendering to change (it created a `<ul><li></li></ul>` for each item): https://github.com/sindresorhus/refined-github/tree/018061da20793b32ec029f563ba122c1a2f547ae
- I didn't want to move the comment at the end of the line because it makes it easy to miss it. This way the feature names are aligned.
- Now it adds comments via empty anchors: https://github.com/sindresorhus/refined-github/tree/591d424099aab829e7240de68d4b3c76984192f0
=> Meta: Fix Readme formatting

source/features/show-names.tsx, source/libs/features.tsx
Fixes #2290
Loading mechanisms are called right away; it's the callback inside that will check the `include` conditions.
The previous setup was calling `onNewsfeedLoad` on every page and failing. This also shows that `onNewComments` should probably receive the same treatment and should be dropped from `features.tsx`’s exports. PR welcome after this is confirmed
Reload this page, check for console errors
=> Fix console error in `show-names`

source/libs/utils.ts
Fixes #2306
In private repo's .atom has a key added.
`master.atom?token=**************************`
=> Fix default branch in private repo

source/features/branch-buttons.css, source/features/branch-buttons.tsx
The markup for navigation bar on repo tree is different from that of a single file page. This causes the insertion of a `div` before breadcrumbs whose parent is not a flex container to push breadcrumbs element to the bottom, even when there is enough space, Leading to a slightly broken view on repo tree pages.
=> Fix branch button alignment

source/features/update-pr-from-base-branch.tsx
Closes [#2213](https://github.com/sindresorhus/refined-github/issues/2213)
This bug fix avoids the duplicated `update branch` button on pull request pages
- <REPO_OWNER>/<REPO_NAME>/pull/<ID>
=> Avoid adding a duplicate “Update Branch” button

source/features/warning-for-disallow-edits.tsx
The warning didn't show after unchecking the checkbox.
`.discussion-sidebar` is no longer available.
**Test**:
On any PR from your fork to an upstream repo, uncheck "Allow edits from maintainers."
The warning should be visible.
=> Fix `warning-for-disallow-edits`

source/features/hide-watch-and-fork-count.css
I like how clean the buttons area looks now, but I don't deny that sometimes I want to access those links we hide. I think this is a good compromise. #2230 should also allow to click the fork count once merged.
=> Show counts when dropdowns are open in `hide-watch-and-fork-count`

source/features/sticky-discussion-sidebar.css
Closes #2339
This feature depends on the viewport size, the sidebar has to be sticky for these issues to appear (or not appear)
1. The Labels dropdown should not overlap the file's header in the review below. [Example](https://github.com/sindresorhus/refined-github/issues/1647)
2. The "Notifications settings" lightbox should appear and work correctly, without the Repo’s social buttons being overlapped. [Example](https://github.com/sindresorhus/refined-github/issues/2189)
3. The "Repo Notifications" dropdown should not overlap the sidebar. [Example](https://github.com/sindresorhus/refined-github/issues/2339)
=> Fix sidebar issues caused by `sticky-discussion-sidebar`

source/features/mark-unread.tsx, source/libs/on-updatable-content-update.ts
Fixes #2335
`.discussion-sidebar` is no longer available.
**Test**:
Open any discussion, look for the "Mark as unread" button
=> Fix `mark-unread` button injection

source/features/clean-sidebar.tsx
Using the new `onUpdatableContentUpdate` by @fregante.
Closes #2333.
On a discussion where you have access to assign things on the sidebar (label, milestone, etc.), make a change - after the "partial" content is updated, the sidebar is cleaned.
=> Fix `clean-sidebar` on sidebar updates

source/features/more-dropdown.tsx, source/globals.d.ts
Closes #2357
Closes #2358
For some reason using `<button>` won't open the dropdown, I have read GitHub's code for some time but can't figure out why, so changed it to `<span>` and everything looks fine.
This repo
=> Fix always expanded "More" dropdown menu

source/features/deprioritize-marketplace-link.tsx
Marketplace is an opt-in feature for GHE, if you're on an instance where it's not enabled, `marketPlaceLink` will be undefined and return an error in the console when `.closest` is invoked.
=> fix: marketplace is opt-in for Enterprise, handle it being turned off

source/features/mark-unread.tsx
Adding the mark unread button on all pages of the PR, e.g. commits, results in a console error:
```
content.js:2568 TypeError: Cannot read property 'after' of null
at addMarkUnreadButton (content.js:3769)
at mark_unread_init (content.js:4011)
at async features_run (content.js:2562)
```
=> fix: only add mark unread on PR Conversation view

source/features/embed-gist-inline.tsx
Currently it tries to load them and then display `(embed failed)`.
https://gist.github.com/KomaliVuddanti/f062a78b4fff3ee001529efe2a468375
https://gist.github.com/defunkt
=> `embed-gist-inline` exclude user links

.github/CODEOWNERS, source/features/tags-dropdown.css, source/features/widen-search-field.css
Fixes #2325
1. Releases tab: https://github.com/sindresorhus/refined-github/releases
2. Tags page
3. When "Draft New Release" is present
4. Unbroken Widen search field on...
**Pull Requests**
**Issues page**
=> Fix header alignment on Releases and Tags pages

source/features/highest-rated-comment.css
Also closes #2237
The `highest-rated-comment` feature adds a border around the highest rated comment. But it bothered me that the caret was not styled. This PR fixes that.
Closes #2237
* https://github.com/isaacs/github/issues/50#issuecomment-29907848
=> Change `highest-rated-comment` color to green instead of orange + fix style

source/features/profile-hotkey.tsx
Closes #2400 
any page and press `g m` to go to profile.
=> Fix `profile-hotkey`

source/features/sync-pr-commit-title.tsx
GitHub added a **Reference in new issue** option to comments that also
contain a `[name="issue[title]"]` element.
```html
<dl class="form-group">
<dt><label for="convert-to-issue-title==">Title</label></dt>
<dd><input id="convert-to-issue-title==" class="form-control" type="text" name="issue[title]" value="Example issue title" aria-label="Issue title" autofocus="" required=""></dd>
</dl>
```
Resulting in this error:
```js
content.js:5341 Uncaught Error: Refined GitHub: `sync-pr-commit-title` can’t update the PR title
at maybeShowNote (content.js:5341)
at onMergePanelOpen (content.js:5358)
at HTMLDivElement.<anonymous> (content.js:5293)
at HTMLDivElement.listenerFn (content.js:364)
```
Because `maybeShowNote()` only expects two elements: …
=> Fix `sync-pr-commit-title` with new issue option

readme.md, source/content.ts, source/features/deemphasize-unrelated-commit-references.css
Closes  https://github.com/sindresorhus/refined-github/issues/1579
Follows https://github.com/sindresorhus/refined-github/pull/1794
- Unrelated commits (commit icon is hidden): https://github.com/sindresorhus/refined-github/issues/226#ref-commit-28fc802
- Commits in the current PR (icon is untouched) https://github.com/sindresorhus/refined-github/pull/2387
=> Add `deemphasize-unrelated-commit-references` feature

source/features/open-all-notifications.tsx
Fixes #2397
Follow the instructions in #2397. Happens on all browsers, but with different messages.
The issue occurs, because "Mark all as read" button is missing in repository subpage in Notification, as described in the picture:
Here's [`/notifications`](https://github.com/notifications):
Instead of skipping missing button, we could add the button there. But I think it needs to be treated with caution to prevent bugs like [this one](https://github.com/sindresorhus/refined-github/issues/1634#issuecomment-441174984).
=> Fix errors in `open-all-notifications`

source/features/quick-review-buttons.tsx
Closes #2401
This behavior is already enforced by GitHub, but it only shows up after the form is submitted and the page is reloaded.
This change makes the requirement appear _before_ the form is actually submitted, via client-side validation.
1. Open a PR you can review
2. Click **Comment** or **Request changes**
3. Expect a "Field required" tooltip on the comment field
4. Click **Approve** or **Cancel review**
5. No tooltip will be shown, no comment is required
=> Prevent "Request change" submission without leaving a comment

source/features/quick-review-buttons.tsx
This fixes reviews always requiring a comment even if other review comments are pending
Closes #2418
Not sure if this is a *"to simple"* solution, but this issue prevented me from reviewing so I wanted a *quick* fix :see_no_evil:
=> Soften PR review comment requirement

source/features/show-whitespace.css
Currently selecting text when `show-whitespace` is on is extremely jerky since `::before`s with whitespace indicators do not have `pointer-events: none`.
- https://gist.github.com/pipboy96/95708bb962b9855b731ee9ba34f38046
- https://pipboy96.github.io/assets/refined-github/fix-whitespace-selection-before.webm
- https://pipboy96.github.io/assets/refined-github/fix-whitespace-selection-after.webm
=> Fix whitespace selection

package.json, source/content.ts, source/features/release-download-count.tsx, source/features/reload-failed-proxied-images.tsx, source/features/revert-file.tsx, source/globals.d.ts, source/resolve-conflicts.ts, test/fixtures/globals.ts
Follow-up to #2391 
Perhaps we can just disable `any` for these exceptions. In some cases it can be replaced with `AnyObject` for a cheap workaround. I don't want to risk passing what was in `reload-failed-proxied-images` anymore
=> Stricter usage of `any`

source/features/widen-search-field.css
Technically fixes #2435
GitHub made some weird changes to their css regarding `.subnav` selector on Issues and Pull Requests pages. It looks like they are migrating from the old `.float-left/right` model to flexbox, but at the same time they ignore existing "semantic" classes.
You can also see it on the Releases page where they are using the old `.subnav` and `.d-flex.flex-justify-between`.
I would call this PR a temporary workaround until things settle down with GitHub changes. Also, we should probably expect some more broken features soon.
Open [issues](https://github.com/sindresorhus/refined-github/issues) or [pull request](https://github.com/sindresorhus/refined-github/pulls) page and see.
=> Temporary fix for `widen-search-field`

source/features/close-out-of-view-modals.tsx
Fixes #2328.
As mentioned in https://github.com/sindresorhus/refined-github/issues/2328#issuecomment-522060316, the `details` element can contain content after its `summary` element that is not visible to the user. What we actually need is the `.dropdown-menu` item, which is targeted using the change in this PR.
- Test on user dropdown/create repo dropdown available on every GH page header.
- If you have access to GH Actions, this can be tested on a PR which has one or more failed checks, and you have access to re-run checks.
=> Fix `close-out-of-view-modals` conflict with GitHub Actions UI

source/features/widen-search-field.css
Follows #2436 
https://github.com/issues
https://github.com/pulls
https://github.com/sindresorhus/refined-github/issues
https://github.com/sindresorhus/refined-github/pulls
<details>
<summary>Previous content</summary>
[Issues](https://github.com/sindresorhus/refined-github/issues)
[Pull Requests](https://github.com/sindresorhus/refined-github/pulls)
[Labels](https://github.com/sindresorhus/refined-github/labels)
[Releases](https://github.com/sindresorhus/refined-github/releases)
</details>
=> Fix `widen-search-field` feature

.github/workflows/test.yml, .github/workflows/tests.yml
I think GitHub Actions can replace Travis for testing. Configuration is verbose but it's only done once and the speed increase seems worth it.
Deployment can stay there until https://github.com/notlmn/browser-extension-template/issues/19, it should be unaffected by this PR because Travis still runs the daily cronjob.
PR and branch testing can later be disabled on https://travis-ci.org/sindresorhus/refined-github/settings
=> Move testing to GitHub Actions

readme.md, source/content.ts, source/features/comment-fields-keyboard-shortcuts.tsx, source/features/one-key-formatting.tsx, source/features/tab-to-indent.tsx, source/features/view-markdown-source.tsx, source/libs/blur-field-accessibly.ts
Closes #2414 
Fixes #2413 
Fixes #2148 
1. Focus comment field
2. Press `tab`
3. A `tab` character should be entered
1. Select word in comment field
2. Press `*` key
3. The word should appear as `*word*`
1. Type `@` in comment field
2. Press `tab`
3. The username should be autocompleted without adding any further `tab`s
1. Visit a discussion where you already posted a comment
2. Focus comment field
3. Press `up` key
4. Your previous comment should now be in `Edit` mode
=> Extract `tab-to-indent` and `one-key-formatting` features

source/features/safer-destructive-actions.css
Re-implements the suggestion from #410 which recently broke since GitHub seems to have changed their markup/CSS a bit.
Test in any of your own issues, so I can't link any specific one here. 🙂
=> Fix `safer-destructive-actions` on comments

.github/workflows/no-banned-git-tags.yml
Minor change, I just extracted the git credentials setup to its own action so our workflow is shortened:
https://github.com/fregante/setup-git-token
=> Meta: Use `fregante/setup-git-token` action to enable `git push`

source/features/sticky-discussion-sidebar.tsx, source/libs/on-updatable-content-update.ts
This adds the old selector fix the GHE issue.
It also adds onUpdatableContentUpdate to keep the sidebar sticky after a comment, etc. is posted on the page.
Closes #2409.
Closes #2463.
=> sticky-discussion-sidebar: fixes

source/features/clean-sidebar.tsx
GH updated the selectors on the sidebar for Projects/Milestones sections. I left the old selectors to keep GHE working.
Closes #2474
See URLs in the original issue. Also tested against GHE 2.17.
=> clean-sidebar: update selectors for GH

source/options-storage.ts, source/options.html, source/options.tsx
This updates the `personal token` link in the settings to use the domain from the dropdown to construct the link. When there is no link, it defaults to GitHub. We now show the protocol in the domain dropdown, otherwise I had to infer it for the link.
Closes #2408
I tested it on GH, a random site I gave permission to, and then a GHE instance (2.17) to confirm the settings URL was the same as GH, it is.
=> Update personal token link based off domain selected

readme.md, source/content.ts, source/features/link-to-prior-blame-line.tsx
Closes #2175
- Go to a blame page (i.e. https://github.com/sindresorhus/refined-github/blame/master/readme.md)
- Click on:
- You're on the line number you clicked on, not at the beginning of the document
=> Add `link-to-prior-blame-line` feature

source/libs/dom-formatters.ts, source/options.tsx
Fixes #2460
I decided that the easiest way to fix this was by allowing overwriting the options for `linkify-issues`.
=> Fix issue links in options

source/content.css, source/content.ts, source/features/always-show-branch-delete-buttons.css
Closes #2452 
(Assuming we don't want to show the delete branch button after it hits the 768px width, if we do, I'll change it accordingly)
=> Restore "Delete branch" button in responsive branch list

source/features/improve-shortcut-help.tsx
Noticed that the shortcuts added by RG weren't shown anymore due to:
```
Uncaught TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
```
It seems the selector for the shortcut dialog changed, so I changed it. 
Sadly the new classes *(or other attributes)* are really generic so I made the selector very specific.
=> Fix showing Refined GitHub's keyboard shortcuts

source/features/comments-time-machine-links.tsx
Closes #2187 
- Start a review on a PR by adding a comment (--> it's now "pending")
- Reload the `Files changed` page of the PR
- On the comment that was just added, open the dropdown menu (... button)
--> It shouldn't be broken anymore (unlike in that screenshot, below)
- Go to the `Conversation` tab of the PR and see the pending comment here as well.
- Again, open the dropdown menu (... button)
--> It shouldn't be broken anymore (unlike in that screenshot, above)
Note: I'm not 100% sure where the `View repo at this time` link is meant to be (or if there's some extra condition to see it) as I couldn't see it myself but I could see the error in my console and my fix seems to be solving that... So, please feel free to edit the test scenario with something a bit more accurate if needs be.
=> Fix `comments-time-machine-links` feature for pending review comments

source/features/global-discussion-list-filters.tsx
This change adds some accessibility to the filter links using the aria-label attribute for the filter link.
Adding the title attribute will show more of an explanation if you mouse hover over (which GitHub has for some of the other filter links).
This change adds the extra attributes on the added 'Commented' and 'Yours' filters in the following pages: 
- https://github.com/pulls
- https://github.com/issues
=> Add explanatory tooltips to `global-discussion-list-filters`

source/features/clean-rich-text-editor.css
The markup is slightly different between the new issue toolbar and the comments toolbar (some divs are hidden), which was making the selector fail on the new issue page.
Closes #2428 
- Go to https://github.com/sindresorhus/refined-github/issues/2428 and scroll down. In the toolbar of the editor, the first block of buttons (Header / Bold / Italic) should be hidden.
- Go to https://github.com/sindresorhus/refined-github/issues/new?labels=bug&template=bug_report.md . In the toolbar of the editor, the first block of buttons (Header / Bold / Italic) should be hidden.
=> Hide the correct editor buttons on the New Issue page

source/options.tsx
This makes it easier to find the features that you previously disabled. This only happens on load and _not_ as the user checks/unchecks the features; you don't want things to disappear from the view.
---
=> Move disabled features to the top of the list (Options page)

source/libs/page-detect.ts, test/page-detect.ts
- Enforces tests on all new page detections
- Keeps expected URLs near the function, as examples
- Tests each function with ALL the available URLs in the file, so any new URL added is an automatic _new test_ for all the rest.
They'll be tree-shaken by webpack.
=> Tests all URLs in `page-detect` against each other

source/features/dim-bots.tsx
Closes #2517
Thanks @fregante for the simplified selector
[aws-cdk](https://github.com/aws/aws-cdk/commits/master):
* commits authored by humans but merged by `mergify` shouldn't be dimmed
* as is the case now, commits authored by `dependabot` should be dimmed
=> Allow PR merge-only bots in `dim-bots`

source/options.css, source/options.html, source/options.tsx
This PR adds a feature option search to Refined GitHub's option popup.
Searching for `open batch` will only return one result ("batch-open-issues"); the order of the words doesn't matter. Under the hood, this makes sure that every word in the search pattern matches some part of the feature name and description.
Notes:
- This only searches the feature name & description.
- All matches are case-insensitive.
- The following characters are ignored: <code>,.:;'"’`</code>.
- The following character is replaced with a space: `-`; this allows `"open-batch` to still match "batch-open-issues"
Closes #2147
Open Refined-GitHub's options
=> Meta: Add feature option search

source/features/update-pr-from-base-branch.tsx, source/features/user-profile-follower-badge.tsx, source/libs/api.ts
This has been broken for months and I'm surprised nobody reported it. It's a super useful feature, especially since now it's supposed to work for cross-repo PRs.
Tested in https://github.com/sindresorhus/refined-github/pull/2513 (see the merge commit https://github.com/sindresorhus/refined-github/pull/2513/commits/9a58274d9442427dafd6d533dd92a84e5c2594fa)
To test it, find any PR:
- you're allowed merge,
- is not up to date, and
- has no conflicts (there's a native button in that case)
It should work whether it's a draft PR or not
=> Fix `update-pr-from-base-branch` feature

source/features/html-preview-link.tsx, source/libs/page-detect.ts, source/libs/utils.ts
- Move `isSingleHTMLFile` function to `html-preview-link` ~~(despite https://github.com/sindresorhus/refined-github/pull/2505#discussion_r339354154)~~
- Handle edge cases (e.g. `https://github.com/<user>/<name>.html`)
https://github.com/sindresorhus/refined-github/blob/master/source/options.html (is this fine?)
Sorry I didn't actually find some repo ending with `.html`😅
=> Cleanup `html-preview-link` feature page detection

.github/workflows/test.yml
This should have 2 advantages:
- The `npm test` won't be full with hundreds of lines from AVA test results
- It will be easier to see which of the 3 parts of the testing failed at a glance, without loading the Checks tab:
Disadvantage:
- This disconnects it from the `npm test` command, which would have to be kept in sync (or we can add another generic job for this purpose)
=> Split testing jobs in GitHub Actions

readme.md, source/content.ts, source/features/fix-view-file-link-in-pr.tsx, source/features/raw-file-link.tsx
Closes https://github.com/sindresorhus/refined-github/issues/2260
This feature only works on open PRs.
- Files tab: https://github.com/sindresorhus/refined-github/pull/2529/files
- Latest commit: [#2529/commits/d6ca2e2](https://github.com/sindresorhus/refined-github/pull/2529/commits/d6ca2e2528c237912eb1be0bbd204e3993bf8327)
- _Not_ the latest commit [#2529/commits/3c91c2](https://github.com/sindresorhus/refined-github/pull/2529/commits/3c91c2e0bbd030e98995dc47a529a63e6d9adf09)
- Files tab of a merged PR: https://github.com/sindresorhus/refined-github/pull/2259/files
- Files tab of a closed PR: https://github.com/sindresorhus/refined-github/pull/2472/files
=> Add `fix-view-file-link-in-pr` feature

source/features/pr-branches.tsx
Small design glitch where the PR details from Refined-Github overflow the PR informations (see screenshots below)
Using Github CSS class `mt-1`, it adds a tiny spacing above the PR details injected by Refined Github
=> Pull Request details spacing fix

readme.md, source/content.ts, source/features/linkify-user-location.tsx
Closes #2116
Hover any user or organization profile or visit a user/organization profile, if location is present, it should be turned into a link to Google Maps.
On user profile pages, resize the browser window, the link should be preserved.
---
<details>
<summary>
<b>IssueHunt Summary</b>
</summary>
This pull request has been submitted to:
- [#2116: Hovercard enhancements](https://issuehunt.io/repos/51769689/issues/2116)
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>
=> Add `linkify-user-location` feature

source/features/faster-pr-diff-options.tsx
The text for data-ga-load is actually slightly different on the two buttons so we need a selector that covers both values
Closes #2217
- Go to a single commit view (default) (https://github.com/sindresorhus/refined-github/commit/75624f2acf21abf14fa75ea512cfcab42eeb6a2c)
--> the original split/unified buttons should be hidden and the 'icon-only' buttons should be displayed
- Go to a single commit view (split) (https://github.com/sindresorhus/refined-github/commit/75624f2acf21abf14fa75ea512cfcab42eeb6a2c?diff=split)
--> the original split/unified buttons should be hidden and the 'icon-only' buttons should be displayed
- Go to a single commit view (unified) (https://github.com/sindresorhus/refined-github/commit/75624f2acf21abf14fa75ea512cfcab42eeb6a2c?diff=unified)
--> the original …
=> Avoid duplicate view switcher in `faster-pr-diff-options`

readme.md, source/content.ts, source/features/show-local-user-time.tsx, source/features/user-local-time.tsx, source/globals.d.ts, source/libs/api.ts
This is the first implementation of adding the user's time to their hovercard.
This is done through checking their last commit author date.
<details>
<summary>Screenshot</summary>
</details>
It is still a bit rough implementation and might not be final.
Todos:
Right now most of them just result into an empty time (that is also chached).
Closes #1233
=> Add `user-local-time` feature

source/features/linkify-user-location.tsx
Closes #2581.
I chose slightly different approach: instead of `except: [features.isUserOwnProfile]` it will skip editable nodes by using existing `isEditable` helper. That's because there are two sets of DOM nodes (display and form) on user profile and "Edit profile" button just toggles between those two.
This way displayed location will remain linkified, but editable field will be kept intact.
=> Disable `linkify-user-location` on own editable profile

source/resolve-conflicts.ts
In latest versions of CodeMirror line widgets is nullable, and this cause the problem
Closes #2573
=> Fix `resolve-conflict` feature

package-lock.json, package.json, source/features/clean-issue-filters.tsx, source/features/list-prs-for-file.tsx, source/features/releases-tab.tsx, source/features/user-local-time.tsx, source/libs/get-default-branch.ts
Edit: I replaced `p-memoize` with a new built-in [memoization feature](https://github.com/fregante/webext-storage-cache/pull/5) of [webext-storage-cache](https://github.com/fregante/webext-storage-cache)
Affects (I tested the first 4):
- `clean-issue-filters`
- `list-prs-for-file`
- `releases-tab`
- `user-local-time`
- any additional feature that uses the default branch information
- `warn-pr-from-master`
- `branch-buttons`
- `edit-files-faster`
- `edit-readme`
- `useful-not-found-page`
- `pr-branches`
<details>
<summary>Resolved problems</summary>
Implementation test for https://github.com/sindresorhus/p-memoize/pull/12
- https://github.com/sindresorhus/p-memoize/pull/12#issuecomment-559845913
- I think `releases-count`'s API call is broken
- Currently there's no way to set an …
=> Simplify cache usage (as a memoized function)

source/content.css, source/features/conflict-marker.css, source/features/conflict-marker.tsx, source/features/pr-branches.tsx
Replaces #2522. The `mt-1` class was causing a jump after being added to the dom.
Improves `conflict-marker` color/spacing as well
Lighter is new
=> Improve spacing in discussion lists and avoid jump

source/features/fix-view-file-link-in-pr.tsx
This PR will fix 404 when clicking "View file" on the PR if branch name is namespaced (example: `namespaced/branch`)
With the latest build plugin installed, go to this PR's [Files Changed tab](https://github.com/sindresorhus/refined-github/pull/2595/files) >  click on `...` > click "View file" (bonus: click it "View file" multiple time, by closing the dialog and opening it again over and over)
=> Add support for namespaced branches to`fix-view-file-link-in-pr`

source/features/conflict-marker.tsx, source/features/dim-bots.tsx, source/features/pr-branches.tsx, source/libs/page-detect.ts
This PR will apply PR-related features to mixed lists of Issues and PRs, not just PR-only lists.
Also fixes https://github.com/sindresorhus/refined-github/issues/2582
- `conflict-marker`
- No icon here: https://github.com/sindresorhus/refined-github/pulls?utf8=%E2%9C%93&q=%22Add+%60Releases%60+tab+to+the+repo+page%22+
- Icon appears in non-PR-exclusive search: https://github.com/pulls?utf8=%E2%9C%93&q=author%3Afregante+archived%3Afalse+sort%3Aupdated-desc+rewrite+browser+extension+
- `dim-bots` (now includes issues as well to keep the code simple, but I think we originally didn't include them just because we had no examples of bot-opened issues)
- Bot PRs are hidden in non-PR-exclusive search: https://github.com/issues?utf8=%E2%9C%93&q=user%3Adependabot
- `pr-branches`
1. Open a repo that …
=> Improve PR detection in all discussion lists

source/features/forked-to.tsx, source/features/mark-unread.tsx, source/features/more-dropdown.tsx, source/features/releases-tab.tsx, source/features/sticky-discussion-sidebar.tsx, source/libs/features.tsx
Fixes https://github.com/sindresorhus/refined-github/issues/2604
Naming suggestions welcome. Perhaps `features.onAjaxedPagesInstant` (like the existing `features.onAjaxedPagesRaw`)
This shows a page refresh. Notice how `releases-tab`, `more-dropdown` and `forked-to` are not there for a moment before `dom-ready` happens.
> ![before](https://user-images.githubusercontent.com/1402241/70370051-25e46280-18f5-11ea-8563-a7d78e6db7c8.gif)
Notice how `parse-backticks` still has a FUOC (Flash Of Unstyled Content) but it no longer happens for the 3 features above.
> ![after](https://user-images.githubusercontent.com/1402241/70370062-47dde500-18f5-11ea-9b0c-3479e26644b6.gif)
=> Avoid FOUC on some features

source/features/quick-mention.css
In #2556 I made the button invisible to avoid clutter, but I think it can still look clean if we make it slightly visible. This is not super _accessible_ but it's still more visible than _invisible_
=> Make `quick-mention` button ever-so-slightly more visible

source/features/quick-mention.tsx
Fixes https://github.com/sindresorhus/refined-github/pull/2556#discussion_r357991872
> I think this should say the user name ex: `Mention @fregante in a new comment`
Untested
=> Include user handle in `quick-mention`’s tooltip

source/content.css
Broken following a markup / selector change most likely.
Closes #2631 
Before fix:
After fix:
- Go to the PR list page https://github.com/sindresorhus/refined-github/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc and notice that the filters all have a padding of 8px
- Go to the issue list page https://github.com/sindresorhus/refined-github/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc and notice that the filters all have a padding of 8px
=> Fix spacing on issue/PR list filters

source/features/filter-comments-by-you.tsx
Closes #2647 
1. Go to the PR list page and click on the caret to the left of the input text (i.e. https://github.com/sindresorhus/refined-github/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc)
--> See that a link to `Everything commented by you` is added just before the very last link in the list (`View advanced search syntax`)
2. Click on the link `Everything commented by you`
--> See that the url you're redirected to contains `issues?q=is%3Aopen+commenter:YOUR_USERNAME`
3. Repeat steps 1-2 but go to the issues page instead (i.e. https://github.com/sindresorhus/refined-github/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)
=> Fix `filter-comments-by-you` link on PR list page

source/features/widen-search-field.css
This was using the default value 'stretch' which meant the caret was not vertically aligned within the button.
Closes #2651 
Before fix:
After fix:
- Go to the PR list page (i.e. https://github.com/sindresorhus/refined-github/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc)
- See that to the left of the text filed, there is a button with a vertically aligned caret
- Go to the issues list page (i.e. https://github.com/sindresorhus/refined-github/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)
- See that to the left of the text filed, there is a button with a vertically aligned caret
=> Fix `widen-search-field` caret position

source/features/forked-to.tsx
In https://github.com/sindresorhus/refined-github/pull/2610 all icons where moved around. The [fork icon](https://github.com/sindresorhus/refined-github/pull/2610/files#diff-448a2f6bfa96a35ce700134dafedbc76L79) however was using an class inside the [`forked-to` feature](https://github.com/sindresorhus/refined-github/pull/2610/files#diff-ff16301f232100bd87e910eb98614f66L95-R96).
1. Fork this repo multiple times.
2. See fork icon being aligned again.
=> Fix alignment of fork icon in `forked-to`

readme.md, source/content.ts, source/features/default-branch-button.css, source/features/default-branch-button.tsx, source/features/latest-tag-button.css, source/features/latest-tag-button.tsx, source/options-storage.ts
Closes https://github.com/sindresorhus/refined-github/issues/2635
Partial solution to https://github.com/sindresorhus/refined-github/issues/2624
On default branch: https://github.com/sindresorhus/refined-github
On non-default branch: https://github.com/sindresorhus/refined-github/tree/incremental-tag-changelog-link
On non-default branch (file): https://github.com/sindresorhus/refined-github/blob/incremental-tag-changelog-link/contributing.md
On latest tag (at the moment): https://github.com/sindresorhus/refined-github/tree/20.1.6
=> Make the default branch link smaller in `branch-buttons`

source/features/latest-tag-button.tsx
Context https://github.com/sindresorhus/refined-github/issues/2671
- Adds caching
- Acts before `dom-ready`
=> Faster `latest-tag-button` feature

source/features/default-branch-button.tsx
Context https://github.com/sindresorhus/refined-github/issues/2671
- Acts before `dom-ready`
=> Faster `default-branch-button` feature

source/features/clean-issue-filters.tsx
Context https://github.com/sindresorhus/refined-github/issues/2671
- Acts before `dom-ready`
=> Faster `clean-issue-filters` feature

package.json, source/options.css
See discussion [here](https://github.com/sindresorhus/refined-github/pull/2678#issuecomment-572209852). Stylelint was not running correctly on any other OS then Windows with the glob value.
This PR fixes:
1. the **glob issue**. See proof here: https://github.com/sindresorhus/refined-github/pull/2687/checks?check_run_id=384780372#step:4:9. I couldn't use single quotes `'`, because that resulted in `Error: No files matching the pattern "'source/**/*.css'" were found.`. Using double quotes fixed that.
2. fixes the **errors from stylelint**.
=> Meta: Restore stylelint on all files, cross-platform

source/features/parse-backticks.tsx
Follow-up for https://github.com/sindresorhus/refined-github/pull/2653#issuecomment-571549229
**Adds code highlighting in the following places:**
- Issue/PR references:
- Commmits pushed to a PR:
- Issue/PR title changes:
The last one unfortunately doesn't have a dedicated CSS class. I used `.TimelineItem-body` which targets all timeline items on PRs/issues. It should probably be discussed whether this inclusion is worth it (considering site performance).
=> Enable `parse-backticks` in more places on discussion pages

source/features/ci-link.css
This gives the build status icon some breathing space
Closes #2681
=> Add space between `ci-link` and "Private" label

source/features/show-whitespace.css
Closes: https://github.com/StylishThemes/GitHub-Dark/issues/1050
https://github.com/sindresorhus/refined-github/blob/master/package.json
=> Improve compatibility of `show-whitespace` with GitHub Dark

source/features/sticky-discussion-sidebar.css
Fixes #2576 
This fixes the `z-index` issue with modals opened from the sticky sidebar by increasing the `z-index` of the sidebar.
I set the `z-index` to 110 so the backdrop also overlays the sticky header.
We could also set it to 1 to only overlay the timeline.
=> Fix `z-index` bug caused by `sticky-discussion-sidebar`

source/features/latest-tag-button.css
Closes #2695.
The removed styling only affects the branch-select-menu button, which only appears in one situation. GitHub's own styling is more appropriate.
https://github.com/dr4fters/dr4ft/tree/parse_mtgjson_refactor
=> Fix PR link spacing issue caused by `latest-tag-button`

source/features/highest-rated-comment.tsx, source/features/quick-mention.tsx
Fixes #2623 
Changed the selectors and adjusted the styling a bit so it fits into the timeline again.
=> Restore link to `highest-rated-comment`

source/features/sync-pr-commit-title.tsx
Fixes https://github.com/sindresorhus/refined-github/issues/2713 by avoid renaming merge commits
Fixes https://github.com/sindresorhus/refined-github/issues/1743#issuecomment-530825883 by avoid renaming the PR if the commit title is "the same but clipped"
Fixes: it asks to rename the PR even if it's not necessary, in some cases
Also: slight code cleanup
Test opening/closing/reopening the merge box on a PR you can merge, also switching between Merge/Squash and changing the title.
=> Various fixes for `sync-pr-commit-title`

source/features/comments-time-machine-links.tsx
Closes #2637  
Reproduceable steps:
1. Add a comment (to any PR/issue)
2. Hide the comment
3. Add a second comment
4. Check the hidden comment - there should be only one 'View repo at this time' link
The feature marks comments with a special class to indicate whether the button is there.  
Everytime you add a new comment it will select comments that do not have that class, but the select was looking for that class in the wrong place
=> Avoid duplicate `comments-time-machine-links` in comment dropdown

source/features/link-to-file-in-file-history.tsx
Feature `link-to-file-in-file-history` doesn't work on the second page, because the path contains separators.
Fixes #2692.
Fixes #2711.
No link, no errors
* Page 1 https://github.com/typescript-eslint/typescript-eslint/commits/master
* Page 2 https://github.com/typescript-eslint/typescript-eslint/commits/master?after=367b18f0187ee503c4b21444864027f389a0c69a+34
* Page 1 https://github.com/typescript-eslint/typescript-eslint/commits/master/packages/parser/CHANGELOG.md
* Page 2 https://github.com/typescript-eslint/typescript-eslint/commits/master?after=b5730e02feaec3b66b6e6289ad09d4deadb45592+34&path%5B%5D=packages&path%5B%5D=parser&path%5B%5D=CHANGELOG.md
* Root https://github.com/Cog-Creators/Red-DiscordBot/commits/V3/develop
* Folder …
=> Fix `link-to-file-in-file-history` path detection on page 2+

source/features/emphasize-draft-pr-label.css
Closes https://github.com/sindresorhus/refined-github/issues/2450
The original problem was that the contrast between green and gray was poor. I think this solution increases the contrast without making Draft PRs look bigger.
https://github.com/sindresorhus/refined-github/pulls
https://github.com/WordPress/gutenberg/pulls
=> Change style of `emphasize-draft-pr-label`

source/features/highest-rated-comment.css
**tl;dr:**
---
This PR fixes a minor visual bug I didn't bother to open an issue for: The green border of a highest rated comment carries an `!important` marker only on the main box, not on the triangle on the upper left. This leads to the triangle being incorrectly colored when the comment is focused via a URL anchor (because then there's a `:target` pseudo class in GitHub's CSS which overrules our selector's specificity).
=> Fix style of deep-linked `highest-rated-comment`

source/features/hide-inactive-deployments.tsx
GitHub changed the selector.
* https://github.com/OpenLightingProject/open-fixture-library/pull/425
=> Fix `hide-inactive-deployments`

source/features/show-whitespace.css, source/features/show-whitespace.tsx
Closes https://github.com/sindresorhus/refined-github/issues/2732
I rewrote the feature to limit DOM manipulation. The previous one created a new DocumentFragment for each character, whether it was whitespace or not.
Even this version was slow until I cached `textNode.textContent`; Firefox really doesn't like reading that many times in a loop. Now it's only read once per replacement, which makes the test URL instant. A related bug was opened here but closed as `worksforme`: https://bugzilla.mozilla.org/show_bug.cgi?id=1330475
~~I wonder if manipulation could be further improved with [`Range.surroundContents`](https://developer.mozilla.org/en-US/docs/Web/API/range/surroundContents) but the current solution seems fast enough.~~ Edit: tried, 5x slower: …
=> Improve `show-whitespace` performance on large files

readme.md, source/content.ts, source/features/expand-all-hidden-comments.ts
Closes #1892 
Add `expand-all-hidden-comments` feature. Doing a <kbd>Alt</kbd> + <kbd>Click</kbd> on the `Load more` button will load all the hidden comments in the same page. ~Currently we just recursively click on the button over and over again until there is no more button.~ We use an undocumented API from #2625 to load all the comments. Should we add a maximum limit on how many pages a click should load?
https://github.com/rust-lang/rfcs/pull/2544
GIF: (pay attention to the scroll bar on the right, it takes a long time...)
=> Add `expand-all-hidden-comments` feature

readme.md, source/content.ts, source/features/bugs-tab.tsx
Closes #2749 
<table><td><img width="433" alt="bugs-tab" src="https://user-images.githubusercontent.com/1402241/73720910-a688d900-4755-11ea-9c8d-70e5ddb3bfe5.png"></table>
Your thoughts needed on the ❓ tasks:
=> Add `bugs-tab` feature

source/features/forked-to.tsx
"Open your fork to username/repo" -> "Open your fork **at** username/repo"
English is not my first language, but it seems to make more sense if the address is used as a location?
"Clicking this link will open your fork that can be found at https://github.com/username/repo"
=> Reword tooltip in `forked-to` links

source/content.css, source/features/pr-filters.tsx
Currently, the Draft PR filters are not added to the *Reviews* filter, but to the *Assignee* filter in [some repos](https://github.com/OpenLightingProject/open-fixture-library/pulls) and not at all in [others](https://github.com/sindresorhus/refined-github/pulls). The Status filter is not added in either one.
This PR does the following:
* Fix selectors (to show both filters again)
* Use new dropdown syntax (to fix the layout)
* Fix spacing between dropdown buttons
* Cache CI status for faster Status filter (checks another item from #2671)
* https://github.com/OpenLightingProject/open-fixture-library/pulls
* https://github.com/sindresorhus/refined-github/pulls
* https://github.com/sindresorhus/refined-github/issues (spacing is fixed there, too)
=> Restore `pr-filters` and adjust spacing

source/libs/get-default-branch.ts
1. Visit a new repo, in tag, in a folder (e.g. https://github.com/vega/vega-lite/tree/v4.3.1/bin)
2. See the default branch "back" button appear and have it point to the correct branch
=> Use API v4 to get the default branch

source/features/profile-gists-link.tsx, source/libs/page-detect.ts
Context: #2671 
- Adds cache
- Switches from API v3 to v4
- Uses `element-ready`
---
Discussion: should the tab be added at all if there are no gists? I don't think so, but this might make the feature "slower" since it would _have to_ wait for the API to respond.
I probably never used this link in the first place, so 🤷‍♂️ . cc @sindresorhus
=> Faster `profile-gists-link`

source/features/mark-private-orgs.css, source/features/mark-private-orgs.tsx
I think the "invisible" icon makes more sense than the previous "locked"/"secure" icon. Also this lets us drop the custom inlined icon
=> Change icon for `mark-private-orgs`

source/libs/page-detect.ts
Closes #2792 
The `/milestones/xyc` path wasn't detected as a repo discussion list.
Because of that features like `highlight-collaborators-and-own-discussions` didn't work.
*(I only tested if that feature now works and not any other feature that uses `isRepoDiscussionList` or `isDiscussionList`)*
**Test:**
- https://github.com/sindresorhus/got/milestones/v10
- https://github.com/facebook/react/milestones/17.0.0
=> Apply features to Milestone issue lists

source/features/bugs-tab.tsx
Directly fixes #2780 
Maybe a fuller solution can be implemented in #2805 
https://github.com/sindresorhus/refined-github/issues (no change)
https://github.com/sindresorhus/refined-github/issues?q=is%3Aissue+is%3Aopen+label%3Abug (no change)
https://github.com/sourcegraph/sourcegraph (1033 issues)
https://github.com/godotengine/godot (5000+ issues)
=> Fix Issues count when `bugs-tab` finds 1000+ issues

source/features/ci-link.css
Closes #2762 
Example url: https://github.com/sindresorhus/refined-github/
Before:
After:
(Tested in Firefox 74.0b4 and Chrome 80 on MacOS)
<!-- 
2. TEST URLS:
3. SCREENSHOT:
=> fix: adjust ci indicator vertical alignment

readme.md, source/features/sync-pr-commit-title.tsx
The readme currently describes the `sync-pr-commit-title` rule as "Uses the PR’s title **and description** when merging" (emphasis mine). Our team was excited to see this, since this is exactly the behavior we were looking for - it is a better fit than the default for our workflow of squash merges with a detailed PR template + frequent/small/low-information commits, similar to the workflow @billdybas [describes in his comment on #1934](https://github.com/sindresorhus/refined-github/pull/1934#issuecomment-494463918).
In PR #1934 (commit 9be9440), the addition of the `sync-pr-commit-title` feature intentionally removed the `fix-squash-and-merge-message` feature; the response to PR #2021 makes it abundantly clear that a replacement, even opt-in, will not be considered. We are saddened by …
=> Fix readme for sync-pr-commit-title to match current functionality

source/libs/utils.ts
On ajaxed pages, an extra <link> tag is added so we need to get the last one to figure out what the current branch is.
Closes #2799 
1. Visit https://github.com/sindresorhus/refined-github/commit/bf5dce817b31cea8c4d1535759adc81cc194d305
2. Refresh the page
3. Click the "Code" tab
4. Note that there is NO 'left arrow' button next to the branch dropdown, unlike here:
5. Repeat steps 1 to 4 with a single file url, i.e. https://github.com/sindresorhus/refined-github/blob/bf5dce817b31cea8c4d1535759adc81cc194d305/source/features/profile-gists-link.tsx
<!-- 
2. TEST URLS:
3. SCREENSHOT:
=> Don't show unnecessary `default-branch` after AJAX navigation

source/features/parse-backticks.tsx
Test on https://github.com/eslint/eslint/issues
=> Enable `parse-backticks` on pinned issues

source/features/shorten-links.tsx
I don't know if this is a GitHub bug or to highlight the matched keywords, URLs in repo description on the search page aren't completely linkified, and `shorten-links` makes it even more inaccessible:
Sure it will be better if we can fix this up, but it may be difficult to handle various situations. I think this should be implemented by GitHub itself first.
So this PR ~~add `linkifiedURLClass` to these URLs to make `shorten-links` skip them~~ disables `shorten-links` on search page:
Test URL: https://github.com/search?q=nodejs
=> Don't apply `shorten-links` on search results

source/features/global-discussion-list-filters.tsx, source/libs/search-query.ts
The `@me` filter is not available at enterprise github at least not for v2.18.8
i left out commented-by-you feature as there is #2809 
<!-- 
2. TEST URLS:
3. SCREENSHOT:
=> Revert usage of `@me` search keyword to restore GHE support

source/features/pr-branches.tsx
this feature is not working, as there is no single repoOwner and repo in
this list.
<!-- 
2. TEST URLS:
3. SCREENSHOT:
=> Avoid console errors by `pr-branches` on global discussion lists

source/features/filter-comments-by-you.tsx
in github enterprise the old html template is still in use
at least for Enterprise v2.18.8
hint, i am using `getUserName()` instead of `@me`, in enterprise `@me` is not available.
=> Restore `filter-comments-by-you` on GHE

readme.md, source/content.ts, source/features/mark-merge-commits-in-list.css, source/features/mark-merge-commits-in-list.tsx
closes #2827 
I hate typescript
I did not add the icon since typescript would not let me.
~wasted~ used about an hour because if it :confused:
https://github.com/babel/babel/commits/master?after=ddd40bf5c7ad8565fc990f26142f85613958a329+104
=> Add back `mark-merge-commits-in-list` feature

source/features/emphasize-draft-pr-label.css
Fixes #2755 
Screenshots in Brave 1.3.118 (Chromium 80.0.3987.116) on Ubuntu 18.04.4 LTS
Before:
After:
=> Change `emphasize-draft-pr-label` style

source/features/repo-age.tsx
As discussed on https://github.com/sindresorhus/refined-github/pull/2667#issuecomment-571003482. This merge request change enables the usage of the first commit for the repo-age.
The change is backward compatible so we don't need to worry about existing cached values in user browsers.
Closes https://github.com/sindresorhus/refined-github/issues/2660
1. https://github.com/sindresorhus/refined-github/tree/ava
2. https://github.com/sindresorhus/refined-github
3. https://github.com/getify/You-Dont-Know-JS
=> Determine `repo-age` with its first commit
