source/features/user-local-time.tsx
When hovering over usernames, sometimes it showed a local time in the hour after midnight:
That looks strange to me, normally I see those times beginning "00:xx", not "24:xx". I guess I'm not used the US locale.
Use the browser's default locale, with fallback to `en-US`:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat#Examples
=> Show `00:mm` instead of `24:mm` in `user-local-time`

source/features/more-dropdown.tsx
=> Fix broken Compare icon in `more-dropdown`

source/features/dim-bots.css
I have this strange feeling when I open GitHub today... it seems they have changed their mockup somehow. When I saw commit history page, I knew it was true.
**Chrome**
**Firefox**
This PR kindly stops the performance of these gorgeous buttons and fix `dim-bots` up.
- https://github.com/renovatebot/renovate/commits/master
- https://github.com/kidonng/readhub/commits/master
=> Fix `dim-bots` styles

source/features/latest-tag-button.tsx
- Retry earlier
- `aheadBy`'s cache key should include the tag itself, otherwise it might return the information for a previous tag
<!-- 
2. TEST URLS:
3. SCREENSHOT:
=> Cache improvements for `latest-tag-button`

source/features/repo-age.tsx
I am not sure the `.commit-meta` is even needed
see https://github.com/sindresorhus/refined-github/pull/2783#discussion_r388907440
=> Fix `repo-age` selector

source/features/more-dropdown.tsx, source/features/releases-tab.tsx, source/libs/dom-utils.ts, source/libs/utils.ts, test/utils.ts
Closes #2763 
- Go to https://github.com/sindresorhus/refined-github/
- Go to https://github.com/atom-community/sync-settings
- Go to https://github.com/aritchie/settings
--> The `releases` tab should be right before the `More` tab
<!-- 
2. TEST URLS:
3. SCREENSHOT:
=> Fix `releases-tab` position on repo with "settings" in their name

package-lock.json, package.json, source/features/forked-to.tsx, source/libs/utils.ts
Closes #2759 
Closes #2885 
Cases tested:
- User has no organizations (no action taken)
- User has 1 fork (icon shown)
- User has 1 fork and is currently visiting it (no icon shown)
- User has 2 forks (dropdown shown)
- User has 2 forks and is currently visiting 1 (dropdown shown, 1 fork selected)
Edge cases that work but aren't strictly supported:
- User has forked a fork (the "source" repo points to the first fork, so the UI might not be exactly what's expected)
=> Improve `forked-to` reliability

source/features/list-prs-for-file.css, source/features/list-prs-for-file.tsx
Fixes https://github.com/sindresorhus/refined-github/issues/2624
- Groups multiple PRs under a dropdown in `isSingleFile`
- Improves "single PR" wording and style in `isEditingFile`
- Drops tooltips everywhere except "single PR" `isSingleFile` (everywhere else, links have context)
https://github.com/sindresorhus/refined-github/blob/master/source/content.ts 
https://github.com/sindresorhus/refined-github/edit/master/source/content.ts
https://github.com/sindresorhus/refined-github/blob/master/source/features/releases-tab.tsx
https://github.com/sindresorhus/refined-github/edit/master/source/features/releases-tab.tsx
=> Improve `list-prs-for-file`'s display

source/content.css, source/features/batch-open-issues.tsx, source/features/pr-filters.tsx
Closes #2888 
- Go to the security page of a repository i.e. https://github.com/sindresorhus/refined-github/network/alerts
Note: you need to have some security alerts for the filter to be displayed
- See that the sort filter on the right-hand side of the bar has some padding-right.
Before:
After:
Note: the selector isn't great but the markup is quite different on the security page than the other pages so I didn't want to make it overly complex just to have one selector that matched all the use cases.
<!--
2. TEST URLS:
3. SCREENSHOT:
=> Adjust filters padding on Security page

source/features/clean-sidebar.css, source/features/clean-sidebar.tsx
Closes #2773 
This feature depends on:
- whether you can edit the issue/pr
- whether each section is full or empty
So open [one of your favorite repos](https://github.com/sindresorhus/refined-github/issues?q=sort%3Aupdated-desc) and go through its issues to double-check their sidebar
<table><td><img width="239" alt="b" src="https://user-images.githubusercontent.com/1402241/77234010-9b75f500-6bab-11ea-9b06-7696b308090b.png"></table> <table><td><img width="242" alt="a" src="https://user-images.githubusercontent.com/1402241/77234011-9b75f500-6bab-11ea-9b64-f7d373b851b0.png"></table> <table><td><img width="238" alt="c" src="https://user-images.githubusercontent.com/1402241/77234008-9add5e80-6bab-11ea-9343-db561211ab3f.png"></table>
"Reviewers" sometimes isn't removed because GitHub sets "No …
=> Clean `clean-sidebar` and also clean "Linked issues" section

source/features/latest-tag-button.tsx, source/libs/utils.ts, test/utils.ts
Fixes #2239 
I can't find a repo that has pre-releases right now, but I also **included some automated tests** to make sure the algorithm works.
=> Exclude pre-releases from `latest-tag-button`

source/features/reactions-avatars.css, source/features/reactions-avatars.tsx
Fixes https://github.com/sindresorhus/refined-github/issues/1744
- Issues are now responsive, we can't use previous JS solutions that only run on load
- CSS Grid doesn't allow automatic wrap
- CSS `flex-grow` can't be used because if there's a 1-avatar reaction on the second line, it will be stretched along the whole line, making it huge
Some aren't great, but that's just how it is 🤷‍♂️
=> Wrap reaction avatars to avoid "CSS IS AWESØME"

source/features/preserve-file-finder-term.tsx
Don't throw an error when there is no history
Error mentioned in #2907
<!--
2. TEST URLS:
3. SCREENSHOT:
=> Avoid console error in `preserve-file-finder-term`

readme.md, source/features/expand-all-hidden-comments.ts
Fixes #2931
Just saw your comment,
>What we can do, if easy, is to limit it to ~200 items
Should I 200?
<!--
2. TEST URLS:
3. SCREENSHOT:
=> Limit `expand-all-hidden-comments` to 200

source/features/expand-all-collapsed-code.tsx
Closes #2939
https://github.com/microsoft/TypeScript/commit/55218d64a58a9964229daa0a38bdfb0a6be717e5#diff-46fd87925e4552c166ec188712741c3f
Not sure if this is what you had in mind.
<!--
2. TEST URLS:
3. SCREENSHOT:
=> Stop `expand-all-collapsed-code` with `esc`

.github/workflows/deploy-auto.yml
Due to https://github.com/notlmn/browser-extension-template/issues/25
@sindresorhus can you generate and set a token in the secrets? E.g. `TAGGER_TOKEN`
=> Fix deployment cronjob

source/features/deep-reblame.tsx
Fixes #2949
@fregante how do you want to handle the message?
Related PR in commit title: it should "enter" it https://github.com/sindresorhus/refined-github/blame/b5497da33a6c5b99eb518ecc266881780bc11877/contributing.md#L7
Unrelated PR in commit title: it should `alert()` https://github.com/sindresorhus/refined-github/blame/d1e27cb34f18b9d5d57fdbf853e5b15c3a660d85/source/features/deep-reblame.tsx#L67
Renamed file: it should `alert()` 
https://github.com/sindresorhus/refined-github/blame/fad67fb8d8fcf608601c9b8ae1b5f12337cbccce/source/options.html#L1
<!--
2. TEST URLS:
3. SCREENSHOT:
=> Don't 404 `deep-reblame` on renamed files

octicon-svg-loader.ts, package-lock.json, package.json, webpack.config.ts
The build used to:
1. For every SVG, create a module that exports JSX
2. Use Buble to transpile that JSX into `dom-chef` calls
Now:
1. For every SVG, create a module that exported an SVG element
This is done by using [doma](https://github.com/fregante/doma)/`innerHTML` instead of going through JSX first
Pros:
- 89 bytes saved (!!!)
- 0s build time shaved (_!**!**!_)
- 2 fewer dependencies (and a dozen subs)
- an enviable `+4 -188` diff stat
This is what webpack outputs:
```diff
-   var check = function() {
-     return dom_chef["a"].createElement("svg", {
-       class: "octicon octicon-check",
-       xmlns: "http://www.w3.org/2000/svg",
-       width: "12",
-       height: "16",
-       viewBox: "0 0 12 16"
-     }, dom_chef["a"].createElement("path", {
-       "fill-rule": "evenodd",
- …
```
=> Simplify Octicons build by dropping Buble

source/features/ci-link.tsx
Fixes https://github.com/sindresorhus/refined-github/issues/2884#issuecomment-611991396
Has icon: https://github.com/sindresorhus/refined-github/commits/master
Every commit has a CI run, `ci-link` should be shown
No icon: https://github.com/samuelmeuli/font-picker/commits/master
The last CI run was last year, `ci-link` should **not** be shown
=> Only look for `ci-link` in the last 2 days of commits

source/features/profile-gists-link.tsx
Follows https://github.com/sindresorhus/refined-github/pull/2981#discussion_r404920120
There was (never) any need to exclude. `isUserProfile`'s selector does not exist on `isOrganizationProfile`
Test on
https://github.com/highlightjs
<!--
2. TEST URLS:
3. SCREENSHOT:
=> Remove useless exclude from `profile-gists-link`

readme.md, source/features/deemphasize-unrelated-commit-references.css, source/refined-github.ts
The feature has been added by GitHub
=> Drop `deemphasize-unrelated-commit-references`

source/features/clone-branch.tsx
I know you said https://github.com/sindresorhus/refined-github/pull/2896#issuecomment-599794812
>Ah you're talking about the filter: when used, the buttons don't appear. That's ok, not a big deal enough to add observeElement
But with #3022 it looks funny that the dom changes when you do a search
Test on: https://github.com/sindresorhus/refined-github/branches
If you need a gif ping me...
<!--
2. TEST URLS:
3. SCREENSHOT:
=> Keep `clone-branch` after a search

readme.md, source/features/action-used-by-link.tsx, source/libs/page-detect.ts, source/refined-github.ts
Fix #3009
URLs to check it from
* https://github.com/marketplace/actions/urlchecker-action
* https://github.com/marketplace/actions/github-action-for-assignee-to-reviewer (no result! which I think is not a bug but surprised me because it was the first action featured on https://github.com/marketplace?type=actions)
* https://github.com/marketplace/actions/hugo-actions
=> Add `action-used-by-link` feature

readme.md, source/features/open-all-notifications.css, source/features/open-all-notifications.tsx
Fixes https://github.com/sindresorhus/refined-github/issues/2911
Replaces #3046
Try both the "Grouped by date" and "Grouped by repository" representations
=> Restore `open-all-notifications` feature

readme.md, source/features/linkify-notification-repository-header.tsx, source/refined-github.ts
Partial fix for #3030 
https://github.com/notifications (only the inbox has this kind of grouping)
=> Add `linkify-notification-repository-header` feature

package.json, source/options.css, source/options.html, source/options.tsx
Debugging tools are useful during development, they should be more visible then.
This PR moves them higher (only during development) and highlights them.
=> Highlight debugging tools when side-loaded

source/features/clean-issue-filters.tsx
Test on https://github.com/fregante/slash-tag-test/issues
The errors shows up only on Chrome, apparently because they happen inside Promises:
```
Uncaught (in promise) TypeError: Cannot read property 'parentElement' of undefined
at hideMilestones (refined-github.js:11936)
Uncaught (in promise) TypeError: Cannot read property 'parentElement' of undefined
at hideProjects (refined-github.js:11954)
```
=> Fix console errors in `clean-issue-filters`

source/features/batch-open-issues.tsx
Closes #2671 (or at least ticks its last checkbox).
Test here: https://github.com/sindresorhus/refined-github/pulls
Or here: https://github.com/sindresorhus/refined-github/issues
=> Make `batch-open-issues` faster

source/features/highest-rated-comment.css, source/features/highest-rated-comment.tsx, source/globals.d.ts
[GitHub Discussions](https://github.com/zeit/next.js/discussions/12559#discussioncomment-9555) have a "Selected answer" style we can reuse.
https://github.com/facebook/create-react-app/issues/1333#issuecomment-327776666
=> Update `highest-rated-comment` style to match a Discussion "Answer"

source/features/clean-sidebar.tsx
Fixes #3076 
Follows https://github.com/sindresorhus/refined-github/pull/2916
1. Allows "Convert to draft"
1. Hides "No reviewers" when `canEditSidebar` (because GitHub tries suggesting reviewers in that case)
I hope at some point they move this awkward "Convert to draft" button, it should not be in the Reviewers section
=> Improve Reviewers hiding in `clean-sidebar`

source/features/warning-for-disallow-edits.tsx
Bug:
1. Open any PRs from https://github.com/pulls (that you made from a fork)
2. Toggle checkbox
=> Fix position of `warning-for-disallow-edits`

source/features/open-all-notifications.tsx
Fixes #3066
On unsaved filters like https://github.com/notifications?query=reason%3Acomment, the button was being added to the wrong place:
---
<details>
<summary>
<b>IssueHunt Summary</b>
</summary>
This pull request has been submitted to:
- [#3066: "Open (all) unread" is not shown on repository specific notifications list](https://issuehunt.io/repos/51769689/issues/3066)
---
</details>
=> Show `open-all-notifications` on unsaved filters

source/features/remove-checks-tab.tsx
None
2. TEST URLS:
https://github.com/RandomEngy/VidCoder/pull/490
3. SCREENSHOT:
None
~~One thing to note `pageDetect.isRepoWithAccess`~~ 
~~https://github.com/fregante/github-url-detection/blob/f88d029d45d29a31ec6c91de6b1588ea30874986/index.ts#L318~~
~~does not include~~
```js
'.pagehead-tabs-item[href$="/settings/profile"]' // In organizations
```
~~@busches can you check?~~ sorry I mixed up organizations and enterprises 
Edit: There is no need for that check here its only on `isOrganizationProfile` so it was never needed
=> Simplify `remove-checks-tab`

package-lock.json, package.json, source/features/show-open-prs-of-forks.tsx
Fixes #2934 I also fixed a console error while I was at it. Follows https://github.com/sindresorhus/refined-github/issues/2934#issuecomment-604146813 (I changed it to headRepository because I think that is correct)
2. TEST URLS:
I tested on https://github.com/talknsmile/refined-github which is a fork of my fork and I have 3 local PR's open and I have only one pull request
3. SCREENSHOT:
Before
After
=> Fix `show-open-prs-of-forks` to only include related PRs 

source/features/reactions-avatars.tsx
Fixes #3122
The gif shows the initial implementation, which triggers the requests as soon as the reactions become visible.
Adding `rootMargin` to the `IntersectionObserver` will make them load sooner
PR best reviewed without whitespace: https://github.com/sindresorhus/refined-github/pull/3126/files?diff=split&w=1
https://github.com/facebook/react/issues/13991
https://github.com/sindresorhus/refined-github/issues/3122
Any PR/issue like this one ⬇️
=> Restore `reactions-avatars`

source/features/dim-bots.css
Fixes #3124
Solution:
- The overflow-hidden property is moved to not:navigation-focus
- Implemented a scroller for text that exceeds the container, which was not the case before.
**TEST URL**
https://github.com/kulshekhar/ts-jest/commits/master
=> Avoid clipping descriptions and CI status messages in `dim-bots`

source/features/add-tag-to-commits.tsx, source/features/bugs-tab.tsx, source/features/esc-to-deselect-line.tsx, source/features/recently-pushed-branches-enhancements.tsx, source/features/revert-file.tsx, source/features/selection-in-new-tab.tsx, source/features/show-names.tsx
Continues #3119
- Reuse filePath var in `revert-file`
- Makes recently-pushed-branches-enhancements not fall off the screen #2940 (Does not fix it, just makes it not as bad)
- Don't run `show-names` on app bots (Revert's the change I made) _Fixes https://github.com/sindresorhus/refined-github/issues/3133_
- Use `getRepoURL` instead of `getOwnerandRepo` for `add-tag-to-commits`
- Don't highlight bugs tab when on the PR tab (Continues fixing #3001)
- Run `esc-to-deselect-line` only on code pages
- Don't error `selection-in-new-tab` if there is no element to mark unread (in RepoRoot for example)
=> Minor bug fixes

source/features/more-dropdown.tsx, source/features/releases-tab.tsx
Fixes #3102.
GitHub likely changed their DOM and moved all the items inside `.reponav` into an unordered list. This change makes sure that we add elements inside that list, and not as its siblings.
Bug explained at https://github.com/sindresorhus/refined-github/issues/3102#issuecomment-630102823 and https://github.com/sindresorhus/refined-github/issues/3102#issuecomment-630209900.
On any repo that you are admin of, take a look at navigation tab order.
=> Fix position of `more-dropdown` and `releases-tab`

source/features/pr-commit-lines-changed.tsx
We can get the commit hash from the pathname then just wait for diffstat to be available
Test On:
[https://github.com/sindresorhus/refined-github/pull/3145/commits/3d3d50b01f47a230758aae1095e4116527591f7f ](https://github.com/sindresorhus/refined-github/pull/3145/commits/3d3d50b01f47a230758aae1095e4116527591f7f)
=> Faster `pr-commit-lines-changed`

source/features/clear-pr-merge-commit-message.tsx
Closes https://github.com/sindresorhus/refined-github/issues/3140
Testable on your PRs. Try on in https://github.com/pulls?q=is%3Aopen+user%3A%40me+sort%3Aupdated-desc
=> Exclude 1-commit PRs from `clear-pr-merge-commit-message`

source/features/comments-time-machine-links.tsx
Fixes https://github.com/sindresorhus/refined-github/issues/1953
Closes https://github.com/sindresorhus/refined-github/issues/2618
Related to https://github.com/sindresorhus/refined-github/issues/2131
Ancestor of https://github.com/sindresorhus/refined-github/pull/1863
Prophecy of https://github.com/sindresorhus/refined-github/issues/1448 🪁
To test this feature, click the test links in https://github.com/sindresorhus/refined-github/issues/2618 (the feature depends on comment date)
Also here are two pre-edited links to see what they look like:
```
Still exist: https://github.com/sindresorhus/refined-github/blob/master/source/features/comments-time-machine-links.tsx?rgh-link-date=2019-12-11T10%3A12%3A11Z
File deleted: https://github.com/sindresorhus/refined-github/blob/master/source/features …
```
=> Only show `comments-time-machine-links` after visiting the link

octicon-svg-loader.ts, package-lock.json, package.json, source/features/bugs-tab.tsx, source/features/minimize-upload-bar.tsx, source/features/release-download-count.tsx, source/features/tags-dropdown.tsx, webpack.config.ts
GitHub.com just switched to the [new icons](https://primer.style/octicons-v2/) even though they're not "stable" on npm for use to use. However I want to update RGH asap to _preserve the illusion_ and make any improvements later
There are 2 issues:
- bug.svg no longer exists: https://github.com/primer/octicons/issues/430
I avoided this issue by keeping the older v1 around just for this icon.
- every filename now ends with `-16.svg`.
I avoided this issue by using the last "v2" version without this requirement. This will have to be fixed once they're "stable"
=> Use Octicons v2

source/refined-github.css
Hi,
fixes a misaligned icon I noticed after the recent `octicons` update. Not sure if this is the best way to go about it, feel free to close in case there is a better way to achieve this.
Before:
After:
Thanks for maintaining this extension! :sunny:
=> Reset vertical-align for new octicons in js-issue-row

source/features/add-tag-to-commits.tsx, source/features/clean-issue-filters.tsx, source/features/index.tsx, source/features/mark-unread.tsx, source/features/remove-projects-tab.tsx, source/features/resolve-conflicts.tsx, source/features/show-followers-you-know.tsx, source/github-helpers/get-default-branch.ts, source/helpers/dom-utils.ts
Fixes one error and lint's a few more
- Wait for milestone and project dropdowns to be ready
Looks like Github does not **always** load them right away. ( I dont get the error every time)
```javascript
refined-github.js:12163 Uncaught (in promise) TypeError: Cannot read property 'parentElement' of null
at hideMilestones (refined-github.js:12163)
at clean_issue_filters_init (refined-github.js:12189)
at async runFeature (refined-github.js:5637)
at async setupPageLoad (refined-github.js:5651)
hideMilestones @ refined-github.js:12163
clean_issue_filters_init @ refined-github.js:12189
async function (async)
clean_issue_filters_init @ refined-github.js:12185
runFeature @ refined-github.js:5637
setupPageLoad @ refined-github.js:5651
add @ refined-github.js:5708
async function (async)
add @ …
```
=> Lint and add missing screenshots

source/features/improve-shortcut-help.tsx, source/features/index.tsx
Follows
>I think this is the format I was referring to
>
>```suggestion
>		shortcutMap.set(hotkey, description);
>```
>
>_Originally posted by @fregante in https://github.com/sindresorhus/refined-github/pull/3160_
_Was almost related to this PR_ but https://github.com/fregante/webext-additional-permissions/blob/master/index.ts#L15 uses flatMap and that is only supported from [firefox 62](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap#Browser_compatibility) currently were set to 61
=> Meta: Change format of shortcuts map

source/options.tsx
As mentioned in #3168 
The `init` function is [73-lines long](https://github.com/sindresorhus/refined-github/blob/8b86ff97aa652475792ee9c2e1c86f92cfe35120/source/options.tsx#L54-L127). This PR brings it down to a more reasonable 33-lines.
Suggestions welcome, but know that almost everything depends on these 2 lines
```js
// Generate list
select('.js-features')!.append(...__featuresMeta__.map(buildFeatureCheckbox));
// Update list from saved options
await perDomainOptions.syncForm('form');
```
=> Split `options.tsx`’ `init` function into multiple parts

readme.md, source/features/clean-sidebar.tsx, source/features/faster-reviews.css, source/features/faster-reviews.tsx, source/refined-github.ts
Closes #3095, closes #1069, closes #883.
Test this on any PRs, both ones you can request reviews for and ones you can't.
1. ~`quick-review-buttons` (and maybe other features?) don't run in this popup.~ Changed behavior based on https://github.com/sindresorhus/refined-github/pull/3149#discussion_r431683606
2. ~Update the screenshot after the other features are enabled.~ Done
=> Add `faster-reviews` feature

source/features/reactions-avatars.tsx
Closes #3122
>PR welcome to drop the first ~10 lines of `showAvatarsOn`
>
>_Originally posted by @fregante in https://github.com/sindresorhus/refined-github/issues/3122#issuecomment-639110887_
=> Restore `reactions-avatars` again

source/features/repo-age.tsx
Follows 
>Hardik can you implement the link to the first commit as well? https://github.com/sindresorhus/refined-github/pull/2667/files#diff-9d82f672e2199b6b2b455fa80d3373f2R86
>_Originally posted by @fregante in https://github.com/sindresorhus/refined-github/pull/2783#issuecomment-636680756_
This will cause issues, with the cache due to the href being empty. I am not sure how to go about it.
=> Make `repo-age` a clickable link

source/features/toggle-files-button.css
Relates to #3081.
With feature preview enabled:
With feature preview disabled:
=> Restore `toggle-files-button` in "Repository refresh" beta

source/features/remove-upload-files-button.tsx
=> Disable `remove-upload-files-button` in "Repository refresh" beta

source/features/stop-redirecting-in-notification-bar.tsx
Closes #3173
Feature originally implemented in #2952 and #3036.
=> `stop-redirecting-in-notification-bar` automatically when possible

source/features/releases-tab.tsx
Relates to #3081.
With feature preview enabled:
With feature preview disabled:
=> Restore `releases-tab` in "Repository refresh" beta

.github/workflows/test.yml
When opening PRs from the current repo, each commit gets tested twice.
This should limit duplication, but it means that the CI won't run on secondary branches **until you open a PR.** This is fine since we have draft PRs.
<table><th>Before<th>After
<tr><td><img width="399" alt="before" src="https://user-images.githubusercontent.com/1402241/83930196-a695f580-a796-11ea-94d9-967c4b601fbb.png">
<td valign=top><img width="389" alt="after" src="https://user-images.githubusercontent.com/1402241/83930207-b8779880-a796-11ea-8135-f9e9c79a5131.png">
=> Meta: Reduce GitHub Actions runs on local PRs

source/options.tsx
Chrome attempts to open them in the options popup which leads to
Firefox does not have this issue
**To be clear:** I am talking about the screenshot and source links
=> Chrome: Open the options source/screenshot links in a new tab

source/features/releases-tab.tsx
Fixes the issue found by @yakov116 in https://github.com/sindresorhus/refined-github/pull/3186#issuecomment-640546353:
The `.UnderlineNav` selector was too unspecific and also matched the tab bar inside the "Open with" popup.
=> Fix `releases-tab` selector for "Repository refresh" beta

source/features/download-folder-button.tsx
=> Restore `download-folder-button` in "Repository refresh" beta

source/features/faster-reviews.tsx
I think the picture does all the explaining
https://github.com/chalk/chalk/pull/392 really any pr
Press the conversation tab a few times, to get even more review nows :)
=> Avoid duplicate `fast-reviews` links

source/refined-github.css
GitHub added this: 
So we can remove most of this:
And now it looks like this:
Related: https://github.com/sindresorhus/refined-github/issues/963 
Partially undoes: https://github.com/sindresorhus/refined-github/pull/2553
=> Hide duplicate "You can also open this in GitHub Desktop" in PRs

source/features/faster-reviews.tsx, source/features/releases-tab.tsx, source/github-helpers/index.ts
Fix releases tab not ever running from api. It returned false and were using ??.
I think it may make more sense to do `pageDetect.isRepoRoot() ? parseCountFromDom() : fetchFromApi()` Not sure
Also fixes attempting to apply a shortcut in `faster-reviews` on locked pr's
Test on https://github.com/yakov116/TestR/pull/6
=> Fix console errors and make `releases-tab` more reliable

readme.md, source/features/clean-pinned-issues.css, source/features/pinned-issues-update-time.tsx, source/refined-github.ts
Closes #3179 
https://github.com/sindresorhus/refined-github/issues (3 pinned issues)
https://github.com/avajs/ava/issues (2 pinned issues)
https://github.com/facebook/react/issues (0 pinned issues)
<details>
<summary>Old, <code>display:flex</code> version</summary>
</details>
=> Add `clean-pinned-issues` feature

source/features/default-branch-button.tsx, source/features/latest-tag-button.tsx, source/features/list-prs-for-file.tsx
Design fix for <https://github.com/sindresorhus/refined-github/issues/3081#issuecomment-643198654> / <https://github.com/sindresorhus/refined-github/pull/3205#issuecomment-641926371>.
Note that I didn't change the button size for `latest-tag-button` and `list-prs-for-file`; I just centered them, as that looks better IMO.
<details>
<summary>See how it looks with changed button sizes instead:</summary>
</details>
=> Fix button styles in "Repository refresh" beta

source/features/repo-age.tsx
References #3081, follows <https://github.com/sindresorhus/refined-github/pull/3201#issuecomment-641948774>.
Test this on any repo, e.g. <https://github.com/sindresorhus/refined-github>. Note that you should clear the cache to test if the commit link can be extracted correctly.
=> Restore `repo-age` in "Repository refresh" beta

source/github-events/on-new-comments.ts
This is similar to how lazy handlers are added in `on-pr-file-load`, and as `include-fragment` is not a direct descendant of `details` element.
Related to #2852, but doesn't exactly fix that. Stilling figuring out on how to handle that.
=> Fix handling lazy-loaded comments

package-lock.json, package.json, source/features/patch-diff-links.tsx, source/features/useful-not-found-page.tsx
Add a second `init` function in `useful-not-found-page` that acts on not found PR commits. These can happen if you link to the PR commit (`/repo/pull/number/commits/commit_ref`) instead of the commit itself (`/repo/commit/commit_ref`)<sup>1</sup> and the PR gets force-pushed.
Test: [`32c8a88` (#3227)](https://github.com/sindresorhus/refined-github/pull/3227/commits/32c8a88360a85739f151566eae0225d530ce6a15) (should link to https://github.com/sindresorhus/refined-github/commit/32c8a88360a85739f151566eae0225d530ce6a15)
<sup>1</sup>: We actually encourage to do so in `prevent-pr-commit-link-loss`, maybe that's the reason why GitHub doesn't use PR commit links by default.
=> Improve PR commit 404 page

package-lock.json, package.json, source/github-helpers/get-default-branch.ts
Follows https://github.com/sindresorhus/refined-github/issues/3239#issuecomment-646072282
**Note:** `isRepoTree`cannot be used instead of `!String(getRepoPath()).startsWith('tree/')` since `isRepoTree` includes `isRepoRoot`
=> Make `getDefaultBranch` quicker on `isRepoHome`

source/features/dim-bots.css, source/features/dim-bots.tsx, source/features/pr-branches.tsx
Fixes https://github.com/sindresorhus/refined-github/issues/3232
Follows https://github.com/sindresorhus/refined-github/pull/3128 
Follows https://github.com/sindresorhus/refined-github/pull/2864
Instead of clipping via `height` and `overflow: hidden`, I'm just using negative margins to collapse the meta information.
- No more visible overflow
- No more clipped titles (because there's no fixed height)
Also some selectors needed to be updated because lists no longer use `display: table` :tada:
https://github.com/facebook/react/pulls?q=bump
https://github.com/kulshekhar/ts-jest/commits/master?after=3247ae409af4d9e47acf1ac31707b970f829e990+104
=> Improve `dim-bots`’s behavior

source/features/comments-time-machine-links.tsx
Closes #3244
2. TEST URLS:
Should not show
https://github.com/sindresorhus/refined-github/blob/master/source/features/comments-time-machine-links.tsx
Should show
```
https://github.com/sindresorhus/refined-github/blob/master/source/features/comments-time-machine-links.tsx?rgh-link-date=2019-12-11T10%3A12%3A11Z
```
3. SCREENSHOT:
=> Don't run `comments-time-machine-links` if comment is after latest commit

source/features/align-issue-labels.css, source/features/align-issue-labels.tsx
=> Fix padding for status labels

source/features/add-tag-to-commits.tsx, source/features/mark-merge-commits-in-list.tsx
Fixes #3294
This fixes both features that relied on the same dataset and the dom changed.
Test On:
https://github.com/sindresorhus/refined-github/commits/master
=> Fix `Add-tag-to-commits` and `mark-merge-commits-in-list`

source/github-helpers/pr-ci-status.ts
Seems like the icon was updated recently which meant the commit status check selector was incorrect and the checkbox was not displayed.
Closes #1067 
- Go to a PR that has some CI running, click on merge and see that the checkbox is displayed:
seems to work for the current design:
but also in the preview:
=> Fix `wait-for-build` checkbox display

source/features/clean-dashboard.css, source/features/clean-pinned-issues.css, source/features/hide-watch-and-fork-count.css, source/features/highlight-collaborators-and-own-discussions.css, source/features/minimize-upload-bar.css, source/features/parse-backticks.css, source/features/reactions-avatars.css, source/features/reactions-avatars.tsx, source/features/recently-pushed-branches-enhancements.css
Related to #3081
Fixes #3248
Match border radius with GitHub's new design.
Features and test URLs:
- `reactions-avatars`: here
<details>
"Design updates" feature preview **disabled**:
"Design updates" feature preview **enabled**:
</details>
- `parse-backticks`: https://github.com/sindresorhus/refined-github/pulls
- `clean-dashboard`: https://github.com/
- `clean-pinned-issues`: https://github.com/sindresorhus/refined-github/issues
- `hide-watch-and-fork-count`: here
- `highlight-collaborators-and-own-discussions`: https://github.com/sindresorhus/refined-github/pulls
- `minimize-upload-bar`: here
- `recently-pushed-branches-enhancements`: 🤷
=> Match border radius in GitHub new design

source/features/repo-age.tsx, source/features/toggle-files-button.css, source/features/toggle-files-button.tsx
Follows #3187 and #3225, related to #3081. GitHub updated the design of the "latest commit" box in the "Repository refresh" beta, so our selectors broke.
Test URLs:
* https://github.com/sindresorhus/refined-github
* https://github.com/sindresorhus/refined-github/tree/fregante-patch-1
* https://github.com/sindresorhus/refined-github/tree/20.6.18
Make sure to clear the cache to test if the selectors work properly.
Test URLs: see above
=> Restore `toggle-files-button`+`repo-age` in "Repository refresh"

source/features/clean-pinned-issues.css
Fix #3298
Test: some repo you have admin access, with only 1 pinned issue
**Before**
**After**
=> Fix `clean-pinned-issues` layout

source/features/view-markdown-source.tsx
- Fix selector
- Match GitHub's tooltip style (position)
Test: https://github.com/sindresorhus/refined-github/blob/master/contributing.md
**Before**
**After**
=> Update `view-markdown-source` selector

source/features/user-profile-follower-badge.tsx
The badge position always looks weird for me, especially with the new design. The new stats area seems like a better place for it.
**Before:**
**After (wide view):**
**After (narrow view):**
=> Move `user-profile-follower-badge` position

source/features/download-folder-button.tsx, source/features/latest-tag-button.tsx
1. Fixes <https://github.com/sindresorhus/refined-github/pull/3195#issuecomment-646323153>.
`download-folder-button` doesn't need to be shown when "Clone or download" button exists.
Problem: `isRepoRoot` seems to not work on branches with slashes. It caused the big button to appear with "Repository refresh" beta disabled and a console error with "Repository refresh" beta enabled.
Test: https://github.com/yakov116/TestR/tree/this/branch/has/many/slashes
2. Fixes <https://github.com/sindresorhus/refined-github/issues/3081#issuecomment-643198654> again after #3214 was merged.
Test: https://github.com/OpenLightingProject/open-fixture-library
Before:  
After:
=> Fix `download-folder-button` and `latest-tag-button`

source/features/releases-tab.tsx
None
2. TEST URLS:
3. SCREENSHOT:
None
Looks like the selector changed
=> Fix Releases Tab on `isRepoRoot`

package.json, readme.md, source/features/align-repository-header.css, source/refined-github.ts
Fixes https://github.com/sindresorhus/refined-github/issues/3280
Replaces and closes #3250
Instead of aligning both sides and limiting the available space for the tabs, this only aligns the left side
=> Add `align-repository-header` feature

source/features/view-markdown-source.tsx
Continue of https://github.com/sindresorhus/refined-github/pull/3282#issuecomment-652526963
I forgot that `Element.querySelector` uses depth-first pre-order traversal, so it will match the old selector sometimes.
Test:
- https://github.com/sindresorhus/refined-github/blob/master/readme.md
- https://github.com/sindresorhus/refined-github/blob/master/contributing.md
- https://github.com/kidonng/cherry/blob/master/Bookmarklets.md
=> Update `view-markdown-source` selector again

source/features/prevent-pr-commit-link-loss.tsx
Closes #3234
Replaces and closes #3296
Test content:
```
https://github.com/sindresorhus/refined-github/pull/3085/commits/a7b1a8bd85c230ff9ff8e407ca8f6d3646c90eb6       
```
To test this, you have to create a PR from another repo. Example URL:
https://github.com/sindresorhus/refined-github/compare/master...fregante:a@b?expand=1
Example URL: https://github.com/sindresorhus/refined-github/issues/new
Try on this PR
=> Show `prevent-pr-commit-link-loss` on "new issue/PR" pages

source/features/align-repository-header.css
Some pages are full-width, so they don't need to be "aligned".
- Centered: https://github.com/sindresorhus/refined-github
- Centered: this very page
- Centered: https://github.com/sindresorhus/refined-github/pull/3322/files?diff=unified
- Full width: https://github.com/sindresorhus/refined-github/pull/3322/files?diff=split
- Full width: https://github.com/sindresorhus/refined-github/blame/master/.gitattributes
- Full width: https://github.com/sindresorhus/refined-github/commit/f87c46617028be1882047bc3cf3166de94c86e14?diff=split
=> Limit `align-repository-header` to non-full-width pages

source/features/tags-dropdown.tsx
Fixes #3331
It seems the layout structure changed, so I fixed the selector.
There is also an `id="tags-menu"` on the `[role="tabpanel"]:last-child` element so we could also use that instead.
=> Fix links in `tags-dropdown`

source/features/edit-comments-faster.tsx
Sometimes the the `edit-files-faster` doesn't act or doesn't act in time, moving the button outside **after** I open the dropdown. https://github.com/sindresorhus/refined-github/issues/3279
There's no direct need to hide it from the dropdown. Also this piece of code is pretty ugly (I wrote it) 🤓
=> Preserve "Edit comment" in dropdown

source/features/latest-tag-button.tsx
Fix https://github.com/sindresorhus/refined-github/issues/3277#issuecomment-655173202
This is a placeholder, once the feature goes into production (likely) we can fix it (or make other changes).
Screenshot with the fix:
=> Fix `latest-tag-button`

source/refined-github.css
Code copied from https://github.com/kidonng/cherry/blob/4e6e5e34fa59aed18fc21e155c5ca9067b83db5e/styles/github.user.css#L32-L38
Close #3283
Before: 
After: 
Test: here
=> Fix fork popup title style

source/features/copy-file.tsx
Fixes #3323 
2. TEST URLS:
https://gist.github.com/cimi/8c9674e587d3f05131e42353ab1282c3?short_path=939f372
https://github.com/jmeridth/jmeridth.github.io/blob/gh-pages/_posts/2012-03-30-do-not-issue-pull-requests-from-your-master-branch.md (No changes)
3. SCREENSHOT:
Before
After
=> Fix multiple `copy-file` buttons on gist svg files

source/features/more-dropdown.css, source/features/more-dropdown.tsx, source/features/releases-tab.tsx
Fixes #3215 
<details>
<summary>First implementation</summary>
I'm not entirely sure that this is the right approach to this and the code is hacky and repetitive. 
Thoughts?
</details>
Edit: this might be better and less repetitive:
I noticed a problem with `releases-tab` not always disappearing: https://github.com/sindresorhus/refined-github/issues/3347
This will have to be added separately:
=> Refresh `more-dropdown` feature

source/features/show-whitespace.css, source/features/show-whitespace.tsx
Fixes: #2991
Uses clipped SVG background images for spaces and tabs, this makes it more flexible for text wrapping, and any other future characters (#2150).
* [text wrapping](https://github.com/discord/discord-api-docs/pull/1396/files#diff-99b76a48d014c043f2f8804f6653ed82R515) issue from #2991
* [standalone file](https://github.com/sindresorhus/refined-github/blob/master/source/features/show-whitespace.tsx)
* [diff](https://github.com/sindresorhus/refined-github/pull/3168/files)
* [gist](https://gist.github.com/notlmn/fe7f722971dea345379850bd64516fd2)
-----
This PR is still in the works, as SVG content used are static paths, which should ideally be text nodes that inherit font from DOM (Figma still flattens all text nodes while exporting).
I tried to match the existing styles (and size) …
=> Fix display of wrapped whitespace in `show-whitespace`

source/features/comments-time-machine-links.tsx, source/features/edit-files-faster.tsx, source/features/edit-readme.tsx, source/github-helpers/index.ts
They removed the text we were using:
Causing
```
❌ Refined GitHub → edit-files-faster → TypeError: The element wasn’t found, the selector needs to be updated.
```
```
❌ Refined GitHub → edit-readme → TypeError: The element wasn’t found, the selector needs to be updated.
```
cc @yakov116 I think you mentioned this first
https://github.com/sindresorhus/refined-github/tree/20.7.16 (`edit-readme` and `edit-files-faster`)
```
`comments-time-machine-links` bar at the top: https://github.com/sindresorhus/refined-github/blob/master/source/features/comments-time-machine-links.tsx?rgh-link-date=2019-12-11T10%3A12%3A11Z
```
=> Fix permalink detection in 3 features

source/features/parse-backticks.tsx
- Drop two old selectors since "Latest commit design updates" is out of beta
- Add a new selector for commit message selector on `isCommitList`
=> Update `parse-backticks` selectors

source/features/profile-gists-link.tsx
The counters on user profiles were missing in the initial GitHub redesign, so we removed the Gists counter in #3272.
GitHub later added back counters for repositories, packages (see https://github.com/kidonng), and projects (see https://github.com/ouuan).
To be consistent with the design, and recover the usage mentioned in https://github.com/sindresorhus/refined-github/pull/3286#issuecomment-660881989, I suggest adding back the Gists counter.
The logic is the same as GitHub's (and https://github.com/sindresorhus/refined-github/pull/3272#issuecomment-648577062), the counter will only be added if the user has gists.
=> Restore counter on `profile-gists-link`

source/features/parse-backticks.tsx
Fix #3385 
The bug is caused by 
https://github.com/sindresorhus/refined-github/blob/a82f849bd4a745542642b9453c12a6ec18c381aa/source/features/parse-backticks.tsx#L31
After this PR:
To prevent possible problems, I updated another selector which uses `.repository-content .js-details-container` as well.
=> Use more precise `parse-backticks` selectors on `isSingleFile`

source/features/add-tag-to-commits.tsx
It would fail if the commit had expanded details
Test on https://github.com/sindresorhus/refined-github/commits/master
=> Fix `add-tag-to-commits` selector

source/features/dim-bots.css
Fix #3386 
I'm wondering should I preserve old selectors (for enterprise)
=> Fix `dim-bots` selectors

source/features/comment-fields-keyboard-shortcuts.tsx
Fix #3388
GitHub has some kind of lazy load logic for the edit comment button, ~~so we need to dispatch a `mouseover` event to make the button "appear" (though not visible, unless `edit-comments-faster` is also enabled).~~
~~The first trigger will be slow (about 2-3 seconds on my machine) but following triggers will be instant.~~
I think the same method can be used to make `edit-comments-faster` more reliable (or can it?)
=> Fix `comment-fields-keyboard-shortcuts`

readme.md, source/features/highlight-non-default-base-branch.tsx, source/features/pr-branches.tsx, source/refined-github.ts
~_Draft: I just edited the feature on the fly_~
This brings the feature in line with https://github.com/sindresorhus/refined-github/pull/455
IMHO the feature is noisy and doesn't show all the branches to begin with. If anyone finds this useful, they'll probably find it more useful to show _all_ the branches _all_ the time.
Resolves https://github.com/sindresorhus/refined-github/issues/2943, which asked for more branches to appear
=> Reduce `pr-branches` to `highlight-non-default-base-branch`

source/features/ci-link.tsx
=> Restore `ci-link`

source/features/keyboard-navigation.tsx
Fixes #3319 
Instead of making complex query selectors this approach just filters out elements that shouldn't be *targetable*.
I mainly tested this code with use cases described in the [issue](https://github.com/sindresorhus/refined-github/issues/3319#issue-651357203), so if there are any other edge case I didn't consider please let me know.
> Hidden conversations in Files tabs are "focused"
For this now any `.js-minimizable-comment-group` is ignored if if it is *minimized*.
I tested this with in [#3242 (files)](https://github.com/sindresorhus/refined-github/pull/3242/files), now only the files are targeted.
For me the comments also where hidden *(and not visible when targeted)* without pressing `i` first, so I handled both scenarios.
> PR reviews are skipped
Targetable …
=> Fix `keyboard-navigation` issues

readme.md, source/features/linkify-user-edit-history-popup.tsx, source/refined-github.ts
Closes #2161
2. TEST URLS:
https://github.com/Mottie/GitHub-userscripts/issues/88#issuecomment-502933879 (with bot and should not be linkified)
https://github.com/sindresorhus/refined-github/pull/1766#issue-251741293
This pull request
3. SCREENSHOT:
=> Add `linkify-user-edit-history-popup` feature

source/features/useful-not-found-page.tsx
GitHub seems to have finally started automatically redirecting URLs to old branches:
Demo:
- 404 branch, file: https://github.com/sindresorhus/refined-github/blob/404/package.json
- 404 branch, folder: https://github.com/sindresorhus/refined-github/blob/404/source
So I'm removing this behavior from `blob` and `tree`
---
However, they don't apply this behavior to `edit` URLs, so I'm leaving the logic just for that:
- 404 branch, **edit** file: https://github.com/sindresorhus/refined-github/edit/404/package.json
---
Bugfixes:
- `/user/repo/edit/` URLs should not be queried in the loop:
https://github.com/sindresorhus/refined-github/edit/master/wrong-file
---
Original feature tests in https://github.com/sindresorhus/refined-github/pull/1558
=> Fixes and improvements to `useful-not-found-page`

source/features/ci-link.css, source/features/ci-link.tsx
Test URL: a private repo
Before: 
After:
<details>
<summary>No longer apply <s>The extra margin also pairs nicely with other extensions like Octotree.</s>
</summary>
Before:
After:
Before:
After:
</details>
=> Append `ci-link` icon after private label

source/features/show-open-prs-of-forks.tsx
Updates selectors.
Also fixes the `cacheKey`. The repo url was not saved so if you had more than one fork it would show on both.
=> Small fix to `show-open-prs-of-forks`

source/features/shorten-links.tsx
Resolves #2264
Test: https://github.com/sindresorhus/refined-github/pull/636/files (edit this comment and observe the link)
Screenshot:
=> Apply `shorten-links` after editing comments

source/features/fork-source-link-same-view.tsx
https://github.com/sindresorhus/refined-github/pull/3230#issuecomment-671308585
2. TEST URLS:
https://github.com/yakov116/refined-github/edit/upstream/package.json
3. SCREENSHOT:
None
Sorry about 
>Send it just to blob?
>
>_Originally posted by @yakov116 in https://github.com/sindresorhus/refined-github/pull/3230#issuecomment-671309723_
I made a mistake and thought that `doesFileExist` looks at route. ([For the second time!](https://github.com/sindresorhus/refined-github/pull/3420#discussion_r463870882))
=> Enable `fork-source-link-same-view` on editing pages

source/features/close-out-of-view-modals.tsx, source/globals.d.ts
-
2. TEST URLS:
-
3. SCREENSHOT
-
We can listen for `menu:activated` (CutomEvent) instead of click.
=> Faster & Simplify `close-out-of-view-modals`

readme.md, source/features/follow-local-link.tsx, source/features/same-page-definition-jump.tsx, source/refined-github.ts
Closes #3337 
2. TEST URLS:
(Same Page) https://github.com/sindresorhus/refined-github/blob/master/source/github-helpers/api.ts#L50
(External Page) https://github.com/sindresorhus/refined-github/blob/master/source/features/add-tag-to-commits.tsx#L127
3. SCREENSHOT:
=> Add `same-page-definition-jump` feature

source/features/keyboard-navigation.tsx
Fixes #3457
The not already resolved review comments aren't `<details>` elements, so the also don't have an `[open]` attribute.
=> Adjust minimized review comment selector

source/features/latest-tag-button.tsx, source/features/parse-backticks.tsx
This is tougher than I previously thought (*just add a selector is fine*) because existing functions won't handle elements inside, while the keyword should remain highlighted on the search page. I end up with:
- ~~Adding a workaround (`child.textContent = child.textContent`)~~
- ~~Rehighlight the search keywords~~
~~The code may not look pretty but it works, though only for **issues/PRs**. **Commits** has a deeper level of elements to couple with, which I may come up with an idea later.~~
Suggestions/testing welcome.
None
2. TEST URLS:
- Commit search: https://github.com/sindresorhus/refined-github/search?q=latest+button&type=Commits
- Issue search: https://github.com/sindresorhus/refined-github/search?q=latest+button+is%3Aissue&type=Issues
- PR search: …
=> Add `isRepoSearch` into `parse-backticks`

source/features/warn-pr-from-master.tsx
None but it fixes the feature too, the selector changed.
2. TEST URLS:
https://github.com/sindresorhus/refined-github/compare/incremental-tag-changelog-link...yakov116:upstream
3. SCREENSHOT:
**There should be no visible changes**
Before
After
@busches can you check if `.is-cross-repo` and `.js-compare-pr` exist on GHE?
=> Enable `warn-pr-from-master` on cross fork pr's

source/features/linkify-code.tsx
Both `.blob-wrapper` and `.comment-body` matches a code block in review comments, so the linkify functions got run for multiple times.
Fix #3226
2. TEST URLS:
https://github.com/sindresorhus/refined-github/pull/3225#discussion_r439535538
3. SCREENSHOT:
Before: ![image](https://user-images.githubusercontent.com/1402241/84527576-71316080-acde-11ea-856e-db9f72915a36.png)
After:
=> Prevent `linkify-urls` from running multiple times

source/features/hide-readme-header.css
Closes #3495 
Because `hide-readme-header` hides the readme header, it essentially decreases the top padding. This makes the top padding `32px`, the same as the left/right/bottom padding.
=> Re-add top padding removed by `hide-readme-header`

source/features/hide-disabled-milestone-sorter.tsx
#2671
2. TEST URLS:
https://github.com/sindresorhus/eslint-plugin-unicorn/milestones?direction=asc&sort=due_date
3. SCREENSHOT:
None
=> Refactor `hide-disable-milestone-sorter` to use `selector-observer`

source/features/dim-bots.css
- The selectors added in #2864 are a mess now
- They didn't hide the comment link
- They didn't correctly hide the meta if there is commit message (added in #3389)
See above
2. TEST URLS:
- https://github.com/kidonng/readhub/commits/master
- https://github.com/bors-ng/bors-ng/commits/master
3. SCREENSHOT:
Before: 
After: 
(Also note the height difference)
=> Correctly hide more information in `dim-bots` 

source/features/dim-bots.tsx
There is a use case where a bot like `renovate` could be self-hosted using an author username does not match the `app/` pattern. 
Ex: our renovate PRs are created by a bot user matching `author:XXX-renovate`
Initially, I thought about supporting this use case by adding a specific selector for that use case: 
```
/* Support self-hosted renovate contribution comming from a git user ending with *-renovate */
'.commit-author[href$="-renovate"]:first-child',
'.opened-by [href$="-renovate+sort%3Aupdated-desc"]'
```
The problem now is that this does not scale with how people might name their bot or if they use renovate locally with their credentials
Bots like `renovate` usually allows us to add custom labels upon PR creation.
A user of `dim-bots` feature could benefit from the feature by setting …
=> Support `bot` label in `dim-bots`

readme.md, source/features/batch-open-conversations.tsx
Add checkboxes to issues for batch-open-conversations when i don't have write access to the repo.
closes #3487
*Note: an repo i don't have write access:*
https://github.com/gatsbyjs/gatsby/pulls?page=2&q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed+is%3Aunread
*Note: an repo i don't have write access:*
=> Enable `batch-open-conversations` on repos without write access

source/features/clean-pinned-issues.css
I feel that with `clean-pinned-issues`, the pinned issues have become _less visible_, which was not the intent. Here I just make the border thicker. Alternative suggestions welcome.
=> Make `clean-pinned-issues` slightly more visible

source/features/dim-bots.tsx
Fix: #3520 
@fregante I went a bit fast by approving the change you propose. 
This will work a lot better, since there is not `/` in the URL.
=> Correctly dim `bot` label in `dim-bots`

source/features/remove-label-faster.tsx
https://github.com/sindresorhus/refined-github/pull/3476#issuecomment-679030079
2. TEST URLS:
https://github.com/sindresorhus/refined-github/issues/3084 then click Pull Requests tab
3. SCREENSHOT:
None
=> Remove `deinit` in `remove-label-faster`

source/features/more-dropdown.tsx, source/features/releases-tab.tsx
Closes https://github.com/sindresorhus/refined-github/issues/3354 (this issue wasn't a "good first issue" after all 😅)
Replaces and closes https://github.com/sindresorhus/refined-github/pull/3482
This seems to work, but https://github.com/sindresorhus/refined-github/issues/3347 still exists, complicating things a bit.
=> Move Security and Insights tabs to `more-dropdown`

package-lock.json, package.json, readme.md, source/features/new-repo-disable-projects-and-wikis.tsx, source/refined-github.ts
Closes #3533
2. TEST URLS:
https://github.com/new
3. SCREENSHOT:
=> Add `new-repo-disable-projects-and-wikis` feature

source/features/highlight-deleted-and-added-files-in-diffs.tsx
https://github.com/sindresorhus/refined-github/pull/3439
2. TEST URLS:
[20.9.11...master](https://github.com/sindresorhus/refined-github/compare/20.9.11...master#diff-67ba01fa3e792891b585fa43e92c78ea) (Showing the change)
https://github.com/sindresorhus/refined-github/compare/incremental-tag-changelog-link...20.9.11 (Too large)
https://github.com/sindresorhus/refined-github/compare/master...20.9.11 (Nothing to compare)
3. SCREENSHOT:
None
=> Enable `highlight-deleted-and-added-files-in-diffs` on Compare pages

.xo-config.js
I found lint warnings to be more a nuisance than anything else, mixing with real warnings and making them harder to tell them apart.
Warnings are useful if you're actively looking for something to do; in that case, use:
```
❯ xo --no-quiet
source/features/submit-review-as-single-comment.tsx:50:2
⚠   50:2  Unexpected todo comment.                                                             no-warning-comments
source/features/repo-age.tsx:84:2
⚠   84:2  Unexpected todo comment.                                                             no-warning-comments
source/features/remove-label-faster.tsx:37:1
⚠   37:1  Unexpected todo comment.                                                             no-warning-comments
source/features/highest-rated-comment.tsx:88:3
⚠   88:3  Unexpected todo …
```
=> Meta: silence XO warnings

readme.md, source/features/hide-zero-packages.tsx, source/refined-github.ts
Close #3572
> [Just to mention that if we want to hide “Packages” tab on organization, we need to query the API.](https://github.com/sindresorhus/refined-github/pull/3297#issuecomment-650671415)
2. TEST URLS:
https://github.com/sindresorhus/refined-github (no packages)
https://github.com/yarnpkg/berry (with packages)
https://github.com/sindresorhus (no packages)
https://github.com/kidonng (with packages)
3. SCREENSHOT:
=> Restore `hide-zero-packages`

source/features/file-finder-buffer.tsx
Close #3212
2. TEST URLS:
3. SCREENSHOT:
Before: ![](https://user-images.githubusercontent.com/1402241/84258013-89ef1a00-ab16-11ea-86c4-b4bc860ea316.png)
After:
=> Improve `file-finder-buffer` style

source/features/releases-tab.tsx
The 'Releases' section in the 'Refreshed Repository' design sidebar is redundant when there is already the releases-tab.
This change removes the 'Releases' section from the sidebar.
I'm not sure whether this has been discussed before ( I did dig through some old issues, but could not find any ), but there is one direct link to the latest release that goes away with the section.
I usually find myself either navigating directly to `/releases/latest` or simply going to the main Releases page and referring to the latest release. I do not know if people use the latest release link as often. But the remaining information is already on the releases-tab.
None
2. TEST URLS:
Any repository root page
* https://github.com/sindresorhus/refined-github
* https://github.com/xojs/xo
* …
=> Hide redundant 'Releases' section from repo sidebar

source/features/stop-pjax-loading-with-esc.tsx
Closes #3584
2. TEST URLS:
https://github.com/sindresorhus/refined-github/settings/hooks
`https://github.com/REPO_OWNER/REPO_YOU_HAVE_ADMIN_PERMS_ON/settings/hooks`
3. SCREENSHOT:
=> Avoid repository settings bug caused by `stop-pjax-loading-with-esc`

source/features/toggle-files-button.tsx
1. LINKED ISSUES: Closes #3588 
2. TEST URLS: https://github.com/sindresorhus/refined-github
3. SCREENSHOT:
As you can see in the GIF above, I couldn't totally get rid of the content flash. I don't find it too distracting though, so I could live with it. But it's probably possible to do better, given that "Hide Files on GitHub" modifies the file list on load without any noticeable jitters.
=> Persist `toggle-files-button` state

source/features/view-markdown-source.tsx, source/globals.d.ts
Closes #2542 
2. TEST URLS:
https://github.com/sindresorhus/refined-github/blob/3d517d6cd00e83a51973808c7ff03cae2b692d2b/contributing.md#L7
3. SCREENSHOT:
=> Enhance `view-markdown-source` with line actions

source/features/collapsible-content-button.tsx
1. LINKED ISSUES: none
2. TEST URLS: https://github.com/sindresorhus/refined-github/issues/new
While working on #3598 I noticed a small bug in `collapsible-content-button.tsx`: there was a few lines of code to restore the selection after wrapping it in a `<details>` tag, but it had no effect (at least on latest Firefox):
This can be fixed by focusing the textarea before restoring the selection:
=> Focus field after using `collapsible-content-button`

readme.md, source/features/link-to-gihub-io.tsx, source/refined-github.ts
Closes #3560
2. TEST URLS:
[Repository Lists](https://github.com/yashshah1?tab=repositories&type=source)
[Repository Page](https://github.com/yashshah1/yashshah1.github.io)
3. SCREENSHOT:
=> Add `link-to-github-io` feature

source/features/link-to-github-io.tsx, source/refined-github.ts
- Fix filename typo
- Add padding: https://github.com/Qv2ray/qv2ray.github.io
- Enable on orgs: https://github.com/Qv2ray
=> `link-to-github-io` improvements

source/features/table-input.tsx
First of all, congratulations on this one of the most elegant features in Refined GitHub 🎉
- Add (possibly) missing tooltip classes
- ~~Sorted the classes to match GitHub's order~~
- ~~Move `aria-label` attribute one level up to avoid the popup arrow being cut off~~
None
2. TEST URLS:
This PR
3. SCREENSHOT:
Note the tooltip persists when creating a table 🤷‍♀️:
=> Add tooltip to `table-input` button

source/features/bypass-checks.tsx
Fixes #3418 
Closes #3609
2. TEST URLS:
This PR it should not run (its all actions)
https://github.com/xojs/xo/pull/497
3. SCREENSHOT:
None
=> Enable `bypass-checks` on more commit statuses

source/features/next-scheduled-github-action.tsx
1. LINKED ISSUES: None (PR #3604)
2. TEST URLS: https://github.com/sindresorhus/refined-github/actions
3. SCREENSHOT:
Before | After
--- | ---
This is a pretty flaky fix since it depends on the SVG icon next to the workflow name, but I couldn't find another way to do this.
=> Don't show next scheduled time of disabled workflows

source/features/bypass-checks.tsx
Dont remember which issue
2. TEST URLS:
https://github.com/xojs/xo/pull/497
https://github.com/sindresorhus/got/pull/1491
https://github.com/webpack/webpack/pull/11438
3. SCREENSHOT:
None
=> Use API for `bypass-checks`

readme.md, source/features/convert-pr-to-draft-improvements.tsx, source/refined-github.ts
Closes https://github.com/sindresorhus/refined-github/issues/3213
Some people will keep using the button in the sidebar, so I opted to _copy it_ instead of _moving it._
Also I added a "clicked" state because the modal does not give any feedback after you click it, only closing a few seconds later.
Gif note for reviewers: the loading icon alignment has already been fixed.
Gif note for contributors: notice how clean the gif is; it's because I move/delete every other element around it. If you can sometimes, try to do the same.
=> Add `convert-pr-to-draft-improvements` feature

source/features/cleanup-repo-filelist-actions.tsx
- fix "add file" details overlay broken by `.tooltipped`
- fix nextElementSibling when the user is logged out
- add compatibility with mobile styles
- remove BtnGroup in favor of mobile style improvements
2. TEST URLS:
3. SCREENSHOT:
<table>
<tr>
<th>
<th> GitHub
<th> Before
<th> After
<tr>
<td> Desktop
<td><img width="1009" alt="Captura de pantalla 2020-10-13 a las 22 55 54" src="https://user-images.githubusercontent.com/11599942/95917095-fe2e1880-0da9-11eb-8dc5-150c881d4a87.png">
<td><img width="1267" alt="Captura de pantalla 2020-10-13 a las 23 09 48" src="https://user-images.githubusercontent.com/11599942/95917141-0ede8e …
=> fix repo filelist actions

source/features/clean-footer.css
Sets the color to the button recently added to the footer.
No issue
2. TEST URLS:
Any url
3. SCREENSHOT:
<table>
<tr>
<td>Before
<td>After
<tr>
<td><img width="435" alt="Captura de pantalla 2020-10-16 a las 0 24 13" src="https://user-images.githubusercontent.com/11599942/96192634-b690c380-0f46-11eb-9d97-baf52a5f2259.png">
<td><img width="447" alt="Captura de pantalla 2020-10-16 a las 0 23 27" src="https://user-images.githubusercontent.com/11599942/96192649-bc86a480-0f46-11eb-88e8-53f2b544522e.png">
</table>
=> Fix "Cookie Preferences" link color in `clean-footer`

source/features/restore-file.tsx
1. New files can be "reverted" by deleting them.
2. PRs already have a button to delete the files
3. Thanks to `highlight-deleted-and-added-files-in-diffs` now we also know which files are new as I had hoped in the JS comment.
Test on https://github.com/sindresorhus/refined-github/pull/3650/files?file-filters%5B%5D=.json&file-filters%5B%5D=.tsx#diff-793b39887195dc240846c30af909a5a6ef55a7fc329979225fecbebea653047f
=> Don't add `restore-file` action on new files in PRs

source/features/profile-hotkey.tsx
None
2. TEST URLS:
https://gist.github.com/yakov116
3. SCREENSHOT:
None
It did not work there since `/${getUsername()` leads to the `Your gists` button
=> Fix `profile-hotkey` on Gist pages

source/features/default-branch-button.tsx, source/features/enable-file-links-in-compare-view.tsx, source/features/latest-tag-button.tsx, source/features/more-dropdown.tsx, source/features/restore-file.tsx, source/github-helpers/get-default-branch.ts, source/github-helpers/github-url.ts, source/github-helpers/index.ts
Fixes #3641 
2. TEST URLS:
#3641 
3. SCREENSHOT:
None
=> Avoid errors caused by `more-dropdown` on issues

source/features/releases-tab.tsx
Resolves #3652 
2. TEST URLS:
None
3. SCREENSHOT:
None
=> Make `releases-tab` non dependent of `more-dropdown`

source/background.ts, source/features/embed-gist-inline.tsx, source/features/view-markdown-source.tsx, source/helpers/fetch-dom.ts
https://github.com/sindresorhus/refined-github/pull/3594#issuecomment-711839565
2. TEST URLS:
https://github.com/sindresorhus/refined-github/blob/3d517d6cd00e83a51973808c7ff03cae2b692d2b/contributing.md#L3-L5
3. SCREENSHOT:
None
@fregante why do you say we need to exclude enterprise?
=> Fetch widget for `view-markdown-source` instead of maintaining a copy of it

source/features/faster-reviews.tsx
As mentioned in #3621. You can test it right here in this PR :wink:
=> Restore `faster-reviews` autofocus

readme.md
Apostrophe abuse is a crime!
N/A
2. TEST URLS:
N/A
3. SCREENSHOT:
N/A, this is just copy-editing.
=> Meta: Fix typo in the description of `show-associated-branch-prs-on-fork`

source/features/github-bugs.css
- Add first fix from #3444 again (details on https://github.com/sindresorhus/refined-github/pull/3444#discussion_r468017909)
- Remove second fix from #3444 since it has been fixed by GitHub
- Added a new fix
<table>
<tr>
<td> Test
<td> Before
<td> After
<tr>
<td> This PR
<td> <img src="https://user-images.githubusercontent.com/44045911/89752707-0d71bb00-db08-11ea-9f50-e625c956bf11.png">
<td> <img src="https://user-images.githubusercontent.com/44045911/89752675-e9ae7500-db07-11ea-9989-f518c2542643.png">
<tr>
<td> <a href="https://github.com/sindresorhus/refined-github/pull/3660/commits/ad3b3d20d36c017dcbc06a46277aa0ed595b309a">Link</a>
<td> <img src="https://user-images.githubusercontent.com/44045911/96263039-2067a680-0ff5-11eb-8c67-746b9826549c.png">
<td> <img …
=> Meta: remove no-longer-necessary alignment CSS

readme.md, source/features/unfinished-comments.tsx, source/refined-github.ts
1. LINKED ISSUES: Closes #3680 
2. TEST URLS:
- https://github.com/sindresorhus/refined-github/issues/3680
- https://github.com/sindresorhus/refined-github/pull/3596 (hidden textareas)
3. SCREENSHOT:
Notes:
- I used the `visibilitychange` event instead of `pageshow`/`pagehide` as the latter weren't working for me in Firefox. As an added bonus, it also works when hiding/minifying the whole browser window.
- I followed the suggestion of the issue for the notification text, but imho something shorter would be better, e.g. `(+)` or `[*]` (akin to what editors show when a file has been modified but not saved).
=> Add `unfinished-comments` feature

readme.md, source/features/jump-to-change-requested-comment.tsx, source/features/link-to-requested-change-comment.tsx, source/refined-github.ts
Closes [#2712](https://github.com/sindresorhus/refined-github/issues/2712)
2. TEST URLS:
[#17968](https://github.com/facebook/react/pull/17968#partial-pull-merging)
3. SCREENSHOT:
=> Add `jump-to-change-requested-comment` feature

source/features/recently-pushed-branches-enhancements.tsx
Fixes https://github.com/sindresorhus/refined-github/issues/3702
Reverts the change made in #3596 that was incorrect since it does not start with `https://`
=> Fix `recently-pushed-branches-enhancements`

source/features/deprioritize-marketplace-link.tsx
https://github.com/sindresorhus/refined-github/issues/3720#issuecomment-726810747
2. TEST URLS:
all over
3. SCREENSHOT:
None
=> Fix `deprioritize-marketplace-link`

source/features/use-first-commit-message-for-new-prs.tsx
GitHub is going to give us a very hard time. There are almost no more class specific selectors
Test on: 
https://github.com/sindresorhus/refined-github/compare/master...yakov116:text?expand=1 (Cross-fork)
https://github.com/sindresorhus/refined-github/compare/master...sindresorhus:lint?expand=1 (Same-repo)
=> Fix `first-commit-message-for-new-prs`

source/features/sticky-sidebar.css
Fixes https://github.com/sindresorhus/refined-github/issues/3732
This shouldn't make it any worse than `sticky` already does since, at most, it just brings the whole sidebar a little higher than the rest of the page, which is expected since it floats. Its contents and their z-index were also already trapped by `sticky` so they won't be affected by this.
All that this does is bring it above the regular `z-index` of the elements that _follow_ the sidebar, like the footer.
If it causes issues, the alternative to #3732 would be to detect an "overlay details" opening/closing and toggling the "sticky-sidebar" class instead.
=> Fix `z-index` conflict between `sticky-sidebar` and the footer

distribution/options.html, source/options.css
=> Meta: Add more information about the token in the options page

source/features/unfinished-comments.tsx
1. LINKED ISSUES: Closes #3765 
2. TEST URLS:
- issue: https://github.com/sindresorhus/refined-github/issues/3765
- PR: https://github.com/sindresorhus/refined-github/pull/3767
Tested on Firefox and Chromium in all possible cases (issue comment, PR comment, PR review comment). Side note: it also works on the "New issue"/"New PR" pages now, but we get the same "switching tabs right after posting" problem as we had for the comments (at least on Firefox).
=> Enable `unfinished-comments` on temporarily-hidden text fields

readme.md
The old link is now broken. Thanks for including us in your list of related extensions!
=> Meta: Update Sourcegraph Readme link

source/github-helpers/api.ts
1. LINKED ISSUES: none
2. TEST URLS: https://github.com/new
The `new-repo-disable-projects-and-wiki` feature was the only one passing an empty query string to `api.v3()`, which caused a trailing slash to appear at the end of the URL and resulted in a 404 error.
=> Fix `new-repo-disable-projects-and-wiki` feature

source/features/parse-backticks.tsx
None specifically, but these two comments: https://github.com/sindresorhus/refined-github/issues/3798#issuecomment-742561887, https://github.com/sindresorhus/refined-github/pull/3806#issuecomment-742667247.
2. TEST URLS:
[This PR with many commits](https://github.com/sindresorhus/refined-github/pull/1986).
3. SCREENSHOT:
<table>
<tr>
<td>Before
<td>After
<tr>
<td><img alt="backticks in PR commit list - before" src="https://user-images.githubusercontent.com/1441704/101916737-a5230b00-3bc7-11eb-9f28-e855f9b71186.png">
<td><img alt="backticks in PR commit list - after" src="https://user-images.githubusercontent.com/1441704/101916823-bff57f80-3bc7-11eb-91da-1a5d9975981a.png">
</table>
-----
I also fixed the way the `:not(.rgh-backticks-already-parsed)` pseudo-class is added …
=> Fix `parse-backticks` in PR commit list and Compare page

readme.md, source/features/quick-repo-deletion.css, source/features/quick-repo-deletion.tsx, source/refined-github.ts
1. LINKED ISSUES: Closes #3779 
2. TEST URLS: see https://github.com/sindresorhus/refined-github/pull/3734#issue-523513983
3. SCREENSHOT: **TODO**
* Renamed the feature to `quick-repo-deletion`
* Fixed an incorrect selector that broke the feature
* Enabled the feature on every repo and added an additional confirmation step for non-forks
=> Expand `quick-fork-deletion` to empty repos

source/features/clean-dashboard.css, source/features/conflict-marker.css, source/features/emphasize-draft-pr-label.css, source/features/highlight-collaborators-and-own-conversations.css, source/features/parse-backticks.css, source/features/reactions-avatars.css, source/features/resolve-conflicts.css, source/features/show-whitespace.css, source/features/split-issue-pr-search-results.css, source/features/table-input.css, source/refined-github.css
I believe this PR fixes all Dark mode issues, so close issue #3798 once this is merged if you agree.
-----
Fix border issues in #3798:
- [Pinned issues border](https://github.com/sindresorhus/refined-github/issues/3798#issuecomment-741568995).
- [Divider line in grouped events in Activity list](https://github.com/sindresorhus/refined-github/issues/3798#issuecomment-741604005).
2. TEST URLS:
- [Pinned issues example](https://github.com/sindresorhus/refined-github/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc).
- [Activity list example](https://github.com/) (see while logged in).
3. SCREENSHOTS:
<table>
<tr>
<td>Before
<td>After
<tr>
<td><img alt="pinned issues - before" src="https://user-images.githubusercontent.com/1441704/101666452-864d3900-3a4e-11eb-8b9d-97717301fcc …
=> Further improvements to Dark mode

source/features/hide-useless-comments.tsx, source/helpers/useless-comments.ts, test/helpers.ts
1. LINKED ISSUES: Closes #3822 
2. TEST URLS:
- ["Please update" and variations](https://github.com/justinfrankel/licecap/issues/97)
- ["+1" and variations](https://github.com/hayaku/hayaku/issues/303)
- ["+1" and thumbs-ups](https://github.com/isaacs/github/issues/215)
This PR:
* removes spaces and basic punctuation from the comments before testing them — it makes it easier to match small sentences like "Please update, thanks" and all their possible variations
* adds several keywords and their variations
* adds support for skin tone modifiers on hand-related emojis (it's relatively rare but I've seen them used a few times)
TODO:
=> Improve detection in `hide-useless-comments`

source/features/more-dropdown.tsx
1. LINKED ISSUES: none
2. TEST URLS:
* [Repo with actions](https://github.com/sindresorhus/refined-github)
* [Repo with wiki](https://github.com/justinfrankel/licecap)
* [Repo with projects & wiki](https://github.com/polybar/polybar)
* [Repo with discussions](https://github.com/CoderLine/alphaTab)
I noticed that `more-dropdown` was still broken on repos with "Wiki" or "Discussions" tab(s). This is because the `data-tab-item` and `data-menu-item` attributes were changed to the following format:
```
i<tab index><tab name>-tab
```
This should be fixed for good now.
=> Fix `more-dropdown`

source/features/sync-pr-commit-title.tsx
Closes #3829.
Test URLs are quite specific… A PR that you can merge, where some branch restrictions are not met, and where auto-merge is enabled.
Please test both cases:
1. Auto-merge
2. Override restrictions and merge immediately
You don't need to actually merge the PR, just verify that this note appears when changing the commit title:
> The title of this PR will be updated to match this title. <ins>Cancel</ins>
=> Fix `sync-pr-commit-title` to work with GitHub's auto-merge

source/features/highest-rated-comment.tsx
Too many checks, one is enough. 
The one on the title bar:
- has a tooltip
- poses no overlapping risks
- is also visible on "mobile view"
=> Drop duplicate icon from `highest-rated-comment`

source/features/show-whitespace.css
Closes #3542
pls, can the reporter test this out with *tabs* (only had space indented repos handy) and post a screenshot?
I also tested the implied-github-softwrap discussed in the issue by going to https://github.com/sindresorhus/refined-github/issues/2991 and it seems that is not triggering the same things as discussed in the issue #3542 . As the class name changed here doesn't even apply on that diff.
also, some times forced soft-line-wrap is a desirable feature. Will try to move to it's own setting later on.
=> Prevent soft line-wrap caused by `show-whitespace`

source/background.ts, source/features/embed-gist-inline.tsx, source/features/view-markdown-source.tsx
Fixes #3865 
The feature’s style has probably been broken since https://github.com/sindresorhus/refined-github/pull/3640
Test on: https://github.com/expressjs/express/issues/2761#issuecomment-628549001
Pure link here:
https://gist.github.com/sompylasar/99b5d307da3168b833c1119fb95caf11
[Text link here](https://gist.github.com/sompylasar/99b5d307da3168b833c1119fb95caf11)
=> Fix `embed-gist-inline` style and preserve the original link

source/features/tag-changelog-link.css, source/features/tag-changelog-link.tsx
1. LINKED ISSUES: Fixes #2699 
2. TEST URLS:
* [Single release](https://github.com/sindresorhus/refined-github/releases/tag/20.1.6)
* [Multiple releases](https://github.com/facebook/react/releases)
* [Tags in release list](https://github.com/facebook/react/releases?after=v16.7.0)
* [Tags list](https://github.com/facebook/react/tags)
* [Release with "Verified" badge](https://github.com/tensorflow/tensorflow/releases?after=v1.12.0-rc1)
3. SCREENSHOT:
<table>
<tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/46634000/103087064-9fc1b980-45e6-11eb-8980-3bfa6c362fce.png">
<td><img src="https://user-images.githubusercontent.com/46634000/103087106-b831d400-45e6-11eb-80bb-cd4eb040fd98.png">
</table> …
=> Reposition `tag-changelog-link`

source/features/faster-pr-diff-options.tsx
1. LINKED ISSUES: Closes #3870
2. TEST URLS:
* https://github.com/drichard/mindmaps/compare/master...eitwizlearn:master
3. SCREENSHOT:
<table>
<tr>
<th>Before
<th>After
<tr>
<td>
</td>
<td>
</td>
</table>
=> Enable `faster-pr-diff-options` on compare pages

source/features/hide-comments-faster.tsx
1. LINKED ISSUES: Fixes #3867
2. TEST URLS: see test comment below
Edit: this also fixes a bug where if the "Hide" drop-down is opened then closed by clicking outside, it will subsequently always appear on top of the main drop-down when clicking the "..." button. Seems like the `d-none` class had no effect anymore, so I replaced it by `v-hidden`.
=> Fix `hide-comments-faster`

source/features/separate-draft-pr-button.tsx
1. LINKED ISSUES: Fix #3871 
2. TEST URLS:
* https://github.com/sindresorhus/refined-github/compare/unknow-feature-name?expand=1
3. SCREENSHOT:
<table>
<tr>
<th>Before
<th>After
<tr>
<td>
</td>
<td>
</td>
</table>
Bug was caused by a new wrapper around the PR form.
=> Fix `separate-draft-pr-button` position 

source/features/clean-dashboard.css
1. LINKED ISSUES: Fixes #3880 
2. TEST URLS: homepage feed
3. SCREENSHOT:
<table>
<tr>
<th> Before </th>
<th> After </th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
I only have `.watch-started` events in my feed so I can only test those. Also, is there a reason why non-grouped fork events are left untouched?
=> Fix `clean-dashboard`

source/features/wait-for-build.tsx
Fixes #3887
2. TEST URLS:
Not possible to provide, the tester will need to make a repo with proper conditions met themselves.
See SCREENSHOT section below for possible conditions.
3. SCREENSHOT:
=> Don't apply `wait-for-build` when auto-merge is enabled

source/features/bugs-tab.tsx, source/features/extend-conversation-status-filters.tsx, source/features/global-conversation-list-filters.tsx, source/features/split-issue-pr-search-results.tsx, source/github-helpers/search-query.ts, test/search-query.ts
Fixes #3824 
Steps to test as mentioned in the issue:
1. Visit https://github.com/search?q=refined+github&type=Issues
2. Click Pull requests (and wait for load)
3. Click Issues
The problem was that `createUrl` always appended the next `is:<type>` query part.
This is also used by Github for the filter and every previous `is:<type>` is ignored.
But the detection did just check for the first occurence of `is:<type>` so the ui wasn't updated correctly.
I changed the code to first clear all `is:<type>` and then add the new filter.
I also improved the detection if multiple `is:<types>` are in the search.
As a bonus I also added that the language and state search parameters are also copied for each url
=> Fix and improve `split-issue-pr-search-results`

source/features/show-open-prs-of-forks.tsx
Closes #3888 
2. TEST URLS:
None
3. SCREENSHOT:
None
=> Make `show-open-prs-of-forks`’s text more specific

source/features/tag-changelog-link.tsx
=> Fix `tag-changelog-link` on Safari

source/features/separate-draft-pr-button.tsx
Old selector is still needed on GHE, at least on 2.21 still. I normally don't make a lot of draft PRs, but needed to do a handful the last few days and noticed it was more cumbersome than usual.  :D
N/A
2. TEST URLS:
N/A
3. SCREENSHOT:
GHE:
GH:
=> Fix separate draft pr button on GHE

source/features/clean-conversation-filters.tsx
2. TEST URLS: Go to [the issues page](https://github.com/sindresorhus/refined-github/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) or [the PRs page](https://github.com/sindresorhus/refined-github/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc) and refresh with Ctrl-F5 a few times. (The errors may only pop up on a slow connection).
This fixes a similar bug as #3898, where the elements targeted by the two selectors sometimes don't exist.
=> Fix `clean-conversation-filters`

source/github-events/on-profile-dropdown-load.ts
1. LINKED ISSUES: Fixes #3898 
2. TEST URLS: Go to [the PR list](https://github.com/sindresorhus/refined-github/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc) and do a few "hard refresh" (Ctrl-F5). This triggers the error almost every time for me.
I think #3898 was caused by `awaitDomReady: false` combined with the plain `document.querySelector()` in `onProfileDropdownLoad()`. Using `elementReady` seems to fix it.
Also `set-default-repositories-type-to-sources` is unaffected.
=> Fix `deprioritize-marketplace-link` error in some instances

source/features/dim-bots.tsx
Test URL: https://github.com/OpenLightingProject/open-fixture-library/commits/c18c0b9caf5127637c56ff518623a0fd3effb738/.github/workflows/test.yaml
The commit from Jun 26, 2020 is dimmed correctly, as the squash-merged PR was opened by a bot.
The commit from Dec 27, 2019 is dimmed incorrectly IMHO, as the squash-merged PR was opened by a bot, but enhanced by me. So also squash merge commit was co-authored by me. This PR fixes that.
=> Exclude human-co-authored commits in `dim-bots`

readme.md, source/features/update-pr-from-base-branch.tsx
Fixes https://github.com/sindresorhus/refined-github/issues/3927
Fixes https://github.com/sindresorhus/refined-github/issues/3699
I noticed that the mergeability [box](https://user-images.githubusercontent.com/1402241/106494253-cd204380-647f-11eb-90aa-df05213f8a38.png) [varies](https://user-images.githubusercontent.com/1402241/106494275-d27d8e00-647f-11eb-848d-d73280c5fad9.png) [a](https://user-images.githubusercontent.com/1402241/106494261-cf829d80-647f-11eb-831b-2a0d3d4d1878.png) [lot](https://user-images.githubusercontent.com/1402241/106494266-d0b3ca80-647f-11eb-977e-8e3576c3941e.png) and it's a pain to cover all the cases reliably. So I just moved the action next to the text that tells _we can update it by pushing,_ which makes sense. Also it helps that this text doesn't change that …
=> Move `update-pr-from-base-branch` to a more reliable position

source/features/table-input.css
1. LINKED ISSUES: Fixes #3936 
2. TEST URLS: any rich text editor
The bug was caused by the fixed width of `108px`. Setting it to `auto` and using CSS Grid for the layout solves the problem.
Tested in Firefox & Chromium only.
=> Fix `table-input` at 90% zoom

source/features/extend-conversation-status-filters.tsx
Fixes #3781 
2. TEST URLS:
https://github.com/sindresorhus/refined-github/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Amerged
3. SCREENSHOT:
Before
After
The issue was that there are 2 buttons but returning breaks the loop.
=> Fix merged button text in `extend-conversation-status-filters`

source/features/latest-tag-button.tsx
2. TEST URLS: Go to a repo homepage (e.g. https://github.com/sindresorhus/refined-github) and hard-refresh a few times.
I noticed this feature failing with an error once in a while (especially when my connection is sluggish). Waiting for the `#branch-select-menu` element seems to fix it.
=> Make `latest-tag-button` more reliable

source/features/comments-time-machine-links.tsx, source/features/list-prs-for-file.tsx
Looks like I missed testing when there are no prs
=> Fix console error in `list-prs-for-file`

source/features/index.tsx
Fixes https://github.com/sindresorhus/refined-github/issues/3945 and maybe more
It seems that there's a new nested ajax container. The `pjax:end` listener was being called, but `has-rgh` was not being removed by GitHub because GitHub changed a niece of `has-rgh` instead of its parent.
=> Restore features in file lists

source/features/update-pr-from-base-branch.tsx
Caused by #3931 
I was hoping that the link was short-lived enough that its listener wouldn't be lost. I was wrong. Event delegation it is, as it was.
1. Open a PR that needs to be updated, like https://github.com/sindresorhus/refined-github/pull/3955
2. Visit the PR Commits tab
3. Hit the browser’s back button
4. Try clicking the "Update base branch" button, it won't work
=> Ensure `update-pr-from-base-branch` is always clickable

source/features/more-dropdown.tsx
1. LINKED ISSUES: Fixes #3953 
2. TEST URLS: Any repo page. The "Security" and "Insights" tabs should be moved to the dropdown.
My guess is that the bug is caused by the absence of the "Security" tab when doing:
```typescript
onlyShowInDropdown('security-tab');
onlyShowInDropdown('insights-tab');
```
I can't test this on GHE, but checking for the existence of the tab element should fix this.
=> Fix `more-dropdown` on GHE

source/features/download-folder-button.tsx
Resolves #3949 
2. TEST URLS:
https://github.com/sindresorhus/refined-github/tree/main/media
3. SCREENSHOT:
I added `repeatOnBackButton: true,` since I found that when going from dir to dir it was not applying unless I refreshed (nothing to do with the current PR)
=> Move `download-folder-button` to the dropdown

readme.md, source/features/link-to-changelog-file.tsx, source/features/link-to-changelog.md.tsx, source/refined-github.ts
Closes #3930 
2. TEST URLS: (will add more later)
https://github.com/nodeca/js-yaml/releases/tag/4.0.0
https://github.com/pyca/cryptography/releases
3. SCREENSHOT: (Will update when layout confirmed)
=> Add `link-to-changelog-file` feature

source/features/parse-backticks.tsx
1. LINKED ISSUES: Closes #3975 
2. TEST URLS:
https://github.com/tophf/mpiv/discussions/50
https://github.com/tophf/mpiv/discussions
3. SCREENSHOT:
This PR adds 2 selectors in `source/features/parse-backticks.tsx` (for discussion pages and listings) .
=> Enable `parse-backticks` on Discussions

source/refined-github.css
1. LINKED ISSUES: Fixes #3925 
2. TEST URLS: https://github.com/sindresorhus/refined-github/pull/3922/files
3. SCREENSHOT:
<table>
<tr>
<th>Before
<td>
<tr>
<th>After
<td>
</table>
The original selector that hides the diff stats is `.is-stuck .diffbar .diffstat`, but since I don't know what else it might affect, I chose something more specific to this particular layout.
Also should this be added to the readme?
=> Keep diff stats in "Jump to" dropdown when header is fixed

source/github-helpers/parse-backticks.tsx, test/helpers.ts, test/parse-backticks.ts
1. LINKED ISSUES: Fixes #3990 
2. TEST URLS: [`09c0354` (#3991)](https://github.com/sindresorhus/refined-github/pull/3991/commits/09c03549819592b9245ff9c1a4cb8817b17c50a4)
3. SCREENSHOT:
<table>
<tr>
<th>Before</th>
<th>After</th>
</tr>
<tr>
<td valign="top"><img src="https://user-images.githubusercontent.com/46634000/108341218-bbf26900-71d9-11eb-81c2-f5e648105618.png"></td>
<td valign="top"><img src="https://user-images.githubusercontent.com/46634000/108341085-97968c80-71d9-11eb-8f81-9efc77962ceb.png"></td>
</tr>
</table>
=> Ignore triple-backtick blocks in `parse-backticks`

source/features/hide-useless-comments.tsx
1. LINKED ISSUES: Closes #3830 
2. TEST URLS: https://github.com/justinfrankel/licecap/issues/97
Picked up where #3839 left off. This PR:
- always hides "similar comment(s)" boxes
- expand every one of them when the link to show useless comments is clicked
This is not exactly what was described in #3830, rather it's following this review comment: https://github.com/sindresorhus/refined-github/pull/3839#discussion_r548323403
The idea is to consider every similar comment as useless by default, and not expand them to actually check their contents, since there can be a lot of them (I remember seeing issues with 200+ similar comments). Thoughts?
=> Hide and auto-expand Similar comments in `hide-useless-comments`

package-lock.json, package.json, source/features/sticky-sidebar.tsx, source/helpers/on-element-removal.ts
1. LINKED ISSUES: Closes #3582 
2. TEST URLS:
* Conversation sidebar
* [PR]()
* [Issue](https://github.com/sindresorhus/refined-github/issues/3582)
* Repo root
* [Small sidebar](https://github.com/co1ncidence/mountaineer.vim)
* [Sidebar too tall for viewport](https://github.com/sindresorhus/refined-github) (disable `clean-repo-sidebar` before)
I've added types for `ResizeObserver` but I don't know if those are "official" (seems like the TS issue referenced in `on-element-removal` was closed but idk if the changes have been released yet).
=> Preserve `sticky-sidebar` after a new comment

source/features/rgh-sponsor-button.tsx, source/refined-github.ts
Just a silly feel-good feature.
Named `rgh-` because it's safe so it doesn't need to be documented, but it's not limited to RG.
I'll probably also add an animation on [Sponsor] click
https://github.com/sindresorhus/refined-github/issues
https://github.com/babel
=> Improve GitHub Sponsors UX

source/features/latest-tag-button.tsx
1. LINKED ISSUES: Fixes #3979 
2. TEST URLS:
* [Repo root](https://github.com/fregante/GhostText/tree/21.2.3.221)
* [Single file](https://github.com/fregante/GhostText/blob/21.2.3.221/package.json)
* [Folder](https://github.com/fregante/GhostText/tree/21.2.3.221/source)
* [Latest tag](https://github.com/fregante/GhostText/tree/21.2.21)
* [Old tag](https://github.com/fregante/GhostText/tree/21.1.1)
* [Branch](https://github.com/fregante/GhostText/tree/future-syntax)
I've noticed that the button disappears when navigating from the repo root to a file/folder. Is that an expected behavior?
=> Fix position of `latest-tag-button`

source/features/link-to-changelog-file.tsx
1. LINKED ISSUES: Closes #3999 
2. TEST URLS:
* [`CHANGELOG.md`](https://github.com/nodeca/js-yaml/releases/tag/4.0.0)
* [`CHANGELOG.rst`](https://github.com/pyca/cryptography/releases)
* [`CHANGES`](https://github.com/sphinx-doc/sphinx/releases)
* [`news`](https://github.com/pypa/pip/releases)
* [`HISTORY.md`](https://github.com/psf/requests/releases)
* note: for every URL, there are two things to test:
1. going directly to the release page
2. going to the repo root (with a cleared cache), _then_ to the release page
=> Support more filenames in `link-to-changelog-file`

readme.md, source/features/clean-repo-sidebar.css, source/features/clean-repo-sidebar.tsx, source/features/repo-age.tsx
1. LINKED ISSUES: Closes #3972
2. TEST URLS:
* [Description, releases & no packages](https://github.com/sindresorhus/refined-github)
* [Packages & releases](https://github.com/Jaboo9/github-packages)
* [Empty meta](https://github.com/Witold101/wpw)
* Releases:
* [No "Releases" section](https://github.com/co1ncidence/mountaineer.vim)
* [Empty "Releases" section](https://github.com/justinfrankel/licecap)
* [Tags instead of releases](https://github.com/tpope/vim-unimpaired)
* Alignments:
* [Top of "About" section with no description](https://github.com/broofa/npmgraph)
* [Repo age & latest tag icon](https://github.com/tpope/vim-unimpaired)
* [License, repo age & latest release icons](https://github.com/sindresorhus/refined-github)
3. SCREENSHOTS:
<details>
<summary>Description, releases & no …
=> Improve `clean-repo-sidebar`

source/features/clean-conversation-headers.tsx
None
2. TEST URLS:
Go to https://github.com/sindresorhus/refined-github/issues/3545#issuecomment-783811667 click on the commit link then go back `history.back()`
3. SCREENSHOT:
None
This also prevents it from running 3 times
=> Fix console error in `clean-conversation-headers`

source/features/hide-useless-comments.tsx
#3992 
2. TEST URLS:
https://github.com/justinfrankel/licecap/issues/97
3. SCREENSHOT:
Before
after
=> Fix `hide-useless-comments` selectors

source/options.tsx
1. LINKED ISSUES: Closes #4012 
2. TEST URLS: the options page
3. SCREENSHOT:
I chose a method with very little code, but I'm not sure about `await`ing `highlightNewFeatures()`. It causes a small but noticeable content jump when opening the options page.
=> Meta: Move new features to the top on the Options page

source/features/align-issue-labels.css, source/features/batch-open-conversations.tsx, source/features/center-reactions-popup.css, source/features/clean-dashboard.css, source/features/clean-repo-sidebar.tsx, source/features/conversation-links-on-repo-lists.tsx, source/features/convert-pr-to-draft-improvements.tsx, source/features/easier-pr-sha-copy.css, source/features/faster-reviews.tsx, source/features/first-published-tag-for-merged-pr.tsx, source/features/linkify-user-edit-history-popup.tsx, source/features/open-issue-to-latest-comment.tsx, source/features/parse-backticks.tsx, source/features/pr-approvals-count.css, source/features/repo-age.tsx, source/features/show-associated-branch-prs-on-fork.tsx, source/features/sync-pr-commit-title.tsx, source/features/tag-changelog-link.tsx, source/options-storage.ts, source/refined-github.css
1. LINKED ISSUES: 
Replaces and closes #4017 
Fixes #4026 
2. TEST URLS:
* [`clean-repo-sidebar`](https://github.com/sindresorhus/refined-github)
* `convert-pr-to-draft-improvements`
* `parse-backticks`
* [Commit title above files list](https://github.com/sindresorhus/refined-github/tree/0887b196c66ec3e170da89f6a42ab295fb324fdd)
* [Commit title above single file](https://github.com/sindresorhus/refined-github/blob/0887b196c66ec3e170da89f6a42ab295fb324fdd/readme.md)
* ["Pulse" page](https://github.com/sindresorhus/refined-github/pulse)
* [`first-published-tag-for-merged-pr`](https://github.com/sindresorhus/refined-github/pull/4013)
* [`align-issue-labels`](https://github.com/sindresorhus/refined-github/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)
GitHub changed some class names …
=> Fix several features that depended on specific classes

source/features/useful-forks.tsx
As per the comment there: https://github.com/sindresorhus/refined-github/pull/3955#issuecomment-787113315
2. TEST URLS:
I don't use GHE, so that's a bit hard for me to provide.
3. SCREENSHOT:
Contextually impossible for me.
=> Hide `useful-forks` on GitHub Enterprise

package-lock.json, package.json, webpack.config.ts
They finally merged https://github.com/primer/octicons/pull/453 and released a new version :tada:
So we can drop the workaround from #3227 :blush:
=> Meta: Simplify Octicons usage

source/features/latest-tag-button.tsx
__New issue:__
The text inside the latest tag button isn’t being truncated, despite having `css-truncate-target`. This causes the file navigation row to overflow (see screenshots).
__Changes:__
This PR adds `css-truncate` to the button to enable the `css-truncate-target` styling.
2. TEST URLS:
https://github.com/gfx-rs/wgpu/
3. SCREENSHOT:
Before:
After:
=> Fix text overflow in `latest-tag-button`

source/features/edit-comments-faster.tsx
Fixes https://github.com/sindresorhus/refined-github/issues/4031
Testable on https://github.com/sindresorhus/refined-github/issues/4030
Notice the edit button on a locked issue:
=> Enable `edit-comments-faster` on locked conversations

source/features/hide-readme-header.css
Fixes #4033 
https://github.com/probablykasper/vidl <-- the spacing should be reasonable, ref: https://github.com/sindresorhus/refined-github/issues/3495
https://github.com/no2chem/bigint-buffer <-- the popover position should be right, ref #4033
=> Simplify `hide-readme-header`: Fixes "Jump to definition" bug

source/features/remove-label-faster.tsx
Currently the close button appears in the new label dialog too, and when clicked the api returns 404 (because of course it doesn't exist, yet)
Any PR/issue and attempt to type a new label name in the tooltip to open the new label dialog
=> Don't mistakenly add `remove-label-faster` when creating a label

distribution/options.html
In the next couple of weeks GitHub will change the format for new authentication tokens.  
https://github.blog/changelog/2021-03-04-authentication-token-format-updates/
The characters used will change from [a-f0-9] to [A-Za-z0-9_] and new tokens will include a prefix ("gp1_" for Personal Access Tokens).  Additionally, after June 1, 2021 the token length will increase to up to 255 characters.  Currently, the form to submit personal tokens in the options page will not accept the new token format.  
This PR changes the pattern of the form input to accept both existing tokens and tokens of the new format. 
Related: https://github.com/fregante/github-issue-link-status/pull/46
=> Accept the new token format in the options

source/features/monospace-textareas.css
Fixes #3998
Any PR for merge + This 72-char title:
```
123456789 123456789 123456789 123456789 123456789 123456789 123456789 12
```
Before:
After:
=> Fix `suggest-commit-title-limit` input field size

source/features/link-to-changelog-file.tsx
Closes #4066 
https://github.com/pypa/pip/releases
Two things to test:
- going directly to the release page
- going to the repo root (with a cleared cache), then to the release page
It was unclear to me what was decided about this, so this PR takes the simplest approach of ignoring folders altogether.
If we want to include them but prioritize files, it would be as simple as separating the list in two instead of filtering it (and maybe also make the selection logic a bit stricter as mentioned in https://github.com/sindresorhus/refined-github/issues/3999#issuecomment-784258402).
=> Exclude folders from `link-to-changelog-file`

source/features/clone-branch.tsx
Fixes #4083
Was renamed see https://github.com/primer/octicons/releases/tag/v12.0.0
https://github.com/fregante/webextension-polyfill/branches
https://github.com/yakov116/refined-github/branches
https://github.com/sindresorhus/refined-github/branches
This is one of the downsides of using select-observer, we do not get to see the errors.
=> Restore `clone-branch` feature

source/features/unfinished-comments.tsx
1. Go to a PR with reviews, e.g. https://github.com/sindresorhus/refined-github/pull/4023
2. Open the dropdown menu of any review comment
3. Go to a different tab
4. The title of the previous tab should NOT say `(Draft comment)`
=> Don't trigger `unfinished-comments` for open comment dropdowns

source/features/comment-fields-keyboard-shortcuts.tsx
Fixes #3662 
- [an issue commented by you](https://github.com/sindresorhus/refined-github/issues?q=is%3Aissue+commenter%3A%40me)
- [a PR commented/reviewed by you](https://github.com/sindresorhus/refined-github/pulls?q=is%3Apr+commenter%3A%40me)
Note: when the comment field at the bottom of a PR thread is selected, pressing Up will edit the last comment _regardless if it's a review comment or a "regular" comment_ (i.e. in the main thread).
Is that intended behavior? Or a small issue with a fix too complex to bother with? (checked the feature history but didn't find mention of this)
=> Fix "Edit last comment" in `comment-fields-keyboard-shortcuts`

source/features/clean-conversation-headers.tsx, source/features/highlight-deleted-and-added-files-in-diffs.tsx, source/features/sticky-sidebar.tsx
Avoids many console error.
Without this pr go from one issue to the next and the do history.back() there will be a console error. `clean-conversation-headers`
Go from the conversation tab to the files changed there will be a console error. `sticky-sidebar`
If needed I can paste all the console errors
=> Correctly remove listeners when leaving certain pages

package-lock.json, readme.md, source/features/no-duplicate-list-update-time.tsx, source/refined-github.ts
Closes https://github.com/sindresorhus/refined-github/issues/3948
This feature applies to conversation lists sorted by updated time
- https://github.com/sindresorhus/refined-github/pulls?q=sort%3Aupdated-asc+is%3Aclosed
- https://github.com/sindresorhus/refined-github/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed+comments%3A0
- [github.com/issues (is:issue is:open author:fregante archived:false sort:updated-desc)](https://github.com/issues?q=is%3Aissue+is%3Aopen+author%3Afregante+archived%3Afalse+sort%3Aupdated-desc)
=> Add `no-duplicate-list-update-time` feature

source/features/night-not-found.css
Context: https://github.blog/changelog/2021-03-16-dimmed-theme-beta-for-github-com/
Tested in both system-sync and single-theme options
=> Add "Dark dimmed" version to `night-not-found`

readme.md, source/features/linkify-full-profile-readme-title.tsx
Fix #4122
https://github.com/sindresorhus
Unnecessary I guess?
P.S. Coincidently, I noticed this icon change a few days ago, but I can't remember this feature existing.
=> Restore `linkify-full-profile-readme-title` feature

source/features/collapse-markdown-sections.ts
Fixes #4126 
- [Links in headings](https://github.com/kidonng/api)
- [Links inside `<code>` elements in headings](https://github.com/cheap-glitch/git-grapnel)
n/a
Note that the sections can still be toggled by clicking on the "side" of the links (since headings are blocks).
This fix also prevents the toggling of a section when the "anchor links" are clicked (which happens otherwise since they are inside the heading elements).
=> Don't `collapse-markdown-sections` when clicking links

source/refined-github.css
Expands only the PR merge status list (and not the popups/dropdowns) to fit all items. This can be thought of as a fix for the popups/dropdowns.
* [dropdown(s) (main)](https://github.com/npm/arborist)
* [dropdown(s) (commit history)](https://github.com/npm/arborist/commits/main)
* [pull request](https://github.com/npm/arborist/pull/254)
<details>
<summary>Long merge status list fixed</summary>
</details>
Fixes #4124.
=> Only expand Checks list on PRs, not in popups

source/features/hide-readme-header.css
relates to https://github.com/sindresorhus/refined-github/pull/4046
(from Github Enterprise v2.21.14)
=> Fix style of `hide-readme-header` on GitHub Enterprise

source/features/bugs-tab.tsx, source/features/releases-tab.tsx
Any repo page
n/a
GitHub changed the layout of the navbar, now it's no longer a list but instead a simple collection of anchor elements. The anchors act both as links and as tabs, so they bear all the meta attributes directly.
=> Fix `releases-tab` and `bugs-tab`

source/features/more-dropdown.tsx
Fixes []() #4166 
Looks like GitHub changed their layout:
The `[data-tab-item$="${id}"]` selector now points to the tab anchor/link.
=> Fix `more-dropdown` removing repo tabs container

distribution/options.html
Fixes #4185
As per https://github.blog/changelog/2021-03-31-authentication-token-format-updates-are-generally-available/
=> Fix access token regex

source/features/bugs-tab.tsx, source/features/more-dropdown.tsx, source/features/releases-tab.tsx
* `more-dropdown`
* https://github.com/microsoft/TypeScript
* https://github.com/eslint/eslint
* `bugs-tab`
* https://github.com/microsoft/TypeScript
* [No issue labels](https://github.com/PHPOffice/PhpSpreadsheet)
* [Archived repo](https://github.com/PHPOffice/PHPExcel)
* `releases-tab`
* https://github.com/atom-community/sync-settings
* [Tags instead or releases](https://github.com/tpope/vim-unimpaired)
n/a
Seems like #4180 wasn't actually needed since the `<a>` is still the one bearing the `.UnderlineNav-item` class:
This PR:
* proposes a hopefully better fix that works for both GitHub and GHE and doesn't leave empty `<li>` in the DOM
* changes `bugs-tab` and `releases-tab` to follow the new DOM structure
=> Fix features related to repo tabs again

source/features/hide-empty-profile-status.css, source/refined-github.css, source/refined-github.ts
Fixes #4160
* [Profile with empty status](https://github.com/Krausso)
* [Profile with status](https://github.com/notlmn)
=> Add `hide-empty-profile-status` feature

source/features/select-all-notifications-shortcut.tsx
Fixes #4198 
* https://github.com/notifications
* https://github.com/notifications?query=is%3Adone
n/a
Steps to reproduce:
1. Make sure you have more than one page of notifications to select
2. Press <kbd>a</kbd> and click "Done"
3. Wait a second or two for the other notifications to load
4. Press <kbd>a</kdb>
5. Nothing happens
=> Preserve `select-all-notifications-shortcut` after clicking Done

source/features/sync-pr-commit-title.tsx
=> Fix backticks conflict in `sync-pr-commit-title`

collaborators.md
What else should we include? This is different from the generic contributors guide, which is more of an entry point and doesn't need to include a lot of details about the codebase.
This file could include instructions on how the codebase is organized and nitpicks to ensure consistency when reviewing, which currently are "unwritten rules" and lints like:
Also in the contributors guide we could add:
- general code instructions (e.g. use this listener instead of that)
- how to reverse engineer GitHub
Reviews and additional draft PRs welcome for this document and the other
=> Meta: Add collaborators guide

contributing.md, package.json
Using `npm run start` instead of `web-ext run --target=chromium` doesn't save a lot of time. Given I have a lot of extensions I just added shorter aliases to my shell and they work everywhere without having to check whether `start` is set. 
For new contributors it also drops the awkward command that appears to be local but requires a global dependency.
=> Meta: Drop unnecessary web-ext redirect

readme.md
Demo URL: https://fregante.github.io/webext-domain-permission-toggle/?name=Refined%20GitHub&icon=https%3A%2F%2Fraw.githubusercontent.com%2Fsindresorhus%2Frefined-github%2Fmain%2Fdistribution%2Ficon.png
Follows https://github.com/fregante/webext-domain-permission-toggle/pull/20
No bitmaps were harmed in the making of that page 😃
=> Meta: Improve GHE documentation in readme

source/features/releases-tab.tsx
https://github.com/sindresorhus/refined-github/releases
=> Fix `releases-tab` not being highlighted on release pages

source/background.ts
I initially had it open in background because I don't like things opening automatically, but this actually causes the tab to be lost if someone has several tabs open. The welcome page contains important information to ensure every feature works (API key)
=> Meta: Open Welcome page in foreground

source/features/one-key-formatting.tsx, source/github-events/on-field-keydown.tsx
Fix #4231. 
Specifically, this PR adds one-key-formatting to:
- the title of a new issue
- the body of a new issue
- the title of a new PR (this already works for the body of a new PR)
- the title of a new gist
- the title and body of [saved replies](https://github.com/settings/replies)
Reference for the difference between `pageDetect.hasCode` and `pageDetect.hasRichTextEditor`: https://github.com/fregante/github-url-detection/blob/9aa429df7af2807ce4797c02b164f83386c453bb/index.ts#L474-L488
one-key-formatting no longer applies on the pages flagged by `pageDetect.isRepoTree` and `pageDetect.isBlame`, which is OK because there are no text inputs on these pages.
Unfortunately, one-key-formatting does not work when creating new files/gists or editing existing files/gists. This is because the …
=> Enable `one-key-formatting` on more pages

safari/Refined GitHub.xcodeproj/project.pbxproj, safari/Refined GitHub/ViewController.swift
I also slightly improved the look of the wrapper app:
=> Improve error handling for the Safari extension app

source/features/show-user-top-repositories.tsx
Closes #4221 
https://github.com/sindresorhus
n/a
=> Simplify `show-user-top-repositories`

source/github-widgets/notice-bar.tsx
Fixes #4227
https://github.com/sindresorhus/refined-github/blob/main/media/promo.png?rgh-link-date=2017-04-12T07%3A11%3A49Z
=> Align `comments-time-machine-links` banner to the site header

source/features/hide-useless-newsfeed-events.css
This PR adds releases to `hide-useless-newsfeed-events`. Since recently, published releases appear in the newsfeed. They take a lot of place, and I can even see some bots' releases. I figured it was pretty much useless and could belong in this feature.
- https://github.com/ (when logged in, newsfeed)
=> `hide-useless-newsfeed-events`: Hide releases too

package-lock.json, package.json, source/features/new-repo-disable-projects-and-wikis.tsx
https://github.com/fregante/browser-extension-template/generate
=> Extend `new-repo-disable-projects-and-wikis` to new repo templates

source/features/bugs-tab.tsx
https://github.com/sindresorhus/refined-github/issues/4260
=> Fix `bugs-tab` highlighting

source/features/ci-link.tsx
Fix https://github.com/sindresorhus/refined-github/pull/4267#issuecomment-826471250
- Should show icon: this repo
- Should not show icon: https://github.com/kidonng/refined-github
Before: 
After:
=> `ci-link`: Don't incorrectly show *Verified next to a repo title

source/features/vertical-front-matter.tsx
Fix #4273
There isn't a selector which tells us it's a front matter or not, so we are on our own.
I come up with some rules that should handle most cases:
- The table should be the first element
- The table should only have one row in the body
- The head row and the body row should have the same number of cells
Suggestions welcome. Honestly I don't want to drop this feature just because we don't have a nice way to support it :(
- With front matter: https://github.com/gatsbyjs/gatsby/blob/HEAD@%7B2020-07-08T14:12:43Z%7D/docs/blog/2020-07-07-wordpress-source-beta/index.mdx
- Invalid table as first element: https://github.com/kidonng/refined-github/blob/8bec852e016d10a574b1a456174139d6bb9e6c99/test.md
- Valid table, but not as first element: …
=> Restore `vertical-front-matter`

source/features/latest-tag-button.tsx
Partially replaces https://github.com/sindresorhus/refined-github/pull/4187
Re #4196. Currently we cannot determine the branch. However this change should happen anyways. 
=> Fix `latest-tag-button` on repo home page

source/features/set-default-repositories-type-to-sources.tsx
"Your repositories"  does not exist on gists
```js
❌ set-default-repositories-type-to-sources 0.0.0 → TypeError: Cannot read property 'search' of undefined
at addSourceTypeToLink (refined-github.js:13332)
at profileDropdown (refined-github.js:13350)
at async runFeature (refined-github.js:8785)
at async setupPageLoad (refined-github.js:8803)
at async chrome-extension:/pplhppbihehddgkdedhpbfpbbbefeihl/build/refined-github.js:8867
```
https://gist.github.com/sindresorhus
=> Fix console error in `set-default-repositories-type-to-sources`

source/features/next-scheduled-github-action.tsx
```
next-scheduled-github-action 0.0.0 → TypeError: Cannot read property 'entries' of null
at webext_storage_cache__WEBPACK_IMPORTED_MODULE_1__.default.function.maxAge.days (refined-github.js:10401)
at async getSet (refined-github.js:24127)
at async init (refined-github.js:10435)
at async runFeature (refined-github.js:8785)
at async setupPageLoad (refined-github.js:8803)
```
https://github.com/k0shk0sh/FastHub/actions
None
=> Fix error in `next-scheduled-github-action` when no action files exist

source/helpers/bisect.tsx
Closes #4295 
1. Complete "Find feature" wizard and remain on the last step
2. Change tab & go back
3. The bisect modal should NOT say "Process completed in another tab"
https://user-images.githubusercontent.com/46634000/116893307-1b84e000-ac31-11eb-90d0-845299e65a6c.mp4
=> Meta: Don't hide final bisect message when changing tab

source/features/quick-repo-deletion.tsx
Respecting: 0d186f70335f1efa2dfbe213f16dbcf7dff6e50e
Check your any forked repositories.
=> Consistent button label in `quick-repo-deletion`

source/features/remove-label-faster.css
Following the PR for fixing the hover color on labels https://github.com/sindresorhus/refined-github/commit/074b2b8c2f0a12d82e6b528db1b6366f017148fa, I forgot to consider dark mode:
https://user-images.githubusercontent.com/43481548/117852277-10f4c700-b27f-11eb-9166-bb02a6287ffc.mov
Sorry this is not a gif, Gifski didn't like this video.
In previous versions it looks like in dark mode the X was just black.
I attempted to make the X the background color of the label, however this did not work as the background color has transparency and is made dark by the body background.
To avoid overcomplication my fix/suggestion is to set the X to the body background color.
Tested on Firefox and Chrome
Dark
Dark Dimmed
=> Support for dark mode in `remove-label-faster`

source/features/edit-comments-faster.tsx
Closes #4334
https://github.com/tophf/mpiv/discussions/50
- The added selector `.timeline-comment-actions details:last-child` (or `.timeline-comment-actions > div > details:last-child` ) is for discussions
=> Enable `edit-comments-faster` on Discussions

source/features/dim-bots.tsx
Closes #4354
Fixes a regression from #3921 causing the PRs with more than just the `bot` label not to be dimmed anymore.
1. Create a pull request with a `bot` label and any other one.
2. Browse to https://github.com/pulls
|     | normal | hover |
| --- | ------ | ----- |
| Before | ![image](https://user-images.githubusercontent.com/47184027/118136965-a94f9080-b3d2-11eb-815e-e0778f621fb8.png) | N/A |
| After | ![image](https://user-images.githubusercontent.com/47184027/118136665-5b3a8d00-b3d2-11eb-863e-4ceaec5c67ab.png) | ![image](https://user-images.githubusercontent.com/47184027/118136710-67264f00-b3d2-11eb-8c66-4512152c5793.png) |
=> Fix `dim-bots` with multiple PR labels

source/features/quick-repo-deletion.css, source/features/sticky-sidebar.css
Fixes #4363 
Fixes #4192 
Preserves https://github.com/sindresorhus/refined-github/pull/3754
1. Find own fork that can be deleted by `quick-repo-deletion`, like https://github.com/fregante/xo for me
2. Click "Delete fork" button
1. Find own repo (can be the same as above), like https://github.com/fregante/xo for me
2. Click gear icon in sidebar
=> Fix `z-index` bug in `quick-repo-deletion` and `sticky-sidebar`

source/features/index.tsx, source/helpers/hotfix.ts
Fixes https://github.com/sindresorhus/refined-github/issues/4324
To test this PR, the manifest version needs to be manually changed. I tested it and the function correctly returns the expected option settings.
=> Meta: Add per-feature “unaffected” version in the hotfix manager

package.json
When attempting to run lint checks from the top directory, I encountered the following error:
```
C:\Repos\refined-github>npm run lint:css
> lint:css
> stylelint 'source/**/*.css'
Error: No files matching the pattern "'source/**/*.css'" were found.
at C:\Repos\refined-github\node_modules\stylelint\lib\standalone.js:212:12
at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
After this fix, lint checks run as expected without errors.
It's very possible that this is an error that only affects me, seeing as though the code hasn't changed a year. Please let me know if the error exists on your end!
Edit: Sorry for the spam title changing. Forgot that gets added to the log.
=> Meta: Fix `lint:css` error on Windows

source/features/global-conversation-list-filters.tsx
Closes #3731
1. if sort by Recently updated is disabled, Github url will be changed as short automatically after clicking review requests tab, mentioned or something.
2. then click Commented tab, the bug occurs.
=> Fix `global-conversation-list-filters` creates faulty links

source/features/highlight-deleted-and-added-files-in-diffs.tsx
See https://github.blog/changelog/2021-05-25-new-tools-to-discover-and-resolve-pull-request-conversations-beta/
Console error
```
refined-github.js:8434 Uncaught TypeError: Cannot read property 'cloneNode' of undefined
at add (refined-github.js:8434)
at runAdd (refined-github.js:4334)
at applyChanges (refined-github.js:4304)
at SelectorObserver.addRootNodes (refined-github.js:4456)
at Array.processBatchQueue (refined-github.js:4276)
at MutationObserver.handleMutations (refined-github.js:4293)
add @ refined-github.js:8434
runAdd @ refined-github.js:4334
applyChanges @ refined-github.js:4304
addRootNodes @ refined-github.js:4456
processBatchQueue @ refined-github.js:4276
handleMutations @ refined-github.js:4293
setTimeout (async)
handleMutations @ refined-github.js:4295
attributes (async) …
```
=> Restore `highlight-deleted-and-added-files-in-diffs`

source/features/clean-repo-sidebar.tsx
=> `clean-repo-sidebar` fix: Section disappears if URL includes “releases”

source/features/index.tsx, source/helpers/wait-for.ts
Fixes #4376
This is hard to test since it's a rare occurrence.
1. Specify CSS in the options
2. Reload the page a million times
=> Fix: Extension may fail to load if custom CSS is specified

source/features/embed-gist-inline.tsx
Tested on non-GHE, still works 
https://gist.github.com/fregante/cf4d0415c4802e0c81812ae9bbb821d8
https://gist.github.com/fregante/afa017a7c81dd5f5eeefc963593088b4
https://gist.github.com/fregante
=> `embed-gist-inline` fix: Exclude gist user links on Enterprise

source/features/edit-comments-faster.tsx
Fix #4400
Discussions where you don't have made any comments, and you are not maintainer/collaborator,
e.g. https://github.com/streetcomplete/StreetComplete/discussions/2671
The issue #4400 is about this line:
https://github.com/sindresorhus/refined-github/blob/575f41a7faacd5901065cfae634ce0399658d1cb/source/features/edit-comments-faster.tsx#L11
That selector works ok in Issue pages *(it selects all your comments that you can edit)*, 
but it doesn't work ok in Discussion pages - it wrongly selects all comments).
This PR adds a check so that, if in the Discussion page there's a "`You are a (maintainer/collaborator)`" element
~~or it's in Issues page, then use the old selector,~~, or that you still can edit the page,
otherwise add to that selector this class: `.current-user` (=comments made …
=> Fix `edit-comments-faster` to only when editing is allowed

source/features/deep-reblame.tsx
Fixes #4440 
1. Visit https://github.com/pixiebrix/pixiebrix-extension/blame/69a0e85c03f57e094591865b5dcf0632c4c9e26f/browsers/chrome/webpack/webpack.dev.js#L101
2. alt-click reblame icon
Related PR in commit title: it should "enter" it https://github.com/sindresorhus/refined-github/blame/b5497da33a6c5b99eb518ecc266881780bc11877/contributing.md#L7
Unrelated PR in commit title: it should `alert()` https://github.com/sindresorhus/refined-github/blame/d1e27cb34f18b9d5d57fdbf853e5b15c3a660d85/source/features/deep-reblame.tsx#L67
Renamed file: it should `alert()` https://github.com/sindresorhus/refined-github/blame/fad67fb8d8fcf608601c9b8ae1b5f12337cbccce/source/options.html#L1
=> Check for multiple related issues in `deep-reblame`

source/features/repo-wide-file-finder.tsx
The repo wide file finder was always loading the finder for the repo's default branch, even if a different branch/tag was selected. This updates the logic to try to get the current branch from the URL before falling back to the default.
https://github.com/optics-dev/Monocle/tree/v3.0.0-RC2
https://github.com/optics-dev/monocle/commits/v3.0.0-RC2
Note `master` in the find URL
<details>
<summary>expand GIF</summary>
</details>
Note `v3.0.0-RC2`, the selected tag, in the find URL
<details>
<summary>expand GIF</summary>
</details>
=> `repo-wide-file-finder`: Use current branch/tag when possible

source/features/fit-textareas.tsx
[fit-textarea](https://github.com/fregante/fit-textarea) v2 is slow on Safari (https://github.com/sindresorhus/refined-github/issues/4266) and v3 is slow on Chrome (https://github.com/sindresorhus/refined-github/issues/4275)
To re-enable v3, I need to figure out why it's so slow on Chrome
=> Disable `fit-textarea` in Safari

source/features/clean-conversation-sidebar.tsx
Fixes #4238 
Fixes #4258 
* this PR
* [merged PR](https://github.com/sindresorhus/refined-github/pull/3951)
* [open issue with one linked PR](https://github.com/sindresorhus/refined-github/issues/4397)
* [open issue with a milestone and assignee](https://github.com/microsoft/TypeScript/issues/43501)
* User has triage access
* [Issue](https://github.com/download-directory/download-directory.github.io/issues/39)
* [PR](https://github.com/download-directory/download-directory.github.io/pull/37)
<details>
<summary>This PR</summary>
</details>
<details>
<summary>Merged PR</summary>
</details>
<details>
<summary>Open issue with linked PR</summary>
</details>
<details>
<summary>Open issue with milestone and assignee</summary>
</details>
<details>
<summary>PR with no labels (<i>user has triage …
=> Restore `clean-conversation-sidebar` feature

source/features/emphasize-draft-pr-label.css, source/refined-github.ts
New icons might make this change unnecessary https://twitter.com/GHchangelog/status/1402312797187366914
Last related PR https://github.com/sindresorhus/refined-github/pull/2848
=> Drop `emphasize-draft-pr-label` feature

package-lock.json, package.json, source/features/collapse-wiki-sections.tsx
Fix #4463
`collapse-wiki-sections` should run on:
- Regular wiki pages: https://github.com/lukesampson/scoop/wiki
But not:
- New page: https://github.com/tooomm/wikitest/wiki/_new
- Edit page: https://github.com/tooomm/wikitest/wiki/Getting-Started/_edit
N/A
=> Don't run `collapse-wiki-sections` on Wiki edit pages

source/features/mark-merge-commits-in-list.tsx
Closes #4468 
https://github.com/pixiebrix/pixiebrix-extension/commits/main
https://github.com/babel/babel/commits/master?after=ddd40bf5c7ad8565fc990f26142f85613958a329+104
##Screenshot
=> Fix `mark-merge-commits-in-list` commit hash selector

source/features/swap-branches-on-compare.tsx
Closes #4390
In direct comparison, `swap-branches-on-compare` feature is not needed because of the same result after swap.
To fix this bug, `swap-branches-on-compare` should be disabled.
So check if only 2-dot exists.
- https://github.com/sindresorhus/modern-normalize/compare/af8df39ff9abd290cb5ee22b7d1cc3451367f8fe..f9a9045502138c23478c2d4760dfa28e01d53e7b
=> Disable `swap-branches-on-compare` in direct comparison

source/features/prevent-link-loss.tsx
Try adding this URL to a new comment (e.g. in this PR):
https://github.com/github/choosealicense.com/compare/gh-pages...Pukimaa:gh-pages#diff-c0311c1df17d5d714db46ca1401ad374a35de861a461d211c6c947f1b2194034R8
After
=> Fix `prevent-link-loss` warning message copy

source/features/reactions-avatars.css
There are users with a very small profile image:
GitHub scales up profile images to fill avatar circles in comments though:
So these two avatar circles look like two different people. Changing `max-width` to `width` in `reaction-avatars` fixes it:
- user with a very small profile image: `https://github.com/Strubbl`
- that user's profile image: `https://avatars.githubusercontent.com/u/97055?v=4`
- comment with that user's reaction: `https://github.com/streetcomplete/StreetComplete/issues/2909#issuecomment-860959344`
- comment by that user: `https://github.com/streetcomplete/StreetComplete/issues/1176#issuecomment-860973960`
=> Fix very small images in `reaction-avatars`

source/features/hidden-review-comments-indicator.tsx, source/features/no-useless-split-diff-view.tsx, source/features/show-whitespace.tsx, source/github-events/on-diff-file-load.ts
This fixes #4488.
Maybe it's off-topic, but I think the listener's name should be something like `onDiffFileLoad` instead of `onPrFileLoad`. It made me wonder whether it works on non-PR pages.
I've tested this at:
-   [button](https://github.com/cpeditor/cpeditor/pull/223/files?diff=split#diff-0f46ff9666ae4dc3789ffaed0f2c4a93fbd4469ab486af80f1b262cb44b7a038)
-   [long](https://github.com/cpeditor/cpeditor.github.io/commit/b349da5cefab537691e1988f74252759aff9c300?diff=split)
=> Fix `no-useless-split-diff-view` doesn't work newly loaded files

source/features/open-issue-to-latest-comment.tsx
Closes #4496
What it looked like before (Sorry could not find a better screenshot)
Now
@fregante title good?
=> Remove `open-issue-to-latest-comment` from the dashboard

source/features/git-checkout-pr.tsx
Closes #4489 
If you click on the dropdown before the page has fully loaded you will get the error.
https://github.com/sindresorhus/refined-github/pull/4448 or this PR
=> Ensure the dropdown loaded in `git-checkout-pr`

source/features/unwrap-useless-dropdowns.tsx
Fix #4512
https://github.com/sindresorhus/refined-github/actions/runs/967719800
Before:
After:
=> Fix `unwrap-useless-dropdowns`'s button size on actions page

source/features/pr-approvals-count.css
Closes #4517
https://github.com/Cog-Creators/Red-DiscordBot/pulls?page=2&q=is%3Apr+is%3Aopen+sort%3Aupdated-desc
https://github.com/Cog-Creators/Red-DiscordBot/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed
**Before**
**After**
=> Fix: Milestone is shown red on PR lists when it contains word "changes"

source/features/no-useless-split-diff-view.tsx
Fixes #4483 
* [Diff should be collapsed](https://github.com/sindresorhus/refined-github/commit/f60cb71e0bc2708ebda622d6c684489241fd367a?diff=split)
* [Diff should be untouched](https://github.com/sindresorhus/refined-github/commit/26e778fd85f7db6c3d5bc6f508e23c77f3ed4a20?diff=split)
n/a
This needs to be tested on GHE 2.22.10 or lower (both diffs should be left untouched).
=> Fix `no-useless-split-diff-view` on GitHub Enterprise

source/features/sticky-sidebar.css, source/features/sticky-sidebar.tsx
Fixes #4490 
Related: #3754, #4364 
- On this page:
* click the "Open with" button → the dropdown should be over the sidebar
* click the "Customize" button next to "Notifications" → the modal's background should cover everything (except the sticky header)
- On a repo root where you can edit the sidebar
* click the gear icon → the modal's background should cover everything
=> Fix: `sticky-conversation-sidebar` overlaps "Open with" dropdown

.github/workflows/test.yml
Re https://github.com/sindresorhus/refined-github/issues/4008#issuecomment-873594509
See https://github.blog/changelog/2021-07-02-github-actions-setup-node-now-supports-dependency-caching
NA
NA
=> Meta: Enable npm cache for actions

source/features/set-default-repositories-type-to-sources.tsx
Currently all tabs get the `?type=source`
https://github.com/microsoft
None
=> Fix: `set-default-repositories-type-to-sources` changes unrelated URLs

distribution/options.html
Required for the `quick-repo-deletion` feature (#3734, #3795).
| Current link ([`...&scopes=repo`](https://github.com/settings/tokens/new?description=Refined%20GitHub&scopes=repo)) | New link ([`...&scopes=repo,delete_repo`](https://github.com/settings/tokens/new?description=Refined%20GitHub&scopes=repo,delete_repo)) |
|-|-|
| <img src="https://user-images.githubusercontent.com/478237/125177554-b4594e00-e1d4-11eb-811b-8337b13f102f.png" width="350px" /> | <img src="https://user-images.githubusercontent.com/478237/125177551-b3c0b780-e1d4-11eb-898f-5feff21be668.png" width="350px" /> |
| ![Screenshot from 2021-07-10 23-19-51](https://user-images.githubusercontent.com/478237/125177730-22eadb80-e1d6-11eb-827a-501fadb51cab.png) | ![Screenshot from 2021-07-10 …
=> Meta: Add `delete_repo` scope to token generation link

source/features/follow-file-renames.tsx
Closes #4477 
https://github.com/sindresorhus/refined-github/commits/main?after=285eaec360f21431757236c6c39cdbe6f303f6e2+34&branch=main&path%5B%5D=source&path%5B%5D=background.ts
<hr>
=> Make `follow-file-renames` more noticeable by adding icons

source/features/link-to-changelog-file.tsx
Closes #4577 (following https://github.com/sindresorhus/refined-github/issues/4577#issuecomment-881951763)
Match: (as before)
https://github.com/pyca/cryptography/releases (`CHANGELOG.rst`)
https://github.com/nodeca/js-yaml/releases/tag/4.0.0  (`CHANGELOG.md`)
Not match: 
https://github.com/vercel/hyper/releases  (`release.js`)
(none)
- The markdown extension regex is from: [`vertical-front-matter`](https://github.com/sindresorhus/refined-github/blob/31a04dd8b43d4fe121bf5a467dbc0cdada568756/source/features/vertical-front-matter.tsx#L9) / [`view-markdown-source`](https://github.com/sindresorhus/refined-github/blob/31a04dd8b43d4fe121bf5a467dbc0cdada568756/source/features/view-markdown-source.tsx#L34)
```regex
/\.(mdx?|mkdn?|mdwn|mdown|markdown|litcoffee)$/
```
I added to it: `|txt|rst` to …
=> `link-to-changelog-file`: Exclude non-textual files

source/features/copy-file.tsx
Closes #4451
`table.highlight` is a selector that means the area of displayed code.
I removed two delegates. This is because `.rgh-md-source` is a selector that doesn't exist in this repository.
https://github.com/sindresorhus/refined-github/blob/main/media/icon.svg
https://github.com/sindresorhus/refined-github/blob/main/contributing.md
https://github.com/sindresorhus/refined-github/blob/hotfix/hotfix.csv
=> Remove `copy-file` from rendered pages

source/features/follow-file-renames.tsx, source/features/mark-merge-commits-in-list.tsx
GitHub add the `[aria-label="Copy the full SHA"]` to the div above it too (WHY?!)
Edit: I see why they did it, the tooltip does not work on the `clipboard-copy`
https://github.com/sindresorhus/refined-github/pull/4530/commits
```
mark-merge-commits-in-list 0.0.0 → TypeError: Cannot read property 'parents' of null
at refined-github.js:5892
at async init (refined-github.js:5890)
at async runFeature (refined-github.js:1932)
at async setupPageLoad (refined-github.js:1945)
at async refined-github.js:1966
````
=> Fix `mark-merge-commits-in-list` feature

source/features/clean-pinned-issues.css
Closes #4598. Fix for vertical misalignment in `clean-pinned-issues` info.
https://github.com/sindresorhus/refined-github/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
<b>Before:</b>
<p align="center"><img alt="github com_sindresorhus_refined-github_issues_q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc" src="https://user-images.githubusercontent.com/82655227/126626685-ebf284df-2027-4fae-8b44-15c713103f82.png" width="512px" /></p>
<b>After:</b>
<p align="center"><img alt="github com_sindresorhus_refined-github_issues_q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc" src="https://user-images.githubusercontent.com/82655227/126626693-5f5eb415-ecd1-47b1-b74c-bc200bad4289.png" width="512px" /></p>
=> Vertically center text of `clean-pinned-issues`

source/features/reactions-avatars.css, source/features/reactions-avatars.tsx
I think that having links in here doesn't make much sense and it's just problematic (the browser will _occasionally(!)_ follow the link when clicking the button) so let's just drop it.
~I should probably also replace the A with a SPAN, that requires changes in the CSS file as well~ _Done_
This PR
=> Stop linking avatars in `reactions-avatars`

source/features/select-notifications.tsx
Happens when there are no notications.
URL: https://github.com/notifications
```
TypeError: Cannot read property 'closest' of undefined
at init (chrome-extension://pplhppbihehddgkdedhpbfpbbbefeihl/build/refined-github.js:13715:91)
at runFeature (chrome-extension://pplhppbihehddgkdedhpbfpbbbefeihl/build/refined-github.js:9195:17)
at setupPageLoad (chrome-extension://pplhppbihehddgkdedhpbfpbbbefeihl/build/refined-github.js:9213:11)
at chrome-extension://pplhppbihehddgkdedhpbfpbbbefeihl/build/refined-github.js:9265:15
```
=> Fix console error in `select-notifications`

source/features/one-click-pr-or-gist.tsx
Closes #4565.
`https://github.com/darkred/test/compare/main...t2?expand=1`
<details>
<summary>Before:</summary>
<details>
<summary>After:</summary>
</details>
=> `one-click-pr-or-gist`: Make the Create PR buttons be disabled when the title field is empty

source/features/default-branch-button.tsx, source/features/latest-tag-button.tsx
Fixes #4623 
I just took the attribute from the `master` element and it worked 😅
It is also used for other elements so it seems to be the right way to trigger an AJAX navigation.
https://github.com/vutran/twas/tree/v2.1.2
https://user-images.githubusercontent.com/9264728/127857124-caf84808-6975-4b04-88bc-a82fe3439c1e.mp4
Chromium 92.0.4515.107
=> Use AJAX navigation for `default-branch-button`

source/features/index.tsx
Fixes #4622
The issue described in #4622 was caused because the `<has-rgh-inner>` element was removed on the first navigation.
So all features that checked it ran again, but the loader that would add `<has-rgh-inner>` again didn't run because the `<has-rgh>` was still present.
This PR splits them up into two loaders, I did not yet unify the code.
We could e.g. refactor it into a factory function, happy to do this if wanted.
=> Fix some features appearing multiple times

source/features/bugs-tab.tsx
Related to #4592
Adds the label "kind:bug" to the `bugs-tab`, as kind is another form of writing type
https://github.com/vercel/next.js/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22kind%3A+bug%22
=> Support `kind:bug` label in `bugs-tab`

source/features/quick-repo-deletion.tsx
Fixes #4599 
A fork you own or an empty repo with no stars
https://user-images.githubusercontent.com/46634000/128853508-fdde8f28-4786-465f-ac45-6f71d6178b5e.mp4
Turns out the z-index was not the problem, rather it was the controller that wasn't aborted.\
**Tested on Firefox only**
=> Fix `quick-repo-deletion` not aborting on Firefox

source/features/reactions-avatars.css
Fix #4630
- Discussions: https://github.com/github/feedback/discussions/4291
- Releases: https://github.com/sindresorhus/refined-github/releases/tag/21.8.1
=> Fix style conflict caused by `reactions-avatars` on other pages

source/features/follow-file-renames.tsx, source/features/index.tsx, source/features/useful-not-found-page.tsx
This PR adds a couple of things mentioned in #4617:
- If the branch does not exist and the user is trying to view a file on that branch, tell the user that the branch was deleted.
* In addition, check if the file exists on the default branch (existing behaviour)
- If the file was deleted/moved, show who did it, when and with which commit. Also link to the last version of the file before the commit took place.
- If the file was renamed, show who did it, when and with which commit. Also link to the renamed file.
All of the above information is added as the API calls resolve.
Closes #4617 (if merged).
- Renamed file: https://github.com/gamemaker1/test/blob/main/rename-test/readme.txt
- Moved/deleted file: https://github.com/gorhill/uBlock/blob/master/assets/ublock/resources.txt
- Non …
=> Add more details to `useful-not-found-page` 

distribution/options.html, source/features/bugs-tab.tsx, source/github-helpers/api.ts, source/helpers/fetch-dom.ts, source/options-storage.ts, source/options.tsx
Added to:
- api.v3
- api.v4
- fetchDom
I added as a new option since having it on by default is going to be annoying. Including in the other logging option does not make any sense.
=> Meta: Log API calls and other fetches

package-lock.json, package.json
Fixes [#4505](https://github.com/sindresorhus/refined-github/issues/4505)
PR that fixes bug in shorten-repo-url -[ Ignore links that contain tags/images ](https://github.com/fregante/shorten-repo-url/pull/30)
https://github.com/saarahasad/egormanga
=> `shorten-repo-url`: Avoid loss of images/formatting in links

readme.md, source/features/reactions-avatars.css, source/features/reactions-avatars.tsx
- Fix for #4674 
Regular comment: https://github.com/sindresorhus/refined-github/issues/4674
Review: https://github.com/sindresorhus/refined-github/pull/4667#pullrequestreview-730139417
Review comments: https://github.com/sindresorhus/refined-github/pull/4667#discussion_r689119705
=> Fix `reactions-avatars` conflict with new style

source/features/navigate-pages-with-arrow-keys.tsx
When single commits are selected on pull requests, there is a pagination that enables moving between commits.
- [`1e1e070` (#4677)](https://github.com/sindresorhus/refined-github/pull/4677/commits/1e1e0707ac58d1a40543a92651c3bbfd113481bf)
- [`d5a6052` (#4677)](https://github.com/sindresorhus/refined-github/pull/4677/commits/d5a6052eeef5f57f47e1bd3aec43caa3cebb1813)
=> Extend `navigate-pages-with-arrow-keys` to pull request commit pages

source/features/toggle-files-button.css, source/refined-github.css
Fix #4719
I also took the chance to remove the seemingly no longer existing `.file-wrap` which is introduced in 07ecc75e81cbc466d6bc98a12505ae58fec68d59 (5 years ago) and #1017 (3 years ago).
Before:
After:
=> Fix extra border in `toggle-files-button`

source/features/comments-time-machine-links.tsx, source/features/linkify-branch-references.tsx, source/features/linkify-symbolic-links.tsx, source/features/list-prs-for-file.tsx, source/features/rgh-feature-descriptions.tsx, source/features/swap-branches-on-compare.tsx, source/features/view-markdown-source.tsx
Motivation: https://github.com/sindresorhus/refined-github/pull/4631#issuecomment-891201750
This PR will continue for a few days in case anyone find something new, but hopefully searching for `<a` will give not too much results to check.
Ajaxed features and Test URLS:
- `comments-time-machine-links`: https://github.com/sindresorhus/refined-github/blob/main/.gitattributes?rgh-link-date=2021-08-01
- `linkify-branch-references`: 🤷‍♀️ Something like https://github.com/sindresorhus/refined-github/compare/main...test?quick_pull=1
- `linkify-symbolic-links`: https://github.com/lxqt/lxqt/blob/master/CONTRIBUTING
- `list-prs-for-file`: https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/all-packages.nix
- `rgh-feature-descriptions`: …
=> Make some feature-generated links load via AJAX

source/features/rgh-feature-descriptions.tsx
Closes #4697 if merged.
Changes the CSS selector used to add the feature description box on RGH feature pages from `.Box-header--blue.Details, include-fragment.commit-loader` to `.hx_commit-tease`
https://github.com/sindresorhus/refined-github/blob/main/source/features/reactions-avatars.tsx
https://github.com/sindresorhus/refined-github/blob/main/source/features/clean-conversation-headers.tsx
=> Fix `rgh-feature-descriptions` feature

source/features/emphasize-draft-pr-label.css, source/refined-github.ts
- Reverts sindresorhus/refined-github#4450
On second thought… the contrast between the two is still too low.
=> Restore `emphasize-draft-pr-label` feature

source/features/list-prs-for-file.tsx
Via [Scroll To Text Fragment](https://github.com/WICG/scroll-to-text-fragment) we can direct the browser to the corresponding file in `list-prs-for-file`'s links, without fetching the page to get a hash.
This is not 100% accurate but should be fine most of the type, and it does nothing on a unsupported browser.
https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/all-packages.nix
https://user-images.githubusercontent.com/44045911/131881041-a93830e7-bd3b-4b22-86a6-baa3cd8c41a8.mov
=> Link to exact file in PR in `list-prs-for-file` (Chrome only)

build/verify-features.ts, source/refined-github.ts
This will make CI fail if we remove a feature but forget to remove its CSS file.
Note: There are currently two orphaned CSS files which are being removed in #4715, but https://github.com/sindresorhus/refined-github/pull/4715#discussion_r696328315 suggested extracting this to a separate PR to demonstrate the script failing when we expect it to.
[Example failure](https://github.com/sindresorhus/refined-github/runs/3437113085?check_suite_focus=true):
=> Meta: Catch orphaned CSS files on CI

source/features/parse-backticks.tsx
Closes #3975 finally
https://github.com/tophf/mpiv/discussions/50
The `.js-issue-title` selector for Discussion page titles of my PR #3977 had to be removed, in PR [#4136 (comment)](https://github.com/sindresorhus/refined-github/pull/4136#issuecomment-805101315).
Following https://github.com/sindresorhus/refined-github/issues/3975#issuecomment-815975667, the selector in this PR, `.js-discussions-title-container h1 > .js-issue-title` 
matches (*once*) in discussion pages, and it doesn't matches in issue pages.
If I remove the `h1 >` part then it matches *twice* in discussion pages (i.e. also in a hidden element).
=> Restore `parse-backticks` on Discussions

source/features/follow-file-renames.tsx
Fixes #4774
Caused by https://github.com/sindresorhus/refined-github/pull/4677
- https://github.com/sindresorhus/refined-github/commits/main/source/features/quick-pr-diff-options.tsx
The following URLs point to the life-cycle of a single file called `site.rb` in https://github.com/ForkAwesome/Fork-Awesome.
- https://github.com/ForkAwesome/Fork-Awesome/commits/master/src/doc/_plugins/site.rb
- https://github.com/ForkAwesome/Fork-Awesome/commits/master/src/_plugins/site.rb
- https://github.com/ForkAwesome/Fork-Awesome/commits/master/source/_plugins/site.rb
- https://github.com/ForkAwesome/Fork-Awesome/commits/master/build/_plugins/site.rb
The first URL should have only the **Older** button linkified, the second and third URLs should have both buttons linkified and the last URL should have …
=> Don't `follow-file-renames` when file was not renamed

source/features/useful-not-found-page.tsx, source/github-helpers/github-url.ts
Fixes #4790 if merged.
Restores a check from https://github.com/sindresorhus/refined-github/commit/6047ca569d61638025a26f29a31ab9069b0dd108 that does not run the `showDefaultBranchLink` and `showAlternateLink` functions if the URL is not a `blob`/`tree`/`edit` one.
From the original issue:
https://github.com/octokit/rest.js/issues/558
=> `useful-not-found-page`: Show alternate links only if applicable

source/features/view-markdown-source.tsx
Related to #4244, this adds support for another common markup format that is rendered by GitHub, reStructuredText.
Should this feature be renamed to `view-markup-source` since it would now support more formats than just markdown? I'll let someone else decide.
- https://github.com/github/markup/blob/46908504f5/test/markups/README.rst
=> Add support for `rst` files to `view-markdown-source`

source/features/select-notifications.css, source/features/select-notifications.tsx
Fixes #4753 
https://user-images.githubusercontent.com/46634000/133922795-289fb9b2-1ea9-4b03-b3b7-b3cac7152e36.mp4
=> Fix: "Done" click is ignored when `select-notifications` is open

source/features/rgh-feature-descriptions.tsx
The dropdown is a little inconvenient because it closes every time you click on a commit, making it difficult to open more than one at a time. I think it's easier to just open the History page.
One possible meta feature in that case would be to dim every meta/lint commit in the regular commit list of Refined GitHub, using the styles of `dim-bots`
=> Meta: Drop "Feature history" dropdown

source/features/quick-comment-edit.tsx
Closes #4712 if merged.
This is an up-to-date version of #4749.
Does not add the edit button on comments from other users if the current user is not allowed to edit them.
https://github.com/facebook/jest/issues/6316 (locked issue)
https://github.com/facebook/jest/issues/11791 (regular issue)
=> Fix: `edit-comments-faster` appears on every comment

contributing.md, source/features/comment-on-draft-pr-indicator.tsx, source/features/comments-time-machine-links.tsx, source/features/copy-file.tsx, source/features/enable-file-links-in-compare-view.tsx, source/features/fork-source-link-same-view.tsx, source/features/index.tsx, source/features/link-to-github-io.tsx, source/features/no-duplicate-list-update-time.tsx, source/features/no-unnecessary-split-diff-view.tsx, source/features/show-associated-branch-prs-on-fork.tsx, source/features/show-open-prs-of-forks.tsx, source/features/useful-not-found-page.tsx, source/features/view-last-pr-deployment.tsx, source/features/wait-for-build.tsx, source/github-helpers/index.ts, test/helpers.ts
Adds the `required` variable from https://github.com/sindresorhus/refined-github/issues/4008#issuecomment-812843149 as the `always` variable. Also move negative `exclude`s to their own list of `always` tests.
> https://github.com/sindresorhus/refined-github/blob/936eedbb0bb37a30fc44a2cc7e5f3af31f24a3fc/source/features/fork-source-link-same-view.tsx#L24-L32
> 
> Could be
> 
> ```js
> 	required: [ // name TBD
>		pageDetect.isForkedRepo
>	],
>	include: [
>		pageDetect.isSingleFile,
>		pageDetect.isRepoTree,
>		pageDetect.isEditingFile
>	],
>	exclude: [
>		pageDetect.isRepoRoot
>	],
>```
>
> Side note: https://github.com/sindresorhus/refined-github/pull/4797/files#r711719028
---
I will be changing all the instances of negative exclusions to their own list of `always` tests, until then, the PR …
=> Meta: Add an `asLongAs` option to `features.add()`

source/features/select-notifications.tsx
Fixes #4752 
https://github.com/notifications?query=repo%3Asindresorhus%2Frefined-github
https://user-images.githubusercontent.com/46634000/133923470-46a61400-7abe-4a28-bd68-915dbb8c063d.mp4
GitHub fires some events when "Done" is clicked (notably two `socket:message` events from `.js-updatable` elements) but they're not correlated to the removal of the dropdown: sometimes it happens before, sometimes after.\
So in the end I went with a simple `selector-observer`.
=> Fix: `select-notifications` disappears after clicking "Done"

source/features/show-whitespace.css, source/refined-github.css
- Fixes #4832 
- Fixes https://github.com/sindresorhus/refined-github/issues/4806
- In files, follow the user’s setting
- In comments, stick to 4 characters because GitHub is ignoring the setting
- Preserves support in `show-whitespace`
- https://github.com/sindresorhus/refined-github/blob/a52decfe2d0b5cd4617c08055bcf4a0a23812e4e/package.json
- https://github.com/sindresorhus/refined-github/pull/4833/files
GitHub ignores the user setting in comments and just sets `data-tab-size="8"` in the DOM 🤷‍♂️  so I will force it in this case.
- Review: https://github.com/sindresorhus/refined-github/pull/4833#discussion_r719986599
- Inlined code:
https://github.com/sindresorhus/refined-github/blob/a52decfe2d0b5cd4617c08055bcf4a0a23812e4e/package.json#L1-L6
- Code block
```js
{
no: "support"
}
```
- …
=> Follow the user’s tab-size setting where possible

source/features/view-markdown-source.tsx
- Closes https://github.com/sindresorhus/refined-github/issues/4834
https://github.com/sindresorhus/refined-github/blob/main/readme.md
More URLs in https://github.com/sindresorhus/refined-github/issues/4834#issuecomment-931400778
https://github.com/iamandrewluca/issue-view-markdown-source/blob/main/file.mdwn
https://github.com/iamandrewluca/issue-view-markdown-source/blob/main/file.mdx
https://github.com/iamandrewluca/issue-view-markdown-source/blob/main/file.litcoffee
https://github.com/iamandrewluca/issue-view-markdown-source/blob/main/file.rst
=> Disable `view-markdown-source` where it already exists

source/features/parse-backticks.tsx
Related #4135
We only cleaned up the selectors a little bit in [`5e40087` (#4361)](https://github.com/sindresorhus/refined-github/pull/4361/commits/5e400878bdb49d747430584017547b8b16fbf1ea) but there's plenty more to deal with. I started with removing all "commit" related selector since they should all be native now.
(Too many places 🤷‍♀️ just test and see if there are places left out)
- Commits: https://github.com/sindresorhus/refined-github/commits/main
- `isActions` run: https://github.com/sindresorhus/refined-github/actions/runs/1272877098
- `isRepoSearch`: https://github.com/sindresorhus/refined-github/search?q=latest+reliable+button+is%3Aissue&type=Issues
=> Clean up more `parse-backticks` selectors

source/features/rgh-feature-descriptions.tsx
Changes the selector to select the commit box to `.Box-header.Details`, as suggested in https://github.com/sindresorhus/refined-github/issues/4815#issuecomment-927072107.
Closes #4815 if merged.
=> Meta: Fix `rgh-feature-descriptions` feature

source/features/copy-file.tsx
The ideal solution to the new button would be to make the button faster:
-  https://github.com/sindresorhus/refined-github/issues/4802#issuecomment-932558832
but for now let's just hide our duplicate button.
https://github.com/sindresorhus/refined-github/blob/main/.gitignore
=> Avoid duplicate `copy-file` button

source/features/clean-dashboard.css, source/refined-github.css
=> Fix `clean-dashboard`’s background color

source/features/hide-low-quality-comments.css, source/options.css, source/refined-github.css
Fix #4849
NOTE: `highest-rated-comment` got a similar style fix in #4554
https://github.com/jerone/UserScripts/issues/1#issuecomment-162996100
Before: ![image](https://user-images.githubusercontent.com/44045911/135723289-1d61fb38-76e9-4476-8671-2ac1b9f03b3a.png)
After:
=> Fix `hide-low-quality-comments` style

source/features/show-names.css, source/features/show-names.tsx
Fixes #4847
https://github.com/sindresorhus/refined-github/pull/4821#discussion_r716093511
Before
After
=> Fix inconsistent `show-names` color

source/features/reactions-avatars.tsx
Fixes #4845 
Fixes #4591 
* [Discussion](https://github.com/sindresorhus/refined-github/pull/4819)
* [Releases](https://github.com/sindresorhus/refined-github/releases)
https://user-images.githubusercontent.com/46634000/135746945-b6f80b95-4616-4359-bcc3-b99cf9963590.mp4
@fregante feel free to close this if it's not the right solution. I just don't get why `onReplacedElement` was used in the first place, when the tracked element ins't even used in the callback :shrug:
=> Improve reliability of `reactions-avatar`

source/features/show-whitespace.tsx
Fix #4843
Also runs `show-whitespace` on code blocks now:
```
A
Block
Without
Highlight
```
```html
<A Block>
With Highlight
</A>
```
https://github.com/sindresorhus/refined-github/commit/e8ec186217ffc42f351983b22187ee14efb9251b#diff-6a8348ff857b16e455a52ddd651b49f31cd05895459c37301051a0e30bcf077c
Before:
After:
=> Run `show-whitespace` on code blocks but not diff headers

source/features/clean-repo-sidebar.css
Fixes #4642 
Steps to reproduce the bug:
1. Go to repo home & reload the page
2. Navigate to the PR tab
3. Open a PR
https://user-images.githubusercontent.com/46634000/135836816-0343d42c-110d-4289-91a1-cdb8faf1b265.mp4
=> Fix: Margin missing sometimes in the PR sidebar

source/features/show-names.tsx
Fix bug introduced by #4851 
Also fixes the feature on the dashboard
* [Conversation](https://github.com/refined-github/refined-github/pull/4851)
* [Dashboard](https://github.com)
_Conversation (before)_
_Conversation (after)_
_Dashboard_
https://user-images.githubusercontent.com/46634000/136196560-6db174a4-07b8-4d4d-94f3-d1a29c4b1ba3.mp4
=> Fix missing spaces in `show-names`

source/features/sort-conversations-by-update-time.tsx
Resolve #4957
This is a small addition to the existing `sort-conversations-by-update-time` feature.
In spite of https://github.com/refined-github/refined-github/issues/2960#issuecomment-619437895, I think this change is beneficial:
- Unlike what I stated in #4891 (which asks to drop a similar feature), this change is valid, refined and would indeed help those who do use Projects
- It is only a few lines of code, built upon an existing feature. One question though, it doesn't fit the feature name closely 🤷
https://github.com/worldbank/gld/projects
N/A
=> Sort projects by update time

source/features/wait-for-build.tsx
Properly remove `beforeunload` event listener with `deinit`.
Also remove the unnecessary message.
Background: https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event
From my tests, only assigning a string to `event.returnValue` works on Chrome, plus both Chrome and Firefox won't show the string you provided.
Here maybe?
N/A
=> Remove `beforeunload` event listener in `wait-for-build`

source/features/clean-repo-sidebar.css, source/features/sticky-sidebar.tsx
Fixes #5008 
* this page (PR conversation sidebar)
* [issue page](https://togithub.com/refined-github/refined-github/issues/4941)
* [repo root](https://github.com/refined-github/refined-github)
=> Fix `sticky-sidebar` on repo root

source/features/quick-pr-diff-options.tsx
Part of https://github.com/refined-github/refined-github/issues/5009
This PR only avoids the duplication and slightly improves consistency, but @kidonng’s suggestions in the original issue are valid and should be followed or discussed further.
- https://github.com/refined-github/refined-github/pull/5022/files?w=0 // whitespace
- https://github.com/refined-github/refined-github/pull/5022/files?w=1 // no whitespace
Unchanged:
- https://github.com/refined-github/refined-github/commit/db1e5682e925cdc7bf3b6e091befe51a3c703b7e?w=0
- https://github.com/refined-github/refined-github/commit/db1e5682e925cdc7bf3b6e091befe51a3c703b7e?w=1
Whitespace shown (the style has been reversed to match the "on" style of the "whitespace hidden" one)
Whitespace hidden
=> Avoid duplicating native button in `quick-pr-diff-options`

source/features/github-bugs.css
Fixes #5032 
* https://github.com/refined-github/refined-github/commit/fb7726a2335204d1cd33721b32b6e7b284c7397b
**Before**
**After**
=> Limit width of comment form on commit pages

source/features/quick-pr-diff-options.tsx
Tackle https://github.com/refined-github/refined-github/issues/5009#issuecomment-955777413
- [`isSingleCommit`](https://github.com/refined-github/refined-github/commit/49fd6261e21d69bd62094bf0b38783a7e06020d1)
- [`isCompare`](https://github.com/refined-github/refined-github/compare/main...add-multiple-prs-dropdown)
Before:
After:
=> Hide duplicate `quick-pr-diff-options` buttons on commit and compare pages

source/features/deprioritize-marketplace-link.tsx
Makes the Marketplace link in the dropdown accessible via the up and down arrows on the keyboard.
https://user-images.githubusercontent.com/73734376/140486207-de4a5790-86ab-492d-9ba6-0d14f2e4834a.mp4
=> Make "Marketplace" menu item focusable via keyboard

.xo-config.json, build/readme.loader.cts, source/features/index.tsx, source/features/rgh-feature-descriptions.tsx, source/features/rgh-linkify-features.tsx, source/globals.d.ts, source/helpers/bisect.tsx, source/options-storage.ts, source/options.tsx, webpack.config.ts
- Closes https://github.com/refined-github/refined-github/issues/4320
- Readme.md becomes part of the webpack dependency tree, which means it's watched just like other files 
- No magic/global variables that need special handling (e.g. "Don't repeat the magic variable, it will be inlined multiple times")
- More portable codebase, the loader can be more easily ported to esbuild [or something](https://github.com/refined-github/refined-github/pull/5014)
- It makes it more clear that the data is coming from the readme - https://github.com/refined-github/refined-github/pull/3678
- A lil hacky because it doesn't use the correct webpack APIs
=> Meta: drop magic globals in favor of `import`ing the readme

source/features/tag-changes-link.tsx
Fixes #5037 
* [Release list](https://github.com/refined-github/refined-github/releases)
* [Regular release](https://github.com/refined-github/refined-github/releases/tag/21.11.1)
* [Tag without release](https://github.com/torvalds/linux/releases/tag/v5.15)
<table>
<tr>
<th>Before
<th>After
<tr>
<td>
<td>
</table>
<table>
<tr>
<th>Before
<th>After
<tr>
<td>
<td>
</table>
=> Fix `tag-changes-link` for tags without release

source/features/quick-review-buttons.tsx
Fixes #5010 
* https://togithub.com/refined-github/sandbox/pull/4/files
<table>
<tr>
<th colspan="2" align="center">Open PR
<tr>
<td>Before
<td>After
<tr>
<td>
<td>
<tr>
<th colspan="2" align="center">Own open PR
<tr>
<td>Before
<td>After
<tr>
<td>
<td>
</table>
=> Fix order of actions in `quick-review-buttons`

source/features/user-local-time.css, source/features/user-local-time.tsx
Fixes #4527 
To check the cropping issue isn't back:
* https://togithub.com/refined-github/refined-github/issues/4285
* https://togithub.com/hexalellogram/iPhoneBatteryClient
https://user-images.githubusercontent.com/46634000/141319805-305ded44-20a2-4f85-b0bd-ae33d2679661.mp4
=> Fix: `user-local-time` breaks positioning of some hovercards

build/readme-parser.ts, build/verify-features.ts, readme.md
Mentioned in https://github.com/refined-github/refined-github/pull/4699#issuecomment-962593291.
It ensures that all features are described only once in [`readme.md`](readme.md).
=> Meta: Ensure features are described only once in the readme

source/github-helpers/prevent-link-loss.ts, test/prevent-link-loss.ts
Fix #4228 
Copy these links in the comment textarea below:
* `https://github.com/refined-github/shorten-repo-url/pull/33/commits/3d8d1cc8d784c7d92788a8a21e2c30cf87be3658`
* `https://github.com/sindresorhus/got/compare/v11.5.2...v11.6.0#diff-6be2971b2bb8dbf48d15ff680dd898b0R191`
* `https://github.com/eslint/eslint/discussions/15305#discussioncomment-1634740`
https://user-images.githubusercontent.com/46634000/141814685-9d37d8af-ad43-40e2-94f7-62d33a45c1db.mp4
=> Preserve name of other repos in `prevent-pr-commit-link-loss`

source/features/conversation-activity-filter.tsx
Fixes #4997 
https://togithub.com/refined-github/refined-github/issues/4997
https://user-images.githubusercontent.com/46634000/141775695-a611f3e4-bbf7-493a-b805-56f787db7fdd.mp4
=> Fix: `conversation-activity-filter` doesn't reset its state when navigating

source/github-helpers/pr-ci-status.ts
`wait-for-build` is broken:
```
❌ wait-for-build 0.0.0 → TypeError: select_dom__WEBPACK_IMPORTED_MODULE_0__.default.last(...) is undefined
getLastCommitReference moz-extension://c2ad1c81-15a9-47dc-844b-f4235a6885c1/build/refined-github.js:16955
addEventListener moz-extension://c2ad1c81-15a9-47dc-844b-f4235a6885c1/build/refined-github.js:16989
init moz-extension://c2ad1c81-15a9-47dc-844b-f4235a6885c1/build/refined-github.js:15816
runFeature moz-extension://c2ad1c81-15a9-47dc-844b-f4235a6885c1/build/refined-github.js:8021
setupPageLoad moz-extension://c2ad1c81-15a9-47dc-844b-f4235a6885c1/build/refined-github.js:8039
add moz-extension://c2ad1c81-15a9-47dc-844b-f4235a6885c1/build/refined-github.js:8094
add moz-extension://c2ad1c81-15a9-47dc-844b-f4235a6885c1/build/refined-github.js:8095
tsx …
```
=> Fix selector in `wait-for-build`

source/features/bugs-tab.tsx
Fixes #5068
https://github.com/zdharma-continuum/zinit
=> Fix `bugs-tab` where the emoji contains a dash

source/features/useful-not-found-page.tsx
The `commit` variable may be undefined, resulting in:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'oid')
at getLatestCommitToFile (refined-github.js:15213)
at async showAlternateLink (refined-github.js:15265)
```
https://github.com/refined-github/refined-github/blob/d77b5ef46be8e935cf032184da94152e1dc660fa/source/features/rgh-linkify-features.ts
N/A
=> Skip `useful-not-found-page` on pages that never exist

source/features/one-key-formatting.tsx, source/github-events/on-field-keydown.tsx
Enable `one-key-formatting` on:
- Commit title with `onCommitTitleFieldKeydown` (new event listener)
- Commit description with `onCommentFieldKeydown` (we just enable it on `isEditingFile` pages)
- Merge commit description with `onCommentFieldKeydown` (new selector)
- https://github.com/refined-github/refined-github/edit/main/.gitignore
- Here
https://user-images.githubusercontent.com/44045911/142914589-3c76b599-8c52-457b-bcdb-5e18be0fa7f6.mov
=> Enable `one-key-formatting` on more places

source/features/conversation-filters.tsx
Fixes #4589 
```js
// https://github.com/refined-github/refined-github/issues?q=is%3Aopen+mentions%3A%40me
```
=> Fix `conversation-filters` showing multiple checked marks

source/features/bypass-checks.tsx
Fix #3938 
* "Details" link should by bypassed
* https://togithub.com/Kocal/semantic-release-preset/pull/7 (Travis checks)
* "Details" link should NOT be bypassed
* https://togithub.com/sindresorhus/eslint-plugin-unicorn/pull/1088#commits-pushed-d34fa26 (commit `f800f82`, "codecov/project")
* https://togithub.com/mergeability/mergeable/pull/519 ("Mergeable")
* https://togithub.com/InsightSoftwareConsortium/ITK/pull/2881 ("ghostflow-check-master")
=> Fix broken "Details" links in PR checks due to `bypass-checks`

source/github-events/on-fragment-load.ts
Fixes bug introduced by #5094 
* `show-whitespace`: https://github.com/refined-github/refined-github/pull/5109/files
* `highlight-deleted-and-added-files-in-diffs`: [kidonng/xuann.wang@`576490d6a60a52601fbc33f31d5d9afcc3840bde...34b0d598eae7633d64f1ecbeb927254e74737905`#diff-05ed1c7f99](https://github.com/kidonng/xuann.wang/compare/576490d6a60a52601fbc33f31d5d9afcc3840bde...34b0d598eae7633d64f1ecbeb927254e74737905#diff-05ed1c7f99e45b485708115502a1e0f28c8547e9a9a29c1b8664f79103cf7873)
n/a
=> Meta: Avoid unnecessary calls in diff load listeners

source/features/unfinished-comments.tsx
Fixes #4737 
* [New issue template](https://github.com/refined-github/refined-github/issues/new?assignees=&labels=bug&template=1_bug_report.yml)
* This page (for regular comments)
Demo showing correct behavior when submitting a comment then quickly changing tab:
https://user-images.githubusercontent.com/46634000/143896128-8b9899b9-d442-4faf-a2f8-62bb47068c55.mp4
=> Fix `unfinished-comments` on new issue templates

source/features/quick-pr-diff-options.tsx
https://github.com/refined-github/refined-github/compare/add-multiple-prs-dropdown
=> Fix `quick-pr-diff-options` on compare pages

source/features/ci-link.css, source/refined-github.css
Resolves #4767 
* [Repo home](https://github.com/refined-github/refined-github)
* [User pinned repos](https://github.com/fregante)
* [User repo list](https://github.com/fregante?tab=repositories)
* [Organization pinned repos & repo list](https://github.com/refined-github?type=source)
<table>
<tr>
<td>
<td>Before
<td>After
<tr>
<td>Repo title
<td>
<td>
<tr>
<td>Pinned repos
<td>
<td>
</table>
=> Hide badges in repo headers and pinned repo cards

source/features/use-first-commit-message-for-new-prs.tsx
Fixes #5108 
https://github.com/refined-github/refined-github/compare/add-multiple-prs-dropdown?expand=1
<table>
<tr>
<td>
**Before**
<td>
**After**
<tr>
<td>
<td>
</table>
=> Fix `use-first-commit-message-for-new-prs`

source/features/quick-label-removal.tsx, source/github-helpers/toast.tsx
Fixes #4828 
Revoke your API token and try to remove a label on this page.
https://user-images.githubusercontent.com/46634000/144035109-e9dc3fc6-d729-48b7-bae6-621cf4630cbb.mp4
=> Show error toast when `quick-label-removal` fails

source/features/clean-footer.css, source/features/infinite-scroll.tsx
As mentioned in #5126, `infinite-scroll` effectively makes footer inaccessible, not only affecting that PR but also making us lose access to lots of useful links.
<details>
(Similiar to Twitter sidebar:)
</details
=> Move footer to right side when enabling `infinite-scroll`

source/features/clean-conversation-sidebar.css, source/features/clean-conversation-sidebar.tsx, source/features/clean-repo-sidebar.css, source/features/clean-repo-sidebar.tsx
Back story time. I remember seeing #5098 a while ago, and just now I was at https://github.com/fish-shell/fish-shell/ and noticed that link is still there.
I literally updated the browser extension moments ago (I use the store version when not developing it), what could go wrong? Then I noticed #5133 and after taking a closer look, I notice that fish-shell's link is `CODE_OF_CONDUCT.md` (underscore-separated) instead of `code-of-conduct.md` (dash-separated).
Then I fired up the dev env and updated the selectors, nothing happened. I went to check the original testing link (got) and nothing happened either.
Taking a _closer_ look again I noticed [the wrong feature are changed in #5133](https://github.com/refined-github/refined-github/pull/5133#discussion_r761085007). So that's it.
- …
=> Fix Code of conduct link hiding in `clean-repo-sidebar`

source/features/release-download-count.tsx
Fixes #5147 
* [Release list](https://github.com/AudioBand/AudioBand/releases)
* [Single release](https://github.com/AudioBand/AudioBand/releases/tag/v1.0.3)
* [Release list (with several artifact per release)](https://github.com/fish-shell/fish-shell/releases)
=> Fix `release-download-count` feature

source/features/hide-inactive-deployments.tsx
At some point GitHub updated their url for deployment events, making the `hide-inactive-deployment` feature no longer work. This updates the selector with the new path. Here is a copy of the new deployment html:
```html
<div class="js-socket-channel js-updatable-content" data-channel="nope" data-url="/btkostner/btkostner.io/pull/11/partials/deployed_event/5714613804" data-gid="PR_kwDOAdZchc4vYKrY">
<div id="event-5714613804" data-view-component="true" class="TimelineItem js-targetable-element">
<div data-view-component="true" class="TimelineItem-badge"><svg aria-hidden="true" height="16" viewBox="0 0 16 16" version="1.1" width="16" data-view-component="true" class="octicon octicon-rocket">
<path fill-rule="evenodd"
d="M14.064 0a8.75 8.75 0 00-6.187 …
```
=> Restore `hide-inactive-deployments`

source/features/github-bugs.css, source/refined-github.css
* [PR file](https://togithub.com/refined-github/refined-github/pull/5151/files)
* [Commit file](https://togithub.com/refined-github/refined-github/commit/fd89b5a69999aa08ba9add6240c33ac5624e6ac8)
**Before**
**After**
=> Hide trailing separator in PR and commit files dropdown

source/features/quick-mention.tsx
See screenshots for the issue
Also, as you can see from the screenshot, there is a `z-index` issue happening. However it should not happen again with this patch, but nevertheless I will leave the fix here for completeness:
https://github.com/refined-github/refined-github/blob/2d701217614009c3d8e4e0f20fd0c967b4419a7f/source/features/quick-mention.tsx#L48
Add a `style={{zIndex: 2}}` would be fine
- Multiple reviews: https://togithub.com/refined-github/refined-github/pull/5105#pullrequestreview-813257530
- Review + comment: https://togithub.com/NixOS/nixpkgs/pull/147010#pullrequestreview-817111882
Before:
After:
=> Disable `quick-mention` on reviews without a comment

source/features/previous-next-commit-buttons.tsx
Fixes #4503 
* [Condensed commit](https://togithub.com/refined-github/refined-github/pull/4448/commits/0b8966c918eae11da9fc992368741757088edf08)
* [Regular commit](https://togithub.com/refined-github/refined-github/pull/5113/commits/5b7282afc40b013f5928271fb6740cf70b4e4295)
**Before**
**After**
=> Fix `previous-next-commit-buttons` on condensed commit views

source/features/unfinished-comments.tsx
I feel that the text isn't visible enough. The only concern is OSes where emojis aren't available. 🤷‍♂️ 😬 
This PR, type a comment
=> Use emoji in `unfinished-comments`

source/options.tsx
- Fixes https://github.com/refined-github/refined-github/issues/4823
Every time I want to change the options in Safari, I have to manually clear the cache due to this issue. So why not do it automatically?
=> Fix option saving in Safari

source/features/comment-on-draft-pr-indicator.tsx
Fix #5191 
1. Go to https://togithub.com/refined-github/sandbox/pull/7
2. Click on the "Open issue" link in the sidebar
3. Go back
4. The text in the comment button should not be duplicated
https://user-images.githubusercontent.com/46634000/145685950-4ab3e8d2-b7d8-469d-a742-af8b2058cf8b.mp4
=> Fix duplication in `comment-on-draft-pr-indicator`

.github/release.yml
Untested 
Docs: https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuration-options
Mentioned in
- https://github.com/refined-github/refined-github/issues/4008#issuecomment-942723376
=> Meta: Automatically label commits in releases

source/features/reactions-avatars.tsx
Fixes #5190 
* [Release list](https://github.com/refined-github/refined-github/releases)
* [Single release](https://github.com/refined-github/refined-github/releases/tag/21.11.23)
* [Issue with reactions](https://togithub.com/refined-github/refined-github/issues/2673)
**Before**
**After**
=> Fix `reactions-avatars` on releases and review comments

source/features/user-profile-follower-badge.tsx
Fixes #5186 
The profile of someones that follows you ( ͡° ͜ʖ ͡°)
=> Fix `user-profile-follower-badge` feature

source/features/clean-repo-sidebar.tsx, source/features/repo-age.tsx
- Closes https://github.com/refined-github/refined-github/issues/5179
https://github.com/fregante/webext-tools
https://github.com/rust-lang/rust
<table>
<tr>
<th>Native
<th>Before
<th>After
<tr  valign=top>
<td>
<td><img width="322" alt="Screen Shot 2" src="https://user-images.githubusercontent.com/1402241/145778658-c15cf17a-c37f-4b7f-ab42-f81eda8fb27e.png">
<td><img width="322" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/145778646-40a05cc6-d296-40ad-887d-59c7060ce909.png">
</table>
=> Update `repo-age` and `clean-repo-sidebar` spacing

source/features/hide-watch-and-fork-count.css, source/features/hide-watch-and-fork-count.tsx, source/refined-github.ts
- Fixes https://github.com/refined-github/refined-github/issues/5161
I had hotfixed this in https://github.com/refined-github/refined-github/commit/88c3effcdf64cea8bf5dbdbf3084dce75af9cfb5
The old logic no longer applies, the links are now accessible in the sidebar: https://github.com/refined-github/refined-github/issues/5179
I'd argue we don't even need to keep this disableable since it's so simple and there's no loss of information (it appears in the sidebar), but maybe that's harder to sell since it's been possible to disable it already. Thoughts? Should we make it a CSS-only feature?
- This page
- https://github.com/refined-github/shorten-repo-url
=> Restore `hide-watch-and-fork-count`

source/features/reactions-avatars.css
- Fixes https://github.com/refined-github/refined-github/issues/5204
This is happening because they added a CSS rule that targets `span`s in that button, which we're using.
https://togithub.com/xojs/xo/issues/261
=> Fix `reactions-avatars` size

source/features/clean-rich-text-editor.tsx
Fixes #5185 
https://gist.github.com/junegunn/8b572b8d4b5eddd8b85e5f4d40f17236#new_comment_field
=> Enable `clean-rich-text-editor` on Gist pages

contributing.md, source/features/batch-mark-files-as-viewed.tsx, source/features/copy-on-y.tsx, source/features/highlight-deleted-and-added-files-in-diffs.tsx, source/features/index.tsx, source/features/quick-review-comment-deletion.tsx, source/features/releases-tab.tsx, source/features/select-notifications.tsx, source/features/sticky-sidebar.tsx, source/features/wait-for-build.tsx
Implements the second checkbox from https://github.com/refined-github/refined-github/issues/4008#issuecomment-812885528.
* `batch-mark-files-as-viewed`: this PR's files
* `copy-on-y`: e.g. https://github.com/refined-github/refined-github/blob/081adcdabbd22d5d59721a1aceffed81fb322c5f/source/features/index.tsx
* `highlight-deleted-and-added-files-in-diffs`: https://github.com/sindresorhus/refined-github/pull/3062/files
* `quick-review-comment-deletion`: this PR's discussion thread or this PR's files
* `releases-tab`: basically all repo pages
* `select-notifications`: https://github.com/notifications
* `sticky-sidebar`: this PR or this repo's homepage
* `wait-for-build`: this PR
=> Meta: Replace `deinit` option with `init` return value

source/features/github-bugs.css
Fixes #5188 
* [Commit title field](https://togithub.com/refined-github/refined-github/edit/main/readme.md)
* [Open PR merge title field](https://togithub.com/refined-github/sandbox/pull/4)
=> Restore monospace font in commit and merge title fields

source/features/clean-dashboard.css
- Fixes https://github.com/refined-github/refined-github/issues/5182
=> Properly hide new starring dropdown in `clean-dashboard`

source/features/bugs-tab.tsx
Fixes https://github.com/refined-github/refined-github/issues/5181
https://github.com/refined-github/refined-github but without a token stored
Not yet tested
=> Meta: Correctly display "token missing" errors in `bugs-tab`

source/features/quick-repo-deletion.tsx, source/features/useful-forks.tsx
Fixes #5225 
https://github.com/refined-github/refined-github/network
`useful-forks`
`quick-repo-deletion`
=> Fix `useful-forks` and `quick-repo-deletion` selectors

source/features/list-prs-for-branch.tsx, source/github-helpers/index.ts, test/get-current-committish.ts
Fixes #4492
Fixes #4196
* [Branch commits list](https://togithub.com/refined-github/sandbox/commits/branch/with/slashes)
* [Renamed file history](https://togithub.com/refined-github/sandbox/commits/branch/with/slashes/renamed.md)
`follow-file-renames`
`list-prs-for-branch`
=> Fix handling of slashed branches in some commits list features

source/features/conversation-activity-filter.tsx
Fixes #5000 
https://togithub.com/refined-github/sandbox/pull/10
https://user-images.githubusercontent.com/46634000/146204750-afac9ede-956c-438f-b4db-fbb2cba43944.mp4
=> Fix `conversation-activity-filter` hiding unresolved comments

source/features/forked-to.tsx
> As the title says
| When  | Screenshot |
| ---  | --- |
| Before | ![no `forked-to` button](https://user-images.githubusercontent.com/34235681/145825515-0a9df8ce-d0d4-4a58-b7b6-691138d7904d.png) |
| After (only one fork) | ![only one fork](https://user-images.githubusercontent.com/34235681/145825633-79eec672-b2ee-4c54-9267-685b9570a8f0.png) |
| After (two or more forks) | ![two or more forks](https://user-images.githubusercontent.com/34235681/145825755-c70dd001-7fae-4cc6-8f82-4f1d896d20cc.png) |
I couldn't live without that feature for barely even a week XD
=> Restore `forked-to` feature

source/features/hide-tips.css
* [PR list](https://github.com/refined-github/refined-github/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc)
* [Gobal conversations list](https://github.com/issues?q=is%3Aopen+author%3A%40me+archived%3Afalse+sort%3Aupdated-desc)
**Before**
**After**
=> Fix `hide-tips` CSS feature

source/features/github-bugs.css
- Fix https://github.com/refined-github/refined-github/issues/4405
https://github.com/sindresorhus/refined-github/pulls?q=Drop+support+for+the+old+GitHub+layout+sort%3Aupdated-desc
=> Fix GitHub bug: PR lists wrap multiple times sometimes

source/features/index.tsx
Fixes #5173 
[Example of a created link](https://github.com/refined-github/refined-github/issues/new?labels=bug&template=1_bug_report.yml&title=%60forked-to%60%3A+forkCounter+is+undefined&example_url=https%3A%2F%2Fgithub.com%2Frefined-github%2Frefined-github%2Fpulls%3Fq%3Dis%253Apr%2Bis%253Aopen%2Bsort%253Aupdated-desc&description=%60%60%60%0AupdateUI%40moz-extension%3A%2F%2Fc2ad1c81-15a9-47dc-844b-f4235a6885c1%2Fbuild%2Frefined-github.js%3A6743%3A5%0Aasync*init%40moz-extension%3A%2F%2Fc2ad1c81-15a9-47dc-844b-f4235a6885c1%2Fbuild%2Frefined-github.js%3A6780%3A11%0Aasync*runFeature%40moz-extension%3A%2F%2Fc2ad1c81-15a9-47dc-844b-f4235a6885c1%2Fbuild%2Frefined-github.js%3A7973%3A17%0AsetupPageLoad%40moz-extension%3A%2F%2Fc2ad1c81-15a9-47dc-844b-f4235a6885c1%2Fbuild%2Frefined-github.js%3A7991% …
=> Meta: Fix indentation of stack trace in issue links

source/features/clean-conversation-sidebar.tsx, source/features/quick-review.tsx
I may be wrong with this, but additional listeners should probably not call the init function directly.
Instead, they should use the `runFeature` wrapper that is passed to them, so that any potential errors are correctly caught and logged.
=> Meta: Don't call init function directly in additional listeners

source/features/hide-diff-signs.tsx
* [Edit file](https://togithub.com/refined-github/refined-github/edit/main/source/features/index.tsx)
* [Edit PR file](https://togithub.com/refined-github/refined-github/edit/enable-hide-diff-on-edit/source/features/hide-diff-signs.tsx?pr=%2Frefined-github%2Frefined-github%2Fpull%2F5229)
**Before**
**After**
=> Enable `hide-diff-signs` on file edition pages

source/features/quick-comment-edit.tsx
Closes #5235 if merged.
GitHub uses the `.lock-toggle-link` class on the `create issue from discussion` button (which is visible to everyone). `quick-comment-edit` use the same class to check if the user can lock the thread. This results in edit buttons appearing on all comments in all discussions.
If a lock button is actually shown, then there is a `.octicon-lock` SVG inside the div with the `.lock-toggle-link` class. This PR modifies the selector to reflect this.
- https://github.com/PatrickF1/fzf.fish/discussions/190 (not editable) [no comment, not collaborator]
- https://github.com/dabbu-knowledge-platform/cli/discussions/4 (all are editable) [one comment, is collaborator]
- https://github.com/Sunbird-RC/community/discussions/178 (only my comment is editable) [one comment, not …
=> Fix: `quick-comment-edit` should only shown on editable discussion comments

.github/workflows/test.yml, .gitignore, safari/Config.xcconfig, safari/Refined GitHub.xcodeproj/project.pbxproj
- Fixes #5202 
- Partially undoes https://github.com/refined-github/refined-github/commit/a79f49bdb7e571bd8402f3cddba8154220bd0e0c
You should now be able to create the file `safari/LocalOverrides.xcconfig` with the content:
```xcconfig
CODE_SIGN_IDENTITY = "Apple Development";
DEVELOPMENT_TEAM = YG56YK5RN5
```
Untested except on CI, does it work for you?
=> Meta: Allow setting local dev team

.github/ISSUE_TEMPLATE/1_bug_report.yml
I always miss these 2 fields both when looking at an issue and when opening one. I feel that they're fundamental enough to be shown at the top.
Any other suggestions?
=> Meta: Move small bug report fields higher

.github/workflows/release.yml
Follow-up to #5223, this time with the correct step name (see https://github.com/refined-github/refined-github/pull/5223#issuecomment-1000299508).
~This is still untested.~ Tested now: https://github.com/refined-github/refined-github/pull/5243#issuecomment-1003366051
=> Meta: Automatically generate release notes again /2

readme.md, source/features/hide-repo-badges.css, source/features/hide-repo-badges.tsx, source/refined-github.css, source/refined-github.ts
Fixes #5268 
* https://togithub.com/refined-github/refined-github
* https://togithub.com/fregante
**Feature screenshot**
=> Change `hide-repo-badges` into a feature that can be disabled

source/refined-github.css
Fixes #5276 
https://github.com/orgs/refined-github/dashboard
**Before**
**After**
=> Hide "New repository" button on organization dashboard

build/readme-parser.ts, readme.md, source/options.tsx
Both a bug fix and an enhancement.
- Bug fix: the readme parser doesn't include `jpg` in the screenshot regex, resulting in many screenshots being unavailable in the options window.
- Enhancement: [`.mp4` and `.mov` videos are now supported](https://github.blog/2021-05-13-video-uploads-available-github/) in the options window. In fact, `select-notifications` already uses a video as the screenshot.
```
$ rg --only-matching --replace '$1' 'user-images.+\.(\w+)\)$' readme.md | sort -u
gif
jpg
mp4
png
```
chrome://extensions/?options=balgliakcbamepammkbcjdepogihccmj
=> Allow using videos as screenshots

source/features/dim-bots.css
I managed to restored dimming while avoid ["adding a whole other block to add this intermediary state"](https://github.com/refined-github/refined-github/pull/5198#issuecomment-993381037):
https://user-images.githubusercontent.com/44045911/148685609-08232449-f5d8-4ad2-baff-031de031adfd.mov
Also changed restore delay to 10s which should keep the best of both worlds: practical but long enough.
https://github.com/renovatebot/renovate/commits/main
(Note the delay is intentionally shorter in the video for demo purpose)
https://user-images.githubusercontent.com/44045911/148685609-08232449-f5d8-4ad2-baff-031de031adfd.mov
=> `dim-bots` when not hovering

source/features/github-bugs.css, source/features/reactions-avatars.tsx
Fix #5275
- Review threads: https://togithub.com/refined-github/refined-github/pull/5113#discussion_r758597247
- Releases: https://github.com/refined-github/refined-github/releases/tag/21.12.21
- Discussions: https://github.com/sindresorhus/meta/discussions/15#discussioncomment-1934341
<table>
<tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/44045911/148698975-12e06e22-d8e7-4455-b0c3-57b01915bef3.png">
<td><img src="https://user-images.githubusercontent.com/44045911/148698996-366a71f4-045e-445b-9a3b-1ec0c34c34f4.png">
</table>
=> Fix `reactions-avatars` in reviews, releases and discussions

readme.md, source/features/same-branch-author-commits.tsx, source/refined-github.ts
All author names link to `/owner/repo/commits?author=<author>`, that is, the branch is not considered at all. Seems like a GitHub bug, but very easy to fix.
~~The feature can exclude `getRepo()!.path === 'commits'` but there's no need.~~ Now more useful with PJAX!
Note that despite the name is inspired by `same-page-definition-jump`, it can not use `delegate` because the links are actually different.
https://github.com/refined-github/refined-github/commits/hotfix
=> Add `same-branch-author-commits` feature

source/features/comments-time-machine-links.tsx, source/github-helpers/get-default-branch.ts, source/github-helpers/index.ts
This PR actually comes in 3 parts:
1. `getDefaultBranch()` seems to always fallback to using API as the following code fails due to DOM not ready
https://github.com/refined-github/refined-github/blob/a665157c410da81e9fdd83dcad945cd7085fafa4/source/github-helpers/get-default-branch.ts#L25-L30
This PR fixes it with `elementReady()`.
2. The above method may return a truncated branch name.
This PR uses a better method. Fix #5240.
3. `getDefaultBranch()` and `getCurrentCommittish()` doesn't work on commit list without a branch, namely `/repo/user/commits` page.
This PR fixes it by restoring and using `getCurrentBranchFromFeed()` (renamed), which parses the current branch from the feed link. Reasons to do so:
- I'm aware of #5211, but this is safe since we only do it on commit lists which …
=> Fix branch handling on commit list without a branch

source/github-helpers/get-default-branch.ts
It seems that the branch selector's `title` will only include the full branch name **only** when the displayed branch name is truncated. Otherwise, it becomes "Switch branches or tags". This causes the default branch getter to return a wrong result most of the time.
When making #5246 I may have forgotten to clear extension cache on https://github.com/refined-github/refined-github, so somehow I didn't notice this.
This PR also addresses https://github.com/refined-github/refined-github/pull/5246#discussion_r781721667.
1. Clear extension cache
2. Go to https://github.com/refined-github/refined-github
3. Click "<number> commits"
4. The `default-branch-button` should not be there
<table>
<tr>
<tr>
<td><img …
=> Fix default branch getter

source/features/clean-footer.css
Resolves #5292 
Also fixes the hiding of the "GitHub inc." text.
n/a
**Before**
**After**
=> Don't hide custom enterprise footer in `clean-footer.css`

source/features/extend-conversation-status-filters.tsx
Fixes #4870 
* https://github.com/pulls?q=is%3Aopen+is%3Apr+author%3A%40me+archived%3Afalse+sort%3Aupdated-desc
* https://github.com/refined-github/refined-github/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc
Click on the "Merged" filter, then go back and forward in history. The extra filter should not be duplicated.
https://user-images.githubusercontent.com/46634000/149303068-ed6b1b76-363b-4c99-ab9a-e0c110db0132.mp4
=> Fix duplicated "Merged" filter in global conversation list

readme.md, source/features/prevent-pr-merge-panel-opening.tsx, source/refined-github.ts
Resolves #4101 
https://github.com/refined-github/sandbox/pull/4
Open the merge box and reload the page (or click on a tab and come back) to see the behavior.
https://user-images.githubusercontent.com/46634000/149317428-338673be-c42a-4895-993e-728a38716c86.mp4
=> Add `prevent-pr-merge-panel-opening` feature

source/features/forked-to.tsx, source/features/quick-repo-deletion.tsx
I usually try not to correlate features together, but this is a convenient and harmless improvement we can do.
1. Fork https://github.com/octocat/Spoon-Knife
2. Visit your fork
3. Delete the fork using `quick-repo-deletion`
4. Return to https://github.com/octocat/Spoon-Knife, `forked-to` should not be present
N/A
=> Clear `forked-to` cache after `quick-repo-deletion`

readme.md, source/features/same-branch-author-commits.tsx
Somehow I didn't write `deduplicate` in #5289 and `same-branch-author-commits` doesn't work if you go to "Commits" page from repo tree.
I also just noticed this feature also keeps the current _file path_ for us, which is a huge deal.
https://github.com/refined-github/refined-github/commits/main/.github
N/A
=> Deduplicate `same-branch-author-commits`

readme.md, source/features/dim-visited-conversations.css, source/features/dim-visited-conversations.tsx, source/refined-github.css, source/refined-github.ts
Proposed to fix #5299
Make #5258 a standalone **CSS** feature, ~~and disable it on repos the user has write access to~~.
https://github.com/refined-github/refined-github/issues ~~or any repo you can edit~~
N/A
=> Make `dim-visited-conversations` a CSS feature

source/features/clean-conversations.css, source/refined-github.css
Cherry-picked from [`84c9dc1` (#5113)](https://github.com/refined-github/refined-github/pull/5113/commits/84c9dc1f747c144ddf22accfce531e7a00c7fafb)
Mentioned in #1066
- Conversations: Here
- Discussions: https://github.com/vercel/vercel/discussions/3874
- Commits: https://github.com/refined-github/refined-github/commit/82fb3d62f11838ad4120f510bd90520c57bb12da
<table>
<tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/44045911/149635782-951694c8-2da8-4733-90e1-22d3a3b29a87.png">
<td><img src="https://user-images.githubusercontent.com/44045911/149635788-2c8380cd-128d-46f2-9cdf-37907a25579e.png">
</table>
=> Extend `clean-conversations` to new comment forms

source/features/clean-footer.css
- Fixes https://github.com/refined-github/refined-github/issues/5292
- Any GitHub page
- Any GitHub Enterprise page with a custom footer
=> Improve `clean-footer` support for custom Enterprise footers

source/features/hide-tips.css
This PR:
- restores hiding protips at the bottom of conversation pages (removed in #5196)
- hides protip at the bottom of "Saved" and "Done" notifications list
- this page
- https://github.com/notifications/beta?query=is%3Adone
<table>
<tr>
<th>Before
<th>After
<tr>
<td>
<td>
<tr>
<td>
<td>
</table>
=> Lint and extend `hide-tips.css`

source/features/list-prs-for-file.tsx
You are suggested to review each individual commit.
- "Improvement: use more specific path selector": the `clipboard-copy` selector is too generic
- "Fix: don't add PJAX buttons on `isEditingFile`": or else you may get duplicate editors:
- "Improvement: only append Text Fragment on `isEditingFile` and Chrome": only Chrome supports it now, and it doesn't work with PJAX which resets hash. Also solve https://github.com/refined-github/refined-github/pull/4739#discussion_r700517498
- Refactor commits: separate different logic on `isSingleFile` and `isEditingFile`
- "Fix: add back `.BtnGroup-item` class": this is initially broken by #4619 then some PRs from me 😅
- "Improvement: add hovercards": see #5052
https://github.com/refined-github/refined-github/edit/lint/source/features/index.tsx
For …
=> Refactor `list-prs-for-file`

source/features/infinite-scroll.css, source/features/infinite-scroll.tsx
This PR:
- cleans up the footer in the sidebar (the notice & subscription link are still available in the original footer at the bottom of the page)
- makes the footer sticks at the top when the feed is scrolled
<table>
<tr>
<th>Before</th>
<th>After</th>
</tr>
<tr>
<td align="top">
</td>
<td valign="top">
</td>
</tr>
</table>
=> Clean up and stick sidebar footer in `infinite-scroll`

source/features/clean-conversation-sidebar.tsx, source/features/index.tsx, source/features/quick-review.tsx, source/github-events/on-discussion-sidebar-update.ts
Fix https://github.com/refined-github/refined-github/pull/5238#issuecomment-1018551405
The problem is `clean-conversation-sidebar` doesn't get updated along with `quick-review`, resulting in looping `while` in `onReplacedElement`.
From here, visit any PJAXed page
N/A
=> Fix page getting stuck when leaving PR conversation

source/features/align-issue-labels.tsx, source/features/clean-pinned-issues.tsx, source/features/clean-rich-text-editor.tsx, source/features/dim-visited-conversations.tsx, source/features/hide-diff-signs.tsx, source/features/hide-repo-badges.tsx, source/features/index.tsx, source/features/minimize-upload-bar.tsx
To reproduce the bug:
1. Go to https://github.com/refined-github/refined-github/issues and reload the page
2. Click on a conversation
3. The text editor at the bottom isn't cleaned
https://user-images.githubusercontent.com/46634000/150654034-492a0f79-658f-4d3d-9f45-67196e238a72.mp4
=> Disable deduplication mechanism for all CSS features

source/features/first-published-tag-for-merged-pr.tsx, source/features/tags-on-commits-list.tsx
Adopt to GitHub's commit ref style, as seen on PRs headers.
- `tags-on-commits-list`: https://github.com/refined-github/refined-github/commits/22.1.18
- `first-published-tag-for-merged-pr`: https://togithub.com/refined-github/refined-github/pull/5305
<table>
<tr>
<td align="center"><strong>Feature</strong>
<tr>
<td><code>tags-on-commits-list</code>
<td><img src="https://user-images.githubusercontent.com/44045911/150526862-46e027ef-dd23-4649-8deb-c03334de50e5.png">
<td><img src="https://user-images.githubusercontent.com/44045911/150526885-94bf19ab-638a-43f7-92a7-6e2007d6bd88.png">
<tr>
<td><code>first-published-tag-for-merged-pr</code>
<td><img src="https://user-images.githubusercontent.com/44045911/1505284 …
=> Improve `tags-on-commits-list` and `first-published-tag-for-merged-pr` style

source/features/ci-link.css, source/features/ci-link.tsx, source/github-events/on-fragment-load.ts
This and #5246 both reduce requests when opening a new repo.
Fixes #5283 
- `isRepoHome`: https://github.com/refined-github/refined-github
- `isRepoCommitList`
- https://github.com/refined-github/refined-github/commits/main
- https://github.com/refined-github/refined-github/commits (after #5246 gets merged)
- Fallback: https://github.com/refined-github/refined-github/issues
- Discussions: https://github.com/cli/cli/discussions (reload the page to see the bug)
=> Fix `ci-link` on Discussions and get from page if present

source/features/patch-diff-links.tsx
PJAX should never enable on these links, yet it does on PR commits page.
https://github.com//refined-github/refined-github/pull/5238/commits/ebf3f1da71aea11782b8586501ec92fbb002316d
N/A
=> Prevent `patch-diff-links` from being AJAXed

source/features/clean-conversation-sidebar.css
Previously the style is leaking and affects `isCommit`.
https://github.com/refined-github/refined-github/commit/79ef6d8f680ab39c17bb6ec4458b2228769e5fe8#comments
<table>
<tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/44045911/151678437-ea676d66-68b5-4270-9739-3406081f05d2.png">
<td><img src="https://user-images.githubusercontent.com/44045911/151678429-8b13a423-72ef-44c9-8983-76c85c06b619.png">
</table>
=> Fix `clean-conversation-sidebar` leaking style

source/features/linkify-branch-references.tsx
Adopt to GitHub's commit ref style, like #5327
The muted color is not suitable for indicating clickable references.
https://github.com/refined-github/refined-github/pulls
<table>
<tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/44045911/151670687-ff28bed5-2038-4653-b5ae-4101c1229759.png">
<td><img src="https://user-images.githubusercontent.com/44045911/151670689-4aa39b79-eae9-452a-bf16-67cdb2f9fceb.png">
</table>
=> Improve `linkify-branch-references` style

source/features/improve-shortcut-help.tsx
Here
<table>
<tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/44045911/151674641-3419ffee-6ad5-4f58-ad6c-618adfe3bc3c.png">
<td><img src="https://user-images.githubusercontent.com/44045911/151674646-872c78da-d853-4f6d-8511-7656694926f9.png">
</table>
=> Fix `improve-shortcut-help`

source/features/fork-source-link-same-view.tsx, source/features/forked-to.tsx
Most pages of forks and parents are interchangeable, except for issues and PRs.
Enforcing too many limits is unnecessary and `useful-not-found-page` would help if something does go wrong.
- `forked-to`: https://github.com/refined-github/refined-github/tags
- `fork-source-link-same-view`: https://github.com/kidonng/refined-github/tags
=> Extend `forked-to` and `fork-source-link-same-view` to entire repo

source/features/download-folder-button.tsx
Fixes https://github.com/refined-github/refined-github/issues/5335
https://github.com/dotnet/runtime/tree/09ff1acdad2e7789908b5db9bb89896144c13042/src/libraries/Microsoft.VisualBasic.Core
=> Fix missing `download-folder-button` on commit tree pages

build/readme-parser.ts, readme.md, source/options.tsx
Neither of the 2 videos work on Safari, we can't deal with codec issues. I used Gifski.app to convert one video and recreated the rest of the screenshots.
Reverts refined-github/refined-github#5271
=> Revert "Allow using videos as screenshots"

readme.md, source/features/easy-toggle-commit-messages.tsx, source/features/easy-toggle-files.tsx, source/refined-github.ts
Resolves #5341 
- [Repo commit list](https://github.com/torvalds/linux/commits/master)
- [PR commit list](https://togithub.com/refined-github/refined-github/pull/5324/commits)
- [Compare page](https://github.com/torvalds/linux/compare/v5.17-rc1...master)
=> Add `easy-toggle-commit-messages` feature

source/features/git-checkout-pr.tsx, source/globals.d.ts
When `git-checkout-pr` adds two code blocks, the dropdown becomes ugly long. This PR adopts to a style inspired by the native clone dropdown:
This does not affect how it displays when only one code block is added.
https://github.com//fish-shell/fish-shell/pull/8712
<table>
<tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/44045911/153457535-a036b38f-e4da-46f6-b340-0b3fa72420f9.png">
<td><img src="https://user-images.githubusercontent.com/44045911/153457555-025bf791-4bbe-42d8-9ed0-b8d66a62ef00.png">
=> Improve `git-checkout-pr` style

source/features/collapsible-content-button.tsx, source/features/table-input.css, source/features/table-input.tsx
Fixes #5392 
Any page with a comment form
<table>
<tr>
<th>
Before
<th>
After
<tr>
<td>
<td>
<tr>
<td></td>
<td>
On mobile:
</table>
=> Fix styles of `table-input` and `collapsible-content-button`

source/refined-github.css
https://github.com/refined-github/refined-github/issues/5398#issuecomment-1036112206
Any page of a repo pinned to your profile
**Before**
**After**
=> Hide "Unpin" button in repo header

source/features/latest-tag-button.tsx
Bug introduced in [`e7f0d3e` (#3199)](https://github.com/refined-github/refined-github/pull/3199/commits/e7f0d3e099edc355aa0f38497cc4ea24e719365f#diff-865e9997a2004e222760004e23714c43b27194f59ec8aae2483c934935ed66b4R110), it only checks if the default branch is not ahead of the latest tag, but doesn't check if you are actually on the default branch.
Also changed the text from "release" to "tag". "Release" is a GitHub term and what we are really working with is Git tags.
https://github.com/refined-github/refined-github/tree/22.1.18
<table>
<tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/44045911/152232563-919b9a5b-e830-4f53-8cab-963a43108934.png">
<td><img src="https://user-images.githubusercontent.com/44045911/1522325 …
=> Only disable `latest-tag-button` when actually on the latest tag

source/features/tags-dropdown.css, source/features/tags-dropdown.tsx
Follow-up of https://github.com/refined-github/refined-github/pull/5399#discussion_r804887489
- [Releases](https://github.com/refined-github/refined-github/releases)
- [Tags](https://github.com/refined-github/refined-github/tags)
**Before (~550px wide)**
**After**
_Desktop_
_Mobile_
https://user-images.githubusercontent.com/46634000/153719068-abc6e8ce-77ef-42df-a88e-683c7dbbe902.mp4
=> Fix `tags-dropdown` layout

source/features/clean-repo-sidebar.css, source/features/clean-repo-sidebar.tsx
Fixes https://github.com/refined-github/refined-github/issues/5410
https://github.com/panva/jose
<table>
<tr>
<th>Before
<th>After
<tr>
<td>
<td>
</table>
=> Fix `clean-repo-sidebar` hiding some readme links

source/github-helpers/dom-formatters.ts
Part of #5052
https://github.com//refined-github/refined-github/blob/80e42b31dc33338d3ae12092d67fa8bc6f6d5161/source/features/github-bugs.css#L6
<table>
<tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/44045911/154219720-849bb6f9-333d-4d79-8696-f33c553a2954.png">
<td><img src="https://user-images.githubusercontent.com/44045911/154219733-d9645655-e4a5-42eb-b737-977e5a4e4ee8.png">
=> Enable native hovercards when linkifying issues

source/features/use-first-commit-message-for-new-prs.tsx
Fixes #5382 
Also restores using the commit description as the PR body.
- https://togithub.com/refined-github/sandbox/compare/first-commit-msg?expand=1
- https://togithub.com/BNFC/bnfc/compare/master...176-source-position?expand=1
- https://togithub.com/refined-github/refined-github/compare/add-multiple-prs-dropdown?expand=1
With the following commits:
**Before**
**After**
=> Fix linkified `use-first-commit-message-for-new-prs`

source/features/align-repository-header.css
Because it doesn't need to work there.
<table>
<tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/44045911/153726296-f213ce38-9d4e-42c7-9e7b-b48a16873fe8.png">
<td><img src="https://user-images.githubusercontent.com/44045911/153726299-2e3371d7-4be3-4cd3-9392-57f0dbf863f1.png">
=> Disable `align-repository-header` on small screens

source/features/conversation-activity-filter.tsx
Closes #5379
Add new shortcuts  into the `conversation-activity-filter` feature:
- One `h` press: hide events
- Two `h` presses: hide everything
- Three `h`  presses: show everything
- Repeat
https://github.com/refined-github/refined-github/pull/4029
Keyboard shortcuts
=> Add keyboard shortcuts for `conversation-activity-filter`

source/features/comments-time-machine-links.tsx, source/github-events/on-new-comments.ts
`comments-time-machine-links` broke on issue/PR bodies (the first comment of the conversation):
```text
❌ comments-time-machine-links 22.2.13 → TypeError: menu.closest(...) is null
init moz-extension://6ffeab5e-837d-450e-9fa5-fe3ec6a7ee9f/build/refined-github.js:6345
runFeature moz-extension://6ffeab5e-837d-450e-9fa5-fe3ec6a7ee9f/build/refined-github.js:3045
```
This PR also fixes the feature for minimized comments inside review threads.
https://togithub.com/refined-github/refined-github/pull/5422
It should work on:
- first comment (PR body)
- regular comments
- "main" review comments
- review thread comments
- review comments in minimized thread
- minimized review thread comments
Conversation body (i.e. first comment):
Minimized comment in review thread:
=> Fix `comments-time-machine-links` on first conversation comment

source/features/unwrap-unnecessary-dropdowns.tsx
```text
❌ unwrap-unnecessary-dropdowns 0.0.0 → Error: GitHub added items to the dropdown. This feature is obsolete.
unwrapActionRun moz-extension://c2ad1c81-15a9-47dc-844b-f4235a6885c1/build/refined-github.js:15227
```
https://github.com/refined-github/refined-github/actions/runs/1857951266
=> Drop `unwrap-unnecessary-dropdowns` on action run page

source/features/github-bugs.css
https://togithub.com/refined-github/refined-github/commit/2b532270a189169835017493b9b6ff2c44d566b3
<table>
<tr>
<th>Before
<td>
<tr>
<th>After
<td>
</table>
=> Fix spacing of diff icon in commit diff stats

.github/release.yml
*(This is a follow-up of PR #5175 )*  .
Currently the categories order in Releases is: `Bugfixes` → `New` → `Changes` .
My suggested minor change in release.yml is to make it: `New` → `Changes` → `Bugfixes` .
I believe `New` entries should be listed first, followed by `Changes` and `Bugfixes` to be in the end.
https://github.com/refined-github/refined-github/releases/tag/22.2.22
<details>
<summary>Before:</summary>
</details>
<details>
<summary>After:</summary>
</details>
=> Meta: Rearrange category order in releases

source/features/highest-rated-comment.css, source/features/highest-rated-comment.tsx, source/features/preview-hidden-comments.css, source/features/preview-hidden-comments.tsx
- Align `highest-rated-comment` style with GitHub
- Redesign `highest-rated-comment` jump to comment button (like hidden comments)
`preview-hidden-comments` is also changed slightly to align with it
- Always add `highest-rated-comment` link unless the fist timeline item is the best comment
Previous logic is to check if the first **3** timeline items contain the best comment.
However chances are the first 3 timeline items could be _many_ events like references, label and assignment changes, etc. (e.g. https://github.com//ytdl-org/youtube-dl/issues/30568, previously the link to highest-rated comment isn't created).
<table>
<tr>
<td><strong>Test URL</strong>
<tr>
<td><a href="https://github.com//vercel/swr/issues/93"><code>highest-rated-c …
=> Improve `highest-rated-comment`

source/features/clean-conversation-sidebar.tsx
Closes #5447.
Note that `canEditSidebar` for RGH maintainers is exactly reversed compared to me, so the screenshots may not look exactly the same for you.
<table>
<tr>
<th>Linked?
<th><code>canEditSidebar</code>?<br>(for @FloEdelmann)
<th>URL
<th>Before
<th>After
<tr>
<td>:x:
<td>:x: 
<td>Issue <a href="https://togithub.com/refined-github/refined-github/issues/4194">#4194</a>
<td>Section completely hidden
<td>Section completely hidden
<tr>
<td>:x:
<td>:x: 
<td>PR <a href="https://togithub.com/refined-github/refined-github/pull/5416">#5416</a>
<td>Section completely hidden
<td>Section completely hidden
<tr>
<td>:x:
<td>:heavy_check_mark:
<td>Issue <a href="https://togithub.com/streetcomplete/StreetComplete/issues/1892">StreetComplete#1892</a>
<td><img …
=> Support "Create a branch" link in `clean-conversation-sidebar`

.xo-config.json
This PR:
- sorts the local rules list by plugin
- disable `no-warning-comments`
- sets `unicorn/expiring-todo-comments` to produce a warning on todo comments with no condition
Output of `npx xo` before:
```
source/options-storage.ts:55:1
⚠   55:1   Unexpected todo comment: TODO [2022-05-01]: Remove obsolete color....  no-warning-comments
source/github-helpers/index.ts:78:3
⚠   78:3   Unexpected todo comment: TODO: Can TypeScript take care of this?....   no-warning-comments
source/github-helpers/pr-ci-status.ts:11:47
⚠   11:47  Unexpected todo comment: TODO [2022-05-01]: GHE.                       no-warning-comments
source/features/ci-link.tsx:12:71
⚠   12:71  Unexpected todo comment: TODO[2022-04-29]: GHE #4294.                  no-warning-comments …
```
=> Meta: Fix warnings for todo comments

source/features/github-bugs.css
Seems like GitHub fixed the issue of the missing spacing between reactions, so now our fix is adding superfluous space.
- [Issue body](https://togithub.com/refined-github/refined-github/issues/5459)
- [PR body](https://togithub.com/refined-github/refined-github/pull/5457)
- [Review thread comment](https://togithub.com/refined-github/refined-github/pull/5458#discussion_r819645385)
- [Release](https://github.com/refined-github/refined-github/releases/tag/22.1.18)
**Before**
**After**
=> Drop reactions spacing fix

source/features/latest-tag-button.tsx
Fixes #5446 
- [Latest tag](https://github.com/refined-github/refined-github/tree/22.3.3)
- [Default branch, tagged](https://github.com/kas-elvirov/gloc)
- [Default branch, not tagged](https://github.com/refined-github/github-url-detection)
- [Other branches](https://github.com/refined-github/refined-github/tree/hotfix)
**Before**
**After**
=> Fix `latest-tag-button` at repo home on tagged default branch

source/features/clean-conversation-sidebar.css
- [Issue conversation](https://togithub.com/refined-github/sandbox/issues/3)
- [PR conversation](https://togithub.com/refined-github/sandbox/pull/4)
**Before**
**After**
=> Fix top alignment of PR sidebar in `clean-conversation-sidebar`

source/refined-github.css
- For https://github.com/refined-github/refined-github/issues/5222#issuecomment-1064769358
The code makes it smaller without breaking the autosizer
=> Meta: Make our bug report "Example URLs" field smaller

source/features/use-first-commit-message-for-new-prs.tsx
- Closes https://github.com/refined-github/refined-github/issues/5477
https://github.com/refined-github/refined-github/compare/main...add-multiple-prs-dropdown?expand=1&pull_request%5Bbody%5D=bar&pull_request%5Btitle%5D=foo
=> Don't override the PR title and body provided via URL parameters

source/features/github-bugs.css
- Closes https://github.com/refined-github/refined-github/issues/5152
https://github.com/pixiebrix/pixiebrix-extension/runs/5523238774?check_suite_focus=true
=> Fix GitHub Safari bug: Horizontal scrollbars on Action logs

source/features/shorten-links.tsx
Fixes #4758 
Follow-up of #4759 
- [Highlighted and non-highlighted code blocks in comment](https://togithub.com//denosaurs/mod.land/issues/55)
- [Code block in readme](https://togithub.com/oakserver/oak#application-middleware-and-context)
- [Review suggestion](https://togithub.com/refined-github/refined-github/pull/4759#discussion_r738167140)
**Before**
**After**
=> Don't apply `shorten-links` to links in code blocks

source/features/first-published-tag-for-merged-pr.tsx, source/features/tags-on-commits-list.tsx
First attempt: #5327
I made a mistake last time: the style is referenced from branch names, but tags are not actually branch names. This makes the blue background of branch names (in contrast to the usual gray of `<code>` blocks) less distinctive. The color also makes it appear more prominent than necessary, especially for `tags-on-commits-list`.
So this time I went to take a look at how [release pages](https://github.com/refined-github/refined-github/releases/tag/22.2.13) show the tag, which also shows meta info just like the feature does.
<table>
<tr>
<td align="center"><strong>Test URL</strong>
<tr>
<td><a href="https://github.com/refined-github/refined-github/commits/22.1.18"><code>tags-on-commits-list …
=> Restyle two tag-related features

source/features/index.tsx
- Closes https://github.com/refined-github/refined-github/issues/5174
https://github.com/MatthewL246/hello-world/edit/main/CONTRIBUTING.md
(error was reported in https://github.com/refined-github/refined-github/issues/4194)
=> Fix error reporting in Safari

source/features/bugs-tab.tsx, source/features/releases-tab.tsx
- Fixes https://github.com/refined-github/refined-github/issues/4254
- Replaces and closes https://github.com/refined-github/refined-github/pull/5333
1. Resize the window to have it just barely hide the Releases tab2. 
2. Empty the cache (makes the `bugs-tab` appear later)3. 
3. Refresh the page
Shows that triggering a fake `resize` event makes the tab disappear
https://user-images.githubusercontent.com/1402241/158060307-b299c3ce-9bba-4150-b242-5fe6517d054b.mov
=> Fix repo tab menu overflow due to `releases-tab` and `bugs-tab`

source/features/scrollable-code-and-blockquote.css
- Fixes https://github.com/refined-github/refined-github/issues/4597
Our code was just being overridden by GitHub’s
- https://github.com/refined-github/refined-github/pull/5416#issuecomment-1041546190
- https://github.com/discordjs/discord.js/pull/6162#issuecomment-884157859
- https://github.com/refined-github/refined-github/pull/5506#issuecomment-1067652695
=> Avoid extra scrollbars in `scrollable-code-and-blockquote`

source/features/latest-tag-button.tsx
Fixes #5504 
Follow-up of #5462
- [Latest tag](https://github.com/refined-github/refined-github/tree/22.3.3)
- [Default branch, tagged](https://github.com/kas-elvirov/gloc)
- [Default branch, not tagged](https://github.com/refined-github/github-url-detection)
- [Default branch, not tagged (20+ commits ahead)](https://github.com/refined-github/refined-github)
- [Other branches](https://github.com/refined-github/refined-github/tree/hotfix)
=> Fix `latest-tag-button` on branch ahead by more than 20 commits

source/features/useful-not-found-page.tsx
- Closes https://github.com/refined-github/refined-github/issues/5483
https://github.com/orgs/date-fns/teams/i18n-id
=> Include but skip inert URL segments in `useful-not-found-page`

source/features/dim-bots.tsx
Dim more bots PRs + refactor a bit and add an explanatory comment on each extra selector
- [PRs by `renovate` and `dependabot`](https://github.com/mozilla/dispensary/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed)
- [PRs by `dependabot` and `snyk-bot`](https://github.com/cheap-glitch/fretboarder/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed)
- [Commits by `renovate`](https://github.com/renovatebot/renovate/commits/main)
- [Commits by `bors`](https://github.com/rust-lang/rust/commits/master)
**Before**
**After**
=> Dim more PRs opened by bots in `dim-bots`

source/features/fork-source-link-same-view.tsx
- Fixes https://github.com/refined-github/refined-github/issues/5479
- Follows #5351 
1. Visit https://github.com/humphd/browser-extension-template/tree/update-deps/.github
2. Link must point to https://github.com/fregante/browser-extension-template/tree/main/.github
3. Click "Code" tab
4. Link must be reset to https://github.com/fregante/browser-extension-template
5. Click "Pull requests" tab
6. Link must include URL parameters https://github.com/humphd/browser-extension-template/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc
7. Go back in history to verify everything is still correct
=> Reliability fixes for `fork-source-link-same-view`

source/features/align-issue-labels.css
- fixes https://github.com/refined-github/refined-github/issues/5532
They dropped the `labels` class.
Heads up: `dim-bots` is also affected but it's not as high priority
https://github.com/refined-github/refined-github/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc
https://github.com/orden-gg/fireball/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
=> Restore `align-issue-labels`

readme.md, source/features/dim-visited-conversations.css, source/features/dim-visited-conversations.tsx, source/refined-github.ts
On repos you visit often, this just leads to links having lower contrast.
- See https://github.com/refined-github/refined-github/pull/1206#issuecomment-386051034
Being 3 lines of CSS, it can be added to one’s own CSS field
=> Drop `dim-visited-conversations` feature

source/features/clean-dashboard.css
- Closes https://github.com/refined-github/refined-github/issues/5530
I'm updating the style a bit:
- keep the card styles, but move them to each event group rather than around each repo. I think we had this at some point but maybe it wasn't working
- add some shadows to match the upcoming "For you" style
=> Restore `clean-dashboard` style

source/features/stop-pjax-loading-with-esc.tsx
Fixes #5561 :man_facepalming: :man_facepalming: 
1. Click on a repo tab
2. Quick! Press <kbd>Esc</kbd>!
3. Voilà
https://user-images.githubusercontent.com/46634000/161933513-449c86eb-9ef6-4233-912a-a5181d8e7f3b.mp4
=> Fix: `stop-pjax-loading-with-esc` stopped working

source/features/hide-low-quality-comments.tsx, source/features/highest-rated-comment.tsx
Resolves #5567 
- Control URL: https://togithub.com/vercel/swr/issues/93
- No comment should be highlighted here: https://togithub.com/facebook/jest/issues/5311
**Before**
**After**
=> Exclude low quality comments from `highest-rated-comment`

source/features/hide-repo-badges.css
Any repo page
**Before**
**After**
=> Fix `hide-repo-badges` feature

readme.md, source/features/quick-comment-edit.tsx
Fixes #5558 
Fixes #5572 
Add, edit and delete regular & review comments in conversations
- [Issue conversation](https://togithub.com/refined-github/sandbox/issues/3)
- [PR conversation](https://togithub.com/refined-github/sandbox/pull/10)
=> Fix position and duplication of `quick-comment-edit` button

source/features/follow-file-renames.tsx
Fixes #5576 
- [Renamed file on main branch](https://github.com/MicrosoftDocs/azure-docs/commits/main/articles/app-service/tutorial-connect-msi-sql-database.md)
- [Renamed file on branch with slashes](https://togithub.com/refined-github/sandbox/commits/branch/with/slashes/renamed.md)
https://user-images.githubusercontent.com/46634000/162250772-726ab1ec-7653-41bc-8dd5-4bd08c2bea97.mp4
=> Fix `follow-file-renames` feature

source/features/quick-comment-edit.tsx
- [Issue conversation](https://togithub.com/refined-github/sandbox/issues/3)
- [PR conversation](https://github.com/refined-github/sandbox/pull/4)
**Before**
**After**
Note to self: it's probably better not to overcompensate for small GitHub mishaps like that.
=> Fix left padding of `quick-comment-edit` button

source/features/safer-destructive-actions.css
https://togithub.com/github/feedback/discussions/13399
**Before**
**After**
=> Fix and extend `safer-destructive-actions` on Discussions

source/features/quick-comment-edit.tsx
- A discussion where you posted some comments
- [Issue conversation](https://github.com/refined-github/sandbox/issues/3)
- [PR conversation](https://github.com/refined-github/sandbox/pull/10)
https://user-images.githubusercontent.com/46634000/163672370-8f9bab81-003a-40d6-b062-fcff911f921a.mp4
Note: the weird layout of the editor toolbar is a GitHub bug
=> Restore `quick-comment-edit` on Discussions

source/features/wait-for-checks.tsx
Fixes #1771 
A PR requiring admin privileges on a repo where you're an admin
=> Disable `wait-for-checks` when PR requires admin privileges

source/features/clean-conversation-headers.css, source/features/clean-conversation-headers.tsx
Fixes the placement of the arrow icon, relative to the base branch dropdown that appears when editing the title of an open PR.
- [Open PR you can edit](https://github.com/refined-github/sandbox/pull/4)
- [Open PR you can't edit](https://togithub.com/microsoft/TypeScript/pull/39930)
**Before**
**After**
=> Fix branch dropdown position in `clean-conversation-headers`

source/features/tag-changes-link.tsx
I think this is too generic. If the release is decent we're likely already looking at the list of changes. "Commits" makes it more specific as to what the link points to.
=> Meta: Change `tag-changes-link`’ label to "Commits"

package.json, source/features/github-bugs.css
Any repo page.
**Before**
**After**
=> Fix spacing of icons in repo header buttons

source/features/github-bugs.css
Fixes https://github.com/refined-github/refined-github/issues/5398
Replaces #5622
https://github.com/fregante/webext-dynamic-content-scripts
---
Unfortunately the parent’s flexbox is still pretty bad at sharing the space, but it's unlikely that we can do much about it: Once flexbox has to wrap something, it will drop space **from both**: 1/4 from the title and 3/4 from the actions. This can cause both sides to wrap internally even even the sum of the available space is available from at least one more piece from either side:
=> Fix GitHub bug: Avoid excessive repo title wrap

source/features/bugs-tab.tsx
This PR adds the `type/bug` and `kind/bug` labels to the list of supported labels for the `bugs-tab` feature. The `kind/bug` label format is currently used by Prisma in all of their repositories.
https://github.com/prisma/prisma
=> Add `type/bug` and `kind/bug` to list of supported labels in `bugs-tab`

source/features/expand-all-hidden-comments.tsx
Fixes #4921 
1. Go to https://togithub.com/lensapp/lens/pull/3910 and scroll down to the "131 hidden items / Load more" button.
2. Alt-click it. Every comment in the main thread should load.
3. Scroll down until you see a review thread with a "44 hidden comments" button.
4. Alt-click it. Every review comment in the thread should load.
https://user-images.githubusercontent.com/46634000/168293483-7931ccdb-f632-4e9e-8882-f8b08538dc48.mp4
=> Restore `expand-all-hidden-comments` feature

source/features/suggest-commit-title-limit.css, source/features/suggest-commit-title-limit.tsx, source/refined-github.css
- Fixes https://github.com/refined-github/refined-github/issues/3998
Untested, except via dev tools in Safari. I should also test it when editing files
- This PR
- https://github.com/refined-github/refined-github/edit/fix-commit-title-limit/source/refined-github.css
=> Fix `suggest-commit-title-limit` 1-character-short width

source/features/avoid-accidental-submissions.tsx, source/features/list-prs-for-file.tsx, source/features/submission-via-ctrl-enter-everywhere.tsx
- Fixes https://github.com/refined-github/refined-github/issues/4194
The ideal, global solution continues to be https://github.com/refined-github/refined-github/issues/4008#issuecomment-822942520
- https://github.com/MatthewL246/hello-world/edit/main/CONTRIBUTING.md
This is a blank slate and this excludes it.
=> Avoid some console errors when attempting to edit files on non-own repos

source/features/highest-rated-comment.tsx
- Fixes https://github.com/refined-github/refined-github/issues/5577
- Restores unwanted change from https://github.com/refined-github/refined-github/pull/5357#discussion_r796514659
The feature seems to be broken? Can't test at all
- https://togithub.com/vercel/next.js/issues/31054
<table><caption>Both screenshots include a fix that restores the feature altogether</caption>
<tr>
<th>Before
<th>After
<tr>
<td><img width="519" alt="Screen Shot 16" src="https://user-images.githubusercontent.com/1402241/169487402-dbf0b555-c46d-493a-b232-280472dc5b32.png">
<td><img width="508" alt="Screen Shot 15" src="https://user-images.githubusercontent.com/1402241/169487412-c36abe89-569f-4cce-aec0-4400da75efcb.png">
</table>
=> Don't link to first comment in `highest-rated-comment`

source/features/shorten-links.tsx, source/github-helpers/dom-formatters.ts
- Closes https://github.com/refined-github/refined-github/issues/5630
The interesting part here is that GitHub is specifically parsing **Markdown** tables differently and linkifying URLs within them. Since this does not usually happen with other tables, we've never encountered this bug. 
- https://github.com/refined-github/sandbox/pull/14
<table>
<tr>
<th> Native
<th> Before
<th> After
<tr>
<td><img width="320" alt="Screen Shot 13" src="https://user-images.githubusercontent.com/1402241/169455067-f38d0d1a-ca25-498f-8c53-2056289b0390.png">
<td>
<td><img width="337" alt="Screen Shot 11" src="https://user-images.githubusercontent.com/1402241/169454921-3befa8f3-98f6-4a34-ab65-369ff2ac1ef5.png">
</table>
=> Don't `shorten-links` in code blocks in tables in comments
