source/features/highest-rated-comment.css, source/features/highest-rated-comment.tsx
Closes #4529. (CC @fregante)
https://github.com/isaacs/github/issues/402#issuecomment-239936197
https://github.com/vercel/swr/issues/93#issuecomment-551110903
=> Update and fix `highest-rated-comment` style

source/github-helpers/search-query.ts
n/a
n/a
This is my first open source contribution. Please let me know if this is good? Thank you!
=> Meta: Fix spelling errors in comment inside `search-query.ts`

source/features/dim-bots.css
Fix #4600
https://github.com/mozilla/dispensary/pulls
Before:
After:
=> Fix `dim-bots`: Does not collapse label-less bot PRs

source/features/toggle-everything-with-alt.tsx
Resolve #4601
https://github.com/sindresorhus/refined-github/pull/4585/files
N/A
=> Support "Expand all" button in `toggle-everything-with-alt`

source/features/quick-mention.tsx
Resolve #4603
https://github.com/sindresorhus/refined-github/issues/3686#issuecomment-734784717
Before:
After:
=> Disable `quick-mention` on hidden comments

source/features/linkify-code.tsx, source/features/repo-age.tsx
Fix #3226
From #2066:
> URLs in diffs
> [Homebrew/homebrew-core#18015 (files)](https://github.com/Homebrew/homebrew-core/pull/18015/files)
> 
> URLs in regular files
> [/source/features/copy-markdown.js@`3f5fc48`#L45](https://github.com/sindresorhus/refined-github/blob/3f5fc489e417d4f4a14da5ea423775e9ca9246fd/source/features/copy-markdown.js#L45)
> 
> URLs in PR files
> [#546 (files)](https://github.com/sindresorhus/refined-github/pull/546/files#diff-36280fbf56b6409696e3d46d6b30118fR51)
> 
> URLs in embedded code
> https://github.com/sindresorhus/refined-github/blob/3f5fc489e417d4f4a14da5ea423775e9ca9246fd/source/features/copy-markdown.js#L45
> 
> Issue reference in file
> 
> [/source/features/sort-issues-by-update-time.tsx@`2ade9a8`#L18](https://github.com/sindresorhus/refined-github/blob …
=> Prevent `linkify-code` from running multiple times

.xo-config.json, source/features/conflict-marker.tsx, source/features/list-prs-for-file.tsx, source/features/mark-merge-commits-in-list.tsx, source/features/open-all-conversations.tsx, source/features/pinned-issues-update-time.tsx, source/features/reactions-avatars.tsx, source/features/tag-changelog-link.tsx, source/options.tsx
Re https://github.com/sindresorhus/refined-github/issues/4008#issuecomment-888167968
Based on the [<code>unicorn/no-array-callback-reference</code> documentation](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-array-callback-reference.md#pass) , 1st example:
```
Fail: const foo = array.map(callback);
Pass: const foo = array.map(element => callback(element));
```
N/A
N/A
=> Fix every instance of `unicorn/no-array-callback-reference`

source/features/toggle-everything-with-alt.tsx
`toggle-everything-with-alt` is not enabled on issue pages. This looks like an oversight in #2087.
#4008
🤷‍♀️
=> Enable `toggle-everything-with-alt` on all conversation pages

.prettierignore
Re https://github.com/sindresorhus/refined-github/issues/4008#issuecomment-894761663 :
> * [ ]  Add `.prettierignore` file to disable "prettier on save" feature of every editor: [prettier.io/docs/en/ignore.html](https://prettier.io/docs/en/ignore.html)
>
> The content would probably be just `*.*` but it needs to be tested
N/A
N/A
I tested it as follows:
Installed Prettier package globally (`npm install -g prettier`), and installed [Prettier - Code Formatter](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) extension.
Then I set Prettier as 'Default Formatter' and 'Format on Save' (below are the respective VSCode settings):
```
"editor.defaultFormatter": "esbenp.prettier-vscode",
"editor.formatOnSave": true
```
Then I opened various RG files (.ts, .tsx, .json) in …
=> Add `.prettierignore` file to disable "prettier on save" feature of every editor

source/features/conversation-activity-filter.tsx, source/features/first-published-tag-for-merged-pr.tsx
Fixes #4625 
* [Open issue](https://github.com/sindresorhus/refined-github/issues/4008)
* [Released PR](https://github.com/sindresorhus/refined-github/pull/4487)
Fixed horizontal spacing between comments count and eye icon:
Fixed icons color and vertical alignment of tag icon:
=> Fix some minor icon color and position issues

source/features/git-checkout-pr.tsx
Fixes #4661 
* Open PR: this page!
* [Draft PR](https://github.com/sindresorhus/refined-github/pull/4641)
* PJAX navigation : go to [the PR list](https://github.com/sindresorhus/refined-github/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc), reload the page and select an open PR → the dropdown should be augmented
**Can someone with GitHub Codespaces enabled test this too?** (The dropdown should have tabs in it)
Also should I update the readme screenshot while I'm at it?
=> Fix `git-checkout-pr` feature

source/features/clean-repo-filelist-actions.tsx
=> Fix `clean-repo-filelist-actions` feature

distribution/options.html, source/features/bugs-tab.tsx, source/features/convert-release-to-draft.tsx, source/features/index.tsx, source/features/restore-file.tsx, source/features/stop-pjax-loading-with-esc.tsx, source/features/submit-review-as-single-comment.tsx, source/features/sync-pr-commit-title.tsx, source/github-helpers/api.ts, source/github-helpers/index.ts, source/helpers/fetch-dom.ts, source/options-storage.ts, source/options.tsx
Closes #4666 
Any page
Was it `hidden` on purpose? But, having a label without a checkbox seems unfinished/broken.
=> Meta: Make `Log API calls in the console` option checkbox visible

package.json
Per #4704
Tested and works ok, it's essentially the same fix as #4386.
=> Meta: Make `npm run fix` run on Windows

source/features/profile-gists-link.tsx
Fix #4751 
https://github.com/xt0rted
Before: 
After:
=> Add missing space to `profile-gists-link`

source/features/hide-low-quality-comments.tsx, source/features/hide-noisy-newsfeed-events.css, source/features/hide-tips.css, source/features/open-all-notifications.tsx
Per https://github.com/sindresorhus/refined-github/pull/4723#issuecomment-913437029
I reviewed all changes again in the above PR, and found that, in `hide-low-quality-comments.tsx ` and `hide-noisy-newsfeed-events.css` there were inconsistencies in the classes. This PR fixes them. *Sorry about that, they missed my attention.*
Also, by the way, I also replaced the two last occurrences "useless" into "unnecessary" in comments of two previously-untouched files.
=> Meta: Make classes and feature names consistent

source/features/file-finder-buffer.tsx
=>  Match `file-finder-buffer` style with GitHub

source/helpers/bisect.tsx
Fixes #4748
None
None
@fregante if this is not the correct solution you can just close the PR.
=> Meta: Ensure the body loaded before bisecting

source/features/reactions-avatars.tsx
Fix #3978
- Discussion: https://github.com/tophf/mpiv/discussions/50
- Release: https://github.com/sindresorhus/refined-github/releases/tag/21.9.3
=> Enable `reactions-avatars` on more pages

source/features/restore-file.tsx, source/github-helpers/api.ts
Closes #4781 
https://github.com/gamemaker1/test/pull/1/files
=> Use safer saving mechanism in `restore-file`

source/features/conversation-activity-filter.tsx
Resolve #4063
Here
Before:
Now:
=> Meta: Improve `conversation-activity-filter` labels

source/features/show-whitespace.css, source/github-helpers/api.ts
This is used in `quick-repo-deletion`
[Link to your fork]
Before:
After:
=> Meta: Improve lack of token scopes message

source/features/quick-mention.tsx
Fixes #4844 
https://github.com/pixiebrix/pixiebrix-extension/pull/1548
https://user-images.githubusercontent.com/46634000/135748608-81ecd14e-681e-48c8-9b98-9ad89bed14e7.mp4
=> Fix `quick-mention` on review events

source/features/quick-comment-hiding.tsx
Fixes #4846
Before:
https://user-images.githubusercontent.com/23432278/135725079-fac20d83-2242-42e4-b5f7-22233d225215.mov
After:
=> Don't leave menu open in `quick-comment-hiding`

source/features/no-unnecessary-split-diff-view.css
Fixes #4669 
https://github.com/fregante/sandbox/pull/30/files
_Before_
_After_
=> Fix CI annotations in `no-unnecessary-split-diff-view`

source/refined-github.css
Fix https://github.com/refined-github/refined-github/pull/4996/files#r739665567
=> Fix selector for commit title input width

source/features/clean-dashboard.css, source/features/clean-mergeability-box.css, source/features/clean-pinned-issues.css, source/features/emphasize-draft-pr-label.css, source/features/hide-low-quality-comments.css, source/features/highest-rated-comment.css, source/features/pr-approvals-count.css, source/features/quick-label-removal.css, source/features/suggest-commit-title-limit.css, source/features/table-input.css, source/options.css, source/refined-github.css
Let's merge this by 21.11.1
- Fixes #5018 
=> Use new background color variables

source/features/reactions-avatars.css, source/features/reactions-avatars.tsx
For reasons of changes see review comments below. Mainly:
- Size: `1.3em` -> `16px`
- Favor GitHub's classes over our own styles
- Follow GitHub's markup
https://togithub.com/TypeStrong/ts-node/issues/1007
Before:
After:
- https://github.com/refined-github/refined-github/pull/4696
=> Tweak `reactions-avatars` style

source/features/quick-review-buttons.tsx
- Fixes #5010 
This PR or any open PR that you _did not_ open
=> Improve usability of `quick-review-buttons`

package-lock.json, package.json, source/features/tag-changes-link.tsx, source/features/tags-dropdown.tsx
Fix #5029
Maybe wait for https://github.com/fregante/github-url-detection/pull/103
https://github.com/refined-github/refined-github/tags?after=21.8.1
N/A
=> Fix `tags-dropdown` and `tag-changes-link` after first tags page

source/features/clean-dashboard.css
Fixes #5024 
**Before**
**After**
=> Fix missing margin caused by `clean-dashboard`

source/features/clean-repo-sidebar.css, source/features/sticky-sidebar.css
Fix https://github.com/refined-github/refined-github/pull/5012#issuecomment-955677383
- Here
Before:
https://user-images.githubusercontent.com/44045911/139589751-13292554-8866-4413-aed4-1dd259bfe88a.mov
After:
https://user-images.githubusercontent.com/44045911/139589753-1fbf4b8f-0a7c-4c2c-be05-eb1f1207e41b.mov
=> Fix `clean-repo-sidebar` and `sticky-sidebar` top margin

README.md, hotfix.json
See the note in the hotfix branch's readme that I also removed.
https://www.youtube.com/watch?v=NU9JoFKlaZ0
=> Meta: Delete hotfix.json

source/features/clean-repo-tabs.tsx, source/features/scheduled-and-manual-workflow-indicators.tsx
Follow-up of https://github.com/refined-github/refined-github/pull/4998#issuecomment-958757002
https://github.com/refined-github/refined-github/actions
=> Meta: Don't store entire workflow files in cache

source/background.ts, source/features/index.tsx, source/helpers/hotfix.ts, source/options.tsx
Follow-up of https://github.com/refined-github/refined-github/pull/4961#pullrequestreview-796250499
Fixes #4861 
n/a
=> Fix implementation of hotfixes

source/features/highest-rated-comment.tsx
Fixes #5064 
https://github.com/evanw/esbuild/issues/297#issuecomment-692571427
=> Fix `highest-rated-comment` checkmark misalignment

build/readme-parser.ts, build/verify-features.ts, readme.md
Continues https://github.com/refined-github/refined-github/pull/5055
=> Meta: Improve readme parsing

package-lock.json, package.json, readme.md, tsconfig.json
Extracted from https://github.com/refined-github/refined-github/pull/5086/files
=> Meta fixes

source/features/show-whitespace.tsx
Fixes #5092 
https://github.com/github/copilot.vim/blob/03a11aded57a78975effc87770ade4059c058dc7/copilot/dist/tokenizer.json
n/a
=> Fix `show-whitespace` hanging on very long lines

source/features/global-search-filters.tsx
Revert https://github.com/refined-github/refined-github/pull/5036/files#diff-dd31bb5dede6917724258dd1ff7d12428475eded46f3b832ec2179661d4bbb57
Reason: https://github.com/refined-github/refined-github/pull/4098#discussion_r595679970
`https://github.com/search?q=user%3A<Your username here>&type=code`
=> Fix "Yours" filter in `global-search-filters`

source/features/highlight-deleted-and-added-files-in-diffs.tsx, source/github-events/on-diff-file-load.ts
Fix #5093
[`576490d6a60a52601fbc33f31d5d9afcc3840bde...34b0d598eae7633d64f1ecbeb927254e74737905`#diff-05ed1c7f99](https://github.com/kidonng/xuann.wang/compare/576490d6a60a52601fbc33f31d5d9afcc3840bde...34b0d598eae7633d64f1ecbeb927254e74737905#diff-05ed1c7f99e45b485708115502a1e0f28c8547e9a9a29c1b8664f79103cf7873)
Before:
After:
=> Fix `highlight-deleted-and-added-files-in-diffs` on compare page

source/features/rgh-feature-descriptions.tsx, source/features/rgh-linkify-features.tsx, source/github-helpers/index.ts, source/helpers/bisect.tsx, source/helpers/feature-link.ts, source/options-storage.ts, source/options.tsx
- [`isCommitList`](https://github.com/refined-github/refined-github/commits/6d5bda3b9db8b8d1514af40ff53628f198f4478d)
- [`isSingleCommit`](https://github.com/refined-github/refined-github/commit/6d5bda3b9db8b8d1514af40ff53628f198f4478d)
- [`isRepoTree`](https://github.com/refined-github/refined-github/tree/6d5bda3b9db8b8d1514af40ff53628f198f4478d) (one gotcha: it won't work for links loaded asynchronously, but we probably don't care)
Before:
After:
=> Meta: Extend `rgh-linkify-features` to more places

source/options.css, source/options.tsx
Continues #4987
Resolves #4974 
Options page
=> Disable the checkbox of hotfixed features

build/readme-parser.ts, build/readme.loader.cts, build/verify-features.ts, source/globals.d.ts, source/helpers/bisect.tsx, source/options-storage.ts, source/options.tsx
Fixes bugs introduced by #5084 
Options page
**Before**
**After**
=> Fix the feature list in the options page

source/features/conversation-activity-filter.tsx
=> Fix `conversation-activity-filter` sometimes failing

source/features/conflict-marker.tsx, source/features/open-all-conversations.tsx
Fixes #4870 
https://github.com/pulls?q=is%3Aopen+is%3Apr+author%3A%40me+archived%3Afalse+sort%3Aupdated-desc
https://user-images.githubusercontent.com/46634000/143888743-9b524d60-10c4-41ed-ba45-7b9de26a1e0a.mp4
=> Fix duplicated features on global conversation list

source/features/new-repo-disable-projects-and-wikis.tsx
Fixes #5107 
https://github.com/new
n/a
=> Fix tab deletion in `new-repo-disable-projects-and-wikis`

source/features/preview-hidden-comments.css, source/features/preview-hidden-comments.tsx
Fixes #4983 
Here
https://user-images.githubusercontent.com/46634000/143909122-ea5324f1-7fb2-4ec0-97bf-69cd9776e49b.mp4
=> Fix `preview-hidden-comments` preview text after hiding comment

source/features/quick-pr-diff-options.tsx
Fixes #5039 
* [Files tab](https://github.com/refined-github/sandbox/pull/4/files)
* [Single commit](https://github.com/refined-github/refined-github/commit/49fd6261e21d69bd62094bf0b38783a7e06020d1)
n/a
=> Fix `quick-pr-diff-options` on GHE

source/features/clean-repo-sidebar.tsx
https://github.com/sindresorhus/got
**Before**
**After**
=> Fix alignment of "Code of conduct" link in `clean-repo-sidebar`

package-lock.json, package.json, source/features/file-finder-buffer.tsx, source/features/fit-textareas.tsx, source/helpers/browser-detection.ts, source/options.tsx
- Follows https://github.com/refined-github/refined-github/pull/5166
- Replaces https://github.com/refined-github/refined-github/pull/5177
=> Meta: Standardize Safari detection

source/background.ts, source/features/rgh-linkify-welcome-issue.tsx, source/features/rgh-welcome-issue.css, source/features/rgh-welcome-issue.tsx, source/github-helpers/prevent-link-loss.ts, source/refined-github.ts
- Fixes https://github.com/refined-github/refined-github/issues/5080
https://user-images.githubusercontent.com/1402241/145529215-3f880d8e-ac13-4901-94db-e0b40ce36866.mov
https://github.com/refined-github/refined-github/issues/3543
=> Meta: Linkify welcome issue to open options page + clean it up

source/features/dim-bots.tsx
Resolves #4952 
Follow-up of #5139 
* https://togithub.com/rust-lang/rust/commits/master
* https://togithub.com/OpenLightingProject/open-fixture-library/commits/c18c0b9caf5127637c56ff518623a0fd3effb738/.github/workflows/test.yaml
=> Detect more bots in `dim-bots`

source/features/dim-bots.css, source/features/dim-bots.tsx
- Closes https://github.com/refined-github/refined-github/issues/5158
https://github.com/pixiebrix/pixiebrix-extension/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed+bump+
https://user-images.githubusercontent.com/1402241/145775347-7b773183-6efe-475b-9b83-b2753ed221fa.mov
https://user-images.githubusercontent.com/1402241/145978531-ae3d3b9f-8825-45f1-81ff-381aac8c1b70.mov
=> Delay `dim-bots` after hover

source/features/index.tsx
=> Meta: Fix silencing of console errors when logged out

source/features/sticky-sidebar.css, source/features/sticky-sidebar.tsx
Fixes #5214 
- https://github.com/refined-github/sandbox
- https://github.com/enqueue/metabase-clickhouse-driver
=> Fix "unclickable Stars dropdown" bug

.github/workflows/release.yml
For https://github.com/refined-github/refined-github/issues/4008#issuecomment-942723376
=> Meta: Automatically generate release again

source/background.ts, source/features/index.tsx, source/helpers/hotfix.ts, source/helpers/is-development-version.ts, source/options.tsx
=> Fix: The welcome page isn't opened on Safari

source/features/batch-mark-files-as-viewed.tsx, source/features/clean-conversation-headers.tsx, source/features/clean-repo-sidebar.tsx, source/features/easy-toggle-files.tsx, source/features/hide-low-quality-comments.tsx, source/features/highest-rated-comment.tsx, source/features/linkify-branch-references.tsx, source/helpers/types.d.ts, source/refined-github.ts
- For https://github.com/refined-github/refined-github/issues/4008#issuecomment-823814526
- More context in https://github.com/g-plane/typed-query-selector/issues/16#issuecomment-996766347
=> Meta: Default selectors to `HTMLElement` type

source/features/list-prs-for-file.tsx
Fixes #5233 
https://github.com/timolins/react-hot-toast/blob/main/src/core/store.ts
https://user-images.githubusercontent.com/46634000/147075143-a1472d44-1506-4a75-9f1a-14ed6e4182e2.mp4
=> Fix deduplication of `list-prs-for-file` feature

source/features/latest-tag-button.tsx, source/features/list-prs-for-file.tsx
Fixes #5232 
* https://github.com/refined-github/refined-github/blob/main/source/refined-github.ts
* https://github.com/timolins/react-hot-toast/blob/main/src/core/store.ts
=> Fix alignment of `latest-tag-button` & `list-prs-for-file` icons

source/features/conversation-activity-filter.tsx
Related to https://github.com/refined-github/refined-github/issues/5222#issuecomment-996627450
* https://togithub.com/refined-github/refined-github/issues/4008
* https://togithub.com/refined-github/refined-github/issues/5222
=> Meta: Automatically hide resolved comments on minor fixes issues

source/features/bugs-tab.tsx, source/features/extend-conversation-status-filters.tsx, source/features/global-conversation-list-filters.tsx, source/features/global-search-filters.tsx, source/features/more-conversation-filters.tsx, source/features/sort-conversations-by-update-time.tsx, source/features/split-issue-pr-search-results.tsx, source/github-helpers/search-query.ts, test/search-query.ts
Related to https://github.com/refined-github/refined-github/issues/5222#issuecomment-996884047
=> Meta: Refactor `SearchQuery`

source/features/profile-gists-link.tsx
Fixes #5184 
https://togithub.com/kidonng
https://user-images.githubusercontent.com/46634000/147740681-f809893b-e2e0-4d28-802b-7c0423f21847.mp4
=> Fix: `profile-gists-link` is not responsive

source/features/dim-bots.css, source/features/dim-bots.tsx
Fixes #5260
Go to https://github.com/renovatebot/renovate/commits/main and click on "Older" at the bottom of the page
https://user-images.githubusercontent.com/46634000/148674527-0f7e5650-b2a4-4860-a7c6-c8f29c2dbb86.mp4
=> Fix: `dim-bots` only works on the first page

.github/workflows/test.yml, package.json, webpack.config.ts
=> Meta: Run tests on Windows

source/options.tsx
Related to https://github.com/refined-github/refined-github/issues/5222#issuecomment-996942943
Options page
https://user-images.githubusercontent.com/46634000/147745733-aa9a55fa-b077-40aa-b3c5-fcff1440df76.mp4
=> Meta: Toggle all screenshots in options page with Alt

source/features/collapsible-content-button.tsx, source/features/table-input.tsx
Fixes https://github.com/refined-github/refined-github/issues/5303
https://github.com/refined-github/refined-github/issues/new?assignees=&labels=bug&template=1_bug_report.yml
https://user-images.githubusercontent.com/46634000/149537830-e8d45c32-6a5f-4173-b508-e92f8acd4475.mp4
=> Fix some editor features on issue forms text fields

.github/ISSUE_TEMPLATE/1_bug_report.yml, readme.md, source/features/index.tsx
These are routine questions we probably should ask in the template.
https://github.com/kidonng/refined-github/issues/new?assignees=&labels=bug&template=1_bug_report.yml
=> Meta: require cleared cache and extension version in bug reports

source/features/comments-time-machine-links.tsx
Fixes https://github.com/refined-github/refined-github/issues/4977
Follow-up of https://github.com/refined-github/refined-github/pull/4893
- File still exists: https://github.com/sindresorhus/refined-github/blob/main/source/features/comments-time-machine-links.tsx
- File has been deleted: https://github.com/sindresorhus/refined-github/blob/main/source/features/default-to-rich-diff.tsx
https://user-images.githubusercontent.com/46634000/150313201-e8a4601b-c6f1-41ea-9424-628bed82b25e.mp4
=> Fix `comments-time-machine-links` loading

source/helpers/is-low-quality-comment.ts, test/is-low-quality-comment.ts
Closes #5257 
https://github.com/stephencookdev/speed-measure-webpack-plugin/issues/167
|---|---|
| ![image](https://user-images.githubusercontent.com/44284655/151346259-34338869-d81d-473c-ad4c-4ff59c00ae0e.png)|![image](https://user-images.githubusercontent.com/44284655/151346901-215a7b2c-457c-4239-8058-88131c2cc73c.png)|
|![image](https://user-images.githubusercontent.com/44284655/151347606-bfda8c3e-b74e-4f29-9bc6-cc2802b738bf.png)|![image](https://user-images.githubusercontent.com/44284655/151347717-2ca2b238-41a9-4988-a288-eb4f2bcf13e5.png)|
=> Extend `hide-low-quality-comments` with more keywords

source/features/toggle-everything-with-alt.tsx, source/helpers/click-all.ts
Inspired by #5341
- `isPRConversation`: https://github.com/refined-github/refined-github/pull//5324
- `isCommitList`: https://github.com/torvalds/linux/commits/master
=> Extend `toggle-everything-with-alt` to commit messages

source/features/clean-commit-form.css, source/refined-github.ts
Basically [`clean-conversations`](https://github.com/refined-github/refined-github/blob/ecb1769a7b37acd172917860e62356acd3569469/source/features/clean-conversations.css) but for commit forms.
https://github.com/refined-github/refined-github/edit/hotfix/README.md
<table>
<tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/44045911/151679080-231fe42b-156c-488c-af6e-7281dc364b0c.png">
<td><img src="https://user-images.githubusercontent.com/44045911/151679082-cb28d6f3-fe62-4ff9-87bc-ef40c6bcbb69.png">
</table>
=> Add `clean-commit-form` feature

distribution/options.html, source/background.ts, source/options-storage.ts
Resolves #5342 
n/a
https://user-images.githubusercontent.com/46634000/151666203-5f69a08d-8942-4b38-8af4-96f17b32baf7.mp4
=> Add option to set URL of toolbar icon

source/features/latest-tag-button.tsx, source/refined-github.css
- Close #5347
https://github.com/dotnet/runtime/tree/09ff1acdad2e7789908b5db9bb89896144c13042/src/libraries/Microsoft.VisualBasic.Core
=> Align all file navigation buttons

build/readme-parser.ts, build/verify-features.ts, readme.md
Closes #5361 if merged
Adds a check to the `verify-features` script to ensure every feature has a valid screenshot.
=> Meta: Add test for feature screenshot

source/features/hide-low-quality-comments.tsx
https://github.com/refined-github/refined-github/issues/5257
https://github.com/ambarvm/ng-action-test/issues/1
=> Exclude comments with links in `hide-low-quality-comments` 

.github/ISSUE_TEMPLATE/1_bug_report.yml, source/features/index.tsx, source/features/rgh-improve-new-issue-form.tsx, source/helpers/clear-cache-handler.ts, source/options.tsx, source/refined-github.ts
Follow-up of https://github.com/refined-github/refined-github/pull/5298#pullrequestreview-853544750
https://github.com/refined-github/refined-github/issues/new?assignees=&labels=bug&template=1_bug_report.yml
https://user-images.githubusercontent.com/46634000/152186938-cb08524e-c046-4c8a-97d7-0c5fd297432d.mp4
=> Meta: Improve new issue form on RGH repo

source/features/mark-merge-commits-in-list.css, source/features/mark-merge-commits-in-list.tsx, source/features/tags-on-commits-list.tsx
- Properly deduplicate so it works across PJAX navigation
- Use actual merge icon instead of PR icon
- Extend it to PR converstaions
- https://github.com//refined-github/refined-github/pull/5304
- https://github.com//refined-github/refined-github/pull/5304/commits
<table>
<tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/44045911/153467930-73b57727-4133-4878-996c-2f6918e1212b.png">
<td><img src="https://user-images.githubusercontent.com/44045911/153467953-52426731-8809-4974-8e60-0055e0f5007c.png">
=> Improve `mark-merge-commits-in-list`

readme.md
Because we can't implement everything.
Formally speaking: I feel this has been suggested by us many times, apparently many (most?) people are still unaware of its existence. Adding it to the README so ~~you don't have to make it a [Saved reply](https://github.com/settings/replies)~~ people are less likely to waste their (and our) time.
=> Add a link to GitHub feedback in README

source/features/hide-empty-profile-status.css, source/refined-github.ts
Fixed by GitHub
https://github.com//andrewda
https://user-images.githubusercontent.com/44045911/153752609-98aa0bcf-ef8b-4bfa-b472-f5b058c4e1a6.mov
=> Drop `hide-empty-profile-status` feature

source/features/github-bugs.css
https://github.com/refined-github/refined-github/issues/5222#issuecomment-1027678780
See review comments
See review comments
=> Lint `github-bugs.css`

source/features/clean-repo-sidebar.css
Just a small refinement :)
- https://github.com/tpope/vim-surround
<table>
<tr>
<tr>
<td>
<td>
<tr>
<td><img src="https://user-images.githubusercontent.com/44045911/154983899-a8a19b76-14db-455e-8402-b9d31f3f55e5.png">
<td><img src="https://user-images.githubusercontent.com/44045911/154983888-915da2bb-48a1-4869-bfc7-a0e616fb4900.png">
</table>
=> Align data section with `clean-repo-sidebar`

source/features/rgh-welcome-issue.css, source/features/rgh-welcome-issue.tsx
Some styles is unnecessarily restricted to large screens.
https://github.com//refined-github/refined-github/issues/3543
<table>
<tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/44045911/155516538-2f6ac6aa-26c3-4810-b07d-5d5239c06683.png">
<td><img src="https://user-images.githubusercontent.com/44045911/155516541-41dc0291-9fc5-4d59-bde3-fa7b9b3e90ab.png">
=> Improve `rgh-welcome-issue` style on mobile

source/github-events/on-new-comments.ts
I noticed `onNewComments` is being wrongly triggered in the following cases:
- when adding or removing a reaction on the first comment of a discussion
- when hovering on the dropdown button of a review thread comment
- when editing or removing a regular comment
- when a new event appeared in the timeline (label added/removed, commit pushed, issue linked, etc.)
While it doesn't cause any visible bugs, it still means unnecessary calls and duplicate observers/listeners being created (every feature that acts on `hasComments` pages implicitly listens to `onNewComments`!)
This PR fixes that.
=> Fix `onNewComments` listener

readme.md, source/features/link-to-compare-diff.css, source/features/link-to-compare-diff.tsx, source/refined-github.ts
https://github.com/refined-github/refined-github/issues/5440#issuecomment-1052390587
https://github.com/refined-github/refined-github/compare/22.2.13...22.2.22
The feature should NOT run here: https://github.com/refined-github/refined-github/compare/22.2.1...22.2.22
https://user-images.githubusercontent.com/46634000/156762884-28c8d88f-2518-4400-a089-72c2709e5e05.mp4
=> Add `link-to-compare-diff` feature

source/features/deep-reblame.tsx
- Fixes https://github.com/refined-github/refined-github/issues/4439
Test URL: https://github.com/refined-github/refined-github/blame/77e11bd49548f5ff883aad34b4e3e94346c3ccf2/source/background.ts#L3
https://user-images.githubusercontent.com/1402241/158050526-7b0ee86f-09e6-41d9-aff0-fa8fcf1f2268.mov
=> Improve progress UI for `deep-reblame`

distribution/options.html, source/options.css, source/options.tsx
- Closes https://github.com/refined-github/refined-github/issues/5134
Note: This is not a meta PR because it affects a visible part of RG
=> Make Debugging section more prominent in the options

source/features/index.tsx
- Closes https://github.com/refined-github/refined-github/issues/4731#issuecomment-1066059907
- Replaces #5492 
Not yet tested
=> Ensure custom CSS is added *after* the extension CSS

source/options.tsx
- Closes https://github.com/refined-github/refined-github/issues/5442
cc @karfau
However… still 9 steps required 🙂 maybe this wasn't worth it after all
=> Exclude disabled features from "Find feature" wizard

source/background.ts
- Fixes https://github.com/refined-github/refined-github/issues/5412
=> Fix Safari first install detection

source/features/github-bugs.css
- Fixes https://github.com/refined-github/refined-github/issues/5468
=> GitHub bug: Avoid overflow caused by the diff signs

.github/ISSUE_TEMPLATE/1_bug_report.yml, source/features/rgh-improve-new-issue-form.tsx, source/features/rgh-welcome-issue.tsx, source/helpers/open-options.ts
Might help avoiding this kind of situations in the future: https://github.com/refined-github/refined-github/issues/5403
=> Meta: Warn for missing or invalid token in bug report form

.github/release.yml
- Closes https://github.com/refined-github/refined-github/issues/5516
Docs: https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuration-options
=> Meta: Fix changelog creation

source/features/comments-time-machine-links.tsx, source/features/edit-readme.tsx, source/features/fork-source-link-same-view.tsx, source/features/forked-to.tsx, source/features/reactions-avatars.tsx, source/features/sync-pr-commit-title.tsx
Due to https://github.com/refined-github/refined-github/pull/5494#discussion_r829019629
cc @kidonng
=> Reliability fixes for `fork-source-link-same-view` /2

source/features/easy-toggle-commit-messages.tsx
Extend `easy-toggle-commit-messages` to the following places:
- [Repo root](https://github.com/jpmens/jo/tree/eefaf71b4106f791b74bd21eaea2d27f9cd03ce1)
- [Repo tree](https://github.com/jpmens/jo/tree/eefaf71b4106f791b74bd21eaea2d27f9cd03ce1/tests)
- [Single file](https://github.com/jpmens/jo/blob/eefaf71b4106f791b74bd21eaea2d27f9cd03ce1/README.md)
https://user-images.githubusercontent.com/44045911/159135057-b2d284c2-1496-4911-989b-5aff590aa298.mov
=> Extend `easy-toggle-commit-messages` to more places

source/features/linkify-code.tsx, source/github-helpers/dom-formatters.ts
Fixes https://github.com/refined-github/refined-github/issues/5474
Go to https://github.com/pulls?q=is%3Apr+is%3Aopen+author%3A%40me+archived%3Afalse+sort%3Aupdated-desc and open a PR
n/a
=> Fix console error in `linkify-code`

source/features/easy-toggle-files.tsx
https://gist.github.com/kidonng/0d16c7f17045f486751fad1b602204a0/revisions
https://user-images.githubusercontent.com/44045911/159741735-e3c71016-6054-4575-963b-d15908474d3b.mov
=> Extend `easy-toggle-files` to gists

source/features/conversation-activity-filter.tsx
Fixes #5390.
https://github.com/refined-github/refined-github/issues/4008#issuecomment-996659891
=> Show explicitly linked comment in `conversation-activity-filter`

source/features/hidden-review-comments-indicator.tsx, source/features/linkify-branch-references.tsx, source/features/releases-tab.tsx, source/features/show-whitespace.tsx, source/features/update-pr-from-base-branch.tsx, source/github-events/on-conversation-header-update.ts, source/github-events/on-file-list-update.ts, source/github-events/on-new-comments.ts, source/helpers/get-deinit-handler.ts
Follow-up of https://github.com/refined-github/refined-github/pull/5422#discussion_r841821958
Fixes https://github.com/refined-github/refined-github/issues/5552 (hopefully)
=> Fix clean-up of observers used by features

source/features/file-finder-buffer.tsx
Caused by #5422 
Similar to #5570
https://user-images.githubusercontent.com/46634000/162161836-a75e92c1-8a91-4463-9028-606c88529349.mp4
=> Restore `file-finder-buffer` feature

source/features/conversation-activity-filter.css, source/features/conversation-activity-filter.tsx
Resolves https://github.com/refined-github/refined-github/issues/5581
https://github.com/refined-github/sandbox/pull/10
https://user-images.githubusercontent.com/46634000/162580597-14e735da-71a1-4874-9bab-ef884c534895.mp4
=> Improve `conversation-activity-filter` for PR conversations

source/features/select-all-notifications-shortcut.tsx
Fixes #5569 
https://user-images.githubusercontent.com/46634000/162682068-4d85ff52-89b5-47e6-ad81-641a8b7dd6df.mp4
=> Fix slowdown caused by `select-all-notifications-shortcut`

package.json, source/github-helpers/github-url.test.ts, source/github-helpers/index.test.ts, source/github-helpers/parse-backticks.test.ts, source/github-helpers/prevent-link-loss.test.ts, source/github-helpers/search-query.test.ts, source/helpers/is-low-quality-comment.test.ts, source/helpers/loose-parse-int.test.ts, source/helpers/pluralize.test.ts
https://github.com/refined-github/refined-github/issues/5222#issuecomment-1070525355
=> Meta: Move some test modules into `source` folder

source/features/conversation-activity-filter.tsx
Fixes #5390.
1. Go to https://github.com/refined-github/refined-github/issues/4008#issuecomment-996659891
2. Click the hidden comment and click the link (https://github.com/refined-github/refined-github/issues/4008#issuecomment-824729016)
=> Keep linked comments visible in `conversation-activity-filter`

source/features/conversation-activity-filter.tsx, source/features/improve-shortcut-help.tsx, source/features/keyboard-navigation.tsx, source/features/selection-in-new-tab.tsx
Also lint some hotkey listeners
=> Meta: Use `registerHotkey` everywhere applicable

source/features/scrollable-code-and-blockquote.css
Fix #5540
Copied from #5509 (which caused this bug)
- https://github.com//refined-github/refined-github/pull/5416#issuecomment-1041546190
- https://github.com//discordjs/discord.js/pull/6162#issuecomment-884157859
- https://github.com//refined-github/refined-github/pull/5506#issuecomment-1067652695
=> Restore padding broken by `scrollable-code-and-blockquote`

source/features/forked-to.tsx
Fixes #5596 
Fork a repo :fork_and_knife:
=> Restore `forked-to` feature and enable it for every user

source/features/release-download-count.tsx
- Fixes #5634 
https://github.com/notepad-plus-plus/notepad-plus-plus/releases
=> Restore broken `release-download-count`

source/features/clean-conversation-filters.tsx
=> Silence `clean-conversation-filters` errors on orgs without projects

source/features/conversation-activity-filter.tsx
- Fixes https://github.com/refined-github/refined-github/issues/5450
Short header: https://github.com/refined-github/refined-github/issues/5449
Long header: https://github.com/refined-github/refined-github/issues/5450
Notice the direction
=> Avoid clipping `conversation-activity-filter`

source/features/forked-to.tsx, source/features/sort-conversations-by-update-time.tsx
- Fixes https://github.com/refined-github/refined-github/issues/5609
- Fixes #5435
1. Visit any repo, like this one
2. Fork it
3. Return to this repo
You should see the button
1. Open https://github.com/refined-github/refined-github/issues
2. Open an issue
You should not see an error in the console
=> Restore broken `forked-to`

source/features/highlight-deleted-and-added-files-in-diffs.tsx
- Fixes #5565
PR: https://github.com/refined-github/refined-github/pull/5631/files
PR with CODEOWNERS: https://github.com/dotnet/winforms/pull/6028/files
<table>
<tr>
<th>Before
<th>After
<tr>
<td> <img src="https://user-images.githubusercontent.com/1402241/169677369-bc5b1e8a-3eba-4d70-9766-89de4c90de22.png">
<td><img src="https://user-images.githubusercontent.com/1402241/169677382-e2028127-ab46-47c9-8ea9-dbb5d3de095c.png">
</table>
=> Fix `highlight-deleted-and-added-files-in-diffs` with CODEOWNERS

source/features/open-all-notifications.tsx
- Closes https://github.com/refined-github/refined-github/issues/3068
A hidden feature just for Mr Sor
Alt-click demo:
https://user-images.githubusercontent.com/1402241/169694391-afffe7ca-a153-4616-b4be-9e8b54ffb5c3.mov
=> Alt-click on `open-all-notifications` to also mark them as done

source/features/open-all-conversations.tsx, source/features/open-all-notifications.tsx, source/helpers/confirm-open.ts, source/helpers/open-tabs.ts
Fix #5679 
* [Repo PR list](https://github.com/refined-github/refined-github/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc)
* [Global PR list](https://github.com/pulls?q=is%3Apr+is%3Aopen+author%3A%40me+archived%3Afalse+sort%3Aupdated-desc)
https://user-images.githubusercontent.com/46634000/172637096-85b9f6fa-4aca-46b5-b1d4-634d25047e72.mp4
=> Fix `open-all-conversations` feature

source/refined-github.css
https://github.com/refined-github/refined-github/issues/5657#issuecomment-1134077169
Replaces #5658 
* https://togithub.com/refined-github/refined-github/pull/5658
**Before**
**After**
=> Stack titles in title edition events to improve readability

source/github-helpers/api.ts
Closes #5713
https://github.com/apollographql/federation-rs/releases/tag/supergraph%40v2.0.5
NA
=> Fix `release-download-count` on releases with @ in their names

source/features/toggle-files-button.tsx, source/helpers/attach-element.ts, source/helpers/hash-string.ts
- Closes https://github.com/refined-github/refined-github/issues/5692
- Closes https://github.com/refined-github/refined-github/issues/5693
URL: https://github.com/refined-github/refined-github
https://user-images.githubusercontent.com/1402241/174477063-52f36daa-e552-4552-ada6-a51fffe5718a.mov
=> Avoid duplication in `toggle-files-button`

source/features/open-all-notifications.css, source/features/open-all-notifications.tsx, source/features/select-notifications.tsx, source/refined-github.css
Resolves #5705. Tested in Firefox and Chromium.
=> Improve positioning of `open-all-notifications`

package-lock.json, package.json, source/features/show-whitespace.tsx, source/helpers/show-whitespace-on-line.test.ts, source/helpers/show-whitespace-on-line.tsx, test/fixtures/globals.ts
=> Meta: Add tests for `show-whitespace`

source/features/conflict-marker.tsx, source/github-helpers/api.ts
- Fixes issue caused by https://github.com/refined-github/refined-github/pull/5714
https://github.com/refined-github/refined-github/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
=> Restore `pinned-issues-update-time`

source/options.html, source/options.tsx
<table>
<tr>
<th>Before
<th>After
<tr>
<td><img width="546" alt="Screen Shot 6" src="https://user-images.githubusercontent.com/1402241/176110686-994b1a96-c231-4063-83a2-bd28155abe64.png">
<td><img width="546" alt="Screen Shot 5" src="https://user-images.githubusercontent.com/1402241/176110644-4208b08e-2f68-4ae3-9a80-c4901ac78ce4.png">
</table>
=> Meta: Options page improvements

source/features/clean-repo-sidebar.tsx, source/features/file-finder-buffer.tsx, source/features/hide-navigation-hover-highlight.tsx, source/features/index.tsx, source/features/sticky-sidebar.tsx, source/features/tag-changes-link.tsx
- Maybe closes #5719 ?
- Potentially also mentioned in https://github.com/refined-github/refined-github/pull/5720#issuecomment-1167966280
1. Open https://github.com/refined-github/refined-github/issues
3. Click on Issues tab
https://user-images.githubusercontent.com/1402241/176489932-20874707-d01b-4234-aa1f-fee4da581eea.mov
https://user-images.githubusercontent.com/1402241/176490087-90b92331-a8f3-4f01-b167-017334003e32.mov
=> Fix CSS features disappearing after clicking on a link

collaborators.md, source/features/index.tsx, source/helpers/hotfix.ts, source/helpers/is-development-version.ts, source/helpers/template-literal.ts
- As mentioned in https://github.com/refined-github/refined-github/issues/5222#issuecomment-1167741255
- See the content in https://github.com/refined-github/yolo
- Note that when creating commits on the new repo, issue references **in commit titles** need to be `refined-github/refined-github#1234` instead of just `#1234` (or just the whole issue URL)
=> Meta: Move hotfixes to new repo + allow string hotfixes

source/features/useful-forks.tsx
- Closes https://github.com/refined-github/refined-github/issues/5443
https://github.com/reactjs/react-autocomplete
=> Add `useful-forks` to archived repos

source/features/new-repo-disable-projects-and-wikis.tsx
- Closes https://github.com/refined-github/refined-github/issues/4605
https://github.com/new
=> Highlight `new-repo-disable-projects-and-wikis`

readme.md, source/features/reactions-avatars.tsx, source/features/repo-avatars.tsx, source/github-helpers/get-user-avatar.ts, source/github-helpers/index.ts, source/refined-github.ts
Resolve #5546
Code loosely adapted from https://github.com/kidonng/cherry/blob/b7dfa1b01802e708a40c0bef82a93b1f5a6ca3eb/scripts/github-repository-avatars.user.tsx
- User: https://github.com/sindresorhus/awesome
- Org: Here
<table>
<tr>
<td>User
<td>Org
<tr>
<td><img width="389" alt="image" src="https://user-images.githubusercontent.com/44045911/177211937-540504bd-f072-41c8-87bd-fc21cc288b37.png">
<td><img width="396" alt="image" src="https://user-images.githubusercontent.com/44045911/177211845-c9b0fa37-c157-4449-890e-af2602c312e3.png">
</table>
=> Add `repo-avatars` feature

source/features/user-local-time.tsx
Resolve #5775
A lot of dup code, get this thing out first
https://github.com/fregante
=> Extend `user-local-time` to user profiles

source/features/dim-bots.css, source/features/dim-bots.tsx
Fix #5786
https://github.com/levrik/mdi-react/commits/master
https://user-images.githubusercontent.com/44045911/177605889-9bc81ece-65d1-4183-ad72-dcac67b066e1.mov
=> Fix `dim-bots`

source/features/readable-title-change-events.css, source/refined-github.css, source/refined-github.ts
- As suggested in https://github.com/refined-github/refined-github/pull/5703#issuecomment-1176568500
This page
=> Improve `readable-title-change-events` order

.github/ISSUE_TEMPLATE/1_bug_report.yml, source/features/rgh-improve-new-issue-form.tsx, source/refined-github.css
- Described in https://github.com/refined-github/refined-github/issues/5222#issuecomment-1168268259
See it at https://github.com/refined-github/refined-github/issues/new?assignees=&labels=bug&template=1_bug_report.yml
Changes welcome
<table>
<tr>
<th>Before
<th>After
<tr>
<td><img width="760" alt="Screen Shot 13" src="https://user-images.githubusercontent.com/1402241/178100359-f7501219-9d52-4ae2-8727-add41632a03e.png">
<td><img width="760" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/178100376-9bc3da5d-2558-43f2-9697-a27fbfe0427c.png">
</table>
=> Meta: Improve new bug template

source/features/patch-diff-links.tsx
Make it work with multiple consecutive slashes.
https://github.com//refined-github/refined-github/pull/5327/commits/2e2dc93f2b6f626a7b02da243d66c9f7586ef0d8 (from https://github.com/refined-github/refined-github/issues/5326#issuecomment-1018549713)
N/A
=> Improve reliability of `patch-diff-links`

.github/ISSUE_TEMPLATE/2_feature_request.yml, source/features/new-repo-disable-projects-and-wikis.tsx, source/features/prevent-link-loss.tsx, source/features/rgh-welcome-issue.tsx
I'm creating this PR to keep track of the changes required by the move of content to the wiki. @kidonng please include any further changes here
=> Meta: Move content to wiki

source/features/repo-avatars.tsx
Small improvement to `repo-avatars` to address https://github.com/refined-github/refined-github/issues/5546#issuecomment-1189033522
Here
=> Link `repo-avatars` to repository author

source/refined-github.css
=> Hide label on Milestones link if there are zero milestones

source/features/show-whitespace.css
- Fixes https://github.com/refined-github/refined-github/issues/4991#issuecomment-1201374863
https://github.com/npmhub/npmhub/blob/main/.xo-config.json#L2
<table>
<tr>
<th>Before
<th>After
<tr>
<td><img width="140" alt="Screen Shot 3" src="https://user-images.githubusercontent.com/1402241/183232740-99c8fda6-1442-4744-a3a2-ecdbd685ba50.png">
<td><img width="140" alt="Screen Shot 4" src="https://user-images.githubusercontent.com/1402241/183232737-27a1e1dd-139c-43a6-aa3d-16e66dbd9c58.png">
</table>
=> Fix `show-whitespace` peekaboo bugfix bug

source/features/github-bugs.css
=> Drop some fixes for GitHub bugs

source/features/index.tsx
- Fixes #5857
- Kinda reverts #5493
=> Fix: User style lost after navigation

source/features/repo-avatars.tsx
A small bug introduced in #5885.
Here
<table>
<tr>
<td>Before
<td><img width="317" alt="image" src="https://user-images.githubusercontent.com/44045911/184803527-118ed544-34af-41c7-b9d1-155e5718295c.png">
<tr>
<td>After
<td><img width="316" alt="image" src="https://user-images.githubusercontent.com/44045911/184803536-a5cc38b8-4f4c-415e-846e-2339111f429b.png">
</table>
=> Fix `repo-avatars` alignment

source/features/linkify-code.tsx
Resolve #5915
https://github.com/File-New-Project/EarTrumpet/discussions/877
=> Enable `linkify-code` on discussions

source/features/show-names.tsx, source/github-events/on-fragment-load.ts, source/github-events/on-newsfeed-load.ts
Fixes #5927 
- This page
- Your newsfeed
**Conversation**
**Newsfeed**
=> Restore `show-names` feature

.github/workflows/test.yml
Reverts refined-github/refined-github#5799
=> Meta: Restore artifacts on CI

source/features/sticky-sidebar.css, source/features/sticky-sidebar.tsx, source/helpers/calculate-css-calc-string.test.ts, source/helpers/calculate-css-calc-string.ts, webpack.config.ts
- Closes https://github.com/refined-github/refined-github/issues/5939
- this PR
- the repo home
To actually test it, you'd have to try on a repo with projects, as shown in the original issue
=> Don't change `sticky-sidebar` state while interacting with it

source/features/center-reactions-popup.css
Fixes #5957 
- #5957 (issue conversation)
- this page (PR conversation)
*Before*
*After*
=> Fix reaction popup at bottom of comments

package.json, source/features/open-all-notifications.tsx, source/helpers/attach-element.ts
- Fixes #5947
1. Open https://github.com/notifications
5. Visit the "Done" section in the sidebar
6. Go back
7. Click "Open"
8. It works ✅
=> Fix `open-all-notifications` on back button

source/features/one-click-diff-options.tsx
- Fixes https://github.com/refined-github/refined-github/issues/5288
1. Visit the "Files" tab above
2. Ensure your window is wide enough that `one-click-diff-options` is shown
3. Click the "split diff" view (or unified)
4. Wait for it to load
5. Refresh the page
6. The new view should be persisted
=> Persist `one-click-diff-options` like the native buttons

source/features/select-notifications.css, source/features/show-whitespace.tsx, source/globals.d.ts
- Fixes https://github.com/refined-github/refined-github/issues/5729
- Related to https://github.com/refined-github/refined-github/issues/5992
Any comments with code or suggestions 
Tested:
- edited suggestion, code block
- new comment
https://user-images.githubusercontent.com/1402241/190839257-02a93a89-8955-470c-a447-c38a9577d17a.mov
=> Make `show-whitespace` more reliable

source/features/open-all-conversations.tsx, source/helpers/attach-element.ts
- Fixes https://github.com/refined-github/refined-github/issues/5679
- Part of https://github.com/refined-github/refined-github/issues/5871
- https://github.com/refined-github/refined-github/pulls
- https://github.com/refined-github/refined-github/issues
https://user-images.githubusercontent.com/1402241/191004249-c2850ebd-2878-42af-a31b-6b32d6a22949.mov
=> Restore ability to open selected issues in `open-all-conversations`

package-lock.json, package.json
- Fixes https://github.com/refined-github/refined-github/issues/5903
- This PR
=> Avoid duplicate indentation in `tab-to-indent`

source/features/comment-fields-keyboard-shortcuts.tsx, source/features/convert-release-to-draft.tsx, source/features/copy-file.tsx, source/features/deep-reblame.tsx, source/features/esc-to-cancel.tsx, source/features/hide-low-quality-comments.tsx, source/features/one-click-diff-options.tsx, source/features/one-click-review-submission.tsx, source/features/pr-filters.tsx, source/features/rgh-sponsor-button.tsx, source/features/rgh-welcome-issue.tsx, source/helpers/attach-element.ts
- Closes https://github.com/refined-github/refined-github/issues/5871
~~Un~~tested
=> Avoid `delegate`/`deduplicate` combination errors

package-lock.json, package.json
- Includes https://github.com/fregante/webext-dynamic-content-scripts/pull/38
- Potentially fixes https://github.com/refined-github/refined-github/issues/6025
The issue above probably cannot be fixed until:
- #5531 
but it's worth a try.
=> Future-proof GitHub Enterprise injection logic

source/features/convert-release-to-draft.tsx
Closes #6033 
https://github.com/refined-github/yolo/releases/tag/6033
=> Ask for confirmation in `convert-release-to-draft`

source/features/global-conversation-list-filters.tsx, source/features/profile-gists-link.tsx, source/features/show-user-top-repositories.tsx
- Fixes #6011 
- Fixes https://github.com/refined-github/refined-github/issues/5995
- Replaces https://github.com/refined-github/refined-github/pull/5996
https://github.com/pulls
https://github.com/fregante
=> Avoid duplicate links in 3 features

source/features/release-download-count.tsx
- Closes #6014 
- https://github.com/notepad-plus-plus/notepad-plus-plus/releases
=> Add support for lazy-loaded assets in `release-download-count`

source/features/clean-dashboard.css, source/features/hide-newsfeed-noise.css, source/features/hide-own-stars.tsx
- Fixes https://github.com/refined-github/refined-github/issues/6069
- Fixes https://github.com/refined-github/refined-github/issues/6066
- Includes https://github.com/refined-github/refined-github/pull/6051
=> Fix `clean-dashboard`, `hide-newsfeed-noise`, `hide-own-stars`

source/features/dim-bots.tsx
Resolves #6070. Also noticed that they updated the selector, so only the open PR was being dimmed, not closed.
=> Add weblate to `dim-bots`  and fix collapsing

source/features/clear-pr-merge-commit-message.tsx
- fix https://github.com/refined-github/refined-github/issues/6109
This PR (if unmerged)
=> Fix `clear-pr-merge-commit-message`/`sync-pr-commit-title`

source/features/view-last-pr-deployment.tsx
- closes https://github.com/refined-github/refined-github/issues/5984
https://github.com/fregante/bundle/pull/2
=> Restore `view-last-pr-deployment`

source/features/clean-dashboard.css
- Fixes https://github.com/refined-github/refined-github/issues/6085
=> Fix `clean-dashboard` spacing of grouped items

.github/workflows/release.yml
=> Meta: Improve release workflow

source/features/clean-repo-sidebar.tsx, source/features/releases-tab.tsx
=> Fix `releases-tab` count /3

source/features/highest-rated-comment.css, source/features/highest-rated-comment.tsx
Closes #6196.
https://github.com//ytdl-org/youtube-dl/issues/30568#issuecomment-1024989514
=> Update and fix `highest-rated-comment`

package-lock.json, package.json
- Includes https://github.com/fregante/webext-storage-cache/pull/37
- Should fix https://github.com/refined-github/refined-github/issues/5821
1. Open https://github.com/refined-github/sandbox in a new tab
2. Click the "Refined GitHub" link **in the readme**
❌ Notice the "cool" tab appearing on "Refined GitHub"
3. Refresh the page to see the right tag
https://user-images.githubusercontent.com/1402241/216236316-caaf0c11-d11f-49ff-a1c9-273d2f64bba3.mov
https://user-images.githubusercontent.com/1402241/216238905-252f785a-8b1f-4607-8b89-74f71ca0a24a.mov
=> Fetch correct item from cache after an ajax navigation

source/features/repo-wide-file-finder.tsx
- For #6142 
This is the least we could do right now. 
1. Open https://github.com/refined-github/refined-github/releases
2. Press `t`
=> Use new File Finder view in `repo-wide-file-finder`

package-lock.json, package.json, source/globals.d.ts
- Likely broken since https://github.com/refined-github/refined-github/pull/5724
- `esc`: this PR
- `up`: any issue where you just left a comment
=> Restore `comment-fields-keyboard-shortcuts`

source/features/quick-comment-hiding.tsx, source/globals.d.ts
- Closes https://github.com/refined-github/refined-github/issues/5879
https://github.com/refined-github/sandbox/pull/47
=> Add support for PR review comments to `quick-comment-hiding` 

source/features/rgh-feature-descriptions.tsx
Fixes #6337 
https://github.com/refined-github/refined-github/blob/main/source/features/action-used-by-link.tsx
=> Fix overlap in `rgh-feature-descriptions`

source/features/expand-all-hidden-comments.tsx, source/features/update-pr-from-base-branch.tsx
- Includes https://github.com/refined-github/refined-github/issues/5222#issuecomment-1201437649
- expand all: https://github.com/rust-lang/rfcs/pull/2544
- update branch: any undateable PR of yours
=> Meta: Show toast in more features

.github/workflows/actionlint.yml, .github/workflows/release.yml
- Mentioned in https://github.com/refined-github/refined-github/issues/5222#issuecomment-1304731693
- Also https://github.com/fregante/ghatemplates/pull/13
Copied from https://github.com/rhysd/actionlint/blob/048c97d90b98b832450d3adf00fc7757b0ed9953/docs/usage.md#use-actionlint-on-github-actions
=> Meta: add `actionlint`

source/features/clear-pr-merge-commit-message.tsx, source/features/quick-comment-edit.css, source/features/quick-comment-edit.tsx, source/features/sync-pr-commit-title.tsx, source/features/wait-for-checks.tsx, source/github-helpers/index.ts
- Includes https://github.com/refined-github/refined-github/issues/5222#issuecomment-1166529517
cc @cheap-glitch 
Any other features?
Any open PR that you can't merge
=> Disable some features on PRs that the user can't edit

source/feature-manager.tsx, source/features/conversation-activity-filter.tsx, source/features/rgh-improve-new-issue-form.tsx
- Includes https://github.com/refined-github/refined-github/issues/5222#issuecomment-1070341541
- Fixes #6300
https://github.com/refined-github/refined-github/issues/new?assignees=&labels=bug&template=1_bug_report.yml
More exact notice:
=> Restore `rgh-improve-new-issue-form`

source/features/conflict-marker.tsx, source/features/pr-approvals-count.css
- Fixes https://github.com/refined-github/refined-github/issues/6420
https://github.com/discretize/discretize-gear-optimizer/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+for+
=> Restore `conflict-marker`

source/options.tsx
- Closes https://github.com/refined-github/refined-github/issues/6404
=> Autofocus field in options page

contributing.md, package-lock.json, package.json, readme.md, source/features/clean-conversation-headers.tsx, source/features/closing-remarks.tsx, source/features/jump-to-conversation-close-event.tsx, source/features/netiquette.tsx, source/github-helpers/banner.tsx, source/refined-github.ts
- Part of #5934 
- Old issue: https://github.com/refined-github/refined-github/issues/3076
- Old PR: https://github.com/refined-github/refined-github/pull/159
=> Add `netiquette` feature

readme.md, source/features/unhide-reactions-on-mobile.css, source/refined-github.ts
=> Drop `unhide-reactions-on-mobile` feature

source/refined-github.css
- Fixes https://github.com/refined-github/refined-github/issues/6474
https://github.com/refined-github/sandbox/pull/53
=> Fix merge button corners in Firefox

source/features/clean-checks-list.css, source/features/clean-mergeability-box.css
Fix #6467
- Should fix bug on https://github.com//refined-github/refined-github/pull/6466
- Should not break on https://github.com//refined-github/sandbox/pull/12
=> Fix pull request review list style

readme.md, source/features/swap-branches-on-compare.tsx
Fix #6361
https://github.com/refined-github/refined-github/compare/23.2.1...main
=> Restore `swap-branches-on-compare`

.github/release.yml, package-lock.json, package.json, source/options.html
- Fixes https://github.com/refined-github/refined-github/issues/3981
- Includes https://github.com/fregante/webext-options-sync/pull/65
=> Add options export/import

source/helpers/bisect.tsx
Nice feature, but the wording could use some refinement.
=> Meta: Refine bisect message

source/features/ci-link.tsx
- For https://github.com/refined-github/refined-github/issues/6454
This just disables the feature where it can't appear. Help wanted in the issue above.
=> Silence `ci-link` error

source/features/clear-pr-merge-commit-message.tsx, source/features/sync-pr-commit-title.tsx
- Fixes https://github.com/refined-github/refined-github/issues/6348
- Fixes https://github.com/refined-github/refined-github/issues/6547
Any open PR
=> Avoid race conditions in PR merge commit fields

source/features/quick-review-comment-deletion.tsx
Fixes https://github.com/refined-github/refined-github/issues/6065
https://github.com/refined-github/refined-github/pull/6604
=> Restore `quick-review-comment-deletion` 

source/feature-manager.tsx
=> Meta: Improve DX when features are not yet finalized

package-lock.json, package.json, source/background.ts, source/options-storage.ts, source/options.tsx
- Includes https://github.com/fregante/webext-detect-page/releases/tag/v4.1.0
- Will fix #6587
=> Automatically set popup to contain options on iOS

source/features/one-click-review-submission.tsx
- Fixes #6618
- https://github.com/refined-github/refined-github/pull/6619/files
=> Restore `one-click-review-submissions`

source/features/default-branch-button.tsx, source/features/quick-file-edit.tsx, source/github-helpers/get-default-branch.ts, source/github-helpers/index.ts, source/github-helpers/selectors.ts
- Should fix https://github.com/refined-github/refined-github/issues/6626
https://github.com/refined-github/refined-github/tree/main/.github
=> Some fixes around `quick-file-edit`

readme.md, source/features/ci-link.css, source/features/ci-link.tsx, source/features/previous-version.tsx
- Fixes https://github.com/refined-github/refined-github/issues/6454
Here
=> Restore `ci-link` on new header UI

source/features/open-all-notifications.tsx, source/helpers/open-tabs.ts
- Fixes https://github.com/refined-github/refined-github/issues/6590
I need to verify that it actually throws an error, because I think it doesn't
=> Fix `open-all-notifications` error display

source/features/prevent-link-loss.tsx, source/github-helpers/banner.tsx
=> Improve `prevent-link-loss` layou on mobile

readme.md
=> Meta: Fix typo in readme

source/features/clean-rich-text-editor.tsx
Closes [#6589](https://github.com/refined-github/refined-github/issues/6589)
Test on any page with required text inputs, such as [the create issue page](https://github.com/refined-github/refined-github/issues/new?template=1_bug_report.yml), [an issue](https://github.com/refined-github/refined-github/issues/6408), or [a discussion](https://github.com/StrataSource/Portal-2-Community-Edition/discussions/706)
=> Meta: Add test URLs to `clean-rich-text-editor`

build/verify-test-urls.sh, source/background.ts, source/features/rgh-linkify-yolo-issues.tsx
Various improvements. See review
=> Meta: Improve "Test URLs" annotations

source/background.ts, source/helpers/feature-utils.ts, source/options.tsx
- Closes https://github.com/refined-github/refined-github/issues/5455
- Follows https://github.com/refined-github/refined-github/pull/6592
Popups are awkward. Let's try this
=> Open options in a new tab on iOS Safari

source/features/wait-for-checks.tsx
- Fixes #6689 
~~I could probably also fix the issue #6331 here~~
A PR on a repo with merge queue. We don't have one 
https://github.com/refined-github/refined-github/assets/1402241/64345220-2c45-43dd-a80b-005b643593a6
=> Avoid `wait-for-checks` conflicts with GitHub’s AutoMerge

source/features/pr-approvals-count.css
- Closes https://github.com/refined-github/refined-github/issues/6473
=> Permanently fix `pr-approvals-count` in Safari

source/features/fit-textareas.tsx
- Closes https://github.com/refined-github/refined-github/issues/6639
https://github.com/refined-github/sandbox/issues/3
=> `fit-textareas` after a comment submission

source/features/restore-file.tsx
- Probably fixes https://github.com/refined-github/refined-github/issues/6679
https://github.com/refined-github/sandbox/pull/16/files
Created commit: https://github.com/refined-github/sandbox/pull/16/commits/12344dcf2929c8c776d16138180b343d185803be
Demo: (note that here are 2 files initially)
https://github.com/refined-github/refined-github/assets/1402241/6be342b3-1769-41be-84be-4fdf7dc34b20
=> Handle renamed files in `restore-file`

source/options.html
- Should fix https://github.com/refined-github/refined-github/issues/6724
=> Fix options "project" scope checker

source/features/readable-title-change-events.css
- Fixes https://github.com/refined-github/refined-github/issues/6548
https://github.com/refined-github/sandbox/pull/62
=> Fix `readable-title-change-events` wrap on unwrappable titles

source/feature-manager.tsx
- Probably fixes https://github.com/refined-github/refined-github/issues/6386
- On PRs (here), "Select all notifications" should not appear
- On [notifications](https://github.com/notifications), it should
=> Only show active shortcuts in the shortcut viewer

source/features/bugs-tab.tsx, source/github-helpers/bugs-label.test.ts, source/github-helpers/bugs-label.ts
- Close https://github.com/refined-github/refined-github/issues/6144
It'd be best to add tests for this at some point
=> Meta: Add label tests in `bugs-tab`

readme.md
I knew these feature had to exist, but I failed to find it from grepping README. I ended up searching the issues and finding #6044.
Thanks for this extension!
=> Improve search bait for `expand-all-hidden-comments`

source/options.tsx
- Extracted from https://github.com/refined-github/refined-github/pull/6722
https://github.com/refined-github/refined-github/assets/1402241/e009ad5b-ec0d-4a91-9e5d-b10275bd5dd0
=> Meta: `scrollIntoViewIfNeeded` in options

source/options.html
[Link](https://github.com/settings/tokens/new?description=Refined%20GitHub&scopes=repo,delete_repo,project)
=> Include project scope in token generation link

source/features/rgh-feature-descriptions.tsx
- Closes https://github.com/refined-github/refined-github/issues/6763
- Enabled: https://github.com/refined-github/refined-github/blob/567a90067a4d7ad77e463bf4dfd6ffef785cf58f/source/features/rgh-feature-descriptions.tsx
- Disabled: https://github.com/refined-github/refined-github/blob/567a90067a4d7ad77e463bf4dfd6ffef785cf58f/source/helpers/abbreviate-number.ts
=> Limit `rgh-feature-descriptions` to features

readme.md, source/features/repo-avatars.tsx
- Closes https://github.com/refined-github/refined-github/issues/6784
- org repo: https://github.com/refined-github/refined-github/issues
- user repo: https://github.com/fregante/GhostText/issues
=> Restore `repo-avatars`

source/features/select-notifications.tsx
Fixes https://github.com/refined-github/refined-github/issues/6801
Test URL:
- https://github.com/notifications
=> Select closed rejected issues in `select-notifications`

source/features/archive-forks-link.tsx, source/features/link-to-github-io.tsx
- Closes https://github.com/refined-github/refined-github/issues/6456
=> Review `hasRepoHeader` usage

package-lock.json, package.json, source/features/actionable-pr-view-file.tsx, source/features/conversation-links-on-repo-lists.tsx, source/features/convert-release-to-draft.tsx, source/features/download-folder-button.tsx, source/features/hidden-review-comments-indicator.tsx, source/features/link-to-changelog-file.tsx, source/features/link-to-github-io.tsx, source/features/one-click-diff-options.tsx, source/features/one-click-review-submission.tsx, source/features/pagination-hotkey.tsx, source/features/parse-backticks.tsx, source/features/previous-next-commit-buttons.tsx, source/features/restore-file.tsx, source/features/tag-changes-link.tsx
https://github.com/refined-github/github-url-detection/releases/tag/v8.0.0
- Rename isSingleTag to isSingleReleaseOrTag
=> Improve page detection

source/features/action-pr-link.tsx, source/features/conversation-activity-filter.css
- Closes #6767
- https://github.com/refined-github/refined-github/pull/6794
=> Extend `action-pr-link` to links in PRs

package.json, source/options.tsx
Fixes https://github.com/refined-github/refined-github/issues/6807
Fixes https://github.com/refined-github/refined-github/issues/6785
https://github.com/refined-github/refined-github/assets/1402241/6ad0f5f4-cf6e-42ba-886d-b4cc681b0cd2
https://github.com/refined-github/refined-github/assets/1402241/4e2369d2-6fb9-4704-9008-7b92d94d753b
cc @jsumners @orrc
=> Fix options overscroll on load

source/features/quick-mention.tsx
Closes #6811
https://github.com/SimonMarquis/SealedObjectInstances/pull/130
=> Drop `[bot]` from usernames in `quick-mention`

source/features/dim-bots.tsx
- fixes #6856 
<https://github.com/cataclysmbnteam/Cataclysm-BN/pulls?q=is%3Apr+author%3Aborsek+sort%3Aupdated-desc>
=> Avoid false positives in `dim-bots`

source/feature-manager.tsx, source/features/conversation-activity-filter.tsx, source/features/create-release-shortcut.tsx, source/features/linkify-branch-references.tsx, source/features/profile-hotkey.tsx, source/features/repo-wide-file-finder.tsx, source/features/select-all-notifications-shortcut.tsx, source/features/selection-in-new-tab.tsx, source/github-helpers/hotkey.tsx, source/globals.d.ts, source/helpers/abort-controller.ts
=> Meta: Drop `deinit` functions

source/feature-manager.tsx, source/features/clean-repo-sidebar.tsx, source/features/clean-repo-tabs.tsx, source/features/rgh-improve-new-issue-form.tsx, source/globals.d.ts, source/helpers/async-for-each.ts
Part of https://github.com/refined-github/refined-github/issues/6000#issuecomment-1426645966
=> Meta: Accept `init` array

source/helpers/bisect.tsx
- Close https://github.com/refined-github/refined-github/issues/5668
- Replaces https://github.com/refined-github/refined-github/pull/6828
=> Meta: Improve bisect message

build/verify-features.ts, source/features/link-to-changelog-file.tsx
From https://github.com/refined-github/refined-github/pull/6879
cc @FloEdelmann any other tests?
=> Meta: Verify GQL files

source/features/default-branch-button.tsx, source/features/useful-not-found-page.tsx, source/github-helpers/index.ts
- `isUrlReachable` function's behavior is not matches it's name.
- Flip it's behavior and usages
- https://github.com/refined-github/refined-github/pull/6840#discussion_r1320079324
cc. @jerone
=> Match the behavior of function `isUrlReachable` to its name

package-lock.json, package.json, source/features/linkify-code.tsx, source/github-helpers/dom-formatters.tsx
Reverts https://github.com/refined-github/refined-github/pull/6844 because it was implemented in https://github.com/sindresorhus/linkify-urls/pull/40
* https://github.com/search?q=repo%3AKatsuteDev%2FBackground+marketplace&type=code
* https://github.com/sindresorhus/linkify-urls/pull/40#pullrequestreview-1593302757
Working links and truncated links at end:
Links truncated in the middle:
=> Meta: Extract `linkify-code` truncation logic to `linkify-urls`

source/features/infinite-scroll.tsx
- Closes #6912
- The main reason of the issue is `select('[role="tabpanel"]:not([hidden]) button.ajax-pagination-btn')!` is no longer available
- Fix the selector.
- Remove deprecated `deduplicate: 'has-rgh'` and `awaitDomReady: true` with using `selector-observer`
- https://github.com/
=> Restore `infinite-scroll` broken on new dashboard

source/features/pinned-issues-update-time.tsx, source/features/show-names.tsx
batchedFunction wasn't doing its job because it was calling the callback too often. 
- Discovered in https://github.com/refined-github/refined-github/pull/6839#discussion_r1304212911
- Also visible in https://github.com/refined-github/refined-github/pull/6916
=> Properly merge API requests

source/features/repo-header-info.tsx
- Closes #6923
- Click on the CI checkmark
- Before
- After
=> `repo-header-info` - Bugfix: Also appears in wrong place

source/features/repo-header-info.tsx
- Close https://github.com/refined-github/refined-github/issues/6926
- Address https://github.com/refined-github/refined-github/pull/6900#issuecomment-1724702659
=> `repo-header-info` - Add link and tooltip

package-lock.json, package.json
- Temporarily fixes https://github.com/refined-github/refined-github/issues/6930
cc @Katsute 
- Discussions: https://github.com/File-New-Project/EarTrumpet/discussions/877
- Code Search: https://github.com/search?q=repo%3AKatsuteDev%2FBackground+marketplace&type=code
- Comment: https://github.com/sindresorhus/linkify-urls/pull/40#pullrequestreview-1593302757
=> `linkify-code` - Fix console error

source/features/clean-repo-header.css, source/features/clean-repo-header.tsx, source/features/conversation-activity-filter.css, source/refined-github.ts
- Closes #6940 
- Follows #6908 
- Includes #6665 
People _really_ love those counters in that exact same place, even if they cause trouble. 🤷‍♂️
=> `clean-repo-header` - Let users disable it

source/options.html, source/options.tsx
- Closes #6952
- Your extension's options page
https://github.com/refined-github/refined-github/assets/50487467/df98d2d8-c6b0-4e7b-8195-870f72384519
=> Support fine-grained tokens in the options and update the widget

.github/pull_request_template.md, source/features/rgh-pr-template.tsx, source/refined-github.ts
- Closes #6697 
https://github.com/refined-github/refined-github/compare/main...sandbox/keep-branch?quick_pull=1
=> Add `rgh-pr-template` feature

source/background.ts, source/feature-manager.tsx
- Fixes https://github.com/refined-github/refined-github/issues/6433
=> Avoid 404 hotfix request in console

build/new-feature.sh, contributing.md, package.json
```
> nr new -- one-click-issue-closure
✨ Feature created! ✨
source/features/one-click-issue-closure.tsx
After you're done, also add the feature to ./readme.md; Don't worry about the screenshot yet
Refer to https://github.com/refined-github/refined-github/blob/main/contributing.md for more information.
```
=> Meta: Add `npm run new` to add new features

source/features/collapsible-content-button.tsx
- For https://github.com/refined-github/refined-github/issues/7012
- Related to https://github.com/refined-github/refined-github/issues/7021
Here
=> `collapsible-content-button` - Restore feature

source/features/collapsible-content-button.tsx, source/features/table-input.css, source/features/table-input.tsx
See https://github.com/refined-github/refined-github/issues/5797#issuecomment-1796191920
=> `table-input` and `collapsible-content-button` - Silence Firefox error 

source/features/easy-toggle-files.tsx, source/github-helpers/selectors.ts
Closes #6975 
https://github.com/search?q=repo%3Arefined-github%2Frefined-github%20easy&type=code
=> `easy-toggle-files` - Apply to code search

source/features/clean-checks-list.css
* Closes #6945 
* ~~Also: vertically align app/gh icon~~
* Top align run status icon
https://github.com/refined-github/sandbox/pull/12
**before**
**after**
=> `clean-checks-list` - Untruncate check descriptions

package-lock.json, package.json, source/options-storage.ts, source/options.tsx
This has been here ever since I added this feature and nobody ever complained 😅
=> Fix "Hotfixes are not applied on GitHub Enterprise." error

source/features/dim-bots.css, source/features/dim-bots.tsx, source/features/mark-merge-commits-in-list.css
close: #7068 
- Commits: https://github.com/typed-ember/ember-cli-typescript/commits/master?after=5ff0c078a4274aeccaf83382c0d6b46323f57397+174
- Commits by unmarked bot: https://github.com/rust-lang/rust/commits/master?after=c387f012b14a3d64e0d580b7ebe65e5325bcf822+34&branch=master&qualified_name=refs%2Fheads%2Fmaster
- PRs: https://github.com/OctoLinker/OctoLinker/pulls?q=is%3Apr+is%3Aclosed
- PRs by unmarked bot: https://github.com/spotify/scio/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed+steward
- PR Commits: https://github.com/pixiebrix/webext-messenger/pull/173/commits
after:
=> `dim-bots` - Support new commit list style

source/features/list-prs-for-file.css, source/features/list-prs-for-file.tsx
- Fixes https://github.com/refined-github/refined-github/issues/6845
- Closes #7074 
https://github.com/hashicorp/vault/blob/main/go.mod
=> `list-prs-for-file` - Fix overlap with other components

source/features/highlight-non-default-base-branch.tsx
Fix todo
https://github.com/refined-github/sandbox/pulls?q=is%3Apr+is%3Aopen+pr+branch
=> `highlight-non-default-base-branch` - Use selector-observer

source/features/unwrap-unnecessary-dropdowns.tsx
close: #7103 
[github.com/notifications](https://github.com/notifications)
https://github.com/refined-github/refined-github/assets/82451257/68943782-3e22-4533-967c-838408634d26
=> `unwrap-unnecessary-dropdowns` - Restore feature

source/features/visit-tag.tsx
Mentioned in https://github.com/refined-github/refined-github/issues/7125#issuecomment-1833875365
https://github.com/refined-github/refined-github/releases/tag/23.11.23
=> `visit-tag` - Enable on single releases

.github/workflows/release.yml
- Includes https://github.com/fregante/ghatemplates/pull/15
=> Meta: Improve release script

.github/workflows/features.yml, .github/workflows/test.yml, .xo-config.json, build/__snapshots__/features-meta.json, build/features.test.ts, build/readme-parser.test.ts, build/readme-parser.ts, build/verify-test-urls.sh, package-lock.json, package.json, source/features/copy-on-y.tsx, source/features/rgh-feature-descriptions.tsx, source/github-helpers/prevent-link-loss.ts, source/resolve-conflicts.ts
Some code I wrote while offline. Will Clean Up ™️ 
Context:
- https://github.com/refined-github/refined-github/issues/7132
=> Meta: Move feature checker to vitest

.github/workflows/test.yml, package-lock.json, package.json, test/__snapshots__/shorten-link.test.ts.snap
- Follows https://github.com/refined-github/refined-github/pull/7164
=> Meta: Update vitest

build/verify-test-urls.sh, source/features/table-input.css, source/features/table-input.tsx
- Fixes #7203 
Here
Interestingly… the :hover performance in Chrome is awful… it's `:has(:hover)`-based :(
https://github.com/refined-github/refined-github/assets/1402241/e2403876-960b-4b81-8e78-1b2dd4892b38
=> `table-input` - Restore feature

.github/workflows/test.yml, package-lock.json, package.json
The tests are failing at random, only on CI. This makes them optional
Context:
- https://github.com/vitest-dev/vitest/issues/4920
=> Fix flacky selectors tests

source/features/collapsible-content-button.tsx, source/features/table-input.tsx
- Fixes https://github.com/refined-github/refined-github/pull/7211#issuecomment-1885863318
Here
=> `table-input`/`collapsible-content-button` - Fix overflow

source/features/show-associated-branch-prs-on-fork.css, source/features/show-associated-branch-prs-on-fork.tsx
Closes https://github.com/refined-github/refined-github/issues/7193
https://github.com/bfred-it-org/github-sandbox/branches
With this fix
Without
=> `show-associated-branch-prs-on-fork` - Support new page style

contributing.md
I'm guessing said style guide is supposed to be hidden?
N/A
N/A
=> Fix style guide link in contributing.md

source/features/more-dropdown-links.tsx, source/features/profile-gists-link.tsx, source/features/releases-tab.tsx, source/github-helpers/create-dropdown-item.tsx, source/github-helpers/selectors.ts
- Fixes https://github.com/refined-github/refined-github/issues/7163
Here
=> Update style of repo navigation dropdown

source/features/closing-remarks.tsx, tsconfig.json
- Fixes https://github.com/refined-github/refined-github/issues/7206
- Junk tag: https://github.com/refined-github/sandbox/pull/1
- See: https://github.com/refined-github/sandbox/branch_commits/f743c334f6475021ef133591b587bc282c0cf4c4
- <img width="262" alt="Screenshot 9" src="https://github.com/refined-github/refined-github/assets/1402241/62ac6e4b-be07-4b12-8c7a-47ff34609501">
- Normal tag: https://togithub.com/refined-github/refined-github/pull/7127
- See https://github.com/refined-github/refined-github/branch_commits/5321825
- <img width="261" alt="Screenshot 8" src="https://github.com/refined-github/refined-github/assets/1402241/aafc0f52-f3d4-4f41-b597-22e9837d8f48">
- Nightly tag: https://togithub.com/neovim/neovim/pull/22060
- see: …
=> `closing-remarks` - Exclude nightly tags and non-version tags

source/features/show-associated-branch-prs-on-fork.css
- Thankfully fixes https://github.com/refined-github/refined-github/issues/7251
=> Fix constant Safari crashes due to browser's CSS selector parsing bug

source/features/releases-tab.tsx
=> `releases-tab` - Mention that it requires a token

source/features/hide-low-quality-comments.tsx, source/features/select-notifications.tsx
=> Meta: fix some typos

source/manifest.json
=> Ensure support for Firefox for Android

source/features/locked-issue.tsx, source/features/quick-comment-edit.tsx, source/features/quick-review-comment-deletion.tsx, source/features/show-whitespace.tsx, source/helpers/7116.tsx
=> Disable 4 slow features in Firefox/Safari

source/features/clean-conversation-headers.css, source/features/clean-footer.css, source/features/conflict-marker.css, source/features/emphasize-draft-pr-label.css, source/features/extend-diff-expander.css, source/features/github-bugs.css, source/features/hide-low-quality-comments.css, source/features/highest-rated-comment.css, source/features/highlight-collaborators-and-own-conversations.css, source/features/link-to-compare-diff.css, source/features/mark-private-repos.css, source/features/mobile-tabs.css, source/features/parse-backticks.css, source/features/resolve-conflicts.css, source/features/show-associated-branch-prs-on-fork.css, source/features/sticky-csv-header.css, source/features/table-input.css, source/github-helpers/heat-map.css, source/refined-github.css
=> Use new GitHub color variables

source/features/useful-not-found-page.tsx, source/github-helpers/selectors.ts
=> Meta: fix todo comment typos

source/features/archive-forks-link.tsx
close: #7334 
https://github.com/dnSpy/dnSpy
=> `archive-fork-links` - Update Selector

source/options.html, source/options.tsx
Related to <https://github.com/refined-github/refined-github/issues/6000#issuecomment-1556136109>
=> Show token owner in options page

build/__snapshots__/features-meta.json, readme.md, source/features/toggle-files-button.css, source/features/toggle-files-button.tsx, source/options.tsx
- Reverts https://github.com/refined-github/refined-github/pull/6706
- Will fix https://github.com/refined-github/refined-github/issues/6959
=> `toggle-files-button` - Restore feature

source/features/small-user-avatars.tsx
- Closes https://github.com/refined-github/refined-github/issues/7360
https://github.com/GEOS-ESM/MAPL/pulls?q=is%3Apr+sort%3Aupdated-desc+submodules
=> `small-user-avatars` - Fix wrapping

source/features/quick-comment-edit.tsx, source/features/selection-in-new-tab.tsx
- Close https://github.com/refined-github/refined-github/issues/7246
=> `selection-in-new-tab` - Restore feature

source/features/quick-new-issue.tsx
It feels like they change the DOM every couple of weeks
Here
=> `quick-new-issue` - Restore feature

source/options.tsx
Related: <https://github.com/refined-github/refined-github/pull/7380#issuecomment-2143737791>
=> Show token owner in options page: GHE support

source/features/rgh-improve-new-issue-form.tsx
- Closes https://github.com/refined-github/refined-github/issues/7199
=> `rgh-improve-new-issue-form` - Improve wording on incomplete tokens

package.json, source/features/one-click-pr-or-gist.tsx
- Fixes https://github.com/refined-github/refined-github/issues/7153
- Normal: https://github.com/refined-github/sandbox/compare/default-a...fregante-patch-1
- "Allow edits from maintainers": https://github.com/refined-github/refined-github/compare/main...fregante:refined-github:main?expand=1
=> `one-click-pr-or-gist` - Fix mobile wrapping

source/background.ts, source/features/restore-file.tsx, source/features/toggle-files-button.css
- Fixes https://github.com/refined-github/refined-github/issues/7410
- Minor copy and spacing fixes
1. Change contents of https://github.com/refined-github/sandbox/edit/testing-%60restore-file%60/emoji
2. "Discard changes" in https://github.com/refined-github/sandbox/pull/16/files
=> `restore-file` - Restore UTF-8 support

source/features/rgh-improve-new-issue-form.tsx, source/features/rgh-welcome-issue.css, source/options.html
- Part of https://github.com/refined-github/refined-github/issues/7231
Together with changes made to https://togithub.com/refined-github/refined-github/issues/3543
=> Meta: Invite users to add token

package-lock.json, package.json, source/features/reload-failed-proxied-images.tsx
See https://github.com/fregante/image-promise/issues/27
=> Meta: Drop `image-promise` dependency

source/features/previous-version.tsx
=> `previous-version` - Restore feature

source/features/default-branch-button.css, source/features/default-branch-button.tsx
=> `default-branch-button` - Fix overlap with other components

source/feature-manager.tsx
- Close https://github.com/refined-github/refined-github/issues/6951
_Untested_
=> Meta: Improve error message related to fine-grained tokens

source/features/quick-review.tsx, source/github-helpers/index.ts
- Closes https://github.com/refined-github/refined-github/issues/7151
Any open PR you can approve, like this one
https://github.com/refined-github/refined-github/assets/1402241/9e35d5a6-6e37-4d59-9220-6a5523a37529
=> `quick-review` - Update view after quick approval

source/background.ts, source/options-storage.ts, source/options.html
- Closes https://github.com/refined-github/refined-github/issues/7188
https://github.com/refined-github/refined-github/assets/1402241/52f4fe48-f864-46d6-abc9-539e9fa8f342
=> Meta: Allow opening the options page via "Button Link"

source/features/fit-textareas.tsx
=> Restore extension

source/background.ts
- Fixes #7448 
- #7437 
https://github.com/refined-github/refined-github/assets/1402241/3a67b7f6-ff7f-4c5f-b423-c3fa12109a15
=> Meta: Fix opening the options page via "Button Link"

source/features/netiquette.tsx, source/features/rgh-netiquette.tsx
- Closes https://github.com/refined-github/refined-github/issues/5934
- Popular issue: https://togithub.com/facebook/react/issues/13991
Copy suggestions welcome
=> `netiquette` - Add banner to popular issues

source/features/default-branch-button.css, source/features/default-branch-button.tsx, source/features/list-prs-for-file.css, source/features/list-prs-for-file.tsx, source/github-helpers/index.ts, source/refined-github.css
=> `list-pr-for-files` - Improve performance

build/__snapshots__/features-meta.json, readme.md
- Closes https://github.com/refined-github/refined-github/issues/5389
=> Meta: Clarify "Conversation" jargon

source/features/conversation-activity-filter.css, source/features/conversation-activity-filter.tsx
- Closes https://github.com/refined-github/refined-github/issues/4994
here
=> `conversation-activity-filter` - Add label to Events

build/__snapshots__/features-meta.json, build/__snapshots__/imported-features.txt, package-lock.json, package.json, readme.md, source/features/clickable-line-numbers.tsx, source/features/linkify-line-numbers.tsx, source/refined-github.ts
- Closes https://github.com/refined-github/refined-github/issues/4572
https://github.com/refined-github/sandbox/pull/81
https://github.com/refined-github/refined-github/assets/1402241/2bf042a0-3e4c-4c02-9f5a-a375ab3be7f4
=> `linkify-line-numbers` - New feature

package-lock.json, package.json, source/background.ts, source/feature-manager.tsx, source/features/embed-gist-inline.tsx, source/features/quick-repo-deletion.tsx, source/features/resolve-conflicts.tsx, source/features/rgh-improve-new-issue-form.tsx, source/features/selection-in-new-tab.tsx, source/helpers/hotfix.tsx, source/helpers/is-development-version.ts, source/helpers/open-options.ts, source/helpers/open-tabs.ts, source/helpers/types.d.ts, source/helpers/used-storage.ts, source/options.tsx, webpack.config.ts
=> Drop `webextension-polyfill`

source/features/suggest-commit-title-limit.tsx
Addresses this comment by @fregante:
- https://github.com/refined-github/refined-github/pull/7428#issuecomment-2186176615
https://github.com/refined-github/refined-github/pull/7484/files
=> `suggest-commit-title-limit` - Enable on other PR tabs

package-lock.json, package.json, source/background.ts
1. Added in https://github.com/refined-github/refined-github/pull/7469
2. Mentioned in https://github.com/refined-github/refined-github/issues/5531#issuecomment-2183950424
3. Broken in https://github.com/refined-github/refined-github/pull/7485
4. Extracted to and improved in https://github.com/fregante/webext-tools/pull/8
5. Re-installed here
=> Add "Options…" context menu to Firefox and Safari

package-lock.json, package.json
See https://github.com/refined-github/shorten-repo-url/releases/tag/v5.0.0
=> `shorten-links` - Improve shortener

package-lock.json, package.json, source/background.ts, source/features/fit-textareas.tsx, source/features/list-prs-for-file.tsx, source/features/quick-comment-edit.tsx, source/features/quick-review-comment-deletion.tsx, source/options.tsx
See https://github.com/fregante/webext-detect/releases/tag/v5.0.2
=> Meta: Rename `webext-detect-page`

source/features/rgh-netiquette.tsx
Tiny improvement
- https://github.com/refined-github/refined-github/pull/5983
https://github.com/refined-github/refined-github/assets/1402241/4492271e-18f2-46f8-956c-88990654e7d5
=> `rgh-netiquette` - Keep on screen

.github/workflows/release.yml, build/AMO_BUILD_INSTRUCTIONS
- Testing https://github.com/fregante/ghatemplates/pull/20
=> Upload source to Mozilla Addons

source/features/closing-remarks.tsx
- Mentions https://github.com/refined-github/refined-github/issues/7208
- Mentions https://github.com/refined-github/refined-github/wiki/Extended-feature-descriptions#closing-remarks
https://github.com/refined-github/sandbox/pull/76 
https://github.com/refined-github/refined-github/pull/5983
=> `closing-remarks` - Add link to more details

source/features/clean-footer.css
Fix #7505
KISS
Here
https://github.com/refined-github/refined-github/assets/44045911/8892e9f6-64a7-4019-86fc-a6495e21d4a3
Also tested on dashboard
https://github.com/refined-github/refined-github/assets/44045911/ce5d9d8e-daa4-427b-b24a-99802065b4ed
=> `clean-footer` - Restore feature

source/features/netiquette.tsx
https://github.com//facebook/react/issues/227
| <img width="589" alt="Screenshot 2024-06-30 at 7 56 30 PM" src="https://github.com/refined-github/refined-github/assets/44045911/f858fe91-2da1-4fbe-931a-aa97f7dd5173"> | <img width="591" alt="Screenshot 2024-06-30 at 7 56 40 PM" src="https://github.com/refined-github/refined-github/assets/44045911/1ab2d0c6-c326-40c4-8ced-f7de9f93cc44"> |
=> `netiquette` - Fix spacing on small screen

source/features/unreleased-commits.tsx
Closes #7536
1. [refined-github/refined-github](https://github.com/refined-github/refined-github)
2. toggle your system color
Before
After
=> `unreleased-commits`- Fix duplication after system theme update

source/features/fit-textareas.css, source/features/fit-textareas.tsx
Closes https://github.com/refined-github/refined-github/issues/7522
- https://github.com/mdx-js/mdx/issues/new?assignees=&labels=&projects=&template=1-bug.yml
=> `fit-textareas` - Apply to issue template placeholders

build/__snapshots__/features-meta.json, package-lock.json, package.json, readme.md, source/features/previous-version.tsx, source/github-events/on-react-page-update.tsx, source/manifest.json
- Part of #6554 
- Follows #7440 
- Also fixes a theme-related issue like #7536 
- Also enables it on folders
https://github.com/refined-github/refined-github/blob/main/readme.md
=> `previous-version` - Various fixes

source/features/comment-on-draft-pr-indicator.tsx, source/features/netiquette.tsx, source/github-helpers/index.ts, source/github-helpers/selectors.ts
Follow up https://github.com/refined-github/refined-github/pull/7568#issuecomment-2241694654
https://github.com//nodejs/node/pull/43689#discussion_r914328969
| <img width="790" alt="Screenshot 2024-07-21 at 11 53 05 PM" src="https://github.com/user-attachments/assets/2294725c-104a-4e61-8b10-bfe96e1c1cc7"> | <img width="783" alt="Screenshot 2024-07-22 at 12 01 12 AM" src="https://github.com/user-attachments/assets/422d9163-1f9b-4053-884e-d8713fabf3d3"> |
=> `netiquette` - Avoid appearing on wrong places

source/features/quick-mention.css, source/features/quick-mention.tsx
Fix #7561
Fix #7575
- https://github.com//dotnet/docs/issues/10085
- https://github.com//biomejs/biome/issues/1927#issuecomment-2227203261
| <img width="88" alt="Screenshot 2024-07-24 at 2 33 59 AM" src="https://github.com/user-attachments/assets/3c4ed43a-7a99-4910-8ad1-9322e22a96ab"> | <img width="76" alt="Screenshot 2024-07-24 at 2 34 45 AM" src="https://github.com/user-attachments/assets/6fd122da-d25f-408e-b756-3b88b67d44f0"> |
| <img width="111" alt="Screenshot 2024-07-24 at 2 34 26 AM" src="https://github.com/user-attachments/assets/be2d1af8-b556-417d-9273-bb67da2e4d25"> | <img width="102" alt="Screenshot 2024-07-24 at 2 34 38 AM" src="https://github.com/user-attachments/assets/d39172f0-cfee-4375-aaa5-19185b80260d"> |
=> `quick-mention` - Fix position

source/features/warning-for-disallow-edits.css, source/features/warning-for-disallow-edits.tsx
=> `warning-for-disallow-edits` - Restore feature

source/features/dim-bots.tsx
=> `dim-bots` - Restore feature on commit lists

source/features/mark-merge-commits-in-list.tsx
=> `mark-merge-commits-in-list` - Restore feature

source/features/rgh-dim-commits.tsx
https://github.com/refined-github/refined-github/commits/98fb24e53704b436d68f254429885fb7bef09541/source/features/bypass-checks.tsx
before:
after:
=> `rgh-dim-commits` - Restore feature

source/features/fix-no-pr-search.tsx
Fixes: #7611 
https://github.com/user-attachments/assets/3e1fa0d5-fec4-46a6-b90f-8ba6b4378723
=> `fix-no-pr-search` - Restore feature

source/features/fix-no-pr-search.tsx
close: #7616 
https://github.com/user-attachments/assets/ad7c9370-0a34-49a8-bc96-62357cb6fa56
=> `fix-no-pr-search` - Enable on global PR list

source/features/default-branch-button.tsx
- Reverts refined-github/refined-github#7623
- Closes https://github.com/refined-github/refined-github/issues/7098
- Opens https://github.com/refined-github/refined-github/issues/7618
=> Revert "`default-branch-button` - Restore feature in sticky header"

source/features/previous-version.tsx
- Fixes https://github.com/refined-github/refined-github/issues/7540
https://github.com/refined-github/refined-github/blob/main/source/background.ts
=> `previous-version` - Show on mobile

package.json, source/features/night-not-found.css, source/refined-github.css
- Fixes https://github.com/refined-github/refined-github/issues/7586
https://github.com/fregante-404
https://github.com/fregante/404
=> `night-not-found` - Restore feature

source/features/list-prs-for-file.tsx
- Fixes https://github.com/refined-github/refined-github/issues/7423
- Fixes https://github.com/refined-github/refined-github/issues/6579
https://github.com/refined-github/sandbox/edit/6619/6619
=> `list-prs-for-file` - Restore on File Edit view

source/features/list-prs-for-file.tsx
- Fixes https://github.com/refined-github/refined-github/issues/7595
https://github.com/refined-github/sandbox/blob/6619/6619
=> `list-prs-for-file` - Hide extra triangle

source/features/update-pr-from-base-branch.tsx, source/github-helpers/get-pr-info.ts
- Fixes https://github.com/refined-github/refined-github/issues/7478
- Fixes https://github.com/refined-github/refined-github/issues/7631
PRs to repos without write access, find one among your own PRs here:
https://github.com/pulls?q=is%3Apr+is%3Aopen+author%3A%40me+archived%3Afalse+-user%3A%40me
For me it's: https://github.com/sindresorhus/grunt-footer/pull/2
=> `update-pr-from-base-branch` - Enable on non-own repos

package.json, source/features/mark-private-orgs.tsx, source/features/mark-private-repos.css
- Closes https://github.com/refined-github/refined-github/issues/7585
=> Small fixes

source/helpers/selector-observer.tsx
Features like `mark-private-orgs` only need to run once, but the selector observer is still useful to show the feature without having to wait for DOM ready.
I think this is a good compromise, it also matches element-ready: https://github.com/sindresorhus/element-ready?tab=readme-ov-file#stopondomready
=> Meta: Add some selection-observer helpers

.github/ISSUE_TEMPLATE/1_bug_report.yml
Mentioned in https://github.com/refined-github/refined-github/issues/7231
=> Add required "token" checkbox when reporting bugs

source/features/fit-textareas.tsx
- Might fix #7664 
https://github.com/refined-github/refined-github/issues/7664
Demo of reloading:
=> `fit-textareas` - Improve Copilot compatibility

source/features/extend-conversation-status-filters.tsx, source/features/hide-issue-list-autocomplete.tsx, source/features/keyboard-navigation.tsx, source/features/linkify-user-edit-history-popup.tsx, source/features/more-conversation-filters.tsx, source/features/no-duplicate-list-update-time.tsx, source/features/stop-redirecting-in-notification-bar.tsx, source/features/submission-via-ctrl-enter-everywhere.tsx
Starting PR for https://github.com/refined-github/refined-github/issues/7656
=> Meta: Add more test URLs

source/features/dim-bots.tsx, source/features/mark-merge-commits-in-list.tsx, source/features/tags-on-commits-list.tsx
Closes:  #7682
https://github.com/typed-ember/ember-cli-typescript/commits/master?after=5ff0c078a4274aeccaf83382c0d6b46323f57397+174
=> `tags-on-commits-list` + `dim-bots` - Restore features

source/features/suggest-commit-title-limit.css, source/features/suggest-commit-title-limit.tsx
Fixes https://github.com/refined-github/refined-github/pull/7428#issuecomment-2290952228
https://github.com/refined-github/refined-github/compare/main...karlhorky:refined-github:test/bun?expand=true
=> `suggest-commit-title-limit` - Enable on compare pages

source/features/toggle-files-button.tsx
Before:
https://github.com/user-attachments/assets/07356d10-a7a5-42b3-9bee-48e3f79e285f
After:
https://github.com/user-attachments/assets/3218ba5e-dcd8-4283-868f-5b2b84c6350c
=> `toggle-files-button` - Improve loading layout

package-lock.json, package.json
- Fixes https://github.com/refined-github/refined-github/issues/7688
- Includes https://github.com/fregante/webext-options-sync/pull/76
=> Allow options export/import on GitHub Enterprise

source/features/action-used-by-link.tsx
https://github.com/marketplace/actions/title-replacer
https://github.com/user-attachments/assets/cd0cb81a-49de-4024-b5b3-e3999d244dd3
=> `action-used-by-link` - Prevent duplicates on back button

source/features/suggest-commit-title-limit.tsx, source/features/sync-pr-commit-title.tsx, source/github-helpers/get-next-conversation-number.ts, source/github-helpers/index.ts
Fixes https://github.com/refined-github/refined-github/pull/7689#issuecomment-2304519269
https://github.com/refined-github/refined-github/compare/main...karlhorky:refined-github:test/bun?expand=true
=> `suggest-commit-title-limit` - Fix length limit on new PRs

source/features/quick-review.tsx, source/features/rgh-improve-new-issue-form.tsx, source/github-helpers/api.ts, source/github-helpers/github-token.ts, source/options-storage.ts
Fixes issue highlighted by Rollup in https://github.com/refined-github/refined-github/pull/7472
And continues #7231, for fun
https://github.com/user-attachments/assets/df421dfe-db2c-4369-b9a4-838388d8c064
=> Avoid cyclic dependency in token code

source/features/toggle-files-button.tsx
closes: #7737 
https://github.com/user-attachments/assets/eb818ee8-12c3-4c57-b1c3-2370b9d1531f
=> `toggle-files-button` - Avoid duplicates

source/features/extend-conversation-status-filters.tsx
Related with: https://github.com/refined-github/refined-github/issues/5871 
before:
https://github.com/user-attachments/assets/12c51cd9-aadd-4e13-bfa0-c7fd1e1a1e1a
after:
https://github.com/user-attachments/assets/83c43900-51d7-4f5a-af6d-2b781f4bf5a8
=> `extend-conversation-status-filters` - Improve reliability

source/helpers/feature-utils.ts
=> Fix options opening on Safari iOS

package-lock.json, package.json
- Fixes  https://github.com/refined-github/refined-github/issues/7745
- Includes https://github.com/refined-github/shorten-repo-url/pull/57
- Will continue in https://github.com/refined-github/shorten-repo-url/pull/61
https://github.com/refined-github/refined-github/issues/7745
=> `shorten-links` - Improve CJK links support

source/features/resolve-conflicts.tsx
- Fixes https://github.com/refined-github/refined-github/issues/7767
https://github.com/refined-github/sandbox/pull/82/conflicts
=> `resolve-conflicts` - Restore feature

package-lock.json, package.json
- Fixes https://github.com/refined-github/refined-github/issues/7744
- Includes https://github.com/refined-github/shorten-repo-url/pull/61
=> `shorten-links` - Improve CJK and encoded URLs support

.github/workflows/test.yml
- Should fix https://github.com/refined-github/refined-github/issues/7729
=> Meta: Add ripgrep to GitHub Actions

source/features/clean-conversation-headers.tsx
Closes: #7802 
- Open PR (default branch): https://github.com/refined-github/sandbox/pull/4
- Open PR (non-default branch): https://github.com/Kenshin/simpread/pull/698
- Merged PR (same author): https://github.com/sindresorhus/refined-github/pull/3402
- Merged PR (different author): https://github.com/parcel-bundler/parcel/pull/78
- Merged PR (different author + first published tag): https://github.com/sindresorhus/refined-github/pull/3227
- Closed PR: https://github.com/sindresorhus/refined-github/pull/4141
https://github.com/user-attachments/assets/0da876ef-5448-4155-9ddc-f4b35b329d6a
=> `clean-conversation-headers` - Restore author for open PR

source/helpers/bisect.tsx
=> Drop link to deleted `Undo-unwanted-styles` wiki page

source/features/default-branch-button.css, source/features/default-branch-button.tsx
Closes: #7679 
https://github.com/refined-github/refined-github/tree/sandbox/keep-branch
=> `default-branch-button` - Highlight non default branch button

source/features/list-prs-for-file.tsx
- Follows https://github.com/refined-github/refined-github/pull/7496
- isSingleFile: https://github.com/refined-github/sandbox/blob/6619/6619
- isEditingFile: https://github.com/refined-github/sandbox/edit/6619/6619
=> `list-prs-for-file` - Simplify code

source/features/conversation-activity-filter.tsx, source/options.html, source/options.tsx
For https://github.com/refined-github/refined-github/issues/6000#issuecomment-2313192586
=> Show version in options page

source/github-helpers/selectors.ts
https://github.com/refined-github/refined-github/issues/7808#issuecomment-2363295100
https://github.com/refined-github/refined-github/commits/main/
=> `tags-on-commits` - Restore feature

source/github-helpers/github-token.ts, source/helpers/conventional-commits.ts, source/helpers/used-storage.ts, source/options.css, source/options.html, source/options.tsx, source/options/token-validation.tsx
- Like #7831 
- Related to https://github.com/refined-github/refined-github/issues/6446#issuecomment-2346322573
=> Meta: Reorganize options page code (token validation)

.github/workflows/test.yml
=> Meta: Fix Safari CI build

source/features/github-bugs.css
=>  Fix sponsor button size in mobile view

package-lock.json, package.json, source/options.css, source/options.html, source/options.tsx
- Includes https://github.com/fregante/webext-base-css/pull/17
=> Improve options page forms style across browsers

source/features/hide-issue-list-autocomplete.tsx
Closes: #7856 
https://github.com/tc39/proposal-await.ops/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen
=> `hide-issue-list-autocomplete` - Fix error on new beta view

source/options.css, source/options.html, source/options/feature-list.tsx, source/welcome.svelte
- Follows https://github.com/refined-github/refined-github/pull/7831
- Follows https://github.com/refined-github/refined-github/pull/7864
=> Improve layout of feature list in options

source/features/clean-conversation-filters.tsx
=> `clean-conversation-filters` - Fix error on project-free orgs

source/github-helpers/get-user-permission.ts, source/github-helpers/github-token.ts, source/options-storage.ts, source/options/token-validation.tsx, source/welcome.svelte
- Fixes https://github.com/refined-github/refined-github/issues/7897
- GHE token check broken by https://github.com/refined-github/refined-github/pull/7845
- Extracted from #7904
=> Fix recent token-related issues

source/features/unfinished-comments.tsx, source/github-events/on-field-keydown.tsx
- For https://github.com/refined-github/refined-github/issues/7886
https://github.com/eslint/eslint/issues/new?template=change.yml
=> `tab-to-indent` - Support new text fields

source/features/unfinished-comments.tsx
- for #7886 
- https://togithub.com/eslint/eslint/issues/19013
- https://github.com/eslint/eslint/issues/new?template=change.yml
=> `unfinished-comments` - Support new text fields

source/features/clean-rich-text-editor.css
- For #7886 
- https://togithub.com/eslint/eslint/issues/19013
- https://github.com/eslint/eslint/issues/new?template=change.yml
=> `clean-rich-text-editor` - Support new text fields

source/features/esc-to-cancel.tsx, source/github-events/on-field-keydown.tsx
- For #7886 
Part of this feature is also covered by https://github.com/refined-github/refined-github/pull/7890
- https://togithub.com/eslint/eslint/issues/19013
- https://github.com/eslint/eslint/issues/new?template=change.yml
=> `one-key-formatting` - Support new issue view

source/features/small-user-avatars.tsx
part of #7856
https://github.com/nuxt/nuxt/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen
> added after comment
=> `small-user-avatars` - Support new issue page

source/github-helpers/toast.tsx
<del>Close: 7809 </del>
BTW, as you can we only had a fade-in effect before and I found the toast component has a `Toast--animateIn` class to use. In the end, we have animate-in and animate-out.
Before:
https://github.com/user-attachments/assets/a5faa888-d3e6-4990-8213-aa05c04d953c
After:
https://github.com/user-attachments/assets/b75c34c5-d7d7-4e41-ab27-8834935651fd
=> Animate notifications

source/features/align-issue-labels.css, source/features/center-reactions-popup.css, source/features/dim-bots.css, source/features/hide-navigation-hover-highlight.css, source/features/quick-label-removal.css, source/features/reactions-avatars.css, source/features/release-download-count.css, source/features/rgh-feature-descriptions.css, source/features/scrollable-areas.css, source/features/show-associated-branch-prs-on-fork.css, source/features/suggest-commit-title-limit.css, source/github-helpers/heat-map.css
- Picks up https://github.com/refined-github/refined-github/pull/7553
- Unblocked by #7949
=> Use nested CSS

source/features/default-branch-button.tsx, source/features/hide-navigation-hover-highlight.css, source/github-helpers/group-buttons.tsx
- Closes https://github.com/refined-github/refined-github/issues/7957
https://github.com/microsoft/vscode/commits/release/1.25/
=> `default-branch-button` - Fix wrapping on mobile

package-lock.json, source/features/select-notifications.tsx
- Fixes https://github.com/refined-github/refined-github/issues/7960
=> `select-notifications` - Fix selection bug

source/features/rgh-linkify-features.tsx
https://github.com/download-directory/download-directory.github.io/issues/143
=> `rgh-linkify-features` - Support new issue view

source/features/conversation-authors.tsx
https://github.com/eslint/eslint/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen
New view:
Old view:
=> `conversation-authors` - Support new issue view

source/github-helpers/selectors.ts
part of #7856
https://github.com/download-directory/download-directory.github.io/issues/141
=> `show-names` - Support new issue view

source/features/shorten-links.tsx, source/github-helpers/dom-formatters.tsx
- For #7856 
https://github.com/download-directory/download-directory.github.io/issues/141#issuecomment-2443099561
| ------ | ------ |
| <img width="956" alt="image" src="https://github.com/user-attachments/assets/962da243-933e-49eb-b723-7644177e337c"> | <img width="992" alt="image" src="https://github.com/user-attachments/assets/f13b4387-72f2-4f0d-935c-70817d61adc3"> |
| <img width="940" alt="image" src="https://github.com/user-attachments/assets/f216ad79-d926-44a4-ae72-29e194e77111"> | <img width="937" alt="image" src="https://github.com/user-attachments/assets/6159835e-fc36-4240-a9a3-0b8f1d832bf4"> |
=> `shorten-links` - Support new issue view

source/features/emphasize-draft-pr-label.css
- For #7856 
https://github.com/download-directory/download-directory.github.io/issues?q=is%3Apr
=> `emphasize-draft-pr-label` - Support new issue view

build/__snapshots__/imported-features.json, source/features/rgh-feature-descriptions.tsx, source/features/rgh-improve-new-issue-form.tsx, source/features/rgh-token-user.tsx, source/github-helpers/api.ts, source/helpers/open-options.ts, source/helpers/open-options.tsx, source/refined-github.ts
- Closes https://github.com/refined-github/refined-github/issues/7384
Any page
=> Warn user of mismatch between token user and logged-in user 

source/options/feature-list.tsx
- Closes https://github.com/refined-github/refined-github/issues/7550
[Options page](#refined-github-options)
=> Options page: Count disabled features

source/features/conversation-activity-filter.tsx
- Fixes #7901
- Issue: https://github.com/refined-github/refined-github/issues/7901
- PR: https://github.com/refined-github/refined-github/pull/7645
=> `conversation-activity-filter` - Restore on issues

build/__snapshots__/features-meta.json, build/__snapshots__/imported-features.json, readme.md, source/features/avoid-accidental-submissions.tsx, source/features/unread-anywhere.tsx, source/github-helpers/api.ts, source/github-helpers/hotkey.tsx, source/github-helpers/toast.tsx, source/helpers/fetch-dom.ts, source/refined-github.ts
- Closes https://github.com/refined-github/refined-github/issues/7442
anywhere :)
=> `unread-anywhere` - Add feature

source/features/jump-to-conversation-close-event.tsx, source/features/netiquette.tsx
- Part of https://github.com/refined-github/refined-github/issues/7856
- Completed: https://github.com/download-directory/download-directory.github.io/issues/145#event-15094763473
- Not planned: https://github.com/download-directory/download-directory.github.io/issues/141
- Slightly blocks https://github.com/refined-github/refined-github/pull/8010
- Slightly dependent on https://github.com/refined-github/github-url-detection/pull/200#issuecomment-2457787195
=> `jump-to-conversation-close-event` - Support new issue view

source/features/netiquette.tsx, source/features/quick-comment-hiding.tsx, source/features/rgh-netiquette.tsx, source/github-helpers/selectors.ts, source/helpers/loose-parse-int.ts
- Follows https://github.com/refined-github/refined-github/pull/7889
- Closes https://github.com/refined-github/refined-github/issues/7886
- Blocked by https://github.com/refined-github/refined-github/pull/8011
https://togithub.com/eslint/eslint/issues/3565#react-issue-comment-composer
https://togithub.com/download-directory/download-directory.github.io/issues/41
=> `netiquette` - Support new text fields

source/features/html-preview-link.tsx
Closes: #7860 
https://github.com/refined-github/refined-github/blob/main/source/welcome.html
=> `html-preview-link` - Restore feature

source/github-helpers/selectors.ts
- part of https://github.com/refined-github/refined-github/issues/7856
https://github.com/eslint/eslint/issues/18391
before:
after:
=> `show-names` - Extend support of new issue view

source/features/jump-to-conversation-close-event.tsx
https://github.com/refined-github/refined-github/issues/3076
=> `rgh-netiquette` - Fix console error on open PRs and issues

source/options.css, source/options.html, source/options/token-validation.tsx
=> Adjust spacing/borders in options

source/features/mobile-tabs.css
- Closes https://github.com/refined-github/refined-github/issues/7725
Here
=> `mobile-tabs` - Also compact PR tabs

source/features/cross-deleted-pr-branches.css
https://github.com/refined-github/refined-github/pull/7987
Before:
After:
=> `cross-deleted-pr-branches` - Also dim link

source/features/more-dropdown-links.tsx
Close: #7806 
https://github.com/user-attachments/assets/aa4f0746-027d-40e6-b411-46629850fb38
=> `more-dropdown-links` - Fix duplicates on security tab

source/features/status-subscription.css, source/features/status-subscription.tsx
Close: #7800 
https://github.com/refined-github/refined-github/issues/7800
=> `status-subscription` - Improve contrast

source/features/table-input.css, source/features/table-input.tsx
- follows https://github.com/refined-github/refined-github/pull/8041
https://togithub.com/eslint/eslint/issues/17733
=> `table-input` - Fix sidebar overlap; Further improve performance

source/github-events/on-pr-merge.ts
Close: #8055 
Any PR you can merge
https://github.com/user-attachments/assets/8a68f5a6-ef96-4998-9c38-f57abc5dd74d
=> `pr-branch-auto-delete` - Restore feature

source/features/mobile-tabs.css
https://github.com/refined-github/refined-github/pull/8033
=> `mobile-tabs` - Further tighten spacing

build/__snapshots__/features-meta.json, readme.md, source/features/unread-anywhere.tsx, source/github-helpers/hotkey.tsx
- Fixes https://github.com/refined-github/refined-github/issues/8060
=> `unread-anywhere` - Change shortcut to `g u` to avoid conflicts

eslint.config.js, source/feature-manager.tsx, source/features/close-out-of-view-modals.tsx, source/features/command-palette-navigation-shortcuts.tsx, source/features/embed-gist-via-iframe.tsx, source/features/hide-user-forks.tsx, source/features/improve-shortcut-help.tsx, source/features/linkify-user-location.tsx, source/features/new-repo-disable-projects-and-wikis.tsx, source/features/parse-backticks.tsx, source/features/profile-hotkey.tsx, source/features/reload-failed-proxied-images.tsx, source/features/rgh-token-user.tsx, source/features/selection-in-new-tab.tsx, source/features/shorten-links.tsx, source/features/small-user-avatars.tsx, source/features/unread-anywhere.tsx, source/features/useful-not-found-page.tsx
- Fixes https://github.com/refined-github/refined-github/issues/8064
=> Don't unload persistent features on page change

source/feature-manager.tsx, source/features/close-as-unplanned.tsx, source/features/close-out-of-view-modals.tsx, source/features/dim-bots.tsx, source/features/improve-shortcut-help.tsx, source/features/open-all-notifications.tsx, source/features/pr-branch-auto-delete.tsx, source/github-helpers/api.ts, source/helpers/feature-helpers.ts, source/helpers/fetch-dom.ts
This finally drops some general utilities from the manager (which has side effects and is already pretty long)
Related improvements:
- https://github.com/refined-github/refined-github/pull/8073
=> Extract feature helpers

source/feature-manager.tsx
Dropping the awkward `details`, `InternalRunConfig`, `setupPageLoad`/`maybeRun`, …
=> Make init logic more linear

source/features/extend-diff-expander.css, source/features/extend-diff-expander.tsx
part of #7808
https://github.com/refined-github/sandbox/commit/54c10fe670779eab43b6a18b7fb06e51dd7050af
https://github.com/user-attachments/assets/be7e996c-0965-473c-9501-6f943c979eb1
=> `extend-diff-expander` - Support new commit view

source/features/scrollable-areas.css
Part of #7808 
https://github.com/refined-github/sandbox/commit/54c10fe670779eab43b6a18b7fb06e51dd7050af#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R2
=> `scrollable-areas` - Support new commit view

source/features/clean-pinned-issues.css, source/features/clean-repo-sidebar.css, source/features/hide-low-quality-comments.css, source/features/link-to-compare-diff.css, source/features/night-not-found.css, source/features/no-unnecessary-split-diff-view.css, source/features/rgh-feature-descriptions.css, source/features/scrollable-areas.css, source/features/sticky-csv-header.css
- Part of https://github.com/refined-github/refined-github/issues/6665
- Follows #7950
=> Meta: Nested CSS

source/github-helpers/selectors.ts
- Part of #7808 
https://github.com/refined-github/sandbox/commit/54c10fe670779eab43b6a18b7fb06e51dd7050af#r148774860
=> `show-names` - Suppot new commit view

source/features/clean-conversation-headers.css
Close: #8101 
https://github.com/sindresorhus/serialize-error/issues/48
=> `clean-conversation-headers` - Fix hidden fixed link

source/features/clean-conversation-headers.css, source/features/extend-diff-expander.css, source/features/status-subscription.css
- Fixes https://github.com/refined-github/refined-github/issues/8091
=> Fix missing colors on GitHub Enterprise

source/features/clear-pr-merge-commit-message.tsx
- Fixes https://github.com/refined-github/refined-github/issues/6611
- Reverts https://github.com/refined-github/refined-github/pull/6330
while fixing the duplicate message
Any open PR, like this one
=> `clear-pr-merge-commit-message` - Clear at every opening

source/features/pr-branch-auto-delete.tsx, source/options/feature-list.tsx
- For https://github.com/refined-github/refined-github/issues/6000#issuecomment-2475492108
Options page
=> Options: place broken features after user-disabled feature

source/options.html
- For https://github.com/refined-github/refined-github/issues/8058
<a name="options-page-link">options page</a>
=> Add debug link to open welcome page

source/helpers/hotfix.tsx, source/options.html, source/options.tsx
- Closes #6383 
- Extracted from #8126
=> Add button to refresh hotfixes

package-lock.json, package.json, source/options.html, source/options.tsx, source/options/toggle-all.ts
- Moves the copy into a dedicated and hidden section
- Shows the section automatically when a large number of features has already been disabled
=> Options: Move "Toggle all" section

rollup.config.js, source/feature-manager.tsx, source/features/conversation-activity-filter.tsx, source/features/jump-to-conversation-close-event.tsx, source/features/suggest-commit-title-limit.tsx, source/helpers/abortable-classname.ts
- closes https://github.com/refined-github/refined-github/issues/7922
https://github.com/refined-github/refined-github/pull/7854
=> `suggest-commit-title-limit` - Disable on merged PRs

rollup.config.js, source/manifest.json, source/options.css
Fixes an issue introduced by https://github.com/refined-github/refined-github/pull/8119 due to https://github.com/parcel-bundler/lightningcss/issues/831 and then improves the colors.
=> Options: Fix colors 

build/features.test.ts, source/feature-manager.tsx, source/features/align-issue-labels.css, source/features/align-issue-labels.tsx, source/features/clean-pinned-issues.css, source/features/clean-pinned-issues.tsx, source/features/clean-rich-text-editor.css, source/features/clean-rich-text-editor.tsx, source/features/emphasize-draft-pr-label.css, source/features/hide-diff-signs.css, source/features/hide-diff-signs.tsx, source/features/no-unnecessary-split-diff-view.css, source/features/no-unnecessary-split-diff-view.tsx, source/features/scrollable-areas.css
- Closes https://github.com/refined-github/refined-github/issues/7944
=> Faster disableable CSS features

source/features/restore-file.tsx
Closes #8108.
A pull request to a repository which you have permissions over, I guess https://github.com/refined-github/sandbox/pull/16.
=> `restore-file` - Add confirm modal

source/features/pr-notification-link.tsx, source/features/unread-anywhere.tsx
=> `unread-anywhere` - Apply `pr-notification-link` to links

source/background.ts, source/helpers/hotfix.tsx, source/helpers/isomorphic-fetch.ts
- Will properly fix https://github.com/refined-github/refined-github/issues/8142
- Fixes #8144
=> Handle hotfix loading from GitHub Pages

source/github-helpers/index.test.ts, source/github-helpers/index.ts
Closes: #8147 
- https://github.com/refined-github/refined-github/issues/4979
Before:
After:
=> `show-names` - Replace name correctly

source/features/closing-remarks.tsx, source/features/rgh-netiquette.tsx, source/github-helpers/timeline-item.tsx
- closes #8012
https://github.com/download-directory/download-directory.github.io/issues/74
=> `rgh-netiquette` - Support new views

source/features/action-pr-link.tsx
- Closes https://github.com/refined-github/refined-github/issues/7988
Any new broken features can be reported independently 
https://github.com/download-directory/download-directory.github.io/pull/146/commits
=> `action-pr-link` - Support new PR view

source/features/clear-pr-merge-commit-message.tsx
- Part of #8123 
Any open PR like this one
=> `clear-pr-merge-commit-message` - Support new PR merge box

source/github-events/on-pr-merge.ts, source/helpers/selector-observer.tsx
- For #8123 
Any open PR, like this page
Gif also shows other auto-deletion working, but that's a separate PR
=> `closing-remarks` - Support new PR merge box

source/features/pr-branch-auto-delete.tsx
- For #8123 
- Partially fixed by #8164
Any open PR, like this page
=> `pr-branch-auto-delete` - Support new PR merge box

source/github-helpers/dom-formatters.tsx
Closes #7995 
https://github.com/refined-github/refined-github/issues/7995#issuecomment-2452910826
https://github.com/refined-github/refined-github/issues/7995#issuecomment-2526797253
=> `linkify-code` - Support inline links

source/features/convert-pr-to-draft-improvements.tsx
https://github.com/refined-github/sandbox/pull/98
Before: <img width="923" alt="image" src="https://github.com/user-attachments/assets/b9d8e1f4-19bf-471e-b139-26450ff912ee" /> 
After: <img width="941" alt="image" src="https://github.com/user-attachments/assets/3265336d-f67c-4fdd-96d3-ae67b5fd3af0" />
=> `convert-pr-to-draft-improvements` - Improve style

source/features/quick-review.tsx
tiny tiny aesthetic change that I think improves things
https://github.com/refined-github/refined-github/pull/8187 (or any open PR in a repo you have write access to)
Before:
After:
=> `quick-review` - More native look

safari/app-store-description.txt
This simple change should make it easier for users to find the website link.
=> Meta: Update App Store description

source/features/sticky-sidebar.css, source/features/sticky-sidebar.tsx
Close: #7945
https://github.com/eslint/eslint/discussions/18304
https://github.com/user-attachments/assets/a5721aab-2664-4667-bebf-b3bf638629fe
=> `sticky-sidebar` - Support discussions

source/features/linkify-user-location.tsx
=> `linkify-user-location` - Support organization profile

build/__snapshots__/features-meta.json, source/features/show-names.css, source/features/show-names.tsx, source/github-helpers/index.test.ts, source/github-helpers/index.ts
Fix #8191
- RTL: https://github.com/refined-github/refined-github/issues/8191
- Bidi override case 1: https://togithub.com/FortAwesome/Font-Awesome/issues/2465
- Bidi override case 2: https://togithub.com/w3c/webdriver/issues/385#issuecomment-598407238
| | Before | After |
|--------|--------|--------|
| RTL | ![CleanShot 2025-01-07 at 18 48 22@2x](https://github.com/user-attachments/assets/2476cb3d-d231-461b-be4e-1e6ed24b81ec) | ![CleanShot 2025-01-07 at 18 48 40@2x](https://github.com/user-attachments/assets/37604174-ba6c-4b20-aa72-580c03886383) |
| Bidi override case 1 | ![CleanShot 2025-01-07 at 19 26 04@2x](https://github.com/user-attachments/assets/5d9c0c72-8efe-447f-876a-ef2e7530b605) | ![CleanShot 2025-01-07 at 19 26 28@2x](https://github.com/user-attachments/assets/a89198cc-19fb-4e …
=> `show-names` - Add support for RTL names

source/options.html, source/welcome.svelte
@fregante you forgot in f30ca4a22528e9720e23b85d4cd38f074d64b179. Maybe add comments to reference each other? Since one of them is a static HTML and a hassle to extract as a variable.
N/A
N/A
=> Update token creation link /2

source/features/quick-mention.css, source/features/quick-mention.tsx
- Part of #7856
https://github.com/download-directory/download-directory.github.io/issues/127
https://github.com/eslint/eslint/issues/8213
Normal Issue:
Locked issue:
=> `quick-mention` - Support new issue view

source/features/update-pr-from-base-branch.tsx
- Part of  #8123 
| Old | New | Test URL |
| --- | ---- | ---- |
| <img width="931" alt="image" src="https://github.com/user-attachments/assets/a42e1bf1-9d5d-400e-b777-dcb832bda82b" /> |  <img width="931" alt="image" src="https://github.com/user-attachments/assets/45da0392-fb7d-456b-a69a-50bd56085cf5" /> | PR without conflicts: https://github.com/refined-github/sandbox/pull/60 |
| <img width="932" alt="image" src="https://github.com/user-attachments/assets/d98c5866-5f92-4400-8537-3b20239c5221" /> | <img width="921" alt="image" src="https://github.com/user-attachments/assets/796c593f-aff6-40f4-b3ab-6b445043c6fe" /> | Draft PR without conflicts: https://github.com/refined-github/sandbox/pull/91 | 
| <img width="833" alt="image" src="https://github.com/user-attachments/assets/2b40027e-0603-47 …
=> `update-pr-from-base-branch` - Support new view

source/features/easy-toggle-files.tsx
#7808
https://github.com/refined-github/refined-github/commit/7b12c475a54ee32531ea4f9a548f08aea1081b83
https://github.com/user-attachments/assets/4cf494ca-a1a8-4f8b-8bce-33816c132623
=> `easy-toggle-files` - Support new commit view

source/features/selection-in-new-tab.tsx
- Part of #7856
https://github.com/user-attachments/assets/4bdece77-6cc6-40be-a9f3-57ae62a69d5c
=> `selection-in-new-tab` - Support new issue view

source/features/conversation-authors.css, source/features/conversation-authors.tsx
https://github.com/refined-github/refined-github/issues?q=sort%3Aupdated-desc%20is%3Aissue%20state%3Aclosed&page=2
=> `conversation-authors` - Update style for border clip

source/features/clear-pr-merge-commit-message.tsx
=> `clear-pr-merge-commit-message` - Restore feature

source/features/comments-time-machine-links.tsx, source/features/shorten-links.tsx, source/github-helpers/get-comment-author.ts
https://github.com/refined-github/sandbox/issues/108
=> Restore 3 features on the first comment of issues

source/features/repo-wide-file-finder.tsx
Fixes https://github.com/refined-github/refined-github/issues/8273
=> `repo-wide-file-finder` - Fix conflict with native shortcut

source/features/action-used-by-link.tsx
Close: #8255
https://github.com/marketplace/actions/urlchecker-action
=> `action-used-by-link` - Restore feature

source/features/tags-on-commits-list.tsx
https://github.com/fuma-nama/fumadocs/commits/dev/
Before:
After:
=> `tags-on-commits-list` - Improve support for multiple tags 

source/options.html
Close: #8275 
https://github.com/user-attachments/assets/0951a496-9d02-435b-af08-58c6bdb1be09
=> Options page: Don't disable all features when pressing `enter`

source/features/netiquette.tsx
Close: #8239 
https://github.com/fregante/sandbox/issues/8
https://github.com/user-attachments/assets/5cf33c68-312d-48d2-8b6a-cc3d8cbc8e15
=> `netiquette` - Switch write/preview tabs cause multiple banner

build/__snapshots__/features-meta.json, source/features/small-user-avatars.css, source/features/small-user-avatars.tsx
Close: #8218
#8218
https://github.com/user-attachments/assets/1899da15-c701-4518-8f60-3b5c09f725ad
=> `small-user-avatars` - Don't quote avatar into comment field

source/features/conflict-marker.tsx, source/github-helpers/selectors.ts
closes #8264
https://github.com/refined-github/sandbox/issues?q=conflict
=> `conflict-marker` - Add support for new issue view

source/features/clear-pr-merge-commit-message.tsx
=> `clear-pr-merge-commit-message` - Support new merge box view

source/features/open-all-notifications.css, source/features/open-all-notifications.tsx
Notifications
| | Before | After |
| ---- | ---- | ---- |
| Inbox | ![CleanShot 2025-03-10 at 09 09 34](https://github.com/user-attachments/assets/9704d9d5-e53b-4ab5-9747-6ed7a7eb78a9) |  ![CleanShot 2025-03-10 at 09 11 25](https://github.com/user-attachments/assets/28830b2f-7f47-4901-a64b-2bc81c6683f9) |
| Done | ![CleanShot 2025-03-10 at 09 09 26](https://github.com/user-attachments/assets/dce4f487-24a8-41ff-b11d-b723261826a1) | ![CleanShot 2025-03-10 at 09 11 17](https://github.com/user-attachments/assets/034e1cad-cc8b-4f05-87e3-b6f39b3c9fc1) |
=> `open-all-notifications` - Fix layout of selected button

build/__snapshots__/features-meta.json, source/features/clean-repo-filelist-actions.css, source/features/clean-repo-filelist-actions.tsx
Close #8259
https://github.com/user-attachments/assets/ae9b34c7-cd79-413b-b997-1ddf6e6c8218
=> `clean-repo-filelist-actions` - Restore feature

source/feature-manager.tsx
GitHub seems to remove the custom HTML attributes used to disable CSS features after navigation, leading to disabled CSS features being suddenly re-enabled.
Fixes #8172.
- https://github.com/pypa/pip/issues
=> Ensure disabled CSS features stay disabled after navigation

source/features/clear-pr-merge-commit-message.tsx
Close: #8346 
Any pr you can merge.
https://github.com/user-attachments/assets/59897e2a-4570-4aa8-a799-b4988278ae21
=> `clear-pr-merge-commit-message` - Restore feature in new merge box

source/features/netiquette.tsx, source/features/rgh-netiquette.tsx
It does not fix []() https://github.com/refined-github/refined-github/issues/8296 but it's a step in the right direction.
=> `rgh-netiquette` - Improve chance of it working

package-lock.json, package.json, source/features/rgh-improve-new-issue-form.tsx, source/helpers/dom-utils.ts
- Fixes https://github.com/refined-github/refined-github/issues/8352
https://github.com/refined-github/refined-github/issues/new?template=1_bug_report.yml
=> `rgh-improve-new-issue-form` - Restore feature

build/__snapshots__/features-meta.json, build/__snapshots__/imported-features.json, build/features.test.ts, eslint.config.js, readme.md, source/features/no-target-blank.tsx, source/refined-github.ts
- Replaces and closes https://github.com/refined-github/refined-github/pull/8356
- Closes https://github.com/refined-github/refined-github/issues/8349
https://github.com/refined-github/refined-github/issues/8346#event-16947543136
=> `no-target-blank` - New feature

source/features/quick-mention.tsx
Any issue
https://github.com/user-attachments/assets/17f0c5d1-32d4-4f9c-bd1d-c6ae260324ba
=> `quick-mention` - Restore feature on issues

source/features/warn-pr-from-master.tsx
https://github.com/vizlabs/PDKeychainBindingsController/compare/master...carlbrown:PDKeychainBindingsController:master
Before:
https://github.com/user-attachments/assets/d3281104-2b26-4720-85fe-4d290cb559a6
After:
https://github.com/user-attachments/assets/eadfc7b7-146e-4eef-a30d-d2928d9be2be
=> `warn-pr-from-master` - Avoid duplicate error banner

source/features/esc-to-deselect-line.tsx, source/features/github-actions-indicators.tsx, source/helpers/history.ts
- Closes https://github.com/refined-github/refined-github/issues/6443
https://github.com/refined-github/refined-github/actions
=> `github-actions-indicators` - Open dropdown on icon click

package-lock.json, package.json, source/features/update-pr-from-base-branch.tsx
- Probably fixes https://github.com/refined-github/refined-github/issues/8247
Any of your open but outdated PRs on a repo with native "update PR" button
🤷‍♂️
=> `update-pr-from-base-branch` - Try harder to avoid duplication

source/features/quick-mention.css, source/features/quick-mention.tsx
Close: #8309 
https://github.com/huggingface/transformers/pull/33962
https://github.com/user-attachments/assets/d76c36ab-796e-4207-ac86-2ebe311ce294
=> `quick-mention` - Improve feature to avoid web lagging

source/features/no-modals.tsx
Closes: #8392 
https://github.com/issues/created
https://github.com/user-attachments/assets/32ff93d0-2556-43c0-a037-5f80b9e865bd
=> `no-modals` - Support global issues page

build/prepare-safari-release.sh
- Fixes https://github.com/refined-github/refined-github/issues/8319
=> Drop support for GHE on Safari due to Safari 18.4 bug

source/features/github-bugs.css, source/refined-github.css
| ---- | ---- |
| <img src="https://github.com/user-attachments/assets/5ff1e142-9dcc-442e-b02f-8bd10ace885b" /> | <img src="https://github.com/user-attachments/assets/f93fe603-d990-4564-b63f-e4f75dd8aa1a" /> |
| <img src="https://github.com/user-attachments/assets/2531dcdb-04ce-4020-ba35-5aa276a81dba" width="500" /> | <img src="https://github.com/user-attachments/assets/26af6f67-9cbc-4520-ab6c-d4e91b7a1a0d" width="500" /> |
=> Style fill stared icon and code in commit title

source/features/repo-avatars.tsx
=> `repo-avatars` - Restore feature

.github/workflows/test.yml, biome.json, package-lock.json, package.json, source/features/clean-rich-text-editor.css, source/features/emphasize-draft-pr-label.css
=> Meta: Replace stylelint with biome

package-lock.json, package.json, source/features/no-modals.tsx
- https://github.com/orgs/RSSNext/projects/3/
https://github.com/user-attachments/assets/a83753b1-3ad1-4a4c-9daf-1713cae122fd
=> `no-modals` - Support projects

source/features/same-page-links.tsx
https://github.com/refined-github/refined-github/issues/8367
https://github.com/user-attachments/assets/2f81ba42-5a94-4c5a-9fb6-88206fa2bb5a
=> `same-page-links` - Support reference pr links in issue headers

source/features/locked-issue.tsx
Close: #8362
- Locked issue: https://github.com/refined-github/sandbox/issues/74
- Locked PR: https://github.com/refined-github/sandbox/pull/48
https://github.com/user-attachments/assets/376788dd-05d1-41ed-ac53-3ac9b7383887
=> `locked-issue` - Restore feature on issues

source/background.ts
Waiting to check if Safari 18.5 fixed it
=> Disable GHE on Safari /2

source/features/pr-first-commit-title.tsx
Closes #8491
https://github.com/chipbite/mawi-chipbite-gh/compare/feature?expand=1&body=%23%23+Checklist&title=%5BIA-334%5D%3A+Patch%3A+add+azure+check+and+install
https://github.com/user-attachments/assets/75d3f33e-9cd6-42a4-83c6-5c4478abc8d5
=> `pr-first-commit-title` - Preserve the title passed via URL

source/features/readable-title-change-events.css
- Part of https://github.com/refined-github/refined-github/issues/7856
- Issue: https://github.com/refined-github/sandbox/issues/112#event-18404386593
- PR: https://github.com/refined-github/sandbox/pull/114#event-18404427896
=> `readable-title-change-events` - Support new issue view

source/features/table-input.css
Close: #8521
Any issue or pr
| Light | Dark |
| --- | ---- |
| <img src="https://github.com/user-attachments/assets/1d4fce46-1f71-4538-b8f3-129bdce9605b" width="200" />| <img src="https://github.com/user-attachments/assets/05d15e57-1db3-4450-8f42-83f24c4d89c4" width="200" />|
=> `table-input` - Fix colors

source/features/show-names.tsx
Close: #8518 
https://github.com/refined-github/refined-github/issues/8491#issuecomment-3017841452
=> `show-names` - Fix spacing

source/features/sticky-notifications-actions.css
fixes #8541
the whole github ui feels much snappier now
https://github.com/refined-github/sandbox/pulls
=> `sticky-notifications-actions` - Improve performance

source/features/restore-file.tsx
- Closes #8280 
https://github.com/refined-github/refined-github/pull/8570/files
=> `restore-file` - Ask for commit title

source/features/new-repo-disable-projects-and-wikis.tsx
For: #8582 
https://github.com/new?use_v2_form=true
<table>
<tr>
<td>
Classic
<td>
New
<tr>
<td>
<td>
</table>
=> `new-repo-disable-projects-and-wikis` - Support new view

package-lock.json, package.json
https://github.com/cunneen/vscode-plist/issues/10
| Before            | After             |
|-------------------|-------------------|
| <img width="1644" height="141" alt="PixelSnap 2025-08-03 at 23 19 46@2x" src="https://github.com/user-attachments/assets/5d63278f-9b9f-41f8-b125-be5bc3fe0cc3" /> | <img width="1644" height="141" alt="PixelSnap 2025-08-03 at 23 20 36@2x" src="https://github.com/user-attachments/assets/0859b68d-0460-4b96-a767-020cde9ef64a" /> |
=> `linkify-code` - Parse references case-insensitively

source/features/conversation-authors.css, source/features/small-user-avatars.css
- Fixes https://github.com/refined-github/refined-github/issues/8396
https://github.com/refined-github/refined-github/pulls
=> `small-user-avatars` Fix misalignment of date/time

source/features/conversation-authors.tsx, source/features/mark-private-orgs.tsx, source/features/profile-hotkey.tsx, source/features/quick-mention.tsx, source/features/quick-review.tsx, source/features/reactions-avatars.tsx, source/features/rgh-token-user.tsx, source/features/show-names.tsx, source/features/show-open-prs-of-forks.tsx, source/features/user-local-time.tsx, source/features/user-profile-follower-badge.tsx, source/github-helpers/index.ts
- Fixes https://github.com/refined-github/refined-github/issues/8408
=> Fix "token is for a different user" false positive

source/features/unread-anywhere.tsx
=> `unread-anywhere` - Restore on notifications page

package-lock.json, package.json, source/features/show-names.tsx
Resolve #8588 
https://togithub.com/typescript-eslint/tsgolint/pull/2
| Before | <img width="409" height="142" alt="Screenshot 2025-09-07 at 2 24 44 AM" src="https://github.com/user-attachments/assets/8c758055-b708-4215-b799-c43bc75bdc43" /> |
| After | <img width="408" height="136" alt="Screenshot 2025-09-07 at 2 24 56 AM" src="https://github.com/user-attachments/assets/0eeed735-219e-4b7c-a032-65ab8b55b9c1" /> |
=> `show-names` - Strip emojis

source/features/conflict-marker.tsx, source/github-helpers/selectors.ts
ref: #8664
https://github.com/CherryHQ/cherry-studio/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen
Before
After
=> `conflict-marker` - Remove feature for repo issue list
