- source/features/rgh-linkify-features.tsx
- source/github-helpers/index.ts
It should linkify the feature in the title on this page:
- https://github.com/refined-github/sandbox/pull/14
> Apply `rgh-linkify-features` to all RGH repos

- source/features/hide-tips.css
- source/refined-github.ts
- Closes https://github.com/refined-github/refined-github/issues/4574
I don’t think it's worth hiding these tips. GitHub’s interface is way more complex than when this feature was added, so hiding "all tips" to save space is a uphill battle that does not help new (and old) GitHub users.
> Drop `hide-tips` feature

- source/features/create-release-shortcut.tsx
- source/features/pagination-hotkey.tsx
- source/features/pull-request-hotkeys.tsx
- source/github-helpers/index.test.ts
- source/github-helpers/index.ts
- Fixes https://github.com/refined-github/refined-github/issues/5555
1. Go to [`1bb5e36` (#5422)](https://github.com/refined-github/refined-github/pull/5422/commits/1bb5e36ce3734a045c5e4aaeeba6e0d29d381789)
2. Maybe reload the page
3. Press N; it works
4. Press N again; gone
> Ensure that Refined GitHub preserves existing shortcuts

- source/features/linkify-code.tsx
- source/features/restore-file.tsx
- Closes https://github.com/refined-github/refined-github/issues/5606
1. Open any PRs in https://github.com/refined-github/refined-github/pulls
2. Go to Files tab
3. Look for "Restore file"
https://user-images.githubusercontent.com/1402241/169457069-b05f0a28-3350-4a19-9f0d-5903808effd9.mov
> Ensure `restore-file` appears after navigating to the Files tab

- source/features/quick-repo-deletion.tsx
- Closes https://github.com/refined-github/refined-github/issues/5369
Gotta delete one of your own forks
> Add link to the upstream repo after `quick-repo-deletion`

- source/features/rgh-feature-descriptions.tsx
- Yes: https://github.com/refined-github/refined-github/blob/main/source/features/show-names.css
- No (CSS only): https://github.com/refined-github/refined-github/blob/main/source/features/clean-commit-form.css
<table>
<tr>
<td><img width="509" alt="Screen Shot 20" src="https://user-images.githubusercontent.com/1402241/169679051-fb9344a2-5636-4fa4-a7f4-8aeb6593f447.png">
<td>🔗➡️
<td><img width="512" alt="Screen Shot 21" src="https://user-images.githubusercontent.com/1402241/169679047-d65a2862-290a-43d9-baac-22eb32cc6463.png">
</table>
> Meta: Add link to TSX file when looking at CSS feature 

- source/features/toggle-files-button.css
- source/features/toggle-files-button.tsx
- Fixes https://github.com/refined-github/refined-github/issues/5524
- Fixes https://github.com/refined-github/refined-github/issues/4402
cc @sideshowbarker because this issue was reported in https://github.com/refined-github/refined-github/issues/4402
1. Go to https://github.com/refined-github/refined-github
2. Hide files
3. Refresh the page
- The notice only appears when the list is hidden automatically so the user doesn't forget about it
- The notice is gone after the first interaction
- The notice is only clickable because the user might click it, but we don't want to actually show a hand because they should prefer clicking the actual button instead
https://user-images.githubusercontent.com/1402241/169680332-6b02c852-be43-44b9-a01a-a7c634aa7e02.mov
> Make `toggle-files-button` unforgettable

- source/features/prevent-link-loss.tsx
- source/github-helpers/prevent-link-loss.test.ts
- source/github-helpers/prevent-link-loss.ts
- Fixes https://github.com/refined-github/refined-github/issues/5466
```
https://github.com/eslint/eslint/discussions/15898?sort=new#discussion-4086661
https://github.com/eslint/eslint/discussions/15898?sort=new#discussioncomment-2787915
```
https://github.com/eslint/eslint/discussions/15898?sort=new#discussion-4086661
https://github.com/eslint/eslint/discussions/15898?sort=new#discussioncomment-2787915
[eslint/eslint#15898](https://github.com/eslint/eslint/discussions/15898?sort=new)#discussion-4086661
[eslint/eslint#15898 (comment)](https://github.com/eslint/eslint/discussions/15898?sort=new#discussioncomment-2787915)
[eslint/eslint#15898 (comment)](https://github.com/eslint/eslint/discussions/15898?sort=new#discussion-4086661)
[eslint/eslint#15898 …
> `prevent-link-loss` for more discussion URLs

- source/features/dim-bots.tsx
- source/manifest.json
- Fixes https://github.com/refined-github/refined-github/issues/5386
@kidonng @cheap-glitch can you think of any more static URLs that we can exclude this way?
```
// https://github.com/login <-- nothing runs
// https://github.com/logins <-- works as usual
```
> Don't run Refined GitHub on login pages

- source/features/enable-file-links-in-compare-view.tsx
- source/features/linkify-code.tsx
Follow-up of https://togithub.com/refined-github/refined-github/pull/5641
1. Go to https://togithub.com/refined-github/refined-github/pull/5658
2. Reload the page and click on the "Files" tab
3. The link should be clickable (`linkify-code`) & the URLs in the file dropdown should point to the branch (`enable-file-links-in-compare-view`)
> Ensure all features appears after navigating to the "Files" tab

- source/features/github-bugs.css
Makes the (un)subscribe button appear correctly for gists.
---
1. Does this PR close/fix an existing issue?
Closes #5663 
2. What pages does this PR affect? Include some REAL URLs where you tested the code
Gist pages, ex. https://gist.github.com/ajmeese7/1eb7178a9cc7284e8627316b475e03dd
3. If applicable, add demonstrative screenshots or gifs
Before:
After:
> Fix misalignment of header buttons on Gist and during page load

- source/features/forked-to.tsx
There is a gap between the fork button of a GitHub repository and the forked-to button added to the page from refined-github. This PR removes that gap, making it look neater.
Before
After
Tested on the [refined-github](https://github.com/refined-github/refined-github) repository after making a fork.
> Fix `forked-to` spacing

- .xo-config.json
- source/features/batch-mark-files-as-viewed.tsx
- source/features/collapsible-content-button.tsx
- source/features/convert-pr-to-draft-improvements.tsx
- source/features/file-finder-buffer.tsx
- source/features/index.tsx
- source/features/infinite-scroll.tsx
- source/features/keyboard-navigation.tsx
- source/features/open-all-notifications.tsx
- source/features/prevent-link-loss.tsx
- source/features/quick-comment-hiding.tsx
- source/features/quick-label-removal.tsx
- source/features/quick-review-comment-deletion.tsx
- source/features/reactions-avatars.tsx
- source/features/restore-file.tsx
- source/features/select-notifications.tsx
- source/features/show-whitespace.tsx
- source/features/sticky-sidebar.tsx
- source/features/table-input.tsx
- source/features/toggle-everything-with-alt.tsx
- source/features/toggle-files-button.tsx
- source/features/update-pr-from-base-branch.tsx
- source/features/wait-for-checks.tsx
- source/github-events/on-new-comments.ts
- source/globals.d.ts
Follow-up of #5654 
1. Make `Deinit` actually useful
2. Allow it to be an array
3. Enable `no-redundant-type-constituents` lint rule
> Improve `Deinit` type

- source/features/mark-private-orgs.tsx
I was a bit surprised to see an org still marked as private on my profile a week after I set it to public. Apparently this was missed by https://github.com/refined-github/refined-github/issues/3302. One day seems reasonable.
Also it would be nice to have a way to manually invalidate the cache for a given feature.
> Reduce `mark-private-orgs` cache validity

- source/features/reactions-avatars.tsx
Fixes #5698 
* [Issue comments](https://github.com/refined-github/refined-github/issues/3136)
* [PR comments, reviews & review comments](https://togithub.com/refined-github/refined-github/pull/5687)
* [Discussion replies](https://github.com/github-community/community/discussions/18153) (not the first post, this likely needs specific logic to be fix since the whole comment gets replaced on load & when a reaction is added/removed)
**Before**
**After**
> Restore `reaction-avatars` feature

- source/features/file-finder-buffer.tsx
- source/features/index.tsx
- source/github-helpers/turbo-events-polyfill.ts
- source/globals.d.ts
- Closes #5719 
@refined-github/maintainers please test because I'd like to release a new version within a few hours
https://user-images.githubusercontent.com/1402241/175499367-6c01e4c3-7317-4cbf-8d57-dcf9c7e003a1.mov
> Fix ajax navigation detection

- source/features/sticky-file-header.css
Broken by GitHub's Pull Request File Tree feature added a while ago.
https://github.com/refined-github/refined-github/commit/1d9dd9f0208c327351512beb6d6a22279bc47807
https://user-images.githubusercontent.com/44045911/175102994-8b4e0eb2-1229-4d26-bc69-28f2c67cc995.mov
---
I would really like to add https://github.com/kidonng/cherry/commit/997ccdf5bd36f4f888622d5c5a06426da81509ab as well, since that's pretty much the only place left with no sticky file header (and technically speaking, GitHub already enabled it for markup i.e. Markdown files).
---
P.S. it's funny GitHUb pushed a bug when I'm working on this
> Fix `sticky-file-header` on commits

- package-lock.json
- package.json
- source/features/comment-fields-keyboard-shortcuts.tsx
- source/globals.d.ts
1. Leave a comment here
2. Press `cmd-up` 
Expected: nothing happens
Actual: the comment you left becomes editable
n/a
> Don't activate `comment-fields-keyboard-shortcuts` with `cmd-⬆️`

- source/features/user-local-time.tsx
- Closes #5699
(In case its you that viewing the PR, I put several accounts here)
- @fregante (sorry for the ping)
- @yakov116 (sorry for the ping)
- @mangkoran
> Restore `user-local-time`

- source/features/file-finder-buffer.tsx
- source/features/index.tsx
- source/github-helpers/turbo-events-polyfill.ts
- Fixes https://github.com/refined-github/refined-github/issues/5738
Here's the sequence again:
Generated via
```js
['turbo:before-cache',
'turbo:before-fetch-request',
'turbo:before-fetch-response',
'turbo:before-render',
'turbo:before-stream-render',
'turbo:before-visit',
'turbo:click',
'turbo:frame-load',
'turbo:frame-render',
'turbo:load',
'turbo:reload',
'turbo:render',
'turbo:submit-end',
'turbo:submit-start',
'turbo:visit',
'pjax:start',
'pjax:end',
'pjax:complete',
'pjax:error',].map(x => document.addEventListener(x, e => console.log(x)))
```
> Fix duplication of features

- source/refined-github.css
Closes #5740
Adds the following css to restrict image blob sizes:
```css
div[data-target='readme-toc.content'] div.blob-wrapper img {
max-width: 100%;
}
```
https://github.com/KatsuteDev/Mal4J/blob/main/assets/banner-sq.png
> Fit large images in the window when viewing single files

- source/features/sticky-file-header.css
- Follows https://github.com/refined-github/refined-github/pull/5717
https://github.com/refined-github/refined-github/pull/5460/files
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
https://github.com//refined-github/refined-github/compare/22.2.13...22.2.22#files_bucket
https://github.com/refined-github/refined-github/commit/1d9dd9f0208c327351512beb6d6a22279bc47807
https://github.com/refined-github/refined-github/edit/main/readme.md
https://github.com/refined-github/refined-github/blame/243e51d786e4771d313091b94cec826ff86becc9/source/features/index.tsx#L326-L327
> Fix `sticky-file-header` positioning

- source/features/use-first-commit-message-for-new-prs.tsx
- Fixes https://github.com/refined-github/refined-github/issues/5694
Missing:
https://github.com/refined-github/sandbox/compare/linked-commit-title?expand=1
https://github.com/refined-github/sandbox/compare/rendered-commit-title?expand=1
> `use-first-commit-message-for-new-prs` Support formatted commits

- source/features/index.tsx
- Closes #5751 
1. Open https://github.com/refined-github/refined-github/issues
2. Click on the "Closed" filter
3. Go back and forth
4. Click on the "Code" tab
5. Go back and forth
5. Open a folder
5. Go back and forth
> Avoid duplicate features on history navigation

- readme.md
- source/features/linkify-user-labels.tsx
- source/github-helpers/get-comment-author.ts
- source/refined-github.ts
- Closes https://github.com/refined-github/refined-github/issues/4362
Bot PR
https://github.com/webpack/webpack/pull/15926#issue-1264092372
Bot comment
https://github.com/webpack/webpack/pull/15926#issuecomment-1149371743
Bot commented on behalf of
https://github.com/webpack/webpack/pull/15926#issuecomment-1170670173
Member review
https://github.com/refined-github/refined-github/pull/5721#pullrequestreview-1018226910
Contributor review comment
https://github.com/refined-github/refined-github/pull/5691#discussion_r895191327
Contributor review second comment
https://github.com/refined-github/refined-github/pull/5691#discussion_r895192800
Contributor review second comment in Files tab
https://github.com/refined-github/refined-github/pull/2667/files#r366433031
> Add `linkify-user-labels` feature

- source/features/clean-repo-tabs.tsx
- source/features/more-dropdown-links.tsx
- source/features/releases-tab.tsx
- closes https://github.com/refined-github/refined-github/issues/5781
Any repo page
> Disable broken `more-dropdown-links` on mobile

- source/features/first-published-tag-for-merged-pr.tsx
- source/github-helpers/banner.tsx
- Follows #5769 
- Released PR: https://github.com/refined-github/refined-github/pull/5752
- Unreleased PR: https://github.com/refined-github/sandbox/pull/23
> Fix `first-published-tag-for-merged-pr` wrapping and wording

- source/features/latest-tag-button.tsx
1. Use compare icon, not commit/diff: https://github.com/pixiebrix/pixiebrix-extension/compare/main
2. Drop useless indicator: if we show the compare link, then it's "behind"; Saying "I don't know how behind" isn't necessary
- 12 commits: https://github.com/webpack/webpack
- Undeterminable: https://github.com/microsoft/typescript
> Polish `latest-tag-button`

- readme.md
- source/features/hide-repo-badges.css
- source/features/hide-repo-badges.tsx
- source/refined-github.ts
As mentioned in https://github.com/refined-github/refined-github/issues/5546, it doesn't work and it became counterproductive with `repo-avatars` in #5778
> Drop `hide-repo-badges` feature

- source/features/preview-hidden-comments.css
- source/features/preview-hidden-comments.tsx
- Fixes https://github.com/refined-github/refined-github/issues/5750
https://github.com/refined-github/refined-github/issues/5546
Mobile fixed:
Desktop unaffected:
> Fix `preview-hidden-comments` overflow on mobile

- .github/workflows/test.yml
- Re: https://github.com/refined-github/refined-github/pull/5282#issuecomment-1178651790
Total time: 41s + 53s (no windows build dependency)
I'm not sure this is easily feasible other than by manually splitting the `matrix`
Total time: 1m20s + 53s
Total time: 1m49s
> Meta: Improve CI speed

- package-lock.json
- package.json
- source/features/rgh-sponsor-button.tsx
- source/features/set-default-repositories-type-to-sources.tsx
- source/features/show-user-top-repositories.tsx
- source/features/user-local-time.tsx
- source/features/user-profile-follower-badge.tsx
- source/github-helpers/index.ts
Part of #5356 (do I even remember that)
First thing to know: query strings (e.g. `sort=stargazers`) have no effect on private profiles.
- `rgh-sponsor-button`: I'm not sure if users in the program can make their profile private, but there probably won't be a sponsor button there
- `set-default-repositories-type-to-sources`: relies on query strings, so it doesn't work for the repositories tab. There's no organization listed either.
- `show-user-top-repositories`: relies on query strings; "popular repositories" element doesn't exist.
- `user-local-time`: can't get their events/commits
- `user-profile-follower-badge`: can't get their followers
https://github.com/Centril
N/A
> Skip some features on private user profiles

- source/features/linkify-user-location.tsx
Well, technically speaking not really a bug, since this type of navigation used to not exist.
Also included style fixes from [`08f6678` (#5113)](https://github.com/refined-github/refined-github/pull/5113/commits/08f667824863fffd935bd62befb5beb8d8e95217) (or dare I say, #5142)
https://github.com/cheap-glitch
Before:
https://user-images.githubusercontent.com/44045911/178342110-ed9cc8ce-ab7c-4cbb-bca7-74b8190e6164.mov
After:
https://user-images.githubusercontent.com/44045911/178342127-bdf33db9-2cf6-4440-a46c-e146eef61c44.mov
> Restore `linkify-user-location` on ajax navigation

- source/features/open-issue-to-latest-comment.tsx
Related to https://github.com/refined-github/refined-github/issues/5813 but it doesn't fix it.
The selector was selecting the "mobile" links as well, pointing them to the bottom of the page.
- https://github.com/refined-github/refined-github/issues?q=+comment+in%3Atitle
> Fix link selection in `open-issue-to-latest-comment`

- source/features/update-pr-from-base-branch.tsx
- source/github-helpers/api.ts
- source/github-helpers/get-pr-info.ts
- Close https://github.com/refined-github/refined-github/issues/5586
Native button: https://github.com/refined-github/sandbox/pull/9
Our feature: https://github.com/refined-github/sandbox/pull/11
> Don't show `update-pr-from-base-branch` when there are conflicts

- source/features/clean-repo-tabs.tsx
The code assumes the page counter always exists in a wiki, which is not the case if a page named "Home" doesn't exist (and thus failing back to a simple list view).
- Wiki with "Home" page: https://github.com/pixiebrix/pixiebrix-extension/wiki
- Wiki without "Home" page: https://github.com/refined-github/refined-github/wiki
> Fix `clean-repo-tabs` wiki count

- source/features/ci-link.css
- source/features/ci-link.tsx
- source/globals.d.ts
- Fixes #5696 
- Fixes #5755 
`attachElement` to the rescue
CI:
No CI:
https://github.com/fregante/.github
> Make `ci-link` more reliable and avoid duplicates

- source/github-helpers/api.ts
- source/github-helpers/get-default-branch.ts
Partial and perhaps temporary solution to:
- https://github.com/refined-github/refined-github/issues/5821
We have two separate issues:
- all of our "current repo" API calls use global state
- plenty of our "cached functions" use global state
The first one is easily fixable by including the state in the key itself, manually, when `repository({global state})` is requested. https://github.com/refined-github/refined-github/pull/5839 offers an alternative approach but it requires a lot of testing. I just want to fix most of these issues in today’s release.
The second one is particularly an issue because I think `webext-storage-cache` does not correctly use the provided `cacheKey` for in-memory cache, just for in-storage one. As you can see the `microMemoize` call only uses the parameters as …
> Fix feature cache across ajaxed page loads

- source/features/show-whitespace.css
- fixes #4991
- https://github.com/fregante/code-tag
- https://github.com/fregante/webext-content-scripts
You have to zoom in to see it near the `}` character and `.and` selector
> Fix `show-whitespace` peekaboo bug

- source/features/first-published-tag-for-merged-pr.tsx
- source/features/releases-tab.tsx
- Fixes https://github.com/refined-github/refined-github/pull/5769#issuecomment-1193189879
- https://github.com/fregante/Awesome-WebExtensions/pull/74
> Only prompt the user to create a release if any already exist

- source/features/clean-checks-list.css
- source/refined-github.ts
- fixes https://github.com/refined-github/refined-github/issues/5856
This feature:
- brings failing and pending checks to the top
- dims successful checks unless it's 100% successful
Support:
- Chrome: not yet (v105+)
- Firefox: not yet (v199+)
- Safari: not yet (next RG release unknown)
This is [a feature for no one](https://www.youtube.com/watch?v=VOhGevqqA1I).
https://github.com/refined-github/refined-github/commit/5c9d630423d66732cb1e2bd7935fc67c133f6072
https://github.com/refined-github/refined-github/pull/5776
_If you like to watch paint dry_
https://user-images.githubusercontent.com/1402241/181183668-1df3a099-2197-43d9-8c23-71ccb24d5081.mov
https://user-images.githubusercontent.com/1402241/181183948-dd170b6d-e4ed-4432-b04c-e7ba96ff35bc.mov
> Add `clean-checks-list` feature

- source/features/action-used-by-link.tsx
- Closes https://github.com/marketplace/actions/urlchecker-action
URL: https://github.com/marketplace/actions/urlchecker-action
> Restore `action-used-by-link`

- source/features/collapsible-content-button.tsx
- source/helpers/attach-element.ts
- Fixes part of https://github.com/refined-github/refined-github/issues/5871
- https://github.com/refined-github/refined-github/issues/5871
- https://github.com/refined-github/refined-github/pull/5872
- https://github.com/refined-github/refined-github/pull/5872/files
1. From this PR
2. Click the "Issues" tab
3. Go back
4. Click the `collapsible-content-button`
> Fix: `collapsible-content-button` doesn't work after back button

- source/features/sticky-file-header.css
- Closes #5823
- Closes #5800
- Any "PR Files", but you must come from a notification
Also, unchanged:
- https://github.com/refined-github/refined-github/commit/1d9dd9f0208c327351512beb6d6a22279bc47807
- https://github.com//refined-github/refined-github/compare/22.2.13...22.2.22#files_bucket
- https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
- https://github.com/refined-github/refined-github/edit/main/readme.md
- https://github.com/refined-github/refined-github/blame/243e51d786e4771d313091b94cec826ff86becc9/source/features/index.tsx#L326-L327
> Fix `sticky-file-header` overlap and position

- source/features/clean-rich-text-editor.css
- Closes https://github.com/refined-github/refined-github/issues/5743
This page
Untouched
Icons restored
> Disable `clean-rich-text-editor` on mobile

- source/features/bypass-checks.tsx
- source/features/conversation-links-on-repo-lists.tsx
- source/features/hide-own-stars.tsx
- source/features/highlight-deleted-and-added-files-in-diffs.tsx
- source/features/jump-to-change-requested-comment.tsx
- source/features/jump-to-conversation-close-event.tsx
- source/features/link-to-github-io.tsx
- source/features/linkify-user-edit-history-popup.tsx
- source/features/quick-label-removal.tsx
- source/features/shorten-links.tsx
- source/helpers/attach-element.ts
- source/helpers/selector-observer.tsx
- Closes #5874 
Not tested.
If the WeakSet doesn't match existing elements, the function will also need to attach a temporary class because I removed our custom `:not(rgh-etc)` selectors
> Replace `selector-observer`

- source/features/fork-source-link-same-view.tsx
Closes #5770
As far as I tested, the releases and tags pages work Ok. I only updated the link for a single tag. I assume we want to fallback to the `defaultUrl` in this case.
https://github.com/GehDoc/textile-js/releases/tag/v2.0.114
> Fix `fork-source-link-same-view` on tags/releases

- source/features/first-published-tag-for-merged-pr.tsx
- source/github-helpers/banner.tsx
Before it was shown:
- on released PRs
- right after merging a PR
Now it's shown:
- when a PR is closed
- released? show link
- else can release? show link
- else show without link
- https://github.com/refined-github/sandbox/pull/35
- https://github.com/facebook/react/pull/25044
- https://github.com/refined-github/refined-github/pull/5854
> Always show `first-published-tag-for-merged-pr`

- source/features/bypass-checks.tsx
`bypass-checks` works great in PR conversations, thanks a lot for this, I wondered for a long time how to get rid of this additional click until I realised refined-github had the feature!
The thing is that `ci-links` will add CI status in other pages outside of PR conversations, and the links are not rewritten by `bypass-checks`.
In this PR I used a similar code as in `bypass-checks` as in `ci-links`:
https://github.com/refined-github/refined-github/blob/eca69b438a9c820a040c38884579c8d1c5af3fe0/source/features/ci-link.tsx#L52-L61
I believe with this change ,`bypass-checks` will run both on PR conversations and all pages where `ci-links` adds a CI status.
I also tested this locally following https://github.com/refined-github/refined-github/blob/main/contributing.md and it seems to work …
> Bypass checks on all repo pages (not only PR conversations)

- source/features/convert-release-to-draft.tsx
- any release you can edit
- WARNING: do no click the button https://github.com/refined-github/refined-github/releases/tag/22.8.8
> Restore `convert-release-to-draft` feature

- source/features/infinite-scroll.tsx
Resolve #5716
https://user-images.githubusercontent.com/44045911/185581428-71a60c63-9803-4b7c-8b2b-acdc14311120.mov
> Support "For you" feed in `infinite-scroll`

- source/features/more-dropdown-links.css
This rule was conflicting with GitHub’s own overflow-nav logic, which ended up hiding every tab.
- Fixes https://github.com/refined-github/refined-github/issues/5921
- Reverts the ancient https://github.com/refined-github/refined-github/issues/3548
- https://github.com/jerone/eslint-formatter-checklist/runs/7950750517?check_suite_focus=true
> Fix: Repo tabs are hidden in Actions on Firefox

- source/features/sticky-file-header.css
Fixes https://github.com/refined-github/refined-github/issues/5914
1. Open a notification pointing to a PR (or PR files)
2. Go to the Files tab
3. This still happens if you go back to the "Conversation" tab, reload the page, and go to "Files" again
**Before**
**After**
> Fix position of sticky file headers after opening notification

- source/features/center-reactions-popup.css
Fix https://github.com/refined-github/refined-github/issues/5881
- This page
- [Split view with review comments](https://github.com/refined-github/sandbox/pull/38/files?diff=split)
**Regular comment**
**Review comment in split diff view**
> Restore `center-reactions-popup` feature

- source/features/dim-bots.tsx
Closes #5945 
Follow the work done in https://github.com/refined-github/refined-github/pull/5512
Check the PRs opened in: https://github.com/gravitee-io/gravitee-policy-oauth2/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc
If there is no PRs opened by Renovate or Snyk by the time this PR is reviewed please refer to the screenshot below ⬇️ 
**Before**
**After**
> Restore support for unmarked bots in `dim-bots`

- source/features/bugs-tab.tsx
Some repositories with more than 1k stars that use the `bug-fix` label:
* https://github.com/axios/axios/issues?q=is%3Aissue+label%3Abug-fix+
* https://github.com/toolkit-for-ynab/toolkit-for-ynab/issues?q=is%3Aissue+label%3Abug-fix
* https://github.com/cloud-hypervisor/cloud-hypervisor/issues?q=is%3Aissue+label%3Abug-fix+ (also has the `bug` label but no issues with it)
* https://github.com/diem/diem/issues?q=is%3Aissue+label%3Abug-fix+ (also has the `bug` label)
* https://github.com/OpenVPN/easy-rsa/issues?q=is%3Aissue+label%3ABUG-FIX+ (also has the `BUG` label)
* https://github.com/JohnSnowLabs/spark-nlp/issues?q=is%3Aissue+label%3Abug-fix+ (also has the `bug` label)
* https://github.com/algorand/go-algorand/issues?q=is%3Aissue+sort%3Aupdated-desc+label%3ABug-Fix+ (also has the `bug` …
> Add support for `bug-fix`/`bugfix` labels in `bugs-tab`

- source/features/hidden-review-comments-indicator.css
- source/features/hidden-review-comments-indicator.tsx
- Part of #5897 
https://github.com/refined-github/sandbox/pull/18/files
Class `.blob-num` was overwriting plugin's css, added `!important` to fix the issue.
Counter was not working, it was using the wrong selector
> Restore `hidden-review-comments-indicator` 

- source/features/link-to-changelog-file.tsx
- source/features/tag-changes-link.tsx
The "Releases UI Refresh" (#4902) was nearly one year ago, so let's drop code still targets the old layout.
* https://github.com/facebook/react/releases
* https://github.com/facebook/react/tags
* https://github.com/facebook/react/releases/tag/v17.0.2
> Meta: Drop code specific to "Releases UI refresh"

- source/features/one-key-formatting.tsx
Closes #5960.
Any page with a Markdown textarea, e.g. the "new comment" field on this page.
> Allow replacing quotes in `one-key-formatting`

- source/features/shorten-links.tsx
- Closes https://github.com/refined-github/refined-github/issues/5889
Yes: https://github.com/refined-github/refined-github/pull/473
No: https://github.com/refined-github/sandbox/pull/14
> Limit `shorten-links` to only Markdown links

- package.json
- source/features/one-click-diff-options.tsx
- Closes #5893 
https://github.com/rancher/rancher/compare/v2.6.3...v2.6.6
https://github.com/rancher/rancher/compare/v2.6.5...v2.6.6
https://github.com/rancher/rancher/commit/e82921075436c21120145927d5a66037661fcf4e
> Avoid duplicate `on-click-diff-options`

- safari/Refined GitHub.xcodeproj/project.pbxproj
- webpack.config.ts
Only inline source maps work in extensions, but they would slow down the extension for everyone
> Meta: Disable sourcemaps

- source/features/select-notifications.css
> Fix: `select-notifications` causes button overlap on mobile

- package-lock.json
- package.json
- source/features/comments-time-machine-links.tsx
- source/features/sort-conversations-by-update-time.tsx
- Fixes https://github.com/refined-github/refined-github/issues/5890
- Fixes https://github.com/refined-github/refined-github/pull/473
- Includes https://github.com/refined-github/shorten-repo-url/pull/38
- Blah blah https://github.com/refined-github/yolo/issues and blah.
- https://github.com/sindresorhus/refined-github/tree/v0.12
<table>
<tr>
<td><img width="390" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/189799120-ebff4e19-2b1a-427c-b36c-75f0cf04a20b.png">
</table>
> Consistently `shorten-links` even if other features altered them

- source/features/open-all-conversations.tsx
- source/features/open-all-notifications.tsx
- source/github-helpers/toast.tsx
- source/helpers/open-tabs.ts
Partial solution to https://github.com/refined-github/refined-github/issues/5798
I think the background page is broken on mobile so the messages aren't received and the tabs aren't opened. This at least stops RG from marking the notifications as read if it fails.
- https://github.com/notifications
I added a toast to show the error, but I thought I'd leave it to also show success.
https://user-images.githubusercontent.com/1402241/189962947-fd3ee98e-4e49-4044-86ea-e9ab137b4438.mov
- https://github.com/npmhub/npmhub/pull/152
> Notify users of errors in `open-all-notifications`

- source/features/toggle-files-button.css
- source/features/toggle-files-button.tsx
- Fixes https://github.com/refined-github/refined-github/issues/5978
Test URL: https://github.com/fregante/refined-github
- Described in https://github.com/refined-github/refined-github/issues/5979#issuecomment-1246502644
Due to this skeleton, `.Details` was not available to be hidden (a selector in the CSS file)
> Make `toggle-files-button` act faster and more reliably

- source/features/quick-review-comment-deletion.tsx
Closes #5901 
https://github.com/refined-github/refined-github/pull/5899/files
> Fix `quick-review-comment-deletion`

- source/features/first-published-tag-for-merged-pr.tsx
- source/github-events/on-pr-merge.ts
- Closes https://github.com/refined-github/refined-github/issues/5868
Any PR:
- that you can merge
- on a repo without native branch auto-deletion
1. Open the PR in two browser, one with RG, one without
2. Merge the PR in the browser without RG
3. The branch should not be deleted 
1. Merge the PR
3. The branch should be deleted
> Avoid triggering `pr-branch-auto-delete` when simply watching a PR

- source/features/sticky-sidebar.css
- source/features/sticky-sidebar.tsx
- Fixes https://github.com/refined-github/refined-github/issues/5790
1. On this PR or on https://github.com/refined-github/refined-github
1. Resize window to less than 768px in width OR use a phone
1. There should not be a `rgh-sticky-sidebar` class when the sidebar is below the content
Note: pop the developer tools out so they don't affect the viewport height calculations
> Disable `sticky-sidebar` on small viewports

- source/features/comment-on-draft-pr-indicator.tsx
- source/features/quick-review.tsx
- Fixes https://github.com/refined-github/refined-github/issues/5815
- Part of #5992 
- Part of #5871 
- Part of https://github.com/refined-github/refined-github/issues/5895
- `quick-review`: This PR
-  `comment-on-draft-pr-indicator`: https://github.com/refined-github/sandbox/pull/7/files
> Fix `quick-review` and `comment-on-draft-pr-indicator`

- source/features/clean-conversation-sidebar.tsx
- Fixes https://github.com/refined-github/refined-github/issues/5843
Not the most optimal solution, but the fastest one. 
Note: No Firefox support, sorry.
The actions change depending on:
- issue / PR
- editable / non editable
Tested URLs:
- This PR
- https://github.com/refined-github/refined-github/issues/5843
- https://github.com/facebook/react/issues/13991
> Restore `clean-conversation-sidebar`

- source/features/quick-review-comment-deletion.tsx
- source/github-helpers/load-details-menu.ts
> Restore `quick-review-comment-deletion`

- source/features/useful-not-found-page.tsx
- Fixes #6005 
- https://github.com/refined-github/refined-github/blob/main/source/features/good-soup.tsx
> Avoid duplication of `useful-not-found-page` on back button

- source/features/clear-pr-merge-commit-message.tsx
- Replaces and closes https://github.com/refined-github/refined-github/pull/5967
- Part of https://github.com/refined-github/refined-github/issues/5155
This is the minimum we can do to make the feature louder since it overrides the user’s settings.
This PR
> Add notice to `clear-pr-merge-commit-message`

- source/features/tag-changes-link.tsx
Hopefully https://github.com/g-plane/typed-query-selector/issues/25 will help us avoid this in the future 
- https://github.com/refined-github/refined-github/releases
```
📕 0.0.0 → DOMException: Failed to execute 'querySelector' on 'Element': 'a[href*="/tree/"])' is not a valid selector.
```
> Restore `tag-changes-link`

- source/helpers/attach-element.ts
- source/helpers/caller-id.test.ts
- source/helpers/caller-id.ts
- source/helpers/selector-observer.tsx
Fixes #5988.
The Chrome stacktrace is starting with an additional line `Error: Get stack`. Firefox already starts with the first stack entry in the first line.
* This PR (see that `reaction-avatars` is working again)
* https://github.com/refined-github/refined-github (see that `toggle-files-button` is working again)
* Basically every other page
> Restore many features in Firefox

- readme.md
- source/features/linkify-labels-on-dashboard.tsx
- source/refined-github.ts
Reverts refined-github/refined-github#6016
> Restore `linkify-labels-on-dashboard` feature

- source/features/user-local-time.tsx
- source/helpers/selector-observer.tsx
- Closes #6013 
- Right here, hover this: @Katsute
> Avoid duplicate `user-local-time`

- source/features/one-click-diff-options.tsx
- For #5820
The feature actively breaks GitHub’s UI on Enterprise, so I had to disable it there. An actual bugfix would be ideal.
@ELLIOTTCABLE @nicolasff @busches
> Disable broken `one-click-diff-options` on GitHub Enterprise

- source/features/clean-header-search-field.tsx
Global search pages don't have a duplicate search bar, so the header field should not be emptied
https://github.com/search?q=repo%3Amicroscaling%2Fimagelayers-graph+is%3Aopen+author%3APeterDaveHello+archived%3Atrue&type=repositories
> Disable `clean-header-search-field` on global search pages

- .github/workflows/test.yml
- contributing.md
- source/feature-manager.tsx
- source/features/no-unnecessary-split-diff-view.css
- source/features/no-unnecessary-split-diff-view.tsx
Works like magic 🤯
But `features.addCssFeature` isn't working? 🤔 
https://github.com/refined-github/sandbox/pull/50/files?diff=split
https://github.com/refined-github/sandbox/compare/no-unnecessary-split-diff-view?expand=1&diff=split
https://github.com/refined-github/sandbox/commit/c28cc8e5271452b5b4c347d46a63f717c29417d6?diff=split
> Make `no-unnecessary-split-diff-view` lighter and immediate 

- source/features/profile-gists-link.tsx
use variable `user` which is introduced in line 41 - no need to call again `getUser()`
```javascript
41: const user = getUser();
```
> Meta: Use existing variable in `profile-gists-link`

- source/features/clean-dashboard.css
While starring an unknown repo seems strange, adding it to a "To check out" list might be reasonable:
I'm thinking about restoring the widget, but making it a little smaller and less prominent. However it's still noisy especially on grouped events. Thoughts?
- https://github.com/refined-github/refined-github/issues/3255
- https://github.com/refined-github/refined-github/issues/1864
> Restore star button in `clean-dashboard`

- source/features/show-open-prs-of-forks.tsx
- Fixes https://github.com/refined-github/refined-github/issues/6010
https://github.com/PeterDaveHelloKitchen/imagelayers-graph
or:
1. Visit https://github.com/pulls?q=is%3Apr+is%3Aopen+author%3A%40me+archived%3Afalse+sort%3Aupdated-desc
2. Open any PRs
3. Visit your own fork from there
4. You should not see this:
> Exclude PRs from archived repos in `show-open-prs-of-forks`

- source/features/release-download-count.tsx
- Fixes https://github.com/refined-github/refined-github/issues/6014 again
https://github.com/TigerBeanst/TigerInTheWall/releases
https://github.com/TigerBeanst/TigerInTheWall/releases/tag/v1.0.6
> Restore `release-download-count` on single releases

- source/features/align-issue-labels.css
- Fixes #6056
https://github.com/bmish/eslint-doc-generator/milestone/1
cc @tyrann0us
> Fix `align-issue-labels` on milestones

- .github/ISSUE_TEMPLATE/1_bug_report.yml
- source/features/no-unnecessary-split-diff-view.css
- Fixes https://github.com/refined-github/refined-github/issues/6061
- Fixes #6064
- Caused by https://github.com/refined-github/refined-github/pull/6023
https://github.com/refined-github/sandbox/pull/50/files?diff=split
https://github.com/refined-github/sandbox/pull/50/files?diff=unified
https://github.com/refined-github/sandbox/compare/no-unnecessary-split-diff-view?expand=1&diff=split
https://github.com/refined-github/sandbox/compare/no-unnecessary-split-diff-view?expand=1&diff=unified
https://github.com/refined-github/sandbox/commit/c28cc8e5271452b5b4c347d46a63f717c29417d6?diff=split
https://github.com/refined-github/sandbox/commit/c28cc8e5271452b5b4c347d46a63f717c29417d6?diff=unified
> Fix unified diff bug caused by `no-unnecessary-split-diff-view`

- source/features/useful-forks.tsx
- source/helpers/dom-utils.ts
- Closes #6049
https://github.com/probot/template/blob/master/CODE_OF_CONDUCT.md?rgh-link-date=2022-10-07T05%3A16%3A38Z
> Avoid misplacement of `useful-forks`

- source/features/hide-newsfeed-noise.css
Closes #5809
This PR adds gollum (wiki)  to hide target on newsfeed.
GitHub uses [gollum](https://github.com/gollum/gollum) for wiki. 
https://github.com (newsfeed)
I took a screenshot almost same time.
There are edited wiki events on feed.
This PR hides the edited wiki events.
> Hide wiki events in `hide-newsfeed-noise`

- source/features/html-preview-link.tsx
- Related to https://github.com/refined-github/refined-github/pull/3305#issuecomment-1277193028
- HTML file on a private repo, e.g. https://github.com/refined-github/refined-github/blob/main/source/options.html
> Don't run `html-preview-link` on private repos

- .github/workflows/release.yml
- attaches the `distribution` folder created by `npm test` to the created release
- archives the `distribution` folder into a tarball before attaching to the release
Closes #4595
> Meta: Attach built extension to releases

- source/features/github-bugs.css
Fixes #6099 
- Added scrollbar
- Added some padding at the bottom of the sidebar to match the padding at top of sidebar
> Make sticky left-side sidebar scrollable on the dashboard

- source/features/table-input.css
- source/features/table-input.tsx
- source/helpers/select-has.ts
- Related to #5797 
`mouseenter` events are triggered hundreds of times just by moving the mouse across the page, whether you’re using `table-input` or not; `delegate` will call `querySelector` in each event to determine whether to call our callback on the specific events we want.
Thankfully `:has` again comes to the rescue, even though the code is awful. I implemented this in a way to preserve backwards compatibility.
This page
> Reduce `table-input` CPU usage thanks to :has selector

- source/features/link-to-github-io.tsx
- source/features/useful-forks.tsx
- source/features/view-last-pr-deployment.tsx
GitHub always opens links in the current tab. The only exception should be for situations where following a link results in loss of data (comments, WIP commits, etc)
> Open RGH links in current tab unless we're on a form

- source/features/restore-file.tsx
- source/features/update-pr-from-base-branch.tsx
- source/github-helpers/get-pr-info.ts
https://github.com/refined-github/sandbox/pull/9 (Conflict)
https://github.com/refined-github/sandbox/pull/11
NA
> Meta: Use new APIs in `update-pr-from-base-branch`

- source/features/clear-pr-merge-commit-message.tsx
- source/features/update-pr-from-base-branch.tsx
Fixes #4531
https://github.com/refined-github/sandbox/pull/53
> `clear-pr-merge-commit-message` preserve closing issues on non-default branch

- source/features/preview-hidden-comments.tsx
Closes #6098
* Write label only if reason exists
* Write comment in all cases (previously would only write if a reason existed)
* Keep comment hidden if disruptive or spam (only if reason exists)
https://github.com/refined-github/refined-github/issues/3647
https://github.com/refined-github/sandbox/pull/47
Comment with missing reason:
|Before|After|
|---|---|
|![image](https://user-images.githubusercontent.com/58778985/198177000-644c1b94-042e-4c24-a137-5be801f0b5dd.png)|![image](https://user-images.githubusercontent.com/58778985/198408331-14fb93f9-47c7-4ff8-a176-bf5ec55c5c7d.png)|
Comment with reason:
|Before|After|
|---|---|
|![image](https://user-images.githubusercontent.com/58778985/198177262-3cc097bc-e774-4c16-ba36-2e3280ab6559.png)|![image](https://user-images.githubusercontent.com/587 …
> `preview-hidden-comments` even if reason is missing

- source/features/releases-tab.tsx
Fix #6130 
~I did not blame this yet. There must have been a reason we did it like this~
Assuming this did not exist in the past
> Fix `releases-tab` count

- source/feature-manager.tsx
- source/features/comments-time-machine-links.tsx
- source/features/default-branch-button.tsx
- source/features/dim-bots.tsx
- source/features/easier-pr-sha-copy.css
- source/features/global-conversation-list-filters.tsx
- source/features/global-search-filters.tsx
- source/features/latest-tag-button.tsx
- source/features/link-to-github-io.tsx
- source/features/linkify-branch-references.tsx
- source/features/linkify-symbolic-links.tsx
- source/features/list-prs-for-file.tsx
- source/features/more-file-links.tsx
- source/features/patch-diff-links.tsx
- source/features/quick-file-edit.tsx
- source/features/quick-review.tsx
- source/features/releases-tab.tsx
- source/features/repo-age.tsx
- source/features/repo-wide-file-finder.tsx
- source/features/rgh-feature-descriptions.tsx
- source/features/rgh-linkify-features.tsx
- source/features/same-branch-author-commits.tsx
- source/features/submission-via-ctrl-enter-everywhere.tsx
- source/features/swap-branches-on-compare.tsx
- source/features/useful-forks.tsx
- source/features/view-last-pr-deployment.tsx
- source/refined-github.ts
- Closes https://github.com/refined-github/refined-github/issues/5751#issuecomment-1275907968
The `#js-repo-pjax-container` continues to exist though
Untested
> Drop outdated references to PJAX

- source/features/patch-diff-links.tsx
- Fixes https://github.com/refined-github/refined-github/issues/5987
[`05b7ccd` (#5807)](https://github.com/refined-github/refined-github/pull/5807/commits/05b7ccda4335b5927531d3c58a535548bbd74b64)
> Fix overflow caused by `patch-diff-links`

- source/features/scheduled-and-manual-workflow-indicators.tsx
- Fixes https://github.com/refined-github/refined-github/issues/6111
Manual:
https://github.com/fregante/browser-extension-template/actions
Manual + scheduled:
https://github.com/fregante/eslint-formatters/actions
> Restore `scheduled-and-manual-workflow-indicators`

- source/features/infinite-scroll.tsx
- Fixes https://github.com/refined-github/refined-github/issues/6100
The intent of https://github.com/refined-github/refined-github/pull/5319 was to copy the RSS feed link, but the broad selector sometimes picked the wrong link (I even saw an issue link appear there)
This is what it looks like when it works correctly:
Since the RSS isn't something people generally look for at every load, it's ok to leave it at the bottom of the feed.
> Drop incorrect link added by `infinite-scroll`

- source/features/pagination-hotkey.tsx
- tsconfig.json
- Fixes #6146 
- Includes #6147
PR Commit: [`1e1e070` (#4677)](https://github.com/refined-github/refined-github/pull/4677/commits/1e1e0707ac58d1a40543a92651c3bbfd113481bf)
Releases: https://github.com/refined-github/refined-github/releases
Issues: https://github.com/refined-github/refined-github/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
Repo Search: https://github.com/refined-github/refined-github/search?q=pull
Global search: https://github.com/search?q=wonder&type=repositories
> Cleanup and extend `pagination-hotkey`

- source/features/open-all-notifications.tsx
- Fixes https://github.com/refined-github/refined-github/issues/6158
https://github.com/notifications after clicking "Group by repository"
> Avoid duplicate `open-all-notifications` buttons

- source/features/repo-avatars.tsx
- For https://github.com/refined-github/github-url-detection/issues/152
- org repo: https://github.com/refined-github/refined-github
- user repo: https://github.com/fregante/GhostText
> Fix `repo-avatars` rounding in orgs

- source/features/profile-gists-link.tsx
- Fixes #6162 
- your own profile, e.g. https://github.com/fregante
> Fix: `profile-gists-link` appears in status selection on profile

- source/features/scheduled-and-manual-workflow-indicators.tsx
The most annoying thing is that I wrote and tested this just last month 
- https://github.com/refined-github/refined-github/pull/6137
https://github.com/refined-github/refined-github/actions
> Restore `scheduled-and-manual-workflow-indicators` again

- source/features/select-notifications.tsx
The button style feels more appropriate for actions in this case, rather than for selections. This is more clear when a notification is selected and you can tell the two types apart (select vs act)
> Improve `select-notifications` style

- source/features/quick-file-edit.tsx
- Part of https://github.com/refined-github/refined-github/issues/6152
- https://github.com/refined-github/refined-github/tree/lint/safari
> Restore `quick-file-edit` on new directory views

- readme.md
- source/features/unhide-reactions-on-mobile.css
- source/refined-github.ts
Closes https://github.com/refined-github/refined-github/issues/6161
https://github.com/refined-github/refined-github/issues/6161
Firefox users have to set `layout.css.has-selector.enabled` to true in `about:config` (https://developer.mozilla.org/en-US/docs/Web/CSS/:has#browser_compatibility).
On Google Play Store version of Firefox Nightly for Developers, version `109.0a1`.
With `npx web-ext run -t firefox-android --adb-device <use adb devices> --firefox-apk org.mozilla.fenix`
> Add `unhide-reactions-on-mobile` feature

- source/features/restore-file.tsx
- source/github-helpers/api.ts
Closes #6155.
https://github.com/gamemaker1/test/pull/1/files
> Restore `restore-file` feature

- source/features/hide-own-stars.tsx
> Fix `hide-own-stars`

- source/refined-github.css
It seems like GitHub have changed the css variables `--color-fg-success` and `--color-fg-danger` to `--color-success-fg` and `--color-danger-fg`, respectively. This fixes that so that the refined-github changes align better with the rest of the colors on the webpage. 
https://github.com/cypress-io/cypress/pulls seems to have quite a few examples where this change can be seen 
**Before**
**After**
> Update CSS color names

- source/features/last-notification-page-button.tsx
fixes #6218
Tested via `npx web-ext run --target=chromium` and https://github.com/notifications?query=repo%3Aprisma%2Fprisma+is%3Aunread where the problem manifested for me.
> Fix pagination in `last-notification-page-buttons`

- source/features/copy-on-y.tsx
- Fixes https://github.com/refined-github/refined-github/issues/6210
- Part of #6152
Over the years I've come to expect "copy on y" on any page so I think it wouldn't be too bad to actually enable it site-wide.
Thoughts?
￼
Literally any page, including:
https://github.com/refined-github/refined-github/blob/main/source/features/hide-diff-signs.css
> Restore `copy-on-y` and enable it on every page

- source/feature-manager.tsx
Probably:
- Fixes #6001 
- Fixes #5762
https://user-images.githubusercontent.com/1402241/215728496-84f7bba7-ae29-445c-93ac-3302838b6a51.mov
> Reduce content shift on navigation

- source/features/clean-header-search-field.tsx
https://github.com/fregante/GhostText/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc
> Restore `clean-header-search-field`

- source/features/download-folder-button.tsx
- Finally fixes https://github.com/refined-github/refined-github/issues/6154
- Own repo: https://github.com/refined-github/refined-github/tree/main/.github
- Archived repo: https://github.com/fregante/object-fit-images/tree/master/demo
Seen in both desktop and mobile resolutions.
> Restore `download-folder-button`

- source/features/one-click-diff-options.tsx
- source/helpers/dom-utils.ts
- Fixes https://github.com/refined-github/refined-github/issues/6200
- PR files: https://github.com/refined-github/refined-github/pull/6261/files
- Compare, in "Files changed" tab: https://github.com/rancher/rancher/compare/v2.6.3...v2.6.6
- Compare, without tab: https://github.com/rancher/rancher/compare/v2.6.5...v2.6.6
- Single commit: https://github.com/rancher/rancher/commit/e82921075436c21120145927d5a66037661fcf4e
Lengthy video… it just demoes that the value is preserved after a refresh
https://user-images.githubusercontent.com/1402241/215558582-27c1f86d-a13d-4b88-bc53-7c282a38ec56.mov
> Remember `one-click-diff-options` state

- source/features/profile-gists-link.tsx
- source/github-helpers/create-dropdown-item.tsx
- closes #6231
https://github.com/fregante
It also keeps #6162 in mind
> Avoid misplacement of `profile-gists-link`

- source/features/mark-merge-commits-in-list.tsx
- closes https://github.com/refined-github/refined-github/issues/6235
- isPRConversation: https://github.com/refined-github/refined-github/pull/6194
- isPRCommitList: https://github.com/refined-github/refined-github/pull/6194/commits
- isCommitList: https://github.com/babel/babel/commits/master?after=ddd40bf5c7ad8565fc990f26142f85613958a329+104
- isCompare: https://github.com/refined-github/sandbox/compare/e8b25d3e...b3d0d992
> Restore `mark-merge-commits-in-list` in PRs

- source/features/clean-conversation-headers.css
- source/features/linkify-user-labels.tsx
The `.Label` class is gone.
Also:
https://github.com/refined-github/refined-github/issues/6263
> Restore `linkify-user-labels`

- source/features/release-download-count.tsx
- fix https://github.com/refined-github/refined-github/issues/6014 again
- One release: https://github.com/TigerBeanst/TigerInTheWall/releases/tag/v1.0.6
- List of releases: https://github.com/TigerBeanst/TigerInTheWall/releases
- Lots of assets: https://github.com/notepad-plus-plus/notepad-plus-plus/releases
> Restore `release-download-count`

- source/options.css
- source/options.tsx
The notice is useful when the user has disabled a lot of features, because they're pushed down, but it's not essential, we already show when each feature has been disabled inline.
> Drop duplicate hotfix notice in the options page

- source/features/clear-pr-merge-commit-message.tsx
Any unmerged PR, find one in https://github.com/pulls
https://user-images.githubusercontent.com/1402241/215960483-efe70247-8125-43a3-8903-26f7ba6456b8.mov
https://user-images.githubusercontent.com/1402241/215960522-f2012e33-36ef-42d4-806d-4bbda2daac65.mov
> Shrink text field after `clear-pr-merge-commit-message`

- source/features/default-branch-button.css
- source/features/default-branch-button.tsx
- source/github-helpers/group-buttons.tsx
- source/refined-github.css
- Part of #6152 
Branch, subfolder: https://github.com/refined-github/refined-github/tree/better-ajax-detection/safari
Commit, home page: https://github.com/refined-github/refined-github/tree/2ce3317eba7d01d0c728605ad7730b4ee067835d
> Restore `default-branch-button`

- source/features/rgh-feature-descriptions.css
- source/features/rgh-feature-descriptions.tsx
- finally fixes https://github.com/refined-github/refined-github/issues/6211
- https://github.com/refined-github/refined-github/blob/main/source/features/avoid-accidental-submissions.tsx
- https://github.com/refined-github/refined-github/blob/main/source/features/copy-on-y.tsx
At three different resolutions. Zoom in or open in a new window:
<table>
<tr>
<td><img width="1029" alt="Screenshot 25" src="https://user-images.githubusercontent.com/1402241/215476515-35c9865c-29e1-4777-8399-4144a37dc804.png">
<td>
<td><img width="479" alt="Screenshot" src="https://user-images.githubusercontent.com/1402241/215476577-c0188b2e-8d15-4d32-8bfc-451b3483cd93.png">
</table>
> Restore `rgh-feature-descriptions`

- source/features/sticky-sidebar.css
- Fixes https://github.com/refined-github/refined-github/issues/6151
Side note: `sticky-sidebar` is broken on the repo root, likely due to https://github.com/refined-github/refined-github/pull/5961 and specifically due to the lack of this variable outside the conversations
https://github.com/refined-github/refined-github/blob/c0c48c4290b4ae38e3f10b60e93a84a7174e0d13/source/features/sticky-sidebar.css#L10-L11
> Fix global search dropdown overlap caused by `sticky-sidebar`

- contributing.md
- Since Each JavaScript feature lives in its own file under [source/features](https://github.com/refined-github/refined-github/tree/main/source/features), the import mentioned in [contributing.md](https://github.com/refined-github/refined-github/commit/89143fa5a0a57be34cceada6f158a7eb0d708863) gives error: `Cannot find module`.
> Minor correction in `feature.add` examples in contributing.md

- source/features/github-bugs.css
- Fixes https://github.com/refined-github/refined-github/issues/6159
Months later, bug still there. The hotfix wasn't enough https://github.com/refined-github/yolo/commit/f038ff814d194a101fb51ab2a3068c7387906b64
https://user-images.githubusercontent.com/1402241/215964724-31325882-16a2-4c94-8c13-76add2000aa1.mov
https://user-images.githubusercontent.com/1402241/215964785-b7296a9e-10e1-4573-bd43-34ad7bdada7d.mov
> Fix GitHub bug: header overflow on homepage on mobile

- source/features/hide-diff-signs.css
- source/features/sticky-file-header.css
This updates the links following a report in https://github.com/refined-github/refined-github/issues/6152#issuecomment-1376541166
Everything seems to still work, with the exception that GitHub now does this natively almost everywhere.
@kema-dev where do you see the issue? Please include URLs, your browser and the version you're using
> Update links in `sticky-file-header`

- source/features/releases-tab.tsx
This pull request fixes an issue with `releases-tab` where the tab would not be displayed if Refined GitHub could not find the release count from the DOM, which would be the case if a user disabled "releases" from the "show in the home page" setting.
Example repositories:
- https://github.com/hybridly/hybridly
- https://github.com/vueuse/motion
Note: this change doesn't affect the fact that the release tab won't be displayed if there's no release at all.
> Improve `releases-tab` reliability

- source/features/rgh-linkify-yolo-issues.tsx
- source/github-helpers/index.ts
- source/refined-github.ts
- closes [#6258](https://github.com/refined-github/refined-github/issues/6258)
- Affects the page:  [refined-github/yolo@main/broken-features.csv](https://github.com/refined-github/yolo/blob/main/broken-features.csv?rgh-link-date=2023-01-30T13%3A28%3A41Z).
- This change in this pr continues the work which was done on [#6269](https://github.com/refined-github/refined-github/pull/6269) pr.
> Add `rgh-linkify-yolo-issues` feature

- source/features/rgh-feature-descriptions.css
- source/features/rgh-feature-descriptions.tsx
- Follows https://github.com/refined-github/refined-github/pull/6253
Why:
- the box looks weird without a title, it's not clear what it describes
- I find myself copying the name all the time
<table>
<tr>
<th>Before
<th>After
<tr>
<td><img width="662" alt="Screenshot 4" src="https://user-images.githubusercontent.com/1402241/216768901-bf13ad0e-456b-491e-9d4d-5d1d1440f376.png">
<td><img width="662" alt="Screenshot 3" src="https://user-images.githubusercontent.com/1402241/216768892-8b9c9e91-c9f9-436e-9b09-c4078e1372f9.png">
</table>
> Add name and  "Copy name" button to `rgh-feature-descriptions`

- source/features/fork-source-link-same-view.tsx
- Fixes https://github.com/refined-github/refined-github/issues/6179
- Reverts https://github.com/refined-github/refined-github/pull/5351
cc @kidonng what pages do you think we can add here? Let's be explicit in what we support so we avoid silly 404s
- Folder: https://github.com/fregante/refined-github/tree/main/.github
- PR list: https://github.com/fregante/refined-github/pulls
- Tags list: https://github.com/fregante/refined-github/tags
> Limit `fork-source-link-same-view` to known-good pages

- source/features/hide-newsfeed-noise.css
- Fixes https://github.com/refined-github/refined-github/issues/6232
- Fixes https://github.com/refined-github/refined-github/issues/6305
<table>
<tr>
<th>Before
<td><img width="581" alt="Screenshot" src="https://user-images.githubusercontent.com/1402241/217328740-f6ad62de-7828-4b8b-94e7-95fc859a132e.png">
<tr>
<th>After
<td><img width="581" alt="Screenshot 1" src="https://user-images.githubusercontent.com/1402241/217328754-937d0837-1415-4643-ad0a-81199d648684.png">
</table>
> Correctly hide grouped "Follow" events in `hide-newsfeed-noise`

- source/features/download-folder-button.css
- source/features/download-folder-button.tsx
- Re-fixes https://github.com/refined-github/refined-github/issues/6154
- https://github.com/VoronDesign/VoronUsers/tree/master/orphaned_mods/printer_mods/edwardyeeks/Decontaminator_Purge_Bucket_%26_Nozzle_Scrubber
> Restore `download-folder-button` for non-beta users

- source/features/clean-header-search-field.tsx
- Fixes https://github.com/refined-github/refined-github/issues/6310
https://github.com/fregante/GhostText/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc
Untested, depends on the user
cc @kaste
> Restore `clean-header-search-field` for some users

- source/features/github-bugs.css
- Extends https://github.com/refined-github/refined-github/pull/6278
- For https://github.com/refined-github/refined-github/issues/6159
- https://github.com/VoronDesign/VoronUsers/tree/master/orphaned_mods/printer_mods/edwardyeeks/Decontaminator_Purge_Bucket_%26_Nozzle_Scrubber
> Fix GitHub header overflow bug on every page

- source/features/tag-changes-link.tsx
- Fixes #6080 
Fixes the tag-changes-link not visible on the tags list and single release pages.
- https://github.com/refined-github/refined-github/releases
- https://github.com/refined-github/refined-github/tags
- https://github.com/refined-github/refined-github/releases/tag/23.2.5
> Fixed partially broken `tag-changes-link` 

- package-lock.json
- package.json
- source/features/reactions-avatars.tsx
- Fixes https://github.com/refined-github/refined-github/issues/5485
- Includes https://github.com/refined-github/github-url-detection/pull/158
https://github.com/orgs/community/discussions/11202
https://github.com/parcel-bundler/parcel/discussions/6490
https://github.com/refined-github/refined-github/pull/4119
> Enable `reaction-avatars` on organization discussions

- source/features/sticky-sidebar.css
> Fix `sticky-sidebar` on repo's "Code" tab 

- source/features/quick-comment-edit.tsx
- closes https://github.com/refined-github/refined-github/issues/6029
Sorry discussions have a completely different DOM so at this point they're not worth supporting (also because relatively rare).
I can accept PRs to add support, if they don't require complex logic, but otherwise I won't treat this as a bug and won't keep it as a feature request.
> Drop discussion support from `quick-comment-edit`

- source/features/clear-pr-merge-commit-message.tsx
Opening the merge box multiple times could cause multiple notes to be injected. The field also lost any user-customized content every time the form was opened.
https://github.com/refined-github/sandbox/pull/55
<table>
<tr>
<th>Before
<th>After
<tr>
<td> 
https://user-images.githubusercontent.com/1402241/218244742-f049e627-4ce4-4894-bbbd-928c9d045600.mov
<td> 
https://user-images.githubusercontent.com/1402241/218244820-e01cb99a-5318-452d-9074-12aa0d7e9059.mov
</table>
> Run `clear-pr-merge-commit-message` only once per load

- source/features/batch-mark-files-as-viewed.tsx
- Fixes #5880 
https://github.com/refined-github/sandbox/pull/55/files
https://user-images.githubusercontent.com/1402241/218014929-0c1accf3-416f-4909-a83a-662a5cbe555b.mov
> Restore alt-clicks in `batch-mark-files-as-viewed`

- source/features/center-reactions-popup.css
https://github.com/refined-github/refined-github/releases/tag/23.2.5
> Better wrap 6 reactions in releases in `center-reactions-popup`

- readme.md
- source/features/quick-new-issue.tsx
- source/refined-github.ts
- Closes https://github.com/refined-github/refined-github/issues/6294
Known issues: it still appears on repos that have issues disabled 🤷‍♂️ 
Repo home:
https://github.com/fregante/webext-storage-cache
Wiki, template picker:
https://github.com/refined-github/refined-github/wiki
Archived repo (feature disabled):
https://github.com/fregante/iphone-inline-video
> Add `quick-new-issue` feature

- source/features/tag-changes-link.tsx
- Fixes #5884 
https://github.com/parcel-bundler/parcel/tags?after=%40parcel%2Fintegration-tests%401.12.5
> Correctly escape tags in the tooltip of `tag-changes-link`

- source/features/clear-pr-merge-commit-message.tsx
> Properly clear field in `clear-pr-merge-commit-message`

- source/features/html-preview-link.tsx
- Due to https://github.com/refined-github/refined-github/pull/6357#discussion_r1111221239 
```
refined-github.js:24847 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'textContent')
at isPublicRepo (refined-github.js:24847:88)
at refined-github.js:17997:32
at Array.every (<anonymous>)
at shouldFeatureRun (refined-github.js:17997:19)
at setupPageLoad (refined-github.js:3790:73)
at Object.add (refined-github.js:3865:12)
```
https://github.com/OctoLinker/OctoLinker/commits/master
> Avoid console error in `html-preview-link`

- readme.md
- source/features/dim-bots.css
- source/features/dim-bots.tsx
- source/features/mark-merge-commits-in-list.css
- source/features/mark-merge-commits-in-list.tsx
- Closes #5993 
- Better solution to https://github.com/refined-github/refined-github/issues/5158
- than https://github.com/refined-github/refined-github/pull/5198
Probably the next improvements to this feature is to make it CSS-only via `:has()` to avoid the delay after load
- PRs: https://github.com/OctoLinker/OctoLinker/pulls?q=is%3Apr+is%3Aclosed
- Commits: https://github.com/typed-ember/ember-cli-typescript/commits/master?after=5ff0c078a4274aeccaf83382c0d6b46323f57397+174
The latter now also has a fade and it matches the opacity
<table>
<tr>
<th>Before
<th>After
<tr>
<td> 
https://user-images.githubusercontent.com/1402241/220601266-12a8a1a8-9f8e-46b6-8213-7338f15e7313.mov
<td>
https://user-images.githubusercontent.com/1402241/220601280-a459847f-115d-4153-ac02-2b32156d8bac.mov …
> Improve UX of `dim-bots` by disabling the feature on click

- source/features/improve-shortcut-help.tsx
- source/features/pull-request-hotkeys.tsx
- Closes https://github.com/refined-github/refined-github/issues/5439
This page, press the `?` key
<table>
<tr>
<th>Before
<th>After
<tr>
<td><img width="308" alt="Screenshot 2" src="https://user-images.githubusercontent.com/1402241/220908958-09387e02-989c-4e75-bff9-594b5e9a29b1.png">
<td><img width="308" alt="Screenshot 1" src="https://user-images.githubusercontent.com/1402241/220908935-fc2461ad-bf34-4b9b-8fd6-ef798f4be715.png">
</table>
> Sort Refined GitHub shortcuts in Shortcut Help dialog

- source/options.css
- source/options.html
- source/options.tsx
- Includes https://github.com/refined-github/refined-github/issues/5222#issuecomment-1172237540
- In preparation for a future https://github.com/refined-github/refined-github/issues/6383
Open the options page
<details>
<summary>Initial screenshots / demos </summary>
https://user-images.githubusercontent.com/1402241/220904136-ca1be78d-4b82-46b1-8faf-4277f5bfa4d7.mov
</details>
> Collapse sections in options page

- source/features/one-click-pr-or-gist.tsx
Closes #6391
This page affects PR creation in private repos
Without the fix
> <img src="https://user-images.githubusercontent.com/29425008/221418957-1c9c663f-b970-46e0-871d-079b74d2045d.png"  width="40%">
With the fix
> <img src="https://user-images.githubusercontent.com/29425008/221418879-6e07c225-941b-4829-835a-b872853e0703.png"  width="40%">
> Fix `one-click-pr-or-gist` private free repos pr creation

- source/features/bugs-tab.tsx
- source/features/ci-link.tsx
- source/features/clean-repo-tabs.tsx
- source/features/more-dropdown-links.tsx
- source/features/releases-tab.tsx
- source/features/repo-avatars.tsx
- source/features/rgh-sponsor-button.tsx
- Follows https://github.com/refined-github/github-url-detection/pull/131
- For https://github.com/refined-github/refined-github/issues/5222#issuecomment-1245728297
This feature was slightly refactored.
- Org with 0 projects: https://github.com/babel
- Repo with 0 projects: https://github.com/babel/flavortown
- Repo with 0 wiki: https://github.com/babel/babel-sublime-snippets
> Meta: use `hasRepoHeader`

- package-lock.json
- package.json
- source/features/bugs-tab.tsx
- source/features/clean-conversation-filters.tsx
- source/features/clean-repo-tabs.tsx
- source/features/closing-remarks.tsx
- source/features/github-actions-indicators.tsx
- source/features/highlight-collaborators-and-own-conversations.tsx
- source/features/latest-tag-button.tsx
- source/features/link-to-changelog-file.tsx
- source/features/list-prs-for-file.tsx
- source/features/mark-private-orgs.tsx
- source/features/pinned-issues-update-time.tsx
- source/features/pr-commit-lines-changed.tsx
- source/features/pr-filters.tsx
- source/features/profile-gists-link.tsx
- source/features/releases-tab.tsx
- source/features/repo-age.tsx
- source/features/show-associated-branch-prs-on-fork.tsx
- source/features/show-open-prs-of-forks.tsx
- source/features/user-local-time.tsx
- source/features/user-profile-follower-badge.tsx
- source/github-helpers/get-default-branch.ts
- source/github-helpers/index.ts
- source/helpers/hotfix.tsx
- Includes https://github.com/fregante/webext-storage-cache/pull/39
It looks pretty smooth, no great improvement though since many functions silently depend on a global (`user/repo`). This should help on that front:
- https://github.com/refined-github/refined-github/issues/5848
> Meta: Update `webext-storage-cache`

- source/features/quick-comment-edit.css
- source/features/quick-comment-edit.tsx
- Fixes https://github.com/refined-github/refined-github/issues/6390
Note this fix is `has` selector-based: #5797 
A conversation:
- you commented on in the past
- you can't edit or comment on anymore (locked or user blocked you)
> Disable `quick-comment-edit` on non-editable issues

- source/background.ts
- source/helpers/hotfix.tsx
- Follows https://github.com/refined-github/refined-github/pull/6376
- Precedes https://github.com/fregante/webext-storage-cache/issues/40
Before my PR, the key was static: `'hotfixes'`
After my PR, the key became dynamic: `'hotfixes:0.0.0'`
I had ignored this because the actual key doesn't really matter when using `cache.function`, but it does matter when accessing the same cached item via `cache.get`. 
Yet another reason to fix the API as described in https://github.com/fregante/webext-storage-cache/issues/40
> Meta: Fix hotfixes

- source/features/rgh-feature-descriptions.tsx
- source/helpers/hotfix.tsx
> Show whether feature is hotfixed in `rgh-feature-descriptions`

- .github/workflows/release.yml
- For https://github.com/fregante/browser-extension-template/issues/49
It turns out it's a single line of configuration 🎉 
Unfortunately it only covers the actual deployment step, not the build, so if versioning fails, there it will still not be visible outside the Action tab.
> Meta: Display deployments

- source/features/github-bugs.css
The custom style which applies margin-right to the header button icons is no longer needed as GitHub has these styles corrected itself, and moreover the custom style is slightly incorrect as it was applying both to the icon before the text as well as the dropdown icon which doesn't need the margin.
**Before**
**After**
> Remove style override that is no longer needed

- source/options.css
- source/options.tsx
Closes https://github.com/refined-github/refined-github/issues/5539
~~I'm not gonna drop the code for now, but it's been broken for longer than a year. I'll likely drop it sooner or later if not fixed,~~ we do have releases now.
> Stop highlighting NEW features

- readme.md
- source/features/closing-remarks.tsx
- source/features/netiquette.tsx
- source/features/rgh-netiquette.tsx
- source/github-helpers/banner.tsx
- source/refined-github.ts
- Continues from #6427 
- Part of #5934 
I don't want to lock issues, but also I don't want comments on years-old issues.
I think the only comments allowed there would be "GitHub implemented this" or "I extracted this code into its own extension". That is: actually-useful comments, not just disagreements or bug reports.
👆 maybe not, because of the aforementioned _useful_ comments.
- Old issue: https://github.com/refined-github/refined-github/issues/3076
- Old PR: https://github.com/refined-github/refined-github/pull/159
> Add `rgh-netiquette` feature

- source/features/useful-forks.tsx
Due to: https://github.com/useful-forks/useful-forks.github.io/issues/42
Revert after:
- https://github.com/useful-forks/useful-forks.github.io/pull/62
> Ask for token more politely in `useful-forks`

- source/github-helpers/heat-map.css
Closes #6369
My preferred green (75deg)
The default current palette (29deg)
> Allow color customization via CSS in `file-age-color` and `release-download-count`

- source/features/tab-size.css
The selector is not specific enough after previous refactor PR.
https://github.com/refined-github/refined-github/pull/6480#discussion_r1161521663
I'm leaving out https://github.com/refined-github/refined-github/pull/6480#discussion_r1161516959 fot the moment.
https://github.com/refined-github/sandbox/pull/19
As mentioned in https://github.com/refined-github/refined-github/pull/6480#pullrequestreview-1377199124 GitHub has some weird render bug so I think this is probably clearer:
<table>
<tr>
<td>Before
<td>After
<tr>
<td><img width="326" alt="image" src="https://user-images.githubusercontent.com/44045911/230856944-bf69d108-4988-4ade-9f16-2aa4188b1c4d.png">
<td><img width="321" alt="image" src="https://user-images.githubusercontent.com/44045911/230856956-377454bb-f09e-48f7-9400-c2f0a84525ac …
> Refactor `tab-size` /2

- package-lock.json
- package.json
- source/features/quick-new-issue.tsx
- source/github-helpers/index.ts
- source/refined-github.css
> Restore `quick-new-issue` on Global navigation update

- source/features/rgh-netiquette.tsx
- source/refined-github.css
- fixes #6484 
https://github.com/refined-github/sandbox/pull/17
https://github.com/refined-github/sandbox/pull/1
> Less eye-catching `rgh-netiquette`

- readme.md
- source/features/highlight-collaborators-and-own-conversations.css
- source/features/small-user-avatars.css
- source/features/small-user-avatars.tsx
- source/refined-github.ts
Resolve #4906
- https://github.com/refined-github/refined-github/issues
- With pinned issue: https://github.com/dependabot/dependabot-core/issues
> Add `small-user-avatars` feature

- source/features/clean-conversations.css
Previously we are just hiding the image, not the link. Therefore I can still tab to it, which doesn't seem right.
Here
https://github.com/refined-github/refined-github/pull/6490#issuecomment-1505002859
> Hide avatar entirely from comment form

- source/features/html-preview-link.tsx
Fix #6360
https://github.com/CodingTrain/website-archive/blob/4f90eedb9618257d9166241e92e51a7f3f00a08e/code_challenges/PerlinNoiseTerrain_p5.js/index.html
> Fix `html-preview-link` in new file UI

- source/features/closing-remarks.tsx
- source/features/rgh-netiquette.tsx
- source/refined-github.css
- Fixes #6482 
- Addresses https://github.com/refined-github/refined-github/issues/5851#issuecomment-1195289714
- May replace #6489 
- PR: https://github.com/refined-github/refined-github/pull/5600
- Locked PR: https://github.com/eslint/eslint/pull/17
- Archived repo: https://github.com/fregante/iphone-inline-video/pull/130
- RGH tagged PR: https://github.com/refined-github/sandbox/pull/1
> Less flashy `closing-remarks`

- package-lock.json
- package.json
Follows:
-  #3981 
-  #6448 
Includes:
- https://github.com/fregante/webext-options-sync/pull/65/files/06fafa8a6f002908e2ef43683a4d8181baf612da..7cf1c25080528a177192d8563b68c5a68afb5f46
Working at first try 😍  I also tested importing a file from Chrome
https://user-images.githubusercontent.com/1402241/232036339-58584155-e802-4d0d-8d9c-4def47bf39f5.mov
> Add support for Firefox and Safari in options import/export

- source/features/table-input.tsx
Fix #6514
Moved the table input button to the same position as `collapsible-content-button`
Here
<table>
<tr>
<td>Before
<td>After
<tr>
<td><img width="693" alt="image" src="https://user-images.githubusercontent.com/44045911/232004756-29e5362d-c051-427f-854a-ed35ebda4f3b.png">
<td><img width="676" alt="image" src="https://user-images.githubusercontent.com/44045911/232097015-c623d12a-e77c-4381-bce1-259f9df9263d.png">
</table>
> Fix `table-input` position

- source/features/github-bugs.css
- source/features/release-download-count.css
- source/features/release-download-count.tsx
Fix #6509
Fix #6150
https://github.com/veracrypt/VeraCrypt/releases/tag/VeraCrypt_1.25.9
<table>
<tr>
<td>Before
<td>After
<tr>
<td><img width="376" alt="image" src="https://user-images.githubusercontent.com/44045911/231974877-fe37aa0d-f14a-4d60-8323-2a9b5078e8dd.png">
<td>
[See comment](https://github.com/refined-github/refined-github/pull/6510#issuecomment-1508788214)
</table>
> Fix `release-download-count` spacing

- source/features/linkify-user-labels.tsx
- source/features/show-names.tsx
- Fixes https://github.com/refined-github/refined-github/issues/6504
https://github.com/python/cpython/issues/67591
> Exclude mannequins from `show-names`

- readme.md
- source/features/github-bugs.css
- source/features/highlight-non-default-base-branch.tsx
- source/features/latest-tag-button.tsx
- source/features/releases-dropdown.tsx
- source/features/tags-dropdown.tsx
- source/globals.d.ts
- source/refined-github.ts
Follows:
- https://github.com/refined-github/refined-github/issues/6257
- https://github.com/refined-github/refined-github/pull/6438
Super easy, barely an inconvenience. The only issue is that it's technically misusing the `datalist` for navigation (just like mobile websites have done with `select` from 2007 until recently)
https://github.com/refined-github/refined-github/releases
> Add `releases-dropdown` feature

- package-lock.json
- package.json
- source/features/swap-branches-on-compare.tsx
Fix #6513
https://github.com/refined-github/refined-github/compare
https://user-images.githubusercontent.com/44045911/232227088-29776d4c-185f-4594-af51-25ff929edf24.mov
> Disable `swap-branches-on-compare` on blank page

- source/features/table-input.tsx
I think this generates a slightly more usable HTML:
- if there's only one column, print one HTML line per table row
- reduce the indentation because it can issues in Markdown, like:
```html
<table>
<tr>
<td> 
<td>
<tr>
<td>
<td>
</table>
```
Causes:
<table>
<tr>
<td> 
<td>
<tr>
<td>
<td>
</table>
The extra line breaks are used sometimes to re-enable markdown parsing in the table, like:
```md
<table>
<tr>
<td>
[link](/file)
</table>
```
<table>
<tr>
<td>
[link](/file)
</table>
Here
> More ergonomic `table-input` HTML

- readme.md
- source/features/view-last-pr-deployment.tsx
GitHub represents deployments with rocket icon, I think it is better than a general external link icon.
Also changed the copy from "last" to "latest" which is more conventional.
https://github.com//vuejs/core/pull/6160
> Use correct `view-last-pr-deployment` icon

- package-lock.json
- package.json
- source/features/hide-user-forks.tsx
- Fixes #6464
- Replaces and closes https://github.com/refined-github/refined-github/pull/6466
- https://github.com/fregante?tab=repositories
- https://github.com/orgs/refined-github/repositories
- The "Your repositories" link in the user dropdown in the header
- The "Repositories" tab in
- https://github.com/fregante
- https://github.com/refined-github
> Ensure `hide-user-forks` works coming from anywhere

- source/feature-manager.tsx
> Better search link in console issue reporter

- source/features/clean-conversation-sidebar.tsx
- source/features/hide-own-stars.tsx
- source/features/mark-merge-commits-in-list.tsx
- source/features/quick-new-issue.tsx
- source/features/rgh-netiquette.tsx
- source/features/table-input.tsx
- source/helpers/select-has.ts
- Closes #6508 
As seen in https://github.com/refined-github/refined-github/issues/6533
This should explicitly skip features that rely on the `has` selector.
May be incomplete but better than nothing.
Related:
- #5797
> Reduce `has` selector console noise in Firefox

- source/features/github-actions-indicators.tsx
- Closes #6529 
- This is my first PR. I'm good at VanilaJS and Chrome Extensions but not TypeScript.
Blaming my code is Welcome!
- May the next PR will be Impl #6443.
I've implemented it through the details component, but not Just with SVG Icon.
My low css skill is going to bother me.
- Thank you for maintaining this awesome project.
https://github.com/134130/134130/actions
> Show "Disabled" state in `github-actions-indicators`

- source/features/fit-textareas.tsx
Testable here. It works.
Ideal testing:
1. Find a tall message you wrote
2. Click edit
> Enable `fit-textareas` sooner, don't wait for focus

- readme.md
- source/features/list-prs-for-file.tsx
- Fixes https://github.com/refined-github/refined-github/issues/6299
For brevity and consistency, this now always uses a dropdown when displaying the PRs, regardless of count. This was also done in order to always have a small widget on `isEditingFile` and show the description inside.
- isSingleFile: One PR https://github.com/refined-github/sandbox/blob/default-a/4679
- isSingleFile: Multiple PRs https://github.com/refined-github/sandbox/blob/default-a/README.md
- isEditingFile: One PR https://github.com/refined-github/sandbox/edit/default-a/4679
- isEditingFile: Multiple PRs https://github.com/refined-github/sandbox/edit/default-a/README.md
> Restore `list-prs-for-file` 

- source/features/table-input.css
- Fixes https://github.com/refined-github/refined-github/issues/6511
In a comment box below
> Adjust `table-input` size on mobile

- source/features/show-names.tsx
- Fixes https://github.com/refined-github/refined-github/issues/6530
> Avoid `show-names` on the wrong links in the For You dashboard

- package-lock.json
Includes https://github.com/fregante/webext-polyfill-kinda/commit/8438cd88f245ca9a5bcfc7ced18a9d03a191e516
1. `webext-polyfill-kinda` always threw an error when accessing a missing property
2. `webext-options-sync` started using `webext-polyfill-kinda` in v4, including a call to `chromeP.management.getSelf()`
3. [#6448](https://github.com/refined-github/refined-github/pull/6448) started using `webext-options-sync` v4
4. 23.4.15 is the first Safari version that includes the above changes
5. Safari doesn't support `chrome.management`
6. Today: the RG icon doesn't nothing in Safari
```
TypeError: A Proxy's 'target' should be an Object
```
> Safari: Restore migrations and the actions button

- readme.md
- source/features/restore-file.tsx
- Continues #6596 
- Allow deletion via API
- "Drop" was a bit awkward, I replaced with with "Remove from PR"
https://github.com/refined-github/sandbox/pull/16/files
cc @134130
> `restore-file` UX improvements

- source/feature-manager.tsx
- source/options.html
- source/options.tsx
- Part of https://github.com/refined-github/refined-github/issues/6383
Pretty straightforward, it can make debugging a bit easier. I don't know if I want to expose the ability to disable hotfixes.
> Make CSS hotfixes visible in the options

- source/features/clean-repo-filelist-actions.tsx
- Fixes https://github.com/refined-github/refined-github/issues/6608
https://github.com/refined-github/sandbox
https://github.com/refined-github/sandbox/tree/branch/with/slashes
> Fix Code-button error in `clean-repo-filelist-actions`

- source/features/one-click-review-submission.tsx
- Fixes https://github.com/refined-github/refined-github/issues/6633
- Reworks #6619 
- https://github.com/refined-github/sandbox/pull/69/files
@busches are you able to test it? I think your version was also affected
> Restore PR review buttons on GitHub Enterprise

- source/features/clear-pr-merge-commit-message.tsx
- source/features/sync-pr-commit-title.tsx
- Due to https://github.com/refined-github/refined-github/pull/6584
This page (if not yet merged)
> `fit-textareas` after `clear-pr-merge-commit-message`

- source/features/default-branch-button.tsx
- source/features/download-folder-button.tsx
- source/features/fork-source-link-same-view.tsx
- source/features/warn-pr-from-master.tsx
- source/github-helpers/get-current-git-ref.test.ts
- source/github-helpers/get-current-git-ref.ts
- source/github-helpers/get-default-branch.ts
- source/github-helpers/github-url.ts
- source/github-helpers/index.ts
- source/github-helpers/prevent-link-loss.ts
- source/github-helpers/selectors.test.ts
- source/github-helpers/selectors.ts
- test/fixtures/globals.js
- Closes https://github.com/refined-github/refined-github/issues/6557
- Fixes issue introduced by https://github.com/refined-github/refined-github/pull/6629
A mistake that we keep making is mixing parameterized functions which then ignore the parameters and use the DOM. This must either be made clear by the function name (e.g. "current") or by verifying that the arguments match the current page. Default parameters are the worst because they make us forget this important distinction.
Related:
- https://github.com/sindresorhus/eslint-plugin-unicorn/issues/1864#issuecomment-1413182933
> Default branch and current branch detector improvements

- source/options.html
- source/options.tsx
- For https://github.com/refined-github/refined-github/issues/6092
> Add basic support for fine-grained tokens

- build/verify-features.ts
- source/background.ts
- source/feature-manager.tsx
- source/features/rgh-feature-descriptions.tsx
- source/helpers/feature-utils.ts
- source/options-storage.ts
- source/options.tsx
> Improve `rgh-feature-descriptions` links

- source/features/ci-link.tsx
Somehow this only happens in Chrome’s responsive view
https://github.com/refined-github/refined-github/assets/1402241/087b9ce2-7db0-45b6-a16c-0126b20a6301
https://github.com/refined-github/refined-github/assets/1402241/e5ed3992-41e8-4fe4-bd5c-c6e002a57ec8
> Fix `ci-link` duplicates on mobile

- source/features/clean-repo-sidebar.tsx
- Closes https://github.com/refined-github/refined-github/issues/6648
The homepage of one of your own repos, like
https://github.com/fregante/doma
> Ignore `clean-repo-sidebar` report link error

- source/features/open-all-notifications.tsx
- source/refined-github.css
- Partially reverts https://github.com/refined-github/refined-github/pull/5707
- https://github.com/notifications (sort by date OR repo)
> Fix notification action bar style

- source/features/restore-file.tsx
- source/github-helpers/get-pr-info.ts
- Fixes #4679 
This is the generated call:
```gql
mutation {
createCommitOnBranch(
input: {
branch: {
repositoryNameWithOwner: "refined-github/sandbox"
branchName: "4679-2"
}
expectedHeadOid: "6ad16fb97fd1a0dee13d5177cb0bb95448bfb2a5"
fileChanges: {
additions: [{ path: "4679", contents: "b3JpZ2luYWwgZmlsZQo=" }]
}
message: { headline: "Discard changes to 4679" }
}
) {
commit {
oid
}
}
}
```
> Use correct file after merges in in `restore-file`

- build/verify-test-urls.sh
- source/features/wait-for-checks.tsx
- source/github-helpers/pr-ci-status.ts
- source/github-helpers/selectors.test.ts
- source/github-helpers/selectors.ts
- Fixes #6321
Test URLs:
- https://github.com/refined-github/sandbox/pull/10
No Firefox support due to:
- #5797
> Restore `wait-for-checks` (no more Firefox support)

- source/features/status-subscription.tsx
Extracted from a discussion in https://github.com/refined-github/refined-github/pull/6667 cc @FloEdelmann 
This text doesn't add anything more to the state shown by the feature, except when "all" is selected, because it can be one of:
- You’re receiving notifications because you’re watching this repository.
- You’re receiving notifications because you authored the thread.
- You’re receiving notifications because you commented.
- You’re receiving notifications because you were mentioned.
- _who knows what else_
Here
> Hide reason text in `status-subscription`

- .xo-config.json
- build/verify-features.ts
- source/features/bugs-tab.tsx
- source/features/clean-conversation-filters.tsx
- source/features/comments-time-machine-links.tsx
- source/features/conversation-activity-filter.tsx
- source/features/deep-reblame.css
- source/features/deep-reblame.tsx
- source/features/fork-source-link-same-view.tsx
- source/features/highlight-deleted-and-added-files-in-diffs.tsx
- source/features/list-prs-for-file.gql
- source/features/list-prs-for-file.tsx
- source/features/pr-commit-lines-changed.tsx
- source/features/previous-version.tsx
- source/features/profile-gists-link.tsx
- source/features/repo-age.tsx
- source/features/restore-file.tsx
- source/features/show-open-prs-of-forks.tsx
- source/features/useful-not-found-page.tsx
- source/github-helpers/api.ts
- source/github-helpers/does-file-exist.tsx
- source/github-helpers/get-default-branch.ts
- source/github-helpers/get-pr-info.ts
- source/github-helpers/pr-ci-status.ts
- source/globals.d.ts
- source/options.html
- source/options.tsx
- webpack.config.ts
- Extracted from https://github.com/refined-github/refined-github/pull/6671
- Closes https://github.com/refined-github/refined-github/issues/5848
This PR
-  ✅  Adds support for variables
- ❌  Extracts GraphQL expressions into their own .gql files (https://www.apollographql.com/docs/react/integrations/webpack/)
This is harder than anticipated: 
- you can't include variable data in the JSON and not use them (i.e. no default user/repo)
- you can't just _use_ variables; each query must ALSO declare them…
```diff
- query {
+ query ($owner: String!, $name: String!) {
repository(owner: $owner, name: $name) {
```
Extensions suggested: 
- https://chrome.google.com/webstore/detail/graphql-network-inspector/ndlbedplllcgconngcnfmkadhokfaaln
- …
> Meta: Use variables in GraphQL

- source/background.ts
- https://github.com/fregante/webext-storage-cache/issues/3
Clear cache on reload.
While working a cached part of the extension, you expect a fresh version to appear every time you change the code. This setup also preserves the natural cache behavior without adding custom logic anywhere to shorten it.
Can't test `isExpired` (which we haven't been using) https://github.com/fregante/webext-storage-cache/issues/11#issuecomment-572206603
> Meta: Automatically clear cache on reload while developing

- source/features/conversation-activity-filter.css
Issue described in  https://github.com/refined-github/refined-github/issues/6437#issuecomment-1540526012
Already hotfixed on 23.5.10 and 23.5.20, but I don't want to see it anymore so I'll push this to main.
The issue is that the header is not regenerated between page loads and the lack of `.js-issues-results` element on the Files page leaves both icons visible.
The issue and final solution will be similar to what's required for:
- https://github.com/refined-github/refined-github/issues/6554
Which probably is: have features revalidate themselves and hide/remove themselves when the page changes.
> Hide `conversation-activity-filter` on PR Files tab

- source/features/last-notification-page-button.tsx
Main change here is the `-1` that is subtracted from the number of total notifications to make the calculation return the correct value for the cursor.
Other changes are renaming variables to make them more descriptive waht they contain.
Closes https://github.com/refined-github/refined-github/issues/6691
> Fix page number calculation in `last-notification-page-button`

- source/features/quick-review.tsx
Old bug. I was sure it was reported before but… nope.
I don't see any other "reasonable" positions so I'll just add a delay
Any PR
> Fix `quick-review` position due to race condition

- source/features/hide-user-forks.tsx
- Fixes https://github.com/refined-github/refined-github/issues/6687
https://github.com/wakamex?tab=repositories&type=source
> Fix: “Clear filters” doesn’t work due to `hide-user-forks`

- package.json
- For https://github.com/refined-github/refined-github/issues/6686
This PR only adds autocomplete support in your IDE, via https://marketplace.visualstudio.com/items?itemName=GraphQL.vscode-graphql
I thought getting the types out of the graphql files just required a TS plugin, but apparently you must _also_ run an additional generator. Plus all the documentation expects you to use an existing client like Apollo instead of a plain `fetch` like we do.
GitHub’s own API client does not support this out of the box either, you're supposed to write your own types: https://github.com/octokit/graphql.js/pull/99
I found https://github.com/Quramy/ts-graphql-plugin but there are a couple of issues I'm stuck on: https://github.com/Quramy/ts-graphql-plugin/issues?q=is%3Aissue+author%3Afregante
> Meta: Add graphql schema

- source/features/pr-base-commit.tsx
- source/helpers/dom-utils.ts
- Fixes https://github.com/refined-github/refined-github/issues/6651
- Fixes https://github.com/refined-github/refined-github/issues/6650
- Future: https://github.com/refined-github/refined-github/issues/6574
Console shows no error 
- I can merge: https://github.com/refined-github/sandbox/pull/60
- I can't merge: https://github.com/DanielMiao1/test/pull/8
> Fix `pr-base-commit` style on non-mergeable PRs

- source/features/toggle-files-button.css
- source/features/toggle-files-button.tsx
- Fixes https://github.com/refined-github/refined-github/issues/6284
- new chevron icon 🆕
- clicking it shows the native toggle 🆕
- reloading the page while collapsed preserves the states
- reloading the page after expanding it restores the state
https://github.com/refined-github/refined-github/assets/1402241/62ff90a9-f5d4-43f0-aee4-8da260bb3f1e
- starts collapsed as usual
- after uncollapsing, the collapse button appears 🆕
- reloading the page after expanding does not preserve the state 🆕 bug fix
https://github.com/refined-github/refined-github/assets/1402241/e0dd3d15-bff3-4710-9006-8f3b24f6c7fe
> Fix conflict with native mobile toggle in `toggle-files-button`

- source/features/conversation-activity-filter.css
- Closes https://github.com/refined-github/refined-github/issues/6663
https://github.com/electron/electron/issues/21457
> Fix `conversation-activity-filter` overlap with "Tracked in"

- source/features/ci-link.gql
- source/features/ci-link.tsx
- Closes https://github.com/refined-github/refined-github/issues/5863
- https://github.com/refined-github/github-url-detection
> Restore `ci-link` on repos that have generated commits

- build/prepare-safari-release.sh
- package-lock.json
- package.json
- source/manifest.json
- Fixes https://github.com/refined-github/refined-github/issues/6025
Context:
- Dynamic injection isn't fully possible in event pages with the current API: https://github.com/fregante/content-scripts-register-polyfill/commit/eac3418eb435e0e3e220721eee9ff5bee1a1804a
- iOS _only_ supports event pages
Solution:
- Ship regular background pages to desktop browsers
- Ship event pages to Safari/iOS
Future:
- #5531
> Restore full GitHub Enterprise support

- source/github-helpers/dom-formatters.tsx
- Fixes https://github.com/refined-github/refined-github/issues/5870
Super easy, barely an inconvenience.
In short:
1. GitHub sometimes defers the syntax highlighting and sends unformatted code
2. This code is wrapped in a `deferred-diff-lines` element with `awaiting-highlight` class
3. The new code is loaded via ajax and `awaiting-highlight` is removed
4. NOW we can run `show-whitespace` 
1. Open a fresh PR to find one that probably isn't cached by GitHub yet
2. Go to the Files tab
3. You can try again by picking a different commit in the PR commit dropdown
Notice how, for an instant, the code loaded after the commit selection is not syntax-highlighted. After the highlighting comes in, `show-whitespace` is also applied.
Before this PR, our whitespace would be applied before the …
> Fix: `show-whitespace` and `linkify-code` disappears after load

- source/features/download-folder-button.tsx
- Closes #6414 
- Related to https://github.com/refined-github/refined-github/issues/6554
- This also points the link to the correct folder, before it would get stuck
- This moves the link back into the dropdown, as the [feature screenshot](https://user-images.githubusercontent.com/46634000/158347358-49234bb8-b9e6-41be-92ed-c0c0233cbad2.png) showed
- I'm pretty sure that archived repos don't have a "Delete directory" link so it's now broken there
https://github.com/refined-github/refined-github/tree/main/source
> Restore `download-folder-button` on new file list UI

- .github/workflows/actionlint.yml
- .github/workflows/hotfixes.yml
Closes https://github.com/refined-github/refined-github/issues/6259
Tested in https://github.com/refined-github/sandbox/issues/3#issuecomment-1572361491 via https://github.com/refined-github/sandbox/actions/runs/5146817251
Example _(the message has since been changed)_
> CI: Leave reminder to update `broken-features`

- source/features/status-subscription.tsx
The button group for but the current label ("Subscribe just to the close event") is a little misleading because that subscription level also includes other status change events (e.g. merging a PR or reopening an issue). I slightly reworded the tooltip to be a bit more accurate.
This PR, for instance.
Before:
After:
> Adjust wording of `status-subscription`’s tooltip

- readme.md
- source/features/rgh-feature-descriptions.tsx
Fix some typos in features descriptions:
* Add "of" in "previous version **of** a file" ([readme.md:181](https://github.com/refined-github/refined-github/blob/c40cb294a25c25962389e0733e16afa162e22004/readme.md#L181))
* Add "are" in "whether files in commits and pull requests **are** being added or removed" ([readme.md:308](https://github.com/refined-github/refined-github/blob/c40cb294a25c25962389e0733e16afa162e22004/readme.md#L308))
* Add a final comma before "and" in "<kbd>g</kbd> <kbd>1</kbd>, <kbd>g</kbd> <kbd>2</kbd>, <kbd>g</kbd> <kbd>3</kbd>, and <kbd>g</kbd> <kbd>4</kbd>" ([readme.md:288](https://github.com/refined-github/refined-github/blob/c40cb294a25c25962389e0733e16afa162e22004/readme.md#L288))
* Add a final comma before "and" in "the raw version, the blame, and the history" …
> Meta: Fix typos in feature descriptions

- source/feature-manager.tsx
- Fixes https://github.com/refined-github/refined-github/issues/6568
Minor bug, lightweight fix
> Avoid duplicate `has-rgh` elements

- source/features/easy-toggle-commit-messages.tsx
Currently, `easy-toggle-commit-messages` feature will toggle the commit message when a click event triggers, which is not helpful if you want to select (and copy) something from the commit message.
This PR suppresses the toggle when text is selected.
Go to https://github.com/rust-lang/rust, expand the commit message, and select some text in expanded commit message.
Current: The commit message is elided (toggled)
After this PR: Text is selected
> Prevent `easy-toggle-commit-messages` when selecting text

- source/features/list-prs-for-file.tsx
This link is broken:
1. Visit https://github.com/bfred-it-org/github-sandbox/blob/branch/for-pr/README.md
2. Open PRs dropdown
3. Click any PRs
> Fix `list-prs-for-file` links

- source/features/hide-navigation-hover-highlight.css
- source/features/hide-navigation-hover-highlight.tsx
- Notifications list: https://github.com/notifications
- Issue list: https://github.com/refined-github/refined-github/issues
- React file list: https://github.com/refined-github/refined-github/tree/main/.github
- File list: https://github.com/refined-github/refined-github
> Restore `hide-navigation-hover-highlight` on files/notifications

- source/features/sticky-sidebar.css
- Fixes https://github.com/refined-github/refined-github/issues/6761
Any page
Strangely only the forks dropdown was broken. Now it works. We had the same issue before with the whole action bar
https://github.com/refined-github/refined-github/assets/1402241/318b81d1-0cba-4acb-a61c-95bdb3822e84
> Fix forks dropdown bug caused by `sticky-sidebar`

- source/refined-github.css
- Fixes https://github.com/refined-github/refined-github/issues/6749
- Caused by https://github.com/refined-github/refined-github/pull/6655
> Fix notifications action bar overflow

- source/feature-manager.tsx
- source/features/align-issue-labels.css
- source/features/clean-pinned-issues.css
- source/features/clean-repo-sidebar.css
- source/features/clean-repo-sidebar.tsx
- source/features/clean-rich-text-editor.css
- source/features/emphasize-draft-pr-label.css
- source/features/hide-diff-signs.css
- source/features/hide-navigation-hover-highlight.css
- source/features/hide-navigation-hover-highlight.tsx
- source/features/hide-newsfeed-noise.css
- source/features/minimize-upload-bar.css
- source/features/mobile-tabs.css
- source/features/no-unnecessary-split-diff-view.css
- source/features/scrollable-areas.css
- source/features/sticky-sidebar.css
- source/features/sticky-sidebar.tsx
Before Turbo unloads a page, it will reset the HTML and BODY classes, removing our classes too. This often causes FOUC because the page is still visible; `hide-navigation-hover-highlight` on the notifications or `clean-rich-text-editor` are the most visible.
Features that don't use these classes for CSS rules don't have to use attributes (e.g. a feature that adds a class to `body` only for `delegate` or `observe`)
> Avoid early style removal by GitHub on ajax navigation

- source/features/show-names.tsx
- Fixes https://github.com/refined-github/refined-github/issues/6793
This selector was introduced by:
- https://github.com/refined-github/refined-github/pull/6505
https://togithub.com/streetcomplete/StreetComplete/issues/5164
> Restore `show-names`

- source/features/github-bugs.css
This has annoyed me for quite a while: locked issues still have hoverable buttons. Notice how the button does not turn into a hand, but the background changes:
After:
Also tested on own reactions:
Test URL:
- https://github.com/refined-github/sandbox/pull/48
- https://togithub.com/RupertBenWiser/Web-Environment-Integrity/issues/28
> Dim unclickable reaction buttons

- source/features/hide-low-quality-comments.tsx
Hi everyone, thanks for the great extension!
This PR will fix the "VIP label" check to still show "low quality" comments if it was posted by a VIP like owner, maintainer, author etc. 
closes #6799 
The previous check is not working since the `.timeline-comment-label` has been removed at some point. The code now checks for the `.Label` class that is given to labels and then tests the innerHTML to be one of the VIPs defined in an array above.
https://github.com/sindresorhus/type-fest/issues/621 -> comment by repo owner is now shown
https://github.com/oslabs-beta/ReacTree/issues/35 -> if low quality comment was posted by non-VIP, comment is hidden
current behavior
behavior with PR
> Fix VIP label check for low quality comments

- .github/workflows/test.yml
The v2 version is deprecated.
https://github.com/actions/upload-artifact/releases/tag/v3.0.0
> Update actions/upload-artifact action to v3

- source/features/quick-comment-hiding.tsx
- Closes #6350 
- The `select` element has `required` attribute
- Chrome tried to focus `select` element for notify some alert like "empty value"
- But failed since `select` element is invisible.
```html
<select name="classifier" class="form-select mr-2" aria-label="Reason" required></select>
```
- https://github.com/refined-github/refined-github/issues/6350#issuecomment-1434102807
- **Before** (Error on dev-console)
- <img width="500px" src="https://github.com/refined-github/refined-github/assets/50487467/6db4840f-21bc-4dcb-abbb-bf3fadc6d07d">
- **After**
- <img width="500px" src="https://github.com/refined-github/refined-github/assets/50487467/3a204fc4-d1d1-415c-b664-97467f7c1baa">
> Restore `quick-comment-hiding`

- source/features/reactions-avatars.tsx
- source/features/release-download-count.tsx
- source/features/rgh-linkify-features.tsx
- source/features/tag-changes-link.tsx
Closes #6831
Hope I haven't missed every `isReleasesOrTags` usage
- https://github.com/refined-github/refined-github/releases/tag/23.7.25
* Before
* After
> Add missing `isSingleReleaseOrTag` when `isReleasesOrTags` usage

- source/features/linkify-code.tsx
- source/github-helpers/dom-formatters.tsx
* Closes #6841
Simply checks if the linkified URL is followed by `…`
`linkified.lastChild.textContent === '…'`
* https://github.com/search?q=repo%3AKatsuteDev%2FBackground+marketplace&type=code
> Discard truncated linkified URLs

- source/github-helpers/get-default-branch.ts
- Closes #6818
When visiting some pages which using `getDefaultBranch()` API, like repository's main page with enabling GitHub feature preview: `New Repository Overview`, The below error is occuring.
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'title')
at extractCurrentBranchFromBranchPicker (refined-github.js:3455:57)
at refined-github.js:4646:81
at async CachedFunction.updater (refined-github.js:4645:121)
at async getSet (refined-github.js:2344:30)
```
- The reason is `getDefaultBranch()` uses DOM-Selector
- `getDefaultBranch()` -> `fromDOM()` uses `export const branchSelector = '[data-hotkey="w"]';`
- We can fix the #6818 with adding option `awaitDomReady: true` to `repo-wide-file-finder`
- However, the other rgh-features which using …
> Improve support of New Repository Overview

- source/features/conflict-marker.gql
- source/features/conflict-marker.tsx
- Closes #6809
- Use new patterns
- element observing
- seperate gql
- https://github.com/pulls
- https://github.com/refined-github/refined-github/pulls
> Fix `conflict-marker` duplicated

- source/features/linkify-user-location.tsx
Due to a recent change in title-casing of the `aria-label` attribute of user location anchors in the GitHub UI, the selector used on [line 31 of `linkify-user-location.tsx`](https://github.com/refined-github/refined-github/blob/05099f2d2e0ba38d18b2145333e70eca86a68e2a/source/features/linkify-user-location.tsx#L31) is now invalid.
* [here](https://github.com/refined-github/refined-github/pull/6847)
* https://github.com/refined-github/refined-github/issues
* https://github.com/refined-github/refined-github/pulls
> Restore `linkify-user-location` in hover cards

- source/features/parse-backticks.tsx
* Closes #6806 
* Also enables backticks on subscription pages
* https://github.com/search?q=repo%3Arefined-github%2Frefined-github+is%3Aissue&type=issues
* https://github.com/search?q=repo%3Arefined-github%2Frefined-github+is%3Apr&type=pullrequests
* https://github.com/search?q=repo%3Acommunity%2Fcommunity+backticks+in+titles&type=discussions
* https://github.com/notifications/subscriptions
<details>
<summary>Search - Issue</summary>
</details>
<details>
<summary>Search - PR</summary>
</details>
<details>
<summary>Search - Discussions</summary>
</details>
<details>
<summary>Subscriptions</summary>
</details>
> Enable `parse-backticks` on search and subscription pages

- source/features/sticky-sidebar.tsx
- Fixes https://github.com/refined-github/refined-github/issues/6834
- Fixes https://github.com/refined-github/refined-github/issues/6408
Due to lack of `has` selector support
> Disable broken `sticky-sidebar` in Firefox

- source/features/clean-conversation-sidebar.tsx
- source/features/embed-gist-via-iframe.tsx
- source/features/file-age-color.tsx
- source/features/hide-newsfeed-noise.css
- source/features/linkify-code.tsx
- source/features/parse-backticks.tsx
- source/options.tsx
From https://github.com/refined-github/refined-github/issues/6000#issuecomment-1521431676
What I didn't touch:
- TODOs dated in the future
- selector-observer TODOs, for the most part
- has-selector-related TODOs
- TODOs dependent on external factors/libraries
> Meta: Fix some TODOs

- safari/Refined GitHub/MainScreen.swift
- safari/Refined GitHub/Utilities.swift
The review is requested on the second launch, and to not be annoying, it's only requested once ever. We kinda have to do it on the second launch as most don't even launch it a second time, even less a third time.
> Ask for review in the Safari extension app

- source/features/quick-file-edit.tsx
- Follows https://github.com/refined-github/refined-github/pull/6875
> Drop ability to `quick-file-edit` on permalinks

- source/features/mark-private-repos.css
- source/refined-github.ts
The official styling in each user's list of personal repositories makes it difficult to distinguish public from private repos at a glance.
This commit colors the "Private" label with GitHub's "attention" color so that it stands out more prominently.
closes #6656
`https://github.com/YOUR_USERNAME?tab=repositories`
> Add `mark-private-repos` feature

- source/features/pr-approvals-count.css
- Restoring workaround for Safari on other browsers.
- Related #6473
- https://github.com/pulls
- _**Cannot install `refined-github` on my MacOS. Can somebody help for testing this PR?**_
- Before
- After
> Add support for "minimum font size" browser setting in `pr-approvals-count`

- source/features/releases-tab.tsx
- source/github-helpers/selectors.ts
- Closes #6899
- `releases-tab` is not working when GitHub's Feature preview: `Global Navigation Update` is disabled.
- Since the `.UnderlineNav-body` count is 3 when disabled. More specifying with `ul.UnderlineNav-body` selector
- It works both of disabled and enabled
- Disabled
- Enabled
> Restore `releases-tab` when "Global Navigation Bar" is disabled

- readme.md
- source/features/unreleased-commits.tsx
- source/helpers/abbreviate-string.ts
- Closes #6851 
- Repo with no tags (no button)
https://github.com/refined-github/yolo
- Repo with too many unreleased commits
https://github.com/refined-github/sandbox
- Repo with some unreleased commits (If no button, check if is latest tag)
> Add support for New Repository Overview in `unreleased-commits`

- source/features/bugs-tab.tsx
- source/features/clean-repo-sidebar.tsx
- source/features/more-dropdown-links.css
- source/features/releases-tab.tsx
- source/github-helpers/index.ts
- source/github-helpers/selectors.ts
Following https://github.com/refined-github/refined-github/pull/6901 I took a further look at the feature and made some changes. See self-review
It might fix https://github.com/refined-github/refined-github/issues/6293, so I'll close it until I see that bug again.
> Faster `releases-tab` on repo home

- readme.md
- source/features/clean-repo-header.css
- source/features/clean-repo-header.tsx
- source/refined-github.ts
Reverts refined-github/refined-github#6759
The header is still long, ugly and it still causes a wrap and [Cumulative Layout Shift](https://web.dev/cls/).
We can restore it without making it disableable because _all_ of that information is visible in the sidebar, on the same page, as well as in the upcoming:
- #6900
> Restore `clean-repo-header` feature

- source/features/dim-bots.tsx
- source/features/hide-navigation-hover-highlight.tsx
This was annoying to do until now: ctrl-click multiple PRs.
This PR makes 2 changes:
- the bots won't undim when clicking on active elements 
- the bots won't undim when pressing _any_ keys
https://github.com/refined-github/refined-github/assets/1402241/5841672a-767f-4226-895a-095456313d81
https://github.com/mozilla/web-ext/pulls
> Disable `dim-bots` only when clicking on empty areas

- source/features/show-names.tsx
- Closes #6915 
- Fix `show-names` fetches redundant username on `followed article` in `GitHub newsfeed`
- https://github.com/ (some followed article)
> `show-names` - Exclude invalid elements on new dashboard

- source/features/unreleased-commits.tsx
- Closes #6922 
- Disabled via hotfix: https://github.com/refined-github/yolo/commit/4581c8158898b8a8e2e7abe0039aa33200b475ac
- Reason is described here: https://github.com/refined-github/refined-github/issues/6922#issuecomment-1723228576
- `New repository overview` disabled
- `New repository overview` enabled
> `unreleased-commits` - Restore support for old repository overview

- source/features/actionable-pr-view-file.tsx
- source/features/comments-time-machine-links.tsx
- source/features/conflict-marker.tsx
- source/features/deep-reblame.tsx
- source/features/default-branch-button.tsx
- source/features/linkify-branch-references.tsx
- source/features/list-prs-for-file.tsx
- source/features/more-file-links.tsx
- source/features/previous-version.tsx
- source/features/quick-file-edit.tsx
- source/features/rgh-dim-commits.tsx
- source/features/useful-not-found-page.tsx
- source/github-helpers/does-file-exist.tsx
- source/github-helpers/get-current-git-ref.ts
- source/github-helpers/github-file-url.test.ts
- source/github-helpers/github-file-url.ts
Since Firefox still fails, we can only rename the class.
- Replaces https://github.com/refined-github/refined-github/pull/6870
> Meta: Rename `GitHubURL` to `GitHubFileURL`

- source/features/link-to-changelog-file.tsx
Hello 👋 
This PR remove the additional `}` on the tooltip label of the link to the changelog file.
Have a great day ☀️ !
https://github.com/aws/aws-sdk-php/tags
> `link-to-changelog-file` - Drop extraneous character in tooltip

- source/features/previous-version.tsx
- Closes #6944
- The reason is css selector of `History` button has changed.
- `aria-label="History"` -> `aria-label="Commit history"`
https://github.com/refined-github/refined-github/blob/main/readme.md
> `previous-version` - Restore feature

- source/options.html
- source/options.tsx
- Closes https://github.com/refined-github/refined-github/issues/5760
- Closes https://github.com/refined-github/refined-github/issues/3535
- Closes https://github.com/refined-github/refined-github/issues/2684
I added this ability in "Debugging" to really discourage people from breaking the whole extension.
https://github.com/refined-github/refined-github/assets/1402241/dd7ffdf4-ad92-496f-9b4b-12dd376558d6
> Add buttons to toggle all features at once

- source/options.css
- source/options.html
- source/options.tsx
Occasionally javascript fails to run correctly in the browser, often in unsupported browsers, but this isn't not immediately clear because we currently show a partially-empty page.
> Only show the options if JS has loaded correctly

- source/features/one-click-review-submission.tsx
Fixes #6963.
GitHub have changed their review submission modal so that it:
- now has the radio buttons properly nested in a form
- the radios' labels are not adjacent siblings anymore
[This PR??](https://github.com/refined-github/refined-github/pull/6964)
https://github.com/refined-github/refined-github/assets/609062/be30dd75-a894-49e4-8023-9d7994165440
> Restore `one-click-review-submission` feature

- source/features/repo-header-info.tsx
> `repo-header-info` - Improve alignment 

- source/features/linkify-code.tsx
Fixes #6996
Retrieves the repository using the line url when getRepo doesn't work
`/notion-enhancer/notion-repackaged/blob/4eefa99dc1bcde18268d70bb2b7f050786229feb/scripts/extract-src.sh#L50`
↑ pull repo from this
https://github.com/search?q=repo%3Anotion-enhancer%2Fnotion-repackaged%20sqlite&type=code
https://github.com/search?q=org%3Arefined-github+%2F%23%5Cd%2B%2F&type=code
https://github.com/search?q=%2F%23%5Cd%7B4%2C%7D%2F+language%3Atypescript&type=code
---
> `linkify-code` - Fix issue links on global search pages

- source/features/highlight-collaborators-and-own-conversations.css
- source/features/small-user-avatars.css
- source/features/small-user-avatars.tsx
Fixes #7002 
Adds left margin to user avatars to better match word spacing
<table><td>
Hello world. @Katsute
<br>
Hello world. Omniscience 
</td></table>
<table><td>
@Katsute
<br>
Ordinary
</td></table>
↓
> `small-user-avatars` - Adjust spacing

- source/features/clean-rich-text-editor.css
> `clean-rich-text-editor` - Restore feature

- source/features/table-input.tsx
- Closes https://github.com/refined-github/refined-github/issues/7012
- Related to https://github.com/refined-github/refined-github/issues/7020
Here
The mobile UI still works too:
> `table-input` - Restore feature

- source/features/close-as-unplanned.tsx
Fix #7024
The `.js-comment-and-button` class is only for changing the text (see https://github.githubassets.com/assets/app/assets/modules/github/behaviors/commenting/close.ts), so our button doesn't need it.
#7024
[Kooha-2023-11-02-03-09-33.webm](https://github.com/refined-github/refined-github/assets/44045911/588cc07b-29e5-4f6f-bc26-1d98026a02ee)
> `close-as-planned` - Fix "close with comment" bug

- source/features/releases-tab.tsx
> `releases-tab`: Hide dropdown item when there are no releases

- source/features/link-to-changelog-file.tsx
Yet another broken DOM+API access. Let's just drop it
> `link-to-changelog-file`: Drop broken `parseFromDom`

- source/features/closing-remarks.tsx
- source/features/releases-tab.gql
- source/features/releases-tab.tsx
- Closes https://github.com/refined-github/refined-github/issues/6517
Releases: https://github.com/refined-github/refined-github
Tags: https://github.com/python/cpython
> `releases-tab`: Add support for tags-only repos

- source/features/pr-jump-to-first-non-viewed-file.tsx
This PR fixes the issue with the `pr-jump-to-first-non-viewed-file` feature by adapting the selector and tighten the check a bit by not only checking against the `firstNonViewedFile` value but also its `id`.
Fixes #7030
https://github.com/pixiebrix/pixiebrix-extension/pull/6808/files
> `pr-jump-to-first-non-viewed-file` - Restore feature in all PRs

- source/github-helpers/bugs-label.test.ts
- source/github-helpers/bugs-label.ts
Fixes #6882.
https://github.com/crim-ca/weaver
> `bugs-tab` - Support the labels `triage:bug` and `triage/bug`

- source/features/one-click-review-submission.tsx
- Fixes https://github.com/refined-github/refined-github/issues/7043
https://github.com/refined-github/refined-github/pull/7056/files
> `one-click-review-submission` - Fix "Abandon review" position

- source/options.html
I wasn't a fan of how the button invited every debugger to toggle all features
So I moved it into the section that the follow-up paragraph invites the user to use:
> Move "Toggle all features" into the "Identify feature" section

- source/github-helpers/api.ts
- Fixes https://github.com/refined-github/refined-github/issues/6988
Look for `repo-header-info`
1. Clear cache
2. Open this in a new tab https://github.com/sindresorhus/p-retry/releases/tag/v6.1.0
3. Click "separate package"
https://github.com/refined-github/refined-github/assets/1402241/e31d9b26-a514-4a80-81a6-f4e4857bbd8f
> Fix: Some features show information from the wrong/previous repository visited

- source/github-helpers/is-default-branch.ts
I noticed this while debugging https://github.com/refined-github/refined-github/issues/6988#issuecomment-1801165960
This affects 3 features but they're not as visible as `default-branch-button`
https://github.com/sindresorhus/is-network-error/tree/main/.github/workflows
> `default-branch-button` - Don't show on the default branch

- source/features/locked-issue.tsx
> `locked-issue` - Disable on GitHub Enterprise

- source/features/locked-issue.tsx
Every issue is marked as locked when logged out because logged out users cannot react.
cc @Katsute we might need an improved logic in the future, also considering:
- #7063 
1. Log out
2. Visit any conversation, like https://github.com/refined-github/refined-github/pull/7051
> `locked-issue` - Disable on logged out users due to false positives

- source/features/quick-mention.css
- source/features/quick-mention.tsx
- Closes https://github.com/refined-github/refined-github/issues/7070
- Bug exacerbated by #7054 
https://github.com/refined-github/refined-github/issues/1469
<table>
<tr>
<th>Before
<th>After
<tr>
<td><img width="430" alt="Screenshot 1" src="https://github.com/refined-github/refined-github/assets/1402241/d609a893-10dd-431b-a539-587255db9a48">
<td><img width="430" alt="Screenshot" src="https://github.com/refined-github/refined-github/assets/1402241/941484c3-915f-4511-92a7-927cb2f55fbd">
</table>
https://github.com/refined-github/refined-github/pull/7069
<table>
<tr>
<th>Before
<th>After
<tr>
<td><img width="239" alt="Screenshot 2" src="https://github.com/refined-github/refined-github/assets/1402241/a651fe3d-0343-4d37-8888-835b1b16de51">
<td><img width="239" alt="Screenshot 3" …
> `quick-mention` - Fix "locked issue" detection

- source/features/vertical-front-matter.tsx
- Close https://github.com/refined-github/refined-github/issues/6865
It seems that the issue was caused by GitHub reloading/rehydrating the content.
Using the new observer also somewhat improves the feature, however this is still an issue:
- https://github.com/refined-github/refined-github/issues/6554
https://github.com/github/docs/blob/main/content/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github.md?rgh-link-date=2023-09-01T21%3A37%3A35Z
> `vertical-front-matter` - Fix flickering/loss of the feature on content rehydration

- source/features/locked-issue.css
- source/features/locked-issue.tsx
Resolves a bug that was introduced in https://github.com/refined-github/refined-github/pull/7051/commits/ce78ed0e096ec86c321c8a7e5f4e5996551f7f40 ; commit inadvertently put `d-flex` and `rgh-locked-issue` in the same element causing this css issue.
The css used to re-hide the lock state on update was not active because `d-flex` was taking precedence.
Test requires looking at an issue as it is being unlocked
https://github.com/refined-github/sandbox/issues/74
`display: none` now takes precedence
> `locked-issue` - Remove after unlocking issue

- readme.md
- source/features/mark-merge-commits-in-list.tsx
- source/features/tags-on-commits-list.tsx
close: #7045 
https://github.com/refined-github/refined-github/commits/19.5.21.1921
before:
after:
> `tags-on-commits-list` - Support new commit list style

- source/features/default-branch-button.tsx
- source/github-helpers/is-default-branch.ts
https://github.com/typed-ember/ember-cli-typescript/commits/master
> `default-branch-button` - Fix mistaken display on commits list

- source/features/mark-merge-commits-in-list.tsx
- closes https://github.com/refined-github/refined-github/issues/6852
- isPRConversation: https://github.com/refined-github/refined-github/pull/6194
- isCommitList (untouched): https://github.com/typed-ember/ember-cli-typescript/commits/master?after=5ff0c078a4274aeccaf83382c0d6b46323f57397+174
I think it gives it too much weigh
Can't do it because GitHub does that when the commit is just a reference from elsewhere.  See https://github.com/refined-github/refined-github/pull/3015
> `mark-merge-commits-in-list` - Avoid duplicating icon

- source/features/select-notifications.tsx
- Closes https://github.com/refined-github/refined-github/issues/6980
I think "others" includes
- new tags
- comments on commits
- discussions
- deployments
- cancelled actions, if notifications are active
- dependabot alerts?
> `select-notifications` - Add filter for "Anything other than issues and PRs"

- readme.md
- source/features/visit-tag.tsx
- source/refined-github.ts
- Closes https://github.com/refined-github/refined-github/issues/6499
- https://github.com/refined-github/refined-github/tree/23.11.15
- https://github.com/refined-github/refined-github/blob/23.4.10/.editorconfig
- https://github.com/refined-github/refined-github/releases
- https://github.com/refined-github/refined-github/releases/tag/23.11.15
> `visit-tag` - New feature

- source/features/mark-merge-commits-in-list.tsx
Use `observe` and `batchedFunction`
- isCommitList: [typed-ember/ember-cli-typescript@master?after=5ff0c078a4274aeccaf83382c0d6b46323f57397+174 (commits)](https://github.com/typed-ember/ember-cli-typescript/commits/master?after=5ff0c078a4274aeccaf83382c0d6b46323f57397+174)
new view:
old view:
> `mark-merge-commits-in-list` - Use selector-observer

- source/features/small-user-avatars.tsx
Fix #7137 based on https://github.com/refined-github/refined-github/issues/7137#issuecomment-1839574252
https://github.com/sopel-irc/sopel/commit/120477fe28f470f9308163203c43688ff9121e12
Before:
After:
----
Verified that small-user-avatars are still added on regular mentions in comments, e.g. https://github.com/sopel-irc/sopel/pull/2533#issuecomment-1784202911
> `small-user-avatars` - Don't mistakenly add to commit authors

- source/features/link-to-changelog-file.tsx
- source/features/unreleased-commits.tsx
- Extracted from https://github.com/refined-github/refined-github/pull/7121
- #6977 
- Can release: https://github.com/refined-github/sandbox/releases
- Cannot release: https://github.com/facebook/react/releases
- Cannot release, has changelog file https://github.com/fczbkk/css-selector-generator/releases
- It's missing from the tag page for now
> `unreleased-commits` - Show on Releases page

- source/features/small-user-avatars.tsx
Fixes an error in the implementation of #7139 as shown [here](https://github.com/refined-github/refined-github/pull/7139#issuecomment-1858889250). (As I [said](https://github.com/refined-github/refined-github/pull/7139#issuecomment-1839706110), I'm clearly not a JS dev!)
Commit header (don't add): https://github.com/sopel-irc/sopel/commit/120477fe28f470f9308163203c43688ff9121e12
Release notes (add): https://github.com/refined-github/refined-github/releases/tag/23.12.1
Comment mention (add): https://github.com/sopel-irc/sopel/pull/2533#issuecomment-1784202911
Still not adding extra avatars to commit header:
Plus additional verification that the feature is working as expected in expected places, in release notes:
In a comment:
If always using `link.firstChild` proves to be more fragile than …
> `small-user-avatars` - Restore feature

- source/features/link-to-github-io.tsx
Fixes #7159 
https://github.com/orgs/Qv2ray/repositories?q=GitHub.io
> `link-to-github-io` - Support new organization repository list style

- source/features/one-click-diff-options.tsx
Fixes #7184 
https://github.com/rancher/rancher/commit/e82921075436c21120145927d5a66037661fcf4e
https://github.com/refined-github/sandbox/commit/96451b68751d9807d5da0964868f418c5eeee148
> `one-click-diff-options` - Disable on single commits

- source/features/conversation-links-on-repo-lists.tsx
Fixes #7173 
* https://github.com/orgs/refined-github/repositories
> `conversation-links-on-repo-lists` - Disable on organizations

- source/features/rgh-dim-commits.tsx
Fix #7179
https://github.com/refined-github/refined-github/commits/98fb24e53704b436d68f254429885fb7bef09541/source/features/bypass-checks.tsx
> `rgh-dim-commits` - Add support for new commit view

- source/features/fit-textareas.tsx
Closes https://github.com/refined-github/refined-github/issues/7196.
Make `fit-textareas` listen to focus events to resize.
https://github.com/refined-github/refined-github/issues/new?assignees=&labels=bug&projects=&template=1_bug_report.yml
<table>
<tr>
<td> Previously
<td> With fix
<tr>
<td> <video src="https://github.com/refined-github/refined-github/assets/23154723/3ea3dca7-a2ac-4954-8b14-cd4ba649cc9a">
<td> <video src="https://github.com/refined-github/refined-github/assets/23154723/0622f800-703a-4142-8892-191b555d884d">
</table>
> `fit-textareas` - Fit on focus

- source/features/conversation-links-on-repo-lists.tsx
Fixes #7174
https://github.com/search?q=user%3Afregante&type=repositories
> `conversation-links-on-repo-lists` - Restore on global search

- build/verify-test-urls.sh
- source/features/github-bugs.css
Fix https://github.com/refined-github/refined-github/issues/7187.
Rendered markdown div automatically fit their content, but for some reason Github explicitly sets the `min-height` style property to the height of the input textarea.
Simply overriding the `min-height` to `0` fixes this bug.
Affects any div that renders markdown.
| Input | Original | Fixed |
|--------|--------|--------|
| <img width="846" alt="image" src="https://github.com/refined-github/refined-github/assets/23154723/684c367a-924d-4fd6-b5bc-7b956e633aee"> | <img width="847" alt="image" src="https://github.com/refined-github/refined-github/assets/23154723/9f5e12bc-e41b-4e7e-b12b-c9c41ee6d56c"> | <img width="846" alt="image" src="https://github.com/refined-github/refined-github/assets/23154723/ea44d760-bd5a-4025-8c6d-de9ff8b …
> Automatically fit comment preview height

- source/features/quick-comment-hiding.tsx
Fixes #7171.
The assignment of `newForm.className` removes the existing class `.js-comment-minimize`. I haven't scrutinized the implementation code, but this solution seems to work:
```diff
-	newForm.className = ['dropdown-menu', 'dropdown-menu-sw', 'color-fg-default', 'show-more-popover', 'anim-scale-in'].join(' ');
+	newForm.className = ['js-comment-minimize', 'dropdown-menu', 'dropdown-menu-sw', 'color-fg-default', 'show-more-popover', 'anim-scale-in'].join(' ');
```
https://github.com/refined-github/refined-github/issues/7171#issuecomment-1893057145 or any comment you can hide it.
https://github.com/refined-github/refined-github/assets/18693190/e51f2a67-84e6-42c7-8f5a-27048f3f8696
> `quick-comment-hiding` - Use AJAX again

- source/features/deep-reblame.css
- source/features/deep-reblame.tsx
- Fixes https://github.com/refined-github/refined-github/issues/6838
- Follows https://github.com/refined-github/refined-github/pull/7114
https://github.com/refined-github/refined-github/blame/af0dd20dde497ac9dcec9cda47bee80902121298/source/features/deep-reblame.tsx#L5
> `deep-reblame` - Restore feature

- source/features/show-names.tsx
- Presumably fixes https://github.com/refined-github/refined-github/issues/7232
- Presumably fixes https://github.com/refined-github/refined-github/issues/3204
The attribute was mentioned and fixed before: https://github.com/refined-github/refined-github/issues?q=show_full_name
> `show-names` - Avoid duplicates on GitHub Enterprise

- source/features/clean-conversation-filters.tsx
- source/features/convert-release-to-draft.tsx
- source/features/list-prs-for-branch.tsx
- source/features/new-repo-disable-projects-and-wikis.tsx
- source/features/pr-base-commit.tsx
- source/features/quick-label-removal.tsx
- source/features/quick-repo-deletion.tsx
- source/features/quick-review.tsx
- source/features/rgh-improve-new-issue-form.tsx
- source/features/unreleased-commits.tsx
- source/features/update-pr-from-base-branch.tsx
- source/github-helpers/api.ts
- source/github-helpers/github-token.ts
- source/options.tsx
- Closes: #7261
- Centralize token-management helper
- Previously, github-token management was separated to "for option" and "for features"
NOTE: Only occurs on my private repositories (SAML required Organization)
[refined-github/refined-github/pulls](https://github.com/refined-github/refined-github/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc)
> `clean-conversation-filters` - fix token permission error

- source/refined-github.css
GitHub recently seems to have changed its `--color*` vars to `--fgColor*`/`--bgColor*`. This updates the `--rgh*` color vars to use the new names, as leaving them at defaults causes issues in colorblind/dark themes.
Note that `--fgColor-danger` in Default Light Mode is now `#d1242f` which differs from the previously (still) defined default we have of `#cf222e` (now on `--bgColor-danger-emphasis`, among other vars). I am colorblind so I will need someone else to tell me if this is a significant difference and/or if the default value should also be updated for `--rgh-red`.
Also note that `--borderColor-muted` in Default Light Mode is now `#d0d7deb3` which differs from our default of `#d8dee4`. A var with this color is no longer present in Default Light Mode, but we can consider changing it …
> Fix colors on dark themes 

- source/features/previous-next-commit-buttons.tsx
Fix for #7234 
Tested on Firefox and Chrome.
[Lundalogik/lime-elements@`9726b8f` (#2739)](https://github.com/Lundalogik/lime-elements/pull/2739/commits/9726b8f50a4d27fb297fda2e6d496a3f109a5c26)
Before:
After:
> `previous-next-commit-buttons` - Restore feature

- source/features/github-actions-indicators.tsx
close: #7282 
[AlmostReliable/almostunified/actions/workflows/release.yml](https://github.com/AlmostReliable/almostunified/actions/workflows/release.yml)
> `github-actions-indicators` -  Restore feature

- source/features/unfinished-comments.tsx
With GitHub having both 'Pull-Requests' and 'Draft Pull Requests', it may be confusing for users to understand that the 'Draft' in the document title refers to a unfinished comment rather than a Draft PR.
> `unfinished-comments` - Drop "Draft" from the tab title prefix

- source/features/repo-avatars.tsx
- source/github-helpers/get-user-avatar.ts
Closes #7322
I've added a new optional parameter `ignoreBots`, for the `repo-avatars` scene.
- https://github.com/simple-icons/simple-icons/pull/10728
> `repo-avatars` - Fix wrong organization avatar

- source/features/locked-issue.tsx
- source/features/quick-comment-edit.tsx
- source/features/quick-review-comment-deletion.tsx
- source/features/show-whitespace.tsx
- source/helpers/7116.tsx
- replace `exclude: [isBadBrowserOnPrFiles]` with `asLongAs: [isChrome]` in the `locked-issue`, `quick-comment-edit`, `quick-review-comment-deletion` and `show-whitespace`
Changes according the the proposal in the https://github.com/refined-github/refined-github/issues/7316#issuecomment-2034018693
> Completely disable 4 slow features in Firefox/Safari

- source/features/locked-issue.css
- source/features/locked-issue.tsx
- source/features/quick-comment-edit.css
- source/features/quick-comment-edit.tsx
- source/features/quick-mention.tsx
- source/features/readable-title-change-events.css
- Follows the advice in https://github.com/refined-github/refined-github/issues/7331#issuecomment-2120464245
- Part of https://github.com/refined-github/refined-github/issues/5797
- Reverts https://github.com/refined-github/refined-github/pull/7075
URL: https://github.com/refined-github/sandbox/issues/74
GitHub seems to be reloading the whole page when locked/unlocked, so I dropped the additional CSS rule.
https://github.com/refined-github/refined-github/assets/1402241/bdcb2dd4-0ba8-4a99-85bb-abdc96841379
URL: https://github.com/refined-github/sandbox/pull/10
Alignment but must be reported/fixed separately
URL: Below
> Improve `has`-selector performance

- source/features/unreleased-commits.tsx
Close #7375.
Since the branch picker sets the width to 100%, the unreleased commits button group will shrink in a flexbox.
Set `flex-shrink: 0` solves this problem, it will let the width of the button group grow from its min-content.
> `unreleased-commits` - Avoid internal wrapping

- source/features/clean-conversation-sidebar.tsx
Closes #7235 
* Data action of create branch corrected from `click:create-issue-branch#openDialog` to `click:create-branch#openDialog` so that it will be added to the heading when the section is collapsed
* Section will not be hidden or collapsed if the "Open in Workspace" button is in the Development section (currently a feature in limited technical preview)
Affects Issues pages
* https://github.com/refined-github/refined-github/issues/7235
* https://github.com/DenverCoder1/readme-typing-svg/issues/295
* https://github.com/DenverCoder1/readme-typing-svg/issues/21
Not logged in:
----
Logged in, no edit access, no Copilot Workspace access, no linked issues:
----
Logged in, no edit access, no Copilot Workspace access, has linked issues:
----
Logged in, has edit access, no Copilot Workspace …
> `clean-conversation-sidebar` - Restore mistakenly-hidden links

- source/features/quick-review.tsx
- Closes #7272
- GitHub changed to use [Top Layer](https://developer.mozilla.org/en/docs/Glossary/Top_layer) with [Popover API](https://developer.mozilla.org/en/docs/Web/API/Popover_API) on modal elements.
- And the [docs](https://developer.mozilla.org/en-US/docs/Web/API/Popover_API#interfaces) says popover triggers `ToggleEvent` when they called. but `lib.dom.ts` is typed with `Event` maybe for backward compatibility.
- So I hacked the type like `(event as unknown) as ToggleEvent`
- Open [refined-github/sandbox#12 (files)](https://github.com/refined-github/sandbox/pull/12/files#review-changes-modal)
See the field not being focused
https://github.com/refined-github/refined-github/assets/50487467/fd653e1b-e25b-4a5c-8ac5-52eddc5c26c5
> `quick-review` - Restore auto-focus

- source/features/close-out-of-view-modals.tsx
- Closes https://github.com/refined-github/refined-github/issues/7093
- Dropdowns in conversation sidebar: https://github.com/refined-github/sandbox/issues/3
- Star/Watch dropdowns: https://github.com/refined-github/sandbox
> `close-out-of-view-modals` - Fix conflict with Development menu

- source/features/swap-branches-on-compare.tsx
- Fixes https://github.com/refined-github/refined-github/issues/7102
- Compare: https://github.com/refined-github/refined-github/compare/23.2.1...main
- Blank but valid: https://github.com/refined-github/refined-github/compare/23.11.15.1433...23.11.15
- Blank but unswappable: https://github.com/refined-github/refined-github/compare
> `swap-branches-on-compare` - Show when list is empty

- source/features/quick-label-removal.tsx
- Reverts #4939
- Will fix https://github.com/refined-github/refined-github/issues/6862
Here
https://github.com/refined-github/refined-github/assets/1402241/4f7f33a4-49b5-49d3-b049-da857396287a
The dropdown is emptied but it still works afterwards
https://github.com/refined-github/refined-github/assets/1402241/fd091eff-636a-4b73-b1e1-f9c63d57657a
> `quick-label-removal` - Don't restore labels when adding some

- package-lock.json
- package.json
- source/background.ts
- closes https://github.com/refined-github/refined-github/issues/7381
- includes https://github.com/fregante/webext-alert/pull/4
I also tried to follow the removal with `.request(GitHub.com)` but that didn't work.
> Stop allowing "all urls" as a permission

- source/features/github-actions-indicators.tsx
- Fixes https://github.com/refined-github/refined-github/issues/7389
Manual + scheduled:
https://github.com/sindresorhus/type-fest/actions/workflows/ts-canary.yml
Manual + disabled + pinned:
https://github.com/refined-github/sandbox/actions
> `github-actions-indicators` - Restore feature

- source/features/default-branch-button.tsx
- Fixes https://github.com/refined-github/refined-github/issues/7098
- Fixes part of https://github.com/refined-github/refined-github/issues/6554
- https://github.com/refined-github/sandbox/tree/locked/.github/workflows
Changing the theme now no longer duplicates the button, but since React rebuilds the branch selector, it no longer has a "button group" class. For #6554 we'll likely have to just track the React element removal and remove the attached element.
> `default-branch-button` - Various fixes

- source/features/one-click-review-submission.tsx
I know the `actionsRow` changes need to be reverted, I'll check the April 2024 comments in the AM as well.
> `one-click-review-submission` - Restore GHE support

- source/features/fit-textareas.css
- source/features/fit-textareas.tsx
- Closes https://github.com/refined-github/refined-github/issues/7414
After this PR:
- Chrome 123+: uses `field-sizing`
- Firefox and Chrome 122: uses `fit-textarea@2` module
- Safari: enabled only when `field-sizing` will be available
- Since `fit-textarea` can introduce new performance issues, I'd rather not enabled it
Tracking issues:
- https://bugzilla.mozilla.org/show_bug.cgi?id=1832409
- https://bugs.webkit.org/show_bug.cgi?id=264720
Here
See how the field is resized without any changes to the DOM
https://github.com/refined-github/refined-github/assets/1402241/ea600268-3c99-4172-a84d-f363c5ed1e34
> `fit-textareas` - Enable CSS-native feature where available

- source/options.html
Allow users to use an GitHub OAuth token (`gho_...`). Right now the form validation regex prevent me from even using it.
For example, I am using the one from the GitHub CLI (`gh auth token`). GitHub's OAuth app has as much permissions as one can grant and should be sufficient for refined-github usage.
My organization does not allow PATs (`ghp_...`) to access GH.
Related to:
- https://github.com/refined-github/refined-github/issues/6951
- https://github.com/refined-github/refined-github/issues/6092#issuecomment-1732286938
n/a
n/a
> Accept OAuth tokens in the options

- package-lock.json
- package.json
- source/features/locked-issue.tsx
- Continues from https://github.com/refined-github/refined-github/pull/7378
- Partially reverts #7315 
That PR reduced the `:has()` subtree size, this PR just drops it.
This means the feature can be re-enabled for all users.
- Locked issue: https://github.com/refined-github/sandbox/issues/74
- Locked PR: https://github.com/refined-github/sandbox/pull/48
> `locked-issue` - Fix performance issues

- source/features/deep-reblame.tsx
- source/features/open-all-notifications.tsx
- source/features/status-subscription.tsx
- source/github-helpers/index.ts
- Closes https://github.com/refined-github/refined-github/issues/6273
I picked P because it's near O (the one used to open the focused item). Alt-Shift-O would have been an alternative too, but unnecessary at this point since P seems unused.
> `open-all-notifications` - Add keyboard shortcut: P

- source/features/bugs-tab.tsx
- source/features/sort-conversations-by-update-time.tsx
- source/github-helpers/search-query.test.ts
- source/github-helpers/search-query.ts
- source/github-helpers/selectors.ts
- Closes #7415 
This PR:
- makes it easier to alter the query by prepending the sort instead of appending it
- excludes `&page=` links outside the pagination widget as well
- moves some exclusion filters into the selector
Live link:
- https://github.com/refined-github/refined-github/pulls
Should become:
```diff
- https://github.com/refined-github/refined-github/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc
+ https://github.com/refined-github/refined-github/pulls?q=sort%3Aupdated-desc+is%3Apr+is%3Aopen
```
> `sort-conversations-by-update-time` - Various improvements

- package-lock.json
- package.json
- source/background.ts
- source/helpers/feature-utils.ts
1. No relevant issue found
This change is made to detect if the user is on a mobile platform (ios or android), instead of just looking for mobile Safari, or explicitly checking for user agents of mobile browsers.
Mobile safari, and other mobile browsers like Kiwi and Firefox for Android do not support context menus. 
This change allows android browsers to access the options page.
`getPlatformInfo` seems to have fairly wide browser support, so it should be fine to use, instead of checking the user agent, like `webext-detect-page` does. 
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/getPlatformInfo
This method is used, because `webext-detect-page` does not seem to have functions to detect mobile browsers other than Safari.
This has only been tested on …
> Improve support for mobile Firefox

- .github/workflows/release.yml
- build/manifest.js
- package.json
- Fixes #7477 
- Related https://github.com/refined-github/refined-github/pull/7480
This should work, assuming AMO doesn't block manifest downgrades.
The manifest.json in `source` will continue to work in both browsers.
cc @INSANEMODE @HanabishiRecca
> Avoid "Permission needed" bug on Firefox for now

- source/features/show-whitespace.tsx
- Partially reverts https://github.com/refined-github/refined-github/pull/7315
- Related to #7404
> `show-whitespace` - Restore feature on Firefox and Safari

- source/features/visit-tag.tsx
Fix #7491
I think I still remember how to do RGH PRs 😂 
https://github.com/refined-github/refined-github/assets/44045911/5d308061-c452-4fe2-bde2-895fcfd1dd89
> `visit-tag` - Work around GitHub tag picker icon bug

- source/features/tags-on-commits-list.tsx
Fix #7459
I only updated the selector. Further work may include moving them to `selectors.ts` (which is a new thing to me) and also migrate from the deprecated `cache` function.
https://github.com/refined-github/refined-github/commits/main/
> `tags-on-commits-list` - Restore feature

- source/options.css
Resolve #7483
I only tested this in (desktop) Chrome since the smaller font seems to be a Chrome only thing. ~~In other browsers the change should make no difference.~~
I do anticipate we need to tweak a few other sizes to make it look perfect (see the logo for example).
chrome-extension://<RGH>/assets/options.html
> Larger text size in the options

- source/features/list-prs-for-file.tsx
- source/github-helpers/index.ts
- source/refined-github.css
Fix #7468
https://github.com/pypi/warehouse/blob/main/warehouse/packaging/models.py
> `list-prs-for-file` - Prevent symbols panel overlapping

- source/options.css
- source/options.tsx
🚫 NO FUNKY MOVE ALLOWED
`chrome-extension://<RGH>/assets/options.html`
<table>
<thead>
<tr>
<td>Before
<td>After
</tr>
</thead>
<tbody>
<tr>
<td>
https://github.com/refined-github/refined-github/assets/44045911/0120e4db-9f35-4536-b3d7-3a47b8ebfce7
<td>
https://github.com/refined-github/refined-github/assets/44045911/e4ea3f9c-2f1c-46d4-b821-eef4bd374d0f
</tobdy>
</table>
> Prevent options checkbox position change

- source/features/netiquette.tsx
Use the same selector as in #7514. Unfortunately this currently only works with inline comments on the Conversation page since `wasClosedLongAgo()` etc. only works there.
https://github.com//nodejs/node/pull/43689#discussion_r915109802
> `netiquette` - Support review comments

- source/features/small-user-avatars.tsx
Closes #7509
small-user-avatars disabled:
|Before|After|
|---|---|
| <img width="672" alt="SCR-20240701-rctj" src="https://github.com/refined-github/refined-github/assets/17134256/2fb3148f-6732-4b55-8b37-7cc275c2cae4"> |<img width="685" alt="SCR-20240701-rcwp" src="https://github.com/refined-github/refined-github/assets/17134256/ec8c729c-ffbd-48be-aad5-1dd108228465"> |
small-user-avatars enabled:
|Before|After|
|---|---|
| <img width="739" alt="SCR-20240701-rcjn" src="https://github.com/refined-github/refined-github/assets/17134256/2a649bd2-b2bd-4dbf-9522-68cfd6543a00"> |<img width="719" alt="SCR-20240701-rcct" src="https://github.com/refined-github/refined-github/assets/17134256/c1aa09d3-4e52-4a74-8728-5feea65d39a2"> |
> `small-user-avatars` - Fix misalignment 

- build/__snapshots__/features-meta.json
- readme.md
- source/features/comment-on-draft-pr-indicator.tsx
Resolve #7438
https://github.com/refined-github/sandbox/pull/7
Regular
Inline
> `comment-on-draft-pr-indicator` - Create `netiquette`-like banner

- source/features/conversation-links-on-repo-lists.tsx
Closes https://github.com/refined-github/refined-github/issues/7520
1. open [github.com/search?q=%22webext%22&type=repositories](https://github.com/search?q=%22webext%22&type=repositories)
2. Click "Code" in the sidebar
3. Notice extra links
4. Refresh the page
5. The links are gone
1. open [github.com/search?q=%22webext%22&type=code](https://github.com/search?q=%22webext%22&type=code)
2. Click "Repositories" in the sidebar
3. The links are gone
4. Refresh the page
5.  links show
Before:
After: 
|
> `conversation-links-on-repo-lists` - Improve AJAX support

- source/features/action-pr-link.tsx
Closes #7534
Fix `action-pr-link` runLink element null
https://github.com/refined-github/refined-github/actions
Before
After
> `action-pr-link` - Restore feature on Actions tab

- source/features/clean-repo-sidebar.css
- source/features/clean-repo-sidebar.tsx
- Fixes https://github.com/refined-github/refined-github/issues/7544
- Replaces and closes https://github.com/refined-github/refined-github/pull/7532
- Repo with packages: https://github.com/recyclarr/recyclarr
> `clean-repo-sidebar` - Show packages if not empty

- package-lock.json
- package.json
- source/github-events/on-react-page-update.tsx
- source/helpers/selector-observer.tsx
We've been having an issue upgrading TS since 5.3. It's failing here:
https://github.com/refined-github/refined-github/blob/f34c0a9c06e94cb82c0724cbe627c0d610ebdc13/source/helpers/fetch-dom.ts#L8
https://github.com/refined-github/refined-github/blob/f34c0a9c06e94cb82c0724cbe627c0d610ebdc13/source/helpers/selector-observer.tsx#L12-L15
```ts
Error: source/helpers/fetch-dom.ts(8,81): error TS2344: Type 'ParseSelector<Selector, HTMLElement>' does not satisfy the constraint 'HTMLElement'.
Type 'HTMLElement | (ExpandAnd<string & ParseSelectorToTagNames<Selector>, HTMLElement> extends Element ? Element & ExpandAnd<...> : HTMLElement)' is not assignable to type 'HTMLElement'.
Type 'ExpandAnd<string & ParseSelectorToTagNames<Selector>, HTMLElement> extends Element ? Element & ExpandAnd<...> : …
```
> Bump TypeScript to v5.5

- source/features/comment-on-draft-pr-indicator.tsx
- source/github-helpers/index.ts
Fix #7541
- https://github.com/refined-github/sandbox/pull/7
| | Before | After |
|--------|--------|--------|
| Own PR | <img width="404" alt="Screenshot 2024-07-21 at 9 24 56 PM" src="https://github.com/user-attachments/assets/b6fc59e3-b303-4da1-89d1-899ec0ae1322"> | <img width="408" alt="Screenshot 2024-07-21 at 9 24 24 PM" src="https://github.com/user-attachments/assets/6cdc2fb7-ef9e-41e9-8c4c-35fa75571707"> |
| New & edit comment | <img width="788" alt="Screenshot 2024-07-21 at 9 25 30 PM" src="https://github.com/user-attachments/assets/84bbd8a1-462c-4d79-8182-a9383cc62399"> | <img width="789" alt="Screenshot 2024-07-21 at 8 38 16 PM" src="https://github.com/user-attachments/assets/bbcac98f-601d-48c5-b1d2-cd14e3776fe7"> |
> `comment-on-draft-pr-indicator` - Avoid appearing on wrong places

- source/github-helpers/index.ts
close: #7549 
When `default-branch-button` appears in the header, we can find the closet container element so it works fine!
But whetn it appears in the sidebar, the closet container element is null. And I think we don't need to add `rgh-z-index-5` class in this situation.
> `default-branch-button` - Restore feature in sidebar

- source/features/draft-pr-notice.tsx
- source/features/netiquette.tsx
Fix #7612
- Draft PR: https://github.com//refined-github/sandbox/pull/7
- Old PR: https://github.com//facebook/react/pull/209
`draft-pr-notice`
https://github.com/user-attachments/assets/840956f9-6427-4823-a2eb-a502c4be0df8
`netiquette`
https://github.com/user-attachments/assets/0c63ad0c-8a89-49d6-bfba-0701277517de
> `netiquette` - Hide banners in preview tab

- source/features/conversation-activity-filter.tsx
> `conversation-activity-filter` - Restore feature on RGH repo

- source/features/default-branch-button.tsx
> `default-branch-button` - Restore feature in sticky header

- source/features/comments-time-machine-links.tsx
- Appears to fix https://github.com/refined-github/refined-github/issues/7620
Not yet tested
1. Open https://togithub.com/acomagu/fish-async-prompt/issues/51
2. Click `__async_prompt.fish#L2` link
3. Click "view this object as it appeared at the time of the comment"
4. Expect `#L2` hash to still be there
> `comments-time-machine-links` - Preserve hash on link

- build/prepare-safari-release.sh
- Fixes #7629 
- Fixes #7590 
- Workaround for https://bugs.webkit.org/show_bug.cgi?id=277588
@sindresorhus FYI I added a line to the `npm run prepare:safari` release script
> Fix several Safari bugs

- source/features/visit-tag.tsx
- Fixes https://github.com/refined-github/refined-github/issues/7601
https://github.com/fregante/title-to-labels-action/tree/v1.2.1?rgh-link-date=2024-07-26T04%3A58%3A45Z
The `default-branch-button` duplicate is a regression from https://github.com/refined-github/refined-github/pull/7623
> `visit-tag` - Fix duplication after system theme update

- source/features/one-click-diff-options.tsx
- Fixes https://github.com/refined-github/refined-github/issues/7542
https://github.com//refined-github/refined-github/pull/7472/files
> `one-click-diff-options` - Fix sticky header alignment

- source/features/clean-conversation-headers.tsx
- source/features/conversation-activity-filter.tsx
- Fixes https://github.com/refined-github/refined-github/issues/7545
The original selector was blamed to https://github.com/refined-github/refined-github/pull/4378
https://github.com/refined-github/sandbox/pull/4
> `conversation-activity-filter` - Don't show in wrong position

- source/features/update-pr-from-base-branch.tsx
- Introduced by https://github.com/refined-github/refined-github/pull/7642
If you can merge the PR, the container has `.branch-action-item + .merge-message`, so `.branch-action-item:last-child` did not match anything anymore.
Tested on https://github.com/refined-github/sandbox/pull/16/files
> `update-pr-from-base-branch` - Fix regression

- source/features/hide-inactive-deployments.tsx
Closes: #7630
https://github.com/btkostner/btkostner.io/pull/10
if use `.js-socket-channel[data-gid^="PR"]`, you can see there will some dom not what we expected to get.
after:
everything works fine, and the last deployment still keep on the page.
> `hide-inactive-deployments` - Restore feature

- source/features/pr-branch-auto-delete.tsx
close: #7646 
We need all conditions in `asLongAs` are true, so that we can successfully get `runFeature` function. So we need to add `awaitDomReady: true` to make `canCreateRelease` to be `true`.
> `pr-branch-auto-delete` - Restore feature

- source/features/show-names.tsx
> `show-names` - Fix comment header cleanup

- source/features/pull-request-hotkeys.tsx
- source/features/rgh-welcome-issue.tsx
- source/features/same-branch-author-commits.tsx
- source/features/tab-to-indent.tsx
- source/features/toggle-everything-with-alt.tsx
- source/features/warn-pr-from-master.tsx
Add test URLs for the `pull-request-hotkeys`, `rgh-welcome-issue`, `same-branch-author-commits`, `tab-to-indent`, `toggle-everything-with-alt` and `warn-pr-from-master` features
Related to the https://github.com/refined-github/refined-github/issues/7656
> Meta: Add more test URLs

- source/features/toggle-everything-with-alt.tsx
Closes: #7671 
https://github.com/torvalds/linux/commits/master
https://github.com/user-attachments/assets/cf4b2550-099b-4691-9b56-4487f0e3f5e1
> `toggle-everything-with-alt` - Restore for commit message

- source/feature-data.ts
- source/features/mark-merge-commits-in-list.tsx
- source/github-helpers/index.ts
- source/github-helpers/selectors.ts
- Continues from https://github.com/refined-github/refined-github/pull/7685
> `mark-merge-commits-in-list` - Restore feature

- source/refined-github.css
This PR adds 4 lines of CSS to `refined-github.css`, increasing the size of profile pictures in hovercards by 150%. Closes #7481.
Before:
After:
Opening this PR as a draft, because in rare cases it can cut off the top of the hovercard (reproduce by hovering over the avatar of a user with a two or more line bio, in the first comment of an issue or PR).
> Increase size of profile picture in user hovercard

- source/features/same-branch-author-commits.tsx
At the moment the `same-branch-author-commits` doesn't work correctly as the current selector no longer matches the author link element
https://github.com/refined-github/sandbox/commits/branch/with/slashes/
> `same-branch-author-commits` - Restore feature

- source/features/repo-stats-spacing.css
- source/refined-github.ts
Added a long time ago: https://github.com/refined-github/refined-github/pull/2560
> `repo-stats-spacing` - Drop feature

- source/features/comment-excess.tsx
https://github.com/refined-github/sandbox/issues/3
before:
after:
> `comment-excess` -  Fix rare bug + improve style

- build/__snapshots__/features-meta.json
- build/readme-parser.ts
- source/features/rgh-feature-descriptions.tsx
- source/globals.d.ts
Closes: #7724 
- Regular feature: https://github.com/refined-github/refined-github/blob/main/source/features/sync-pr-commit-title.tsx
- CSS counterpart: https://github.com/refined-github/refined-github/blob/main/source/features/sync-pr-commit-title.css
- RGH feature: https://github.com/refined-github/refined-github/blob/main/source/features/rgh-feature-descriptions.css
- CSS-only feature: https://github.com/refined-github/refined-github/blob/main/source/features/center-reactions-popup.css
> `rgh-feature-description` - Add link to css file

- source/features/default-branch-button.css
- source/features/default-branch-button.tsx
closes: #7681 
I think it doesn't need to set width. Github seem already handle this situation.
> `default-branch-button` - Stop shortening branch name

- source/features/tag-changes-link.tsx
https://github.com/refined-github/refined-github/releases
https://github.com/refined-github/refined-github/tags
https://github.com/refined-github/refined-github/tags?after=0.5.0
Sometimes it's all fail.
It's may add the `compareLink` to the end after reloading. But it's still fail for the last tag in this page.
after:
https://github.com/user-attachments/assets/97694952-2993-43db-b4a0-d18b3bb9443b
> `tag-changes-link` - Improve reliability 

- source/manifest.json
I think Firefox won't show a "Preferences" link because `options_page` is not supported until Firefox 126 (🤦‍♂️)
I can't use `options_ui` as a "fallback" because it takes priority over `options_page`
Related:
- https://github.com/refined-github/refined-github/issues/7732
> Bump minimum Firefox version to 126

- .github/workflows/release.yml
- Thanks to https://github.com/refined-github/refined-github/pull/7472
- Related to https://github.com/refined-github/refined-github/issues/7750
The source code is super readable now, no bundler junk. Look at this beauty. We're basically shipping the source code.
> Avoid uploading source code to AMO

- rollup.config.js
You can see the first video. I make an error in code and then I fix it. But the `distribution/assets` folder doesn't  generate this time. It means the build failed. So whetever you reload the page or fix the error, extension will not update anymore.
before:
https://github.com/user-attachments/assets/e08d24ff-670e-46da-89ff-688fe5940e19
after:
https://github.com/user-attachments/assets/a373d4cf-a4d2-4144-8191-05818ba05db1
> Meta: Keep build active after syntax error

- .github/workflows/release.yml
For https://github.com/refined-github/refined-github/issues/7763
I always clean up and extend the release notes before sending out a new release, so it's better to hold it before sending out notification emails.
> Create release as draft

- source/features/rgh-feature-descriptions.tsx
Closes: #7765 
https://github.com/refined-github/refined-github/blob/main/source/features/table-input.tsx
before:
after:
> `rgh-feature-descriptions` - Fix overlap of "Feature disabled"

- source/features/cross-deleted-pr-branches.tsx
Closes: #7708 
- deleted branch: https://github.com/refined-github/refined-github/pull/576
- deleted branch (from fork): https://github.com/refined-github/refined-github/pull/872
- restored branch (on fork): https://github.com/refined-github/refined-github/pull/909
- deleted repository: https://github.com/refined-github/refined-github/pull/271
- deleted repository on open PR: https://github.com/yakov116/TestR/pull/7
- deleted repository with no deleted branch https://github.com/jquery/jquery/pull/769
https://github.com/user-attachments/assets/841eb449-921c-461d-a777-0ddce12ea689
> `cross-deleted-pr-branches` - Restore feature

- build/__snapshots__/features-meta.json
- readme.md
- source/features/conventional-commits.css
- source/features/conventional-commits.tsx
- source/helpers/conventional-commits.test.ts
- source/helpers/conventional-commits.ts
- source/helpers/dom-utils.ts
- Follows https://github.com/refined-github/refined-github/pull/7796
- support titles that contain HTML
- `parseConventionalCommit` now rejects invalid types
- use CSS attributes for type matching
- avoid hardcoded padding values
- reduce label to type
- add test URLs
- Repo commits: https://github.com/refined-github/sandbox/commits/conventional-commits/
- PR commits: https://github.com/refined-github/sandbox/pull/91/commits
- Real data: https://github.com/semantic-release/semantic-release/commits
- Repo without conventional commits: https://github.com/refined-github/refined-github/commits
<table>
<tr>
<td><img width="458" alt="light" src="https://github.com/user-attachments/assets/5e557bb4-aacf-4848-b11f-cb00e80bf039"> 
<td><img width="458" alt="dark" …
> `conventional-commits` - Cleanup

- package-lock.json
- package.json
- source/background.ts
- source/feature-manager.tsx
- source/features/embed-gist-inline.tsx
- source/features/quick-repo-deletion.tsx
- source/features/selection-in-new-tab.tsx
- source/helpers/messaging.ts
- source/helpers/open-options.ts
- source/helpers/open-tabs.ts
- Fixes https://github.com/refined-github/refined-github/issues/7781
https://github.com/refined-github/refined-github/pull/7482 in v24.6.25 broke a few features that depended on the background worker, for example style hotfixes (😱) because Chrome is the only browser that _still_ can't handle promises in `onMessage`.
> `embed-gist-inline` - Restore feature

- source/features/pr-branch-auto-delete.tsx
I am adding `staging` as a common branch type for the pr-auto-delete exception branch list. Like `production` `staging` is also similarly used for the branch before prod.
> `pr-branch-auto-delete` - Exclude `staging`

- source/features/conventional-commits.css
- source/features/conventional-commits.tsx
- source/helpers/conventional-commits.ts
- source/helpers/dom-utils.ts
- Follows https://github.com/refined-github/refined-github/pull/7813
- Will close https://github.com/refined-github/refined-github/issues/7814
- https://github.com/refined-github/sandbox/commits/conventional-commits/
- https://github.com/conventional-changelog/standard-version/commits
> `conventional-commits` - Various fixes

- source/features/default-branch-button.css
Adding old css variables and tweaking the selectors so this doesn't render incorrectly on older GHES platforms.
Fixes #7857
https://github.com/refined-github/refined-github/tree/sandbox/keep-branch?rgh-link-date=2024-10-04T15%3A40%3A11Z
https://github.com/refined-github/refined-github/issues/7857#issuecomment-2394150829
> `default-branch-button` - Fix pink button on GHE

- readme.md
Info moved to https://github.com/refined-github/refined-github/wiki/Contributing#metadata-guidelines
> Meta: Move metadata guidelines to wiki

- source/features/more-conversation-filters.tsx
Closes: #7856 
Because our test page doesn't have `#filters-select-menu`, so it throws an error.
https://github.com/tc39/proposal-await.ops/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen
> `more-conversation-filters` - Fix error on new beta view

- source/features/release-download-count.css
- source/features/release-download-count.tsx
Fixes #7579.
https://github.com/dnicolson/Home-Screen-Layout/releases/tag/v0.1.0
https://github.com/cli/cli/releases/tag/v2.30.0
|--------|-------|
| ![PixelSnap 2024-10-09 at 18 52 08@2x](https://github.com/user-attachments/assets/91a92536-091a-48b7-a9c0-9fe8b21a1f33)| ![PixelSnap 2024-10-09 at 18 52 31@2x](https://github.com/user-attachments/assets/0b50dbc3-4438-469f-8738-180c7a425d08) |
| ![PixelSnap 2024-10-09 at 18 51 44@2x](https://github.com/user-attachments/assets/29dad592-cd08-486c-b35a-48c231773ebf) | ![PixelSnap 2024-10-09 at 18 52 38@2x](https://github.com/user-attachments/assets/04412f81-3fe2-4bba-8126-6772ae5de5fa) |
This also fixes timestamps when there are downloads:
|--------|-------|
| ![PixelSnap 2024-10-09 at 19 50 …
> `release-download-count` - Fix misalignment 

- source/features/clean-conversation-filters.tsx
- source/refined-github.css
Closes: #7856
https://github.com/tc39/proposal-await.ops/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen
👆 this is the usual page
👇 this is the new view
> `clean-conversation-filters` - Add support for new beta view

- source/features/select-notifications.tsx
- Fixes https://github.com/refined-github/refined-github/issues/7852
This is specifically an iOS issue because the OS' checkbox pushes the "Select all" label a bit lower. Exaggerated example via `vertical-align: super`:
`vertical-align` fixes this issue and also aligns it better on Chrome. You can see how this reduces the first box' height:
A better solution would be to use `align-items: baseline` on the entire line, but we do want them to be centered. There's no `center baseline` option, apparently.
In this PR I'm also adding a dot to better separate the two buttons.
Safari:
Chrome:
> `select-notifications` - Improve spacing and alignment

- .github/ISSUE_TEMPLATE/3_discussion.md
- .github/release.yml
- source/features/rgh-improve-new-issue-form.tsx
- Fixes https://github.com/refined-github/refined-github/issues/7678
> Meta: Improve "New Issue" templates

- source/features/netiquette.tsx
- For #7886 
- https://togithub.com/eslint/eslint/issues/19013
> `netiquette` - Support new text fields (partial)

- eslint.config.js
- rollup.config.js
- source/features/select-notifications.tsx
- source/features/suggest-commit-title-limit.tsx
- source/github-helpers/search-query.ts
- source/options.css
- source/options.html
- source/options/header.css
- source/options/header.svelte
- source/welcome.css
- source/welcome.html
- source/welcome.svelte
- Related to #7854 
Now it matches the welcome page, which borrows from GitHub's own header style
> Improve options page style 

- source/features/table-input.tsx
- part of #7856 
https://github.com/download-directory/download-directory.github.io/issues/141
> `table-input` - Support new text fields

- source/features/unreleased-commits.tsx
Closes #7919.
Based on testing in browser console on Firefox 130.0.1 on macOS/arm64, and via this Stack Overflow post: https://stackoverflow.com/a/43243161
> `unreleased-commits` - Only show "Create release" if allowed

- source/features/patch-diff-links.tsx
- part of #7808 
- Commit:https://github.com/refined-github/refined-github/commit/132272786fdc058193e089d8c06f2a158844e101
- PR Commit: [`07ddf83` (#7751)](https://github.com/refined-github/refined-github/pull/7751/commits/07ddf838c211075701e9a681ab061a158b05ee79)
https://github.com/user-attachments/assets/91528850-34c7-4f0f-be5a-5b663800ccb6
> `patch-diff-links` - Support new commit view

- source/features/fit-textareas.css
- source/features/fit-textareas.tsx
- They changed their class name
- In Chrome, the field starts at 30px high, which doesn't look like a textarea
Here
> `fit-textareas` - Avoid conflict with native feature

- source/features/linkify-user-labels.tsx
- source/github-helpers/get-comment-author.ts
part of #7856 
https://github.com/download-directory/download-directory.github.io/issues/141
---
This PR fixes the `linkify-user-labels` feature in the new issue view.
The new Ui doesn't seem to have a lot of usable classes or IDs so I used `data-testid` but I  am not sure how much sense this makes. 
I really like this project and would like to contribute a bit more, so please let me know what I can improve!
> `linkify-user-labels` - Support new issue view

- source/features/pr-branch-auto-delete.tsx
We use a single release branch named `release` that I'd like to protect from auto-deletion.
The current functionality is to protect branches named `release/*`. This PR would change that to protect branches named `release*`.
> `pr-branch-auto-delete` - Preserve more `release` branches

- source/features/ci-link.tsx
> `ci-link` - Add explanatory tooltip

- source/helpers/errors.ts
- source/helpers/event-listener-loop.test.ts
- source/helpers/event-listener-loop.ts
- source/helpers/selector-observer.tsx
- Closes https://github.com/refined-github/refined-github/issues/6096
It's quite noisy because many of these features are "optional", for example on issues often you won't be able to edit _any_ comments, but that doesn't mean that the feature is broken.
It might be a way to detect broken features in 7856 #7886 #7808, but it's probably just noise.
I added it temporarily behind the `logging` flag, let's see how it works.
> Log broken selectors in the observer

- package-lock.json
- package.json
- rollup.config.js
#7915 accidentally introduced a selector that broke Safari completely. Thankfully I noticed this before it reached production.
Since we can't wait for https://bugs.webkit.org/show_bug.cgi?id=276942 to be fixed, I think it's just easier to circumvent the issue and just use a CSS transformer.
This is super easy, barely an inconvenience.
- Unlocks #6665
> Workaround for fatal Safari CSS bug

- source/features/github-bugs.css
> Fix GitHub bug: Notification buttons overlap on mobile

- source/features/linkify-code.tsx
- source/github-helpers/dom-formatters.tsx
- Fixes https://github.com/refined-github/refined-github/issues/7951
https://github.com/search?q=path%3A.npmrc&type=code
Live tests fields:
```js
JS:
issues: // #12, GH-34, fregante#1 and facebook/react#5678
url: // https://github.com/?q=refined-github
```
```
No syntax:
issues: // #12, GH-34, fregante#1 and facebook/react#5678
url: // https://github.com/?q=refined-github
```
> `linkify-code` - Restore feature

- source/features/small-user-avatars.tsx
- Reverts refined-github/refined-github#7924
- For https://github.com/refined-github/refined-github/issues/7856#issuecomment-2440813618
- Native avatars: https://github.com/download-directory/download-directory.github.io/issues?q=sort%3Aupdated-desc+is%3Apr
- Our avatars: https://github.com/download-directory/download-directory.github.io/issues?q=sort%3Aupdated-desc
> `small-user-avatars` - Don't duplicate native functionality

- source/github-helpers/bugs-label.test.ts
- source/github-helpers/bugs-label.ts
Microsoft PowerToys uses `Issue-Bug` for bug labels. See https://github.com/microsoft/PowerToys/issues?q=sort%3Aupdated-desc%20is%3Aissue%20is%3Aopen%20label%3AIssue-Bug.
This PR adds support for it. 
This fixes https://github.com/refined-github/refined-github/issues/7991.
This fixes https://github.com/refined-github/refined-github/issues/7991.
> `bugs-tab` - Support `issue-bug`

- package-lock.json
- package.json
- source/features/tags-on-commits-list.tsx
- Closes https://github.com/refined-github/refined-github/issues/7954
- Replaces https://github.com/refined-github/refined-github/pull/7987
- Includes https://github.com/fregante/select-dom/pull/31
Like this, but on GHE https://github.com/microsoft/vscode/commits/release/1.25/
_Untested_
> `tags-on-commits` - Improve GitHub Enterprise compatibility

- package-lock.json
- package.json
- source/features/clean-conversation-headers.css
- source/features/clean-conversation-headers.tsx
Part of #7988
- https://github.com/refined-github/refined-github/pull/7987/commits
- [`32352f7` (#7981)](https://github.com/refined-github/refined-github/pull/7981/commits/32352f73b951779f7e07e15be5fecc4ebe62e664)
> `clean-converstion-headers` - Support new PR view

- package-lock.json
- package.json
- source/features/patch-diff-links.tsx
https://github.com/refined-github/refined-github/pull/7909#issuecomment-2458740998
Test URL:
https://github.com/refined-github/refined-github/commit/132272786fdc058193e089d8c06f2a158844e101
New view:
Old view:
> `patch-diff-links` - Restore feature on non-beta issues

- source/features/keyboard-navigation.tsx
- Close: #8022
https://github.com/tstirrat/mGB/pull/6/files
https://github.com/user-attachments/assets/9b9d8897-761c-43df-a2d5-0118214a4deb
> `keyboard-navigation` - Restore navigation without pre-selection

- source/features/conversation-authors.css
https://github.com/download-directory/download-directory.github.io/issues?q=sort%3Aupdated-desc%20is%3Aissue%20state%3Aclosed
Before:
After:
> `conversation-authors` - Fix border partially visible in new view

- source/features/batch-mark-files-as-viewed.tsx
- Fixes https://github.com/refined-github/refined-github/issues/7819
https://github.com/refined-github/refined-github/pull/6006/files
> `batch-mark-files-as-viewed` - Don't select excluded files

- source/features/default-branch-button.tsx
- source/refined-github.css
- Fixes https://github.com/refined-github/refined-github/issues/7875
- Core issue initially fixed in https://github.com/refined-github/refined-github/pull/6249
For some reason Chrome isn't affected by either bug 🤷‍♂️ 
https://github.com/refined-github/refined-github/commits/test/safari2/
> `default-branch-button` - Fix Firefox rounded corners bug

- source/github-helpers/toast.tsx
- Closes #7809 
- As mocked up in https://github.com/refined-github/refined-github/pull/7918#issuecomment-2428709240
Anywhere, press cmd-u to enable `unread-anywhere`
> Label notifications as coming from Refined GitHub

- package-lock.json
- package.json
- source/features/actionable-pr-view-file.tsx
- source/features/clean-conversation-headers.tsx
- source/features/closing-remarks.tsx
- source/features/jump-to-conversation-close-event.tsx
- source/features/netiquette.tsx
- source/features/pr-base-commit.tsx
- source/features/pr-branch-auto-delete.tsx
- source/features/quick-review.tsx
- source/features/update-pr-from-base-branch.tsx
- Follows https://github.com/refined-github/refined-github/pull/8001
- Includes https://github.com/refined-github/github-url-detection/pull/202
- https://github.com/refined-github/refined-github/pull/8001
- https://github.com/refined-github/refined-github/pull/8001/commits
- [`ae164ef` (#8001)](https://github.com/refined-github/refined-github/pull/8001/commits/ae164efc1ed34fc64f4b13bffdb93a534a691622)
> `clean-conversation-headers` - Support new PR view

- source/features/clean-repo-tabs.tsx
- Fixes https://github.com/refined-github/refined-github/issues/7140
- Related to https://github.com/refined-github/refined-github/pull/4180
- Related to https://github.com/refined-github/refined-github/pull/5614
1. Open https://github.com/refined-github/sandbox/pull/12/checks
2. Click on the "Files" tab
or
1. Open https://github.com/PyStatPower/PyStatPower/security
2. Visit any there security pages from the left menu
> `clean-repo-tabs` - Fix console error

- source/features/table-input.css
Make table-input more performant as @fregante discovered in fixes #8039.
It will ensure that firefox does not freeze when opening the labels dialog when you have a large number of labels (somewhere between 500 and 2241).
> Work around Firefox bug that causes tab freezes

- source/features/show-associated-branch-prs-on-fork.tsx
At some point, GitHub changed the format of the class name which broke this feature.
https://github.com/bfred-it-org/github-sandbox/branches
> `show-associated-branch-prs-on-fork` - Restore feature

- source/features/conversation-authors.css
Follow-up to https://github.com/refined-github/refined-github/pull/8025#issuecomment-2469007955
I noticed that the margin-top value needs to be 1.5px instead of 1px.
https://github.com/download-directory/download-directory.github.io/issues?q=sort%3Aupdated-desc%20is%3Aissue%20state%3Aclosed
Comparison of 1px vs 1.5px padding:
1px
1.5px
> `conversation-authors` - Avoid border clip on Windows

- source/features/rgh-token-user.tsx
- Follows https://github.com/refined-github/refined-github/pull/8002
Before:
After:
> `rgh-token-user` - Fix token button style

- source/features/clean-conversation-sidebar.tsx
- Fixes https://github.com/refined-github/refined-github/issues/7283
1. Visit a conversation you can't moderate, like this https://togithub.com/facebook/react/pull/31542
2. Reach a conversation you can't moderate, via ajaxed link, like via notifications
> `clean-conversation-sidebar` - Don't break the label picker

- rollup.config.js
- source/helpers/used-storage.ts
- source/options.css
- source/options.html
- source/options.tsx
- source/options/storage-usage.svelte
- extends https://github.com/refined-github/refined-github/pull/6595
The label was wrong, we don't have 100KB but only 8KB because `webext-options-sync` stores everything in a single key, which is limited to 8KB https://github.com/fregante/webext-options-sync/issues/80.
> Fix storage display in options

- source/features/netiquette.tsx
part of #7808
https://github.com/refined-github/sandbox/commit/54c10fe670779eab43b6a18b7fb06e51dd7050af
| ------ | ------ |
| ![CleanShot 2024-11-18 at 08 47 53@2x](https://github.com/user-attachments/assets/97c506e1-cbce-4311-b5b2-c15037a1260d) | ![CleanShot 2024-11-18 at 08 47 40@2x](https://github.com/user-attachments/assets/da2700f5-2588-4038-8e18-88d8371baafa) |
| ![CleanShot 2024-11-18 at 08 48 01@2x](https://github.com/user-attachments/assets/226f9947-b044-4623-bdc9-7462b31c5753) | ![CleanShot 2024-11-18 at 08 47 33@2x](https://github.com/user-attachments/assets/295e5dfe-a4bf-4d9a-8294-f90aa5d0f092) |
> `netiquette` - Support new commit view

- source/features/hide-low-quality-comments.tsx
The feature stops working when you load a page with a comment link AND the comment link is not "low quality"
```
ElementNotFoundError: Expected element not found: #issuecomment-2413307020 .comment-body > p:only-child
at expectElement (chrome-extension://jialghbnladbdlhaibaoejjlnihkmemc/assets/npm/select-dom.js:21:11)
at init (chrome-extension://jialghbnladbdlhaibaoejjlnihkmemc/assets/features/hide-low-quality-comments.js:38:5)
at chrome-extension://jialghbnladbdlhaibaoejjlnihkmemc/assets/feature-manager.js:100:24
at chrome-extension://jialghbnladbdlhaibaoejjlnihkmemc/assets/helpers/async-for-each.js:6:52
at Array.map (<anonymous>)
at asyncForEach (chrome-extension://jialghbnladbdlhaibaoejjlnihkmemc/assets/helpers/async-for-each.js:6:34)
at maybeRun …
```
> `hide-low-quality-comments` - Fix feature on linked comments

- source/features/shorten-links.tsx
Part of #7808 
https://github.com/refined-github/sandbox/commit/54c10fe670779eab43b6a18b7fb06e51dd7050af#r148774860
Before: 
After:
> `shorten-links` - Support new commit view

- source/github-helpers/get-comment-author.ts
Part of #7808 
https://github.com/refined-github/sandbox/commit/54c10fe670779eab43b6a18b7fb06e51dd7050af#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R2
> `linkify-user-label` - Support new commit view

- source/features/hide-diff-signs.css
- Part of #7808
https://github.com/refined-github/sandbox/commit/54c10fe670779eab43b6a18b7fb06e51dd7050af#r148774860
> `hide-diff-signs` - Support new commit view

- source/features/scrollable-areas.css
- Fixes #8099 
- https://github.com/elastio/bon#struct-builder
- https://github.com/refined-github/sandbox/commit/54c10fe670779eab43b6a18b7fb06e51dd7050af#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R2
> `scrollable-areas` - Remove from new commit conversation view

- source/features/conventional-commits.tsx
- source/helpers/conventional-commits.test.ts
- source/helpers/conventional-commits.ts
- Fixes https://github.com/refined-github/refined-github/issues/8066
- ✅ `ci: #1` is now formatted
- ⚠️ `ci: #1` has a little extra padding after the type because a space character appears _between_ the two elements
- ✅ `ci:` is still skipped
- ℹ️ `fix: #1` has custom formatting already so it's not detected as conventional commit
https://github.com/refined-github/sandbox/commits/conventional-commits/
> `conventional-commits` - Support links following the type

- source/features/one-key-formatting.tsx
- Fixes https://github.com/refined-github/refined-github/issues/7707
https://github.com/refined-github/refined-github/edit/main/.git-blame-ignore-revs
> `one-key-formatting` - Enable on commit title fields

- source/helpers/target-blank-polyfill.ts
- fixes https://github.com/refined-github/refined-github/issues/8059
Options page
tested in Chrome (after dropping `isSafari`)
> Options: expand screenshot inline instead of new tab

- source/features/github-bugs.css
- Closes https://github.com/refined-github/refined-github/issues/8065
https://github.com/hkint/xiaomi-ax3000t-immortalwrt-hanwckf-firmware-build/releases/tag/ImmortalWrt_2024.11.13-0026
> Fix GitHub bug: broken layout with long release assets names

- source/features/comments-time-machine-links.tsx
Part of 
- #7808
- #7856
https://github.com/refined-github/sandbox/commit/54c10fe670779eab43b6a18b7fb06e51dd7050af#r149853192
https://github.com/download-directory/download-directory.github.io/issues/143
> `comments-time-machine-links` - Support new view

- source/features/previous-version.tsx
https://github.com/chalk/chalk/blame/f399cd0ff69841e88cca89d43a49f1cc9ba2efd5/readme.md
https://github.com/user-attachments/assets/260580e4-425b-4065-b36e-efeeba32e28a
> `previous-version` - Show in blame page

- source/helpers/hotfix.tsx
- Should fix https://github.com/refined-github/refined-github/issues/7916
Gotta love no-effort GitHub Pages publishing. I clicked a button and got a CDN-baked URL that _hopefully_ isn't affected by (aggressive) rate-limiting.
e.g. https://refined-github.github.io/yolo/broken-features.csv
> Improve hotfix loading reliability

- package-lock.json
- package.json
- source/features/batch-mark-files-as-viewed.tsx
- source/features/clean-repo-tabs.tsx
- source/features/clear-pr-merge-commit-message.tsx
- source/features/fit-textareas.tsx
- source/features/hidden-review-comments-indicator.tsx
- source/features/hide-diff-signs.css
- source/features/hide-low-quality-comments.tsx
- source/features/linkify-branch-references.tsx
- source/features/netiquette.tsx
- source/features/one-click-review-submission.tsx
- source/features/open-all-notifications.tsx
- source/features/release-download-count.tsx
- source/github-helpers/group-buttons.tsx
- source/options/feature-list.tsx
- Prefer `$()` over `querySelector()!`
- Use new `countElements()` to avoid unnecessary array conversion in `$$()`
I'd block `querySelector` entirely but I still prefer it in traversing sequences like `x.parentElement.querySelector`
> Meta: Use `select-dom` more

- source/features/comments-time-machine-links.tsx
- Closes https://github.com/refined-github/refined-github/issues/4979
I think all links appearing in the "Code" tab should be covered, except irrelevant ones like `/edit/`
1. On this page
2. Click on any of:
- https://github.com/refined-github/refined-github/tree/main
- https://github.com/refined-github/refined-github/blob/main/readme.md
- https://github.com/refined-github/refined-github/tree/main/test
Or visit this:
```js
// https://github.com/refined-github/refined-github?rgh-link-date=2024-12-08T06%3A15%3A26Z
```
> `comments-time-machine-links` - Add support for all "Code" links

- source/features/pull-request-hotkeys.tsx
- Fixes #7369 pull-request-hotkeys
Each tab has its own tabs component… so it wasn't finding any tabs.
Using the new `select-dom/strict` would have made this immediately	 visible.
Here
> `pull-request-hotkeys` - Restore feature

- source/helpers/target-blank-polyfill.ts
- should fix https://github.com/refined-github/refined-github/issues/8058
Reason: `instanceof HTMLAnchorElement` fails across web components. Neat.
> Open Welcome page links in new tab in Safari

- source/features/quick-review-comment-deletion.tsx
- source/features/safer-destructive-actions.css
- Fixes #7711 
- Doesn't cover #7856 
- Here
- Files tab: https://github.com/refined-github/refined-github/pull/8134/files
Unchanged, still works
> `safer-destructive-actions` - Restore feature

- source/github-helpers/github-token.ts
- source/options.html
- source/options/token-validation.tsx
- Closes https://github.com/refined-github/refined-github/issues/7917
- Kinda reverts https://github.com/refined-github/refined-github/pull/6956
I don't want to support a dedicated UI for a token that is non-supported as per our docs. Easier to mark it as "unknown". Perhaps as part of #7855, more information about the token type can be shown on the list.
Options page
> Options: Change visualization of fine-grained tokens

- package-lock.json
- package.json
- source/background.ts
- source/feature-manager.tsx
- source/options/reload-without.ts
- Includes https://github.com/fregante/webext-alert/pull/14
- Closes #7562 
Here or any page, including `about:blank`
> Add "Reload without Refined GitHub" action

- source/features/show-associated-branch-prs-on-fork.tsx
Was changed yet again, now it just checks for BranchName in the attribute at all.
https://github.com/bfred-it-org/github-sandbox/branches
> `show-associated-branch-prs-on-fork` - Restore feature (again)

- source/features/esc-to-deselect-line.tsx
Fix #7756
Related GitHub source code:
```tsx
// Simplified for demonstration
// https://github.githubassets.com/assets/app/assets/modules/react-code-view/components/blob/BlobContent/Code/LineNumber.tsx
<div onMouseDown={preventClick ? undefined : codeCellClickFunc} />
const codeCellClickFunc = event => {
const targetedLineNumber = parseInt(event.currentTarget.getAttribute('data-line-number')!, 10)
}
```
https://github.com/refined-github/refined-github/blob/main/source/features/esc-to-deselect-line.tsx
https://github.com/user-attachments/assets/eb900534-02a7-49d1-9697-89fd21ed22e6
> `esc-to-deselect-line` - Restore feature

- source/features/conversation-activity-filter.tsx
Minor cosmetic fix (that has been in my todo for 6 months)
https://togithub.com/refined-github/refined-github/pull/8038
This is the sticky header
| ![CleanShot 2025-01-07 at 00 38 37@2x](https://github.com/user-attachments/assets/d512d1cb-f90d-446c-b41d-0eeaf02f7db6) | ![CleanShot 2025-01-07 at 00 41 39@2x](https://github.com/user-attachments/assets/98ce9165-f753-4810-8822-2eecf4369f3e) |
|![CleanShot 2025-01-07 at 02 38 16@2x](https://github.com/user-attachments/assets/23795242-a029-4c73-983a-b5f94a505de2) | ![CleanShot 2025-01-07 at 02 39 04@2x](https://github.com/user-attachments/assets/4010ec7b-ad87-4bb1-8c5c-5a0c151345ef)|
> `conversation-activity-filter` - Fix position and color

- source/features/rgh-dim-commits.tsx
- source/features/tags-on-commits-list.tsx
- source/github-helpers/selectors.ts
- Fixes https://github.com/refined-github/refined-github/issues/8237
https://github.com/typed-ember/ember-cli-typescript/commits/master?after=5ff0c078a4274aeccaf83382c0d6b46323f57397+174
https://github.com/refined-github/sandbox/commits/conventional-commits
https://github.com/refined-github/refined-github/commits/19.5.21.1921
> Restore 4 features on commit lists

- source/features/pr-approvals-count.css
- source/refined-github.css
An addition to the [Shows color-coded review counts in PR lists.](https://github-production-user-asset-6210df.s3.amazonaws.com/83146190/253125143-d10d95df-4a89-4692-b218-5eba5cd79906.png) feature. Highlights the 'Review Required' text in yellow so it pops more easily when skimming PR lists.
I would appreciate some guidance on a few things:
1. Existing CSS vars for `--rgh-green` and `--rgh-red` reference `--color-*` vars that I'm unable to find in refined-github or in github's own CSS files, so I cannot apply an applicable one to the `--rgh-yellow` var I've added.
2. I'm not 100% confident I sourced the default color for `--rgh-yellow` from the correct place. I've made the assumption it's meant to be the hex code that the `--fgColor-*` var being used is assigned by github's CSS files.
3. …
> `pr-approvals-count` - Highlight "Review Required" in yellow

- source/features/clean-rich-text-editor.css
Close: #8260 
https://github.com/refined-github/refined-github/issues/new?template=1_bug_report.ym
> `clean-rich-text-editor` - Restore feature on the first comment

- source/github-helpers/selectors.ts
Close: #8270 
https://github.com/refined-github/sandbox/issues/77
> `embed-gist-inline` - Restore feature on the first comment

- .github/workflows/test.yml
- source/features/default-branch-button.css
- source/features/github-bugs.css
- source/features/global-conversation-list-filters.tsx
This PR does not close any issue and does not change any pages.
It only fixes typos and adds a GitHub Action step to the Lint job to look for future typos.
% `codespell --ignore-words-list=eror,usera --skip="*.json" --write-changes`
* https://pypi.org/project/codespell
> Meta: Fix typos discovered by codespell

- source/features/update-pr-from-base-branch.tsx
Close: #8247
[github.com/pulls (is:open archived:false user:@me draft:false)](https://github.com/pulls?q=sort%3Aupdated-desc+is%3Apr+is%3Aopen+archived%3Afalse+user%3A%40me+draft%3Afalse&rgh-link-date=2025-02-01T07%3A43%3A26.000Z)
Before:
After:
> `update-pr-from-base-branch` - Don't duplicate native button

- source/helpers/conventional-commits.test.ts
- source/helpers/conventional-commits.ts
The problem:
Before fix: https://regex101.com/r/XZIg7M/1
After fix: https://regex101.com/r/j85oEo/1
https://github.com/renovatebot/renovate/commits/4214048e713096f58005658e104c09e881d4b933/
> `conventional-commits` - Fix grouping on commits with parens

- source/features/small-user-avatars.css
The avatars shown next to the mentions are squished if it is the logged in user's mention:
> ![1](https://github.com/user-attachments/assets/04c64c01-9e2b-4023-ab2a-bf5641426f76)
The following CSS used by GitHub is causing the issue:
```css
.user-mention[href$="/OnkarRuikar"]:before, .user-mention[href$="/OnkarRuikar"]:after {
content: '';
display: inline-block;
width: 2px;
}
```
Force the width from refined-github's side:
```diff
.rgh-mention-avatar::before {
content: '';
display: inline-block;
--	width: 16px;
++	width: 16px !important;
height: 16px;
margin-right: 0.2em;
border-radius: 50%;
}
```
In this case, one URL doesn't work for everyone. Instead I give you steps to reproduce:
1. Add mine and your mention `@OnkarRuikar and @yourname` in the new comment edit box below.
2. Switch to …
> `small-user-avatars` - Fix own avatar size

- build/__snapshots__/features-meta.json
- readme.md
It's nice to be able to search the features for a consistent string and see all features that impact it. Since the other 2 features that modify the text editor mention it in their descriptions, I figured this one should as well. Note how it's currently left out of this search:
> `collapsible-content-button` - Improve description

- .github/workflows/relative-ci.yml
- .github/workflows/test.yml
Run relative-ci/agent-action during `workflow_run` to safely provide the secret for pull requests triggered by unsecured flows(forks, dependabot). The new workflow will be run only from the context of the main branch (after merge).
- rel: https://github.com/relative-ci/agent-action/issues/442
- more info: https://relative-ci.com/documentation/setup/agent/github-action/#workflow_run-event
- Base repository action: 
- https://github.com/relative-ci/refined-github/actions/runs/13862190986
- Pull request triggered from a forked repo:
- Pull request: https://github.com/relative-ci/refined-github/pull/3
- Action logs: https://github.com/relative-ci/refined-github/actions/runs/13862469687/job/38794010415
> Meta: Fix RelativeCI setup on PRs from forks

- source/features/emphasize-draft-pr-label.css
> `emphasize-draft-pr-label` - Support in notifications

- source/features/jump-to-conversation-close-event.tsx
https://github.com/refined-github/refined-github/issues/8296#issuecomment-2759478677
`.Timeline-Item` is missing. We need to update the selector.
https://github.com/ktheory/dalli-elasticache/issues/54
> `jump-to-conversation-close-event` - Update selector

- source/features/small-user-avatars.tsx
Close: #8354 
It seems like native avatar has been removed.
- Native avatars: [download-directory/download-directory.github.io/issues (sort:updated-desc is:pr)](https://github.com/download-directory/download-directory.github.io/issues?q=sort%3Aupdated-desc+is%3Apr)
- Our avatars: [download-directory/download-directory.github.io/issues (sort:updated-desc)](https://github.com/download-directory/download-directory.github.io/issues?q=sort%3Aupdated-desc)
https://github.com/user-attachments/assets/2510d19e-1825-4bfa-9f24-2381f73e058a
> `small-user-avatar` - Restore feature

- source/features/closing-remarks.tsx
- Close https://github.com/refined-github/refined-github/issues/7789
Dropping the ugly info icon that wrapped badly and restored less specific wording, more clearly linking to the explanatory document.
https://github.com/refined-github/sandbox/pull/109#issue-comment-box
> `closing-remarks` - Clarify message

- source/features/repo-header-info.tsx
> `repo-header-info` - Restore feature

- source/github-helpers/selectors.ts
Closes #8433 
Documentation references to `/github-apps`:
- https://docs.github.com/en/enterprise-server@3.16/apps/using-github-apps/installing-a-github-app-from-a-third-party
- https://docs.github.com/en/enterprise-server@3.16/apps/sharing-github-apps/sharing-your-github-app
- https://docs.github.com/en/enterprise-server@3.16/apps/creating-github-apps/about-creating-github-apps/migrating-oauth-apps-to-github-apps
No test url as it applies to private GHE only.
> `show-names` - treat `github-apps` as a bot

- source/features/conventional-commits.tsx
Apparently, the problem with the label not showing up when the message starts with a backtick, was fault of:
https://github.com/refined-github/refined-github/blob/1f6ec8a24faa3a489001c843e50d31314a6244da/source/features/conventional-commits.tsx#L27
The `commit.raw` and `textNode.textContent` were identical and no sibling was found because the `<code>` element is inside `commitTitleElement`, not as a sibling.
By counting the children, the `<code>` element or any element should avoid the early return, as text nodes don't count as childElements.
https://github.com/loky-lp/rgh-dummy-conventional-commits/commits/main
https://github.com/refined-github/sandbox/pull/91/commits
<table>
<tr>
<th>Before
<th>After
<tr>
<td><img width="370" alt="Screenshot 2025-05-02 alle 22 56 03" …
> `conventional-commits` - Support message starting with backtick

- source/features/bugs-tab.gql
- source/features/bugs-tab.tsx
- source/github-helpers/search-query.test.ts
- source/github-helpers/search-query.ts
Closes #8227
Not the best at crafting regexp, so would appreciate suggestions on how to improve it if possible, but all existing tests on queryPartsRegExp are still passing.
https://github.com/refined-github/refined-github/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen+%28label%3Abug+OR+type%3ABug%29
Unfortunately don't have any public repository available to test the issue type bug on.
> `bugs-tab` - Support Bug type

- source/features/github-bugs.css
PR description's input in [Folo](https://github.com/RSSNext/Folo)
| ----- | ----- |
| ![CleanShot 2025-05-19 at 15 13 07](https://github.com/user-attachments/assets/946f5b93-a50e-423f-a8eb-74b160baeb1e) | ![CleanShot 2025-05-19 at 15 27 46](https://github.com/user-attachments/assets/abbd8272-5f10-4646-9638-40931c212497) |
> GitHub bug fix: container's width is overing browser viewport

- source/features/sticky-sidebar.css
Close: #8462
Any repo you own.
https://github.com/user-attachments/assets/43c5ca32-9461-48dd-afd1-4a0d6af635fe
> `sticky-header` - Fix overlap with repository readme header

- source/features/repo-age.tsx
A small fix to properly anchor the `repo-age` feature, as it's currently being injected into the `Forks` row.
Any repo
| --- | --- |
| ![image](https://github.com/user-attachments/assets/c5932422-edad-4348-84b2-4bfe250f0789) | ![image](https://github.com/user-attachments/assets/69ad7bbd-0a90-4fcc-a2a7-b5529113a257) |
> `repo-age` - Fix positioning in document

- source/features/clean-conversation-sidebar.tsx
https://github.com/refined-github/sandbox/pull/60
Before:
After:
> `clean-conversation-sidebar` - Restore feature for development hint

- source/features/ci-link.css
> `ci-link` - Fix popup is cut off

- source/features/list-prs-for-file.tsx
This pull request fixes a bug where `list-prs-for-file` does not add the dropdown button to view the PR list as expected. From my understanding, when it was last written, the "More file actions" dropdown button had an `aria-label` attribute, but it has now been changed to use `aria-labelledby`, which causes it not to function properly. So when I checked using the browser’s built-in Inspect tool, the `data-testid` attribute among the "More file actions" dropdown button’s properties appeared to be usable for identification purposes. I applied this to the code, and since it appears to work correctly in my case, I’m submitting this PR.
- https://github.com/vuejs/vitepress/blob/main/src/client/theme-default/components/VPDocFooterLastUpdated.vue
- …
> `list-prs-for-file` - Restore feature

- .github/ISSUE_TEMPLATE/1_bug_report.yml
Updates the bug report GitHub issue template from "Find feature" to "Identify feature" to match the text in the options page.
> Rename "Find feature" to "Identify feature" in bug template

- source/features/linkify-user-location.tsx
Closes #8482 
https://github.com/f15u
> `linkify-user-location` - Use Open Street Map instead of Google Maps

- source/features/clear-pr-merge-commit-message.tsx
-  Part of #8123 
It was already fixed twice, I suppose this is the last time since the box is out of the beta. I'm also dropping support for GHE right away.
Any open mergeable PRs like this one
> `clear-pr-merge-commit-message` - Restore feature

- source/features/quick-file-edit.css
now the `height` value matches the content 
fixes #8532 
> `quick-file-edit` - Fix icon alignment

- source/github-helpers/bugs-label.ts
Hello, the company im in has a repo where bug issues have the label `category:bug`. Unfortunately I cant provide screenshots or other prove of it working, because that is a private repo.  
I love this project and wanted it to work on my company repos too, so i updated the file in question.
I would be happy to provide more information if you need anything further and im allowed to give.
> `bugs-tab` - Support `category:bug`

- source/features/pr-jump-to-first-non-viewed-file.tsx
Quick fix attempt at the PR jump to first non-viewed file.
Not super happy with the selector for the viewed file count but it _does_ work. Unfortunately the cute `progress-bar` element has been replaced with an SVG.
Relates to #8504 
- PR: https://github.com/refined-github/sandbox/pull/55/files
- Large PR https://github.com/pixiebrix/pixiebrix-extension/pull/6808/files
https://github.com/user-attachments/assets/e8bc4c88-4cc8-412d-bf8b-5c55f319cb0a
> `pr-jump-to-first-non-viewed-file` - Support new PR Files view

- source/features/no-modals.tsx
Close: #8556
- http://github.com/issues
- https://github.com/orgs/CherryHQ/projects/3?query=sort%3Aupdated-desc+is%3Aopen
> `no-modals` - Restore feature

- source/features/netiquette.tsx
Fix: #8558 
- There is a `margin: 0 auto` being applied by the `flash` CSS class upstream somewhere in Primer. So I added a `m-0` to override this unwanted styling.
- I verified all the banner example URLs I could find in the issue and in the netiquette files.
Fix visible here: https://github.com/sindresorhus/create-html-element/issues/2
Make sure I didn't break other banners: https://github.com/refined-github/refined-github/issues/3076, https://github.com/refined-github/refined-github/pull/159, https://github.com/refined-github/refined-github/pull/159
Before | After
:---: | :---:
> `netiquette` - Fix banner margins

- source/features/new-or-deleted-file.tsx
Relates to #8504 
The new PR page also now enables this feature on 1 file commits.
I also snuck in the renamed file icon from the new PR page too, let me know if we wanna keep that or not.
Commit: https://github.com/refined-github/sandbox/commit/a00694ff7370d46b5f6d723a0b39141903dae45a
PR: https://github.com/refined-github/sandbox/pull/71/files
1-file commits: https://github.com/refined-github/sandbox/commit/1ed862e3abd13004009927b26355a51a109d6855
New PR page:
Commit page:
Single commit:
Old PR page:
> `new-or-deleted-files`: Support new PR files view

- source/features/bugs-tab.tsx
Linked Issue: [#8484](https://github.com/refined-github/refined-github/issues/8484)
this PR solves the issue where in the `Bugs` tabs it showed the wrong number of bugs.
fix: assumes that most bug-type issues also have bug labels, so we take the larger of the two counts as our approximation
screenshot of issues filtered by `(label:"type: bug" OR type:Bug) ` and it also matches `Bugs` tab both are `554`
> `bugs-tab` - Stop counting bugs twice when using issue types

- source/features/conversation-authors.css
- source/features/conversation-authors.tsx
- follows https://github.com/refined-github/refined-github/pull/8602
https://github.com/issues
<table>
<tr>
<th>Before
<th>After
<tr>
<td><img width="643" height="350" alt="Screenshot 18" src="https://github.com/user-attachments/assets/26aecc90-2f9f-4659-9b12-945725aecf63" />
<td><img width="643" height="350" alt="Screenshot 17" src="https://github.com/user-attachments/assets/7b390294-eb20-4be6-a093-f8bd9ffb3956" />
</table>
> `conversation-authors` - Match own-user highlight to GitHub's

- source/features/center-reactions-popup.css
- Fixes https://github.com/refined-github/refined-github/issues/8605
https://togithub.com/facebook/react/pull/34091
Translucent to see how it aligns
> `center-reactions-popup` - Don't cut off on mobile

- build/__snapshots__/features-meta.json
- readme.md
- source/features/unread-anywhere.tsx
- Fixes https://github.com/refined-github/refined-github/issues/8641
- Fixes https://github.com/refined-github/refined-github/issues/8646
- Closes https://github.com/refined-github/refined-github/issues/8645
- Disable on Gists
- Disable on notifications page 
- Fix on Enterprise
- Add arrow icon
- Hide if there are no notifications (but stays visible after a click)
- Mention shortcut in tooltip
- Close tooltip after click
- GIF and description updated
- Limited to 5 notifications (just click multiple times if needed)
- Avoid double-clicks
https://gist.github.com
> `unread-anywhere` - Several improvements

- readme.md
Broken since linked wiki page has been removed.
Or replace with https://github.com/stefanbuck/awesome-browser-extensions-for-github? I remember bringing up the idea before, but that list is lacking maintenance as well (better than nothing I suppose).
> Drop "more extensions" link from readme

- source/features/readable-title-change-events.css
GitHub bug, their other style is overriding the `<del>` base style.
https://togithub.com/refined-github/refined-github/pull/8668#event-19553429615
| Before | <img width="441" height="81" alt="Screenshot 2025-09-09 at 11 46 21 AM" src="https://github.com/user-attachments/assets/6b572cae-d904-463c-9879-0ba14729816e" /> |
| After | <img width="428" height="83" alt="Screenshot 2025-09-09 at 12 17 48 PM" src="https://github.com/user-attachments/assets/c64d7aa7-3a30-4da0-b948-fc404564a3e8" /> |
> `readable-title-change-events` - Restore line through

- source/features/html-preview-link.tsx
Also:
- Rewrote the worker
- Added description and worker source code to [wiki](https://github.com/refined-github/refined-github/wiki/Extended-feature-descriptions#html-preview-link)
- Write a test suite in sandbox ([rendered](https://refined-github-html-preview.kidonng.workers.dev/refined-github/sandbox/raw/refs/heads/html/preview-link/public/test.html))
https://github.com/refined-github/sandbox/blob/html/preview-link/public/test.html
Before:
https://github.com/user-attachments/assets/2c5a3f87-12e7-45d9-bf0f-60b136c196b6
After:
https://github.com/user-attachments/assets/12a8fd12-975f-4539-b2fa-9564d2ab8763
> `html-preview-link` - Fix button style
