- readme.md
Not turn turn this into an `awesome-*` but I love this extension so much.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/sindresorhus/refined-github/6)
> Add canned responses as related project

- extension/content.css
This closes https://github.com/sindresorhus/refined-github/issues/13
> fix bug where switcher is messing with account menu

- extension/content.css
> Moves the account switcher thumbnail next to the text

- extension/content.js
This was some style attribute I was debugging with that snuck past us all. It didn't even do anything because there was a typo. :disappointed:
> Delete style attribute that doesn't work anyway

- extension/content.js
- Use dynamic checks for everything related to commit, PR, repo, compare and dashboard views.
- Remove obsolete isRepo() calls from other URL checks which already rely on a similar regex.
- Consider the new page of a commit in a PR as both a PR and a commit.
- Update `isCommit` regex to not match false positives such as `owner/repo/commits/<branch>` and `owner/repo/commits/<commit>`.
I'd say the extension is behaving much more reliably with these changes.
> Update URL checks. Closes #84.

- extension/content.css
Fixes https://github.com/sindresorhus/refined-github/issues/90
> Show tooltips for comment reactions on issues and PRs

- extension/content.js
- extension/manifest.json
- package.json
Follow-up to https://github.com/sindresorhus/refined-github/pull/12#issuecomment-185583858
I made some small fixes/adjustments in separate commits which I needed for this PR.
> Show releases count in releases tab and persist it

- extension/content.css
GitHub has changed the Upload files button URL to include the branch name in the end.
> Update CSS for hiding Upload files button

- extension/content.js
> fix merge commit duplicated icon

- extension/content.css
fixes https://github.com/sindresorhus/refined-github/issues/109
> increase min-height to for longer starred items in feed

- extension/content.js
- readme.md
Disables tab key navigation from textarea elements
> Adds support to indent with the tab key

- readme.md
I believe the correct action would be collapse instead of minimize. I understand minimize as normally _minimize_ a window into a dock/taskbar.
What the feature does is actually collapse/expand or fold if you like so.
> Improve feature action for maximize/minimize switching to collapse/expand

- readme.md
Ref: https://github.com/sindresorhus/refined-github/issues/136#issuecomment-204075281
> Add note on customization to readme

- extension/content.css
remove tooltip except for Participants, Organizations and Reactions
> Add back tooltip for Participants and Organizations Fix #149

- extension/content.js
> Do not repeat blame parent links if present

- extension/content.js
I think this style of indentation is better and I think it was so indented before, because of a Sublime Text bug with syntax grammar which could indent like that sometimes automatically when you press Tab depending on above line.
> Unindent some deeply indented code

- extension/content.js
- extension/page-detect.js
Closes #163 
Test Cases:
[Depth of 1](https://github.com/rjsteinert/GitHub-For-Writers-Manual/tree/master/managing-multiple-pages)
[Depth of 2](https://github.com/DrewML/tester-tester/tree/master/test/anothertest)
> Add Edit(Pencil) link for readmes not in the root

- extension/diffheader.js
- extension/manifest.json
- extension/util.js
- extension/utils.js
> Fixes overflow in sticky diff header when shrinking page

- readme.md
> Link to GitHub +1 Chrome Extension

- .travis.yml
See https://github.com/sindresorhus/refined-github/pull/172#issuecomment-210699291
Removes the whitelist of Travis CI so all branches are built.
> Remove whitelist block from Travis CI

- extension/custom.css
closes #179
I believe I covered all style selectors that set the normal monospace stack.
> change monospace font stack

- extension/content.js
- extension/copy-file.js
- extension/copy-on-y.js
- extension/manifest.json
- extension/util.js
- readme.md
> Copy canonical link to file when pressing "y" hotkey

- extension/content.js
Noticed that the "Trending" menu item is being added on gists, this fixes it.
> Dont add "Trending" on gists

- extension/custom.css
As per discussion https://github.com/sindresorhus/refined-github/pull/210#issuecomment-222877877
@sindresorhus / @paulmolluzzo let me know if you'd prefer a different position for it.
> Add Ubuntu Mono to monospace font stack

- extension/content.css
This is more flexible than `position: relative` on a single element
> Move entire sidebar content down with padding

- extension/content.js
> Fix readme edit button

- extension/content.js
Selector was changed from `.left` to `.float-left` so it isn't being added to the navigation.
> Fix trending menu item and readme edit button

- extension/content.js
- extension/page-detect.js
Fixes the diff signs on compare pages. See commit messages for details.
> Improve checks for diffs

- extension/content.js
- extension/icons.js
- extension/manifest.json
- extension/mark-unread.js
> Extract icons into their own file

- extension/content.css
- extension/diffheader.js
> fix diff header file name

- extension/custom.css
> Use custom fonts and enable font ligatures in code editor

- extension/custom.css
As per https://github.com/sindresorhus/refined-github/commit/fe6cda0b891efd6c7ed0cf7c7d7230dee6a25591#commitcomment-18233077
I think the difference is minimal, but it is an improvement.
This is a follow-up to #293 and https://github.com/sindresorhus/refined-github/commit/b6b9eead7854e1070115d7c1680f29539aa777e2.
> Reduce letter spacing a bit

- extension/content.js
> Fix crash on pull request pages

- extension/content.js
Fixed #352.
This makes the `isEmpty` test a boolean instead of a `0`.
> Fix #352 - Hide duplicate header on issues page

- extension/content.js
Fixes https://github.com/sindresorhus/refined-github/pull/382/files#r114247416
Test it here: https://github.com/sindresorhus/refined-github/pull/382/files#r114247416
> Fix misaligned diffs

- extension/content.css
- extension/content.js
- readme.md
> Remove “collapse files in a pull request diff” feature

- extension/content.css
- extension/content.js
- extension/icons.js
- extension/manifest.json
- extension/page-detect.js
- extension/upload-button.js
- test/page-detect.js
> Add upload button to comment forms

- extension/content.js
- extension/linkify-urls-in-code.js
- extension/util.js
First stab at fixing #412.
before: ![](http://www.seas.upenn.edu/~aburka/tmp/Screen%20Shot%202017-05-11%20at%2012.02.55%20AM.png)
after: ![](http://www.seas.upenn.edu/~aburka/tmp/Screen%20Shot%202017-05-11%20at%2012.00.27%20AM.png)
> Linkify cross-repo issues references in titles - Fixes #412

- extension/content.js
> Add "Compare" and "Releases" tabs before "Settings" if present

- extension/linkify-urls-in-code.js
- extension/mark-unread.js
Some of these jQuery uses only add convolution
> Skip jQuery when it adds nothing

- extension/mark-unread.js
Page with error for me, no unread notifications: https://gist.github.com/bfred-it/56d0ab0b88691f4a70acdd096cc2d411
> Fix error on empty unread notifications

- extension/copy-gist.js
+ change fake link to proper <button>
> Remove fickle index-based traversing

- extension/content.js
> Add "title" attribute to emojis

- extension/content.js
It looks like GH change the class name
> Update patch diff links selector

- extension/show-names.js
Current situation example: https://github.com/digimezzo/Dopamine/pull/412
> Don't add full name if it's identical to username

- readme.md
> Add GitHub Clean Feed to related repos

- src/content.js
- src/libs/page-detect.js
- src/libs/reactions-avatars.js
- src/libs/show-names.js
- src/libs/util.js
> Fix non-github.com URLs to support GHE

- extension/manifest.json
Fixes #439
- ~~Unsafe assignment to innerHTML <a href="https://github.com/sindresorhus/refined-github/blob/master/extension/linkify-urls-in-code.js#L26"><code>linkify-urls-in-code.js 26:5</code></a>~~ done by #467
-  ~~Unsafe assignment to innerHTML <a href="https://github.com/sindresorhus/refined-github/blob/master/extension/linkify-urls-in-code.js#L36"><code>linkify-urls-in-code.js 36:5</code></a>~~ done by #467
- ~~Unsafe assignment to innerHTML <a href="https://github.com/sindresorhus/refined-github/blob/master/extension/content.js#L284"><code>content.js 284:3</code></a>~~ done by #469 
Unsafe assignment to innerHTML
> Warning: Due to both security and performance concerns, this may not be set using dynamic values which have not been adequately sanitized. This can lead to security …
> Fix AMO review warnings

- package.json
> Add AMO autodeployment

- readme.md
Related to #450. How's the wording and position?
> Mention GH Enterprise support in the readme

- extension/content.css
> Fix broken tab indents on Firefox

- src/content.js
Fixes #479
@busches please have a look
> Load script injector's ping receiver (for GH Enterprise)

- src/libs/mark-unread.js
Simple changes, already tested in Chrome and Firefox.
> Mark unread improvements

- extension/content.css
- src/libs/mark-unread.js
> Update notification icon when marking read

- src/content.js
> Insert Release+Compare tabs before Settings/Insight

- extension/options/index.css
- extension/options/index.html
- package.json
- readme.md
- src/background.js
- src/content.js
- src/options/index.js
Oh boy.
I tried to keep it as contained as possible. Options are automatically saved.
Fixes #193 (Also #344 #174 #131 #75)
> Add extension option for whether to hide other users starring/forking your repos

- package.json
- rollup.config.js
> Add support for requiring json

- src/libs/shorten-links.js
- test/shorten-links.js
Closes #472
Have a look. These are pre-shortened links, you don't need to checkout this PR. Open #473 for live shortening.
[/doc@`master`](https://github.com/sindresorhus/refined-github/tree/master/doc)
[/doc@`v0.12`](https://github.com/sindresorhus/refined-github/tree/v0.12/doc)
[/doc@`d71718d`](https://github.com/sindresorhus/refined-github/tree/d71718db6aa4feb8dc10edbad1134472468e971a/doc)
[nodejs/node:doc@`master`](https://github.com/nodejs/node/tree/master/doc)
[nodejs/node:doc@`v0.12`](https://github.com/nodejs/node/tree/v0.12/doc)
[nodejs/node:doc@`d71718d`](https://github.com/nodejs/node/tree/d71718db6aa4feb8dc10edbad1134472468e971a/doc)
[/.gitignore@`master`](https://github.com/sindresorhus/refined-github/blob/master/.gitignore) …
> Change shortened link path style from u/r/file to u/r:file

- extension/content.css
> Fix account switcher's selectors

- src/content.js
- src/libs/mark-unread.js
> Correctly detect real unread notifications

- src/libs/mark-unread.js
Fixes #534
The console error also appears for everyone on https://github.com/marketplace
> Support pages with no notification icon

- readme.md
These will help keep track of what's on each store and if the deployment is working.
> Add Travis and version badges

- src/libs/page-detect.js
- test/page-detect.js
> Fix and test notification page detection

- extension/content.css
Closes #556 
Replaces and closes #569
> Drop the custom font stack for the code blocks

- extension/content.css
> Fix diff bar message position

- readme.md
Related: #560, #309, #411 
Not sure how many people read that far into the Readme, but it's a step into the right direction
> Add instructions for creating projects

- extension/content.css
* Simplify CSS without modifying existing behavior
* Use flex-box for reordering elements
> Simplify CSS for the dashboard

- extension/content.css
- readme.md
Replaces and closes #551
Closes #523
> Move Issue/PR labels below the title

- extension/content.css
I think it fixes #601
Definitely fixes #590 
Remembers #557 
Honors #396
Wishes luck to #382
Prays for #317 because that's still a separate issue
Blames it all on #254
> Totally finally fix every single removeDiffSigns bug forever

- src/content.js
Perform specific actions _only_ when user is logged in.
> Don't do anything when not logged into GitHub

- package.json
> Fix minify

- src/content.js
> Close More dropdown after visiting Compare

- extension/content.css
- src/content.js
- src/libs/utils.js
> The only other annoying thing is `padding-top` to `dashboard-sidebar`. Not every user has an organization switcher which leaves a large gap above sidebar.
> https://github.com/sindresorhus/refined-github/pull/599#issuecomment-313983025
> Only move the organization switcher if it exists

- extension/content.css
- src/content.js
- src/libs/reactions-avatars.js
Fixes #233 
Test it on: https://github.com/sindresorhus/refined-github/issues/74
Or on this post :)
> Auto-update reaction avatars

- src/content.js
> Fix issue/PR tabs after clicking Yours tab

- src/libs/reactions-avatars.js
Fixes https://github.com/sindresorhus/refined-github/pull/644#issuecomment-318318850
> Lower avatar limit

- readme.md
Fixes https://github.com/sindresorhus/refined-github/issues/181#issuecomment-318304190
@sindresorhus like this?
As per your comment in https://github.com/sindresorhus/module-requests/issues/99, that would make it a generic extension, not related specifically to GitHub
> Add ideas for browser extensions to develop to the readme

- src/content.js
- src/libs/add-releases-tab.js
No changes made other than the move.
> Cleanup: Move releases tab to its own file

- src/content.js
> check for repo nav element

- readme.md
Resolves https://github.com/sindresorhus/refined-github/issues/667 🎉
> Add GitHub Custom Tab Size to Related section

- extension/content.css
- src/content.js
> Restore nav links after GitHub updates

- src/content.js
> Fix header Trending link spacing

- src/libs/mark-unread.js
- fixes #497 
- uses `getUsername` from `utils` and removes `getUserName` function present in `mark-unread.js` since it was not working because of DOM changes.
> Fix "mark unread" not updating participating count on notifications page

- src/libs/linkify-urls-in-code.js
> Add issue linkify support for GH Enterprise

- src/content.js
- src/libs/page-detect.js
- test/page-detect.js
> Fix branch automatically not linking on quick pull request

- .travis.yml
- package.json
- This should finally only deploy if there are changes in the last day
- Also adds the possibility to manually deploy via (temporary?) tag
> Deployment conditions fix

- src/libs/show-names.js
> Contain Left-to-right Character in user names

- src/content.js
- src/libs/icons.js
Fixes #715 
I also tested this on GHE.
> Move Insights Tab to 'More'

- extension/content.css
Cause... why not? They're pretty awesome in diffs... ✨
> Make headers sticky in regular file views

- extension/content.css
- src/libs/copy-file-path.js
> Avoid overlap

- src/content.js
- src/libs/utils.js
Closes #678 
I used the `Promise` instead of a plain `try{ fn() } catch(e){ console.error(e) }` because the promise won't actually catch the error so they're easier to debug. Happy to discuss this.
~~The downside is that functions are called asyncronously.~~ Not anymore with `new Promise`
> Prevent everything from breaking if one feature breaks

- src/content.js
> Make space for Whitespace toggle in huge PRs

- src/content.js
The Insights link in the More dropdown will appear twice if you click a link and hit the back button.
> Fix duplicate Insights link in More dropdown

- src/content.js
- src/libs/scroll-to-top-on-collapse.js
> Keep PR file in view after collapsing it

- src/content.js
Add a hotkey (`g m`) for the users profile.
Fixes #688
> Add Hotkey for Users Profile

- src/libs/auto-load-more-news.js
- src/libs/utils.js
Fixes #757 
Obvious bug that only affects this part of the extension. Automerging in 5 min.
> Fix console error in newsfeed

- src/content.js
Fixes https://github.com/sindresorhus/refined-github/issues/757#issuecomment-339684928
> Run addYoursMenuItem onDomReady

- src/content.js
- src/libs/page-detect.js
This is mostly moving code around. If you read this code, do [commit by commit, possibly without whitespace.](https://github.com/sindresorhus/refined-github/pull/784/commits/063a9ab2a11bd00f50be35f5436aec6e737d1900?w=1)
> Cleanup init

- extension/content.css
As proposed in #755
Fixes #753 
Closes #755
If you feel that improvements on the footer could be made, open a PR. For now this will at least fix the existing inconsistency (and doesn't affect non-Enterprise GH anyway)
> Restore footer

- src/content.js
> Avoid shortening of linkified code

- extension/content.css
- src/features/add-diff-view-without-whitespace-option.js
- src/features/add-readme-buttons.js
- src/features/add-time-machine-links-to-comments.js
- src/features/copy-file-path.js
- src/features/mark-unread.js
- src/features/op-labels.js
- src/features/upload-button.js
> Restore feature: Remove most tooltips

- src/features/add-delete-fork-link.js
> Only show "delete fork" link if the user is allowed to

- src/features/add-ci-link.js
- src/features/more-dropdown.js
- src/libs/utils.js
A lil bug:
https://github.com/anthonygelibert/QLColorCode
> Fix CI link position on forks

- readme.md
PR best reviewed [one commit at a time](https://github.com/sindresorhus/refined-github/pull/813/commits/30724b65c0326aa60915ae6a048e5246ad7d4089)
> Readme: cleanup related extensions (drop, sort, update)

- source/options.html
Related to https://github.com/sindresorhus/refined-github/issues/840
> Add GHE notice for Firefox

- source/content.js
- source/features/add-releases-tab.js
> Sort repo navbar before first paint

- source/content.css
> Remove "Seeing something unexpected?" from user profiles

- source/features/copy-file.js
- source/libs/utils.js
> Fix gist copy button bug

- source/content.css
> Remove old dashboard CSS

- source/content.css
> Clean up the global footer

- package.json
Especially useful because `stylelint-order` is annoying 😅
> Add lint-fix npm script

- readme.md
> Fix broken link to "lots" "more..." in readme

- readme.md
Mention GHE in the readme, but let's avoid having to explain in two places.
Either
- we just leave a mention in the readme (like this PR), or
- we move the current options.html copy to the readme and link to it from options.html
The latter means making the readme even longer.
> Update instructions for GHE

- source/content.js
- source/libs/page-detect.js
- test/page-detect.js
Without this there would be errors in the console. Not a big deal but it's 3 lines of code that might be useful for #485
> Detect and avoid 404 and 500 error pages

- readme.md
> Add GitHub Issue Link Status to readme

- source/content.css
just optimize footer link color
> Optimize footer link color

- source/features/embed-gist-inline.js
Closes #870 
https://gist.github.com/staltz/868e7e9bc2a7b8c1f754 _(7 files)_
Plain link -> shortened link + loading -> shortened link + file count
https://gist.github.com/staltz/868e7e9bc2a7b8c1f754
https://gist.github.com/kenoir/8998532
> Gist embed: add "loading" + only embed if it's one file

- readme.md
> Document the option for disabling individual features

- readme.md
- source/content.js
- source/features/add-jump-to-bottom-link.js
> Add 'Jump to bottom' link to discussion pages

- readme.md
- source/content.css
Fixes #896 
Before | After
-|-
> Hide dashboard activity cards

- source/options.html
Enough to click on the sentence ...
> Better user experience

- source/content.css
> Hide all follow events in the dashboard

- source/manifest.json
> Fix API permission issue on Firefox

- source/content.css
> Fix Firefox button spacing in recently pushed branches

- source/background.js
- source/content.js
> Fix linkify-branch-refs feature name

- source/features/linkify-branch-refs.js
Fixes #833
Testing threads:
- deleted branch: https://github.com/sindresorhus/refined-github/pull/576
- deleted branch (from fork): https://github.com/sindresorhus/refined-github/pull/872
- restored branch: https://github.com/bfred-it/sandbox/pull/11
- restored branch (on fork): https://github.com/sindresorhus/refined-github/pull/909
> Restore linkify-branch-refs feature

- source/options.css
> Meta: Fix options pop up width in Chrome

- readme.md
As discussed in #923 
cc @sindresorhus @jgierer12 @hkdobrev @busches @paulmolluzzo
> Meta: Remove maintainers section

- readme.md
- source/content.js
- source/features/sort-issues-by-update-time.js
- source/libs/utils.js
> Change default issue/PR sort

- source/content.css
This was causing some issues with zenhub's overlays
> Fix conflict with ZenHub extension overlays

- source/features/remove-upload-files-button.js
Related to #754
Test page: https://github.com/sindresorhus/refined-github/tree/master/source
> Also remove the upload button in folder views

- source/content.css
> Restore tooltips on disabled buttons

- source/features/open-all-notifications.js
> Enable Open All Notifications button in repo-specific views

- source/content.js
- source/libs/page-detect.js
- test/page-detect.js
Fixes #957 
Just changed the regular expression used to detect if the current page is an 'issues' page.
> fix for #957 - Missing upload button on the new issue creation page

- source/features/show-names.js
Replaces #959
Untested because I can't find any bots. @shroudedcode can you link to an issue with bots to test this PR?
> Optimize full names selector

- source/content.css
Related to #928.
**Before:**
**After:**
> Fix alignment of the "Update branch" button for PRs

- source/features/add-releases-tab.js
Fixes #989 
Second commit fixes #993
> Fix a couple bugs related to the Releases tab

- readme.md
- source/content.js
- source/features/add-your-repositories-link-to-profile-dropdown.js
> Add "Your repositories" link to navbar profile dropdown

- source/content.css
- source/content.js
- source/features/hide-useless-newsfeed-events.js
I figured a couple more lines of code are worth it
> <img width="425" alt="screen shot 2018-01-13 at 14 02 28" src="https://user-images.githubusercontent.com/1402241/34903737-990e1808-f86a-11e7-8029-800b410e341a.png">
Closes #747
> Let users disable hiding some newsfeed events

- readme.md
- source/content.js
- source/features/add-scoped-search-on-user-profile.js
Fixes #1011.
The code still looks a little bit hacky for me, and I'm open for any suggestions!
> Add scoped search on user profile page

- source/content.js
- source/features/add-scoped-search-on-user-profile.js
From https://github.com/sindresorhus/refined-github/pull/1012#issuecomment-359321707
> Add scoped search on user profile before first paint

- readme.md
- source/content.css
- source/content.js
- source/features/add-toggle-files-button.js
- source/libs/icons.js
- source/libs/utils.js
Adds a button to toggle the files list as suggested by @Celthi and @jgierer12 in #598.
Clicking it will hide the files, show the other icon and apply a few CSS fixes like rounding corners.
*Closes #598*
> Add "Toggle files" button

- readme.md
- source/content.css
- source/content.js
- source/features/add-branch-buttons.js
- source/features/add-readme-buttons.js
Addresses https://github.com/sindresorhus/refined-github/pull/395#issuecomment-301186914
Related: https://github.com/sindresorhus/refined-github/issues/1029
cc @hkdobrev who suggested the change
> Move release link from readme to branch selector

- source/features/linkify-urls-in-code.js
> Add support for automatic title fetch in linkified issues

- package.json
- source/content.css
- source/content.js
- source/features/mark-unread.js
- source/features/open-all-notifications.js
- source/libs/icons.js
- source/libs/utils.js
> Add open in tabs for each repo in notifications

- source/content.css
- source/features/add-branch-buttons.js
- source/features/add-diff-view-without-whitespace-option.js
- source/features/add-time-machine-links-to-comments.js
- source/features/op-labels.js
- source/features/reactions-avatars.js
- source/features/toggle-all-things-with-alt.js
Follows up on https://github.com/sindresorhus/refined-github/pull/1002#issuecomment-358323339
Past discussion: https://github.com/sindresorhus/refined-github/issues/731
Any other annoying tooltip you can think of? They already removed the ones related to the reactions.
> Restore most tooltips

- source/content.css
- source/content.js
- source/features/monospace-textareas.js
> Add monospace textareas feature

- source/content.css
> Fix: Recently pushed branches are in the wrong position on forked repos

- source/features/add-title-to-emojis.js
> Don't break pre-existing tooltips on emojis

- source/features/add-patch-diff-links.js
> Fix patch/diff link feature

- readme.md
Or maybe we should move it to a separate section further down in the readme?
> Minor readme tweaks

- readme.md
- source/content.css
- source/content.js
- source/features/add-commented-menu-item.js
- source/features/add-yours-menu-item.js
> Add `Commented` button in the main issues search tab

- source/content.css
- source/features/add-branch-buttons.js
- source/features/copy-file-path.js
- source/features/copy-file.js
- source/features/open-all-notifications.js
- source/libs/group-buttons.js
- source/libs/utils.js
+ add commit I had missed for https://github.com/sindresorhus/refined-github/pull/1049#issuecomment-361235191
> Buttons code cleanup

- readme.md
- source/background.js
Closes #818
To test it locally, disable line 46.
> Open updates prompt on install

- source/features/linkify-urls-in-code.js
> Don't shorten links in code — again

- readme.md
https://github.com/DrewML/GifHub/issues/21
> GifHub is non-functional abandonware

- source/background.js
Fixes #1147.
The tab keeps opening for me, and I believe the previous call to the `set` method was incorrect.
Refs: 
https://developer.chrome.com/extensions/storage#method-StorageArea-set
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/storage/StorageArea/set
> Fix `userWasNotified` flag not being set

- readme.md
- source/content.css
Highlight linked issue comments with `:target` and modified color. Hope this is what you expected @bfred-it. 
Test comment : https://github.com/sindresorhus/refined-github/pull/988#issuecomment-357531152
Close #1164
> Highlight linked issue comment

- readme.md
Hopefully more people would see it and reduce feature requests in RG.
> Add GitHub Follow to the related extensions list

- source/content.css
Undoes #735 
Closes #1126 overlay without fixing it (the bugs will all just be invisible)
> Drop "dark modal backdrop"

- source/features/show-names.js
> Fix full name on GHE that requires auth

- readme.md
- source/content.css
- source/content.js
- source/features/hide-inactive-deployments.js
See description in #1144. Closes #1144.
> Hide inactive deployments

- readme.md
- source/content.css
> Highlight linked review comment

- source/background.js
- source/content.css
- source/content.js
- source/features/extend-status-labels.js
> Extend status labels for PRs too

- source/features/close-out-of-view-modals.js
> Fix out-of-view modal closing on certain modals

- source/content.css
- source/features/add-toggle-files-button.js
> Fix adding toggle files button on repo root

- source/features/sort-issues-by-update-time.js
> Support pulls/?user= URLs in sort-issues-by-update-time

- source/content.js
- source/features/open-all-selected.js
- source/libs/page-detect.js
- test/page-detect.js
This is an issue list, but it's not detected as such:
[github.com/sindresorhus/refined-github/**labels/change%20request**](https://github.com/sindresorhus/refined-github/labels/change%20request)
Also I merged `isPRList` because it was not currently needed anyway.
> Detect "Label" issue list as issue list

- source/features/open-all-notifications.js
Follows https://github.com/sindresorhus/refined-github/pull/1229#issuecomment-377258774
> Drop custom confirm box from open-all-notifications

- source/content.js
- source/features/upload-button.js
- source/libs/simplified-element-observer.js
Fixes #1242.
Explanation: https://github.com/sindresorhus/refined-github/issues/1242#issuecomment-381403293
-----------
The code looks a bit hacky, but works.
Open to any other suggestions or modifications!
> Fix upload button on comment textareas

- source/features/add-selection-in-new-tab.js
That's the first part in regards to #1240
> Open selection in new [background] tab with shift+o

- readme.md
I think we can remove the potentially ableist language here and keep the same meaning.
This would make it more inclusive to people with disabilities.
> Remove the word 'dumb'

- source/background.js
- source/features/add-scoped-search-on-user-profile.js
- source/features/add-your-repositories-link-to-profile-dropdown.js
- source/features/close-out-of-view-modals.js
- source/features/improve-shortcut-help.js
- source/features/linkify-urls-in-code.js
- source/features/mark-unread.js
Fixes #1305 + 6d658c4 + 44f0278
> Fix some recent errors

- source/features/add-selection-in-new-tab.js
Other part of #1240
I tested it locally and it works. Forgive me if this is not the way to do it - I'm no JS developer.
> Open selection mark list item as read.

- source/features/upload-button.js
This would help improve the accessibility of the button.
> Specify a title for upload attachments button

- source/content.css
> Hide the "Review Summary" header

- source/features/linkify-urls-in-code.js
> Linkify code blocks in comments

- source/features/upload-button.js
> Fixes 'Upload attachments' icon missing

- source/features/copy-file-path.js
- source/features/copy-file.js
> Restore file copy feature

- source/content.js
- source/features/close-out-of-view-modals.js
- source/features/copy-file.js
> Fix Console Errors

- source/background.js
- source/libs/api.js
- source/options.css
- source/options.html
- source/options.js
Closes #1374
Tested only with the "similar issues" search. Other features may need more testing, although this functionality should enable them as well.
> Add support for personal access tokens

- source/libs/api.js
> Handle API errors

- source/options.css
Needs to be `!important`
@bfred-it It only worked by me if I added  !important
> Fix width of personal tokens

- source/features/add-keyboard-shortcuts-to-comment-fields.js
> Don't affect the auto-complete in the comment box

- source/features/display-issue-suggestions.js
> Show colors of related issues

- source/content.js
- source/features/hide-issue-list-autocomplete.js
> disables browser autocomplete for issue/pull search

- source/content.css
> Fix issue filter dropdown conflict with sticky issue header

- source/content.css
- source/features/add-readme-buttons.js
Fixes #1437
For good or bad, GH keeps changing the DOM!
> Fix readme buttons

- source/content.css
Fixes #1066.
Wanted to leave this to @hkdobrev, but no one was picking it up.
> Remove user avatar from new comment form on threads

- source/content.css
> Fix wrapping issue on issue list

- package.json
- readme.md
- source/content.css
- source/content.js
- source/features/user-profile-follower-badge.js
- source/libs/api.js
- source/manifest.json
Fixes #1427
marked as WIP because I would like some suggestions on the way the API call should be handled. I added the if check in api.js for status 204 because the JSON parsing throws an error on that response from the [endpoint,](https://developer.github.com/v3/users/followers/#check-if-one-user-follows-another) since there's no body. also if a user doesn't follow you, it returns 404, which displays an error in the console.
> Add badge to profile if user follows you

- source/features/add-trending-menu-item.js
> Fix "Trending" menu item when displayed in navigation accordion

- source/content.css
Fixes https://github.com/sindresorhus/refined-github/issues/1485
> Fix PR label for stale view

- readme.md
- source/content.css
- source/content.js
- source/features/hide-useless-comments.js
Closes https://github.com/sindresorhus/refined-github/issues/1478
Testable on https://github.com/hayaku/hayaku/issues/303
This is how the comments reappear after clicking "Undo"
> Hide useless comments

- source/features/mark-unread.js
Minor change to add support for https://github.com/tanmayrajani/notifications-preview-github/issues/38 together with https://github.com/tanmayrajani/notifications-preview-github/pull/68
> Advertise "mark as unread" count to other extensions

- source/background.js
- source/features/add-branch-buttons.js
- source/features/add-releases-tab.js
- source/features/show-names.js
- source/libs/cache.js
Fixes #624 
Cookies are limited to about 170 entries, which makes it a pretty short cache though
> Add cookie-based cache with expiration

- source/features/hide-useless-comments.js
Closes #1543 
As per https://github.com/sindresorhus/refined-github/issues/1543#issuecomment-423378536
> Remove `hide useless comments` From Pr's

- source/content.css
> Increase width of review menu dialog

- .gitattributes
Stylelint got real mad me today on windows for not having unix line endings, now it's happy.
> Force css files to checkout as lf

- source/features/display-issue-suggestions.js
> Display issue number in display issue suggestions

- source/content.css
> Unhide new suggestions icon

- package.json
Follows https://github.com/sindresorhus/refined-github/pull/1611
Context: https://github.com/sindresorhus/refined-github/pull/1188/files
> Drop unused Babel plugin

- package.json
Follows https://github.com/babel/babel/pull/8448
Context in review comment: https://github.com/sindresorhus/refined-github/pull/1449/files#r216110819
> Drop object spread Babel plugin

- readme.md
- source/content.css
I feel that the field is too small, especially after adding our `sort:updated-desc`. This should make it more usable
> Widen issue search when focused

- source/features/mark-unread.js
> Only mark relevant notifications as read

- source/content.js
- source/features/add-delete-fork-link.js
- source/features/add-time-machine-links-to-comments.js
- source/features/extend-status-labels.js
- source/features/op-labels.js
- source/features/show-names.js
Fixes #1001
Implementation similar to #1658 
All tested
> Handle conversation updates for 5 old features

- source/features/show-names.js
- source/libs/utils.js
One request, always. Also detects `@ghost`
https://github.com/aspnet/AspNetCore/issues/2022
https://github.com/atom-minimap/minimap/issues/588
> Move `show-names` to API v4

- source/libs/page-detect.js
- Avoids unnecessary `if not`
- Drops long regexes
- Preserves performance
> Avoid long regexes in page-detect.js

- readme.md
- source/content.js
- source/features/infinite-scroll.js
> Drop infinite-scroll feature on user profile

- source/features/batch-open-issues.js
Fixes https://github.com/sindresorhus/refined-github/issues/1699
👋
Wanted to try and tackle this. Feedback is much appreciated!
> Enable `batch-open-issues` on global /pulls and /issues pages

- source/features/remove-projects-tab.js
> Always keep projects tab when current user is repo owner

- source/content.css
- source/features/upload-button.tsx
- source/libs/utils.js
_Details in the commit titles_
> Improve `upload-button` feature

- webpack.config.js
This will let you work on the extension without having to fight TS.
Only in watch mode
> Meta: generate the JS files even when TS errors

- readme.md
WIP PRs are now offered natively by GH
> Drop WIP PRs extension from Related section in readme

- source/features/wait-for-build.tsx
> Temporarily disable broken `wait-for-build`

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE/bug_fix.md
- .github/PULL_REQUEST_TEMPLATE/new_feature.md
These should help them provide the necessary information when opening issues and PRs
> Add issue and PR templates

- package-lock.json
- package.json
- webpack.config.js
```diff
> @ watch ~/refined-github
> webpack --mode=development --watch
-Hash: 2f921e27442babd59a80
Version: webpack 4.29.4
Time: 3517ms
Built at: 02/20/2019 11:22:32 PM
Asset      Size      Chunks             Chunk Names
background.js    19 KiB  background  [emitted]  background
background.js.map  21.6 KiB  background  [emitted]  background
-          background.ts  1.96 KiB              [emitted]  
browser-polyfill.min.js  9.79 KiB              [emitted]  
content.css  25.5 KiB              [emitted]  
content.js   328 KiB     content  [emitted]  content
content.js.map   335 KiB     content  [emitted]  content
-             content.ts  3.92 KiB              [emitted]  
-           globals.d.ts  87 bytes              [emitted]  
icon.png  1.89 KiB              [emitted]  
manifest.json …
```
> Hide unnecessary webpack stats

- source/features/close-out-of-view-modals.tsx
> Restore `close-out-of-view-modals` feature

- readme.md
- source/features/show-user-top-repositories.tsx
Partially reverts sindresorhus/refined-github#1781
> Revert "Find a user’s most recently updated repositories in their profile"

- readme.md
- source/content.css
As suggested in http://tonsky.me/blog/github-redesign/
Closes #1601
> Drop counters for Watch and Forks

- source/features/useful-not-found-page.tsx
- source/libs/page-detect.ts
- test/page-detect.ts
The DOM and page title were changed since https://github.com/sindresorhus/refined-github/pull/1558
> Fix 404 pages detection and support

- source/content.css
> Update dashboard style

- source/content.ts
https://ourcodeworld.com/articles/read/337/how-to-declare-a-new-property-on-the-window-object-with-typescript
> Meta: Simplify `select` global declaration

- source/features/copy-file.tsx
Fixes #1875 
https://github.com/sindresorhus/refined-github/blob/a759d4346e5ac4a98c9fdb2734cdae625de0f309/source/content.css
https://github.com/sindresorhus/refined-github/blob/a759d4346e5ac4a98c9fdb2734cdae625de0f309/source/icon.png (it shouldn't appear)
https://github.com/sindresorhus/refined-github/blob/a759d4346e5ac4a98c9fdb2734cdae625de0f309/readme.md (it shouldn't appear)
> Restore `copy-file` feature

- readme.md
- source/content.ts
- source/features/edit-comments-faster.tsx
Fixes https://github.com/sindresorhus/refined-github/issues/1504
> Add `edit-comments-faster` feature

- source/content.css
- source/features/warning-for-disallow-edits.tsx
> Hide `warning-for-disallow-edits` when PR is closed

- readme.md
- source/content.css
- source/content.ts
- source/features/edit-files-faster.tsx
- source/libs/features.tsx
- source/libs/on-file-list-update.ts
Closes https://github.com/sindresorhus/refined-github/issues/758
Open any repo's root, try changing branches, go back and forth in history, navigate in folders
> Add `edit-files-faster` feature

- readme.md
- source/content.ts
- source/features/remove-checks-tab.tsx
checks not gone- non zero: https://github.com/probot/semantic-pull-requests/pull/40
not gone- selected: https://github.com/sindresorhus/refined-github/pull/1928/checks
this page demonstrates it being gone unless youre owner
closes #1304
> Add `remove-checks-tab` feature

- source/content.css
> Loosen commit message length limits

- source/content.css
- source/features/recently-pushed-branches-enhancements.tsx
GHE still uses the old fixed with header, along with different markup/classes.
> Fix `recently-pushed-branches-enhancements` on GHE

- source/features/filter-pr-by-build-status.tsx
Fixes https://github.com/sindresorhus/refined-github/pull/1904#issuecomment-486709814
> Correctly remove the build status filter from query string

- source/features/link-to-file-in-file-history.tsx
https://github.com/sindresorhus/refined-github/commits/master No longer has button
https://github.com/sindresorhus/refined-github/commits/master/readme.md keeps the button
Fixes #2024
> Hide `link-to-file-in-file-history` where not needed

- source/features/hide-empty-meta.tsx
Fixes #2037
https://github.com/Witold101/wpw
> Fix `hide-empty-meta`

- source/features/wait-for-build.tsx
- source/libs/pr-ci-status.ts
Fixes https://github.com/sindresorhus/refined-github/issues/1792
Tested in Chrome and Firefox
> Fix `wait-for-build`

- source/features/clean-sidebar.tsx
> Fix clean-sidebar feature name

- source/features/recently-pushed-branches-enhancements.css
> Fix recently-pushed-branches div position in GHE

- source/content.ts
> Add `sort-issues-by-update-time` to `filter-comments-by-you`

- package-lock.json
- package.json
- source/features/linkify-issues-in-titles.tsx
- source/features/linkify-urls-in-code.tsx
- source/libs/page-detect.ts
Fixes https://github.com/sindresorhus/refined-github/issues/695 (oldest bug open)
Fixes https://github.com/sindresorhus/refined-github/issues/1499
Thanks to https://github.com/bfred-it/zip-text-nodes. Comments welcome on this package and its name too
URLs in diffs
https://github.com/Homebrew/homebrew-core/pull/18015/files
URLs in regular files
[/source/features/copy-markdown.js@`3f5fc48`#L45](
https://github.com/sindresorhus/refined-github/blob/3f5fc489e417d4f4a14da5ea423775e9ca9246fd/source/features/copy-markdown.js#L45)
URLs in PR files
https://github.com/sindresorhus/refined-github/pull/546/files#diff-36280fbf56b6409696e3d46d6b30118fR51
URLs in embedded code
https://github.com/sindresorhus/refined-github/blob/3f5fc489e417d4f4a14da5ea423775e9ca9246fd/source/features/copy-markdown.js#L45 …
> Restore and extend url linkifier

- source/features/mark-unread.tsx
> Show only GH Enterprise notifications on GH Enterprise

- source/features/reactions-avatars.tsx
Fixes #2125 
Test on: https://github.com/aio-libs/aiohttp/pull/3809 and on any issues with reactions
> Support bots in `reaction-avatars`

- source/features/esc-to-deselect-line.tsx
- source/features/selection-in-new-tab.tsx
- source/libs/dom-utils.ts
Fixes #2152
1. Go to https://github.com/sindresorhus/refined-github/issues
2. Give focus to the first issue
3. Put cursor in "Search all issues" searchbox
4. Press `Shift+O`
5. It should not open any issues
> `Shift+O` shouldn't work when inside an editable element

- source/libs/content-scripts-register-polyfill.ts
Follows #2111
Fixes #2174 #2173 #2171 https://github.com/sindresorhus/refined-github/pull/2184
cc'ing GHE users @ahatzz11 @gibfahn @rastersize @SivanMehta @NickCraver
> Make Enterprise injection more reliable /2

- source/features/clean-issue-filters.tsx
From https://github.com/sindresorhus/refined-github/commit/f19e54bf195cafd375f071636055a95b7a44cfb8#r34246594.
> Add `screenshot` field to `clean-issue-filters` feature

- package-lock.json
- package.json
https://github.com/bfred-it/shorten-repo-url/issues/16
https://github.com/BrowserSync/browser-sync/compare/62007c8b944808d1b46d42d5e22fa65883d1eaec 
https://github.com/BrowserSync/browser-sync/compare/client-ts 
https://github.com/BrowserSync/browser-sync/compare/client-ts...master
> Update `shorten-links` feature

- source/features/forked-to.tsx
Don't show current page fork.
Fixes #2246
1. Fork this project
2. Open your fork
3. Your fork should not be in the forked-to list.
> Don't show current page fork

- source/features/format-discussion-titles.tsx
> Extend `format-discussion-titles` to issue sticky header

- readme.md
- source/content.ts
- source/features/linkify-symbolic-links.tsx
- source/libs/dom-utils.ts
Closes #2276 
https://github.com/wmluke/angular-flash/blob/0.1.14/app/components
Additional test links welcome. This one leads to a 404
> Add `linkify-symbolic-links` feature

- package-lock.json
- source/features/minimize-user-comments.tsx
Fixes https://github.com/sindresorhus/refined-github/pull/2146#issuecomment-517392427 and https://github.com/sindresorhus/refined-github/pull/2146#issuecomment-517392965
> Fix `minimize-user-comments`

- webpack.config.ts
> Passing `true` as the second argument makes these values dynamic — so every file change will update their value.
Closes #2299
> Meta: Make `__featuresList__` & `__featuresInfo__` dynamic

- source/features/indented-code-wrapping.css
> Fix tooltip indentation for `indented-code-wrapping`

- source/features/sticky-discussion-sidebar.css
- source/features/sticky-discussion-sidebar.tsx
Fixes #2313 
> Actually, it looks like they made our job easier with this clean-up.
Turns out that not really, but it's still doable.
Any discussion.
> Fix `sticky-discussion-sidebar`

- readme.md
See https://twitter.com/sindresorhus/status/1160196902455062528 for context :)
> Add PR Monitor to related projects

- source/features/clean-footer.css
- source/features/hide-readme-header.css
Closes #2212
* https://github.com/about
* https://github.com/sindresorhus/refined-github
> Make footer text readable when user hovers over it

- source/features/sync-pr-commit-title.tsx
It wasn't updating the PR title.
> Fix `sync-pr-commit-title` to update the PR title

- source/features/batch-open-issues.tsx
Closes #2338
- https://github.com/issues (global)
- https://github.com/MrSwitch/hello.js/issues (repo you're not a collaborator of)
- (repo where you **are** a collaborator of)
> Fix `batch-open-issues` on glboal discussion list

- contributing.md
> Fix typo in the contributing guide

- source/libs/features.tsx
> Fix comment typo

- source/features/sticky-discussion-sidebar.css
Closes #2378
https://gist.github.com/defunkt
> Fix can't open dropdowns on Gists

- readme.md
- source/content.ts
- source/features/clean-rich-text-editor.css
- source/features/clean-rich-text-editor.ts
Closes #2349
Closes #566 
Closes #2311
This PR
> Hide unnecessary tip on comment field

- source/features/highest-rated-comment.tsx
Closes #2190
From original to make sure it still works:
leafo/sticky-kit#201
facebook/react#13991
flutter/flutter#11609 
MrMEEE/bumblebee-Old-and-abbandoned#123
Example of likes vs hearts + likes (also my project :smiley:)
https://github.com/microsoft/python-language-server/issues/19
> Consider more positive reactions in `highest-rated-comment`

- source/features/copy-file.tsx
I don't know if this works before, but from `features.isGist` I guess it is expected to, so here it is.
https://gist.github.com/KomaliVuddanti/f062a78b4fff3ee001529efe2a468375
> Make `copy-file` feature work on gists

- source/features/clean-sidebar.css
Closes https://github.com/sindresorhus/refined-github/issues/2269
> Restore subscription reason message in discussion sidebar

- source/features/warn-pr-from-master.tsx
Could you please also update the screenshot? I don't have access to a high DPI screen.
> Fix typo in `warn-pr-from-master`

- .github/workflows/test.yml
Trigger workflows on PRs in addition to push. @fregante do we need push still?
[e] Looks like this does work on forks and draft PRs.
> Trigger test workflow on PRs

- source/options.css
> Support dark mode in the options view

- source/features/copy-file.tsx
Source: https://github.com/sindresorhus/refined-github/pull/2505#discussion_r339354337
Maybe any file will do?
https://github.com/sindresorhus/refined-github/blob/master/package.json
> Remove unnecessary `groupSiblings`

- readme.md
- source/content.ts
- source/features/html-preview-link.tsx
- source/features/preview-html-files.tsx
- source/libs/utils.ts
Closes #1096 
https://github.com/CodingTrain/website/blob/4f90eedb9618257d9166241e92e51a7f3f00a08e/code_challenges/PerlinNoiseTerrain_p5.js/index.html
> Add `html-preview-link` feature

- source/features/releases-tab.tsx
Closes https://github.com/sindresorhus/refined-github/issues/2221
Test:
- open a new repo on the root, for example https://github.com/GhostText/GhostText
- open a new repo on any other page, for example https://github.com/fregante/doma/blob/master/index.ts
- open the same repo on any page, for example https://github.com/fregante/doma/pulls
> Use API to fetch releases count in `releases-tab`

- source/features/hide-inactive-deployments.tsx
- source/features/reactions-avatars.tsx
- source/libs/on-new-comments.ts
- source/libs/on-updatable-content-update.ts
I was trying to tackle https://github.com/sindresorhus/refined-github/issues/2264 but I don't know if I will get there.
> Various small improvements to ajaxed widgets updates handler

- source/features/clean-mergeability-box.css
Closes https://github.com/sindresorhus/refined-github/issues/963
> Restore CLI instructions for checking out PRs

- source/features/embed-gist-inline.tsx
I don't think there needs to be a big description for this 😉
> Missing file extension in screenshot

- source/features/embed-gist-via-iframe.tsx
- source/libs/page-detect.ts
Fixes #2530
https://gist.github.com/yakov116 (no more error)
https://gist.github.com/yakov116/2d81580f7907839f9065e670f0aba64c (ensure it still works)
[Test for GHE]
> Fix console error caused by `embed-gist-via-iframe`

- source/features/repo-age.tsx
Addresses https://github.com/sindresorhus/refined-github/pull/2560#discussion_r352330690
> Add caching functionality to repository age feature

- package.json
- source/globals.d.ts
- source/options-storage.ts
- webpack.config.ts
Minor changes. Feel free to ignore. I'll test and merge tomorrow
> Meta: Reduce Option types by moving its generation to webpack

- package-lock.json
- package.json
- source/features/faster-pr-diff-options.tsx
- source/features/highlight-closing-prs-in-open-issues.tsx
- source/libs/features.tsx
- source/libs/get-default-branch.ts
- source/options.html
- source/options.tsx
- webpack.config.ts
Minor changes. Feel free to ignore. I'll test and merge tomorrow
> Meta: Minor improvements thanks to new JS operators

- source/features/user-local-time.tsx
Fixes https://github.com/sindresorhus/refined-github/pull/2549#issuecomment-567243946
> Avoid console error caused by `user-local-time`

- .github/workflows/test.yml
https://snyk.io/blog/why-npm-lockfiles-can-be-a-security-blindspot-for-injecting-malicious-modules/
Testing this out
> Meta: Add lockfile security check to CI

- source/features/edit-comments-faster.tsx
- source/features/embed-gist-via-iframe.tsx
- source/features/pr-filters.tsx
- source/features/reload-failed-proxied-images.tsx
- source/features/split-issue-pr-search-results.tsx
- source/globals.d.ts
Due to https://github.com/microsoft/TypeScript/issues/283
However it's not entirely correct, so if you know a solution to this comment, speak up https://github.com/microsoft/TypeScript/issues/283#issuecomment-571024679 😄
> Fix `cloneNode` type

- source/features/highlight-collaborators-and-own-discussions.tsx
> Restore `highlight-collaborators-and-own-discussions`

- source/features/widen-search-field.css
Closes #2705
Closes #2703
https://github.com/notifications/beta
> fix notifications beta auto completetion overlap

- source/features/sticky-discussion-sidebar.css
Reverts sindresorhus/refined-github#2716
> Revert "Fix `z-index` bug caused by `sticky-discussion-sidebar`"

- package-lock.json
- package.json
- source/features/close-out-of-view-modals.tsx
- source/features/mark-unread.tsx
- source/features/sync-pr-commit-title.tsx
- source/libs/features.tsx
- source/libs/utils.ts
- test/page-detect.ts
- test/utils.ts
I felt that the errors could be more detailed and helpful
> Meta: Add error logger that helps user search/report issues

- source/features/forked-to.tsx
Fixes #2334 
Not sure if that is what you expected to fix the issue :smile:
> Avoid console error caused by `forked-to`

- source/options.html
Related to https://github.com/sindresorhus/refined-github/issues/2679
Closes https://github.com/sindresorhus/refined-github/issues/2693
Please review and suggest further copy or explanation you think it's needed here.
> Meta: Improve copy around personal access token in the options

- source/features/widen-search-field.css
Closes #2703
Closes #2705
https://github.com/notifications/beta
https://github.com/sindresorhus/refined-github/actions
> Fix autocompletion overlap in Notifications’ Beta

- .github/CODEOWNERS
Looks like the codeowner path for this file is slightly wrong. It needs to be `source/features/show-whitespace.tsx` not `source/features/show-whitespaces.tsx`
> Fix wrong file path in CODEOWNER

- source/features/global-discussion-list-filters.tsx
- source/features/split-issue-pr-search-results.tsx
- source/libs/search-query.ts
I had this in mind for a while and #2745 pushed me to finally write it. This class would help us consistently parse and manipulate the search query.
> Improve GitHub search query manipulation

- source/features/show-whitespace.tsx
Fixes https://github.com/sindresorhus/refined-github/issues/2285
It's ugly, honestly, but I can't make it any better. Alternative PRs welcome
https://github.com/sindresorhus/refined-github/blob/2e4a24d3957c205c7bc49525c69e1fa08593d2ca/readme.md#L107-L112
https://github.com/sindresorhus/refined-github/blob/0b40361983b362d028fac2fe0fed9486134fa41e/package.json#L1-L4
> Avoid extra whitespace in embedded code with `show-whitespace`

- readme.md
Add to readme how to enable chrome extensions, with link to official docs, in the new Edge.
Tested on Microsoft Edge `Version 80.0.361.48 (Official build) (64-bit)` on Mac Os Catalina `10.15.2`
> Add the Chromium-based Edge to supported browsers

- source/features/tags-dropdown.css
- source/features/tags-dropdown.tsx
Closes #2781
1. https://github.com/sindresorhus/refined-github/releases
2. https://github.com/nodejs/node/releases
> Update `tags-dropdown` selectors

- source/options.css
- source/options.tsx
Closes #2791 
Changing body background color based on the browser you're using.
Tested on Win10 using Firefox and Chrome.
> Improve settings in dark mode in Firefox

- source/features/mark-private-orgs.tsx
It didn't make sense to follow #2671 since this only adds some overlays on a minor part of the page, but at least this adds caching and changes the API to the lighter v4
> Faster `mark-private-orgs`

- source/features/add-tag-to-commits.tsx
- source/features/deprioritize-marketplace-link.tsx
- source/features/user-local-time.tsx
- source/libs/features.tsx
- source/libs/page-detect.ts
Not sure if this is the best way.
Closes #2823
fixes #2128
> Fix some console errors

- source/features/mark-private-orgs.tsx
Fixes https://github.com/sindresorhus/refined-github/issues/2830.
Details: https://github.com/sindresorhus/refined-github/issues/2830#issuecomment-591111897.
> Fix `mark-private-orgs` showing on all organizations

- source/features/bugs-tab.tsx
>  Don't exclude bugs from Issues tab (`bugs-tab`)

- .github/pull_request_template.md
- source/features/hide-navigation-hover-highlight.css
- source/features/improve-shortcut-help.tsx
- source/features/pr-branches.tsx
- source/features/selection-in-new-tab.tsx
- source/features/tags-dropdown.css
- source/libs/api.ts
Idea came from https://github.com/sindresorhus/refined-github/pull/2858#discussion_r388836596
Fixes #2849
<!-- 
2. TEST URLS:
3. SCREENSHOT:
> Lint and minor console errors fixes

- source/features/link-to-file-in-file-history.tsx
Fix #2871
<!--
2. TEST URLS:
3. SCREENSHOT:
> Fix `link-to-file-in-file-history`

- source/features/user-profile-follower-badge.css
Fix #2874
Cause for this: `.float-left` name card
~~Also remove the margin since it looks pretty fine.~~ I'm using custom styles in the following image, please ignore it
> Fix position of `user-profile-follower-badge`

- source/options-storage.ts
> Avoid losing options when removing the github.com permission

- source/features/forked-to.tsx
> Make `forked-to`'s cache case-insensitive

- source/features/close-out-of-view-modals.tsx
Error mentioned in #2907
<!--
2. TEST URLS:
3. SCREENSHOT:
> Fix `close-out-of-view-modals`

- source/features/default-branch-button.tsx
Closes #2936
<!--
2. TEST URLS:
3. SCREENSHOT:
> Show `default-branch-button` on Commit lists

- source/features/default-branch-button.tsx
Follow up to #2938
Test on https://github.com/sindresorhus/refined-github/pull/2938/commits
<!--
2. TEST URLS:
3. SCREENSHOT:
> Don't try to add `default-branch-button` to PR Commits pages

- source/features/hide-inactive-deployments.tsx
- source/libs/on-new-comments.ts
GitHub changed the selector.
* https://github.com/OpenLightingProject/open-fixture-library/pull/425
> Fix `hide-inactive-deployments` and "Load more..." detection

- source/features/copy-file.tsx
Fixes #2957 
Test on https://github.com/DrewML/GifHub/blob/master/LICENSE.md 
<!--
2. TEST URLS:
3. SCREENSHOT:
> Remove `copy-file` from Markdown view

- readme.md
- source/features/bypass-checks.tsx
Fixes #2003 
Replaces and closes #2968 
Has 3 local links to 3rd party services (will be replaced)
https://github.com/Kocal/symfony-app-template/pull/335
Has 8 GHA links and 2 external links to 3rd party services (all will be skipped)
https://github.com/sindresorhus/eslint-plugin-unicorn/pull/661
> Fix link selection logic in `bypass-checks`

- source/libs/page-detect.ts
- test/page-detect.ts
Should fix part of #2907, specifically https://github.com/sindresorhus/refined-github/issues/2907#issuecomment-607861547
Plus small related improvements
> Fix some page detection

- source/libs/page-detect.ts
Test On https://github.com/sindresorhus/refined-github/commits?author=fregante
<!--
2. TEST URLS:
3. SCREENSHOT:
> Detect filtered commit list in `isRepoCommitList`

- source/features/update-pr-from-base-branch.tsx
Bumped into this while testing.
Its a little hard to allow you to test unless you want me to add you as a collaborator
https://github.com/yakov116/TestR/pull/7
<!--
2. TEST URLS:
3. SCREENSHOT:
> Disable `update-pr-from-base-branch` when action is impossible

- readme.md
- source/features/clear-pr-merge-commit-message.tsx
- source/refined-github.ts
Closes https://github.com/sindresorhus/refined-github/issues/2564
Find a PR:
- you can merge
- has some Co-Authors (or doesn't)
> Add `clear-pr-merge-commit-message` feature

- readme.md
- source/features/gha-runs-from-workflow-file.tsx
- source/features/go-to-action-from-file.tsx
- source/refined-github.ts
Fix #3008 
https://github.com/r-hub/docs/blob/master/.github/workflows/pr.yml
https://github.com/r-hub/docs/blob/master/.github/workflows/urlchecks.yml (not working yet, not sure why the URL encoding fails)
> Add `go-to-action-from-file` feature

- readme.md
- source/features/unwrap-useless-dropdowns.tsx
- source/libs/page-detect.ts
- source/refined-github.ts
> Add `unwrap-useless-dropdowns` feature

- source/features/hide-disabled-milestone-sorter.tsx
Test on [sindresorhus/eslint-plugin-unicorn/milestone/1](https://github.com/sindresorhus/eslint-plugin-unicorn/milestone/1)
> Fix console error in `hide-disabled-milestone-sorter`

- source/features/pr-filters.tsx
A (late) follow-up to #2776, references #2671.
Test here: https://github.com/sindresorhus/refined-github/pulls
> Make `pr-filters` faster

- package.json
- source/features/download-folder-button.tsx
- source/features/linkify-symbolic-links.tsx
- source/features/remove-upload-files-button.tsx
- source/features/show-names.tsx
- source/features/show-user-top-repositories.tsx
None
2. TEST URLS:
There should be no changed to functionality, I tested them all.
3. SCREENSHOT:
None
> Use Optional chaining where possible

- source/features/show-user-top-repositories.tsx
Follows https://github.com/sindresorhus/refined-github/pull/3101#commitcomment-39268247
> Limit `show-user-top-repositories` to the main profile tab

- .github/pull_request_template.md
This change request is so simple it is not worth adding any more information...
> Meta: Fix comment in PR template

- source/features/hide-zero-packages.tsx
- source/features/remove-projects-tab.tsx
Follows #3103 
None
2. TEST URLS:
https://github.com/microsoft (Should **not** get removed)
https://github.com/babel (Should get removed)
3. SCREENSHOT:
None
> `hide-zero-packages` on organization profiles 

- source/features/highlight-collaborators-and-own-discussions.tsx
I am not sure if there should be a max age, these things don't change very often.
> Add cache to `highlight-collaborators-and-own-discussions`

- source/github-helpers/index.ts
Follows https://github.com/sindresorhus/refined-github/commit/9ddcd95d766d26af8fe6362c65f32370464c5bd2#r39608686
> Restore private repo in some features

- source/options-storage.ts
> Meta: update code comment

- source/github-helpers/index.ts
Follows https://github.com/sindresorhus/refined-github/pull/3166#issuecomment-638210073
> Meta: refactor `getCurrentBranch`

- source/features/latest-tag-button.tsx
Follows https://github.com/sindresorhus/refined-github/issues/2927#issuecomment-638420454
> Avoid errors in `latest-tag-button` if count can’t be determined

- source/features/edit-files-faster.tsx
> Restore `edit-files-faster` in "Repository refresh" beta

- source/features/toggle-files-button.css
- source/features/toggle-files-button.tsx
As discussed in <https://github.com/sindresorhus/refined-github/pull/3187#discussion_r436266144>.
> Use fold/unfold octicons for `toggle-files-button`

- source/features/raw-file-link.tsx
I also changed it be consistent with `enable-file-links-in-compare-view`
Test on https://github.com/sindresorhus/refined-github/compare/20.5.27...master
> Enable `raw-file-link` on `isCompare`

- source/features/edit-readme.tsx
- source/features/hide-readme-header.css
> Restore `edit-readme` in "Repository refresh" beta

- source/features/forked-to.tsx
Closes #2810
2. TEST URLS:
Test on any fork
3. SCREENSHOT:
None
> Link to current file/folder in `forked-to` links

- contributing.md
Closes #3202 
Add a note about the node version required to run the extension locally.
I ended up adding it just before the workflow section since that's where we start  mentioning commands and scripts to run. I thought it made more sense to keep it together.
> Docs: Mention Node requirement in contributing.md

- source/features/recently-pushed-branches-enhancements.css
References #3081.
(reveals older branches on hover)
(always shows all branches and overlaps content)
(reveals older branches on hover)
---
Unfortunately, the DOM changed quite a bit, so making it more concise is impossible without changing it the DOM with JavaScript. This PR just makes the feature usable again.
<details>
<summary>Old markup</summary>
```html
<div class="js-socket-channel js-updatable-content"
data-channel="repo:214006287:post-receive:202916 repo:214006287:branch:test repo:214006287:branch:test2"
data-url="/sindresorhus/refined-github/show_partial?partial=tree%2Frecently_touched_branches_list">
<div class="mb-3">
<p class="text-small text-gray mt-0 mb-1">
Your recently pushed branches:
</p>
<div class="RecentBranches">
<div class="RecentBranches-item p-2 clearfix">
<a …
```
> Restore `recently-pushed-branches-enhancements` in "Repository refresh" beta

- readme.md
- source/features/restore-file.tsx
- source/options-storage.ts
- source/refined-github.ts
Resolves #3161
2. TEST URLS:
None
3. SCREENSHOT:
**Does this need to be updated?** Or its file the way it is?
> Rename `revert-file` to  `restore-file`

- source/features/default-branch-button.tsx
Follows #3221. Sorry for not testing with "Repository refresh" beta disabled :/
Thanks @yakov116 for catching this in https://github.com/sindresorhus/refined-github/pull/3214#issuecomment-645008022
> Fix `default-branch-button` in "old design"

- source/features/bugs-tab.tsx
> Restore `bugs-tab` in "Repository refresh" beta

- source/features/show-followers-you-know.tsx
Use the same classes as organizations.
> Update `show-followers-you-know` class

- source/features/clone-branch.tsx
- source/features/show-associated-branch-prs-on-fork.tsx
Selector updates
Test On https://github.com/yakov116/refined-github/branches
> Fix `clone-branch` and `show-associated-branch-prs-on-fork`

- source/features/set-default-repositories-type-to-sources.tsx
Tests:
- This page (header dropdown)
- https://github.com/sindresorhus (user profile)
- https://github.com/github (organization)
> Update `set-default-repositories-type-to-sources` selectors

- source/features/html-preview-link.tsx
Close #3295
Tests
- https://github.com//sindresorhus/refined-github/blob/master/source/options.html -> https://refined-github-html-preview.kidonng.workers.dev/sindresorhus/refined-github/raw/master/source/options.html
- https://github.com/ajtoo/Demo-Single-Page/blob/master/index.html -> https://refined-github-html-preview.kidonng.workers.dev/ajtoo/Demo-Single-Page/raw/master/index.html
> Use CloudFlare Workers for `html-preview-link`

- source/features/align-repository-header.css
Closes #3332 
Fixes https://github.com/sindresorhus/refined-github/pull/3313#issuecomment-655491090
> Fix `align-repository-header` on gists

- source/features/highest-rated-comment.tsx
Fixes #3338 
Test on https://github.com/ysc3839/FontMod/issues/59
> Fix `highest-rated-comment` overlap with avatar

- source/features/bugs-tab.tsx
> Restore `bugs-tab`

- readme.md
- source/features/vertical-front-matter.css
- source/features/vertical-front-matter.tsx
- source/refined-github.ts
Close #3325 
Test: https://github.com/gatsbyjs/gatsby/blob/master/docs/blog/2020-07-07-wordpress-source-beta/index.mdx
Screenshot:
> Add `vertical-front-matter` feature

- source/features/ci-link.css
- source/features/ci-link.tsx
- source/features/file-finder-buffer.tsx
- source/features/fork-source-link-same-view.tsx
- source/features/releases-tab.tsx
- source/features/show-open-prs-of-forks.tsx
> Fix features relying on `.pagehead` 

- source/features/parse-backticks.tsx
Restored `isDashboard` "help wanted" event titles
And resorted the list
> Restore `parse-backticts` on `isPulse`

- source/features/repo-age.tsx
Test on https://github.com/sindresorhus/css-in-readme-like-wat
Selector update
> Fix `repo-age` where there is only one commit

- source/features/align-issue-labels.css
> Fix `align-issue-labels` selector

- source/features/show-whitespace.css
Closes #3375
Any file diff or file content page (eg: https://github.com/sindresorhus/refined-github/pull/3387/files#diff-1034120c49056be4c8f62f895cbd18e0)
| Before | This PR |
|:-:|:-:|
| ![prev](https://user-images.githubusercontent.com/37769974/88254430-f2631680-ccd2-11ea-9790-6ba876c8b813.png) | ![next](https://user-images.githubusercontent.com/37769974/88254403-e1b2a080-ccd2-11ea-9790-0caa71a7da8c.png) |
> Reduce opacity of `show-whitespace`

- source/features/add-tag-to-commits.tsx
- source/features/mark-merge-commits-in-list.tsx
Test on https://github.com/sindresorhus/refined-github/commits/master/.gitattributes
> Fix `add-tag-to-commits` and `mark-merge-commits-in-list`

- source/features/remove-projects-tab.tsx
https://github.com/sindresorhus/refined-github/pull/3286#issuecomment-662357039
This PR was initially solving the same problem so I didn't open a new one, I hope this won't cause trouble.
> Fix `remove-projects-tab` selector

- source/features/follow-file-renames.tsx
Attn: Github, in the future if you want to break thing please do it all at once. Please don't break one thing a day!
Sincerely Yakov
Test on: https://github.com/yakov116/refined-github/commits/f23b687b3b89aa95a76193722cdfeff740646670?after=f23b687b3b89aa95a76193722cdfeff740646670+34&path%5B%5D=source&path%5B%5D=features&path%5B%5D=release-download-count.tsx
> Fix `follow-file-renames` selectors

- source/features/default-branch-button.tsx
- source/features/latest-tag-button.tsx
> Fix bad linebreaks in `default-branch-button` and `latest-tag-button`

- package-lock.json
- package.json
- source/features/parse-backticks.tsx
On request by https://github.com/sindresorhus/refined-github/pull/3290#issuecomment-659262450
Part of #3084
~~Edited the title and it stil runs well!!! 😋 (though there's about 2 seconds' delay)~~ (Never mind, that is `format-conversation-titles`)
> Make `parse-backticks` more reliable

- license
- source/features/restore-file.tsx
Fixes #3417 
2. TEST URLS:
This PR
3. SCREENSHOT:
None
> Fix `restore-file` for deleted files in forks

- source/features/sticky-conversation-sidebar.css
Test: https://github.com/sindresorhus/refined-github/pull/3442
Before:
After:
> Fix `sticky-conversation-sidebar` spacing

- source/features/forked-to.tsx
- source/github-helpers/github-url.ts
Resolves #3416
Resolves #3415
2. TEST URLS:
Have a fork of this repo
https://github.com/sindresorhus/refined-github/edit/master/.editorconfig
3. SCREENSHOT:
None
> Preserve current branch in `forked-to` link when possible

- source/features/repo-age.tsx
Follows https://github.com/sindresorhus/refined-github/issues/3340#issuecomment-671049624
> Only use the default branch to determine `repo-age`

- source/features/dim-bots.tsx
https://github.com/scala-steward-org
> Dim `scala-steward` bot

- source/features/release-download-count.tsx
Fixes #3471
Test URL: https://github.com/makeworld-the-better-one/amfora/releases
> `release-download-count`: hide zero download counts

- source/features/remove-label-faster.tsx
[comment](https://github.com/sindresorhus/refined-github/pull/3454#issuecomment-674854302)
2. TEST URLS:
[sindresorhus/refined-github/issues/3440](https://github.com/sindresorhus/refined-github/issues/3440)
[sindresorhus/refined-github/pull/3454](https://github.com/sindresorhus/refined-github/pull/3454)
3. SCREENSHOT:
> Fix `remove-label-faster`

- source/features/download-folder-button.tsx
Closes #3449
2. TEST URLS:
https://github.com/sindresorhus/refined-github/tree/incremental-tag-changelog-link/media?rgh-link-date=2020-08-10T10%3A00%3A55Z
3. SCREENSHOT:
> Fix conflicts with `default-branch-button`

- source/features/navigate-pages-with-arrow-keys.tsx
Closes #3466
2. TEST URLS:
[https://github.com/sindresorhus/refined-github/releases](https://github.com/sindresorhus/refined-github/releases)
[https://github.com/sindresorhus/refined-github/pulls?q=](https://github.com/sindresorhus/refined-github/pulls?q=)
[https://github.com/sindresorhus/refined-github/commits/master](https://github.com/sindresorhus/refined-github/commits/master)
[https://github.com/sindresorhus/refined-github/search?q=+is%3Aissue&type=Issues](https://github.com/sindresorhus/refined-github/search?q=+is%3Aissue&type=Issues)
3. SCREENSHOT:
> Restore `navigate-pages-with-arrow-keys`

- source/features/clean-conversation-headers.tsx
> Add missing space in `clean-conversation-headers` 

- .xo-config.js
- source/features/add-tag-to-commits.tsx
- source/features/convert-release-to-draft.tsx
- source/features/deep-reblame.tsx
- source/features/faster-reviews.tsx
- source/features/highest-rated-comment.tsx
- source/features/highlight-non-default-base-branch.tsx
- source/features/reactions-avatars.tsx
- source/features/remove-label-faster.tsx
- source/features/remove-projects-tab.tsx
- source/features/show-whitespace.tsx
- source/features/stop-redirecting-in-notification-bar.tsx
- source/features/tag-changelog-link.tsx
- source/features/vertical-front-matter.tsx
- source/github-helpers/api.ts
- source/github-helpers/github-url.ts
- source/github-helpers/index.ts
@fregante I went through them all only `@typescript-eslint/require-await': 'error'` am I not sure if they are correct.
> Meta: enable more lint rules

- source/features/format-conversation-titles.tsx
Closes #3458
2. TEST URLS:
3. SCREENSHOT:
Before![Before](https://user-images.githubusercontent.com/1402241/90074305-d0b5e780-dcf2-11ea-82da-cacf68b5a0e4.gif)
After![After](https://user-images.githubusercontent.com/36174850/90580506-bc318d80-e1d1-11ea-8a1c-6ce68ad8ab28.gif)
> Fix `format-conversation-titles`

- source/features/navigate-pages-with-arrow-keys.tsx
2. TEST URLS:
[/notifications](https://github.com/notifications)
3. SCREENSHOT:
> Apply `navigate-pages-with-arrow-keys` to notification page

- source/features/clean-conversation-headers.css
- source/features/clean-conversation-headers.tsx
Closes #3461
2. TEST URLS:
[flarum/core/pull/2263](https://github.com/flarum/core/pull/2263)
3. SCREENSHOT:
> Highlight a PR's base branch if it's not the default

- source/features/pull-request-hotkey.tsx
https://github.com/sindresorhus/refined-github/pull/1167#issuecomment-679443490
> Fix `pull-request-hotkey`

- source/features/latest-tag-button.tsx
Fix #3493
Test: https://github.com/sindresorhus/refined-github
> Fix `latest-tag-button` position

- source/features/edit-readme.tsx
#2671
Test on
https://github.com/yakov116/refined-github
> Faster `edit-readme`

- source/features/show-associated-branch-prs-on-fork.tsx
#2671
2. TEST URLS:
https://github.com/yakov116/refined-github/branches
> Use `selector-observer` in `show-associated-branch-prs-on-fork`

- source/features/clone-branch.tsx
#2671
2. TEST URLS:
https://github.com/sindresorhus/refined-github/branches
3. SCREENSHOT:
None
> Refactor `clone-branch` to use `selector-observer`

- source/features/cleanup-repo-filelist-actions.tsx
https://github.com/sindresorhus/refined-github/pull/3405#issuecomment-666905584
2. TEST URLS:
Open any file (such as https://github.com/sindresorhus/refined-github/blob/master/license) and go to repo root (https://github.com/sindresorhus/refined-github)
3. SCREENSHOT:
None
> Improve `cleanup-repo-filelist-actions`’s reliability

- source/features/user-local-time.tsx
Fixes #2612 
2. TEST URLS:
https://github.com/sindresorhus/refined-github/issues/3523 the first posts user
3. SCREENSHOT:
None
> Hide `user-local-time` if timezone is unknown

- readme.md
- source/background.ts
Thanks to @notlmn (https://github.com/sindresorhus/refined-github/pull/3421) I no longer have to manually update the changelog: https://github.com/sindresorhus/refined-github/issues/1137
I created https://github.com/sindresorhus/refined-github/issues/3543 as a new welcome screen and I'll update the documentation in this PR.
Next:
> Meta: Update welcome screen

- source/features/highlight-collaborators-and-own-conversations.tsx
https://github.com/sindresorhus/refined-github/pull/3505#issuecomment-687302600
> Faster `highlight-collaborators-and-own-conversations`

- source/features/batch-mark-files-as-viewed.tsx
Closes #3549 
2. TEST URLS:
https://github.com/sindresorhus/refined-github/pull/3540/files
3. SCREENSHOT:
No Screenshots
> Allow selecting files bottom to top in  `batch-mark-files-as-viewed`

- source/features/index.tsx
https://github.com/sindresorhus/refined-github/pull/3530#issuecomment-692328643
2. TEST URLS:
None. Background job.
[Steps to test](https://github.com/sindresorhus/refined-github/pull/3530#issuecomment-687518706)
3. SCREENSHOT:
Not Applicable
> Meta: enable hotfixes search on GitHub Enterprise

- source/features/cleanup-repo-filelist-actions.tsx
None
2. TEST URLS:
3. SCREENSHOT:
Before: 
After:
> Fix incorrect spacing in `cleanup-repo-filelist-actions`

- source/features/split-issue-pr-search-results.tsx
https://github.com/sindresorhus/refined-github/pull/1738
2. TEST URLS:
https://github.com/sindresorhus/refined-github/search?q=batch-mark-files-as-viewed&unscoped_q=batch-mark-files-as-viewed
3. SCREENSHOT:
None
Small selector update
> Restore `split-issue-pr-search-results`

- source/features/user-local-time.tsx
Resolves #3597 
2. TEST URLS:
My Avatar
3. SCREENSHOT:
> Use system setting for `user-local-time` time formatting

- source/features/toggle-files-button.css
Add bottom `border-radius` when collapsed. 🔥 
No issue
2. TEST URLS:
3. SCREENSHOT:
<table>
<tr>
<td>Before
<td>After
<tr>
<td><img width="140" alt="Captura de pantalla 2020-10-15 a las 20 51 56" src="https://user-images.githubusercontent.com/11599942/96174922-5db33200-0f2a-11eb-8012-30ef047772c9.png">
<td><img width="150" alt="Captura de pantalla 2020-10-15 a las 20 51 38" src="https://user-images.githubusercontent.com/11599942/96174936-6441a980-0f2a-11eb-9d8e-fd20013f87f6.png">
</table>
> Correct border radius for `toggle-files-button`

- source/features/highest-rated-comment.css
- source/features/highest-rated-comment.tsx
- source/features/releases-tab.tsx
- source/helpers/loose-parse-int.ts
Test on https://github.com/ysc3839/FontMod/issues/59
Slightly simplifies the feature
> Refactor `highest-rated-comment`

- package-lock.json
- package.json
- source/globals.d.ts
- source/options.tsx
- webpack.config.ts
Closes #3687.
[`markdown-wasm`](https://github.com/rsms/markdown-wasm) is [blazing fast and reasonably small](https://www.infoq.com/news/2020/10/markdown-wasm-fast-parser/).
> Meta: Parse feature descriptions at build time

- source/features/clean-dashboard.css
- source/features/clean-pinned-issues.css
- source/features/table-input.css
- source/refined-github.css
- move border color to CSS variable
- normalize gray border color to `#e1e4e8`
No issue
2. TEST URLS:
https://github.com/ (dashboard)
3. SCREENSHOT:
The border after "All activity" was darker.
<table>
<tr>
<td>Before
<td>After
<tr>
<td><img width="356" alt="Captura de pantalla 2020-10-16 a las 1 07 09" src="https://user-images.githubusercontent.com/11599942/96195030-01f9a080-0f4c-11eb-9ea4-fb2535bfefdb.png">
<td><img width="396" alt="Captura de pantalla 2020-10-16 a las 1 06 46" src="https://user-images.githubusercontent.com/11599942/96195052-0b830880-0f4c-11eb-85b7-086db161c259.png">
</table>
> Use a consistent border color

- source/features/profile-hotkey.tsx
fixes #3720 
2. TEST URLS:
every where including gists
3. SCREENSHOT:
none
> Fix `profile-hotkey`

- readme.md
- source/features/highest-rated-comment.css
- source/features/highest-rated-comment.tsx
Fixes https://github.com/sindresorhus/refined-github/issues/3703
> Update `highest-rated-comment` style

- source/features/unfinished-comments.tsx
1. LINKED ISSUES: #3694 (cf. [this comment](https://github.com/sindresorhus/refined-github/pull/3694#issuecomment-722707088))
2. TEST URLS: #3707
3. SCREENSHOT: n/a
> Improve `unfinished-comments` detection logic

- readme.md
- source/features/pr-easy-toggle-files.tsx
- source/refined-github.ts
Fixes #3738.
2. TEST URLS:
https://github.com/microsoft/TypeScript/pull/12114/files
https://github.com/sindresorhus/refined-github/pull/3750/files
3. SCREENSHOT:
> Add `pr-easy-toggle-files` feature

- source/features/highest-rated-comment.css
1. LINKED ISSUES: Closes #3778 
2. TEST URLS
- https://github.com/DefinitelyTyped/DefinitelyTyped/issues/48806#issuecomment-712654998
- https://github.com/leafo/sticky-kit/issues/201#issuecomment-263118559
- https://github.com/facebook/react/issues/13991#issuecomment-435587809
> Fix code discoloration caused by `highest-rated-comment`

- source/features/pr-easy-toggle-files.tsx
\-
2. TEST URLS:
[`277f47c` (#3227)](https://github.com/sindresorhus/refined-github/pull/3227/commits/277f47cdb4c10842d266745a12e3f5dfb29c6a44)
[`1d1f32e` (#3768)](https://github.com/sindresorhus/refined-github/pull/3768/commits/1d1f32ee4a53a8c03497ee574ab040f7c745805e)
3. SCREENSHOT:
\-
The initial PR #3750 was apparently not complete.
> Enable feature `pr-easy-toggle-files` on pages `isPRCommit`

- source/features/clean-dashboard.css
- source/features/reactions-avatars.css
Corrects some issues in #3798
2. TEST URLS:
Just the [main dashboard](https://github.com/) (see while logged in).
Also you need to have enabled Dark mode in [Settings](https://github.com/settings/appearance).
3. SCREENSHOTS:
<details>
<summary>With Dark mode (fixed)</summary>
_**Before**_
_**After**_
</details>
<details>
<summary>With Light mode (the same)</summary>
_**Before**_
_**After**_
</details>
Tested via custom CSS, with the following snippet:
```css
.dashboard .js-all-activity-header + div {
background-color: var(--color-bg-canvas);
border: 1px solid var(--color-border-primary);
}
```
> Fix a couple of issues with GitHub Dark mode

- source/features/more-dropdown.tsx
1. LINKED ISSUES:  Fixes #3811 
2. TEST URLS: https://github.com/sindresorhus/refined-github
> Fix `more-dropdown`

- source/features/clean-dashboard.css
- source/features/clean-dashboard.ts
- source/refined-github.ts
1. LINKED ISSUES: Closes #3816 
2. TEST URLS: [Dashboard](https://github.com)
3. SCREENSHOT:
<table>
<tr>
<td>Before
<td>After
<tr>
<td><img src="https://user-images.githubusercontent.com/46634000/102007479-b6842880-3d29-11eb-9d7c-0723b9e364c4.png">
<td><img src="https://user-images.githubusercontent.com/46634000/102007460-90f71f00-3d29-11eb-99f5-d310e980f420.png">
</table>
> Allow `clean-dashboard` to be disabled

- source/features/table-input.tsx
1. LINKED ISSUES: Closes #3823 
2. TEST URLS: -
> `table-input` can be closed by clicking anywhere else

- source/features/minimize-upload-bar.css
1. LINKED ISSUES: Fix #3834 
2. TEST URLS: Any page with a comment form.
> Fix missing upload button in `minimize-upload-bar`

- source/features/stop-pjax-loading-with-esc.tsx
Closes #3789
2. TEST URLS:
[https://github.com/dnicolson](https://github.com/dnicolson)
3. SCREENSHOT:
> Fix profile timeline bug caused by `stop-pjax-loading-with-esc`

- source/background.ts
- source/features/embed-gist-inline.tsx
Fixes #3889 
Test on https://github.com/hashicorp/vagrant/issues/11987 (warning, may cause browser to hang before this PR is merged)
> Avoid embedding large files in `embed-gist-inline`

- source/features/repo-wide-file-finder.tsx
1. LINKED ISSUES: Closes #3878 
2. TEST URLS:
- Hotkey should work:
- [Repo homepage](https://github.com/sindresorhus/refined-github)
- [Issues](https://github.com/sindresorhus/refined-github/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)
- [Releases](https://github.com/sindresorhus/refined-github/releases)
- [Single commit](https://github.com/sindresorhus/refined-github/commit/382b398cbaccbb5a3f7135cf873f1302daf5901e)
- Hotkey should NOT work:
- [PR files](https://github.com/sindresorhus/refined-github/pull/3883/files)
- [File finder](https://github.com/sindresorhus/refined-github/find/master)
- [Non-repo page](https://github.com/notifications)
> Enable `repo-wide-file-finder` on most repo pages

- source/features/conversation-filters.tsx
Fixes #3868 
2. TEST URLS:
https://github.com/sindresorhus/refined-github/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc
3. SCREENSHOT:
None
> Fix `conversation-filters`

- source/features/update-pr-from-base-branch.tsx
Fixes #3861 
2. TEST URLS:
#3855 
3. SCREENSHOT:
None
> Don't show `update-pr-from-base-branch` when there are conflicts

- source/features/bugs-tab.tsx
- source/github-helpers/search-query.ts
Fixes #3897 
2. TEST URLS:
Any non issue page
3. SCREENSHOT:
None
> Fix `bugs-tab` on non-issue pages

- source/features/separate-draft-pr-button.tsx
Fixes #3914
Tested in Chrome, but I did not have the problem in the first place.
@mischnic @MrChocolatine can you test this?
```sh
npm install
npm run build
```
@busches do you see any issues on GHE?
> Shorten and fix `separate-draft-pr-button`

- readme.md
2. TEST URLS: -
Just some minor fixes to the readme.
Closes #3970
> Meta: Fix small typos in readme

- contributing.md
- readme.md
Wip. Changed to better-looking more-CTA-like logos + added myself as Sindre suggested 💚
[link-chrome]: https://chrome.google.com/webstore/detail/refined-github/hlepfoohegkhhmjieoechaddaejaokhf "Version published on Chrome Web Store"
[link-firefox]: https://addons.mozilla.org/en-US/firefox/addon/refined-github-/ "Version published on Mozilla Add-ons"
[<img src="https://raw.githubusercontent.com/alrra/browser-logos/main/src/chrome/chrome_128x128.png" width="48" alt="Chrome" valign="middle">][link-chrome] [<img valign="middle" src="https://img.shields.io/chrome-web-store/v/hlepfoohegkhhmjieoechaddaejaokhf.svg?label=%20">][link-chrome] also compatible with [<img src="https://raw.githubusercontent.com/alrra/browser-logos/main/src/edge/edge_48x48.png" width="24" alt="Edge" …
> Update some readme links

- readme.md
- source/features/preview-markdown-result.css
- source/features/preview-markdown-result.tsx
- source/refined-github.ts
1. LINKED ISSUES: Closes #3711 
2. TEST URLS: https://github.com/sindresorhus/refined-github/edit/main/readme.md
3. SCREENSHOT:
Tested in Firefox and Chromium.
> Add `preview-markdown-result` feature

- package-lock.json
- package.json
- source/features/quick-repo-deletion.tsx
Closes #3984 
2. TEST URLS:
None
3. SCREENSHOT:
> Make `quick-repo-deletion` success message more helpful

- source/helpers/useless-comments.ts
- test/helpers.ts
2. TEST URLS: https://github.com/justinfrankel/licecap/issues/97 (bottom of the page)
I noticed a couple of useless comments that slipped through the cracks, namely "Dito" and "Followig".
> Detect more comments in `hide-useless-comments`

- source/features/hide-comments-faster.tsx
Closes #4032
2. TEST URLS:
Can you please explain what Tests this refers to? I checked readme.md and couldn't find anything. Happy to add these in though.
3. SCREENSHOT:
> Correctly display `hide-comments-faster` on small viewports

- source/features/quick-repo-deletion.tsx
None
2. TEST URLS:
Unnecessary
3. SCREENSHOT:
🤷‍♀️
> Add missing period to `quick-repo-deletion` success message

- source/features/action-used-by-link.tsx
- source/features/batch-open-conversations.tsx
- source/features/clone-branch.tsx
- source/features/conflict-marker.tsx
- source/features/faster-pr-diff-options.tsx
- source/features/first-published-tag-for-merged-pr.tsx
- source/features/git-checkout-pr.tsx
- source/features/hide-comments-faster.tsx
- source/features/highest-rated-comment.tsx
- source/features/highlight-non-default-base-branch.tsx
- source/features/pinned-issues-update-time.tsx
- source/features/release-download-count.tsx
- source/features/repo-age.tsx
- source/features/rgh-feature-descriptions.tsx
- source/features/submit-review-as-single-comment.tsx
- source/features/update-pr-from-base-branch.tsx
- source/features/user-local-time.tsx
- source/features/user-profile-follower-badge.tsx
- source/options-storage.ts
2. TEST URLS:
* [`batch-open-conversations`](https://github.com/sindresorhus/refined-github/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc)
* [`update-pr-from-base-branch`](https://github.com/sindresorhus/refined-github/pull/4023) (only while it's still open)
Changed classes:
* `.text-gray-dark` → `.color-text-primary`
* `.text-gray` → `.color-text-secondary`
* `.text-gray-light` → `.color-text-tertiary`
This should have been part of #4021 but I wasn't fast enough, my bad.
> Fix more features dependent on `.link-gray`, `.text-gray` and their variants

- source/features/night-not-found.css
- source/refined-github.ts
> Add `night-not-found` feature

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/change_request.md
- .github/ISSUE_TEMPLATE/discussion.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
These explains better what we request and why. Also specify REAL URL because many unnecessarily post incomprehensible fake URLs for no good reason.
> Meta: Update issue/PR templates

- package-lock.json
- package.json
- source/features/next-scheduled-github-action.tsx
Fixes #4050 
* https://github.com/sindresorhus/refined-github/actions
* https://github.com/sindresorhus/refined-github/actions/workflows/release.yml
* https://github.com/microsoft/TypeScript/actions
This PR:
- Fixes the selector
- Adds a tooltip on the list item for situations like this:
> Restore `next-scheduled-github-action` + show if title overflows

- source/features/conversation-filters.tsx
Fixes #4055 
- https://github.com/sindresorhus/refined-github/issues
- https://github.com/sindresorhus/refined-github/pulls
<table>
<tr>
<th>Before
<th>After
<tr>
<td>
<td>
</table>
> Fix alignment of `conversation-filters`

- source/github-helpers/index.ts
- source/helpers/dom-utils.ts
- test/helpers.ts
Follow-up of https://github.com/sindresorhus/refined-github/pull/4023#discussion_r589125189.
> Meta: Replace `getScopedSelector()` with `:is()`

- source/features/hide-watch-and-fork-count.css
Fixes #4073 
- the root of a repo that you own
- the root of a repo that you don't own
<table>
<tr>
<th>Before
<th>After
<tr>
<td valign="top">
</td>
<td valign="top">
</td>
</table>
> Restore Fork button roundedness in `hide-watch-and-fork-count`

- source/features/conversation-activity-filter.tsx
- source/features/index.tsx
Fix #4067
See https://github.com/sindresorhus/refined-github/issues/4067#issuecomment-792273884 for details
1. Open issue https://github.com/sindresorhus/refined-github/issues/4067
2. Go to issues tab
3. Open any issue again
None
P.S. maybe we should rewrite all `onetime` usage for `selector-observer` with `observer.abort()`?
> Avoid `conversation-activity-filter` duplicates

- source/features/list-prs-for-file.tsx
Closes #4056 
https://github.com/sindresorhus/refined-github/blob/main/source/refined-github.ts
> Add tooltips with PR titles in `list-prs-for-file`

- source/github-events/on-pr-merge-panel-open.ts
- source/globals.d.ts
Fixes #3932 
1. Type something in the comment box at the bottom (without sending it)
2. Soft-reload the page
3. `clear-pr-merge-commit-message` and `suggest-commit-title-limit` should NOT produce errors in the console
Tested in Firefox & Chromium.
> Fix console errors on some PR pages

- source/features/preview-hidden-comments.tsx
Fixes #3647 
https://github.com/sindresorhus/refined-github/issues/3647
<table>
<tr>
<th>Before
<th>After
<tr>
<td>
<td>
</table>
> Fix `preview-hidden-comments` for resolved and outdated comments

- package-lock.json
- package.json
- source/features/collapse-markdown-sections.ts
Possibly wait for fregante/github-url-detection#64
https://github.com/lukesampson/scoop/wiki
> Enable `collapse-markdown-sections` on wikis

- source/features/show-names.tsx
Any PR with review comments, e.g. https://github.com/sindresorhus/refined-github/pull/4023
<table>
<tr>
<th>Before
<th>After
<tr>
<td>
<td>
</table>
> Fix alignment of `show-names` in review comments

- source/features/clean-conversation-headers.tsx
Closes #3808 
- [Open PR (default base branch)](https://github.com/sindresorhus/refined-github/pull/4089)
- [Open PR (non-default base branch)](https://github.com/Kenshin/simpread/pull/698)
- [Merged PR (same author)](https://github.com/sindresorhus/refined-github/pull/3402)
- [Merged PR (different author)](https://github.com/sindresorhus/refined-github/pull/3227)
- [Merged PR (different author, non-default base branch)](https://github.com/sindresorhus/refined-github/pull/3150)
<table>
<tr>
<th>
<th>Before
<th>After
<tr>
<th>Open PR (default branch)
<td valign="middle" width="50%">
<td valign="middle" width="50%">
<tr>
<td>Open PR (non-default branch)
<td valign="middle" width="50%">
<td valign="middle" width="50%">
<tr>
<th>Merged PR (same author)
<td valign="middle" width="50%">
<td …
> Restore base branch name in `clean-conversation-headers`

- source/features/raw-file-link.tsx
Fixes #4143 
We need to wait for GitHubURL to be fixed in order to test the PR.
However this is working
> Disable pjax on `raw-file-link`

- source/features/bugs-tab.tsx
Fixes #4164 
Any Bug issue
https://github.com/sindresorhus/refined-github/issues/4183
> Highlight `bugs-tab` on bug issues

- readme.md
- source/features/clean-header-search-field.tsx
- source/features/sort-conversations-by-update-time.tsx
- source/refined-github.ts
Closes #4095 
* Search field should be cleared (**even when the page is reloaded**):
* https://github.com/sindresorhus/refined-github/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Abug
* https://github.com/pulls?q=is%3Apr+is%3Aopen+author%3Afregante+archived%3Afalse+sort%3Aupdated-desc
* Search field should NOT be cleared:
* https://github.com/search?q=search
* https://github.com/sindresorhus/refined-github/search?q=search
> Add `clean-header-search-field` feature

- source/features/swap-branches-on-compare.tsx
Closes #4223 
https://github.com/sindresorhus/refined-github/compare/main...Slash/slash
> Restore `swap-branches-on-compare` feature

- source/features/batch-mark-files-as-viewed.tsx
Fixes #4226
https://github.com/sindresorhus/refined-github/pull/4100
Tested
> Fix `batch-mark-files-as-viewed` shift-click

- source/features/bugs-tab.tsx
https://github.com/sabrogden/Ditto/issues/102
Just fixes the condition to avoid a console error
> Fix console error in `bugs-tab`

- source/features/view-markdown-source.tsx
Fix #4239 
* https://github.com/sindresorhus/refined-github/blob/main/privacy-policy.md
* https://github.com/yargs/yargs/blob/master/docs/api.md
> Fix position of `view-markdown-source`

- readme.md
- source/features/forked-to.css
- source/features/hide-watch-and-fork-count.css
Re https://github.com/sindresorhus/refined-github/issues/4197#issuecomment-816628465
> Hide the fork count only on smaller screens

- source/features/remove-label-faster.tsx
> Restore `remove-label-faster` feature

- source/features/ci-link.css
- source/features/ci-link.tsx
Fixes #4260
Here and I tested on private
> Restore `ci-link` feature

- source/features/edit-readme.tsx
Fix #4269
- With TOC: https://github.com/jsxtools/cqfill
- Without TOC: https://github.com/theam/aws-lambda-haskell-runtime
- With TOC
Before:
After: 
- Without TOC: Same as #4208
> Restore and clean `edit-readme`

- source/features/view-last-pr-deployment.tsx
- source/refined-github.css
> Improve spacing of PR header buttons

- source/features/ci-link.tsx
Follows https://github.com/sindresorhus/refined-github/pull/4267
Fixes https://github.com/sindresorhus/refined-github/pull/4267#issuecomment-826728022
cc @gustavkj 
Untested because I'm not a GHE user
> Restore `ci-link` on Enterprise

- source/features/close-out-of-view-modals.tsx
- source/features/index.tsx
Closes #4287 
Addresses https://github.com/sindresorhus/refined-github/pull/4276#issuecomment-828204951
> Meta: Improve logs

- source/features/faster-pr-diff-options.tsx
Fix #4298
https://github.com/ShareX/ShareX/compare/v13.4.0...master#files_bucket
> Preserve URL hash in `faster-pr-diff-options`

- source/features/rgh-linkify-features.tsx
Resolves #4284 
https://github.com/sindresorhus/refined-github/releases
> Meta: Extend `rgh-linkify-features` to the releases tab

- source/features/user-local-time.tsx
> Add day of week to `user-local-time`

- source/features/edit-readme.tsx
https://github.com/sindresorhus/refined-github/tree/main/build
None
> Don't run `edit-readme` if no readme exists

- package-lock.json
- package.json
- source/features/index.tsx
This reverts commit cdebcef8dc30c76cf4fdd4cbea005272704f761f.
> Revert "Load features faster (#4316)" 

- package-lock.json
- package.json
- source/features/index.tsx
Tested takes between **0.710205078125** ms and 18.29931640625 ms 
Follows https://github.com/sindresorhus/refined-github/pull/4316#issuecomment-838423309
Fixes https://github.com/sindresorhus/refined-github/issues/4343
> Load features faster /2

- source/features/dim-bots.css
- source/features/tags-on-commits-list.tsx
Fixes #4318 (first attempt was #4321)
https://github.com/fregante/github-url-detection/commits/master?after=e58ce98ffd6a45822d035598eda8f699e1839f06+1&branch=master
<table>
<tr>
<th>Before
<td>
<tr>
<th>After
<td>
</table>
> Don't hide tagged commits in `dim-bots`

- source/features/default-branch-button.css
- source/features/default-branch-button.tsx
Fixes #4240 
Go to https://github.com/sindresorhus/refined-github/tree/hotfix, click on the branch switcher and select an option above the readme header.
https://user-images.githubusercontent.com/46634000/119224239-c89a9c00-bafd-11eb-9f2b-3a97987426e5.mp4
<p>&nbsp;</p>
The culprit:
> Fix branch switcher conflict with `default-branch-button`

- source/features/user-profile-follower-badge.tsx
Fixes #4388 
https://github.com/wizardforcel
Before
After
I also dropped the pre-refresh code
> Fix `user-profile-follower-badge` position

- source/features/conflict-marker.tsx
- source/features/hide-issue-list-autocomplete.tsx
Fixes #4391
Open issues
https://github.com/the-tcpdump-group/libpcap/milestone/1
No open issues.
https://github.com/sindresorhus/eslint-plugin-unicorn/milestone/1
> Fix `conflict-marker` on milestone pages

- package-lock.json
- package.json
Includes https://github.com/fregante/content-scripts-register-polyfill/pull/15
Fixes #4319 
~~Testing~~ _Tested!_
- Chrome was affected, now it works correctly
- Firefox was not affected, now it still works
- Safari was not affected, now it still works
> Avoid duplicate injection on GitHub Enterprise

- source/github-widgets/notice-bar.tsx
Fixes #4404 
1. Starting on this issue
2. Visit https://github.com/sindresorhus/refined-github/tree/list-pr-for-branch
3. Go back
4. Click the link again
> Fix `comments-time-machine-links` duplication

- readme.md
- source/features/list-pr-for-branch.tsx
- source/features/list-prs-for-file.tsx
- source/features/show-associated-branch-prs-on-fork.tsx
- source/refined-github.ts
Closes #3713
https://github.com/yakov116/TestR/commits/yakov116-patch-2
https://github.com/yakov116/TestR/commits/yakov116-patch-3
https://github.com/sindresorhus/refined-github/commits/list-pr-for-branch
> Add `list-pr-for-branch` feature

- source/refined-github.ts
Will be disabled via hotfix
Re https://github.com/sindresorhus/refined-github/issues/4238#issuecomment-851004971
> Meta: Re enable `clean-conversation-sidebar`

- source/features/avoid-accidental-submissions.tsx
Closes #4461
Any PR you can merge, I used my private test repo:
https://github.com/darkred/test/pull/5
> Enable `avoid-accidental-submissions` when merging PRs

- source/features/align-issue-labels.css
- source/features/center-reactions-popup.css
- source/features/ci-link.tsx
- source/features/clean-conversation-headers.css
- source/features/clean-dashboard.css
- source/features/clean-footer.css
- source/features/clean-mergeability-box.css
- source/features/deep-reblame.css
- source/features/deprioritize-marketplace-link.tsx
- source/features/easier-pr-sha-copy.css
- source/features/extend-diff-expander.css
- source/features/extend-status-labels.css
- source/features/hide-useless-comments.css
- source/features/mark-merge-commits-in-list.css
- source/features/more-dropdown.tsx
- source/features/parse-backticks.tsx
- source/features/pr-approvals-count.css
- source/features/table-input.css
- source/features/useful-not-found-page.tsx
- source/features/wait-for-build.css
- source/refined-github.css
Implements https://github.com/sindresorhus/refined-github/issues/4008#issuecomment-803169740.
> Meta: Add issue numbers to GHE comments

- source/refined-github.css
Fixes #4328 
[Link to test this fix : TACC/Core-CMS@c8b7cbe](https://github.com/TACC/Core-CMS/commit/c8b7cbe270ad083dd11d3f81da35cb281fe3d56f)
[Link to test that it doesn't break 1639](https://github.com/webpack/webpack/pull/6446/files#diff-4cb0a7248ed91703f66f261958573976e311153c7273acaa2f6960be6dd84e98)
Before:
After:
How:
Added overwrite to shift the table by `text-align: center;` to `text-align: left;`
> Fix: Submodule diffs are misaligned

- .github/workflows/features.yml
- .github/workflows/new-feature-checker.yml
- build/readme-parser.ts
- webpack.config.ts
Fixes https://github.com/sindresorhus/refined-github/issues/4493
Unblocks https://github.com/sindresorhus/refined-github/issues/4320
We have a few checks for features as part of the local build. This has led to some confusion, so I think it's best to move the checks to CI. This also allows the build improvements described in https://github.com/sindresorhus/refined-github/issues/4320
> Meta: Add workflow that verifies new feature PRs

- source/features/clean-dashboard.css
- source/features/linkify-labels-on-dashboard.tsx
Fix #4491
I figured the selectors may be a little generic, suggestions welcome:
TODO: better title?
Before:
After:
> Restore `clean-dashboard`

- source/features/avoid-accidental-submissions.tsx
Closes #4525 
- Existing issue: https://github.com/sindresorhus/refined-github/pull/4525
- Existing PRs (of any state): https://github.com/sindresorhus/refined-github/pull/4528
None
> Disable `avoid-accidental-submissions` when editing the title of existing PRs
